toxcore/net_crypto.h File Reference
#include `DHT.h`
*
#include `LAN_discovery.h`
*
#include `TCP_connection.h`
*
#include <pthread.h>
*
Data Structures
struct Packet_Data
struct Packets_Array
struct Crypto_Connection
struct New_Connection
struct Net_Crypto
Macros
#define CRYPTO_CONN_NO_CONNECTION 0
#define CRYPTO_CONN_COOKIE_REQUESTING 1
#define CRYPTO_CONN_HANDSHAKE_SENT 2
#define CRYPTO_CONN_NOT_CONFIRMED 3
#define CRYPTO_CONN_ESTABLISHED 4
#define CRYPTO_PACKET_BUFFER_SIZE 16384 /* Must be a power of 2 */
#define CRYPTO_PACKET_MIN_RATE 8.0
#define CRYPTO_MIN_QUEUE_LENGTH 64
#define MAX_CRYPTO_PACKET_SIZE 1400
#define CRYPTO_DATA_PACKET_MIN_SIZE (1 + sizeof(uint16_t) + (sizeof(uint32_t) + sizeof(uint32_t)) + crypto_box_MACBYTES)
#define MAX_CRYPTO_DATA_SIZE (MAX_CRYPTO_PACKET_SIZE - CRYPTO_DATA_PACKET_MIN_SIZE)
#define CRYPTO_SEND_PACKET_INTERVAL 1000
#define MAX_NUM_SENDPACKET_TRIES 8
#define UDP_DIRECT_TIMEOUT ((MAX_NUM_SENDPACKET_TRIES * CRYPTO_SEND_PACKET_INTERVAL) / 1000)
#define PACKET_ID_PADDING 0 /* Denotes padding */
#define PACKET_ID_REQUEST 1 /* Used to request unreceived packets */
#define PACKET_ID_KILL 2 /* Used to kill connection */
#define CRYPTO_RESERVED_PACKETS 16
#define MAX_TCP_CONNECTIONS 64
#define MAX_TCP_RELAYS_PEER 4
#define PACKET_ID_LOSSY_RANGE_START 192
#define PACKET_ID_LOSSY_RANGE_SIZE 63
#define CRYPTO_MAX_PADDING 8 /* All packets will be padded a number of bytes based on this number. */
#define CONGESTION_QUEUE_ARRAY_SIZE 24
#define DEFAULT_PING_CONNECTION 200
Functions
void new_connection_handler (Net_Crypto *c, int(*new_connection_callback)(void *object, New_Connection *n_c), void *object)
int accept_crypto_connection (Net_Crypto *c, New_Connection *n_c)
int new_crypto_connection (Net_Crypto *c, const uint8_t *real_public_key, const uint8_t *dht_public_key)
int set_direct_ip_port (Net_Crypto *c, int crypt_connection_id, IP_Port ip_port, _Bool connected)
int connection_status_handler (const Net_Crypto *c, int crypt_connection_id, int(*connection_status_callback)(void *object, int id, uint8_t status), void *object, int id)
int connection_data_handler (const Net_Crypto *c, int crypt_connection_id, int(*connection_data_callback)(void *object, int id, uint8_t *data, uint16_t length), void *object, int id)
int connection_lossy_data_handler (Net_Crypto *c, int crypt_connection_id, int(*connection_lossy_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object, int id)
int nc_dht_pk_callback (Net_Crypto *c, int crypt_connection_id, void(*function)(void *data, int32_t number, const uint8_t *dht_public_key), void *object, uint32_t number)
uint32_t crypto_num_free_sendqueue_slots (const Net_Crypto *c, int crypt_connection_id)
_Bool max_speed_reached (Net_Crypto *c, int crypt_connection_id)
int64_t write_cryptpacket (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length, uint8_t congestion_control)
int cryptpacket_received (Net_Crypto *c, int crypt_connection_id, uint32_t packet_number)
int send_lossy_cryptpacket (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length)
int add_tcp_relay_peer (Net_Crypto *c, int crypt_connection_id, IP_Port ip_port, const uint8_t *public_key)
int add_tcp_relay (Net_Crypto *c, IP_Port ip_port, const uint8_t *public_key)
int get_random_tcp_con_number (Net_Crypto *c)
int send_tcp_onion_request (Net_Crypto *c, unsigned int TCP_conn_number, const uint8_t *data, uint16_t length)
unsigned int copy_connected_tcp_relays (Net_Crypto *c, Node_format *tcp_relays, uint16_t num)
int crypto_kill (Net_Crypto *c, int crypt_connection_id)
unsigned int crypto_connection_status (const Net_Crypto *c, int crypt_connection_id, _Bool *direct_connected, unsigned int *online_tcp_relays)
void new_keys (Net_Crypto *c)
void save_keys (const Net_Crypto *c, uint8_t *keys)
void load_secret_key (Net_Crypto *c, const uint8_t *sk)
Net_Crypto * new_net_crypto (DHT *dht, TCP_Proxy_Info *proxy_info)
uint32_t crypto_run_interval (const Net_Crypto *c)
void do_net_crypto (Net_Crypto *c)
void kill_net_crypto (Net_Crypto *c)
Macro Definition Documentation
#define CONGESTION_QUEUE_ARRAY_SIZE 24
Definition at line 83 of file net_crypto.h.
Referenced by send_crypto_packets().
#define CRYPTO_CONN_COOKIE_REQUESTING 1
Definition at line 33 of file net_crypto.h.
Referenced by handle_new_connection_handshake(), handle_packet_connection(), kill_timedout(), and new_crypto_connection().
#define CRYPTO_CONN_ESTABLISHED 4
Definition at line 36 of file net_crypto.h.
Referenced by crypto_kill(), do_tcp(), handle_data_packet_helper(), handle_packet_connection(), kill_timedout(), send_crypto_packets(), and write_cryptpacket().
#define CRYPTO_CONN_HANDSHAKE_SENT 2
Definition at line 34 of file net_crypto.h.
Referenced by handle_new_connection_handshake(), handle_packet_connection(), and kill_timedout().
#define CRYPTO_CONN_NO_CONNECTION 0
Definition at line 32 of file net_crypto.h.
Referenced by accept_crypto_connection(), create_crypto_connection(), crypt_connection_id_not_valid(), crypto_connection_status(), getcryptconnection_id(), kill_timedout(), new_crypto_connection(), and wipe_crypto_connection().
#define CRYPTO_CONN_NOT_CONFIRMED 3
Definition at line 35 of file net_crypto.h.
Referenced by accept_crypto_connection(), handle_data_packet_helper(), handle_new_connection_handshake(), handle_packet_connection(), kill_timedout(), and send_crypto_packets().
#define CRYPTO_DATA_PACKET_MIN_SIZE (1 + sizeof(uint16_t) + (sizeof(uint32_t) + sizeof(uint32_t)) + crypto_box_MACBYTES)
Definition at line 50 of file net_crypto.h.
Referenced by handle_data_packet_helper().
#define CRYPTO_MAX_PADDING 8 /* All packets will be padded a number of bytes based on this number. */
Definition at line 79 of file net_crypto.h.
Referenced by send_data_packet_helper().
#define CRYPTO_MIN_QUEUE_LENGTH 64
Definition at line 45 of file net_crypto.h.
Referenced by accept_crypto_connection(), new_crypto_connection(), and send_crypto_packets().
#define CRYPTO_PACKET_BUFFER_SIZE 16384 /* Must be a power of 2 */
Definition at line 39 of file net_crypto.h.
Referenced by add_data_end_of_buffer(), add_data_to_buffer(), clear_buffer(), clear_buffer_until(), crypto_num_free_sendqueue_slots(), generate_request_packet(), get_data_pointer(), handle_request_packet(), read_data_beg_buffer(), and set_buffer_end().
#define CRYPTO_PACKET_MIN_RATE 8.0
Definition at line 42 of file net_crypto.h.
Referenced by accept_crypto_connection(), new_crypto_connection(), and send_crypto_packets().
#define CRYPTO_RESERVED_PACKETS 16
Definition at line 70 of file net_crypto.h.
Referenced by handle_data_packet_helper(), and write_cryptpacket().
#define CRYPTO_SEND_PACKET_INTERVAL 1000
Definition at line 56 of file net_crypto.h.
Referenced by new_net_crypto(), and send_crypto_packets().
#define DEFAULT_PING_CONNECTION 200
Definition at line 86 of file net_crypto.h.
Referenced by accept_crypto_connection(), and new_crypto_connection().
#define MAX_CRYPTO_DATA_SIZE (MAX_CRYPTO_PACKET_SIZE - CRYPTO_DATA_PACKET_MIN_SIZE)
Definition at line 53 of file net_crypto.h.
Referenced by m_send_message_generic(), send_custom_lossless_packet(), send_custom_lossy_packet(), send_data_packet_helper(), send_file_control_packet(), send_lossless_packet(), send_lossy_cryptpacket(), send_lossy_group_peer(), send_packet_group_peer(), send_peers(), send_request_packet(), and write_cryptpacket_id().
#define MAX_CRYPTO_PACKET_SIZE 1400
Definition at line 48 of file net_crypto.h.
Referenced by handle_data_packet(), handle_data_packet_helper(), handle_packet_connection(), new_temp_packet(), send_data_packet(), START_TEST(), tcp_data_callback(), tcp_oob_callback(), and udp_handle_packet().
#define MAX_NUM_SENDPACKET_TRIES 8
Definition at line 60 of file net_crypto.h.
Referenced by kill_timedout().
#define MAX_TCP_CONNECTIONS 64
Definition at line 72 of file net_crypto.h.
#define MAX_TCP_RELAYS_PEER 4
Definition at line 73 of file net_crypto.h.
#define PACKET_ID_KILL 2 /* Used to kill connection */
Definition at line 67 of file net_crypto.h.
Referenced by handle_data_packet_helper(), and send_kill_packet().
#define PACKET_ID_LOSSY_RANGE_SIZE 63
Definition at line 77 of file net_crypto.h.
Referenced by handle_data_packet_helper(), send_custom_lossy_packet(), and send_lossy_cryptpacket().
#define PACKET_ID_LOSSY_RANGE_START 192
Definition at line 76 of file net_crypto.h.
Referenced by handle_custom_lossy_packet(), handle_data_packet_helper(), m_callback_rtp_packet(), send_custom_lossy_packet(), send_lossy_cryptpacket(), tox_friend_send_lossy_packet(), and write_cryptpacket().
#define PACKET_ID_PADDING 0 /* Denotes padding */
Definition at line 65 of file net_crypto.h.
Referenced by handle_data_packet_helper(), and send_data_packet_helper().
#define PACKET_ID_REQUEST 1 /* Used to request unreceived packets */
Definition at line 66 of file net_crypto.h.
Referenced by generate_request_packet(), handle_data_packet_helper(), and handle_request_packet().
#define UDP_DIRECT_TIMEOUT ((MAX_NUM_SENDPACKET_TRIES * CRYPTO_SEND_PACKET_INTERVAL) / 1000)
Definition at line 63 of file net_crypto.h.
Referenced by crypto_connection_status(), and set_direct_ip_port().
Function Documentation
int accept_crypto_connection (Net_Crypto * c, New_Connection * n_c)
Definition at line 1570 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, New_Connection::cookie, COOKIE_LENGTH, New_Connection::cookie_length, create_crypto_connection(), create_send_handshake(), CRYPTO_CONN_NO_CONNECTION, CRYPTO_CONN_NOT_CONFIRMED, crypto_connection_add_source(), Net_Crypto::crypto_connections, CRYPTO_MIN_QUEUE_LENGTH, CRYPTO_PACKET_MIN_RATE, DEFAULT_PING_CONNECTION, Crypto_Connection::dht_public_key, New_Connection::dht_public_key, encrypt_precompute(), getcryptconnection_id(), kill_tcp_connection_to(), new_tcp_connection_to(), Crypto_Connection::packet_send_rate, Crypto_Connection::packets_left, Crypto_Connection::peersessionpublic_key, New_Connection::peersessionpublic_key, Crypto_Connection::public_key, New_Connection::public_key, random_nonce(), Crypto_Connection::recv_nonce, New_Connection::recv_nonce, Crypto_Connection::rtt_time, Crypto_Connection::sent_nonce, Crypto_Connection::sessionpublic_key, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, New_Connection::source, Crypto_Connection::status, Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by handle_new_connections().
{
    if (getcryptconnection_id(c, n_c->public_key) != -1)
        return -1;
    int crypt_connection_id = create_crypto_connection(c);
    if (crypt_connection_id == -1)
        return -1;
    Crypto_Connection *conn = &c->crypto_connections[crypt_connection_id
      ];
    if (n_c->cookie_length != COOKIE_LENGTH)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int connection_number_tcp = new_tcp_connection_to(c->
      tcp_c, n_c->dht_public_key, crypt_connection_id);
    pthread_mutex_unlock(&c->tcp_mutex);
    if (connection_number_tcp == -1)
        return -1;
    conn->connection_number_tcp = connection_number_tcp;
    memcpy(conn->public_key, n_c->public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(conn->recv_nonce, n_c->recv_nonce, crypto_box_NONCEBYTES);
    memcpy(conn->peersessionpublic_key, n_c->
      peersessionpublic_key, crypto_box_PUBLICKEYBYTES);
    random_nonce(conn->sent_nonce);
    crypto_box_keypair(conn->sessionpublic_key, conn->
      sessionsecret_key);
    encrypt_precompute(conn->peersessionpublic_key, conn->
      sessionsecret_key, conn->shared_key);
    conn->status = CRYPTO_CONN_NOT_CONFIRMED;
    if (create_send_handshake(c, crypt_connection_id, n_c->
      cookie, n_c->dht_public_key) != 0) {
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        conn->status = CRYPTO_CONN_NO_CONNECTION;
        return -1;
    }
    memcpy(conn->dht_public_key, n_c->dht_public_key, crypto_box_PUBLICKEYBYTES
      );
    conn->packet_send_rate = CRYPTO_PACKET_MIN_RATE;
    conn->packets_left = CRYPTO_MIN_QUEUE_LENGTH;
    conn->rtt_time = DEFAULT_PING_CONNECTION;
    crypto_connection_add_source(c, crypt_connection_id, n_c->
      source);
    return crypt_connection_id;
}
int add_tcp_relay (Net_Crypto * c, IP_Port ip_port, const uint8_t * public_key)
Definition at line 1794 of file net_crypto.c.
References add_tcp_relay_global(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by do_messenger(), tcp_relay_node_callback(), and tox_add_tcp_relay().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = add_tcp_relay_global(c->tcp_c, ip_port,
      public_key);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
int add_tcp_relay_peer (Net_Crypto * c, int crypt_connection_id, IP_Port ip_port, const uint8_t * public_key)
Definition at line 1776 of file net_crypto.c.
References add_tcp_relay_connection(), Crypto_Connection::connection_number_tcp, get_crypto_connection(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by connect_to_saved_tcp_relays(), and friend_add_tcp_relay().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = add_tcp_relay_connection(c->tcp_c, conn->
      connection_number_tcp, ip_port, public_key);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
int connection_data_handler (const Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, uint8_t *data, uint16_t length) connection_data_callback, void * object, int id)
Definition at line 1914 of file net_crypto.c.
References Crypto_Connection::connection_data_callback, Crypto_Connection::connection_data_callback_id, Crypto_Connection::connection_data_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_data_callback = connection_data_callback;
    conn->connection_data_callback_object = object;
    conn->connection_data_callback_id = id;
    return 0;
}
int connection_lossy_data_handler (Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, const uint8_t *data, uint16_t length) connection_lossy_data_callback, void * object, int id)
Definition at line 1936 of file net_crypto.c.
References Crypto_Connection::connection_lossy_data_callback, Crypto_Connection::connection_lossy_data_callback_id, Crypto_Connection::connection_lossy_data_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_lossy_data_callback = connection_lossy_data_callback;
    conn->connection_lossy_data_callback_object = object;
    conn->connection_lossy_data_callback_id =
      id;
    return 0;
}
int connection_status_handler (const Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, uint8_t status) connection_status_callback, void * object, int id)
Definition at line 1892 of file net_crypto.c.
References Crypto_Connection::connection_status_callback, Crypto_Connection::connection_status_callback_id, Crypto_Connection::connection_status_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_status_callback = connection_status_callback;
    conn->connection_status_callback_object = object;
    conn->connection_status_callback_id = id;
    return 0;
}
unsigned int copy_connected_tcp_relays (Net_Crypto * c, Node_format * tcp_relays, uint16_t num)
Definition at line 1839 of file net_crypto.c.
References Net_Crypto::tcp_c, tcp_copy_connected_relays(), and Net_Crypto::tcp_mutex.
Referenced by messenger_save(), populate_path_nodes_tcp(), send_dhtpk_announce(), and send_relays().
{
    if (num == 0)
        return 0;
    pthread_mutex_lock(&c->tcp_mutex);
    unsigned int ret = tcp_copy_connected_relays(c->
      tcp_c, tcp_relays, num);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
unsigned int crypto_connection_status (const Net_Crypto * c, int crypt_connection_id, _Bool * direct_connected, unsigned int * online_tcp_relays)
Definition at line 2364 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, CRYPTO_CONN_NO_CONNECTION, Crypto_Connection::direct_lastrecv_time, get_crypto_connection(), Crypto_Connection::status, Net_Crypto::tcp_c, tcp_connection_to_online_tcp_relays(), UDP_DIRECT_TIMEOUT, and unix_time().
Referenced by do_tcp(), m_get_friend_connectionstatus(), and send_packet_to().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return CRYPTO_CONN_NO_CONNECTION;
    if (direct_connected) {
        *direct_connected = 0;
        if ((UDP_DIRECT_TIMEOUT + conn->direct_lastrecv_time) >
      unix_time())
            *direct_connected = 1;
    }
    if (online_tcp_relays) {
        *online_tcp_relays = tcp_connection_to_online_tcp_relays(c->
      tcp_c, conn->connection_number_tcp);
    }
    return conn->status;
}
int crypto_kill (Net_Crypto * c, int crypt_connection_id)
Definition at line 2323 of file net_crypto.c.
References bs_list_remove(), clear_buffer(), clear_temp_packet(), Crypto_Connection::connection_number_tcp, Net_Crypto::connection_use_counter, Net_Crypto::connections_mutex, CRYPTO_CONN_ESTABLISHED, get_crypto_connection(), Crypto_Connection::ip_port, Net_Crypto::ip_port_list, kill_tcp_connection_to(), Crypto_Connection::recv_array, Crypto_Connection::send_array, send_kill_packet(), Crypto_Connection::status, Net_Crypto::tcp_c, Net_Crypto::tcp_mutex, and wipe_crypto_connection().
Referenced by connection_kill(), dht_pk_callback(), do_friend_connections(), kill_friend_connection(), and kill_net_crypto().
{
    while (1) { /* TODO: is this really the best way to do this? */
        pthread_mutex_lock(&c->connections_mutex);
        if (!c->connection_use_counter) {
            break;
        }
        pthread_mutex_unlock(&c->connections_mutex);
    }
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    int ret = -1;
    if (conn) {
        if (conn->status == CRYPTO_CONN_ESTABLISHED)
            send_kill_packet(c, crypt_connection_id);
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        bs_list_remove(&c->ip_port_list, (uint8_t *)&conn->
      ip_port, crypt_connection_id);
        clear_temp_packet(c, crypt_connection_id);
        clear_buffer(&conn->send_array);
        clear_buffer(&conn->recv_array);
        ret = wipe_crypto_connection(c, crypt_connection_id);
    }
    pthread_mutex_unlock(&c->connections_mutex);
    return ret;
}
uint32_t crypto_num_free_sendqueue_slots (const Net_Crypto * c, int crypt_connection_id)
Definition at line 2196 of file net_crypto.c.
References CRYPTO_PACKET_BUFFER_SIZE, get_crypto_connection(), num_packets_array(), Crypto_Connection::packets_left, and Crypto_Connection::send_array.
Referenced by do_reqchunk_filecb(), and file_data().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return 0;
    uint32_t max_packets = CRYPTO_PACKET_BUFFER_SIZE -
      num_packets_array(&conn->send_array);
    if (conn->packets_left < max_packets) {
        return conn->packets_left;
    } else {
        return max_packets;
    }
}
uint32_t crypto_run_interval (const Net_Crypto * c)
Definition at line 2491 of file net_crypto.c.
References Net_Crypto::current_sleep_time.
Referenced by messenger_run_interval().
{
    return c->current_sleep_time;
}
int cryptpacket_received (Net_Crypto * c, int crypt_connection_id, uint32_t packet_number)
Definition at line 2262 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, get_crypto_connection(), num, and Crypto_Connection::send_array.
Referenced by friend_received_packet().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint32_t num = conn->send_array.buffer_end - conn->
      send_array.buffer_start;
    uint32_t num1 = packet_number - conn->send_array.buffer_start;
    if (num < num1) {
        return 0;
    } else {
        return -1;
    }
}
void do_net_crypto (Net_Crypto * c)
Definition at line 2497 of file net_crypto.c.
References do_tcp(), kill_timedout(), send_crypto_packets(), and unix_time_update().
Referenced by do_messenger().
{
    unix_time_update();
    kill_timedout(c);
    do_tcp(c);
    send_crypto_packets(c);
}
int get_random_tcp_con_number (Net_Crypto * c)
Definition at line 1810 of file net_crypto.c.
References get_random_tcp_onion_conn_number(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by random_nodes_path_onion().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = get_random_tcp_onion_conn_number(c->
      tcp_c);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
void kill_net_crypto (Net_Crypto * c)
Definition at line 2505 of file net_crypto.c.
References bs_list_free(), Net_Crypto::connections_mutex, Net_Crypto::crypto_connections_length, crypto_kill(), Net_Crypto::dht, i, Net_Crypto::ip_port_list, kill_tcp_connections(), DHT::net, NET_PACKET_COOKIE_REQUEST, NET_PACKET_COOKIE_RESPONSE, NET_PACKET_CRYPTO_DATA, NET_PACKET_CRYPTO_HS, networking_registerhandler(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by kill_messenger(), kill_onions(), and new_messenger().
{
    uint32_t i;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        crypto_kill(c, i);
    }
    pthread_mutex_destroy(&c->tcp_mutex);
    pthread_mutex_destroy(&c->connections_mutex);
    kill_tcp_connections(c->tcp_c);
    bs_list_free(&c->ip_port_list);
    networking_registerhandler(c->dht->net,
      NET_PACKET_COOKIE_REQUEST, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_COOKIE_RESPONSE, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_CRYPTO_HS, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_CRYPTO_DATA, NULL, NULL);
    memset(c, 0, sizeof(Net_Crypto));
    free(c);
}
void load_secret_key (Net_Crypto * c, const uint8_t * sk)
Definition at line 2405 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by messenger_load_state_callback(), and tox_new().
{
    memcpy(c->self_secret_key, sk, crypto_box_SECRETKEYBYTES);
    crypto_scalarmult_curve25519_base(c->self_public_key, c->
      self_secret_key);
}
_Bool max_speed_reached (Net_Crypto * c, int crypt_connection_id)
Definition at line 2188 of file net_crypto.c.
References reset_max_speed_reached().
Referenced by do_reqchunk_filecb().
{
    return reset_max_speed_reached(c, crypt_connection_id) != 0;
}
int nc_dht_pk_callback (Net_Crypto * c, int crypt_connection_id, void(*)(void *data, int32_t number, const uint8_t *dht_public_key) function, void * object, uint32_t number)
Definition at line 1961 of file net_crypto.c.
References Crypto_Connection::dht_pk_callback, Crypto_Connection::dht_pk_callback_number, Crypto_Connection::dht_pk_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->dht_pk_callback = function;
    conn->dht_pk_callback_object = object;
    conn->dht_pk_callback_number = number;
    return 0;
}
void new_connection_handler (Net_Crypto * c, int(*)(void *object, New_Connection *n_c) new_connection_callback, void * object)
Definition at line 1502 of file net_crypto.c.
References Net_Crypto::new_connection_callback, and Net_Crypto::new_connection_callback_object.
Referenced by new_friend_connections().
{
    c->new_connection_callback = new_connection_callback;
    c->new_connection_callback_object = object;
}
int new_crypto_connection (Net_Crypto * c, const uint8_t * real_public_key, const uint8_t * dht_public_key)
Definition at line 1623 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, COOKIE_REQUEST_LENGTH, Crypto_Connection::cookie_request_number, create_cookie_request(), create_crypto_connection(), CRYPTO_CONN_COOKIE_REQUESTING, CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, CRYPTO_MIN_QUEUE_LENGTH, CRYPTO_PACKET_MIN_RATE, DEFAULT_PING_CONNECTION, Crypto_Connection::dht_public_key, getcryptconnection_id(), kill_tcp_connection_to(), new_tcp_connection_to(), new_temp_packet(), Crypto_Connection::packet_send_rate, Crypto_Connection::packets_left, Crypto_Connection::public_key, random_64b(), random_nonce(), Crypto_Connection::rtt_time, Crypto_Connection::sent_nonce, Crypto_Connection::sessionpublic_key, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, Crypto_Connection::status, Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by friend_new_connection().
{
    int crypt_connection_id = getcryptconnection_id(c, real_public_key);
    if (crypt_connection_id != -1)
        return crypt_connection_id;
    crypt_connection_id = create_crypto_connection(c);
    if (crypt_connection_id == -1)
        return -1;
    Crypto_Connection *conn = &c->crypto_connections[crypt_connection_id
      ];
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int connection_number_tcp = new_tcp_connection_to(c->
      tcp_c, dht_public_key, crypt_connection_id);
    pthread_mutex_unlock(&c->tcp_mutex);
    if (connection_number_tcp == -1)
        return -1;
    conn->connection_number_tcp = connection_number_tcp;
    memcpy(conn->public_key, real_public_key, crypto_box_PUBLICKEYBYTES);
    random_nonce(conn->sent_nonce);
    crypto_box_keypair(conn->sessionpublic_key, conn->
      sessionsecret_key);
    conn->status = CRYPTO_CONN_COOKIE_REQUESTING;
    conn->packet_send_rate = CRYPTO_PACKET_MIN_RATE;
    conn->packets_left = CRYPTO_MIN_QUEUE_LENGTH;
    conn->rtt_time = DEFAULT_PING_CONNECTION;
    memcpy(conn->dht_public_key, dht_public_key, crypto_box_PUBLICKEYBYTES);
    conn->cookie_request_number = random_64b();
    uint8_t cookie_request[COOKIE_REQUEST_LENGTH];
    if (create_cookie_request(c, cookie_request, conn->
      dht_public_key, conn->cookie_request_number,
                              conn->shared_key) != sizeof(cookie_request)
            || new_temp_packet(c, crypt_connection_id, cookie_request, sizeof(cookie_request
      )) != 0) {
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        conn->status = CRYPTO_CONN_NO_CONNECTION;
        return -1;
    }
    return crypt_connection_id;
}
void new_keys (Net_Crypto * c)
Definition at line 2386 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by new_net_crypto().
{
    crypto_box_keypair(c->self_public_key, c->self_secret_key);
}
Net_Crypto* new_net_crypto (DHT * dht, TCP_Proxy_Info * proxy_info)
Definition at line 2414 of file net_crypto.c.
References bs_list_init(), Net_Crypto::connections_mutex, create_recursive_mutex(), CRYPTO_SEND_PACKET_INTERVAL, Net_Crypto::current_sleep_time, Net_Crypto::dht, Messenger::dht, Net_Crypto::ip_port_list, kill_tcp_connections(), DHT::net, NET_PACKET_COOKIE_REQUEST, NET_PACKET_COOKIE_RESPONSE, NET_PACKET_CRYPTO_DATA, NET_PACKET_CRYPTO_HS, networking_registerhandler(), new_keys(), new_symmetric_key(), new_tcp_connections(), Net_Crypto::secret_symmetric_key, DHT::self_secret_key, set_oob_packet_tcp_connection_callback(), set_packet_tcp_connection_callback(), Net_Crypto::tcp_c, tcp_data_callback(), Net_Crypto::tcp_mutex, tcp_oob_callback(), udp_handle_cookie_request(), udp_handle_packet(), and unix_time_update().
Referenced by new_messenger(), and new_onions().
{
    unix_time_update();
    if (dht == NULL)
        return NULL;
    Net_Crypto *temp = calloc(1, sizeof(Net_Crypto));
    if (temp == NULL)
        return NULL;
    temp->tcp_c = new_tcp_connections(dht->
      self_secret_key, proxy_info);
    if (temp->tcp_c == NULL) {
        free(temp);
        return NULL;
    }
    set_packet_tcp_connection_callback(temp->
      tcp_c, &tcp_data_callback, temp);
    set_oob_packet_tcp_connection_callback(temp->
      tcp_c, &tcp_oob_callback, temp);
    if (create_recursive_mutex(&temp->tcp_mutex) != 0 ||
            pthread_mutex_init(&temp->connections_mutex, NULL) != 0) {
        kill_tcp_connections(temp->tcp_c);
        free(temp);
        return NULL;
    }
    temp->dht = dht;
    new_keys(temp);
    new_symmetric_key(temp->secret_symmetric_key);
    temp->current_sleep_time = CRYPTO_SEND_PACKET_INTERVAL;
    networking_registerhandler(dht->net,
      NET_PACKET_COOKIE_REQUEST, &udp_handle_cookie_request,
      temp);
    networking_registerhandler(dht->net,
      NET_PACKET_COOKIE_RESPONSE, &udp_handle_packet, temp);
    networking_registerhandler(dht->net,
      NET_PACKET_CRYPTO_HS, &udp_handle_packet, temp);
    networking_registerhandler(dht->net,
      NET_PACKET_CRYPTO_DATA, &udp_handle_packet, temp);
    bs_list_init(&temp->ip_port_list, sizeof(IP_Port), 8);
    return temp;
}
void save_keys (const Net_Crypto * c, uint8_t * keys)
Definition at line 2396 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by messenger_save().
{
    memcpy(keys, c->self_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(keys + crypto_box_PUBLICKEYBYTES, c->self_secret_key, crypto_box_SECRETKEYBYTES);
}
int send_lossy_cryptpacket (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length)
Definition at line 2284 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, Net_Crypto::connection_use_counter, Net_Crypto::connections_mutex, get_crypto_connection(), MAX_CRYPTO_DATA_SIZE, Crypto_Connection::mutex, PACKET_ID_LOSSY_RANGE_SIZE, PACKET_ID_LOSSY_RANGE_START, Crypto_Connection::recv_array, Crypto_Connection::send_array, and send_data_packet_helper().
Referenced by send_custom_lossy_packet(), and send_lossy_group_peer().
{
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -1;
    if (data[0] < PACKET_ID_LOSSY_RANGE_START)
        return -1;
    if (data[0] >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_ID_LOSSY_RANGE_SIZE))
        return -1;
    pthread_mutex_lock(&c->connections_mutex);
    ++c->connection_use_counter;
    pthread_mutex_unlock(&c->connections_mutex);
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    int ret = -1;
    if (conn) {
        pthread_mutex_lock(&conn->mutex);
        uint32_t buffer_start = conn->recv_array.buffer_start;
        uint32_t buffer_end = conn->send_array.buffer_end;
        pthread_mutex_unlock(&conn->mutex);
        ret = send_data_packet_helper(c, crypt_connection_id, buffer_start,
      buffer_end, data, length);
    }
    pthread_mutex_lock(&c->connections_mutex);
    --c->connection_use_counter;
    pthread_mutex_unlock(&c->connections_mutex);
    return ret;
}
int send_tcp_onion_request (Net_Crypto * c, unsigned int TCP_conn_number, const uint8_t * data, uint16_t length)
Definition at line 1824 of file net_crypto.c.
References Net_Crypto::tcp_c, Net_Crypto::tcp_mutex, and tcp_send_onion_request().
Referenced by send_onion_packet_tcp_udp().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = tcp_send_onion_request(c->tcp_c, tcp_connections_number,
      data, length);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
int set_direct_ip_port (Net_Crypto * c, int crypt_connection_id, IP_Port ip_port, _Bool connected)
Definition at line 1680 of file net_crypto.c.
References bs_list_add(), bs_list_remove(), Crypto_Connection::direct_lastrecv_time, IP::family, get_crypto_connection(), IP_Port::ip, Crypto_Connection::ip_port, Net_Crypto::ip_port_list, ipport_equal(), LAN_ip(), UDP_DIRECT_TIMEOUT, and unix_time().
Referenced by dht_ip_callback(), do_friend_connections(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    if (!ipport_equal(&ip_port, &conn->ip_port)) {
        if ((UDP_DIRECT_TIMEOUT + conn->direct_lastrecv_time) >
      unix_time()) {
            /* We already know a LAN ip, no need to switch. */
            if (LAN_ip(conn->ip_port.ip) == 0)
                return -1;
            /* Prefer ipv6. */
            if (conn->ip_port.ip.family == AF_INET6 && ip_port.ip.
      family == AF_INET)
                return -1;
        }
        if (bs_list_add(&c->ip_port_list, (uint8_t *)&ip_port, crypt_connection_id))
       {
            bs_list_remove(&c->ip_port_list, (uint8_t *)&conn->
      ip_port, crypt_connection_id);
            conn->ip_port = ip_port;
            if (connected) {
                conn->direct_lastrecv_time = unix_time();
            } else {
                conn->direct_lastrecv_time = 0;
            }
            return 0;
        }
    }
    return -1;
}
int64_t write_cryptpacket (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length, uint8_t congestion_control)
Definition at line 2219 of file net_crypto.c.
References CRYPTO_CONN_ESTABLISHED, CRYPTO_RESERVED_PACKETS, get_crypto_connection(), PACKET_ID_LOSSY_RANGE_START, Crypto_Connection::packets_left, Crypto_Connection::packets_sent, send_lossless_packet(), and Crypto_Connection::status.
Referenced by m_send_message_generic(), send_custom_lossless_packet(), send_file_data_packet(), send_friend_request_packet(), send_offline_packet(), send_online_packet(), send_packet_group_peer(), send_packet_online(), send_ping(), send_relays(), and write_cryptpacket_id().
{
    if (length == 0)
        return -1;
    if (data[0] < CRYPTO_RESERVED_PACKETS)
        return -1;
    if (data[0] >= PACKET_ID_LOSSY_RANGE_START)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (conn->status != CRYPTO_CONN_ESTABLISHED)
        return -1;
    if (congestion_control && conn->packets_left == 0)
        return -1;
    int64_t ret = send_lossless_packet(c, crypt_connection_id,
      data, length, congestion_control);
    if (ret == -1)
        return -1;
    if (congestion_control) {
        --conn->packets_left;
        conn->packets_sent++;
    }
    return ret;
}