testing/misc_tools.c File Reference
#include <string.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <stdint.h>
*
Functions
uint8_t * hex_string_to_bin (char *hex_string)
int cmdline_parsefor_ipv46 (int argc, char **argv, uint8_t *ipv6enabled)
Function Documentation
int cmdline_parsefor_ipv46 (int argc, char ** argv, uint8_t * ipv6enabled)
Definition at line 55 of file misc_tools.c.
References printf().
Referenced by init_tox(), and main().
{
    int argvoffset = 0, argi;
    for (argi = 1; argi < argc; argi++)
        if (!strncasecmp(argv[argi], "--ipv", 5)) {
            if (argv[argi][5] && !argv[argi][6]) {
                char c = argv[argi][5];
                if (c == '4')
                    *ipv6enabled = 0;
                else if (c == '6')
                    *ipv6enabled = 1;
                else {
                    printf("Invalid argument: %s. Try --ipv4 or --ipv6!\n", argv[argi]);
                    return -1;
                }
            } else {
                printf("Invalid argument: %s. Try --ipv4 or --ipv6!\n", argv[argi]);
                return -1;
            }
            if (argvoffset != argi - 1) {
                printf("Argument must come first: %s.\n", argv[argi]);
                return -1;
            }
            argvoffset++;
        }
    return argvoffset;
};
uint8_t* hex_string_to_bin (char * hex_string)
Definition at line 38 of file misc_tools.c.
References i.
Referenced by bootstrap_from_config(), init_tox(), line_eval(), and main().
{
    // byte is represented by exactly 2 hex digits, so lenth of binary string
    // is half of that of the hex one. only hex string with even length
    // valid. the more proper implementation would be to check if strlen(hex_string)
    // is odd and return error code if it is. we assume strlen is even. if it's not
    // then the last byte just won't be written in 'ret'.
    size_t i, len = strlen(hex_string) / 2;
    uint8_t *ret = malloc(len);
    char *pos = hex_string;
    for (i = 0; i < len; ++i, pos += 2)
        sscanf(pos, "%2hhx", &ret[i]);
    return ret;
}