toxcore/network.c File Reference
#include `logger.h`
*
#include <errno.h>
*
#include `network.h`
*
#include `util.h`
*
#include <sodium.h>
*
Macros
#define _WIN32_WINNT 0x501
#define loglogdata(__message__, __buffer__, __buflen__, __ip_port__, __res__)
Functions
int sock_valid (sock_t sock)
void kill_sock (sock_t sock)
int set_socket_nonblock (sock_t sock)
int set_socket_nosigpipe (sock_t sock)
int set_socket_reuseaddr (sock_t sock)
int set_socket_dualstack (sock_t sock)
static uint64_t current_time_actual (void)
uint64_t current_time_monotonic (void)
int sendpacket (Networking_Core *net, IP_Port ip_port, const uint8_t *data, uint16_t length)
static int receivepacket (sock_t sock, IP_Port *ip_port, uint8_t *data, uint32_t *length)
void networking_registerhandler (Networking_Core *net, uint8_t byte, packet_handler_callback cb, void *object)
void networking_poll (Networking_Core *net)
int networking_at_startup (void)
Networking_Core * new_networking (IP ip, uint16_t port)
Networking_Core * new_networking_ex (IP ip, uint16_t port_from, uint16_t port_to, unsigned int *error)
void kill_networking (Networking_Core *net)
int ip_equal (const IP *a, const IP *b)
int ipport_equal (const IP_Port *a, const IP_Port *b)
void ip_reset (IP *ip)
void ip_init (IP *ip, uint8_t ipv6enabled)
int ip_isset (const IP *ip)
int ipport_isset (const IP_Port *ipport)
void ip_copy (IP *target, const IP *source)
void ipport_copy (IP_Port *target, const IP_Port *source)
const char * ip_ntoa (const IP *ip)
int ip_parse_addr (const IP *ip, char *address, size_t length)
int addr_parse_ip (const char *address, IP *to)
int addr_resolve (const char *address, IP *to, IP *extra)
int addr_resolve_or_parse_ip (const char *address, IP *to, IP *extra)
Variables
uint8_t at_startup_ran = 0
static char addresstext [96]
Macro Definition Documentation
#define _WIN32_WINNT 0x501
Definition at line 25 of file network.c.
#define loglogdata(__message__, __buffer__, __buflen__, __ip_port__, __res__)
Definition at line 270 of file network.c.
Referenced by receivepacket(), and sendpacket().
Function Documentation
int addr_parse_ip (const char * address, IP * to)
Definition at line 900 of file network.c.
References IP::family, IP6::in6_addr, IP4::in_addr, IP::ip4, and IP::ip6.
Referenced by addr_resolve_or_parse_ip().
{
    if (!address || !to)
        return 0;
    struct in_addr addr4;
    if (1 == inet_pton(AF_INET, address, &addr4)) {
        to->family = AF_INET;
        to->ip4.in_addr = addr4;
        return 1;
    }
    struct in6_addr addr6;
    if (1 == inet_pton(AF_INET6, address, &addr6)) {
        to->family = AF_INET6;
        to->ip6.in6_addr = addr6;
        return 1;
    }
    return 0;
}
int addr_resolve (const char * address, IP * to, IP * extra)
Definition at line 941 of file network.c.
References IP::family, IP6::in6_addr, IP4::in_addr, IP::ip4, IP::ip6, and networking_at_startup().
Referenced by addr_resolve_or_parse_ip(), and START_TEST().
{
    if (!address || !to)
        return 0;
    sa_family_t family = to->family;
    struct addrinfo *server = NULL;
    struct addrinfo *walker = NULL;
    struct addrinfo hints;
    int rc;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = family;
    hints.ai_socktype = SOCK_DGRAM; // type of socket Tox uses.
    if (networking_at_startup() != 0)
        return 0;
    rc = getaddrinfo(address, NULL, &hints, &server);
    // Lookup failed.
    if (rc != 0) {
        return 0;
    }
    IP4 ip4;
    memset(&ip4, 0, sizeof(ip4));
    IP6 ip6;
    memset(&ip6, 0, sizeof(ip6));
    for (walker = server; (walker != NULL) && (rc != 3); walker = walker->ai_next) {
        switch (walker->ai_family) {
            case AF_INET:
                if (walker->ai_family == family) { /* AF_INET requested, done */
                    struct sockaddr_in *addr = (struct sockaddr_in *)walker->ai_addr;
                    to->ip4.in_addr = addr->sin_addr;
                    rc = 3;
                } else if (!(rc & 1)) { /* AF_UNSPEC requested, store away */
                    struct sockaddr_in *addr = (struct sockaddr_in *)walker->ai_addr;
                    ip4.in_addr = addr->sin_addr;
                    rc |= 1;
                }
                break; /* switch */
            case AF_INET6:
                if (walker->ai_family == family) { /* AF_INET6 requested, done */
                    if (walker->ai_addrlen == sizeof(struct sockaddr_in6)) {
                        struct sockaddr_in6 *addr = (struct sockaddr_in6 *)walker->ai_addr;
                        to->ip6.in6_addr = addr->sin6_addr;
                        rc = 3;
                    }
                } else if (!(rc & 2)) { /* AF_UNSPEC requested, store away */
                    if (walker->ai_addrlen == sizeof(struct sockaddr_in6)) {
                        struct sockaddr_in6 *addr = (struct sockaddr_in6 *)walker->ai_addr;
                        ip6.in6_addr = addr->sin6_addr;
                        rc |= 2;
                    }
                }
                break; /* switch */
        }
    }
    if (to->family == AF_UNSPEC) {
        if (rc & 2) {
            to->family = AF_INET6;
            to->ip6 = ip6;
            if ((rc & 1) && (extra != NULL)) {
                extra->family = AF_INET;
                extra->ip4 = ip4;
            }
        } else if (rc & 1) {
            to->family = AF_INET;
            to->ip4 = ip4;
        } else
            rc = 0;
    }
    freeaddrinfo(server);
    return rc;
}
int addr_resolve_or_parse_ip (const char * address, IP * to, IP * extra)
Definition at line 1041 of file network.c.
References addr_parse_ip(), and addr_resolve().
Referenced by DHT_bootstrap_from_address(), main(), and tox_new().
{
    if (!addr_resolve(address, to, extra))
        if (!addr_parse_ip(address, to))
            return 0;
    return 1;
}
static uint64_t current_time_actual (void) [static]
Definition at line 206 of file network.c.
Referenced by networking_at_startup().
{
    uint64_t time;
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    /* This probably works fine */
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    time = ft.dwHighDateTime;
    time <<= 32;
    time |= ft.dwLowDateTime;
    time -= 116444736000000000ULL;
    return time / 10;
#else
    struct timeval a;
    gettimeofday(&a, NULL);
    time = 1000000ULL * a.tv_sec + a.tv_usec;
    return time;
#endif
}
uint64_t current_time_monotonic (void)
Definition at line 233 of file network.c.
Referenced by build_header(), get_monotime_sec(), handle_data_packet_helper(), handle_request_packet(), logger_new(), msi_do(), reset_max_speed_reached(), send_crypto_packets(), send_lossless_packet(), send_requested_packets(), send_temp_packet(), timer_alloc(), toxav_do(), and unix_time_update().
{
    uint64_t time;
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    time = (uint64_t)GetTickCount() + add_monotime;
    if (time < last_monotime) { /* Prevent time from ever decreasing because of 32 bit wrap. */
        uint32_t add = ~0;
        add_monotime += add;
        time += add;
    }
    last_monotime = time;
#else
    struct timespec monotime;
#if defined(__linux__) && defined(CLOCK_MONOTONIC_RAW)
    clock_gettime(CLOCK_MONOTONIC_RAW, &monotime);
#elif defined(__APPLE__)
    clock_serv_t muhclock;
    mach_timespec_t machtime;
    host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &muhclock);
    clock_get_time(muhclock, &machtime);
    mach_port_deallocate(mach_task_self(), muhclock);
    monotime.tv_sec = machtime.tv_sec;
    monotime.tv_nsec = machtime.tv_nsec;
#else
    clock_gettime(CLOCK_MONOTONIC, &monotime);
#endif
    time = 1000ULL * monotime.tv_sec + (monotime.tv_nsec / 1000000ULL);
#endif
    return time;
}
void ip_copy (IP * target, const IP * source)
Definition at line 801 of file network.c.
Referenced by punch_holes().
{
    if (!source || !target)
        return;
    memcpy(target, source, sizeof(IP));
}
int ip_equal (const IP * a, const IP * b)
Definition at line 716 of file network.c.
References IP::family, IP4::in_addr, IP::ip4, IP::ip6, IPV6_IPV4_IN_V6, IP6::uint32, and IP6::uint64.
Referenced by ipport_equal(), NAT_commonip(), NAT_getports(), network_suite(), and START_TEST().
{
    if (!a || !b)
        return 0;
    /* same family */
    if (a->family == b->family) {
        if (a->family == AF_INET)
            return (a->ip4.in_addr.s_addr == b->ip4.in_addr.s_addr);
        else if (a->family == AF_INET6)
            return a->ip6.uint64[0] == b->ip6.uint64[0] && a->
      ip6.uint64[1] == b->ip6.uint64[1];
        else
            return 0;
    }
    /* different family: check on the IPv6 one if it is the IPv4 one embedded */
    if ((a->family == AF_INET) && (b->family == AF_INET6)) {
        if (IPV6_IPV4_IN_V6(b->ip6))
            return (a->ip4.in_addr.s_addr == b->ip6.uint32[3]);
    } else if ((a->family == AF_INET6) && (b->family == AF_INET)) {
        if (IPV6_IPV4_IN_V6(a->ip6))
            return (a->ip6.uint32[3] == b->ip4.in_addr.s_addr);
    }
    return 0;
}
void ip_init (IP * ip, uint8_t ipv6enabled)
Definition at line 770 of file network.c.
References IP::family.
Referenced by DHT_bootstrap_from_address(), main(), new_messenger(), new_onions(), START_TEST(), and tox_new().
{
    if (!ip)
        return;
    memset(ip, 0, sizeof(IP));
    ip->family = ipv6enabled ? AF_INET6 : AF_INET;
}
int ip_isset (const IP * ip)
Definition at line 780 of file network.c.
References IP::family.
Referenced by add_to_ping(), DHT_bootstrap_from_address(), do_messenger(), do_NAT(), do_to_ping(), friend_iplist(), ipport_isset(), route_packet(), route_tofriend(), routeone_tofriend(), send_hardening_getnode_res(), and send_LANdiscovery().
{
    if (!ip)
        return 0;
    return (ip->family != 0);
}
const char* ip_ntoa (const IP * ip)
Definition at line 827 of file network.c.
References addresstext, IP::family, IP::ip4, and IP::ip6.
Referenced by do_Assoc(), do_messenger(), new_networking_ex(), print_assoc(), print_friendlist(), and START_TEST().
{
    if (ip) {
        if (ip->family == AF_INET) {
            /* returns standard quad-dotted notation */
            struct in_addr *addr = (struct in_addr *)&ip->ip4;
            addresstext[0] = 0;
            inet_ntop(ip->family, addr, addresstext, sizeof(
      addresstext));
        } else if (ip->family == AF_INET6) {
            /* returns hex-groups enclosed into square brackets */
            struct in6_addr *addr = (struct in6_addr *)&ip->ip6;
            addresstext[0] = '[';
            inet_ntop(ip->family, addr, &addresstext[1], sizeof(
      addresstext) - 3);
            size_t len = strlen(addresstext);
            addresstext[len] = ']';
            addresstext[len + 1] = 0;
        } else
            snprintf(addresstext, sizeof(addresstext), "(IP invalid, family %u)", ip
      ->family);
    } else
        snprintf(addresstext, sizeof(addresstext), "(IP invalid: NULL)");
    /* brute force protection against lacking termination */
    addresstext[sizeof(addresstext) - 1] = 0;
    return addresstext;
}
int ip_parse_addr (const IP * ip, char * address, size_t length)
Definition at line 870 of file network.c.
References IP::family, IP::ip4, and IP::ip6.
Referenced by proxy_http_generate_connection_request().
{
    if (!address || !ip) {
        return 0;
    }
    if (ip->family == AF_INET) {
        struct in_addr *addr = (struct in_addr *)&ip->ip4;
        return inet_ntop(ip->family, addr, address, length) != NULL;
    } else if (ip->family == AF_INET6) {
        struct in6_addr *addr = (struct in6_addr *)&ip->ip6;
        return inet_ntop(ip->family, addr, address, length) != NULL;
    }
    return 0;
}
void ip_reset (IP * ip)
Definition at line 761 of file network.c.
Referenced by broadcast_ip(), DHT_bootstrap_from_address(), DHT_getfriendip(), do_to_ping(), NAT_commonip(), replace_all(), and START_TEST().
{
    if (!ip)
        return;
    memset(ip, 0, sizeof(IP));
}
void ipport_copy (IP_Port * target, const IP_Port * source)
Definition at line 810 of file network.c.
Referenced by add_to_ping(), and test_addto_lists_update().
{
    if (!source || !target)
        return;
    memcpy(target, source, sizeof(IP_Port));
}
int ipport_equal (const IP_Port * a, const IP_Port * b)
Definition at line 749 of file network.c.
References IP_Port::ip, ip_equal(), and IP_Port::port.
Referenced by client_or_ip_port_in_list(), crypto_connection_add_source(), entry_heard_store(), handle_ping_response(), in_list(), is_path_used(), sent_getnode_to_node(), set_direct_ip_port(), and test_addto_lists_update().
{
    if (!a || !b)
        return 0;
    if (!a->port || (a->port != b->port))
        return 0;
    return ip_equal(&a->ip, &b->ip);
}
int ipport_isset (const IP_Port * ipport)
Definition at line 789 of file network.c.
References IP_Port::ip, ip_isset(), and IP_Port::port.
Referenced by Assoc_add_entry(), Assoc_get_close_entries(), candidates_create_new(), DHT_addfriend(), do_hardening(), entry_heard_store(), get_close_nodes(), and handle_sendnodes_ipv6().
{
    if (!ipport)
        return 0;
    if (!ipport->port)
        return 0;
    return ip_isset(&ipport->ip);
}
void kill_networking (Networking_Core * net)
Definition at line 700 of file network.c.
References Networking_Core::family, kill_sock(), and Networking_Core::sock.
Referenced by kill_messenger(), kill_onions(), new_messenger(), new_networking_ex(), START_TEST(), and test_addto_lists().
{
    if (net->family != 0) /* Socket not initialized */
        kill_sock(net->sock);
    free(net);
    return;
}
void kill_sock (sock_t sock)
Definition at line 136 of file network.c.
Referenced by accept_connection(), kill_accepted(), kill_networking(), kill_TCP_con(), kill_TCP_connection(), kill_TCP_server(), new_listening_TCP_socket(), and new_TCP_connection().
{
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    closesocket(sock);
#else
    close(sock);
#endif
}
int networking_at_startup (void)
Definition at line 444 of file network.c.
References current_time_actual().
Referenced by addr_resolve(), new_networking_ex(), new_TCP_connection(), and new_TCP_server().
{
    if (at_startup_ran != 0)
        return 0;
#ifndef VANILLA_NACL
#ifdef USE_RANDOMBYTES_STIR
    randombytes_stir();
#else
    sodium_init();
#endif /*USE_RANDOMBYTES_STIR*/
#endif/*VANILLA_NACL*/
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != NO_ERROR)
        return -1;
#endif
    srand((uint32_t)current_time_actual());
    at_startup_ran = 1;
    return 0;
}
void networking_poll (Networking_Core * net)
Definition at line 415 of file network.c.
References make-funny-savefile::data, Networking_Core::family, Packet_Handles::function, LOGGER_WARNING, MAX_UDP_PACKET_SIZE, Packet_Handles::object, Networking_Core::packethandlers, receivepacket(), Networking_Core::sock, and unix_time_update().
Referenced by do_messenger(), do_onion(), do_onions(), and main().
{
    if (net->family == 0) /* Socket not initialized */
        return;
    unix_time_update();
    IP_Port ip_port;
    uint8_t data[MAX_UDP_PACKET_SIZE];
    uint32_t length;
    while (receivepacket(net->sock, &ip_port, data, &length) != -1) {
        if (length < 1) continue;
        if (!(net->packethandlers[data[0]].function)) {
            LOGGER_WARNING("[%02u] -- Packet has no handler", data[0]);
            continue;
        }
        net->packethandlers[data[0]].function(net->
      packethandlers[data[0]].object, ip_port, data, length);
    }
}
void networking_registerhandler (Networking_Core * net, uint8_t byte, packet_handler_callback cb, void * object)
Definition at line 409 of file network.c.
References Packet_Handles::function, Packet_Handles::object, and Networking_Core::packethandlers.
Referenced by bootstrap_set_callbacks(), kill_DHT(), kill_net_crypto(), kill_onion(), kill_onion_announce(), kill_onion_client(), kill_ping(), LANdiscovery_init(), LANdiscovery_kill(), new_DHT(), new_net_crypto(), new_onion(), new_onion_announce(), new_onion_client(), new_ping(), and START_TEST().
{
    net->packethandlers[byte].function = cb;
    net->packethandlers[byte].object = object;
}
Networking_Core* new_networking (IP ip, uint16_t port)
Definition at line 483 of file network.c.
References new_networking_ex(), TOX_PORTRANGE_FROM, and TOX_PORTRANGE_TO.
Referenced by main(), new_onions(), START_TEST(), and test_addto_lists().
{
    return new_networking_ex(ip, port, port + (
      TOX_PORTRANGE_TO - TOX_PORTRANGE_FROM), 0);
}
Networking_Core* new_networking_ex (IP ip, uint16_t port_from, uint16_t port_to, unsigned int * error)
Definition at line 498 of file network.c.
References IP::family, Networking_Core::family, IP6::in6_addr, IP4::in_addr, IP::ip4, IP::ip6, ip_ntoa(), kill_networking(), LOGGER_DEBUG, LOGGER_ERROR, networking_at_startup(), Networking_Core::port, set_socket_dualstack(), set_socket_nonblock(), set_socket_nosigpipe(), Networking_Core::sock, sock_valid(), TOX_PORTRANGE_FROM, and TOX_PORTRANGE_TO.
Referenced by new_messenger(), and new_networking().
{
    /* If both from and to are 0, use default port range
     * If one is 0 and the other is non-0, use the non-0 value as only port
     * If from > to, swap
     */
    if (port_from == 0 && port_to == 0) {
        port_from = TOX_PORTRANGE_FROM;
        port_to = TOX_PORTRANGE_TO;
    } else if (port_from == 0 && port_to != 0) {
        port_from = port_to;
    } else if (port_from != 0 && port_to == 0) {
        port_to = port_from;
    } else if (port_from > port_to) {
        uint16_t temp = port_from;
        port_from = port_to;
        port_to = temp;
    }
    if (error)
        *error = 2;
    /* maybe check for invalid IPs like 224+.x.y.z? if there is any IP set ever */
    if (ip.family != AF_INET && ip.family != AF_INET6) {
#ifdef DEBUG
        fprintf(stderr, "Invalid address family: %u\n", ip.family);
#endif
        return NULL;
    }
    if (networking_at_startup() != 0)
        return NULL;
    Networking_Core *temp = calloc(1, sizeof(Networking_Core));
    if (temp == NULL)
        return NULL;
    temp->family = ip.family;
    temp->port = 0;
    /* Initialize our socket. */
    /* add log message what we're creating */
    temp->sock = socket(temp->family, SOCK_DGRAM, IPPROTO_UDP);
    /* Check for socket error. */
    if (!sock_valid(temp->sock)) {
#ifdef DEBUG
        fprintf(stderr, "Failed to get a socket?! %u, %s\n", errno, strerror(errno));
#endif
        free(temp);
        if (error)
            *error = 1;
        return NULL;
    }
    /* Functions to increase the size of the send and receive UDP buffers.
     */
    int n = 1024 * 1024 * 2;
    setsockopt(temp->sock, SOL_SOCKET, SO_RCVBUF, (char *)&n, sizeof(n));
    setsockopt(temp->sock, SOL_SOCKET, SO_SNDBUF, (char *)&n, sizeof(n));
    /* Enable broadcast on socket */
    int broadcast = 1;
    setsockopt(temp->sock, SOL_SOCKET, SO_BROADCAST, (char *)&broadcast, sizeof(broadcast));
    /* iOS UDP sockets are weird and apparently can SIGPIPE */
    if (!set_socket_nosigpipe(temp->sock)) {
        kill_networking(temp);
        if (error)
            *error = 1;
        return NULL;
    }
    /* Set socket nonblocking. */
    if (!set_socket_nonblock(temp->sock)) {
        kill_networking(temp);
        if (error)
            *error = 1;
        return NULL;
    }
    /* Bind our socket to port PORT and the given IP address (usually 0.0.0.0 or ::) */
    uint16_t *portptr = NULL;
    struct sockaddr_storage addr;
    size_t addrsize;
    if (temp->family == AF_INET) {
        struct sockaddr_in *addr4 = (struct sockaddr_in *)&addr;
        addrsize = sizeof(struct sockaddr_in);
        addr4->sin_family = AF_INET;
        addr4->sin_port = 0;
        addr4->sin_addr = ip.ip4.in_addr;
        portptr = &addr4->sin_port;
    } else if (temp->family == AF_INET6) {
        struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)&addr;
        addrsize = sizeof(struct sockaddr_in6);
        addr6->sin6_family = AF_INET6;
        addr6->sin6_port = 0;
        addr6->sin6_addr = ip.ip6.in6_addr;
        addr6->sin6_flowinfo = 0;
        addr6->sin6_scope_id = 0;
        portptr = &addr6->sin6_port;
    } else {
        free(temp);
        return NULL;
    }
    if (ip.family == AF_INET6) {
#ifdef LOGGING
        int is_dualstack =
#endif /* LOGGING */
            set_socket_dualstack(temp->sock);
        LOGGER_DEBUG("Dual-stack socket: %s",
                      is_dualstack ? "enabled" : "Failed to enable, won't be able to receive from/send to
       IPv4 addresses");
        /* multicast local nodes */
        struct ipv6_mreq mreq;
        memset(&mreq, 0, sizeof(mreq));
        mreq.ipv6mr_multiaddr.s6_addr[ 0] = 0xFF;
        mreq.ipv6mr_multiaddr.s6_addr[ 1] = 0x02;
        mreq.ipv6mr_multiaddr.s6_addr[15] = 0x01;
        mreq.ipv6mr_interface = 0;
#ifdef LOGGING
        int res =
#endif /* LOGGING */
            setsockopt(temp->sock, IPPROTO_IPV6, IPV6_ADD_MEMBERSHIP, (char *)&mreq, sizeof(mreq));
        LOGGER_DEBUG(res < 0 ? "Failed to activate local multicast membership. (%u, %s)" :
                     "Local multicast group FF02::1 joined successfully", errno, strerror(errno));
    }
    /* a hanging program or a different user might block the standard port;
     * as long as it isn't a parameter coming from the commandline,
     * try a few ports after it, to see if we can find a "free" one
     *
     * if we go on without binding, the first sendto() automatically binds to
     * a free port chosen by the system (i.e. anything from 1024 to 65535)
     *
     * returning NULL after bind fails has both advantages and disadvantages:
     * advantage:
     * we can rely on getting the port in the range 33445..33450, which
     * enables us to tell joe user to open their firewall to a small range
     *
     * disadvantage:
     * some clients might not test return of tox_new(), blindly assuming that
     * it worked ok (which it did previously without a successful bind)
     */
    uint16_t port_to_try = port_from;
    *portptr = htons(port_to_try);
    int tries;
    for (tries = port_from; tries <= port_to; tries++) {
        int res = bind(temp->sock, (struct sockaddr *)&addr, addrsize);
        if (!res) {
            temp->port = *portptr;
            LOGGER_DEBUG("Bound successfully to %s:%u", ip_ntoa(&ip), ntohs(temp->
      port));
            /* errno isn't reset on success, only set on failure, the failed
             * binds with parallel clients yield a -EPERM to the outside if
             * errno isn't cleared here */
            if (tries > 0)
                errno = 0;
            if (error)
                *error = 0;
            return temp;
        }
        port_to_try++;
        if (port_to_try > port_to)
            port_to_try = port_from;
        *portptr = htons(port_to_try);
    }
    LOGGER_ERROR("Failed to bind socket: %u, %s IP: %s port_from: %u port_to: %u", errno,
      strerror(errno),
                 ip_ntoa(&ip), port_from, port_to);
    kill_networking(temp);
    if (error)
        *error = 1;
    return NULL;
}
static int receivepacket (sock_t sock, IP_Port * ip_port, uint8_t * data, uint32_t * length) [static]
Definition at line 363 of file network.c.
References IP::family, IP6::in6_addr, IP4::in_addr, IP_Port::ip, IP::ip4, IP::ip6, IPV6_IPV4_IN_V6, LOGGER_ERROR, LOGGER_SCOPE, loglogdata, MAX_UDP_PACKET_SIZE, IP_Port::port, IP4::uint32, and IP6::uint32.
Referenced by networking_poll().
{
    memset(ip_port, 0, sizeof(IP_Port));
    struct sockaddr_storage addr;
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    int addrlen = sizeof(addr);
#else
    socklen_t addrlen = sizeof(addr);
#endif
    *length = 0;
    int fail_or_len = recvfrom(sock, (char *) data, MAX_UDP_PACKET_SIZE, 0, (
      struct sockaddr *)&addr, &addrlen);
    if (fail_or_len < 0) {
        LOGGER_SCOPE(if ((fail_or_len < 0) && (errno != EWOULDBLOCK))
                      LOGGER_ERROR("Unexpected error reading from socket: %u, %s\n", errno,
      strerror(errno)););
        return -1; /* Nothing received. */
    }
    *length = (uint32_t)fail_or_len;
    if (addr.ss_family == AF_INET) {
        struct sockaddr_in *addr_in = (struct sockaddr_in *)&addr;
        ip_port->ip.family = addr_in->sin_family;
        ip_port->ip.ip4.in_addr = addr_in->sin_addr;
        ip_port->port = addr_in->sin_port;
    } else if (addr.ss_family == AF_INET6) {
        struct sockaddr_in6 *addr_in6 = (struct sockaddr_in6 *)&addr;
        ip_port->ip.family = addr_in6->sin6_family;
        ip_port->ip.ip6.in6_addr = addr_in6->sin6_addr;
        ip_port->port = addr_in6->sin6_port;
        if (IPV6_IPV4_IN_V6(ip_port->ip.ip6)) {
            ip_port->ip.family = AF_INET;
            ip_port->ip.ip4.uint32 = ip_port->ip.ip6.uint32[3];
        }
    } else
        return -1;
    loglogdata("=>O", data, MAX_UDP_PACKET_SIZE, *ip_port, *length);
    return 0;
}
int sendpacket (Networking_Core * net, IP_Port ip_port, const uint8_t * data, uint16_t length)
Definition at line 295 of file network.c.
References IP::family, Networking_Core::family, IP6::in6_addr, IP4::in_addr, IP_Port::ip, IP::ip4, IP::ip6, loglogdata, IP_Port::port, Networking_Core::sock, IP4::uint32, and IP6::uint32.
Referenced by getnodes(), handle_info_request(), handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), onion_send_1(), route_packet(), route_tofriend(), routeone_tofriend(), send_announce_request(), send_broadcasts(), send_data_request(), send_hardening_getnode_res(), send_hardening_req(), send_LANdiscovery(), send_onion_packet(), send_onion_packet_tcp_udp(), send_onion_response(), send_packet_to(), send_ping_request(), send_ping_response(), sendnodes_ipv6(), and udp_handle_cookie_request().
{
    if (net->family == 0) /* Socket not initialized */
        return -1;
    /* socket AF_INET, but target IP NOT: can't send */
    if ((net->family == AF_INET) && (ip_port.ip.family != AF_INET))
        return -1;
    struct sockaddr_storage addr;
    size_t addrsize = 0;
    if (ip_port.ip.family == AF_INET) {
        if (net->family == AF_INET6) {
            /* must convert to IPV4-in-IPV6 address */
            struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)&addr;
            addrsize = sizeof(struct sockaddr_in6);
            addr6->sin6_family = AF_INET6;
            addr6->sin6_port = ip_port.port;
            /* there should be a macro for this in a standards compliant
             * environment, not found */
            IP6 ip6;
            ip6.uint32[0] = 0;
            ip6.uint32[1] = 0;
            ip6.uint32[2] = htonl(0xFFFF);
            ip6.uint32[3] = ip_port.ip.ip4.uint32;
            addr6->sin6_addr = ip6.in6_addr;
            addr6->sin6_flowinfo = 0;
            addr6->sin6_scope_id = 0;
        } else {
            struct sockaddr_in *addr4 = (struct sockaddr_in *)&addr;
            addrsize = sizeof(struct sockaddr_in);
            addr4->sin_family = AF_INET;
            addr4->sin_addr = ip_port.ip.ip4.in_addr;
            addr4->sin_port = ip_port.port;
        }
    } else if (ip_port.ip.family == AF_INET6) {
        struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)&addr;
        addrsize = sizeof(struct sockaddr_in6);
        addr6->sin6_family = AF_INET6;
        addr6->sin6_port = ip_port.port;
        addr6->sin6_addr = ip_port.ip.ip6.in6_addr;
        addr6->sin6_flowinfo = 0;
        addr6->sin6_scope_id = 0;
    } else {
        /* unknown address type*/
        return -1;
    }
    int res = sendto(net->sock, (char *) data, length, 0, (struct sockaddr *)&addr, addrsize);
    loglogdata("O=>", data, length, ip_port, res);
    return res;
}
int set_socket_dualstack (sock_t sock)
Definition at line 191 of file network.c.
Referenced by new_listening_TCP_socket(), and new_networking_ex().
{
    int ipv6only = 0;
    socklen_t optsize = sizeof(ipv6only);
    int res = getsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, (void *)&ipv6only, &optsize);
    if ((res == 0) && (ipv6only == 0))
        return 1;
    ipv6only = 0;
    return (setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, (void *)&ipv6only, sizeof(ipv6only)) == 0);
}
int set_socket_nonblock (sock_t sock)
Definition at line 150 of file network.c.
Referenced by accept_connection(), new_listening_TCP_socket(), new_networking_ex(), and new_TCP_connection().
{
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    u_long mode = 1;
    return (ioctlsocket(sock, FIONBIO, &mode) == 0);
#else
    return (fcntl(sock, F_SETFL, O_NONBLOCK, 1) == 0);
#endif
}
int set_socket_nosigpipe (sock_t sock)
Definition at line 165 of file network.c.
Referenced by accept_connection(), new_networking_ex(), and new_TCP_connection().
{
#if defined(__MACH__)
    int set = 1;
    return (setsockopt(sock, SOL_SOCKET, SO_NOSIGPIPE, (void *)&set, sizeof(int)) == 0);
#else
    return 1;
#endif
}
int set_socket_reuseaddr (sock_t sock)
Definition at line 180 of file network.c.
Referenced by new_listening_TCP_socket().
{
    int set = 1;
    return (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (void *)&set, sizeof(set)) == 0);
}
int sock_valid (sock_t sock)
Definition at line 119 of file network.c.
Referenced by accept_connection(), main(), new_listening_TCP_socket(), new_networking_ex(), new_TCP_connection(), and new_TCP_server().
{
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    if (sock == INVALID_SOCKET) {
#else
    if (sock < 0) {
#endif
        return 0;
    }
    return 1;
}
Variable Documentation
char addresstext[96] [static]
Definition at line 826 of file network.c.
Referenced by ip_ntoa().
uint8_t at_startup_ran = 0
Definition at line 443 of file network.c.