toxcore/TCP_connection.h File Reference
#include `TCP_client.h`
*
Data Structures
struct TCP_Connection_to
struct TCP_con
struct TCP_Connections
Macros
#define TCP_CONN_NONE 0
#define TCP_CONN_VALID 1
#define TCP_CONN_CONNECTED 2
#define TCP_CONN_SLEEPING 3
#define TCP_CONNECTIONS_STATUS_NONE 0
#define TCP_CONNECTIONS_STATUS_REGISTERED 1
#define TCP_CONNECTIONS_STATUS_ONLINE 2
#define MAX_FRIEND_TCP_CONNECTIONS 6
#define TCP_CONNECTION_ANNOUNCE_TIMEOUT (TCP_CONNECTION_TIMEOUT)
#define RECOMMENDED_FRIEND_TCP_CONNECTIONS (MAX_FRIEND_TCP_CONNECTIONS / 2)
#define NUM_ONION_TCP_CONNECTIONS RECOMMENDED_FRIEND_TCP_CONNECTIONS
Functions
int send_packet_tcp_connection (TCP_Connections *tcp_c, int connections_number, const uint8_t *packet, uint16_t length)
int get_random_tcp_onion_conn_number (TCP_Connections *tcp_c)
int tcp_send_onion_request (TCP_Connections *tcp_c, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length)
int set_tcp_onion_status (TCP_Connections *tcp_c, _Bool status)
int tcp_send_oob_packet (TCP_Connections *tcp_c, unsigned int tcp_connections_number, const uint8_t *public_key, const uint8_t *packet, uint16_t length)
void set_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object)
void set_onion_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_onion_callback)(void *object, const uint8_t *data, uint16_t length), void *object)
void set_oob_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_oob_callback)(void *object, const uint8_t *public_key, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length), void *object)
int new_tcp_connection_to (TCP_Connections *tcp_c, const uint8_t *public_key, int id)
int kill_tcp_connection_to (TCP_Connections *tcp_c, int connections_number)
int set_tcp_connection_to_status (TCP_Connections *tcp_c, int connections_number, _Bool status)
unsigned int tcp_connection_to_online_tcp_relays (TCP_Connections *tcp_c, int connections_number)
int add_tcp_number_relay_connection (TCP_Connections *tcp_c, int connections_number, unsigned int tcp_connections_number)
int add_tcp_relay_connection (TCP_Connections *tcp_c, int connections_number, IP_Port ip_port, const uint8_t *relay_pk)
int add_tcp_relay_global (TCP_Connections *tcp_c, IP_Port ip_port, const uint8_t *relay_pk)
unsigned int tcp_copy_connected_relays (TCP_Connections *tcp_c, Node_format *tcp_relays, uint16_t max_num)
TCP_Connections * new_tcp_connections (const uint8_t *secret_key, TCP_Proxy_Info *proxy_info)
void do_tcp_connections (TCP_Connections *tcp_c)
void kill_tcp_connections (TCP_Connections *tcp_c)
Macro Definition Documentation
#define MAX_FRIEND_TCP_CONNECTIONS 6
Definition at line 42 of file TCP_connection.h.
Referenced by add_tcp_connection_to_conn(), do_friend_connections(), kill_tcp_connection_to(), online_tcp_connection_from_conn(), rm_tcp_connection_from_conn(), send_packet_tcp_connection(), set_tcp_connection_status(), set_tcp_connection_to_status(), and tcp_connection_in_conn().
#define NUM_ONION_TCP_CONNECTIONS RECOMMENDED_FRIEND_TCP_CONNECTIONS
Definition at line 52 of file TCP_connection.h.
Referenced by set_tcp_onion_status(), and tcp_relay_on_online().
#define RECOMMENDED_FRIEND_TCP_CONNECTIONS (MAX_FRIEND_TCP_CONNECTIONS / 2)
Definition at line 49 of file TCP_connection.h.
Referenced by add_tcp_relay_connection(), and kill_nonused_tcp().
#define TCP_CONN_CONNECTED 2
Definition at line 33 of file TCP_connection.h.
Referenced by add_tcp_number_relay_connection(), do_tcp_conns(), get_random_tcp_onion_conn_number(), kill_nonused_tcp(), kill_tcp_connection_to(), set_tcp_onion_status(), sleep_tcp_relay_connection(), tcp_copy_connected_relays(), tcp_relay_on_online(), tcp_send_onion_request(), and tcp_send_oob_packet().
#define TCP_CONN_NONE 0
Definition at line 29 of file TCP_connection.h.
Referenced by connections_number_not_valid(), create_connection(), create_tcp_connection(), tcp_connections_number_not_valid(), wipe_connection(), and wipe_tcp_connection().
#define TCP_CONN_SLEEPING 3
Definition at line 36 of file TCP_connection.h.
Referenced by add_tcp_number_relay_connection(), do_tcp_conns(), find_tcp_connection_relay(), kill_tcp_connection_to(), reconnect_tcp_relay_connection(), send_tcp_relay_routing_request(), set_tcp_connection_to_status(), set_tcp_onion_status(), sleep_tcp_relay_connection(), tcp_status_callback(), and unsleep_tcp_relay_connection().
#define TCP_CONN_VALID 1
Definition at line 30 of file TCP_connection.h.
Referenced by add_tcp_relay_instance(), do_tcp_conns(), new_tcp_connection_to(), reconnect_tcp_relay_connection(), set_tcp_connection_to_status(), and unsleep_tcp_relay_connection().
#define TCP_CONNECTION_ANNOUNCE_TIMEOUT (TCP_CONNECTION_TIMEOUT)
Definition at line 45 of file TCP_connection.h.
Referenced by do_tcp_conns(), and kill_nonused_tcp().
#define TCP_CONNECTIONS_STATUS_NONE 0
Definition at line 38 of file TCP_connection.h.
Referenced by add_tcp_connection_to_conn(), reconnect_tcp_relay_connection(), rm_tcp_connection_from_conn(), and sleep_tcp_relay_connection().
#define TCP_CONNECTIONS_STATUS_ONLINE 2
Definition at line 40 of file TCP_connection.h.
Referenced by kill_tcp_connection_to(), online_tcp_connection_from_conn(), send_packet_tcp_connection(), set_tcp_connection_to_status(), and tcp_status_callback().
#define TCP_CONNECTIONS_STATUS_REGISTERED 1
Definition at line 39 of file TCP_connection.h.
Referenced by send_packet_tcp_connection(), tcp_response_callback(), and tcp_status_callback().
Function Documentation
int add_tcp_number_relay_connection (TCP_Connections * tcp_c, int connections_number, unsigned int tcp_connections_number)
Definition at line 1064 of file TCP_connection.c.
References add_tcp_connection_to_conn(), TCP_con::connected_time, get_connection(), get_tcp_connection(), TCP_Connection_to::public_key, send_tcp_relay_routing_request(), TCP_Connection_to::status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, unix_time(), and TCP_con::unsleep.
Referenced by add_tcp_relay_connection(), and crypto_connection_add_source().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (con_to->status != TCP_CONN_SLEEPING && tcp_con->
      status == TCP_CONN_SLEEPING) {
        tcp_con->unsleep = 1;
    }
    if (add_tcp_connection_to_conn(con_to, tcp_connections_number) == -1)
        return -1;
    if (tcp_con->status == TCP_CONN_CONNECTED) {
        if (send_tcp_relay_routing_request(tcp_c, tcp_connections_number,
      con_to->public_key) == 0) {
            tcp_con->connected_time = unix_time();
        }
    }
    return 0;
}
int add_tcp_relay_connection (TCP_Connections * tcp_c, int connections_number, IP_Port ip_port, const uint8_t * relay_pk)
Definition at line 1099 of file TCP_connection.c.
References add_tcp_connection_to_conn(), add_tcp_number_relay_connection(), add_tcp_relay_instance(), find_tcp_connection_relay(), get_connection(), get_tcp_connection(), online_tcp_connection_from_conn(), and RECOMMENDED_FRIEND_TCP_CONNECTIONS.
Referenced by add_tcp_relay_peer(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    int tcp_connections_number = find_tcp_connection_relay(tcp_c, relay_pk);
    if (tcp_connections_number != -1) {
        return add_tcp_number_relay_connection(tcp_c, connections_number,
      tcp_connections_number);
    } else {
        if (online_tcp_connection_from_conn(con_to) >=
      RECOMMENDED_FRIEND_TCP_CONNECTIONS) {
            return -1;
        }
        int tcp_connections_number = add_tcp_relay_instance(tcp_c, ip_port, relay_pk)
      ;
        TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
        if (!tcp_con)
            return -1;
        if (add_tcp_connection_to_conn(con_to, tcp_connections_number) == -1) {
            return -1;
        }
        return 0;
    }
}
int add_tcp_relay_global (TCP_Connections * tcp_c, IP_Port ip_port, const uint8_t * relay_pk)
Definition at line 1046 of file TCP_connection.c.
References add_tcp_relay_instance(), and find_tcp_connection_relay().
Referenced by add_tcp_relay(), and START_TEST().
{
    int tcp_connections_number = find_tcp_connection_relay(tcp_c, relay_pk);
    if (tcp_connections_number != -1)
        return -1;
    if (add_tcp_relay_instance(tcp_c, ip_port, relay_pk) == -1)
        return -1;
    return 0;
}
void do_tcp_connections (TCP_Connections * tcp_c)
Definition at line 1346 of file TCP_connection.c.
References do_tcp_conns(), and kill_nonused_tcp().
Referenced by do_tcp(), and START_TEST().
{
    do_tcp_conns(tcp_c);
    kill_nonused_tcp(tcp_c);
}
int get_random_tcp_onion_conn_number (TCP_Connections * tcp_c)
Definition at line 285 of file TCP_connection.c.
References i, TCP_con::onion, TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by do_onion_client(), and get_random_tcp_con_number().
{
    unsigned int i, r = rand();
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        unsigned int index = ((i + r) % tcp_c->tcp_connections_length);
        if (tcp_c->tcp_connections[index].onion && tcp_c->
      tcp_connections[index].status == TCP_CONN_CONNECTED) {
            return index;
        }
    }
    return -1;
}
int kill_tcp_connection_to (TCP_Connections * tcp_c, int connections_number)
Definition at line 455 of file TCP_connection.c.
References TCP_con::connection, TCP_Connection_to::connection_id, TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, TCP_con::lock_count, MAX_FRIEND_TCP_CONNECTIONS, send_disconnect_request(), TCP_con::sleep_count, TCP_Connection_to::status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and wipe_connection().
Referenced by accept_crypto_connection(), crypto_kill(), new_crypto_connection(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection) {
            unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
            TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
            if (!tcp_con)
                continue;
            if (tcp_con->status == TCP_CONN_CONNECTED) {
                send_disconnect_request(tcp_con->
      connection, con_to->connections[i].connection_id);
            }
            if (con_to->connections[i].status ==
      TCP_CONNECTIONS_STATUS_ONLINE) {
                --tcp_con->lock_count;
                if (con_to->status == TCP_CONN_SLEEPING) {
                    --tcp_con->sleep_count;
                }
            }
        }
    }
    return wipe_connection(tcp_c, connections_number);
}
void kill_tcp_connections (TCP_Connections * tcp_c)
Definition at line 1352 of file TCP_connection.c.
References TCP_con::connection, TCP_Connections::connections, i, kill_TCP_connection(), TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by kill_net_crypto(), new_net_crypto(), and START_TEST().
{
    unsigned int i;
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        kill_TCP_connection(tcp_c->tcp_connections[i].
      connection);
    }
    free(tcp_c->tcp_connections);
    free(tcp_c->connections);
    free(tcp_c);
}
int new_tcp_connection_to (TCP_Connections * tcp_c, const uint8_t * public_key, int id)
Definition at line 433 of file TCP_connection.c.
References TCP_Connections::connections, create_connection(), find_tcp_connection_to(), TCP_Connection_to::id, TCP_Connection_to::public_key, TCP_Connection_to::status, and TCP_CONN_VALID.
Referenced by accept_crypto_connection(), new_crypto_connection(), and START_TEST().
{
    if (find_tcp_connection_to(tcp_c, public_key) != -1)
        return -1;
    int connections_number = create_connection(tcp_c);
    if (connections_number == -1)
        return -1;
    TCP_Connection_to *con_to = &tcp_c->connections[connections_number];
    con_to->status = TCP_CONN_VALID;
    memcpy(con_to->public_key, public_key, crypto_box_PUBLICKEYBYTES);
    con_to->id = id;
    return connections_number;
}
TCP_Connections* new_tcp_connections (const uint8_t * secret_key, TCP_Proxy_Info * proxy_info)
Definition at line 1251 of file TCP_connection.c.
References TCP_Connections::proxy_info, TCP_Connections::self_public_key, and TCP_Connections::self_secret_key.
Referenced by new_net_crypto(), and START_TEST().
{
    if (secret_key == NULL)
        return NULL;
    TCP_Connections *temp = calloc(1, sizeof(TCP_Connections));
    if (temp == NULL)
        return NULL;
    memcpy(temp->self_secret_key, secret_key, crypto_box_SECRETKEYBYTES);
    crypto_scalarmult_curve25519_base(temp->self_public_key, temp->
      self_secret_key);
    temp->proxy_info = *proxy_info;
    return temp;
}
int send_packet_tcp_connection (TCP_Connections * tcp_c, int connections_number, const uint8_t * packet, uint16_t length)
Definition at line 203 of file TCP_connection.c.
References TCP_con::connection, TCP_Connection_to::connection_id, TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::public_key, send_data(), send_oob_packet(), TCP_Connection_to::status, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and TCP_CONNECTIONS_STATUS_REGISTERED.
Referenced by send_packet_to(), START_TEST(), and tcp_handle_cookie_request().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to) {
        return -1;
    }
    //TODO: detect and kill bad relays.
    //TODO: thread safety?
    unsigned int i;
    int ret = -1;
    _Bool limit_reached = 0;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        uint32_t tcp_con_num = con_to->connections[i].tcp_connection;
        uint8_t status = con_to->connections[i].status;
        uint8_t connection_id = con_to->connections[i].connection_id;
        if (tcp_con_num && status == TCP_CONNECTIONS_STATUS_ONLINE) {
            tcp_con_num -= 1;
            TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_con_num);
            if (!tcp_con) {
                continue;
            }
            ret = send_data(tcp_con->connection, connection_id, packet, length);
            if (ret == 0) {
                limit_reached = 1;
            }
            if (ret == 1) {
                break;
            }
        }
    }
    if (ret == 1) {
        return 0;
    } else if (!limit_reached) {
        ret = 0;
        /* Send oob packets to all relays tied to the connection. */
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            uint32_t tcp_con_num = con_to->connections[i].
      tcp_connection;
            uint8_t status = con_to->connections[i].status;
            if (tcp_con_num && status == TCP_CONNECTIONS_STATUS_REGISTERED
      ) {
                tcp_con_num -= 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_con_num);
                if (!tcp_con) {
                    continue;
                }
                if (send_oob_packet(tcp_con->connection, con_to->
      public_key, packet, length) == 1) {
                    ret += 1;
                }
            }
        }
        if (ret >= 1) {
            return 0;
        } else {
            return -1;
        }
    } else {
        return -1;
    }
}
void set_onion_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, const uint8_t *data, uint16_t length) tcp_onion_callback, void * object)
Definition at line 366 of file TCP_connection.c.
References TCP_Connections::tcp_onion_callback, tcp_onion_callback(), and TCP_Connections::tcp_onion_callback_object.
Referenced by kill_onion_client(), and new_onion_client().
{
    tcp_c->tcp_onion_callback = tcp_onion_callback;
    tcp_c->tcp_onion_callback_object = object;
}
void set_oob_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, const uint8_t *public_key, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length) tcp_oob_callback, void * object)
Definition at line 357 of file TCP_connection.c.
References TCP_Connections::tcp_oob_callback, tcp_oob_callback(), and TCP_Connections::tcp_oob_callback_object.
Referenced by new_net_crypto(), and START_TEST().
{
    tcp_c->tcp_oob_callback = tcp_oob_callback;
    tcp_c->tcp_oob_callback_object = object;
}
void set_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, int id, const uint8_t *data, uint16_t length) tcp_data_callback, void * object)
Definition at line 348 of file TCP_connection.c.
References TCP_Connections::tcp_data_callback, tcp_data_callback(), and TCP_Connections::tcp_data_callback_object.
Referenced by new_net_crypto(), and START_TEST().
{
    tcp_c->tcp_data_callback = tcp_data_callback;
    tcp_c->tcp_data_callback_object = object;
}
int set_tcp_connection_to_status (TCP_Connections * tcp_c, int connections_number, _Bool status)
Definition at line 499 of file TCP_connection.c.
References TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, MAX_FRIEND_TCP_CONNECTIONS, TCP_con::sleep_count, TCP_Connection_to::status, TCP_con::status, TCP_CONN_SLEEPING, TCP_CONN_VALID, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and TCP_con::unsleep.
Referenced by do_tcp().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    if (status) {
        /* Conection is unsleeping. */
        if (con_to->status != TCP_CONN_SLEEPING)
            return -1;
        unsigned int i;
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            if (con_to->connections[i].tcp_connection) {
                unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c,
      tcp_connections_number);
                if (!tcp_con)
                    continue;
                if (tcp_con->status == TCP_CONN_SLEEPING) {
                    tcp_con->unsleep = 1;
                }
            }
        }
        con_to->status = TCP_CONN_VALID;
        return 0;
    } else {
        /* Conection is going to sleep. */
        if (con_to->status != TCP_CONN_VALID)
            return -1;
        unsigned int i;
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            if (con_to->connections[i].tcp_connection) {
                unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c,
      tcp_connections_number);
                if (!tcp_con)
                    continue;
                if (con_to->connections[i].status ==
      TCP_CONNECTIONS_STATUS_ONLINE) {
                    ++tcp_con->sleep_count;
                }
            }
        }
        con_to->status = TCP_CONN_SLEEPING;
        return 0;
    }
}
int set_tcp_onion_status (TCP_Connections * tcp_c, _Bool status)
Definition at line 1184 of file TCP_connection.c.
References get_tcp_connection(), i, NUM_ONION_TCP_CONNECTIONS, TCP_con::onion, TCP_Connections::onion_num_conns, TCP_Connections::onion_status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_Connections::tcp_connections_length, and TCP_con::unsleep.
Referenced by do_onion_client().
{
    if (tcp_c->onion_status == status)
        return -1;
    if (status) {
        unsigned int i;
        for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
            TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
            if (tcp_con) {
                if (tcp_con->status == TCP_CONN_CONNECTED && !tcp_con->
      onion) {
                    ++tcp_c->onion_num_conns;
                    tcp_con->onion = 1;
                }
            }
            if (tcp_c->onion_num_conns >=
      NUM_ONION_TCP_CONNECTIONS)
                break;
        }
        if (tcp_c->onion_num_conns < NUM_ONION_TCP_CONNECTIONS) {
            unsigned int wakeup = NUM_ONION_TCP_CONNECTIONS - tcp_c->
      onion_num_conns;
            for (i = 0; i < tcp_c->tcp_connections_length; ++
      i) {
                TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
                if (tcp_con) {
                    if (tcp_con->status == TCP_CONN_SLEEPING) {
                        tcp_con->unsleep = 1;
                    }
                }
                if (!wakeup)
                    break;
            }
        }
        tcp_c->onion_status = 1;
    } else {
        unsigned int i;
        for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
            TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
            if (tcp_con) {
                if (tcp_con->onion) {
                    --tcp_c->onion_num_conns;
                    tcp_con->onion = 0;
                }
            }
        }
        tcp_c->onion_status = 0;
    }
    return 0;
}
unsigned int tcp_connection_to_online_tcp_relays (TCP_Connections * tcp_c, int connections_number)
Definition at line 1133 of file TCP_connection.c.
References get_connection(), and online_tcp_connection_from_conn().
Referenced by crypto_connection_status(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return 0;
    return online_tcp_connection_from_conn(con_to);
}
unsigned int tcp_copy_connected_relays (TCP_Connections * tcp_c, Node_format * tcp_relays, uint16_t max_num)
Definition at line 1149 of file TCP_connection.c.
References TCP_con::connection, IP::family, get_tcp_connection(), i, IP_Port::ip, TCP_Client_Connection::ip_port, Node_format::ip_port, TCP_Client_Connection::public_key, make-funny-savefile::public_key, TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections_length, TCP_INET, and TCP_INET6.
Referenced by copy_connected_tcp_relays().
{
    unsigned int i, copied = 0, r = rand();
    for (i = 0; (i < tcp_c->tcp_connections_length) && (copied < max_num); ++
      i) {
        TCP_con *tcp_con = get_tcp_connection(tcp_c, (i + r) % tcp_c->
      tcp_connections_length);
        if (!tcp_con) {
            continue;
        }
        if (tcp_con->status == TCP_CONN_CONNECTED) {
            memcpy(tcp_relays[copied].public_key, tcp_con->connection->
      public_key, crypto_box_PUBLICKEYBYTES);
            tcp_relays[copied].ip_port = tcp_con->connection->
      ip_port;
            if (tcp_relays[copied].ip_port.ip.family == AF_INET) {
                tcp_relays[copied].ip_port.ip.family = TCP_INET;
            } else if (tcp_relays[copied].ip_port.ip.family == AF_INET6) {
                tcp_relays[copied].ip_port.ip.family = TCP_INET6;
            }
            ++copied;
        }
    }
    return copied;
}
int tcp_send_onion_request (TCP_Connections * tcp_c, unsigned int tcp_connections_number, const uint8_t * data, uint16_t length)
Definition at line 305 of file TCP_connection.c.
References TCP_con::connection, send_onion_request(), TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by send_tcp_onion_request().
{
    if (tcp_connections_number >= tcp_c->tcp_connections_length) {
        return -1;
    }
    if (tcp_c->tcp_connections[tcp_connections_number].status ==
      TCP_CONN_CONNECTED) {
        int ret = send_onion_request(tcp_c->tcp_connections[
      tcp_connections_number].connection, data, length);
        if (ret == 1)
            return 0;
    }
    return -1;
}
int tcp_send_oob_packet (TCP_Connections * tcp_c, unsigned int tcp_connections_number, const uint8_t * public_key, const uint8_t * packet, uint16_t length)
Definition at line 327 of file TCP_connection.c.
References TCP_con::connection, get_tcp_connection(), send_oob_packet(), TCP_con::status, and TCP_CONN_CONNECTED.
Referenced by tcp_oob_handle_cookie_request(), and tcp_oobdata_callback().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status != TCP_CONN_CONNECTED)
        return -1;
    int ret = send_oob_packet(tcp_con->connection,
      public_key, packet, length);
    if (ret == 1)
        return 0;
    return -1;
}