toxcore/logger.c File Reference
#include `logger.h`
*
#include `crypto_core.h`
*
#include <stdio.h>
*
#include <errno.h>
*
#include <stdlib.h>
*
#include <stdarg.h>
*
#include <inttypes.h>
*
#include <time.h>
*
#include <pthread.h>
*
Data Structures
struct logger
Macros
#define SFILE(FILE__M) (strrchr(FILE__M, '/') ? strrchr(FILE__M, '/') + 1 : FILE__M)
#define WIN_CR ``
Functions
char * strtime (char *dest, size_t max_len)
Logger * logger_new (const char *file_name, LOG_LEVEL level, const char *id)
void logger_kill (Logger *log)
void logger_kill_global (void)
void logger_set_global (Logger *log)
Logger * logger_get_global (void)
void logger_write (Logger *log, LOG_LEVEL level, const char *file, int line, const char *format,...)
Variables
Logger * global = NULL
const char * LOG_LEVEL_STR []
Macro Definition Documentation
#define SFILE(FILE__M) (strrchr(FILE__M, '/') ? strrchr(FILE__M, '/') + 1 : FILE__M)
Definition at line 42 of file logger.c.
Referenced by logger_write().
#define WIN_CR ``
Definition at line 43 of file logger.c.
Referenced by logger_new(), and logger_write().
Function Documentation
Logger* logger_get_global (void)
Definition at line 187 of file logger.c.
References global.
Referenced by tox_new().
{
#ifndef LOGGING /* Disabled */
    return NULL;
#endif
    return global;
}
void logger_kill (Logger * log)
Definition at line 148 of file logger.c.
References logger::id, logger::log_file, logger::msg, logger::mutex, logger::posstr, and logger::tstr.
Referenced by logger_kill_global().
{
#ifndef LOGGING /* Disabled */
    return;
#endif
    if (!log)
        return;
    pthread_mutex_lock(log->mutex);
    free(log->id);
    free(log->tstr);
    free(log->posstr);
    free(log->msg);
    if (fclose(log->log_file) != 0)
        perror("Could not close log file");
    pthread_mutex_unlock(log->mutex);
    pthread_mutex_destroy(log->mutex);
    free(log);
}
void logger_kill_global (void)
Definition at line 172 of file logger.c.
References logger_kill().
Referenced by tox_kill().
{
    logger_kill(global);
    global = NULL;
}
Logger* logger_new (const char * file_name, LOG_LEVEL level, const char * id)
Public Functions
Definition at line 88 of file logger.c.
References current_time_monotonic(), logger::id, logger::level, logger::log_file, logger::msg, logger::mutex, logger::posstr, random_int(), logger::start_time, strtime(), logger::tstr, and WIN_CR.
Referenced by tox_new().
{
#ifndef LOGGING /* Disabled */
    return NULL;
#endif
    Logger *retu = calloc(1, sizeof(Logger));
    if (!retu)
        return NULL;
    if (pthread_mutex_init(retu->mutex, NULL) != 0) {
        free(retu);
        return NULL;
    }
    if (!(retu->log_file = fopen(file_name, "ab"))) {
        fprintf(stderr, "Error opening logger file: %s; info: %s" WIN_CR "\n", file_name, strerror(
      errno));
        free(retu);
        pthread_mutex_destroy(retu->mutex);
        return NULL;
    }
    if (!(retu->tstr = calloc(16, sizeof (char))) ||
            !(retu->posstr = calloc(300, sizeof (char))) ||
            !(retu->msg = calloc(4096, sizeof (char))))
        goto FAILURE;
    if (id) {
        if (!(retu->id = calloc(strlen(id) + 1, 1)))
            goto FAILURE;
        strcpy(retu->id, id);
    } else {
        if (!(retu->id = malloc(8)))
            goto FAILURE;
        snprintf(retu->id, 8, "%u", random_int());
    }
    retu->level = level;
    retu->start_time = current_time_monotonic();
    fprintf(retu->log_file, "Successfully created and running logger id: %s; time: %s"
      WIN_CR "\n",
            retu->id, strtime(retu->tstr, 16));
    return retu;
FAILURE:
    fprintf(stderr, "Failed to create logger!" WIN_CR "\n");
    pthread_mutex_destroy(retu->mutex);
    fclose(retu->log_file);
    free(retu->tstr);
    free(retu->posstr);
    free(retu->msg);
    free(retu->id);
    free(retu);
    return NULL;
}
void logger_set_global (Logger * log)
Global logger setter and getter.
Definition at line 178 of file logger.c.
Referenced by tox_new().
{
#ifndef LOGGING /* Disabled */
    return;
#endif
    global = log;
}
void logger_write (Logger * log, LOG_LEVEL level, const char * file, int line, const char * format, ...)
Main write function. If logging disabled does nothing. If log == NULL uses global logger.
Definition at line 196 of file logger.c.
References global, logger::id, logger::level, logger::log_file, LOG_LEVEL_STR, logger::msg, logger::mutex, logger::posstr, SFILE, strtime(), logger::tstr, and WIN_CR.
{
#ifndef LOGGING /* Disabled */
    return;
#endif
    static const char *logger_format =
        "%s " /* Logger id string */
        "%-16s" /* Time string of format: %m:%d %H:%M:%S */
        "%u " /* Thread id */
        "%-5s " /* Logger lever string */
        "%-20s " /* File:line string */
        "- %s" /* Output message */
        WIN_CR "\n"; /* Every new print new line */
    Logger *this_log = log ? log : global;
    if (!this_log)
        return;
    /* Don't print levels lesser than set one */
    if (this_log->level > level)
        return;
    pthread_mutex_lock(this_log->mutex);
    /* Set position str */
    snprintf(this_log->posstr, 300, "%s:%d", SFILE(file), line);
    /* Set message */
    va_list args;
    va_start (args, format);
    vsnprintf(this_log->msg, 4096, format, args);
    va_end (args);
    fprintf(this_log->log_file, logger_format, this_log->id, strtime(this_log->
      tstr, 16), pthread_self(),
            LOG_LEVEL_STR[level], this_log->posstr, this_log->
      msg);
    fflush(this_log->log_file);
    pthread_mutex_unlock(this_log->mutex);
}
char* strtime (char * dest, size_t max_len)
Definition at line 72 of file logger.c.
Referenced by logger_new(), and logger_write().
{
    time_t timer;
    struct tm *tm_info;
    time(&timer);
    tm_info = localtime(&timer);
    strftime(dest, max_len, "%m:%d %H:%M:%S", tm_info);
    return dest;
}
Variable Documentation
Logger* global = NULL
Definition at line 62 of file logger.c.
Referenced by logger_get_global(), and logger_write().
const char* LOG_LEVEL_STR[]
Initial value:
= {
    [LOG_TRACE] = "TRACE",
    [LOG_DEBUG] = "DEBUG",
    [LOG_INFO] = "INFO" ,
    [LOG_WARNING] = "WARN" ,
    [LOG_ERROR] = "ERROR",
}
Definition at line 64 of file logger.c.
Referenced by logger_write().