toxav/rtp.h File Reference
#include <inttypes.h>
*
#include `../toxcore/Messenger.h`
*
Data Structures
struct _RTPHeader
struct _RTPExtHeader
struct _RTPMessage
struct _RTPSession
Macros
#define RTP_VERSION 2
#define MAX_SEQU_NUM 65535
#define MAX_RTP_SIZE 65535
Typedefs
typedef struct _RTPHeader RTPHeader
typedef struct _RTPExtHeader RTPExtHeader
typedef struct _RTPMessage RTPMessage
typedef struct _RTPSession RTPSession
Enumerations
enum RTPError { rtp_ErrorSending = -40
 }
Functions
RTPSession * rtp_new (int payload_type, Messenger *messenger, int friend_num)
void rtp_kill (RTPSession *session, Messenger *messenger)
int rtp_send_msg (RTPSession *session, Messenger *messenger, const uint8_t *data, uint16_t length)
void rtp_free_msg (RTPSession *session, RTPMessage *msg)
Macro Definition Documentation
#define MAX_RTP_SIZE 65535
Definition at line 32 of file rtp.h.
Referenced by msg_parse().
#define MAX_SEQU_NUM 65535
Definition at line 31 of file rtp.h.
Referenced by rtp_send_msg().
#define RTP_VERSION 2
rtp.h
Copyright (C) 2013 Tox project All Rights Reserved.
This file is part of Tox.
Tox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Tox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Tox. If not, see http://www.gnu.org/licenses/.
Definition at line 25 of file rtp.h.
Referenced by extract_header(), and rtp_new().
Typedef Documentation
typedef struct _RTPExtHeader RTPExtHeader
Standard rtp extension header.
typedef struct _RTPHeader RTPHeader
Standard rtp header
typedef struct _RTPMessage RTPMessage
Standard rtp message.
typedef struct _RTPSession RTPSession
RTP control session.
Enumeration Type Documentation
enum RTPError
Enumerator
rtp_ErrorSending
Definition at line 34 of file rtp.h.
             {
    rtp_ErrorSending = -40
} RTPError;
Function Documentation
void rtp_free_msg (RTPSession * session, RTPMessage * msg)
Dealloc msg.
Definition at line 446 of file rtp.c.
References _RTPMessage::ext_header, _RTPSession::ext_header, _RTPMessage::header, and _RTPExtHeader::table.
Referenced by cs_do(), jbuf_clear(), msg_parse(), queue_message(), and rtp_send_msg().
{
    if (!session) {
        if (msg->ext_header) {
            free (msg->ext_header->table);
            free (msg->ext_header);
        }
    } else {
        if (msg->ext_header && session->ext_header != msg->
      ext_header) {
            free (msg->ext_header->table);
            free (msg->ext_header);
        }
    }
    free (msg->header);
    free (msg);
}
void rtp_kill (RTPSession * session, Messenger * messenger)
Terminate the session.
Definition at line 514 of file rtp.c.
References _RTPSession::csrc, _RTPSession::dest, _RTPSession::ext_header, LOGGER_DEBUG, m_callback_rtp_packet(), and _RTPSession::prefix.
Referenced by toxav_kill(), toxav_kill_transmission(), and toxav_prepare_transmission().
{
    if (!session) return;
    m_callback_rtp_packet(messenger, session->dest, session->
      prefix, NULL, NULL);
    free (session->ext_header);
    free (session->csrc);
    LOGGER_DEBUG("Terminated RTP session: %p", session);
    /* And finally free session */
    free (session);
}
RTPSession* rtp_new (int payload_type, Messenger * messenger, int friend_num)
Must be called before calling any other rtp function.
Definition at line 464 of file rtp.c.
References _RTPSession::cc, _RTPSession::csrc, _RTPSession::dest, _RTPSession::ext_header, _RTPSession::extension, LOGGER_DEBUG, LOGGER_ERROR, LOGGER_WARNING, m_callback_rtp_packet(), _RTPSession::marker, _RTPSession::padding, _RTPSession::payload_type, _RTPSession::prefix, random_int(), _RTPSession::rsequnum, rtp_handle_packet(), RTP_VERSION, _RTPSession::sequnum, _RTPSession::ssrc, and _RTPSession::version.
Referenced by toxav_prepare_transmission().
{
    RTPSession *retu = calloc(1, sizeof(RTPSession));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    if (-1 == m_callback_rtp_packet(messenger, friend_num, payload_type,
      rtp_handle_packet, retu)) {
        LOGGER_ERROR("Error setting custom register handler for rtp session");
        free(retu);
        return NULL;
    }
    LOGGER_DEBUG("Registered packet handler: pt: %d; fid: %d", payload_type, friend_num);
    retu->version = RTP_VERSION; /* It's always 2 */
    retu->padding = 0; /* If some additional data is needed about the packet */
    retu->extension = 0; /* If extension to header is needed */
    retu->cc = 1; /* Amount of contributors */
    retu->csrc = NULL; /* Container */
    retu->ssrc = random_int();
    retu->marker = 0;
    retu->payload_type = payload_type % 128;
    retu->dest = friend_num;
    retu->rsequnum = retu->sequnum = 0;
    retu->ext_header = NULL; /* When needed allocate */
    if (!(retu->csrc = calloc(1, sizeof (uint32_t)))) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        free(retu);
        return NULL;
    }
    retu->csrc[0] = retu->ssrc; /* Set my ssrc to the list receive */
    /* Also set payload type as prefix */
    retu->prefix = payload_type;
    /*
     *
     */
    return retu;
}
int rtp_send_msg (RTPSession * session, Messenger * messenger, const uint8_t * data, uint16_t length)
Sends msg to _RTPSession::dest
Definition at line 425 of file rtp.c.
References _RTPMessage::data, _RTPSession::dest, _RTPMessage::length, LOGGER_WARNING, MAX_SEQU_NUM, rtp_ErrorSending, rtp_free_msg(), rtp_new_message(), send_custom_lossy_packet(), and _RTPSession::sequnum.
Referenced by toxav_send_rtp_payload().
{
    RTPMessage *msg = rtp_new_message (session, data, length);
    if (!msg) return -1;
    int ret = send_custom_lossy_packet(messenger, session->
      dest, msg->data, msg->length);
    if (0 != ret) {
        LOGGER_WARNING("Failed to send full packet (len: %d)! error: %i", length, ret);
        rtp_free_msg (session, msg);
        return rtp_ErrorSending;
    }
    /* Set sequ number */
    session->sequnum = session->sequnum >= MAX_SEQU_NUM ? 0 : session->
      sequnum + 1;
    rtp_free_msg (session, msg);
    return 0;
}