toxcore/ping_array.c File Reference
#include `ping_array.h`
*
#include `crypto_core.h`
*
#include `util.h`
*
Functions
static void clear_entry (Ping_Array *array, uint32_t index)
static void ping_array_clear_timedout (Ping_Array *array)
uint64_t ping_array_add (Ping_Array *array, const uint8_t *data, uint32_t length)
int ping_array_check (uint8_t *data, uint32_t length, Ping_Array *array, uint64_t ping_id)
int ping_array_init (Ping_Array *empty_array, uint32_t size, uint32_t timeout)
void ping_array_free_all (Ping_Array *array)
Function Documentation
static void clear_entry (Ping_Array * array, uint32_t index) [static]
Definition at line 33 of file ping_array.c.
References Ping_Array_Entry::data, Ping_Array::entries, Ping_Array_Entry::length, Ping_Array_Entry::ping_id, and Ping_Array_Entry::time.
Referenced by ping_array_add(), ping_array_check(), ping_array_clear_timedout(), and ping_array_free_all().
{
    free(array->entries[index].data);
    array->entries[index].data = NULL;
    array->entries[index].length =
        array->entries[index].time =
            array->entries[index].ping_id = 0;
}
uint64_t ping_array_add (Ping_Array * array, const uint8_t * data, uint32_t length)
Definition at line 62 of file ping_array.c.
References clear_entry(), Ping_Array_Entry::data, Ping_Array::entries, Ping_Array::last_added, Ping_Array::last_deleted, Ping_Array_Entry::length, ping_array_clear_timedout(), Ping_Array_Entry::ping_id, random_64b(), Ping_Array_Entry::time, Ping_Array::total_size, and unix_time().
Referenced by getnodes(), new_sendback(), and send_ping_request().
{
    ping_array_clear_timedout(array);
    uint32_t index = array->last_added % array->total_size;
    if (array->entries[index].data != NULL) {
        array->last_deleted = array->last_added - array->
      total_size;
        clear_entry(array, index);
    }
    array->entries[index].data = malloc(length);
    if (array->entries[index].data == NULL)
        return 0;
    memcpy(array->entries[index].data, data, length);
    array->entries[index].length = length;
    array->entries[index].time = unix_time();
    ++array->last_added;
    uint64_t ping_id = random_64b();
    ping_id /= array->total_size;
    ping_id *= array->total_size;
    ping_id += index;
    if (ping_id == 0)
        ping_id += array->total_size;
    array->entries[index].ping_id = ping_id;
    return ping_id;
}
int ping_array_check (uint8_t * data, uint32_t length, Ping_Array * array, uint64_t ping_id)
Definition at line 101 of file ping_array.c.
References clear_entry(), Ping_Array_Entry::data, Ping_Array::entries, is_timeout(), Ping_Array_Entry::length, Ping_Array_Entry::ping_id, Ping_Array_Entry::time, Ping_Array::timeout, and Ping_Array::total_size.
Referenced by check_sendback(), handle_ping_response(), and sent_getnode_to_node().
{
    if (ping_id == 0)
        return -1;
    uint32_t index = ping_id % array->total_size;
    if (array->entries[index].ping_id != ping_id)
        return -1;
    if (is_timeout(array->entries[index].time, array->
      timeout))
        return -1;
    if (array->entries[index].length > length)
        return -1;
    if (array->entries[index].data == NULL)
        return -1;
    memcpy(data, array->entries[index].data, array->entries[index].
      length);
    uint32_t len = array->entries[index].length;
    clear_entry(array, index);
    return len;
}
static void ping_array_clear_timedout (Ping_Array * array) [static]
Definition at line 44 of file ping_array.c.
References clear_entry(), Ping_Array::entries, is_timeout(), Ping_Array::last_added, Ping_Array::last_deleted, Ping_Array_Entry::time, Ping_Array::timeout, and Ping_Array::total_size.
Referenced by ping_array_add().
{
    while (array->last_deleted != array->last_added) {
        uint32_t index = array->last_deleted % array->total_size;
        if (!is_timeout(array->entries[index].time, array->
      timeout))
            break;
        clear_entry(array, index);
        ++array->last_deleted;
    }
}
void ping_array_free_all (Ping_Array * array)
Definition at line 151 of file ping_array.c.
References clear_entry(), Ping_Array::entries, Ping_Array::last_added, Ping_Array::last_deleted, and Ping_Array::total_size.
Referenced by kill_DHT(), kill_onion_client(), and kill_ping().
{
    while (array->last_deleted != array->last_added) {
        uint32_t index = array->last_deleted % array->total_size;
        clear_entry(array, index);
        ++array->last_deleted;
    }
    free(array->entries);
    array->entries = NULL;
}
int ping_array_init (Ping_Array * empty_array, uint32_t size, uint32_t timeout)
Definition at line 133 of file ping_array.c.
References Ping_Array::entries, Ping_Array::last_added, Ping_Array::last_deleted, Ping_Array::timeout, and Ping_Array::total_size.
Referenced by new_DHT(), new_onion_client(), and new_ping().
{
    if (size == 0 || timeout == 0 || empty_array == NULL)
        return -1;
    empty_array->entries = calloc(size, sizeof(Ping_Array_Entry));
    if (empty_array->entries == NULL)
        return -1;
    empty_array->last_deleted = empty_array->last_added = 0;
    empty_array->total_size = size;
    empty_array->timeout = timeout;
    return 0;
}