toxav/group.h File Reference
#include <opus.h>
*
#include `../toxcore/group.h`
*
Macros
#define GROUP_AUDIO_PACKET_ID 192
Functions
int add_av_groupchat (Group_Chats *g_c, void(*audio_callback)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *), void *userdata)
int join_av_groupchat (Group_Chats *g_c, int32_t friendnumber, const uint8_t *data, uint16_t length, void(*audio_callback)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *), void *userdata)
int group_send_audio (Group_Chats *g_c, int groupnumber, const int16_t *pcm, unsigned int samples, uint8_t channels, unsigned int sample_rate)
Macro Definition Documentation
#define GROUP_AUDIO_PACKET_ID 192
groupav.c
Copyright (C) 2014 Tox project All Rights Reserved.
This file is part of Tox.
Tox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Tox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Tox. If not, see http://www.gnu.org/licenses/.
Definition at line 26 of file group.h.
Referenced by groupchat_enable_av(), and send_audio_packet().
Function Documentation
int add_av_groupchat (Group_Chats * g_c, void(*)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *) audio_callback, void * userdata)
Definition at line 432 of file group.c.
References add_groupchat(), del_groupchat(), groupchat_enable_av(), and GROUPCHAT_TYPE_AV.
Referenced by toxav_add_av_groupchat().
{
    int groupnumber = add_groupchat(g_c, GROUPCHAT_TYPE_AV);
    if (groupnumber == -1) {
        return -1;
    }
    if (groupchat_enable_av(g_c, groupnumber, audio_callback, userdata) == -1) {
        del_groupchat(g_c, groupnumber);
        return -1;
    }
    return groupnumber;
}
int group_send_audio (Group_Chats * g_c, int groupnumber, const int16_t * pcm, unsigned int samples, uint8_t channels, unsigned int sample_rate)
Definition at line 502 of file group.c.
References Group_AV::audio_bitrate, Group_AV::audio_channels, Group_AV::audio_encoder, Group_AV::audio_sample_rate, group_get_object(), recreate_encoder(), and send_audio_packet().
Referenced by toxav_group_send_audio().
{
    Group_AV *group_av = group_get_object(g_c, groupnumber);
    if (!group_av)
        return -1;
    if (channels != 1 && channels != 2)
        return -1;
    if (sample_rate != 8000 && sample_rate != 12000 && sample_rate != 16000 && sample_rate != 24000 &&
      sample_rate != 48000)
        return -1;
    if (!group_av->audio_encoder || group_av->audio_channels != channels ||
      group_av->audio_sample_rate != sample_rate) {
        group_av->audio_channels = channels;
        group_av->audio_sample_rate = sample_rate;
        if (channels == 1) {
            group_av->audio_bitrate = 32000; //TODO: add way of adjusting bitrate
        } else {
            group_av->audio_bitrate = 64000; //TODO: add way of adjusting bitrate
        }
        if (recreate_encoder(group_av) == -1)
            return -1;
    }
    uint8_t encoded[1024];
    int32_t size = opus_encode(group_av->audio_encoder, pcm, samples, encoded, sizeof(encoded)
      );
    if (size <= 0)
        return -1;
    return send_audio_packet(g_c, groupnumber, encoded, size);
}
int join_av_groupchat (Group_Chats * g_c, int32_t friendnumber, const uint8_t * data, uint16_t length, void(*)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *) audio_callback, void * userdata)
Definition at line 454 of file group.c.
References del_groupchat(), groupchat_enable_av(), GROUPCHAT_TYPE_AV, and join_groupchat().
Referenced by toxav_join_av_groupchat().
{
    int groupnumber = join_groupchat(g_c, friendnumber,
      GROUPCHAT_TYPE_AV, data, length);
    if (groupnumber == -1) {
        return -1;
    }
    if (groupchat_enable_av(g_c, groupnumber, audio_callback, userdata) == -1) {
        del_groupchat(g_c, groupnumber);
        return -1;
    }
    return groupnumber;
}