toxcore/friend_requests.h File Reference
#include `friend_connection.h`
*
Data Structures
struct Friend_Requests
Macros
#define MAX_FRIEND_REQUEST_DATA_SIZE (ONION_CLIENT_MAX_DATA_SIZE - (1 + sizeof(uint32_t)))
#define MAX_RECEIVED_STORED 32
Functions
void set_nospam (Friend_Requests *fr, uint32_t num)
uint32_t get_nospam (const Friend_Requests *fr)
int remove_request_received (Friend_Requests *fr, const uint8_t *real_pk)
void callback_friendrequest (Friend_Requests *fr, void(*function)(void *, const uint8_t *, const uint8_t *, size_t, void *), void *object, void *userdata)
void set_filter_function (Friend_Requests *fr, int(*function)(const uint8_t *, void *), void *userdata)
void friendreq_init (Friend_Requests *fr, Friend_Connections *fr_c)
Macro Definition Documentation
#define MAX_FRIEND_REQUEST_DATA_SIZE (ONION_CLIENT_MAX_DATA_SIZE - (1 + sizeof(uint32_t)))
Definition at line 29 of file friend_requests.h.
Referenced by m_addfriend().
#define MAX_RECEIVED_STORED 32
Definition at line 44 of file friend_requests.h.
Referenced by addto_receivedlist(), remove_request_received(), and request_received().
Function Documentation
void callback_friendrequest (Friend_Requests * fr, void(*)(void *, const uint8_t *, const uint8_t *, size_t, void *) function, void * object, void * userdata)
Definition at line 45 of file friend_requests.c.
References Friend_Requests::handle_friendrequest, Friend_Requests::handle_friendrequest_isset, Friend_Requests::handle_friendrequest_object, and Friend_Requests::handle_friendrequest_userdata.
Referenced by m_callback_friendrequest().
{
    fr->handle_friendrequest = function;
    fr->handle_friendrequest_isset = 1;
    fr->handle_friendrequest_object = object;
    fr->handle_friendrequest_userdata = userdata;
}
void friendreq_init (Friend_Requests * fr, Friend_Connections * fr_c)
Definition at line 141 of file friend_requests.c.
References friendreq_handlepacket(), and set_friend_request_callback().
Referenced by new_messenger().
{
    set_friend_request_callback(fr_c, &
      friendreq_handlepacket, fr);
}
uint32_t get_nospam (const Friend_Requests * fr)
Definition at line 38 of file friend_requests.c.
References Friend_Requests::nospam.
Referenced by getaddress(), messenger_save(), and tox_self_get_nospam().
{
    return fr->nospam;
}
int remove_request_received (Friend_Requests * fr, const uint8_t * real_pk)
Definition at line 91 of file friend_requests.c.
References i, id_equal(), MAX_RECEIVED_STORED, and Friend_Requests::received_requests.
Referenced by m_delfriend().
{
    uint32_t i;
    for (i = 0; i < MAX_RECEIVED_STORED; ++i) {
        if (id_equal(fr->received_requests[i], real_pk)) {
            memset(fr->received_requests[i], 0, crypto_box_PUBLICKEYBYTES);
            return 0;
        }
    }
    return -1;
}
void set_filter_function (Friend_Requests * fr, int(*)(const uint8_t *, void *) function, void * userdata)
Definition at line 54 of file friend_requests.c.
References Friend_Requests::filter_function, and Friend_Requests::filter_function_userdata.
Referenced by new_messenger().
{
    fr->filter_function = function;
    fr->filter_function_userdata = userdata;
}
void set_nospam (Friend_Requests * fr, uint32_t num)
Definition at line 33 of file friend_requests.c.
References Friend_Requests::nospam, and num.
Referenced by messenger_load_state_callback(), new_messenger(), and tox_self_set_nospam().
{
    fr->nospam = num;
}