toxcore/TCP_server.h File Reference
#include `crypto_core.h`
*
#include `onion.h`
*
#include `list.h`
*
Data Structures
struct TCP_Priority_List
struct TCP_Secure_Connection
struct TCP_Server
Macros
#define MAX_INCOMMING_CONNECTIONS 256
#define TCP_MAX_BACKLOG MAX_INCOMMING_CONNECTIONS
#define MAX_PACKET_SIZE 2048
#define TCP_HANDSHAKE_PLAIN_SIZE (crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES)
#define TCP_SERVER_HANDSHAKE_SIZE (crypto_box_NONCEBYTES + TCP_HANDSHAKE_PLAIN_SIZE + crypto_box_MACBYTES)
#define TCP_CLIENT_HANDSHAKE_SIZE (crypto_box_PUBLICKEYBYTES + TCP_SERVER_HANDSHAKE_SIZE)
#define TCP_MAX_OOB_DATA_LENGTH 1024
#define NUM_RESERVED_PORTS 16
#define NUM_CLIENT_CONNECTIONS (256 - NUM_RESERVED_PORTS)
#define TCP_PACKET_ROUTING_REQUEST 0
#define TCP_PACKET_ROUTING_RESPONSE 1
#define TCP_PACKET_CONNECTION_NOTIFICATION 2
#define TCP_PACKET_DISCONNECT_NOTIFICATION 3
#define TCP_PACKET_PING 4
#define TCP_PACKET_PONG 5
#define TCP_PACKET_OOB_SEND 6
#define TCP_PACKET_OOB_RECV 7
#define TCP_PACKET_ONION_REQUEST 8
#define TCP_PACKET_ONION_RESPONSE 9
#define ARRAY_ENTRY_SIZE 6
#define TCP_PING_FREQUENCY 30
#define TCP_PING_TIMEOUT 10
Typedefs
typedef struct TCP_Priority_List TCP_Priority_List
typedef struct
*
TCP_Secure_Connection TCP_Secure_Connection
Enumerations
enum { TCP_STATUS_NO_STATUS,
TCP_STATUS_CONNECTED,
TCP_STATUS_UNCONFIRMED,
TCP_STATUS_CONFIRMED
 }
Functions
TCP_Server * new_TCP_server (uint8_t ipv6_enabled, uint16_t num_sockets, const uint16_t *ports, const uint8_t *secret_key, Onion *onion)
void do_TCP_server (TCP_Server *TCP_server)
void kill_TCP_server (TCP_Server *TCP_server)
unsigned int TCP_socket_data_recv_buffer (sock_t sock)
uint16_t read_TCP_length (sock_t sock)
int read_TCP_packet (sock_t sock, uint8_t *data, uint16_t length)
int read_packet_TCP_secure_connection (sock_t sock, uint16_t *next_packet_length, const uint8_t *shared_key, uint8_t *recv_nonce, uint8_t *data, uint16_t max_len)
Macro Definition Documentation
#define ARRAY_ENTRY_SIZE 6
Definition at line 63 of file TCP_server.h.
#define MAX_INCOMMING_CONNECTIONS 256
Definition at line 38 of file TCP_server.h.
Referenced by accept_connection(), do_incoming(), do_TCP_incomming(), and do_TCP_unconfirmed().
#define MAX_PACKET_SIZE 2048
Definition at line 42 of file TCP_server.h.
Referenced by do_confirmed_recv(), do_confirmed_TCP(), do_unconfirmed(), proxy_http_generate_connection_request(), read_TCP_length(), and write_packet_TCP_secure_connection().
#define NUM_CLIENT_CONNECTIONS (256 - NUM_RESERVED_PORTS)
Definition at line 50 of file TCP_server.h.
Referenced by handle_TCP_packet(), handle_TCP_routing_req(), kill_accepted(), rm_connection_index(), send_data(), send_disconnect_request(), and set_tcp_connection_number().
#define NUM_RESERVED_PORTS 16
Definition at line 49 of file TCP_server.h.
Referenced by handle_TCP_packet(), handle_TCP_routing_req(), send_connect_notification(), send_data(), send_disconnect_notification(), and send_disconnect_request().
#define TCP_CLIENT_HANDSHAKE_SIZE (crypto_box_PUBLICKEYBYTES + TCP_SERVER_HANDSHAKE_SIZE)
Definition at line 46 of file TCP_server.h.
Referenced by handle_TCP_handshake(), new_TCP_con(), read_connection_handshake(), and START_TEST().
#define TCP_HANDSHAKE_PLAIN_SIZE (crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES)
Definition at line 44 of file TCP_server.h.
Referenced by handle_TCP_handshake(), new_TCP_con(), and START_TEST().
#define TCP_MAX_BACKLOG MAX_INCOMMING_CONNECTIONS
Definition at line 40 of file TCP_server.h.
Referenced by new_listening_TCP_socket().
#define TCP_MAX_OOB_DATA_LENGTH 1024
Definition at line 47 of file TCP_server.h.
Referenced by handle_TCP_oob_send(), and send_oob_packet().
#define TCP_PACKET_CONNECTION_NOTIFICATION 2
Definition at line 54 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_connect_notification().
#define TCP_PACKET_DISCONNECT_NOTIFICATION 3
Definition at line 55 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_disconnect_notification().
#define TCP_PACKET_ONION_REQUEST 8
Definition at line 60 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_onion_request().
#define TCP_PACKET_ONION_RESPONSE 9
Definition at line 61 of file TCP_server.h.
Referenced by handle_onion_recv_1(), and handle_TCP_packet().
#define TCP_PACKET_OOB_RECV 7
Definition at line 59 of file TCP_server.h.
Referenced by handle_TCP_oob_send(), and handle_TCP_packet().
#define TCP_PACKET_OOB_SEND 6
Definition at line 58 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_oob_packet().
#define TCP_PACKET_PING 4
Definition at line 56 of file TCP_server.h.
Referenced by do_TCP_confirmed(), handle_TCP_packet(), and send_ping_request().
#define TCP_PACKET_PONG 5
Definition at line 57 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_ping_response().
#define TCP_PACKET_ROUTING_REQUEST 0
Definition at line 52 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_routing_request().
#define TCP_PACKET_ROUTING_RESPONSE 1
Definition at line 53 of file TCP_server.h.
Referenced by handle_TCP_packet(), and send_routing_response().
#define TCP_PING_FREQUENCY 30
Definition at line 66 of file TCP_server.h.
Referenced by do_confirmed_TCP(), and do_TCP_confirmed().
#define TCP_PING_TIMEOUT 10
Definition at line 67 of file TCP_server.h.
Referenced by do_confirmed_TCP(), and do_TCP_confirmed().
#define TCP_SERVER_HANDSHAKE_SIZE (crypto_box_NONCEBYTES + TCP_HANDSHAKE_PLAIN_SIZE + crypto_box_MACBYTES)
Definition at line 45 of file TCP_server.h.
Referenced by do_TCP_connection(), handle_handshake(), handle_TCP_handshake(), new_TCP_con(), and START_TEST().
Typedef Documentation
typedef struct TCP_Priority_List TCP_Priority_List
Definition at line 83 of file TCP_server.h.
typedef struct TCP_Secure_Connection TCP_Secure_Connection
Enumeration Type Documentation
anonymous enum
Enumerator
TCP_STATUS_NO_STATUS
TCP_STATUS_CONNECTED
TCP_STATUS_UNCONFIRMED
TCP_STATUS_CONFIRMED
Definition at line 76 of file TCP_server.h.
     {
    TCP_STATUS_NO_STATUS,
    TCP_STATUS_CONNECTED,
    TCP_STATUS_UNCONFIRMED,
    TCP_STATUS_CONFIRMED,
};
Function Documentation
void do_TCP_server (TCP_Server * TCP_server)
Definition at line 1305 of file TCP_server.c.
References do_TCP_accept_new(), do_TCP_confirmed(), do_TCP_incomming(), do_TCP_unconfirmed(), and unix_time_update().
Referenced by do_messenger(), main(), new_TCP_con(), and START_TEST().
{
    unix_time_update();
#ifdef TCP_SERVER_USE_EPOLL
    do_TCP_epoll(TCP_server);
#else
    do_TCP_accept_new(TCP_server);
    do_TCP_incomming(TCP_server);
    do_TCP_unconfirmed(TCP_server);
#endif
    do_TCP_confirmed(TCP_server);
}
void kill_TCP_server (TCP_Server * TCP_server)
Definition at line 1321 of file TCP_server.c.
References TCP_Server::accepted_connection_array, TCP_Server::accepted_key_list, bs_list_free(), i, kill_sock(), TCP_Server::num_listening_socks, TCP_Server::onion, set_callback_handle_recv_1(), and TCP_Server::socks_listening.
Referenced by kill_messenger(), and START_TEST().
{
    uint32_t i;
    for (i = 0; i < TCP_server->num_listening_socks; ++i) {
        kill_sock(TCP_server->socks_listening[i]);
    }
    if (TCP_server->onion) {
        set_callback_handle_recv_1(TCP_server->onion, NULL, NULL);
    }
    bs_list_free(&TCP_server->accepted_key_list);
#ifdef TCP_SERVER_USE_EPOLL
    close(TCP_server->efd);
#endif
    free(TCP_server->socks_listening);
    free(TCP_server->accepted_connection_array);
    free(TCP_server);
}
TCP_Server* new_TCP_server (uint8_t ipv6_enabled, uint16_t num_sockets, const uint16_t * ports, const uint8_t * secret_key, Onion * onion)
Definition at line 942 of file TCP_server.c.
References TCP_Server::accepted_key_list, bs_list_init(), handle_onion_recv_1(), i, networking_at_startup(), new_listening_TCP_socket(), TCP_Server::num_listening_socks, TCP_Server::onion, TCP_Server::public_key, TCP_Server::secret_key, set_callback_handle_recv_1(), sock, sock_valid(), and TCP_Server::socks_listening.
Referenced by main(), new_messenger(), and START_TEST().
{
    if (num_sockets == 0 || ports == NULL)
        return NULL;
    if (networking_at_startup() != 0) {
        return NULL;
    }
    TCP_Server *temp = calloc(1, sizeof(TCP_Server));
    if (temp == NULL)
        return NULL;
    temp->socks_listening = calloc(num_sockets, sizeof(sock_t));
    if (temp->socks_listening == NULL) {
        free(temp);
        return NULL;
    }
#ifdef TCP_SERVER_USE_EPOLL
    temp->efd = epoll_create(8);
    if (temp->efd == -1) {
        free(temp->socks_listening);
        free(temp);
        return NULL;
    }
#endif
    uint8_t family;
    if (ipv6_enabled) {
        family = AF_INET6;
    } else {
        family = AF_INET;
    }
    uint32_t i;
#ifdef TCP_SERVER_USE_EPOLL
    struct epoll_event ev;
#endif
    for (i = 0; i < num_sockets; ++i) {
        sock_t sock = new_listening_TCP_socket(family,
      ports[i]);
        if (sock_valid(sock)) {
#ifdef TCP_SERVER_USE_EPOLL
            ev.events = EPOLLIN | EPOLLET;
            ev.data.u64 = sock | ((uint64_t)TCP_SOCKET_LISTENING << 32);
            if (epoll_ctl(temp->efd, EPOLL_CTL_ADD, sock, &ev) == -1) {
                continue;
            }
#endif
            temp->socks_listening[temp->num_listening_socks] =
      sock;
            ++temp->num_listening_socks;
        }
    }
    if (temp->num_listening_socks == 0) {
        free(temp->socks_listening);
        free(temp);
        return NULL;
    }
    if (onion) {
        temp->onion = onion;
        set_callback_handle_recv_1(onion, &
      handle_onion_recv_1, temp);
    }
    memcpy(temp->secret_key, secret_key, crypto_box_SECRETKEYBYTES);
    crypto_scalarmult_curve25519_base(temp->public_key, temp->
      secret_key);
    bs_list_init(&temp->accepted_key_list, crypto_box_PUBLICKEYBYTES, 8);
    return temp;
}
int read_packet_TCP_secure_connection (sock_t sock, uint16_t * next_packet_length, const uint8_t * shared_key, uint8_t * recv_nonce, uint8_t * data, uint16_t max_len)
Definition at line 256 of file TCP_server.c.
References decrypt_data_symmetric(), increment_nonce(), read_TCP_length(), and read_TCP_packet().
Referenced by do_confirmed_recv(), do_confirmed_TCP(), and do_unconfirmed().
{
    if (*next_packet_length == 0) {
        uint16_t len = read_TCP_length(sock);
        if (len == (uint16_t)~0)
            return -1;
        if (len == 0)
            return 0;
        *next_packet_length = len;
    }
    if (max_len + crypto_box_MACBYTES < *next_packet_length)
        return -1;
    uint8_t data_encrypted[*next_packet_length];
    int len_packet = read_TCP_packet(sock, data_encrypted, *next_packet_length);
    if (len_packet != *next_packet_length)
        return 0;
    *next_packet_length = 0;
    int len = decrypt_data_symmetric(shared_key, recv_nonce, data_encrypted,
      len_packet, data);
    if (len + crypto_box_MACBYTES != len_packet)
        return -1;
    increment_nonce(recv_nonce);
    return len;
}
uint16_t read_TCP_length (sock_t sock)
Definition at line 204 of file TCP_server.c.
References MAX_PACKET_SIZE, and TCP_socket_data_recv_buffer().
Referenced by read_packet_TCP_secure_connection().
{
    unsigned int count = TCP_socket_data_recv_buffer(
      sock);
    if (count >= sizeof(uint16_t)) {
        uint16_t length;
        int len = recv(sock, (uint8_t *)&length, sizeof(uint16_t), MSG_NOSIGNAL);
        if (len != sizeof(uint16_t)) {
            fprintf(stderr, "FAIL recv packet\n");
            return 0;
        }
        length = ntohs(length);
        if (length > MAX_PACKET_SIZE) {
            return ~0;
        }
        return length;
    }
    return 0;
}
int read_TCP_packet (sock_t sock, uint8_t * data, uint16_t length)
Definition at line 234 of file TCP_server.c.
References TCP_socket_data_recv_buffer().
Referenced by do_TCP_connection(), proxy_http_read_connection_response(), proxy_socks5_read_connection_response(), read_connection_handshake(), read_packet_TCP_secure_connection(), and socks5_read_handshake_response().
{
    unsigned int count = TCP_socket_data_recv_buffer(
      sock);
    if (count >= length) {
        int len = recv(sock, data, length, MSG_NOSIGNAL);
        if (len != length) {
            fprintf(stderr, "FAIL recv packet\n");
            return -1;
        }
        return len;
    }
    return -1;
}
unsigned int TCP_socket_data_recv_buffer (sock_t sock)
Definition at line 184 of file TCP_server.c.
Referenced by proxy_http_read_connection_response(), read_TCP_length(), and read_TCP_packet().
{
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    unsigned long count = 0;
    ioctlsocket(sock, FIONREAD, &count);
#else
    int count = 0;
    ioctl(sock, FIONREAD, &count);
#endif
    return count;
}