toxav/rtp.c File Reference
#include `rtp.h`
*
#include `../toxcore/logger.h`
*
#include `../toxcore/util.h`
*
#include <stdlib.h>
*
Macros
#define size_32 4
#define ADD_FLAG_VERSION(_h, _v) do { (_h->flags) &= 0x3F; (_h->flags) |= (((_v) << 6) & 0xC0); } while(0)
#define ADD_FLAG_PADDING(_h, _v) do { if (_v > 0) _v = 1; (_h->flags) &= 0xDF; (_h->flags) |= (((_v) << 5) & 0x20); } while(0)
#define ADD_FLAG_EXTENSION(_h, _v) do { if (_v > 0) _v = 1; (_h->flags) &= 0xEF;(_h->flags) |= (((_v) << 4) & 0x10); } while(0)
#define ADD_FLAG_CSRCC(_h, _v) do { (_h->flags) &= 0xF0; (_h->flags) |= ((_v) & 0x0F); } while(0)
#define ADD_SETTING_MARKER(_h, _v) do { if (_v > 1) _v = 1; (_h->marker_payloadt) &= 0x7F; (_h->marker_payloadt) |= (((_v) << 7) /*& 0x80 */); } while(0)
#define ADD_SETTING_PAYLOAD(_h, _v) do { if (_v > 127) _v = 127; (_h->marker_payloadt) &= 0x80; (_h->marker_payloadt) |= ((_v) /* & 0x7F */); } while(0)
#define GET_FLAG_VERSION(_h) ((_h->flags & 0xd0) >> 6)
#define GET_FLAG_PADDING(_h) ((_h->flags & 0x20) >> 5)
#define GET_FLAG_EXTENSION(_h) ((_h->flags & 0x10) >> 4)
#define GET_FLAG_CSRCC(_h) (_h->flags & 0x0f)
#define GET_SETTING_MARKER(_h) ((_h->marker_payloadt) >> 7)
#define GET_SETTING_PAYLOAD(_h) ((_h->marker_payloadt) & 0x7f)
Functions
void queue_message (RTPSession *_session, RTPMessage *_msg)
static int check_late_message (RTPSession *session, RTPMessage *msg)
RTPHeader * extract_header (const uint8_t *payload, int length)
RTPExtHeader * extract_ext_header (const uint8_t *payload, uint16_t length)
uint8_t * add_header (RTPHeader *header, uint8_t *payload)
uint8_t * add_ext_header (RTPExtHeader *header, uint8_t *payload)
RTPHeader * build_header (RTPSession *session)
RTPMessage * msg_parse (const uint8_t *data, int length)
int rtp_handle_packet (Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t length, void *object)
RTPMessage * rtp_new_message (RTPSession *session, const uint8_t *data, uint32_t length)
int rtp_send_msg (RTPSession *session, Messenger *messenger, const uint8_t *data, uint16_t length)
void rtp_free_msg (RTPSession *session, RTPMessage *msg)
RTPSession * rtp_new (int payload_type, Messenger *messenger, int friend_num)
void rtp_kill (RTPSession *session, Messenger *messenger)
Macro Definition Documentation
#define ADD_FLAG_CSRCC(_h, _v) do { (_h->flags) &= 0xF0; (_h->flags) |= ((_v) & 0x0F); } while(0)
Definition at line 38 of file rtp.c.
Referenced by build_header().
#define ADD_FLAG_EXTENSION(_h, _v) do { if (_v > 0) _v = 1; (_h->flags) &= 0xEF;(_h->flags) |= (((_v) << 4) & 0x10); } while(0)
Definition at line 37 of file rtp.c.
Referenced by build_header().
#define ADD_FLAG_PADDING(_h, _v) do { if (_v > 0) _v = 1; (_h->flags) &= 0xDF; (_h->flags) |= (((_v) << 5) & 0x20); } while(0)
Definition at line 36 of file rtp.c.
Referenced by build_header().
#define ADD_FLAG_VERSION(_h, _v) do { (_h->flags) &= 0x3F; (_h->flags) |= (((_v) << 6) & 0xC0); } while(0)
Definition at line 35 of file rtp.c.
Referenced by build_header().
#define ADD_SETTING_MARKER(_h, _v) do { if (_v > 1) _v = 1; (_h->marker_payloadt) &= 0x7F; (_h->marker_payloadt) |= (((_v) << 7) /*& 0x80 */); } while(0)
Definition at line 39 of file rtp.c.
Referenced by build_header().
#define ADD_SETTING_PAYLOAD(_h, _v) do { if (_v > 127) _v = 127; (_h->marker_payloadt) &= 0x80; (_h->marker_payloadt) |= ((_v) /* & 0x7F */); } while(0)
Definition at line 40 of file rtp.c.
Referenced by build_header().
#define GET_FLAG_CSRCC(_h) (_h->flags & 0x0f)
Definition at line 45 of file rtp.c.
Referenced by add_header(), and extract_header().
#define GET_FLAG_EXTENSION(_h) ((_h->flags & 0x10) >> 4)
Definition at line 44 of file rtp.c.
Referenced by msg_parse().
#define GET_FLAG_PADDING(_h) ((_h->flags & 0x20) >> 5)
Definition at line 43 of file rtp.c.
#define GET_FLAG_VERSION(_h) ((_h->flags & 0xd0) >> 6)
Definition at line 42 of file rtp.c.
Referenced by extract_header().
#define GET_SETTING_MARKER(_h) ((_h->marker_payloadt) >> 7)
Definition at line 46 of file rtp.c.
#define GET_SETTING_PAYLOAD(_h) ((_h->marker_payloadt) & 0x7f)
Definition at line 47 of file rtp.c.
#define size_32 4
Definition at line 33 of file rtp.c.
Referenced by build_header(), msg_parse(), and rtp_new_message().
Function Documentation
uint8_t* add_ext_header (RTPExtHeader * header, uint8_t * payload)
Adds extension header to payload. Make sure payload has enough space.
Definition at line 230 of file rtp.c.
References _RTPExtHeader::length, _RTPExtHeader::table, _RTPExtHeader::type, and x.
Referenced by rtp_new_message().
{
    uint8_t *it = payload;
    uint16_t length;
    uint16_t type;
    uint32_t entry;
    length = htons(header->length);
    memcpy(it, &length, sizeof(length));
    it += 2;
    type = htons(header->type);
    memcpy(it, &type, sizeof(type));
    it -= 2; /* Return to 0 position */
    if (header->table) {
        uint16_t x;
        for (x = 0; x < header->length; x++) {
            it += 4;
            entry = htonl(header->table[x]);
            memcpy(it, &entry, sizeof(entry));
        }
    }
    return it + 4;
}
uint8_t* add_header (RTPHeader * header, uint8_t * payload)
Adds header to payload. Make sure payload has enough space.
Definition at line 189 of file rtp.c.
References _RTPHeader::csrc, _RTPHeader::flags, GET_FLAG_CSRCC, _RTPHeader::marker_payloadt, _RTPHeader::sequnum, _RTPHeader::ssrc, _RTPHeader::timestamp, and x.
Referenced by rtp_new_message().
{
    uint8_t cc = GET_FLAG_CSRCC (header);
    uint8_t *it = payload;
    uint16_t sequnum;
    uint32_t timestamp;
    uint32_t ssrc;
    uint32_t csrc;
    /* Add sequence number first */
    sequnum = htons(header->sequnum);
    memcpy(it, &sequnum, sizeof(sequnum));
    it += 2;
    *it = header->flags;
    ++it;
    *it = header->marker_payloadt;
    ++it;
    timestamp = htonl(header->timestamp);
    memcpy(it, &timestamp, sizeof(timestamp));
    it += 4;
    ssrc = htonl(header->ssrc);
    memcpy(it, &ssrc, sizeof(ssrc));
    uint8_t x;
    for (x = 0; x < cc; x++) {
        it += 4;
        csrc = htonl(header->csrc[x]);
        memcpy(it, &csrc, sizeof(csrc));
    }
    return it + 4;
}
RTPHeader* build_header (RTPSession * session)
Builds header from control session values.
Definition at line 261 of file rtp.c.
References ADD_FLAG_CSRCC, ADD_FLAG_EXTENSION, ADD_FLAG_PADDING, ADD_FLAG_VERSION, ADD_SETTING_MARKER, ADD_SETTING_PAYLOAD, _RTPSession::cc, _RTPHeader::csrc, _RTPSession::csrc, current_time_monotonic(), _RTPSession::extension, i, _RTPHeader::length, LOGGER_WARNING, _RTPSession::marker, _RTPSession::padding, _RTPSession::payload_type, _RTPHeader::sequnum, _RTPSession::sequnum, size_32, _RTPHeader::ssrc, _RTPSession::ssrc, _RTPHeader::timestamp, and _RTPSession::version.
Referenced by rtp_new_message().
{
    RTPHeader *retu = calloc (1, sizeof (RTPHeader));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    ADD_FLAG_VERSION (retu, session->version);
    ADD_FLAG_PADDING (retu, session->padding);
    ADD_FLAG_EXTENSION (retu, session->extension);
    ADD_FLAG_CSRCC (retu, session->cc);
    ADD_SETTING_MARKER (retu, session->marker);
    ADD_SETTING_PAYLOAD (retu, session->payload_type);
    retu->sequnum = session->sequnum;
    retu->timestamp = current_time_monotonic(); /* milliseconds */
    retu->ssrc = session->ssrc;
    int i;
    for (i = 0; i < session->cc; i++)
        retu->csrc[i] = session->csrc[i];
    retu->length = 12 /* Minimum header len */ + (session->cc * size_32);
    return retu;
}
static int check_late_message (RTPSession * session, RTPMessage * msg) [static]
Checks if message came in late.
Definition at line 52 of file rtp.c.
References _RTPMessage::header, _RTPSession::rsequnum, _RTPHeader::sequnum, _RTPHeader::timestamp, and _RTPSession::timestamp.
Referenced by rtp_handle_packet().
{
    /*
     * Check Sequence number. If this new msg has lesser number then the session->rsequnum
     * it shows that the message came in late. Also check timestamp to be 100% certain.
     *
     */
    return (msg->header->sequnum < session->rsequnum && msg->
      header->timestamp < session->timestamp) ? 0 : -1;
}
RTPExtHeader* extract_ext_header (const uint8_t * payload, uint16_t length)
Extracts external header from payload. Must be called AFTER extract_header()!
Definition at line 141 of file rtp.c.
References _RTPExtHeader::length, LOGGER_WARNING, _RTPExtHeader::table, _RTPExtHeader::type, and x.
Referenced by msg_parse().
{
    const uint8_t *it = payload;
    RTPExtHeader *retu = calloc(1, sizeof (RTPExtHeader));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    uint16_t ext_length;
    memcpy(&ext_length, it, sizeof(ext_length));
    ext_length = ntohs(ext_length);
    it += 2;
    if (length < (ext_length * sizeof(uint32_t))) {
        LOGGER_WARNING("Length invalid!");
        free(retu);
        return NULL;
    }
    retu->length = ext_length;
    memcpy(&retu->type, it, sizeof(retu->type));
    retu->type = ntohs(retu->type);
    it += 2;
    if (!(retu->table = calloc(ext_length, sizeof (uint32_t)))) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        free(retu);
        return NULL;
    }
    uint16_t x;
    for (x = 0; x < ext_length; x++) {
        it += 4;
        memcpy(&(retu->table[x]), it, sizeof(retu->table[x]));
        retu->table[x] = ntohl(retu->table[x]);
    }
    return retu;
}
RTPHeader* extract_header (const uint8_t * payload, int length)
Extracts header from payload.
Definition at line 66 of file rtp.c.
References _RTPHeader::csrc, _RTPHeader::flags, GET_FLAG_CSRCC, GET_FLAG_VERSION, _RTPHeader::length, LOGGER_WARNING, _RTPHeader::marker_payloadt, RTP_VERSION, _RTPHeader::sequnum, _RTPHeader::ssrc, _RTPHeader::timestamp, and x.
Referenced by msg_parse().
{
    if (!payload || !length) {
        LOGGER_WARNING("No payload to extract!");
        return NULL;
    }
    RTPHeader *retu = calloc(1, sizeof (RTPHeader));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    memcpy(&retu->sequnum, payload, sizeof(retu->sequnum));
    retu->sequnum = ntohs(retu->sequnum);
    const uint8_t *it = payload + 2;
    retu->flags = *it;
    ++it;
    /* This indicates if the first 2 bits are valid.
     * Now it may happen that this is out of order but
     * it cuts down chances of parsing some invalid value
     */
    if (GET_FLAG_VERSION(retu) != RTP_VERSION) {
        /* Deallocate */
        LOGGER_WARNING("Invalid version!");
        free(retu);
        return NULL;
    }
    /*
     * Added a check for the size of the header little sooner so
     * I don't need to parse the other stuff if it's bad
     */
    uint8_t cc = GET_FLAG_CSRCC (retu);
    int total = 12 /* Minimum header len */ + (cc * 4);
    if (length < total) {
        /* Deallocate */
        LOGGER_WARNING("Length invalid!");
        free(retu);
        return NULL;
    }
    memset(retu->csrc, 0, 16 * sizeof (uint32_t));
    retu->marker_payloadt = *it;
    ++it;
    retu->length = total;
    memcpy(&retu->timestamp, it, sizeof(retu->timestamp));
    retu->timestamp = ntohl(retu->timestamp);
    it += 4;
    memcpy(&retu->ssrc, it, sizeof(retu->ssrc));
    retu->ssrc = ntohl(retu->ssrc);
    uint8_t x;
    for (x = 0; x < cc; x++) {
        it += 4;
        memcpy(&retu->csrc[x], it, sizeof(retu->csrc[x]));
        retu->csrc[x] = ntohl(retu->csrc[x]);
    }
    return retu;
}
RTPMessage* msg_parse (const uint8_t * data, int length)
Parses data into RTPMessage struct. Stores headers separately from the payload data and so the length variable is set accordingly.
Definition at line 296 of file rtp.c.
References _RTPMessage::data, _RTPMessage::ext_header, extract_ext_header(), extract_header(), GET_FLAG_EXTENSION, _RTPMessage::header, _RTPHeader::length, _RTPExtHeader::length, _RTPMessage::length, LOGGER_WARNING, MAX_RTP_SIZE, _RTPMessage::next, rtp_free_msg(), and size_32.
Referenced by rtp_handle_packet().
{
    RTPMessage *retu = calloc(1, sizeof (RTPMessage));
    retu->header = extract_header (data, length); /* It allocates memory and all
      */
    if (!retu->header) {
        LOGGER_WARNING("Header failed to extract!");
        free(retu);
        return NULL;
    }
    uint16_t from_pos = retu->header->length;
    retu->length = length - from_pos;
    if (GET_FLAG_EXTENSION (retu->header)) {
        retu->ext_header = extract_ext_header (data + from_pos, length);
        if (retu->ext_header) {
            retu->length -= (4 /* Minimum ext header len */ + retu->
      ext_header->length * size_32);
            from_pos += (4 /* Minimum ext header len */ + retu->ext_header->
      length * size_32);
        } else { /* Error */
            LOGGER_WARNING("Ext Header failed to extract!");
            rtp_free_msg(NULL, retu);
            return NULL;
        }
    } else {
        retu->ext_header = NULL;
    }
    if (length - from_pos <= MAX_RTP_SIZE)
        memcpy (retu->data, data + from_pos, length - from_pos);
    else {
        LOGGER_WARNING("Invalid length!");
        rtp_free_msg(NULL, retu);
        return NULL;
    }
    retu->next = NULL;
    return retu;
}
void queue_message (RTPSession * _session, RTPMessage * _msg)
rtp.c
Copyright (C) 2013 Tox project All Rights Reserved.
This file is part of Tox.
Tox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Tox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Tox. If not, see http://www.gnu.org/licenses/.
Definition at line 617 of file codec.c.
References buffer_full(), buffer_read(), buffer_write(), _RTPSession::cs, _RTPMessage::data, end, _CSSession::frame_buf, _CSSession::frame_size, _CSSession::frameid_in, _RTPMessage::header, _CSSession::j_buf, jbuf_write(), _CSSession::last_timestamp, _RTPMessage::length, LOGGER_DEBUG, LOGGER_WARNING, _CSSession::max_video_frame_size, msi_TypeAudio, _RTPSession::payload_type, _CSSession::queue_mutex, rtp_free_msg(), _RTPHeader::timestamp, _CSSession::vbuf_raw, _CSSession::video_frame_piece_size, and VIDEOFRAME_HEADER_SIZE.
Referenced by rtp_handle_packet().
{
    /* This function is unregistered during call termination befor destroing
     * Codec session so no need to check for validity of cs
     */
    CSSession *cs = session->cs;
    if (!cs) return;
    /* Audio */
    if (session->payload_type == msi_TypeAudio % 128) {
        pthread_mutex_lock(cs->queue_mutex);
        int ret = jbuf_write(cs->j_buf, msg);
        pthread_mutex_unlock(cs->queue_mutex);
        if (ret == -1) {
            rtp_free_msg(NULL, msg);
        }
    }
    /* Video */
    else {
        uint8_t *packet = msg->data;
        uint32_t packet_size = msg->length;
        if (packet_size < VIDEOFRAME_HEADER_SIZE)
            goto end;
        uint8_t diff = packet[0] - cs->frameid_in;
        if (diff != 0) {
            if (diff < 225) { /* New frame */
                /* Flush last frames' data and get ready for this frame */
                Payload *p = malloc(sizeof(Payload) + cs->frame_size);
                if (p) {
                    pthread_mutex_lock(cs->queue_mutex);
                    if (buffer_full(cs->vbuf_raw)) {
                        LOGGER_DEBUG("Dropped video frame");
                        Payload *tp;
                        buffer_read(cs->vbuf_raw, &tp);
                        free(tp);
                    } else {
                        p->size = cs->frame_size;
                        memcpy(p->data, cs->frame_buf, cs->frame_size);
                    }
                    buffer_write(cs->vbuf_raw, p);
                    pthread_mutex_unlock(cs->queue_mutex);
                } else {
                    LOGGER_WARNING("Allocation failed! Program might misbehave!");
                    goto end;
                }
                cs->last_timestamp = msg->header->timestamp;
                cs->frameid_in = packet[0];
                memset(cs->frame_buf, 0, cs->frame_size);
                cs->frame_size = 0;
            } else { /* Old frame; drop */
                LOGGER_DEBUG("Old packet: %u", packet[0]);
                goto end;
            }
        }
        uint8_t piece_number = packet[1];
        uint32_t length_before_piece = ((piece_number - 1) * cs->
      video_frame_piece_size);
        uint32_t framebuf_new_length = length_before_piece + (packet_size -
      VIDEOFRAME_HEADER_SIZE);
        if (framebuf_new_length > cs->max_video_frame_size) {
            goto end;
        }
        /* Otherwise it's part of the frame so just process */
        /* LOGGER_DEBUG("Video Packet: %u %u", packet[0], packet[1]); */
        memcpy(cs->frame_buf + length_before_piece,
               packet + VIDEOFRAME_HEADER_SIZE,
               packet_size - VIDEOFRAME_HEADER_SIZE);
        if (framebuf_new_length > cs->frame_size) {
            cs->frame_size = framebuf_new_length;
        }
end:
        rtp_free_msg(NULL, msg);
    }
}
void rtp_free_msg (RTPSession * session, RTPMessage * msg)
Dealloc msg.
Definition at line 446 of file rtp.c.
References _RTPMessage::ext_header, _RTPSession::ext_header, _RTPMessage::header, and _RTPExtHeader::table.
Referenced by cs_do(), jbuf_clear(), msg_parse(), queue_message(), and rtp_send_msg().
{
    if (!session) {
        if (msg->ext_header) {
            free (msg->ext_header->table);
            free (msg->ext_header);
        }
    } else {
        if (msg->ext_header && session->ext_header != msg->
      ext_header) {
            free (msg->ext_header->table);
            free (msg->ext_header);
        }
    }
    free (msg->header);
    free (msg);
}
int rtp_handle_packet (Messenger * m, uint32_t friendnumber, const uint8_t * data, uint16_t length, void * object)
Callback for networking core.
Definition at line 344 of file rtp.c.
References check_late_message(), _RTPMessage::header, LOGGER_WARNING, msg_parse(), queue_message(), _RTPSession::rsequnum, _RTPHeader::sequnum, _RTPHeader::timestamp, and _RTPSession::timestamp.
Referenced by rtp_new().
{
    RTPSession *session = object;
    RTPMessage *msg;
    if (!session || length < 13) { /* 12 is the minimum length for rtp + desc. byte */
        LOGGER_WARNING("No session or invalid length of received buffer!");
        return -1;
    }
    msg = msg_parse (data + 1, length - 1);
    if (!msg) {
        LOGGER_WARNING("Could not parse message!");
        return -1;
    }
    /* Check if message came in late */
    if (check_late_message(session, msg) < 0) { /* Not late */
        session->rsequnum = msg->header->sequnum;
        session->timestamp = msg->header->timestamp;
    }
    queue_message(session, msg);
    return 0;
}
void rtp_kill (RTPSession * session, Messenger * messenger)
Terminate the session.
Definition at line 514 of file rtp.c.
References _RTPSession::csrc, _RTPSession::dest, _RTPSession::ext_header, LOGGER_DEBUG, m_callback_rtp_packet(), and _RTPSession::prefix.
Referenced by toxav_kill(), toxav_kill_transmission(), and toxav_prepare_transmission().
{
    if (!session) return;
    m_callback_rtp_packet(messenger, session->dest, session->
      prefix, NULL, NULL);
    free (session->ext_header);
    free (session->csrc);
    LOGGER_DEBUG("Terminated RTP session: %p", session);
    /* And finally free session */
    free (session);
}
RTPSession* rtp_new (int payload_type, Messenger * messenger, int friend_num)
Must be called before calling any other rtp function.
Definition at line 464 of file rtp.c.
References _RTPSession::cc, _RTPSession::csrc, _RTPSession::dest, _RTPSession::ext_header, _RTPSession::extension, LOGGER_DEBUG, LOGGER_ERROR, LOGGER_WARNING, m_callback_rtp_packet(), _RTPSession::marker, _RTPSession::padding, _RTPSession::payload_type, _RTPSession::prefix, random_int(), _RTPSession::rsequnum, rtp_handle_packet(), RTP_VERSION, _RTPSession::sequnum, _RTPSession::ssrc, and _RTPSession::version.
Referenced by toxav_prepare_transmission().
{
    RTPSession *retu = calloc(1, sizeof(RTPSession));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    if (-1 == m_callback_rtp_packet(messenger, friend_num, payload_type,
      rtp_handle_packet, retu)) {
        LOGGER_ERROR("Error setting custom register handler for rtp session");
        free(retu);
        return NULL;
    }
    LOGGER_DEBUG("Registered packet handler: pt: %d; fid: %d", payload_type, friend_num);
    retu->version = RTP_VERSION; /* It's always 2 */
    retu->padding = 0; /* If some additional data is needed about the packet */
    retu->extension = 0; /* If extension to header is needed */
    retu->cc = 1; /* Amount of contributors */
    retu->csrc = NULL; /* Container */
    retu->ssrc = random_int();
    retu->marker = 0;
    retu->payload_type = payload_type % 128;
    retu->dest = friend_num;
    retu->rsequnum = retu->sequnum = 0;
    retu->ext_header = NULL; /* When needed allocate */
    if (!(retu->csrc = calloc(1, sizeof (uint32_t)))) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        free(retu);
        return NULL;
    }
    retu->csrc[0] = retu->ssrc; /* Set my ssrc to the list receive */
    /* Also set payload type as prefix */
    retu->prefix = payload_type;
    /*
     *
     */
    return retu;
}
RTPMessage* rtp_new_message (RTPSession * session, const uint8_t * data, uint32_t length)
Allocate message and store data there
Definition at line 375 of file rtp.c.
References add_ext_header(), add_header(), build_header(), _RTPMessage::data, _RTPMessage::ext_header, _RTPSession::ext_header, _RTPMessage::header, _RTPHeader::length, _RTPExtHeader::length, _RTPMessage::length, LOGGER_WARNING, _RTPMessage::next, _RTPSession::prefix, and size_32.
Referenced by rtp_send_msg().
{
    if (!session) {
        LOGGER_WARNING("No session!");
        return NULL;
    }
    uint8_t *from_pos;
    RTPMessage *retu = calloc(1, sizeof (RTPMessage));
    if (!retu) {
        LOGGER_WARNING("Alloc failed! Program might misbehave!");
        return NULL;
    }
    /* Sets header values and copies the extension header in retu */
    retu->header = build_header (session); /* It allocates memory and all */
    retu->ext_header = session->ext_header;
    uint32_t total_length = length + retu->header->length + 1;
    retu->data[0] = session->prefix;
    if (retu->ext_header) {
        total_length += (4 /* Minimum ext header len */ + retu->ext_header->
      length * size_32);
        from_pos = add_header (retu->header, retu->data + 1);
        from_pos = add_ext_header (retu->ext_header, from_pos + 1);
    } else {
        from_pos = add_header (retu->header, retu->data + 1);
    }
    /*
     * Parses the extension header into the message
     * Of course if any
     */
    /* Appends data on to retu->data */
    memcpy (from_pos, data, length);
    retu->length = total_length;
    retu->next = NULL;
    return retu;
}
int rtp_send_msg (RTPSession * session, Messenger * messenger, const uint8_t * data, uint16_t length)
Sends msg to _RTPSession::dest
Definition at line 425 of file rtp.c.
References _RTPMessage::data, _RTPSession::dest, _RTPMessage::length, LOGGER_WARNING, MAX_SEQU_NUM, rtp_ErrorSending, rtp_free_msg(), rtp_new_message(), send_custom_lossy_packet(), and _RTPSession::sequnum.
Referenced by toxav_send_rtp_payload().
{
    RTPMessage *msg = rtp_new_message (session, data, length);
    if (!msg) return -1;
    int ret = send_custom_lossy_packet(messenger, session->
      dest, msg->data, msg->length);
    if (0 != ret) {
        LOGGER_WARNING("Failed to send full packet (len: %d)! error: %i", length, ret);
        rtp_free_msg (session, msg);
        return rtp_ErrorSending;
    }
    /* Set sequ number */
    session->sequnum = session->sequnum >= MAX_SEQU_NUM ? 0 : session->
      sequnum + 1;
    rtp_free_msg (session, msg);
    return 0;
}