testing/nTox.h File Reference
#include <ctype.h>
*
#include <curses.h>
*
#include `../toxcore/tox.h`
*
Macros
#define STRING_LENGTH 256
#define HISTORY 50
Functions
void new_lines (char *line)
void do_refresh ()
Macro Definition Documentation
#define HISTORY 50
Definition at line 37 of file nTox.h.
Referenced by do_refresh(), and new_lines_mark().
#define STRING_LENGTH 256
Definition at line 36 of file nTox.h.
Referenced by appender(), line_eval(), new_lines_mark(), and print_groupchatpeers().
Function Documentation
void do_refresh ()
Definition at line 841 of file nTox.c.
References count_lines(), flag, HISTORY, i, input_line, lines, STRING_LENGTH_WRAPPED, wrap(), wrap_bars(), x, and y.
Referenced by main(), new_lines_mark(), and print_request().
{
    int count = 0;
    char wrap_output[STRING_LENGTH_WRAPPED];
    int i;
    for (i = 0; i < HISTORY; i++) {
        if (flag[i])
            wrap_bars(wrap_output, lines[i], x);
        else
            wrap(wrap_output, lines[i], x);
        int L = count_lines(wrap_output);
        count = count + L;
        if (count < y) {
            move(y - 1 - count, 0);
            printw("%s", wrap_output);
            clrtoeol();
        }
    }
    move(y - 1, 0);
    clrtoeol();
    printw(">> ");
    printw("%s", input_line);
    clrtoeol();
    refresh();
}
void new_lines (char * line)
Definition at line 241 of file nTox.c.
References new_lines_mark().
Referenced by file_print_control(), file_request_accept(), line_eval(), main(), print_formatted_message(), print_friendlist(), print_groupchatpeers(), print_groupmessage(), print_groupnamelistchange(), print_invite(), print_nickchange(), print_request(), print_statuschange(), timeout_getch(), tox_file_chunk_request(), and write_file().
{
    new_lines_mark(line, 0);
}