testing/irc_syncbot.c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <time.h>
*
#include <fcntl.h>
*
#include <sys/socket.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include <errno.h>
*
#include <sys/time.h>
*
#include <sys/types.h>
*
#include <netdb.h>
*
#include <unistd.h>
*
#include <sys/ioctl.h>
*
#include `../toxcore/tox.h`
*
#include `misc_tools.c`
*
Macros
#define IRC_NAME `Tox_syncbot`
#define IRC_CHANNEL `#tox-real-ontopic`
#define SILENT_TIMEOUT 20
#define SERVER_CONNECT `NICK `IRC_NAME`\nUSER `IRC_NAME` 8 * :`IRC_NAME`\n`
#define CHANNEL_JOIN `JOIN `IRC_CHANNEL`\n`
Functions
uint64_t current_time_monotonic (void)
uint64_t get_monotime_sec (void)
int reconnect (void)
static void callback_group_invite (Tox *tox, int fid, uint8_t type, const uint8_t *data, uint16_t length, void *userdata)
void callback_friend_message (Tox *tox, uint32_t fid, TOX_MESSAGE_TYPE type, const uint8_t *message, size_t length, void *userdata)
static void copy_groupmessage (Tox *tox, int groupnumber, int friendgroupnumber, const uint8_t *message, uint16_t length, void *userdata)
void send_irc_group (Tox *tox, uint8_t *msg, uint16_t len)
Tox * init_tox (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
uint8_t ip [4] = {127, 0, 0, 1}
uint16_t port = 6667
int sock
int current_group = -1
Macro Definition Documentation
#define CHANNEL_JOIN `JOIN `IRC_CHANNEL`\n`
Definition at line 38 of file irc_syncbot.c.
Referenced by callback_friend_message(), and main().
#define IRC_CHANNEL `#tox-real-ontopic`
Definition at line 27 of file irc_syncbot.c.
Referenced by copy_groupmessage().
#define IRC_NAME `Tox_syncbot`
Definition at line 26 of file irc_syncbot.c.
Referenced by init_tox().
#define SERVER_CONNECT `NICK `IRC_NAME`\nUSER `IRC_NAME` 8 * :`IRC_NAME`\n`
Definition at line 37 of file irc_syncbot.c.
Referenced by reconnect().
#define SILENT_TIMEOUT 20
Definition at line 33 of file irc_syncbot.c.
Referenced by main().
Function Documentation
void callback_friend_message (Tox * tox, uint32_t fid, TOX_MESSAGE_TYPE type, const uint8_t * message, size_t length, void * userdata)
Definition at line 92 of file irc_syncbot.c.
References CHANNEL_JOIN, current_group, sock, tox_del_groupchat(), and tox_invite_friend().
Referenced by init_tox().
{
    if (length == 1 && *message == 'c') {
        if (tox_del_groupchat(tox, current_group) == 0)
            current_group = -1;
    }
    if (length == 1 && *message == 'i') {
        tox_invite_friend(tox, fid, current_group);
    }
    if (length == 1 && *message == 'j' && sock >= 0) {
        send(sock, CHANNEL_JOIN, sizeof(CHANNEL_JOIN) - 1, MSG_NOSIGNAL);
    }
}
static void callback_group_invite (Tox * tox, int fid, uint8_t type, const uint8_t * data, uint16_t length, void * userdata) [static]
Definition at line 86 of file irc_syncbot.c.
References current_group, and tox_join_groupchat().
Referenced by init_tox().
{
    if (current_group == -1)
        current_group = tox_join_groupchat(tox, fid,
      data, length);
}
static void copy_groupmessage (Tox * tox, int groupnumber, int friendgroupnumber, const uint8_t * message, uint16_t length, void * userdata) [static]
Definition at line 109 of file irc_syncbot.c.
References i, IRC_CHANNEL, sock, tox_group_peername(), tox_group_peernumber_is_ours(), and TOX_MAX_NAME_LENGTH.
Referenced by init_tox().
{
    if (tox_group_peernumber_is_ours(tox, groupnumber, friendgroupnumber))
        return;
    uint8_t name[TOX_MAX_NAME_LENGTH];
    int namelen = tox_group_peername(tox, groupnumber, friendgroupnumber, name);
    if (namelen == 0 || namelen == -1) {
        memcpy(name, "<unknown>", 9);
        namelen = 9;
    }
    uint8_t sendbuf[2048];
    uint16_t send_len = 0;
    memcpy(sendbuf, "PRIVMSG "IRC_CHANNEL" :", sizeof("PRIVMSG "
      IRC_CHANNEL" :"));
    send_len += sizeof("PRIVMSG "IRC_CHANNEL" :") - 1;
    memcpy(sendbuf + send_len, name, namelen);
    send_len += namelen;
    sendbuf[send_len] = ':';
    send_len += 1;
    sendbuf[send_len] = ' ';
    send_len += 1;
    memcpy(sendbuf + send_len, message, length);
    send_len += length;
    unsigned int i;
    for (i = 0; i < send_len; ++i) {
        if (sendbuf[i] == '\n')
            sendbuf[i] = '|';
        if (sendbuf[i] == 0)
            sendbuf[i] = ' ';
    }
    sendbuf[send_len] = '\n';
    send_len += 1;
    if (sock >= 0)
        send(sock, sendbuf, send_len, MSG_NOSIGNAL);
}
uint64_t current_time_monotonic (void)
Definition at line 233 of file network.c.
Referenced by build_header(), get_monotime_sec(), handle_data_packet_helper(), handle_request_packet(), logger_new(), msi_do(), reset_max_speed_reached(), send_crypto_packets(), send_lossless_packet(), send_requested_packets(), send_temp_packet(), timer_alloc(), toxav_do(), and unix_time_update().
{
    uint64_t time;
#if defined(_WIN32) || defined(__WIN32__) || defined (WIN32)
    time = (uint64_t)GetTickCount() + add_monotime;
    if (time < last_monotime) { /* Prevent time from ever decreasing because of 32 bit wrap. */
        uint32_t add = ~0;
        add_monotime += add;
        time += add;
    }
    last_monotime = time;
#else
    struct timespec monotime;
#if defined(__linux__) && defined(CLOCK_MONOTONIC_RAW)
    clock_gettime(CLOCK_MONOTONIC_RAW, &monotime);
#elif defined(__APPLE__)
    clock_serv_t muhclock;
    mach_timespec_t machtime;
    host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &muhclock);
    clock_get_time(muhclock, &machtime);
    mach_port_deallocate(mach_task_self(), muhclock);
    monotime.tv_sec = machtime.tv_sec;
    monotime.tv_nsec = machtime.tv_nsec;
#else
    clock_gettime(CLOCK_MONOTONIC, &monotime);
#endif
    time = 1000ULL * monotime.tv_sec + (monotime.tv_nsec / 1000000ULL);
#endif
    return time;
}
uint64_t get_monotime_sec (void)
Definition at line 43 of file irc_syncbot.c.
References current_time_monotonic().
Referenced by main().
{
    return current_time_monotonic() / 1000;
}
Tox* init_tox (int argc, char * argv[])
Definition at line 211 of file irc_syncbot.c.
References callback_friend_message(), callback_group_invite(), cmdline_parsefor_ipv46(), copy_groupmessage(), hex_string_to_bin(), IRC_NAME, num, port, printf(), tox_bootstrap(), tox_callback_friend_message(), tox_callback_group_action(), tox_callback_group_invite(), tox_callback_group_message(), tox_friend_add(), tox_new(), and tox_self_set_name().
Referenced by main().
{
    uint8_t ipv6enabled = 1; /* x */
    int argvoffset = cmdline_parsefor_ipv46(argc, argv, &ipv6enabled);
    if (argvoffset < 0)
        exit(1);
    /* with optional --ipvx, now it can be 1-4 arguments... */
    if ((argc != argvoffset + 2) && (argc != argvoffset + 4)) {
        printf("Usage: %s [--ipv4|--ipv6] ip port public_key (of the DHT bootstrap node)\n", argv[0])
      ;
        exit(0);
    }
    Tox *tox = tox_new(0, 0);
    if (!tox)
        exit(1);
    tox_self_set_name(tox, (uint8_t *)IRC_NAME, sizeof(
      IRC_NAME) - 1, 0);
    tox_callback_friend_message(tox, &
      callback_friend_message, 0);
    tox_callback_group_invite(tox, &
      callback_group_invite, 0);
    tox_callback_group_message(tox, &copy_groupmessage, 0);
    tox_callback_group_action(tox, &copy_groupmessage, 0);
    char temp_id[128];
    printf("\nEnter the address of irc_syncbots master (38 bytes HEX format):\n");
    if (scanf("%s", temp_id) != 1) {
        exit (1);
    }
    uint16_t port = atoi(argv[argvoffset + 2]);
    unsigned char *binary_string = hex_string_to_bin(argv[argvoffset + 3]);
    tox_bootstrap(tox, argv[argvoffset + 1], port, binary_string, 0);
    free(binary_string);
    uint8_t *bin_id = hex_string_to_bin(temp_id);
    uint32_t num = tox_friend_add(tox, bin_id, (uint8_t *)"Install Gentoo", sizeof("
      Install Gentoo") - 1, 0);
    free(bin_id);
    if (num == UINT32_MAX) {
        printf("\nSomething went wrong when adding friend.\n");
        exit(1);
    }
    return tox;
}
int main (int argc, char * argv[])
Definition at line 260 of file irc_syncbot.c.
References CHANNEL_JOIN, make-funny-savefile::data, error, get_monotime_sec(), i, init_tox(), printf(), reconnect(), send_irc_group(), SILENT_TIMEOUT, sock, and tox_iterate().
{
    Tox *tox = init_tox(argc, argv);
    sock = reconnect();
    if (sock < 0)
        return 1;
    uint64_t last_get = get_monotime_sec();
    int connected = 0, ping_sent = 0;
    while (1) {
        int count = 0;
        ioctl(sock, FIONREAD, &count);
        if (count > 0) {
            last_get = get_monotime_sec();
            ping_sent = 0;
            uint8_t data[count + 1];
            data[count] = 0;
            recv(sock, data, count, MSG_NOSIGNAL);
            printf("%s", data);
            if (!connected)
                connected = 1;
            if (count > 6 && data[0] == 'P' && data[1] == 'I' && data[2] == 'N' && data[3] == 'G') {
                data[1] = 'O';
                unsigned int i;
                for (i = 0; i < count; ++i) {
                    if (data[i] == '\n') {
                        ++i;
                        break;
                    }
                }
                send(sock, data, i, MSG_NOSIGNAL);
            }
            unsigned int i, p_i = 0;
            for (i = 1; data[0] == ':' && i < count; ++i) {
                if (data[i] == ' ') {
                    if (i + 5 < count && memcmp(data + i, " 404 ", 5) == 0) {
                        connected = 1;
                    }
                    break;
                }
                if (data[i] == ':')
                    break;
            }
            for (i = 0; i < count; ++i) {
                if (data[i] == '\n' && i != 0) {
                    send_irc_group(tox, data + p_i, i - p_i);
                    p_i = i + 1;
                }
            }
        }
        if (connected == 1) {
            send(sock, CHANNEL_JOIN, sizeof(CHANNEL_JOIN) - 1, MSG_NOSIGNAL);
            connected = 2;
        }
        if (!ping_sent && last_get + (SILENT_TIMEOUT / 2) <
      get_monotime_sec()) {
            unsigned int p_s = sizeof("PING :test\n") - 1;
            if (send(sock, "PING :test\n", p_s, MSG_NOSIGNAL) == p_s)
                ping_sent = 1;
        }
        int error = 0;
        socklen_t len = sizeof (error);
        if (sock < 0 || last_get + SILENT_TIMEOUT <
      get_monotime_sec()
                || getsockopt(sock, SOL_SOCKET, SO_ERROR, &error, &len) != 0) {
            close(sock);
            printf("reconnect\n");
            sock = reconnect();
            if (sock >= 0) {
                last_get = get_monotime_sec();
                connected = 0;
                ping_sent = 0;
            }
        }
        tox_iterate(tox);
        usleep(1000 * 50);
    }
    return 0;
}
int reconnect (void)
Definition at line 48 of file irc_syncbot.c.
References ip, port, printf(), SERVER_CONNECT, and sock.
Referenced by main().
{
    int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock < 0) {
        printf("error socket\n");
        return -1;
    }
    struct sockaddr_storage addr = {0};
    size_t addrsize;
    struct sockaddr_in *addr4 = (struct sockaddr_in *)&addr;
    addrsize = sizeof(struct sockaddr_in);
    addr4->sin_family = AF_INET;
    memcpy(&addr4->sin_addr, ip, 4);
    addr4->sin_port = htons(port);
    if (connect(sock, (struct sockaddr *)&addr, addrsize) != 0) {
        printf("error connect\n");
        return -1;
    }
    send(sock, SERVER_CONNECT, sizeof(SERVER_CONNECT) - 1, MSG_NOSIGNAL);
    return sock;
}
void send_irc_group (Tox * tox, uint8_t * msg, uint16_t len)
Definition at line 153 of file irc_syncbot.c.
References current_group, i, and tox_group_message_send().
Referenced by main().
{
    if (len > 1350 || len == 0 || len == 1)
        return;
    --len;
    if (*msg != ':')
        return;
    uint8_t req[len];
    unsigned int i;
    unsigned int spaces = 0;
    for (i = 0; i < (len - 1); ++i) {
        if (msg[i + 1] == ' ') {
            ++spaces;
        } else {
            if (spaces >= 3 && msg[i + 1] == ':') {
                break;
            }
        }
        req[i] = msg[i + 1];
    }
    unsigned int req_len = i;
    req[i] = 0;
    uint8_t message[len];
    uint16_t length = 0;
    uint8_t *pmsg = (uint8_t *)strstr((char *)req, " PRIVMSG");
    if (pmsg == NULL)
        return;
    uint8_t *dt = req;
    for (dt = req, i = 0; dt != pmsg && *dt != '!'; ++dt, ++i) {
        message[i] = *dt;
        ++length;
    }
    message[length] = ':';
    length += 1;
    message[length] = ' ';
    length += 1;
    if ((req_len + 2) >= len)
        return;
    memcpy(message + length, msg + req_len + 2, len - (req_len + 2));
    length += len - (req_len + 2);
    tox_group_message_send(tox, current_group, message, length);
}
Variable Documentation
int current_group = -1
Definition at line 84 of file irc_syncbot.c.
Referenced by callback_friend_message(), callback_group_invite(), and send_irc_group().
uint8_t ip[4] = {127, 0, 0, 1}
Definition at line 30 of file irc_syncbot.c.
Referenced by broadcast_ip(), do_NAT(), main(), NAT_commonip(), new_messenger(), new_onions(), proxy_http_generate_connection_request(), reconnect(), START_TEST(), and test_addto_lists().
uint16_t port = 6667
Definition at line 31 of file irc_syncbot.c.
Referenced by DHT_bootstrap_from_address(), init_tox(), main(), NAT_getports(), proxy_http_generate_connection_request(), punch_holes(), reconnect(), send_LANdiscovery(), and tox_self_get_udp_port().
int sock
Definition at line 35 of file irc_syncbot.c.
Referenced by accept_connection(), callback_friend_message(), copy_groupmessage(), do_TCP_accept_new(), kill_accepted(), main(), new_listening_TCP_socket(), new_TCP_con(), new_TCP_connection(), new_TCP_server(), reconnect(), and START_TEST().