toxcore/ping.h File Reference
Typedefs
typedef struct PING PING
Functions
int add_to_ping (PING *ping, const uint8_t *public_key, IP_Port ip_port)
void do_to_ping (PING *ping)
PING * new_ping (DHT *dht)
void kill_ping (PING *ping)
int send_ping_request (PING *ping, IP_Port ipp, const uint8_t *public_key)
Typedef Documentation
typedef struct PING PING
Definition at line 27 of file ping.h.
Function Documentation
int add_to_ping (PING * ping, const uint8_t * public_key, IP_Port ip_port)
Definition at line 260 of file ping.c.
References DHT::close_clientlist, PING::dht, i, id_closest(), in_list(), IP_Port::ip, ip_isset(), Node_format::ip_port, ipport_copy(), LCLIENT_LIST, MAX_TO_PING, Node_format::public_key, DHT::self_public_key, and PING::to_ping.
Referenced by handle_getnodes(), and handle_ping_request().
{
    if (!ip_isset(&ip_port.ip))
        return -1;
    if (in_list(ping->dht->close_clientlist,
      LCLIENT_LIST, public_key, ip_port))
        return -1;
    uint32_t i;
    for (i = 0; i < MAX_TO_PING; ++i) {
        if (!ip_isset(&ping->to_ping[i].ip_port.ip)) {
            memcpy(ping->to_ping[i].public_key, public_key,
      crypto_box_PUBLICKEYBYTES);
            ipport_copy(&ping->to_ping[i].ip_port, &ip_port);
            return 0;
        }
        if (memcmp(ping->to_ping[i].public_key, public_key,
      crypto_box_PUBLICKEYBYTES) == 0) {
            return -1;
        }
    }
    uint32_t r = rand();
    for (i = 0; i < MAX_TO_PING; ++i) {
        if (id_closest(ping->dht->self_public_key, ping->
      to_ping[(i + r) % MAX_TO_PING].public_key, public_key) == 2) {
            memcpy(ping->to_ping[(i + r) % MAX_TO_PING].public_key,
      public_key, crypto_box_PUBLICKEYBYTES);
            ipport_copy(&ping->to_ping[(i + r) % MAX_TO_PING].
      ip_port, &ip_port);
            return 0;
        }
    }
    return -1;
}
void do_to_ping (PING * ping)
Definition at line 299 of file ping.c.
References i, IP_Port::ip, ip_isset(), Node_format::ip_port, ip_reset(), is_timeout(), PING::last_to_ping, MAX_TO_PING, Node_format::public_key, send_ping_request(), TIME_TO_PING, PING::to_ping, and unix_time().
Referenced by do_DHT().
{
    if (!is_timeout(ping->last_to_ping, TIME_TO_PING))
        return;
    if (!ip_isset(&ping->to_ping[0].ip_port.ip))
        return;
    uint32_t i;
    for (i = 0; i < MAX_TO_PING; ++i) {
        if (!ip_isset(&ping->to_ping[i].ip_port.ip))
            break;
        send_ping_request(ping, ping->to_ping[i].ip_port, ping->
      to_ping[i].public_key);
        ip_reset(&ping->to_ping[i].ip_port.ip);
    }
    if (i != 0)
        ping->last_to_ping = unix_time();
}
void kill_ping (PING * ping)
Definition at line 341 of file ping.c.
References PING::dht, DHT::net, NET_PACKET_PING_REQUEST, NET_PACKET_PING_RESPONSE, networking_registerhandler(), PING::ping_array, and ping_array_free_all().
Referenced by kill_DHT().
{
    networking_registerhandler(ping->dht->net,
      NET_PACKET_PING_REQUEST, NULL, NULL);
    networking_registerhandler(ping->dht->net,
      NET_PACKET_PING_RESPONSE, NULL, NULL);
    ping_array_free_all(&ping->ping_array);
    free(ping);
}
PING* new_ping (DHT * dht)
Definition at line 322 of file ping.c.
References PING::dht, handle_ping_request(), handle_ping_response(), DHT::net, NET_PACKET_PING_REQUEST, NET_PACKET_PING_RESPONSE, networking_registerhandler(), PING::ping_array, ping_array_init(), PING_NUM_MAX, and PING_TIMEOUT.
Referenced by new_DHT().
{
    PING *ping = calloc(1, sizeof(PING));
    if (ping == NULL)
        return NULL;
    if (ping_array_init(&ping->ping_array, PING_NUM_MAX,
      PING_TIMEOUT) != 0) {
        free(ping);
        return NULL;
    }
    ping->dht = dht;
    networking_registerhandler(ping->dht->net,
      NET_PACKET_PING_REQUEST, &handle_ping_request, dht);
    networking_registerhandler(ping->dht->net,
      NET_PACKET_PING_RESPONSE, &handle_ping_response, dht);
    return ping;
}
int send_ping_request (PING * ping, IP_Port ipp, const uint8_t * public_key)
Definition at line 61 of file ping.c.
References make-funny-savefile::data, PING::dht, DHT_get_shared_key_sent(), DHT_PING_SIZE, encrypt_data_symmetric(), id_copy(), id_equal(), DHT::net, NET_PACKET_PING_REQUEST, new_nonce(), PING::ping_array, ping_array_add(), PING_DATA_SIZE, PING_PLAIN_SIZE, DHT::self_public_key, and sendpacket().
Referenced by do_ping_and_sendnode_requests(), do_to_ping(), handle_sendnodes_ipv6(), and punch_holes().
{
    uint8_t pk[DHT_PING_SIZE];
    int rc;
    uint64_t ping_id;
    if (id_equal(public_key, ping->dht->self_public_key))
        return 1;
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    // generate key to encrypt ping_id with recipient privkey
    DHT_get_shared_key_sent(ping->dht, shared_key,
      public_key);
    // Generate random ping_id.
    uint8_t data[PING_DATA_SIZE];
    id_copy(data, public_key);
    memcpy(data + crypto_box_PUBLICKEYBYTES, &ipp, sizeof(IP_Port));
    ping_id = ping_array_add(&ping->ping_array, data, sizeof(data));
    if (ping_id == 0)
        return 1;
    uint8_t ping_plain[PING_PLAIN_SIZE];
    ping_plain[0] = NET_PACKET_PING_REQUEST;
    memcpy(ping_plain + 1, &ping_id, sizeof(ping_id));
    pk[0] = NET_PACKET_PING_REQUEST;
    id_copy(pk + 1, ping->dht->self_public_key); // Our pubkey
    new_nonce(pk + 1 + crypto_box_PUBLICKEYBYTES); // Generate new nonce
    rc = encrypt_data_symmetric(shared_key,
                                pk + 1 + crypto_box_PUBLICKEYBYTES,
                                ping_plain, sizeof(ping_plain),
                                pk + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    if (rc != PING_PLAIN_SIZE + crypto_box_MACBYTES)
        return 1;
    return sendpacket(ping->dht->net, ipp, pk, sizeof(pk));
}