other/bootstrap_node_packets.c File Reference
Macros
#define MAX_MOTD_LENGTH 256 /* I recommend you use a maximum of 96 bytes. The hard maximum is this though. */
#define INFO_REQUEST_PACKET_LENGTH 78
Functions
static int handle_info_request (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
int bootstrap_set_callbacks (Networking_Core *net, uint32_t version, uint8_t *motd, uint16_t motd_length)
Variables
static uint32_t bootstrap_version
static uint8_t bootstrap_motd [MAX_MOTD_LENGTH]
static uint16_t bootstrap_motd_length
Macro Definition Documentation
#define INFO_REQUEST_PACKET_LENGTH 78
Definition at line 28 of file bootstrap_node_packets.c.
Referenced by handle_info_request().
#define MAX_MOTD_LENGTH 256 /* I recommend you use a maximum of 96 bytes. The hard maximum is this though. */
Definition at line 26 of file bootstrap_node_packets.c.
Referenced by bootstrap_set_callbacks(), get_general_config(), and handle_info_request().
Function Documentation
int bootstrap_set_callbacks (Networking_Core * net, uint32_t version, uint8_t * motd, uint16_t motd_length)
Definition at line 54 of file bootstrap_node_packets.c.
References BOOTSTRAP_INFO_PACKET_ID, bootstrap_motd, bootstrap_motd_length, bootstrap_version, handle_info_request(), MAX_MOTD_LENGTH, and networking_registerhandler().
Referenced by main().
{
    if (motd_length > MAX_MOTD_LENGTH)
        return -1;
    bootstrap_version = htonl(version);
    memcpy(bootstrap_motd, motd, motd_length);
    bootstrap_motd_length = motd_length;
    networking_registerhandler(net,
      BOOTSTRAP_INFO_PACKET_ID, &handle_info_request, net);
    return 0;
}
static int handle_info_request (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 37 of file bootstrap_node_packets.c.
References BOOTSTRAP_INFO_PACKET_ID, bootstrap_motd, bootstrap_motd_length, bootstrap_version, make-funny-savefile::data, INFO_REQUEST_PACKET_LENGTH, MAX_MOTD_LENGTH, and sendpacket().
Referenced by bootstrap_set_callbacks().
{
    if (length != INFO_REQUEST_PACKET_LENGTH)
        return 1;
    uint8_t data[1 + sizeof(bootstrap_version) +
      MAX_MOTD_LENGTH];
    data[0] = BOOTSTRAP_INFO_PACKET_ID;
    memcpy(data + 1, &bootstrap_version, sizeof(
      bootstrap_version));
    uint16_t len = 1 + sizeof(bootstrap_version) +
      bootstrap_motd_length;
    memcpy(data + 1 + sizeof(bootstrap_version), bootstrap_motd,
      bootstrap_motd_length);
    if (sendpacket(object, source, data, len) == len)
        return 0;
    return 1;
}
Variable Documentation
uint8_t bootstrap_motd[MAX_MOTD_LENGTH] [static]
Definition at line 31 of file bootstrap_node_packets.c.
Referenced by bootstrap_set_callbacks(), and handle_info_request().
uint16_t bootstrap_motd_length [static]
Definition at line 32 of file bootstrap_node_packets.c.
Referenced by bootstrap_set_callbacks(), and handle_info_request().
uint32_t bootstrap_version [static]
Definition at line 30 of file bootstrap_node_packets.c.
Referenced by bootstrap_set_callbacks(), and handle_info_request().