auto_tests/friends_test.c File Reference
#include `../toxcore/friend_requests.h`
*
#include `../toxcore/Messenger.h`
*
#include <assert.h>
*
#include <unistd.h>
*
#include <sys/mman.h>
*
#include <signal.h>
*
#include <sys/wait.h>
*
Macros
#define WAIT_COUNT 30
#define WAIT_TIME 500
#define MAP_ANONYMOUS MAP_ANON
#define FIRST_FLAG 0x1
#define SECOND_FLAG 0x2
#define c_sleep(x) usleep(1000*x)
#define PORT 33445
Functions
void do_tox (DHT *dht)
void parent_confirm_message (Messenger *m, int num, uint8_t *data, uint16_t length, void *userdata)
void parent_confirm_status (Messenger *m, int num, uint8_t *data, uint16_t length, void *userdata)
int parent_friend_request (DHT *dht)
void child_got_request (Messenger *m, uint8_t *public_key, uint8_t *data, uint16_t length, void *userdata)
void child_got_statuschange (Messenger *m, int friend_num, uint8_t *string, uint16_t length, void *userdata)
int parent_wait_for_message (DHT *dht)
void cleanup (void)
int main (int argc, char *argv[])
Variables
static Messenger * m
uint8_t * parent_id = NULL
uint8_t * child_id = NULL
pid_t child_pid = 0
int request_flags = 0
Macro Definition Documentation
#define c_sleep(x) usleep(1000*x)
Definition at line 48 of file friends_test.c.
Referenced by main(), parent_friend_request(), and parent_wait_for_message().
#define FIRST_FLAG 0x1
Definition at line 41 of file friends_test.c.
Referenced by child_got_request(), main(), parent_confirm_status(), and parent_friend_request().
#define MAP_ANONYMOUS MAP_ANON
Definition at line 37 of file friends_test.c.
Referenced by main().
#define PORT 33445
Definition at line 51 of file friends_test.c.
#define SECOND_FLAG 0x2
Definition at line 42 of file friends_test.c.
Referenced by child_got_statuschange(), main(), parent_confirm_message(), and parent_wait_for_message().
#define WAIT_COUNT 30
Definition at line 33 of file friends_test.c.
Referenced by parent_friend_request(), and parent_wait_for_message().
#define WAIT_TIME 500
Definition at line 34 of file friends_test.c.
Referenced by parent_friend_request(), and parent_wait_for_message().
Function Documentation
void child_got_request (Messenger * m, uint8_t * public_key, uint8_t * data, uint16_t length, void * userdata)
Definition at line 119 of file friends_test.c.
References FIRST_FLAG, m_addfriend_norequest(), and request_flags.
Referenced by main().
{
    fputs("OK\nsending status to parent", stdout);
    fflush(stdout);
    m_addfriend_norequest(m, public_key);
    request_flags |= FIRST_FLAG;
}
void child_got_statuschange (Messenger * m, int friend_num, uint8_t * string, uint16_t length, void * userdata)
Definition at line 127 of file friends_test.c.
References request_flags, and SECOND_FLAG.
Referenced by main().
{
    request_flags |= SECOND_FLAG;
}
void cleanup (void)
Definition at line 160 of file friends_test.c.
References child_id, and parent_id.
Referenced by main().
{
    munmap(parent_id, crypto_box_PUBLICKEYBYTES);
    munmap(child_id, crypto_box_PUBLICKEYBYTES);
    puts("============= END TEST =============");
}
void do_tox (DHT * dht)
Definition at line 61 of file friends_test.c.
References DHT_isconnected().
Referenced by main(), parent_friend_request(), and parent_wait_for_message().
{
    static int dht_on = 0;
    if (!dht_on && DHT_isconnected(dht)) {
        dht_on = 1;
    } else if (dht_on && !DHT_isconnected(dht)) {
        dht_on = 0;
    }
    doMessenger(m);
}
int main (int argc, char * argv[])
Definition at line 167 of file friends_test.c.
References c_sleep, child_got_request(), child_got_statuschange(), child_id, child_pid, cleanup(), Messenger::dht, do_tox(), FIRST_FLAG, i, m_callback_friendmessage(), m_callback_friendrequest(), m_callback_statusmessage(), MAP_ANONYMOUS, parent_confirm_message(), parent_confirm_status(), parent_friend_request(), parent_id, parent_wait_for_message(), request_flags, and SECOND_FLAG.
{
    puts("=========== FRIENDS_TEST ===========");
    /* set up the global memory */
    parent_id = mmap(NULL, crypto_box_PUBLICKEYBYTES, PROT_READ | PROT_WRITE,
                     MAP_SHARED | MAP_ANONYMOUS, -1, 0);
    child_id = mmap(NULL, crypto_box_PUBLICKEYBYTES, PROT_READ | PROT_WRITE,
                    MAP_SHARED | MAP_ANONYMOUS, -1, 0);
    fputs("friends_test: Starting test...\n", stdout);
    if ((child_pid = fork()) == 0) {
        /* child */
        int i = 0;
        char *message = "Y-yes Mr. Watson?";
        m = initMessenger();
        Messenger_save(m, child_id);
        msync(child_id, crypto_box_PUBLICKEYBYTES, MS_SYNC);
        m_callback_friendrequest(m, child_got_request, NULL);
        m_callback_statusmessage(m,
      child_got_statuschange, NULL);
        /* wait on the friend request */
        while (!(request_flags & FIRST_FLAG))
            do_tox(m->dht);
        /* wait for the status change */
        while (!(request_flags & SECOND_FLAG))
            do_tox(m->dht);
        for (i = 0; i < 6; i++) {
            /* send the message six times, just to be sure */
            m_sendmessage(m, 0, (uint8_t *)message, strlen(message));
            do_tox(m->dht);
        }
        cleanupMessenger(m);
        return 0;
    }
    /* parent */
    if (atexit(cleanup) != 0) {
        fputs("friends_test: atexit() failed!\nFailing build...\n", stderr);
        kill(child_pid, SIGKILL);
        return -1;
    }
    m = initMessenger();
    msync(parent_id, crypto_box_PUBLICKEYBYTES, MS_SYNC);
    m_callback_statusmessage(m, parent_confirm_status, NULL);
    m_callback_friendmessage(m, parent_confirm_message, NULL
      );
    /* hacky way to give the child time to set up */
    c_sleep(50);
    Messenger_save(m, parent_id);
    if (parent_friend_request(m->dht) == -1)
        return -1;
    if (parent_wait_for_message(m->dht) == -1)
        return -1;
    wait(NULL);
    fputs("friends_test: Build passed!\n", stdout);
    return 0;
}
void parent_confirm_message (Messenger * m, int num, uint8_t * data, uint16_t length, void * userdata)
Definition at line 74 of file friends_test.c.
References request_flags, and SECOND_FLAG.
Referenced by main().
{
    puts("OK");
    request_flags |= SECOND_FLAG;
}
void parent_confirm_status (Messenger * m, int num, uint8_t * data, uint16_t length, void * userdata)
Definition at line 80 of file friends_test.c.
References FIRST_FLAG, and request_flags.
Referenced by main().
{
    puts("OK");
    request_flags |= FIRST_FLAG;
}
int parent_friend_request (DHT * dht)
Definition at line 86 of file friends_test.c.
References c_sleep, child_id, child_pid, do_tox(), FIRST_FLAG, i, m_addfriend(), request_flags, WAIT_COUNT, and WAIT_TIME.
Referenced by main().
{
    char *message = "Watson, come here, I need you.";
    int len = strlen(message);
    int i = 0;
    fputs("Sending child request.", stdout);
    fflush(stdout);
    m_addfriend(m, child_id, (uint8_t *)message, len);
    /* wait on the status change */
    for (i = 0; i < WAIT_COUNT; i++) {
        do_tox(dht);
        if (request_flags & FIRST_FLAG)
            break;
        fputs(".", stdout);
        fflush(stdout);
        c_sleep(WAIT_TIME);
    }
    if (!(request_flags & FIRST_FLAG)) {
        fputs("\nfriends_test: The child took to long to respond!\n"
              "Friend requests may be broken, failing build!\n", stderr);
        kill(child_pid, SIGKILL);
        return -1;
    }
    return 0;
}
int parent_wait_for_message (DHT * dht)
Definition at line 132 of file friends_test.c.
References c_sleep, child_pid, do_tox(), i, request_flags, SECOND_FLAG, WAIT_COUNT, and WAIT_TIME.
Referenced by main().
{
    int i = 0;
    fputs("Parent waiting for message.", stdout);
    fflush(stdout);
    for (i = 0; i < WAIT_COUNT; i++) {
        do_tox(dht);
        if (request_flags & SECOND_FLAG)
            break;
        fputs(".", stdout);
        fflush(stdout);
        c_sleep(WAIT_TIME);
    }
    if (!(request_flags & SECOND_FLAG)) {
        fputs("\nParent hasn't received the message yet!\n"
              "Messaging may be broken, failing the build!\n", stderr);
        kill(child_pid, SIGKILL);
        return -1;
    }
    return 0;
}
Variable Documentation
uint8_t* child_id = NULL
Definition at line 56 of file friends_test.c.
Referenced by cleanup(), main(), and parent_friend_request().
pid_t child_pid = 0
Definition at line 58 of file friends_test.c.
Referenced by main(), parent_friend_request(), and parent_wait_for_message().
Messenger* m [static]
Definition at line 53 of file friends_test.c.
uint8_t* parent_id = NULL
Definition at line 55 of file friends_test.c.
Referenced by cleanup(), and main().
int request_flags = 0
Definition at line 59 of file friends_test.c.
Referenced by child_got_request(), child_got_statuschange(), main(), parent_confirm_message(), parent_confirm_status(), parent_friend_request(), and parent_wait_for_message().