auto_tests/skeleton_test.c File Reference
#include <sys/types.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <check.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include `helpers.h`
*
Functions
START_TEST (test_creativetestnamegoeshere)
END_TEST Suite * creativesuitenamegoeshere_suite (void)
int main (int argc, char *argv[])
Function Documentation
END_TEST Suite* creativesuitenamegoeshere_suite (void)
Definition at line 25 of file skeleton_test.c.
References DEFTESTCASE.
Referenced by main().
{
    Suite *s = suite_create("creativesuitedescritptiongoeshere");
    DEFTESTCASE(/* remove test_ from test function names */ creativetestnamegoeshere);
    return s;
}
int main (int argc, char * argv[])
Definition at line 34 of file skeleton_test.c.
References creativesuitenamegoeshere_suite().
{
    srand((unsigned int) time(NULL));
    Suite *creativesuitenamegoeshere = creativesuitenamegoeshere_suite();
    SRunner *test_runner = srunner_create(creativesuitenamegoeshere);
    int number_failed = 0;
    srunner_run_all(test_runner, CK_NORMAL);
    number_failed = srunner_ntests_failed(test_runner);
    srunner_free(test_runner);
    return number_failed;
}
START_TEST (test_creativetestnamegoeshere)
Definition at line 18 of file skeleton_test.c.
References ck_assert_msg().
{
    uint8_t test = 0;
    ck_assert_msg(test == 0, "test: expected result 0, got %u.", test);
}