toxcore/friend_connection.h File Reference
#include `net_crypto.h`
*
#include `DHT.h`
*
#include `LAN_discovery.h`
*
#include `onion_client.h`
*
Data Structures
struct Friend_Conn
struct Friend_Connections
Macros
#define MAX_FRIEND_CONNECTION_CALLBACKS 2
#define MESSENGER_CALLBACK_INDEX 0
#define GROUPCHAT_CALLBACK_INDEX 1
#define PACKET_ID_ALIVE 16
#define PACKET_ID_SHARE_RELAYS 17
#define PACKET_ID_FRIEND_REQUESTS 18
#define FRIEND_PING_INTERVAL 8
#define FRIEND_CONNECTION_TIMEOUT (FRIEND_PING_INTERVAL * 4)
#define FRIEND_DHT_TIMEOUT BAD_NODE_TIMEOUT
#define FRIEND_MAX_STORED_TCP_RELAYS (MAX_FRIEND_TCP_CONNECTIONS * 4)
#define MAX_SHARED_RELAYS (RECOMMENDED_FRIEND_TCP_CONNECTIONS)
#define SHARE_RELAYS_INTERVAL (5 * 60)
Enumerations
enum { FRIENDCONN_STATUS_NONE,
FRIENDCONN_STATUS_CONNECTING,
FRIENDCONN_STATUS_CONNECTED
 }
Functions
int getfriend_conn_id_pk (Friend_Connections *fr_c, const uint8_t *real_pk)
int friend_connection_lock (Friend_Connections *fr_c, int friendcon_id)
unsigned int friend_con_connected (Friend_Connections *fr_c, int friendcon_id)
int get_friendcon_public_keys (uint8_t *real_pk, uint8_t *dht_temp_pk, Friend_Connections *fr_c, int friendcon_id)
void set_dht_temp_pk (Friend_Connections *fr_c, int friendcon_id, const uint8_t *dht_temp_pk)
int friend_add_tcp_relay (Friend_Connections *fr_c, int friendcon_id, IP_Port ip_port, const uint8_t *public_key)
int friend_connection_callbacks (Friend_Connections *fr_c, int friendcon_id, unsigned int index, int(*status_callback)(void *object, int id, uint8_t status), int(*data_callback)(void *object, int id, uint8_t *data, uint16_t length), int(*lossy_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object, int number)
int friend_connection_crypt_connection_id (Friend_Connections *fr_c, int friendcon_id)
int new_friend_connection (Friend_Connections *fr_c, const uint8_t *real_public_key)
int kill_friend_connection (Friend_Connections *fr_c, int friendcon_id)
int send_friend_request_packet (Friend_Connections *fr_c, int friendcon_id, uint32_t nospam_num, const uint8_t *data, uint16_t length)
void set_friend_request_callback (Friend_Connections *fr_c, int(*fr_request_callback)(void *, const uint8_t *, const uint8_t *, uint16_t), void *object)
Friend_Connections * new_friend_connections (Onion_Client *onion_c)
void do_friend_connections (Friend_Connections *fr_c)
void kill_friend_connections (Friend_Connections *fr_c)
Macro Definition Documentation
#define FRIEND_CONNECTION_TIMEOUT (FRIEND_PING_INTERVAL * 4)
Definition at line 46 of file friend_connection.h.
Referenced by do_friend_connections().
#define FRIEND_DHT_TIMEOUT BAD_NODE_TIMEOUT
Definition at line 49 of file friend_connection.h.
Referenced by do_friend_connections().
#define FRIEND_MAX_STORED_TCP_RELAYS (MAX_FRIEND_TCP_CONNECTIONS * 4)
Definition at line 51 of file friend_connection.h.
Referenced by connect_to_saved_tcp_relays(), and friend_add_tcp_relay().
#define FRIEND_PING_INTERVAL 8
Definition at line 43 of file friend_connection.h.
Referenced by do_friend_connections().
#define GROUPCHAT_CALLBACK_INDEX 1
Definition at line 36 of file friend_connection.h.
Referenced by add_conn_to_groupchat().
#define MAX_FRIEND_CONNECTION_CALLBACKS 2
Definition at line 34 of file friend_connection.h.
Referenced by friend_connection_callbacks(), handle_lossy_packet(), handle_packet(), and handle_status().
#define MAX_SHARED_RELAYS (RECOMMENDED_FRIEND_TCP_CONNECTIONS)
Definition at line 54 of file friend_connection.h.
Referenced by handle_packet(), and send_relays().
#define MESSENGER_CALLBACK_INDEX 0
Definition at line 35 of file friend_connection.h.
Referenced by init_new_friend(), and m_delfriend().
#define PACKET_ID_ALIVE 16
Definition at line 38 of file friend_connection.h.
Referenced by handle_packet(), and send_ping().
#define PACKET_ID_FRIEND_REQUESTS 18
Definition at line 40 of file friend_connection.h.
Referenced by handle_packet(), and send_friend_request_packet().
#define PACKET_ID_SHARE_RELAYS 17
Definition at line 39 of file friend_connection.h.
Referenced by handle_packet(), and send_relays().
#define SHARE_RELAYS_INTERVAL (5 * 60)
Definition at line 57 of file friend_connection.h.
Referenced by do_friend_connections().
Enumeration Type Documentation
anonymous enum
Enumerator
FRIENDCONN_STATUS_NONE
FRIENDCONN_STATUS_CONNECTING
FRIENDCONN_STATUS_CONNECTED
Definition at line 60 of file friend_connection.h.
     {
    FRIENDCONN_STATUS_NONE,
    FRIENDCONN_STATUS_CONNECTING,
    FRIENDCONN_STATUS_CONNECTED
};
Function Documentation
void do_friend_connections (Friend_Connections * fr_c)
Definition at line 791 of file friend_connection.c.
References connect_to_saved_tcp_relays(), Friend_Conn::crypt_connection_id, crypto_kill(), Friend_Connections::dht, DHT_delfriend(), Friend_Conn::dht_ip_port, Friend_Conn::dht_ip_port_lastrecv, Friend_Conn::dht_lock, Friend_Conn::dht_pk_lastrecv, Friend_Conn::dht_temp_pk, IP::family, FRIEND_CONNECTION_TIMEOUT, FRIEND_DHT_TIMEOUT, friend_new_connection(), FRIEND_PING_INTERVAL, FRIENDCONN_STATUS_CONNECTED, FRIENDCONN_STATUS_CONNECTING, get_conn(), handle_status(), i, IP_Port::ip, LANdiscovery(), MAX_FRIEND_TCP_CONNECTIONS, Friend_Connections::net_crypto, Friend_Connections::num_cons, Friend_Conn::ping_lastrecv, Friend_Conn::ping_lastsent, send_ping(), send_relays(), set_direct_ip_port(), SHARE_RELAYS_INTERVAL, Friend_Conn::share_relays_lastsent, Friend_Conn::status, and unix_time().
Referenced by do_messenger().
{
    uint32_t i;
    uint64_t temp_time = unix_time();
    for (i = 0; i < fr_c->num_cons; ++i) {
        Friend_Conn *friend_con = get_conn(fr_c, i);
        if (friend_con) {
            if (friend_con->status == FRIENDCONN_STATUS_CONNECTING) {
                if (friend_con->dht_pk_lastrecv +
      FRIEND_DHT_TIMEOUT < temp_time) {
                    if (friend_con->dht_lock) {
                        DHT_delfriend(fr_c->dht, friend_con->
      dht_temp_pk, friend_con->dht_lock);
                        friend_con->dht_lock = 0;
                    }
                }
                if (friend_con->dht_ip_port_lastrecv +
      FRIEND_DHT_TIMEOUT < temp_time) {
                    friend_con->dht_ip_port.ip.family = 0;
                }
                if (friend_con->dht_lock) {
                    if (friend_new_connection(fr_c, i) == 0) {
                        set_direct_ip_port(fr_c->net_crypto, friend_con->
      crypt_connection_id, friend_con->dht_ip_port, 0);
                        connect_to_saved_tcp_relays(fr_c, i, (
      MAX_FRIEND_TCP_CONNECTIONS / 2)); /* Only fill it half up. */
                    }
                }
            } else if (friend_con->status == FRIENDCONN_STATUS_CONNECTED)
      {
                if (friend_con->ping_lastsent +
      FRIEND_PING_INTERVAL < temp_time) {
                    send_ping(fr_c, i);
                }
                if (friend_con->share_relays_lastsent +
      SHARE_RELAYS_INTERVAL < temp_time) {
                    send_relays(fr_c, i);
                }
                if (friend_con->ping_lastrecv +
      FRIEND_CONNECTION_TIMEOUT < temp_time) {
                    /* If we stopped receiving ping packets, kill it. */
                    crypto_kill(fr_c->net_crypto, friend_con->
      crypt_connection_id);
                    friend_con->crypt_connection_id = -1;
                    handle_status(fr_c, i, 0); /* Going offline. */
                }
            }
        }
    }
    LANdiscovery(fr_c);
}
int friend_add_tcp_relay (Friend_Connections * fr_c, int friendcon_id, IP_Port ip_port, const uint8_t * public_key)
Definition at line 154 of file friend_connection.c.
References add_tcp_relay_peer(), Friend_Conn::crypt_connection_id, Friend_Conn::dht_ip_port, Friend_Conn::dht_temp_pk, IP::family, FRIEND_MAX_STORED_TCP_RELAYS, get_conn(), Friend_Conn::hosting_tcp_relay, i, IP_Port::ip, Node_format::ip_port, Local_ip(), Friend_Connections::net_crypto, Node_format::public_key, Friend_Conn::tcp_relay_counter, and Friend_Conn::tcp_relays.
Referenced by dht_ip_callback(), handle_packet(), send_relays(), and tcp_relay_node_callback().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    /* Local ip and same pk means that they are hosting a TCP relay. */
    if (Local_ip(ip_port.ip) && memcmp(friend_con->dht_temp_pk,
      public_key, crypto_box_PUBLICKEYBYTES) == 0) {
        if (friend_con->dht_ip_port.ip.family != 0) {
            ip_port.ip = friend_con->dht_ip_port.ip;
        } else {
            friend_con->hosting_tcp_relay = 0;
        }
    }
    unsigned int i;
    uint16_t index = friend_con->tcp_relay_counter %
      FRIEND_MAX_STORED_TCP_RELAYS;
    for (i = 0; i < FRIEND_MAX_STORED_TCP_RELAYS; ++
      i) {
        if (friend_con->tcp_relays[i].ip_port.ip.family != 0
                && memcmp(friend_con->tcp_relays[i].public_key,
      public_key, crypto_box_PUBLICKEYBYTES) == 0) {
            memset(&friend_con->tcp_relays[i], 0, sizeof(Node_format));
        }
    }
    friend_con->tcp_relays[index].ip_port = ip_port;
    memcpy(friend_con->tcp_relays[index].public_key,
      public_key, crypto_box_PUBLICKEYBYTES);
    ++friend_con->tcp_relay_counter;
    return add_tcp_relay_peer(fr_c->net_crypto, friend_con->
      crypt_connection_id, ip_port, public_key);
}
unsigned int friend_con_connected (Friend_Connections * fr_c, int friendcon_id)
Definition at line 561 of file friend_connection.c.
References get_conn(), and Friend_Conn::status.
Referenced by connect_to_closest(), init_new_friend(), and m_delfriend().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return 0;
    return friend_con->status;
}
int friend_connection_callbacks (Friend_Connections * fr_c, int friendcon_id, unsigned int index, int(*)(void *object, int id, uint8_t status) status_callback, int(*)(void *object, int id, uint8_t *data, uint16_t length) data_callback, int(*)(void *object, int id, const uint8_t *data, uint16_t length) lossy_data_callback, void * object, int number)
Definition at line 605 of file friend_connection.c.
References Friend_Conn::callbacks, Friend_Conn::data_callback, data_callback(), Friend_Conn::data_callback_id, Friend_Conn::data_callback_object, get_conn(), Friend_Conn::lossy_data_callback, Friend_Conn::lossy_data_callback_id, Friend_Conn::lossy_data_callback_object, MAX_FRIEND_CONNECTION_CALLBACKS, Friend_Conn::status_callback, status_callback(), Friend_Conn::status_callback_id, and Friend_Conn::status_callback_object.
Referenced by add_conn_to_groupchat(), init_new_friend(), and m_delfriend().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (index >= MAX_FRIEND_CONNECTION_CALLBACKS)
        return -1;
    friend_con->callbacks[index].status_callback =
      status_callback;
    friend_con->callbacks[index].data_callback =
      data_callback;
    friend_con->callbacks[index].lossy_data_callback = lossy_data_callback;
    friend_con->callbacks[index].status_callback_object =
        friend_con->callbacks[index].data_callback_object =
            friend_con->callbacks[index].lossy_data_callback_object =
      object;
    friend_con->callbacks[index].status_callback_id =
        friend_con->callbacks[index].data_callback_id =
            friend_con->callbacks[index].lossy_data_callback_id = number;
    return 0;
}
int friend_connection_crypt_connection_id (Friend_Connections * fr_c, int friendcon_id)
Definition at line 637 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, and get_conn().
Referenced by do_reqchunk_filecb(), file_data(), friend_received_packet(), m_get_friend_connectionstatus(), m_send_message_generic(), send_custom_lossless_packet(), send_custom_lossy_packet(), send_file_data_packet(), send_lossy_group_peer(), send_offline_packet(), send_online_packet(), send_packet_group_peer(), send_packet_online(), and write_cryptpacket_id().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    return friend_con->crypt_connection_id;
}
int friend_connection_lock (Friend_Connections * fr_c, int friendcon_id)
Definition at line 546 of file friend_connection.c.
References get_conn(), and Friend_Conn::lock_count.
Referenced by add_conn_to_groupchat().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    ++friend_con->lock_count;
    return 0;
}
int get_friendcon_public_keys (uint8_t * real_pk, uint8_t * dht_temp_pk, Friend_Connections * fr_c, int friendcon_id)
Definition at line 576 of file friend_connection.c.
References Friend_Conn::dht_temp_pk, get_conn(), and Friend_Conn::real_public_key.
Referenced by connect_to_closest(), handle_friend_invite_packet(), and send_lossy_all_close().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (real_pk)
        memcpy(real_pk, friend_con->real_public_key, crypto_box_PUBLICKEYBYTES);
    if (dht_temp_pk)
        memcpy(dht_temp_pk, friend_con->dht_temp_pk, crypto_box_PUBLICKEYBYTES);
    return 0;
}
int getfriend_conn_id_pk (Friend_Connections * fr_c, const uint8_t * real_pk)
Definition at line 133 of file friend_connection.c.
References get_conn(), i, Friend_Connections::num_cons, and Friend_Conn::real_public_key.
Referenced by connect_to_closest(), delpeer(), handle_new_connections(), and new_friend_connection().
{
    uint32_t i;
    for (i = 0; i < fr_c->num_cons; ++i) {
        Friend_Conn *friend_con = get_conn(fr_c, i);
        if (friend_con) {
            if (memcmp(friend_con->real_public_key, real_pk, crypto_box_PUBLICKEYBYTES) == 0
      )
                return i;
        }
    }
    return -1;
}
int kill_friend_connection (Friend_Connections * fr_c, int friendcon_id)
Definition at line 690 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, crypto_kill(), Friend_Connections::dht, DHT_delfriend(), Friend_Conn::dht_lock, Friend_Conn::dht_temp_pk, get_conn(), Friend_Conn::lock_count, Friend_Connections::net_crypto, Friend_Connections::onion_c, onion_delfriend(), Friend_Conn::onion_friendnum, and wipe_friend_conn().
Referenced by connect_to_closest(), del_groupchat(), handle_direct_packet(), handle_packet_online(), kill_friend_connections(), m_delfriend(), and remove_close_conn().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (friend_con->lock_count) {
        --friend_con->lock_count;
        return 0;
    }
    onion_delfriend(fr_c->onion_c, friend_con->
      onion_friendnum);
    crypto_kill(fr_c->net_crypto, friend_con->
      crypt_connection_id);
    if (friend_con->dht_lock) {
        DHT_delfriend(fr_c->dht, friend_con->dht_temp_pk, friend_con->
      dht_lock);
    }
    return wipe_friend_conn(fr_c, friendcon_id);
}
void kill_friend_connections (Friend_Connections * fr_c)
Definition at line 842 of file friend_connection.c.
References Friend_Connections::dht, i, kill_friend_connection(), LANdiscovery_kill(), and Friend_Connections::num_cons.
Referenced by kill_messenger(), and new_messenger().
{
    if (!fr_c)
        return;
    uint32_t i;
    for (i = 0; i < fr_c->num_cons; ++i) {
        kill_friend_connection(fr_c, i);
    }
    LANdiscovery_kill(fr_c->dht);
    free(fr_c);
}
int new_friend_connection (Friend_Connections * fr_c, const uint8_t * real_public_key)
Definition at line 653 of file friend_connection.c.
References Friend_Connections::conns, create_friend_conn(), Friend_Conn::crypt_connection_id, dht_pk_callback(), FRIENDCONN_STATUS_CONNECTING, getfriend_conn_id_pk(), Friend_Conn::lock_count, onion_addfriend(), Friend_Connections::onion_c, onion_dht_pk_callback(), Friend_Conn::onion_friendnum, Friend_Conn::real_public_key, recv_tcp_relay_handler(), Friend_Conn::status, and tcp_relay_node_callback().
Referenced by connect_to_closest(), and init_new_friend().
{
    int friendcon_id = getfriend_conn_id_pk(fr_c, real_public_key);
    if (friendcon_id != -1) {
        ++fr_c->conns[friendcon_id].lock_count;
        return friendcon_id;
    }
    friendcon_id = create_friend_conn(fr_c);
    if (friendcon_id == -1)
        return -1;
    int32_t onion_friendnum = onion_addfriend(fr_c->onion_c, real_public_key);
    if (onion_friendnum == -1)
        return -1;
    Friend_Conn *friend_con = &fr_c->conns[friendcon_id];
    friend_con->crypt_connection_id = -1;
    friend_con->status = FRIENDCONN_STATUS_CONNECTING;
    memcpy(friend_con->real_public_key, real_public_key, crypto_box_PUBLICKEYBYTES);
    friend_con->onion_friendnum = onion_friendnum;
    recv_tcp_relay_handler(fr_c->onion_c, onion_friendnum, &
      tcp_relay_node_callback, fr_c, friendcon_id);
    onion_dht_pk_callback(fr_c->onion_c, onion_friendnum, &
      dht_pk_callback, fr_c, friendcon_id);
    return friendcon_id;
}
Friend_Connections* new_friend_connections (Onion_Client * onion_c)
Definition at line 761 of file friend_connection.c.
References Onion_Client::c, Friend_Connections::dht, Onion_Client::dht, handle_new_connections(), LANdiscovery_init(), Friend_Connections::net_crypto, new_connection_handler(), and Friend_Connections::onion_c.
Referenced by new_messenger().
{
    if (!onion_c)
        return NULL;
    Friend_Connections *temp = calloc(1, sizeof(
      Friend_Connections));
    if (temp == NULL)
        return NULL;
    temp->dht = onion_c->dht;
    temp->net_crypto = onion_c->c;
    temp->onion_c = onion_c;
    new_connection_handler(temp->net_crypto, &
      handle_new_connections, temp);
    LANdiscovery_init(temp->dht);
    return temp;
}
int send_friend_request_packet (Friend_Connections * fr_c, int friendcon_id, uint32_t nospam_num, const uint8_t * data, uint16_t length)
Definition at line 731 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, CRYPTO_PACKET_FRIEND_REQ, FRIENDCONN_STATUS_CONNECTED, get_conn(), Friend_Connections::net_crypto, num, Friend_Connections::onion_c, ONION_CLIENT_MAX_DATA_SIZE, Friend_Conn::onion_friendnum, PACKET_ID_FRIEND_REQUESTS, send_onion_data(), Friend_Conn::status, and write_cryptpacket().
Referenced by do_friends().
{
    if (1 + sizeof(nospam_num) + length > ONION_CLIENT_MAX_DATA_SIZE || length ==
       0)
        return -1;
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    uint8_t packet[1 + sizeof(nospam_num) + length];
    memcpy(packet + 1, &nospam_num, sizeof(nospam_num));
    memcpy(packet + 1 + sizeof(nospam_num), data, length);
    if (friend_con->status == FRIENDCONN_STATUS_CONNECTED) {
        packet[0] = PACKET_ID_FRIEND_REQUESTS;
        return write_cryptpacket(fr_c->net_crypto, friend_con->
      crypt_connection_id, packet, sizeof(packet), 0) != -1;
    } else {
        packet[0] = CRYPTO_PACKET_FRIEND_REQ;
        int num = send_onion_data(fr_c->onion_c, friend_con->
      onion_friendnum, packet, sizeof(packet));
        if (num <= 0)
            return -1;
        return num;
    }
}
void set_dht_temp_pk (Friend_Connections * fr_c, int friendcon_id, const uint8_t * dht_temp_pk)
Definition at line 594 of file friend_connection.c.
References dht_pk_callback().
Referenced by connect_to_closest().
{
    dht_pk_callback(fr_c, friendcon_id, dht_temp_pk);
}
void set_friend_request_callback (Friend_Connections * fr_c, int(*)(void *, const uint8_t *, const uint8_t *, uint16_t) fr_request_callback, void * object)
Definition at line 717 of file friend_connection.c.
References CRYPTO_PACKET_FRIEND_REQ, Friend_Connections::fr_request_callback, Friend_Connections::fr_request_object, Friend_Connections::onion_c, and oniondata_registerhandler().
Referenced by friendreq_init().
{
    fr_c->fr_request_callback = fr_request_callback;
    fr_c->fr_request_object = object;
    oniondata_registerhandler(fr_c->onion_c,
      CRYPTO_PACKET_FRIEND_REQ, fr_request_callback, object);
}