toxcore/assoc.h File Reference
Data Structures
struct Assoc_close_entries
Macros
#define ASSOC_AVAILABLE
#define DISTANCE_INDEX_DISTANCE_BITS 44
#define ASSOC_BUCKET_REFRESH 45
Typedefs
typedef struct Assoc Assoc
typedef int(* Assoc_distance_relative_callback)(const Assoc *assoc, void *callback_data, const uint8_t *client_id, const uint8_t *client_id1, const uint8_t *client_id2)
typedef uint64_t(* Assoc_distance_absolute_callback)(const Assoc *assoc, void *callback_data, const uint8_t *client_id_ref, const uint8_t *client_id_check)
typedef enum AssocCloseEntriesFlags AssocCloseEntriesFlags
typedef struct Assoc_close_entries Assoc_close_entries
Enumerations
enum NODE_STATUS { BAD,
SEENB_HEARDG,
SEENG,
USED
 }
enum AssocCloseEntriesFlags { ProtoIPv4 = 1,
ProtoIPv6 = 2,
LANOk = 4
 }
Functions
uint8_t Assoc_add_entry (Assoc *assoc, const uint8_t *id, const IPPTs *ippts_send, const IP_Port *ipp_recv, uint8_t used)
uint8_t Assoc_get_close_entries (Assoc *assoc, Assoc_close_entries *close_entries)
Assoc * new_Assoc_default (const uint8_t *public_id)
Assoc * new_Assoc (size_t bits, size_t entries, const uint8_t *public_id)
void Assoc_self_client_id_changed (Assoc *assoc, const uint8_t *public_id)
void do_Assoc (Assoc *assoc, DHT *dht)
void kill_Assoc (Assoc *assoc)
Macro Definition Documentation
#define ASSOC_AVAILABLE
Definition at line 6 of file assoc.h.
#define ASSOC_BUCKET_REFRESH 45
Definition at line 91 of file assoc.h.
Referenced by do_Assoc().
#define DISTANCE_INDEX_DISTANCE_BITS 44
Definition at line 27 of file assoc.h.
Referenced by id_distance().
Typedef Documentation
typedef struct Assoc Assoc
Definition at line 18 of file assoc.h.
typedef struct Assoc_close_entries Assoc_close_entries
typedef uint64_t(* Assoc_distance_absolute_callback)(const Assoc *assoc, void *callback_data, const uint8_t *client_id_ref, const uint8_t *client_id_check)
Definition at line 31 of file assoc.h.
typedef int(* Assoc_distance_relative_callback)(const Assoc *assoc, void *callback_data, const uint8_t *client_id, const uint8_t *client_id1, const uint8_t *client_id2)
Definition at line 24 of file assoc.h.
typedef enum AssocCloseEntriesFlags AssocCloseEntriesFlags
Enumeration Type Documentation
enum AssocCloseEntriesFlags
Enumerator
ProtoIPv4
ProtoIPv6
LANOk
Definition at line 43 of file assoc.h.
                                    {
    ProtoIPv4 = 1,
    ProtoIPv6 = 2,
    LANOk = 4,
} AssocCloseEntriesFlags;
enum NODE_STATUS
Enumerator
BAD
SEENB_HEARDG
SEENG
USED
Definition at line 11 of file assoc.h.
{ BAD, SEENB_HEARDG, SEENG, USED };
Function Documentation
uint8_t Assoc_add_entry (Assoc * assoc, const uint8_t * id, const IPPTs * ippts_send, const IP_Port * ipp_recv, uint8_t used)
Definition at line 552 of file assoc.c.
References candidates_create_new(), candidates_search(), candidates_update_assoc(), client_id_self_update(), id_equal(), id_hash(), IPPTs::ip_port, ipport_isset(), Assoc::self_client_id, and Assoc::self_hash.
Referenced by addto_lists(), returnedip_ports(), and START_TEST().
{
    if (!assoc || !id || !ippts_send)
        return 0;
    if (!assoc->self_hash) {
        client_id_self_update(assoc);
        if (!assoc->self_hash)
            return 0;
    }
    if (!ipport_isset(&ippts_send->ip_port))
        return 0;
    if (ipp_recv && !ipport_isset(ipp_recv))
        ipp_recv = NULL;
    hash_t hash = id_hash(assoc, id);
    if (hash == assoc->self_hash)
        if (id_equal(id, assoc->self_client_id))
            return 0;
    /* if it's new:
     * callback, if there's desire, add to clients, else to candidates
     *
     * if it's "old":
     * if it's client: refresh
     * if it's candidate:
     * if !ipp_recv, refresh
     * if ipp_recv: callback, if there's desire, move to candidates
     */
    Client_entry *cnd_entry;
    if (!candidates_search(assoc, id, hash, &cnd_entry)) {
        if (candidates_create_new(assoc, hash, id, used, ippts_send, ipp_recv))
            return 1;
        else
            return 0;
    } else {
        candidates_update_assoc(assoc, cnd_entry, used, ippts_send, ipp_recv);
        return 2;
    }
}
uint8_t Assoc_get_close_entries (Assoc * assoc, Assoc_close_entries * close_entries)
Definition at line 602 of file assoc.c.
References Client_data::assoc4, Client_data::assoc6, assoc_id_closest(), BAD_NODE_TIMEOUT, Assoc::candidates, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, Client_entry::client, client_id_self_update(), Assoc_close_entries::count_good, Assoc_close_entries::custom_data, dist_index_bubble(), dist_index_comp(), dist_index_entry(), Assoc_close_entries::distance_absolute_func, DISTANCE_INDEX_INDEX_BITS, DISTANCE_INDEX_INDEX_MASK, Assoc_close_entries::distance_relative_func, Assoc_close_entries::flags, Client_entry::hash, i, id_distance(), IP_Port::ip, IPPTsPng::ip_port, ipport_isset(), is_timeout(), LAN_ip(), LANOk, candidates_bucket::list, ProtoIPv4, ProtoIPv6, Client_data::public_key, Assoc_close_entries::result, Client_entry::seen_at, Assoc::self_hash, IPPTsPng::timestamp, and Assoc_close_entries::wanted_id.
Referenced by DHT_addfriend(), get_close_nodes(), and START_TEST().
{
    if (!assoc || !state || !state->wanted_id || !state->result)
        return 0;
    if (!assoc->self_hash) {
        client_id_self_update(assoc);
        if (!assoc->self_hash)
            return 0;
    }
    if (!state->distance_relative_func)
        state->distance_relative_func = assoc_id_closest;
    if (!state->distance_absolute_func)
        state->distance_absolute_func = id_distance;
    size_t dist_list_len = assoc->candidates_bucket_count * assoc->
      candidates_bucket_size;
    uint64_t dist_list[dist_list_len];
    memset(dist_list, ~0, dist_list_len * sizeof(dist_list[0]));
    bucket_t b;
    size_t i;
    for (b = 0; b < assoc->candidates_bucket_count; b++) {
        candidates_bucket *cnd_bckt = &assoc->candidates[b];
        for (i = 0; i < assoc->candidates_bucket_size; i++) {
            Client_entry *entry = &cnd_bckt->list[i];
            if (entry->hash) {
                if (state->flags & ProtoIPv4) {
                    if (!ipport_isset(&entry->client.assoc4.
      ip_port))
                        continue;
                    if (!(state->flags & LANOk))
                        if (!LAN_ip(entry->client.assoc4.
      ip_port.ip))
                            continue;
                }
                if (state->flags & ProtoIPv6) {
                    if (!ipport_isset(&entry->client.assoc6.
      ip_port))
                        continue;
                    if (!(state->flags & LANOk))
                        if (!LAN_ip(entry->client.assoc6.
      ip_port.ip))
                            continue;
                }
                uint64_t dist = state->distance_absolute_func(assoc, state->custom_data, state->wanted_id,
      entry->client.public_key);
                uint32_t index = b * assoc->candidates_bucket_size +
      i;
                dist_list[index] = (dist << DISTANCE_INDEX_INDEX_BITS) | index;
            }
        }
    }
    qsort(dist_list, dist_list_len, sizeof(dist_list[0]), dist_index_comp);
    /* ok, ok, it's not *perfectly* sorted, because we used an absolute distance
     * go over the result and see if we need to "smoothen things out"
     * because those should be only very few and short streaks, the worst regularly
     * used sorting function aka bubble sort is used */
    uint64_t dist_prev = ~0;
    size_t ind_prev = ~0, ind_curr;
    size_t len = 1;
    for (ind_curr = 0; ind_curr < dist_list_len; ind_curr++) {
        /* sorted increasingly, so an invalid entry marks the end */
        if ((dist_list[ind_curr] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
            break;
        uint64_t dist_curr = dist_list[ind_curr] >> DISTANCE_INDEX_INDEX_BITS;
        if (dist_prev == dist_curr)
            len++;
        else {
            if (len > 1)
                dist_index_bubble(assoc, dist_list, ind_prev, ind_curr - 1, state->
      wanted_id, state->custom_data,
                                  state->distance_relative_func);
            dist_prev = dist_curr;
            ind_prev = ind_curr;
            len = 1;
        }
    }
    if (len > 1)
        dist_index_bubble(assoc, dist_list, ind_prev, ind_curr - 1, state->wanted_id,
      state->custom_data,
                          state->distance_relative_func);
    /* ok, now dist_list is a strictly ascending sorted list of nodes
     * a) extract CLOSE_QUOTA_USED clients, not timed out
     * b) extract (1 - QUOTA) (better!) clients & candidates, not timed out
     * c) save candidates which would be better, if contact can be established */
    size_t client_quota_good = 0, pos = 0;
    size_t client_quota_max = state->count_good;
    ssize_t taken_last = - 1;
    for (i = 0; (i < dist_list_len) && (pos < state->count); i++) {
        /* sorted increasingly, so an invalid entry marks the end */
        if ((dist_list[i] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
            break;
        Client_entry *entry = dist_index_entry(assoc, dist_list[i]);
        if (entry && entry->hash) {
            if (client_quota_good >= client_quota_max) {
                state->result[pos++] = &entry->client;
                taken_last = i;
            } else {
                if (state->flags & (ProtoIPv4 | ProtoIPv6)) {
                    if ((state->flags & ProtoIPv4) && is_timeout(entry->
      client.assoc4.timestamp, BAD_NODE_TIMEOUT))
                        continue;
                    if ((state->flags & ProtoIPv6) && is_timeout(entry->
      client.assoc6.timestamp, BAD_NODE_TIMEOUT))
                        continue;
                } else if (is_timeout(entry->seen_at,
      BAD_NODE_TIMEOUT))
                    continue;
                state->result[pos++] = &entry->client;
                client_quota_good++;
                taken_last = i;
            }
        }
    }
    /* if we had not enough valid entries the list might still not be filled.
     *
     * start again from last taken client, but leave out any requirement
     */
    if (pos < state->count) {
        for (i = taken_last + 1; (i < dist_list_len) && (pos < state->count); i++) {
            /* sorted increasingly, so an invalid entry marks the end */
            if ((dist_list[i] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
                break;
            Client_entry *entry = dist_index_entry(assoc, dist_list[i]);
            if (entry && entry->hash)
                state->result[pos++] = &entry->client;
        }
    }
    return pos;
}
void Assoc_self_client_id_changed (Assoc * assoc, const uint8_t * public_id)
Definition at line 872 of file assoc.c.
References client_id_self_update(), id_copy(), Assoc::self_client_id, and Assoc::self_hash.
{
    if (assoc && id) {
        assoc->self_hash = 0;
        id_copy(assoc->self_client_id, id);
        client_id_self_update(assoc);
    }
}
void do_Assoc (Assoc * assoc, DHT * dht)
Definition at line 886 of file assoc.c.
References ASSOC_BUCKET_REFRESH, Assoc::candidates, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, CANDIDATES_HEARD_TIMEOUT, CANDIDATES_SEEN_TIMEOUT, Client_entry::client, DHT_getnodes(), for(), Client_entry::getnodes, Assoc::getnodes, Client_entry::hash, Client_entry::heard_at, i, IP_Port::ip, ip_ntoa(), IPPTsPng::ip_port, is_timeout(), candidates_bucket::list, LOGGER_DEBUG, LOGGER_SCOPE, m, IP_Port::port, Client_data::public_key, Client_entry::seen_at, and unix_time().
Referenced by do_DHT().
{
    if (is_timeout(assoc->getnodes, ASSOC_BUCKET_REFRESH)) {
        assoc->getnodes = unix_time();
        size_t candidate = (rand() % assoc->candidates_bucket_count) + assoc->
      candidates_bucket_count;
        /* in that bucket or the buckets closest to it:
         * find the best heard candidate
         * find the best seen candidate
         * send getnode() requests to both */
        uint8_t *target_id = NULL;
        Client_entry *heard = NULL, *seen = NULL;
        size_t i, k, m;
        for (i = 1; i < assoc->candidates_bucket_count; i++) {
            if (i % 2)
                k = - (i >> 1);
            else
                k = i >> 1;
            size_t bckt = (candidate + k) % assoc->candidates_bucket_count;
            for (m = 0; m < assoc->candidates_bucket_size;
      m++)
                if (assoc->candidates[bckt].list[m].hash) {
                    Client_entry *entry = &assoc->candidates[bckt].
      list[m];
                    if (!is_timeout(entry->getnodes,
      CANDIDATES_SEEN_TIMEOUT))
                        continue;
                    if (!target_id)
                        target_id = entry->client.public_key;
                    if (entry->seen_at) {
                        if (!seen)
                            if (!is_timeout(entry->seen_at,
      CANDIDATES_SEEN_TIMEOUT))
                                seen = entry;
                    }
                    if (entry->heard_at) {
                        if (!heard)
                            if (!is_timeout(entry->heard_at,
      CANDIDATES_HEARD_TIMEOUT))
                                heard = entry;
                    }
                    if (seen && heard)
                        break;
                }
            if (seen && heard)
                break;
        }
        if (seen) {
            IPPTsPng *ippts = seen->seen_family == AF_INET ? &seen->client.assoc4 : &seen->client.
      assoc6;
            LOGGER_DEBUG("[%u] => S[%s...] %s:%u", (uint32_t)(candidate % assoc->
      candidates_bucket_count),
                         idpart2str(seen->client.public_key, 8), ip_ntoa(&ippts->
      ip_port.ip), htons(ippts->ip_port.port));
            DHT_getnodes(dht, &ippts->ip_port, seen->client.public_key, target_id);
            seen->getnodes = unix_time();
        }
        if (heard && (heard != seen)) {
            IP_Port *ipp = heard->heard_family == AF_INET ? &heard->assoc_heard4 : &heard->
      assoc_heard6;
            LOGGER_DEBUG("[%u] => H[%s...] %s:%u", (uint32_t)(candidate % assoc->
      candidates_bucket_count),
                         idpart2str(heard->client.public_key, 8), ip_ntoa(&ipp->
      ip), htons(ipp->port));
            DHT_getnodes(dht, ipp, heard->client.public_key, target_id);
            heard->getnodes = unix_time();
        }
        LOGGER_SCOPE (
            if (!heard && !seen)
            LOGGER_DEBUG("[%u] => no nodes to talk to??", (uint32_t)(candidate % assoc->
      candidates_bucket_count));
        );
    }
}
void kill_Assoc (Assoc * assoc)
Definition at line 968 of file assoc.c.
References Assoc::candidates, and candidates_bucket::list.
Referenced by kill_DHT(), and START_TEST().
{
    if (assoc) {
        free(assoc->candidates->list);
        free(assoc->candidates);
        free(assoc);
    }
}
Assoc* new_Assoc (size_t bits, size_t entries, const uint8_t * public_id)
Definition at line 779 of file assoc.c.
References Assoc::candidates, Assoc::candidates_bucket_bits, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, client_id_self_update(), Assoc::getnodes, Client_entry::hash, HASH_COLLIDE_PRIME, id_copy(), candidates_bucket::list, LOGGER_DEBUG, prime_upto_min9(), Assoc::self_client_id, and unix_time().
Referenced by new_Assoc_default(), and START_TEST().
{
    if (!public_id)
        return NULL;
    Assoc *assoc = calloc(1, sizeof(*assoc));
    if (!assoc)
        return NULL;
    /*
     * bits must be in [ 2 .. 15 ]
     * entries must be a prime
     */
    if (bits < 2)
        bits = 2;
    else if (bits > 15)
        bits = 15;
    assoc->candidates_bucket_bits = bits;
    assoc->candidates_bucket_count = 1U << bits;
    if (entries < 25) {
        if (entries <= 6)
            entries = 5;
        else {
            entries = entries - (1 - (entries % 2)); /* even => odd */
            /* 7..23: all odds but 9&15 are prime */
            if (!(entries % 3)) /* 9, 15 */
                entries -= 2; /* 7, 13 */
        }
    } else if (entries > ((1 << 17) - 1)) /* 130k+ */
        entries = (1 << 17) - 1;
    else {
        /* 9+: test and find a prime less or equal */
        size_t entries_test = prime_upto_min9(entries);
        if (entries_test == HASH_COLLIDE_PRIME) /* disallowed */
            entries_test = prime_upto_min9(entries_test - 1);
        if (entries_test != entries) {
            LOGGER_DEBUG("trimmed %i to %i.\n", (int)entries, (int)entries_test);
            entries = (size_t)entries_test;
        }
    }
    assoc->candidates_bucket_size = entries;
    /* allocation: preferably few blobs */
    size_t bckt, cix;
    Client_entry *clients = malloc(sizeof(*clients) * assoc->
      candidates_bucket_count * assoc->candidates_bucket_size);
    if (!clients) {
        free(assoc);
        return NULL;
    }
    candidates_bucket *lists = malloc(sizeof(*lists) * assoc->
      candidates_bucket_count);
    if (!lists) {
        free(assoc);
        free(clients);
        return NULL;
    }
    for (bckt = 0; bckt < assoc->candidates_bucket_count; bckt++) {
        candidates_bucket *list = &lists[bckt];
        list->list = &clients[bckt * assoc->candidates_bucket_size];
        for (cix = 0; cix < assoc->candidates_bucket_size; cix++)
            list->list[cix].hash = 0;
    }
    assoc->candidates = lists;
    assoc->getnodes = unix_time();
    id_copy(assoc->self_client_id, public_id);
    client_id_self_update(assoc);
    return assoc;
}
Assoc* new_Assoc_default (const uint8_t * public_id)
Definition at line 864 of file assoc.c.
References new_Assoc().
Referenced by new_DHT(), and START_TEST().
{
    /* original 8, 251 averages to ~32k entries... probably the whole DHT :D
     * 320 entries is fine, hopefully */
    return new_Assoc(6, 15, public_id);
}