toxcore/TCP_client.h File Reference
#include `crypto_core.h`
*
#include `TCP_server.h`
*
Data Structures
struct TCP_Proxy_Info
struct TCP_Client_Connection
Macros
#define TCP_CONNECTION_TIMEOUT 10
Enumerations
enum TCP_PROXY_TYPE { TCP_PROXY_NONE,
TCP_PROXY_HTTP,
TCP_PROXY_SOCKS5
 }
enum {
*
TCP_CLIENT_NO_STATUS,
TCP_CLIENT_PROXY_HTTP_CONNECTING,
TCP_CLIENT_PROXY_SOCKS5_CONNECTING,
TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED,
*
TCP_CLIENT_CONNECTING,
TCP_CLIENT_UNCONFIRMED,
TCP_CLIENT_CONFIRMED,
TCP_CLIENT_DISCONNECTED
 }
Functions
TCP_Client_Connection * new_TCP_connection (IP_Port ip_port, const uint8_t *public_key, const uint8_t *self_public_key, const uint8_t *self_secret_key, TCP_Proxy_Info *proxy_info)
void do_TCP_connection (TCP_Client_Connection *TCP_connection)
void kill_TCP_connection (TCP_Client_Connection *TCP_connection)
int send_onion_request (TCP_Client_Connection *con, const uint8_t *data, uint16_t length)
void onion_response_handler (TCP_Client_Connection *con, int(*onion_callback)(void *object, const uint8_t *data, uint16_t length), void *object)
int send_routing_request (TCP_Client_Connection *con, uint8_t *public_key)
void routing_response_handler (TCP_Client_Connection *con, int(*response_callback)(void *object, uint8_t connection_id, const uint8_t *public_key), void *object)
void routing_status_handler (TCP_Client_Connection *con, int(*status_callback)(void *object, uint32_t number, uint8_t connection_id, uint8_t status), void *object)
int send_disconnect_request (TCP_Client_Connection *con, uint8_t con_id)
int set_tcp_connection_number (TCP_Client_Connection *con, uint8_t con_id, uint32_t number)
int send_data (TCP_Client_Connection *con, uint8_t con_id, const uint8_t *data, uint16_t length)
void routing_data_handler (TCP_Client_Connection *con, int(*data_callback)(void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length), void *object)
int send_oob_packet (TCP_Client_Connection *con, const uint8_t *public_key, const uint8_t *data, uint16_t length)
void oob_data_handler (TCP_Client_Connection *con, int(*oob_data_callback)(void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length), void *object)
Macro Definition Documentation
#define TCP_CONNECTION_TIMEOUT 10
Definition at line 30 of file TCP_client.h.
Referenced by new_TCP_connection().
Enumeration Type Documentation
anonymous enum
Enumerator
TCP_CLIENT_NO_STATUS
TCP_CLIENT_PROXY_HTTP_CONNECTING
TCP_CLIENT_PROXY_SOCKS5_CONNECTING
TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED
TCP_CLIENT_CONNECTING
TCP_CLIENT_UNCONFIRMED
TCP_CLIENT_CONFIRMED
TCP_CLIENT_DISCONNECTED
Definition at line 43 of file TCP_client.h.
     {
    TCP_CLIENT_NO_STATUS,
    TCP_CLIENT_PROXY_HTTP_CONNECTING,
    TCP_CLIENT_PROXY_SOCKS5_CONNECTING,
    TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED,
    TCP_CLIENT_CONNECTING,
    TCP_CLIENT_UNCONFIRMED,
    TCP_CLIENT_CONFIRMED,
    TCP_CLIENT_DISCONNECTED,
};
enum TCP_PROXY_TYPE
Enumerator
TCP_PROXY_NONE
TCP_PROXY_HTTP
TCP_PROXY_SOCKS5
Definition at line 32 of file TCP_client.h.
             {
    TCP_PROXY_NONE,
    TCP_PROXY_HTTP,
    TCP_PROXY_SOCKS5
} TCP_PROXY_TYPE;
Function Documentation
void do_TCP_connection (TCP_Client_Connection * TCP_connection)
Definition at line 870 of file TCP_client.c.
References make-funny-savefile::data, do_confirmed_TCP(), generate_handshake(), handle_handshake(), TCP_Client_Connection::kill_at, proxy_http_read_connection_response(), proxy_socks5_generate_connection_request(), proxy_socks5_read_connection_response(), read_TCP_packet(), send_pending_data(), TCP_Client_Connection::sock, socks5_read_handshake_response(), TCP_Client_Connection::status, TCP_CLIENT_CONFIRMED, TCP_CLIENT_CONNECTING, TCP_CLIENT_DISCONNECTED, TCP_CLIENT_PROXY_HTTP_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED, TCP_CLIENT_UNCONFIRMED, TCP_SERVER_HANDSHAKE_SIZE, unix_time(), and unix_time_update().
Referenced by do_tcp_conns(), and START_TEST().
{
    unix_time_update();
    if (TCP_connection->status == TCP_CLIENT_DISCONNECTED) {
        return;
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_HTTP_CONNECTING) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = proxy_http_read_connection_response(TCP_connection
      );
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                generate_handshake(TCP_connection);
                TCP_connection->status = TCP_CLIENT_CONNECTING;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_SOCKS5_CONNECTING
      ) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = socks5_read_handshake_response(TCP_connection);
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                proxy_socks5_generate_connection_request(
      TCP_connection);
                TCP_connection->status =
      TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED
      ) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = proxy_socks5_read_connection_response(
      TCP_connection);
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                generate_handshake(TCP_connection);
                TCP_connection->status = TCP_CLIENT_CONNECTING;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_CONNECTING) {
        if (send_pending_data(TCP_connection) == 0) {
            TCP_connection->status = TCP_CLIENT_UNCONFIRMED;
        }
    }
    if (TCP_connection->status == TCP_CLIENT_UNCONFIRMED) {
        uint8_t data[TCP_SERVER_HANDSHAKE_SIZE];
        int len = read_TCP_packet(TCP_connection->sock, data, sizeof(data));
        if (sizeof(data) == len) {
            if (handle_handshake(TCP_connection, data) == 0) {
                TCP_connection->kill_at = ~0;
                TCP_connection->status = TCP_CLIENT_CONFIRMED;
            } else {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_CONFIRMED) {
        do_confirmed_TCP(TCP_connection);
    }
    if (TCP_connection->kill_at <= unix_time()) {
        TCP_connection->status = TCP_CLIENT_DISCONNECTED;
    }
}
void kill_TCP_connection (TCP_Client_Connection * TCP_connection)
Definition at line 958 of file TCP_client.c.
References kill_sock(), TCP_Client_Connection::sock, and wipe_priority_list().
Referenced by kill_tcp_connections(), kill_tcp_relay_connection(), reconnect_tcp_relay_connection(), sleep_tcp_relay_connection(), and START_TEST().
{
    if (TCP_connection == NULL)
        return;
    wipe_priority_list(TCP_connection);
    kill_sock(TCP_connection->sock);
    memset(TCP_connection, 0, sizeof(TCP_Client_Connection));
    free(TCP_connection);
}
TCP_Client_Connection* new_TCP_connection (IP_Port ip_port, const uint8_t * public_key, const uint8_t * self_public_key, const uint8_t * self_secret_key, TCP_Proxy_Info * proxy_info)
Definition at line 611 of file TCP_client.c.
References connect_sock_to(), encrypt_precompute(), IP::family, generate_handshake(), IP_Port::ip, TCP_Proxy_Info::ip_port, TCP_Client_Connection::ip_port, TCP_Client_Connection::kill_at, kill_sock(), networking_at_startup(), proxy_http_generate_connection_request(), TCP_Client_Connection::proxy_info, proxy_socks5_generate_handshake(), TCP_Proxy_Info::proxy_type, TCP_Client_Connection::public_key, TCP_Client_Connection::self_public_key, set_socket_nonblock(), set_socket_nosigpipe(), TCP_Client_Connection::shared_key, sock, TCP_Client_Connection::sock, sock_valid(), TCP_Client_Connection::status, TCP_CLIENT_CONNECTING, TCP_CLIENT_PROXY_HTTP_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_CONNECTING, TCP_CONNECTION_TIMEOUT, TCP_PROXY_HTTP, TCP_PROXY_NONE, TCP_PROXY_SOCKS5, and unix_time().
Referenced by add_tcp_relay_instance(), reconnect_tcp_relay_connection(), START_TEST(), and unsleep_tcp_relay_connection().
{
    if (networking_at_startup() != 0) {
        return NULL;
    }
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return NULL;
    uint8_t family = ip_port.ip.family;
    TCP_Proxy_Info default_proxyinfo;
    if (proxy_info == NULL) {
        default_proxyinfo.proxy_type = TCP_PROXY_NONE;
        proxy_info = &default_proxyinfo;
    }
    if (proxy_info->proxy_type != TCP_PROXY_NONE) {
        family = proxy_info->ip_port.ip.family;
    }
    sock_t sock = socket(family, SOCK_STREAM, IPPROTO_TCP);
    if (!sock_valid(sock)) {
        return NULL;
    }
    if (!set_socket_nosigpipe(sock)) {
        kill_sock(sock);
        return 0;
    }
    if (!(set_socket_nonblock(sock) && connect_sock_to(sock, ip_port,
      proxy_info))) {
        kill_sock(sock);
        return NULL;
    }
    TCP_Client_Connection *temp = calloc(sizeof(
      TCP_Client_Connection), 1);
    if (temp == NULL) {
        kill_sock(sock);
        return NULL;
    }
    temp->sock = sock;
    memcpy(temp->public_key, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(temp->self_public_key, self_public_key, crypto_box_PUBLICKEYBYTES);
    encrypt_precompute(temp->public_key, self_secret_key, temp->
      shared_key);
    temp->ip_port = ip_port;
    temp->proxy_info = *proxy_info;
    switch (proxy_info->proxy_type) {
        case TCP_PROXY_HTTP:
            temp->status = TCP_CLIENT_PROXY_HTTP_CONNECTING;
            proxy_http_generate_connection_request(temp);
            break;
        case TCP_PROXY_SOCKS5:
            temp->status = TCP_CLIENT_PROXY_SOCKS5_CONNECTING;
            proxy_socks5_generate_handshake(temp);
            break;
        case TCP_PROXY_NONE:
            temp->status = TCP_CLIENT_CONNECTING;
            if (generate_handshake(temp) == -1) {
                kill_sock(sock);
                free(temp);
                return NULL;
            }
            break;
    }
    temp->kill_at = unix_time() + TCP_CONNECTION_TIMEOUT;
    return temp;
}
void onion_response_handler (TCP_Client_Connection * con, int(*)(void *object, const uint8_t *data, uint16_t length) onion_callback, void * object)
Definition at line 602 of file TCP_client.c.
References TCP_Client_Connection::onion_callback, and TCP_Client_Connection::onion_callback_object.
Referenced by tcp_relay_set_callbacks().
{
    con->onion_callback = onion_callback;
    con->onion_callback_object = object;
}
void oob_data_handler (TCP_Client_Connection * con, int(*)(void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length) oob_data_callback, void * object)
Definition at line 515 of file TCP_client.c.
References TCP_Client_Connection::oob_data_callback, oob_data_callback(), and TCP_Client_Connection::oob_data_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->oob_data_callback = oob_data_callback;
    con->oob_data_callback_object = object;
}
void routing_data_handler (TCP_Client_Connection * con, int(*)(void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length) data_callback, void * object)
Definition at line 508 of file TCP_client.c.
References TCP_Client_Connection::data_callback, data_callback(), and TCP_Client_Connection::data_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->data_callback = data_callback;
    con->data_callback_object = object;
}
void routing_response_handler (TCP_Client_Connection * con, int(*)(void *object, uint8_t connection_id, const uint8_t *public_key) response_callback, void * object)
Definition at line 434 of file TCP_client.c.
References TCP_Client_Connection::response_callback, response_callback(), and TCP_Client_Connection::response_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->response_callback = response_callback;
    con->response_callback_object = object;
}
void routing_status_handler (TCP_Client_Connection * con, int(*)(void *object, uint32_t number, uint8_t connection_id, uint8_t status) status_callback, void * object)
Definition at line 441 of file TCP_client.c.
References TCP_Client_Connection::status_callback, status_callback(), and TCP_Client_Connection::status_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->status_callback = status_callback;
    con->status_callback_object = object;
}
int send_data (TCP_Client_Connection * con, uint8_t con_id, const uint8_t * data, uint16_t length)
Definition at line 455 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, NUM_RESERVED_PORTS, send_ping_request(), send_ping_response(), TCP_Client_Connection::status, and write_packet_TCP_secure_connection().
Referenced by send_packet_tcp_connection(), and START_TEST().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    if (con->connections[con_id].status != 2)
        return -1;
    if (send_ping_response(con) == 0 || send_ping_request(con) == 0)
        return 0;
    uint8_t packet[1 + length];
    packet[0] = con_id + NUM_RESERVED_PORTS;
    memcpy(packet + 1, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
int send_disconnect_request (TCP_Client_Connection * con, uint8_t con_id)
Definition at line 580 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, NUM_RESERVED_PORTS, TCP_Client_Connection::number, send_disconnect_notification(), and TCP_Client_Connection::status.
Referenced by kill_tcp_connection_to(), and START_TEST().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    con->connections[con_id].status = 0;
    con->connections[con_id].number = 0;
    return send_disconnect_notification(con, con_id +
      NUM_RESERVED_PORTS);
}
int send_onion_request (TCP_Client_Connection * con, const uint8_t * data, uint16_t length)
Definition at line 594 of file TCP_client.c.
References TCP_PACKET_ONION_REQUEST, and write_packet_TCP_secure_connection().
Referenced by tcp_send_onion_request().
{
    uint8_t packet[1 + length];
    packet[0] = TCP_PACKET_ONION_REQUEST;
    memcpy(packet + 1, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
int send_oob_packet (TCP_Client_Connection * con, const uint8_t * public_key, const uint8_t * data, uint16_t length)
Definition at line 476 of file TCP_client.c.
References TCP_MAX_OOB_DATA_LENGTH, TCP_PACKET_OOB_SEND, and write_packet_TCP_secure_connection().
Referenced by send_packet_tcp_connection(), START_TEST(), and tcp_send_oob_packet().
{
    if (length == 0 || length > TCP_MAX_OOB_DATA_LENGTH)
        return -1;
    uint8_t packet[1 + crypto_box_PUBLICKEYBYTES + length];
    packet[0] = TCP_PACKET_OOB_SEND;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
int send_routing_request (TCP_Client_Connection * con, uint8_t * public_key)
Definition at line 426 of file TCP_client.c.
References TCP_PACKET_ROUTING_REQUEST, and write_packet_TCP_secure_connection().
Referenced by send_tcp_relay_routing_request(), and START_TEST().
{
    uint8_t packet[1 + crypto_box_PUBLICKEYBYTES];
    packet[0] = TCP_PACKET_ROUTING_REQUEST;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 1);
}
int set_tcp_connection_number (TCP_Client_Connection * con, uint8_t con_id, uint32_t number)
Definition at line 496 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, TCP_Client_Connection::number, and TCP_Client_Connection::status.
Referenced by response_callback(), and tcp_response_callback().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    if (con->connections[con_id].status == 0)
        return -1;
    con->connections[con_id].number = number;
    return 0;
}