toxav/msi.h File Reference
#include `codec.h`
*
#include `../toxcore/Messenger.h`
*
Data Structures
struct _MSICodecSettings
struct _MSICall
struct _MSISession
Typedefs
typedef uint8_t MSICallIDType [12]
typedef uint8_t MSIReasonStrType [255]
typedef void(* MSICallbackType)(void *agent, int32_t call_idx, void *arg)
typedef struct _MSICodecSettings MSICSettings
typedef struct _MSICall MSICall
typedef struct _MSISession MSISession
Enumerations
enum MSICallType { msi_TypeAudio = 192,
msi_TypeVideo
 }
enum MSICallState {
*
msi_CallInviting,
msi_CallStarting,
msi_CallActive,
msi_CallHold,
*
msi_CallOver
 }
enum MSICallbackID {
*
msi_OnInvite,
msi_OnRinging,
msi_OnStart,
msi_OnCancel,
*
msi_OnReject,
msi_OnEnd,
msi_OnRequestTimeout,
msi_OnPeerTimeout,
*
msi_OnPeerCSChange,
msi_OnSelfCSChange
 }
enum MSIError { msi_ErrorNoCall = -20,
msi_ErrorInvalidState = -21,
msi_ErrorAlreadyInCallWithPeer = -22,
msi_ErrorReachedCallLimit = -23
 }
Functions
MSISession * msi_new (Messenger *messenger, int32_t max_calls)
int msi_kill (MSISession *session)
void msi_register_callback (MSISession *session, MSICallbackType callback, MSICallbackID id, void *userdata)
int msi_invite (MSISession *session, int32_t *call_index, const MSICSettings *csettings, uint32_t rngsec, uint32_t friend_id)
int msi_hangup (MSISession *session, int32_t call_index)
int msi_answer (MSISession *session, int32_t call_index, const MSICSettings *csettings)
int msi_cancel (MSISession *session, int32_t call_index, uint32_t peer, const char *reason)
int msi_reject (MSISession *session, int32_t call_index, const char *reason)
int msi_stopcall (MSISession *session, int32_t call_index)
int msi_change_csettings (MSISession *session, int32_t call_index, const MSICSettings *csettings)
void msi_do (MSISession *session)
Typedef Documentation
typedef struct _MSICall MSICall
The call struct.
typedef void(* MSICallbackType)(void *agent, int32_t call_idx, void *arg)
Definition at line 30 of file msi.h.
typedef uint8_t MSICallIDType[12]
msi.h
Copyright (C) 2013 Tox project All Rights Reserved.
This file is part of Tox.
Tox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Tox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Tox. If not, see http://www.gnu.org/licenses/.
Definition at line 28 of file msi.h.
typedef struct _MSICodecSettings MSICSettings
Encoding settings.
typedef uint8_t MSIReasonStrType[255]
Definition at line 29 of file msi.h.
typedef struct _MSISession MSISession
Control session struct
Enumeration Type Documentation
enum MSICallbackID
Callbacks ids that handle the states
Enumerator
msi_OnInvite
msi_OnRinging
msi_OnStart
msi_OnCancel
msi_OnReject
msi_OnEnd
msi_OnRequestTimeout
msi_OnPeerTimeout
msi_OnPeerCSChange
msi_OnSelfCSChange
Definition at line 74 of file msi.h.
             {
    msi_OnInvite, /* Incoming call */
    msi_OnRinging, /* When peer is ready to accept/reject the call */
    msi_OnStart, /* Call (RTP transmission) started */
    msi_OnCancel, /* The side that initiated call canceled invite */
    msi_OnReject, /* The side that was invited rejected the call */
    msi_OnEnd, /* Call that was active ended */
    msi_OnRequestTimeout, /* When the requested action didn't get response in specified
       time */
    msi_OnPeerTimeout, /* Peer timed out; stop the call */
    msi_OnPeerCSChange, /* Peer requested Csettings change */
    msi_OnSelfCSChange /* Csettings change confirmation */
} MSICallbackID;
enum MSICallState
Call state identifiers.
Enumerator
msi_CallInviting
msi_CallStarting
msi_CallActive
msi_CallHold
msi_CallOver
Definition at line 44 of file msi.h.
             {
    msi_CallInviting, /* when sending call invite */
    msi_CallStarting, /* when getting call invite */
    msi_CallActive,
    msi_CallHold,
    msi_CallOver
} MSICallState;
enum MSICallType
Call type identifier. Also used as rtp callback prefix.
Enumerator
msi_TypeAudio
msi_TypeVideo
Definition at line 35 of file msi.h.
             {
    msi_TypeAudio = 192,
    msi_TypeVideo
} MSICallType;
enum MSIError
Errors
Enumerator
msi_ErrorNoCall
msi_ErrorInvalidState
msi_ErrorAlreadyInCallWithPeer
msi_ErrorReachedCallLimit
Definition at line 90 of file msi.h.
             {
    msi_ErrorNoCall = -20, /* Trying to perform call action while not in a call */
    msi_ErrorInvalidState = -21, /* Trying to perform call action while in invalid
       state*/
    msi_ErrorAlreadyInCallWithPeer = -22, /* Trying to call peer when already
       in a call with peer */
    msi_ErrorReachedCallLimit = -23, /* Cannot handle more calls */
} MSIError;
Function Documentation
int msi_answer (MSISession * session, int32_t call_index, const MSICSettings * csettings)
Answer active call request.
Definition at line 1403 of file msi.c.
References _MSISession::calls, _MSICall::csettings_local, LOGGER_DEBUG, LOGGER_ERROR, _MSISession::max_calls, msi_CallActive, msi_CallStarting, msi_ErrorInvalidState, msi_ErrorNoCall, msi_msg_set_csettings(), msi_new_message(), _MSISession::mutex, _MSICall::peers, send_message(), starting, _MSICall::state, and TypeResponse.
Referenced by toxav_answer().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Answering call: %u", session, call_index);
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        LOGGER_ERROR("Invalid call index!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    if (session->calls[call_index]->state != msi_CallStarting) {
        LOGGER_ERROR("Call is in invalid state!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorInvalidState;
    }
    MSIMessage *msg_starting = msi_new_message (
      TypeResponse, starting);
    session->calls[call_index]->csettings_local = *csettings;
    msi_msg_set_csettings(msg_starting, csettings);
    send_message (session, session->calls[call_index], msg_starting, session->
      calls[call_index]->peers[0]);
    free (msg_starting);
    session->calls[call_index]->state = msi_CallActive;
    pthread_mutex_unlock(session->mutex);
    return 0;
}
int msi_cancel (MSISession * session, int32_t call_index, uint32_t peer, const char * reason)
Cancel request.
Definition at line 1435 of file msi.c.
References _MSISession::calls, cancel, LOGGER_DEBUG, LOGGER_ERROR, _MSISession::max_calls, msi_CallInviting, msi_ErrorInvalidState, msi_ErrorNoCall, msi_msg_set_reason(), msi_new_message(), _MSISession::mutex, send_message(), _MSICall::state, terminate_call(), and TypeRequest.
Referenced by handle_timeout(), msi_kill(), and toxav_cancel().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Canceling call: %u; reason: %s", session, call_index, reason ?
      reason : "Unknown");
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        LOGGER_ERROR("Invalid call index!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    if (session->calls[call_index]->state != msi_CallInviting) {
        LOGGER_ERROR("Call is in invalid state: %u", session->calls[call_index]->
      state);
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorInvalidState;
    }
    MSIMessage *msg_cancel = msi_new_message (
      TypeRequest, cancel);
    /* FIXME */
#if 0
    if (reason && strlen(reason) < sizeof(MSIReasonStrType)) {
        MSIReasonStrType reason_cast;
        memset(reason_cast, '\0', sizeof(MSIReasonStrType));
        memcpy(reason_cast, reason, strlen(reason));
        msi_msg_set_reason(msg_cancel, reason_cast);
    }
#else
    (void)reason;
#endif
    send_message (session, session->calls[call_index], msg_cancel, peer);
    free (msg_cancel);
    terminate_call (session, session->calls[call_index]);
    pthread_mutex_unlock(session->mutex);
    return 0;
}
int msi_change_csettings (MSISession * session, int32_t call_index, const MSICSettings * csettings)
Change codec settings of the current call.
Definition at line 1542 of file msi.c.
References _MSICodecSettings::audio_bitrate, _MSICodecSettings::audio_channels, _MSICodecSettings::audio_frame_duration, _MSICodecSettings::audio_sample_rate, _MSICodecSettings::call_type, _MSISession::calls, _MSICall::csettings_local, invite, LOGGER_DEBUG, LOGGER_ERROR, _MSISession::max_calls, _MSICodecSettings::max_video_height, _MSICodecSettings::max_video_width, msi_CallActive, msi_ErrorInvalidState, msi_ErrorNoCall, msi_msg_set_csettings(), msi_new_message(), _MSISession::mutex, _MSICall::peers, send_message(), _MSICall::state, TypeRequest, and _MSICodecSettings::video_bitrate.
Referenced by toxav_change_settings().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Changing media on call: %d", call_index);
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        LOGGER_ERROR("Invalid call index!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    MSICall *call = session->calls[call_index];
    if (call->state != msi_CallActive) {
        LOGGER_ERROR("Call is not active!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorInvalidState;
    }
    MSICSettings *local = &call->csettings_local;
    if (
        local->call_type == csettings->call_type &&
        local->video_bitrate == csettings->video_bitrate &&
        local->max_video_width == csettings->max_video_width &&
        local->max_video_height == csettings->max_video_height &&
        local->audio_bitrate == csettings->audio_bitrate &&
        local->audio_frame_duration == csettings->
      audio_frame_duration &&
        local->audio_sample_rate == csettings->
      audio_sample_rate &&
        local->audio_channels == csettings->audio_channels) {
        LOGGER_ERROR("Call is already set accordingly!");
        pthread_mutex_unlock(session->mutex);
        return -1;
    }
    *local = *csettings;
    MSIMessage *msg_invite = msi_new_message (
      TypeRequest, invite);
    msi_msg_set_csettings (msg_invite, local);
    send_message (session, call, msg_invite, call->peers[0]);
    free (msg_invite);
    LOGGER_DEBUG("Request for media change sent");
    pthread_mutex_unlock(session->mutex);
    return 0;
}
void msi_do (MSISession * session)
Main msi loop
Definition at line 1593 of file msi.c.
References current_time_monotonic(), _Timer::func, _Timer::id, LOGGER_DEBUG, _MSISession::mutex, _Timer::timeout, _MSISession::timer_handler, timer_release(), and _TimerHandler::timers.
Referenced by toxav_do().
{
    pthread_mutex_lock(session->mutex);
    TimerHandler *timer = session->timer_handler;
    uint64_t time = current_time_monotonic();
    while (timer->timers[0] && timer->timers[0]->timeout < time) {
        LOGGER_DEBUG("Executing timer assigned at: %d", timer->
      timers[0]->timeout);
        int id = timer->timers[0]->id;
        timer->timers[0]->func(timer->timers[0]);
        /* In case function has released timer */
        if (timer->timers[0] && timer->timers[0]->id == id)
            timer_release(timer, id);
    }
    pthread_mutex_unlock(session->mutex);
}
int msi_hangup (MSISession * session, int32_t call_index)
Hangup active call.
Definition at line 1367 of file msi.c.
References _MSISession::calls, end, handle_timeout(), LOGGER_DEBUG, LOGGER_ERROR, m_deftout, _MSISession::max_calls, msi_CallActive, msi_CallOver, msi_ErrorInvalidState, msi_ErrorNoCall, msi_new_message(), _MSISession::mutex, _MSICall::peer_count, _MSICall::peers, _MSICall::request_timer_id, send_message(), _MSICall::state, timer_alloc(), and TypeRequest.
Referenced by toxav_hangup().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Hanging up call: %u", session, call_index);
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        LOGGER_ERROR("Invalid call index!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    if (session->calls[call_index]->state != msi_CallActive) {
        LOGGER_ERROR("Call is not active!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorInvalidState;
    }
    MSIMessage *msg_end = msi_new_message (TypeRequest,
      end);
    /* hangup for each peer */
    int it = 0;
    for (; it < session->calls[call_index]->peer_count; it ++)
        send_message (session, session->calls[call_index], msg_end, session->
      calls[call_index]->peers[it]);
    session->calls[call_index]->state = msi_CallOver;
    free (msg_end);
    session->calls[call_index]->request_timer_id =
        timer_alloc (session, handle_timeout, call_index,
      m_deftout);
    pthread_mutex_unlock(session->mutex);
    return 0;
}
int msi_invite (MSISession * session, int32_t * call_index, const MSICSettings * csettings, uint32_t rngsec, uint32_t friend_id)
Send invite request to friend_id.
Definition at line 1313 of file msi.c.
References add_peer(), _MSICall::call_idx, _MSISession::calls, _MSICall::csettings_local, handle_timeout(), i, _MSICall::id, init_call(), invite, LOGGER_DEBUG, LOGGER_ERROR, m_deftout, _MSISession::max_calls, msi_CallInviting, msi_ErrorAlreadyInCallWithPeer, msi_ErrorReachedCallLimit, msi_msg_set_csettings(), msi_new_message(), _MSISession::mutex, _MSICall::peers, _MSICall::request_timer_id, send_message(), _MSICall::state, t_randomstr(), timer_alloc(), and TypeRequest.
Referenced by toxav_call().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Inviting friend: %u", session,
      friend_id);
    int i = 0;
    for (; i < session->max_calls; i ++)
        if (session->calls[i] && session->calls[i]->peers[0] ==
      friend_id) {
            LOGGER_ERROR("Already in a call with friend %d",
      friend_id);
            pthread_mutex_unlock(session->mutex);
            return msi_ErrorAlreadyInCallWithPeer;
        }
    MSICall *call = init_call (session, 1, rngsec); /* Just one peer for now */
    if (!call) {
        pthread_mutex_unlock(session->mutex);
        LOGGER_ERROR("Cannot handle more calls");
        return msi_ErrorReachedCallLimit;
    }
    *call_index = call->call_idx;
    t_randomstr (call->id, sizeof(call->id));
    add_peer (call, friend_id);
    call->csettings_local = *csettings;
    MSIMessage *msg_invite = msi_new_message (
      TypeRequest, invite);
    msi_msg_set_csettings(msg_invite, csettings);
    send_message (session, call, msg_invite, friend_id);
    free(msg_invite);
    call->state = msi_CallInviting;
    call->request_timer_id = timer_alloc (session,
      handle_timeout, call->call_idx, m_deftout);
    LOGGER_DEBUG("Invite sent");
    pthread_mutex_unlock(session->mutex);
    return 0;
}
int msi_kill (MSISession * session)
Terminate control session.
Definition at line 1273 of file msi.c.
References _MSISession::calls, LOGGER_DEBUG, LOGGER_ERROR, m_callback_msi_packet(), _MSISession::max_calls, _MSISession::messenger_handle, msi_CallInviting, msi_cancel(), msi_stopcall(), _MSISession::mutex, _MSICall::peers, _MSICall::state, and _MSISession::timer_handler.
Referenced by toxav_kill(), and toxav_new().
{
    if (session == NULL) {
        LOGGER_ERROR("Tried to terminate non-existing session");
        return -1;
    }
    m_callback_msi_packet((struct Messenger *) session->
      messenger_handle, NULL, NULL);
    pthread_mutex_lock(session->mutex);
    /* Cancel active calls */
    int32_t idx = 0;
    for (; idx < session->max_calls; idx ++) if (session->calls[idx]) {
            /* Cancel all? */
            uint16_t _it = 0;
            /*for (; _it < session->calls[idx]->peer_count; _it++)
                * FIXME: will not work on multiple peers, must cancel call for all peers
                */
            MSICallState state = session->calls[idx]->state;
            if (state == msi_CallInviting) {
                msi_cancel(session, idx, session->calls[idx]->
      peers [_it], "MSI session terminated!");
            } else {
                msi_stopcall(session, idx);
            }
        }
    free(((TimerHandler *)session->timer_handler)->timers);
    free(session->timer_handler);
    free (session->calls);
    pthread_mutex_unlock(session->mutex);
    pthread_mutex_destroy(session->mutex);
    LOGGER_DEBUG("Terminated session: %p", session);
    free (session);
    return 0;
}
MSISession* msi_new (Messenger * messenger, int32_t max_calls)
Start the control session.
Definition at line 1202 of file msi.c.
References _MSISession::agent_handler, _MSISession::call_timeout, _MSISession::calls, create_recursive_mutex(), error, _MSISession::frequ, handle_remote_connection_change(), LOGGER_DEBUG, LOGGER_ERROR, LOGGER_WARNING, m_callback_connectionstatus_internal_av(), m_callback_msi_packet(), _MSISession::max_calls, _MSISession::messenger_handle, msi_handle_packet(), _MSISession::mutex, and _MSISession::timer_handler.
Referenced by toxav_new().
{
    if (messenger == NULL) {
        LOGGER_ERROR("Could not init session on empty messenger!");
        return NULL;
    }
    if (!max_calls) {
        LOGGER_WARNING("Invalid max call treshold!");
        return NULL;
    }
    MSISession *retu = calloc (sizeof (MSISession), 1);
    if (retu == NULL) {
        LOGGER_ERROR("Allocation failed! Program might misbehave!");
        return NULL;
    }
    if (!(retu->calls = calloc(sizeof (MSICall *), max_calls))) {
        LOGGER_ERROR("Allocation failed! Program might misbehave!");
        goto error;
    }
    retu->timer_handler = calloc(1, sizeof(TimerHandler));
    if (retu->timer_handler == NULL) {
        LOGGER_ERROR("Allocation failed! Program might misbehave!");
        goto error;
    }
    /* Allocate space for timers */
    ((TimerHandler *)retu->timer_handler)->max_capacity = max_calls * 10;
    if (!(((TimerHandler *)retu->timer_handler)->timers = calloc(max_calls * 10,
      sizeof(Timer *)))) {
        LOGGER_ERROR("Allocation failed! Program might misbehave!");
        goto error;
    }
    if (create_recursive_mutex(retu->mutex) != 0) {
        LOGGER_ERROR("Failed to init mutex! Program might misbehave");
        goto error;
    }
    retu->messenger_handle = messenger;
    retu->agent_handler = NULL;
    retu->max_calls = max_calls;
    retu->frequ = 10000; /* default value? */
    retu->call_timeout = 30000; /* default value? */
    m_callback_msi_packet(messenger, msi_handle_packet, retu);
    /* This is called when remote terminates session */
    m_callback_connectionstatus_internal_av(messenger,
      handle_remote_connection_change, retu);
    LOGGER_DEBUG("New msi session: %p max calls: %u", retu, max_calls);
    return retu;
error:
    if (retu->timer_handler) {
        free(((TimerHandler *)retu->timer_handler)->timers);
        free(retu->timer_handler);
    }
    free(retu->calls);
    free(retu);
    return NULL;
}
void msi_register_callback (MSISession * session, MSICallbackType callback, MSICallbackID id, void * userdata)
Callback setter.
Definition at line 1195 of file msi.c.
Referenced by toxav_register_callstate_callback().
{
    session->callbacks[id].first = callback;
    session->callbacks[id].second = userdata;
}
int msi_reject (MSISession * session, int32_t call_index, const char * reason)
Reject incoming call.
Definition at line 1478 of file msi.c.
References _MSISession::calls, handle_timeout(), LOGGER_DEBUG, LOGGER_ERROR, m_deftout, _MSISession::max_calls, msi_CallOver, msi_CallStarting, msi_ErrorInvalidState, msi_ErrorNoCall, msi_msg_set_reason(), msi_new_message(), _MSISession::mutex, _MSICall::peer_count, _MSICall::peers, reject, _MSICall::request_timer_id, send_message(), _MSICall::state, timer_alloc(), and TypeRequest.
Referenced by toxav_reject().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Rejecting call: %u; reason: %s", session, call_index, reason ?
      reason : "Unknown");
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        LOGGER_ERROR("Invalid call index!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    if (session->calls[call_index]->state != msi_CallStarting) {
        LOGGER_ERROR("Call is in invalid state!");
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorInvalidState;
    }
    MSIMessage *msg_reject = msi_new_message (
      TypeRequest, reject);
    /* FIXME */
#if 0
    if (reason && strlen(reason) < sizeof(MSIReasonStrType)) {
        MSIReasonStrType reason_cast;
        memset(reason_cast, '\0', sizeof(MSIReasonStrType));
        memcpy(reason_cast, reason, strlen(reason));
        msi_msg_set_reason(msg_reject, reason_cast);
    }
#else
    (void)reason;
#endif
    send_message (session, session->calls[call_index], msg_reject,
                   session->calls[call_index]->peers[session->calls[call_index]->
      peer_count - 1]);
    free (msg_reject);
    session->calls[call_index]->state = msi_CallOver;
    session->calls[call_index]->request_timer_id =
        timer_alloc (session, handle_timeout, call_index,
      m_deftout);
    pthread_mutex_unlock(session->mutex);
    return 0;
}
int msi_stopcall (MSISession * session, int32_t call_index)
Terminate the call.
Definition at line 1524 of file msi.c.
References _MSISession::calls, LOGGER_DEBUG, _MSISession::max_calls, msi_ErrorNoCall, _MSISession::mutex, and terminate_call().
Referenced by msi_kill(), and toxav_stop_call().
{
    pthread_mutex_lock(session->mutex);
    LOGGER_DEBUG("Session: %p Stopping call index: %u", session, call_index);
    if (call_index < 0 || call_index >= session->max_calls || !session->
      calls[call_index]) {
        pthread_mutex_unlock(session->mutex);
        return msi_ErrorNoCall;
    }
    /* just terminate it */
    terminate_call (session, session->calls[call_index]);
    pthread_mutex_unlock(session->mutex);
    return 0;
}