toxcore/net_crypto.c File Reference
#include `net_crypto.h`
*
#include `util.h`
*
#include `math.h`
*
#include `logger.h`
*
Macros
#define COOKIE_TIMEOUT 15
#define COOKIE_DATA_LENGTH (crypto_box_PUBLICKEYBYTES * 2)
#define COOKIE_CONTENTS_LENGTH (sizeof(uint64_t) + COOKIE_DATA_LENGTH)
#define COOKIE_LENGTH (crypto_box_NONCEBYTES + COOKIE_CONTENTS_LENGTH + crypto_box_MACBYTES)
#define COOKIE_REQUEST_PLAIN_LENGTH (COOKIE_DATA_LENGTH + sizeof(uint64_t))
#define COOKIE_REQUEST_LENGTH (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + COOKIE_REQUEST_PLAIN_LENGTH + crypto_box_MACBYTES)
#define COOKIE_RESPONSE_LENGTH (1 + crypto_box_NONCEBYTES + COOKIE_LENGTH + sizeof(uint64_t) + crypto_box_MACBYTES)
#define HANDSHAKE_PACKET_LENGTH (1 + COOKIE_LENGTH + crypto_box_NONCEBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_hash_sha512_BYTES + COOKIE_LENGTH + crypto_box_MACBYTES)
#define MAX_DATA_DATA_PACKET_SIZE (MAX_CRYPTO_PACKET_SIZE - (1 + sizeof(uint16_t) + crypto_box_MACBYTES))
#define DATA_NUM_THRESHOLD 21845
#define CRYPTO_MIN_PACKET_SIZE (1 + sizeof(uint16_t) + crypto_box_MACBYTES)
#define PACKET_COUNTER_AVERAGE_INTERVAL 50
#define REQUEST_PACKETS_COMPARE_CONSTANT (0.125 * 100.0)
#define PACKET_RESEND_MULTIPLIER 3.5
#define CONGESTION_EVENT_TIMEOUT 2000
Functions
static uint8_t crypt_connection_id_not_valid (const Net_Crypto *c, int crypt_connection_id)
static int create_cookie_request (const Net_Crypto *c, uint8_t *packet, uint8_t *dht_public_key, uint64_t number, uint8_t *shared_key)
static int create_cookie (uint8_t *cookie, const uint8_t *bytes, const uint8_t *encryption_key)
static int open_cookie (uint8_t *bytes, const uint8_t *cookie, const uint8_t *encryption_key)
static int create_cookie_response (const Net_Crypto *c, uint8_t *packet, const uint8_t *request_plain, const uint8_t *shared_key, const uint8_t *dht_public_key)
static int handle_cookie_request (const Net_Crypto *c, uint8_t *request_plain, uint8_t *shared_key, uint8_t *dht_public_key, const uint8_t *packet, uint16_t length)
static int udp_handle_cookie_request (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int tcp_handle_cookie_request (Net_Crypto *c, int connections_number, const uint8_t *packet, uint16_t length)
static int tcp_oob_handle_cookie_request (const Net_Crypto *c, unsigned int tcp_connections_number, const uint8_t *dht_public_key, const uint8_t *packet, uint16_t length)
static int handle_cookie_response (uint8_t *cookie, uint64_t *number, const uint8_t *packet, uint16_t length, const uint8_t *shared_key)
static int create_crypto_handshake (const Net_Crypto *c, uint8_t *packet, const uint8_t *cookie, const uint8_t *nonce, const uint8_t *session_pk, const uint8_t *peer_real_pk, const uint8_t *peer_dht_pubkey)
static int handle_crypto_handshake (const Net_Crypto *c, uint8_t *nonce, uint8_t *session_pk, uint8_t *peer_real_pk, uint8_t *dht_public_key, uint8_t *cookie, const uint8_t *packet, uint16_t length, const uint8_t *expected_real_pk)
static Crypto_Connection * get_crypto_connection (const Net_Crypto *c, int crypt_connection_id)
static int send_packet_to (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length)
static uint32_t num_packets_array (const Packets_Array *array)
static int add_data_to_buffer (Packets_Array *array, uint32_t number, const Packet_Data *data)
static int get_data_pointer (const Packets_Array *array, Packet_Data **data, uint32_t number)
static int64_t add_data_end_of_buffer (Packets_Array *array, const Packet_Data *data)
static int64_t read_data_beg_buffer (Packets_Array *array, Packet_Data *data)
static int clear_buffer_until (Packets_Array *array, uint32_t number)
static int clear_buffer (Packets_Array *array)
static int set_buffer_end (Packets_Array *array, uint32_t number)
static int generate_request_packet (uint8_t *data, uint16_t length, const Packets_Array *recv_array)
static int handle_request_packet (Packets_Array *send_array, const uint8_t *data, uint16_t length, uint64_t *latest_send_time, uint64_t rtt_time)
static int send_data_packet (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length)
static int send_data_packet_helper (Net_Crypto *c, int crypt_connection_id, uint32_t buffer_start, uint32_t num, const uint8_t *data, uint16_t length)
static int reset_max_speed_reached (Net_Crypto *c, int crypt_connection_id)
static int64_t send_lossless_packet (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length, uint8_t congestion_control)
static uint16_t get_nonce_uint16 (const uint8_t *nonce)
static int handle_data_packet (const Net_Crypto *c, int crypt_connection_id, uint8_t *data, const uint8_t *packet, uint16_t length)
static int send_request_packet (Net_Crypto *c, int crypt_connection_id)
static int send_requested_packets (Net_Crypto *c, int crypt_connection_id, uint32_t max_num)
static int new_temp_packet (const Net_Crypto *c, int crypt_connection_id, const uint8_t *packet, uint16_t length)
static int clear_temp_packet (const Net_Crypto *c, int crypt_connection_id)
static int send_temp_packet (Net_Crypto *c, int crypt_connection_id)
static int create_send_handshake (Net_Crypto *c, int crypt_connection_id, const uint8_t *cookie, const uint8_t *dht_public_key)
static int send_kill_packet (Net_Crypto *c, int crypt_connection_id)
static void connection_kill (Net_Crypto *c, int crypt_connection_id)
static int handle_data_packet_helper (Net_Crypto *c, int crypt_connection_id, const uint8_t *packet, uint16_t length)
static int handle_packet_connection (Net_Crypto *c, int crypt_connection_id, const uint8_t *packet, uint16_t length)
static int realloc_cryptoconnection (Net_Crypto *c, uint32_t num)
static int create_crypto_connection (Net_Crypto *c)
static int wipe_crypto_connection (Net_Crypto *c, int crypt_connection_id)
static int getcryptconnection_id (const Net_Crypto *c, const uint8_t *public_key)
static int crypto_connection_add_source (Net_Crypto *c, int crypt_connection_id, IP_Port source)
void new_connection_handler (Net_Crypto *c, int(*new_connection_callback)(void *object, New_Connection *n_c), void *object)
static int handle_new_connection_handshake (Net_Crypto *c, IP_Port source, const uint8_t *data, uint16_t length)
int accept_crypto_connection (Net_Crypto *c, New_Connection *n_c)
int new_crypto_connection (Net_Crypto *c, const uint8_t *real_public_key, const uint8_t *dht_public_key)
int set_direct_ip_port (Net_Crypto *c, int crypt_connection_id, IP_Port ip_port, _Bool connected)
static int tcp_data_callback (void *object, int id, const uint8_t *data, uint16_t length)
static int tcp_oob_callback (void *object, const uint8_t *public_key, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length)
int add_tcp_relay_peer (Net_Crypto *c, int crypt_connection_id, IP_Port ip_port, const uint8_t *public_key)
int add_tcp_relay (Net_Crypto *c, IP_Port ip_port, const uint8_t *public_key)
int get_random_tcp_con_number (Net_Crypto *c)
int send_tcp_onion_request (Net_Crypto *c, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length)
unsigned int copy_connected_tcp_relays (Net_Crypto *c, Node_format *tcp_relays, uint16_t num)
static void do_tcp (Net_Crypto *c)
int connection_status_handler (const Net_Crypto *c, int crypt_connection_id, int(*connection_status_callback)(void *object, int id, uint8_t status), void *object, int id)
int connection_data_handler (const Net_Crypto *c, int crypt_connection_id, int(*connection_data_callback)(void *object, int id, uint8_t *data, uint16_t length), void *object, int id)
int connection_lossy_data_handler (Net_Crypto *c, int crypt_connection_id, int(*connection_lossy_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object, int id)
int nc_dht_pk_callback (Net_Crypto *c, int crypt_connection_id, void(*function)(void *data, int32_t number, const uint8_t *dht_public_key), void *object, uint32_t number)
static int crypto_id_ip_port (const Net_Crypto *c, IP_Port ip_port)
static int udp_handle_packet (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static void send_crypto_packets (Net_Crypto *c)
_Bool max_speed_reached (Net_Crypto *c, int crypt_connection_id)
uint32_t crypto_num_free_sendqueue_slots (const Net_Crypto *c, int crypt_connection_id)
int64_t write_cryptpacket (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length, uint8_t congestion_control)
int cryptpacket_received (Net_Crypto *c, int crypt_connection_id, uint32_t packet_number)
int send_lossy_cryptpacket (Net_Crypto *c, int crypt_connection_id, const uint8_t *data, uint16_t length)
int crypto_kill (Net_Crypto *c, int crypt_connection_id)
unsigned int crypto_connection_status (const Net_Crypto *c, int crypt_connection_id, _Bool *direct_connected, unsigned int *online_tcp_relays)
void new_keys (Net_Crypto *c)
void save_keys (const Net_Crypto *c, uint8_t *keys)
void load_secret_key (Net_Crypto *c, const uint8_t *sk)
Net_Crypto * new_net_crypto (DHT *dht, TCP_Proxy_Info *proxy_info)
static void kill_timedout (Net_Crypto *c)
uint32_t crypto_run_interval (const Net_Crypto *c)
void do_net_crypto (Net_Crypto *c)
void kill_net_crypto (Net_Crypto *c)
Macro Definition Documentation
#define CONGESTION_EVENT_TIMEOUT 2000
Definition at line 2040 of file net_crypto.c.
Referenced by send_crypto_packets().
#define COOKIE_CONTENTS_LENGTH (sizeof(uint64_t) + COOKIE_DATA_LENGTH)
Definition at line 52 of file net_crypto.c.
Referenced by create_cookie(), and open_cookie().
#define COOKIE_DATA_LENGTH (crypto_box_PUBLICKEYBYTES * 2)
Definition at line 51 of file net_crypto.c.
Referenced by create_cookie(), create_cookie_response(), create_crypto_handshake(), handle_crypto_handshake(), and open_cookie().
#define COOKIE_LENGTH (crypto_box_NONCEBYTES + COOKIE_CONTENTS_LENGTH + crypto_box_MACBYTES)
Definition at line 53 of file net_crypto.c.
Referenced by accept_crypto_connection(), create_cookie(), create_cookie_response(), create_crypto_handshake(), handle_cookie_response(), handle_crypto_handshake(), handle_new_connection_handshake(), handle_packet_connection(), and open_cookie().
#define COOKIE_REQUEST_LENGTH (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + COOKIE_REQUEST_PLAIN_LENGTH + crypto_box_MACBYTES)
Definition at line 56 of file net_crypto.c.
Referenced by handle_cookie_request(), and new_crypto_connection().
#define COOKIE_REQUEST_PLAIN_LENGTH (COOKIE_DATA_LENGTH + sizeof(uint64_t))
Definition at line 55 of file net_crypto.c.
Referenced by create_cookie_request(), handle_cookie_request(), tcp_handle_cookie_request(), tcp_oob_handle_cookie_request(), and udp_handle_cookie_request().
#define COOKIE_RESPONSE_LENGTH (1 + crypto_box_NONCEBYTES + COOKIE_LENGTH + sizeof(uint64_t) + crypto_box_MACBYTES)
Definition at line 57 of file net_crypto.c.
Referenced by create_cookie_response(), handle_cookie_response(), tcp_handle_cookie_request(), tcp_oob_handle_cookie_request(), and udp_handle_cookie_request().
#define COOKIE_TIMEOUT 15
Definition at line 50 of file net_crypto.c.
Referenced by open_cookie().
#define CRYPTO_MIN_PACKET_SIZE (1 + sizeof(uint16_t) + crypto_box_MACBYTES)
Definition at line 1985 of file net_crypto.c.
#define DATA_NUM_THRESHOLD 21845
Definition at line 888 of file net_crypto.c.
Referenced by handle_data_packet().
#define HANDSHAKE_PACKET_LENGTH (1 + COOKIE_LENGTH + crypto_box_NONCEBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_hash_sha512_BYTES + COOKIE_LENGTH + crypto_box_MACBYTES)
Definition at line 285 of file net_crypto.c.
Referenced by create_crypto_handshake(), create_send_handshake(), and handle_crypto_handshake().
#define MAX_DATA_DATA_PACKET_SIZE (MAX_CRYPTO_PACKET_SIZE - (1 + sizeof(uint16_t) + crypto_box_MACBYTES))
END: Array Related functions
Definition at line 734 of file net_crypto.c.
Referenced by handle_data_packet_helper().
#define PACKET_COUNTER_AVERAGE_INTERVAL 50
Definition at line 2029 of file net_crypto.c.
Referenced by send_crypto_packets().
#define PACKET_RESEND_MULTIPLIER 3.5
Definition at line 2037 of file net_crypto.c.
Referenced by send_crypto_packets().
#define REQUEST_PACKETS_COMPARE_CONSTANT (0.125 * 100.0)
Definition at line 2034 of file net_crypto.c.
Referenced by send_crypto_packets().
Function Documentation
int accept_crypto_connection (Net_Crypto * c, New_Connection * n_c)
Definition at line 1570 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, New_Connection::cookie, COOKIE_LENGTH, New_Connection::cookie_length, create_crypto_connection(), create_send_handshake(), CRYPTO_CONN_NO_CONNECTION, CRYPTO_CONN_NOT_CONFIRMED, crypto_connection_add_source(), Net_Crypto::crypto_connections, CRYPTO_MIN_QUEUE_LENGTH, CRYPTO_PACKET_MIN_RATE, DEFAULT_PING_CONNECTION, Crypto_Connection::dht_public_key, New_Connection::dht_public_key, encrypt_precompute(), getcryptconnection_id(), kill_tcp_connection_to(), new_tcp_connection_to(), Crypto_Connection::packet_send_rate, Crypto_Connection::packets_left, Crypto_Connection::peersessionpublic_key, New_Connection::peersessionpublic_key, Crypto_Connection::public_key, New_Connection::public_key, random_nonce(), Crypto_Connection::recv_nonce, New_Connection::recv_nonce, Crypto_Connection::rtt_time, Crypto_Connection::sent_nonce, Crypto_Connection::sessionpublic_key, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, New_Connection::source, Crypto_Connection::status, Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by handle_new_connections().
{
    if (getcryptconnection_id(c, n_c->public_key) != -1)
        return -1;
    int crypt_connection_id = create_crypto_connection(c);
    if (crypt_connection_id == -1)
        return -1;
    Crypto_Connection *conn = &c->crypto_connections[crypt_connection_id
      ];
    if (n_c->cookie_length != COOKIE_LENGTH)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int connection_number_tcp = new_tcp_connection_to(c->
      tcp_c, n_c->dht_public_key, crypt_connection_id);
    pthread_mutex_unlock(&c->tcp_mutex);
    if (connection_number_tcp == -1)
        return -1;
    conn->connection_number_tcp = connection_number_tcp;
    memcpy(conn->public_key, n_c->public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(conn->recv_nonce, n_c->recv_nonce, crypto_box_NONCEBYTES);
    memcpy(conn->peersessionpublic_key, n_c->
      peersessionpublic_key, crypto_box_PUBLICKEYBYTES);
    random_nonce(conn->sent_nonce);
    crypto_box_keypair(conn->sessionpublic_key, conn->
      sessionsecret_key);
    encrypt_precompute(conn->peersessionpublic_key, conn->
      sessionsecret_key, conn->shared_key);
    conn->status = CRYPTO_CONN_NOT_CONFIRMED;
    if (create_send_handshake(c, crypt_connection_id, n_c->
      cookie, n_c->dht_public_key) != 0) {
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        conn->status = CRYPTO_CONN_NO_CONNECTION;
        return -1;
    }
    memcpy(conn->dht_public_key, n_c->dht_public_key, crypto_box_PUBLICKEYBYTES
      );
    conn->packet_send_rate = CRYPTO_PACKET_MIN_RATE;
    conn->packets_left = CRYPTO_MIN_QUEUE_LENGTH;
    conn->rtt_time = DEFAULT_PING_CONNECTION;
    crypto_connection_add_source(c, crypt_connection_id, n_c->
      source);
    return crypt_connection_id;
}
static int64_t add_data_end_of_buffer (Packets_Array * array, const Packet_Data * data) [static]
Definition at line 505 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, CRYPTO_PACKET_BUFFER_SIZE, and num_packets_array().
Referenced by send_lossless_packet().
{
    if (num_packets_array(array) >= CRYPTO_PACKET_BUFFER_SIZE)
        return -1;
    Packet_Data *new_d = malloc(sizeof(Packet_Data));
    if (new_d == NULL)
        return -1;
    memcpy(new_d, data, sizeof(Packet_Data));
    uint32_t id = array->buffer_end;
    array->buffer[id % CRYPTO_PACKET_BUFFER_SIZE] = new_d;
    ++array->buffer_end;
    return id;
}
static int add_data_to_buffer (Packets_Array * array, uint32_t number, const Packet_Data * data) [static]
Definition at line 454 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, and num.
Referenced by handle_data_packet_helper().
{
    if (number - array->buffer_start > CRYPTO_PACKET_BUFFER_SIZE)
        return -1;
    uint32_t num = number % CRYPTO_PACKET_BUFFER_SIZE;
    if (array->buffer[num])
        return -1;
    Packet_Data *new_d = malloc(sizeof(Packet_Data));
    if (new_d == NULL)
        return -1;
    memcpy(new_d, data, sizeof(Packet_Data));
    array->buffer[num] = new_d;
    if ((number - array->buffer_start) >= (array->buffer_end - array->
      buffer_start))
        array->buffer_end = number + 1;
    return 0;
}
int add_tcp_relay (Net_Crypto * c, IP_Port ip_port, const uint8_t * public_key)
Definition at line 1794 of file net_crypto.c.
References add_tcp_relay_global(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by do_messenger(), tcp_relay_node_callback(), and tox_add_tcp_relay().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = add_tcp_relay_global(c->tcp_c, ip_port,
      public_key);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
int add_tcp_relay_peer (Net_Crypto * c, int crypt_connection_id, IP_Port ip_port, const uint8_t * public_key)
Definition at line 1776 of file net_crypto.c.
References add_tcp_relay_connection(), Crypto_Connection::connection_number_tcp, get_crypto_connection(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by connect_to_saved_tcp_relays(), and friend_add_tcp_relay().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = add_tcp_relay_connection(c->tcp_c, conn->
      connection_number_tcp, ip_port, public_key);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
static int clear_buffer (Packets_Array * array) [static]
Definition at line 572 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, i, and num.
Referenced by crypto_kill().
{
    uint32_t i;
    for (i = array->buffer_start; i != array->buffer_end; ++i) {
        uint32_t num = i % CRYPTO_PACKET_BUFFER_SIZE;
        if (array->buffer[num]) {
            free(array->buffer[num]);
            array->buffer[num] = NULL;
        }
    }
    array->buffer_start = i;
    return 0;
}
static int clear_buffer_until (Packets_Array * array, uint32_t number) [static]
Definition at line 550 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, i, and num.
Referenced by handle_data_packet_helper().
{
    uint32_t num_spots = array->buffer_end - array->buffer_start;
    if (array->buffer_end - number >= num_spots || number - array->
      buffer_start > num_spots)
        return -1;
    uint32_t i;
    for (i = array->buffer_start; i != number; ++i) {
        uint32_t num = i % CRYPTO_PACKET_BUFFER_SIZE;
        if (array->buffer[num]) {
            free(array->buffer[num]);
            array->buffer[num] = NULL;
        }
    }
    array->buffer_start = i;
    return 0;
}
static int clear_temp_packet (const Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 1034 of file net_crypto.c.
References get_crypto_connection(), Crypto_Connection::temp_packet, Crypto_Connection::temp_packet_length, Crypto_Connection::temp_packet_num_sent, and Crypto_Connection::temp_packet_sent_time.
Referenced by crypto_kill(), and handle_data_packet_helper().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (conn->temp_packet)
        free(conn->temp_packet);
    conn->temp_packet = 0;
    conn->temp_packet_length = 0;
    conn->temp_packet_sent_time = 0;
    conn->temp_packet_num_sent = 0;
    return 0;
}
int connection_data_handler (const Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, uint8_t *data, uint16_t length) connection_data_callback, void * object, int id)
Definition at line 1914 of file net_crypto.c.
References Crypto_Connection::connection_data_callback, Crypto_Connection::connection_data_callback_id, Crypto_Connection::connection_data_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_data_callback = connection_data_callback;
    conn->connection_data_callback_object = object;
    conn->connection_data_callback_id = id;
    return 0;
}
static void connection_kill (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 1119 of file net_crypto.c.
References Crypto_Connection::connection_status_callback, Crypto_Connection::connection_status_callback_id, Crypto_Connection::connection_status_callback_object, crypto_kill(), and get_crypto_connection().
Referenced by handle_data_packet_helper(), handle_new_connection_handshake(), and kill_timedout().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return;
    if (conn->connection_status_callback) {
        conn->connection_status_callback(conn->
      connection_status_callback_object, conn->
      connection_status_callback_id, 0);
    }
    crypto_kill(c, crypt_connection_id);
}
int connection_lossy_data_handler (Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, const uint8_t *data, uint16_t length) connection_lossy_data_callback, void * object, int id)
Definition at line 1936 of file net_crypto.c.
References Crypto_Connection::connection_lossy_data_callback, Crypto_Connection::connection_lossy_data_callback_id, Crypto_Connection::connection_lossy_data_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_lossy_data_callback = connection_lossy_data_callback;
    conn->connection_lossy_data_callback_object = object;
    conn->connection_lossy_data_callback_id =
      id;
    return 0;
}
int connection_status_handler (const Net_Crypto * c, int crypt_connection_id, int(*)(void *object, int id, uint8_t status) connection_status_callback, void * object, int id)
Definition at line 1892 of file net_crypto.c.
References Crypto_Connection::connection_status_callback, Crypto_Connection::connection_status_callback_id, Crypto_Connection::connection_status_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->connection_status_callback = connection_status_callback;
    conn->connection_status_callback_object = object;
    conn->connection_status_callback_id = id;
    return 0;
}
unsigned int copy_connected_tcp_relays (Net_Crypto * c, Node_format * tcp_relays, uint16_t num)
Definition at line 1839 of file net_crypto.c.
References Net_Crypto::tcp_c, tcp_copy_connected_relays(), and Net_Crypto::tcp_mutex.
Referenced by messenger_save(), populate_path_nodes_tcp(), send_dhtpk_announce(), and send_relays().
{
    if (num == 0)
        return 0;
    pthread_mutex_lock(&c->tcp_mutex);
    unsigned int ret = tcp_copy_connected_relays(c->
      tcp_c, tcp_relays, num);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
static int create_cookie (uint8_t * cookie, const uint8_t * bytes, const uint8_t * encryption_key) [static]
Definition at line 97 of file net_crypto.c.
References COOKIE_CONTENTS_LENGTH, COOKIE_DATA_LENGTH, COOKIE_LENGTH, encrypt_data_symmetric(), new_nonce(), and unix_time().
Referenced by create_cookie_response(), and create_crypto_handshake().
{
    uint8_t contents[COOKIE_CONTENTS_LENGTH];
    uint64_t temp_time = unix_time();
    memcpy(contents, &temp_time, sizeof(temp_time));
    memcpy(contents + sizeof(temp_time), bytes, COOKIE_DATA_LENGTH);
    new_nonce(cookie);
    int len = encrypt_data_symmetric(encryption_key, cookie, contents, sizeof(
      contents), cookie + crypto_box_NONCEBYTES);
    if (len != COOKIE_LENGTH - crypto_box_NONCEBYTES)
        return -1;
    return 0;
}
static int create_cookie_request (const Net_Crypto * c, uint8_t * packet, uint8_t * dht_public_key, uint64_t number, uint8_t * shared_key) [static]
Definition at line 67 of file net_crypto.c.
References COOKIE_REQUEST_PLAIN_LENGTH, Net_Crypto::dht, DHT_get_shared_key_sent(), encrypt_data_symmetric(), NET_PACKET_COOKIE_REQUEST, new_nonce(), nonce, Net_Crypto::self_public_key, and DHT::self_public_key.
Referenced by new_crypto_connection().
{
    uint8_t plain[COOKIE_REQUEST_PLAIN_LENGTH];
    uint8_t padding[crypto_box_PUBLICKEYBYTES] = {0};
    memcpy(plain, c->self_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(plain + crypto_box_PUBLICKEYBYTES, padding, crypto_box_PUBLICKEYBYTES);
    memcpy(plain + (crypto_box_PUBLICKEYBYTES * 2), &number, sizeof(uint64_t));
    DHT_get_shared_key_sent(c->dht, shared_key, dht_public_key);
    uint8_t nonce[crypto_box_NONCEBYTES];
    new_nonce(nonce);
    packet[0] = NET_PACKET_COOKIE_REQUEST;
    memcpy(packet + 1, c->dht->self_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
    int len = encrypt_data_symmetric(shared_key, nonce, plain, sizeof(plain),
                                     packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    if (len != COOKIE_REQUEST_PLAIN_LENGTH + crypto_box_MACBYTES)
        return -1;
    return (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + len);
}
static int create_cookie_response (const Net_Crypto * c, uint8_t * packet, const uint8_t * request_plain, const uint8_t * shared_key, const uint8_t * dht_public_key) [static]
Definition at line 145 of file net_crypto.c.
References COOKIE_DATA_LENGTH, COOKIE_LENGTH, COOKIE_RESPONSE_LENGTH, create_cookie(), encrypt_data_symmetric(), NET_PACKET_COOKIE_RESPONSE, new_nonce(), and Net_Crypto::secret_symmetric_key.
Referenced by tcp_handle_cookie_request(), tcp_oob_handle_cookie_request(), and udp_handle_cookie_request().
{
    uint8_t cookie_plain[COOKIE_DATA_LENGTH];
    memcpy(cookie_plain, request_plain, crypto_box_PUBLICKEYBYTES);
    memcpy(cookie_plain + crypto_box_PUBLICKEYBYTES, dht_public_key, crypto_box_PUBLICKEYBYTES);
    uint8_t plain[COOKIE_LENGTH + sizeof(uint64_t)];
    if (create_cookie(plain, cookie_plain, c->secret_symmetric_key) != 0)
        return -1;
    memcpy(plain + COOKIE_LENGTH, request_plain +
      COOKIE_DATA_LENGTH, sizeof(uint64_t));
    packet[0] = NET_PACKET_COOKIE_RESPONSE;
    new_nonce(packet + 1);
    int len = encrypt_data_symmetric(shared_key, packet + 1, plain, sizeof(plain),
      packet + 1 + crypto_box_NONCEBYTES);
    if (len != COOKIE_RESPONSE_LENGTH - (1 + crypto_box_NONCEBYTES))
        return -1;
    return COOKIE_RESPONSE_LENGTH;
}
static int create_crypto_connection (Net_Crypto * c) [static]
Definition at line 1375 of file net_crypto.c.
References Net_Crypto::connection_use_counter, Net_Crypto::connections_mutex, CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, Net_Crypto::crypto_connections_length, i, Crypto_Connection::mutex, realloc_cryptoconnection(), and Crypto_Connection::status.
Referenced by accept_crypto_connection(), and new_crypto_connection().
{
    uint32_t i;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        if (c->crypto_connections[i].status ==
      CRYPTO_CONN_NO_CONNECTION)
            return i;
    }
    while (1) { /* TODO: is this really the best way to do this? */
        pthread_mutex_lock(&c->connections_mutex);
        if (!c->connection_use_counter) {
            break;
        }
        pthread_mutex_unlock(&c->connections_mutex);
    }
    int id = -1;
    if (realloc_cryptoconnection(c, c->
      crypto_connections_length + 1) == 0) {
        id = c->crypto_connections_length;
        ++c->crypto_connections_length;
        memset(&(c->crypto_connections[id]), 0, sizeof(
      Crypto_Connection));
        if (pthread_mutex_init(&c->crypto_connections[id].
      mutex, NULL) != 0) {
            pthread_mutex_unlock(&c->connections_mutex);
            return -1;
        }
    }
    pthread_mutex_unlock(&c->connections_mutex);
    return id;
}
static int create_crypto_handshake (const Net_Crypto * c, uint8_t * packet, const uint8_t * cookie, const uint8_t * nonce, const uint8_t * session_pk, const uint8_t * peer_real_pk, const uint8_t * peer_dht_pubkey) [static]
Definition at line 294 of file net_crypto.c.
References COOKIE_DATA_LENGTH, COOKIE_LENGTH, create_cookie(), encrypt_data(), HANDSHAKE_PACKET_LENGTH, NET_PACKET_CRYPTO_HS, new_nonce(), Net_Crypto::secret_symmetric_key, and Net_Crypto::self_secret_key.
Referenced by create_send_handshake().
{
    uint8_t plain[crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_hash_sha512_BYTES +
      COOKIE_LENGTH];
    memcpy(plain, nonce, crypto_box_NONCEBYTES);
    memcpy(plain + crypto_box_NONCEBYTES, session_pk, crypto_box_PUBLICKEYBYTES);
    crypto_hash_sha512(plain + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES, cookie,
      COOKIE_LENGTH);
    uint8_t cookie_plain[COOKIE_DATA_LENGTH];
    memcpy(cookie_plain, peer_real_pk, crypto_box_PUBLICKEYBYTES);
    memcpy(cookie_plain + crypto_box_PUBLICKEYBYTES, peer_dht_pubkey, crypto_box_PUBLICKEYBYTES);
    if (create_cookie(plain + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES +
      crypto_hash_sha512_BYTES, cookie_plain,
                      c->secret_symmetric_key) != 0)
        return -1;
    new_nonce(packet + 1 + COOKIE_LENGTH);
    int len = encrypt_data(peer_real_pk, c->self_secret_key, packet + 1 +
      COOKIE_LENGTH, plain, sizeof(plain),
                           packet + 1 + COOKIE_LENGTH + crypto_box_NONCEBYTES);
    if (len != HANDSHAKE_PACKET_LENGTH - (1 +
      COOKIE_LENGTH + crypto_box_NONCEBYTES))
        return -1;
    packet[0] = NET_PACKET_CRYPTO_HS;
    memcpy(packet + 1, cookie, COOKIE_LENGTH);
    return HANDSHAKE_PACKET_LENGTH;
}
static int create_send_handshake (Net_Crypto * c, int crypt_connection_id, const uint8_t * cookie, const uint8_t * dht_public_key) [static]
Definition at line 1081 of file net_crypto.c.
References create_crypto_handshake(), get_crypto_connection(), HANDSHAKE_PACKET_LENGTH, new_temp_packet(), Crypto_Connection::public_key, send_temp_packet(), Crypto_Connection::sent_nonce, and Crypto_Connection::sessionpublic_key.
Referenced by accept_crypto_connection(), handle_new_connection_handshake(), and handle_packet_connection().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t handshake_packet[HANDSHAKE_PACKET_LENGTH];
    if (create_crypto_handshake(c, handshake_packet, cookie, conn->
      sent_nonce, conn->sessionpublic_key,
                                conn->public_key, dht_public_key) != sizeof(handshake_packet))
        return -1;
    if (new_temp_packet(c, crypt_connection_id, handshake_packet, sizeof(handshake_packet))
      != 0)
        return -1;
    send_temp_packet(c, crypt_connection_id);
    return 0;
}
static uint8_t crypt_connection_id_not_valid (const Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 35 of file net_crypto.c.
References CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, Net_Crypto::crypto_connections_length, and Crypto_Connection::status.
Referenced by get_crypto_connection(), and wipe_crypto_connection().
{
    if ((uint32_t)crypt_connection_id >= c->crypto_connections_length)
        return 1;
    if (c->crypto_connections == NULL)
        return 1;
    if (c->crypto_connections[crypt_connection_id].status ==
      CRYPTO_CONN_NO_CONNECTION)
        return 1;
    return 0;
}
static int crypto_connection_add_source (Net_Crypto * c, int crypt_connection_id, IP_Port source) [static]
Definition at line 1469 of file net_crypto.c.
References add_tcp_number_relay_connection(), bs_list_add(), bs_list_remove(), Crypto_Connection::connection_number_tcp, Crypto_Connection::direct_lastrecv_time, IP::family, get_crypto_connection(), IP_Port::ip, IP::ip6, Crypto_Connection::ip_port, Net_Crypto::ip_port_list, ipport_equal(), Net_Crypto::tcp_c, TCP_FAMILY, IP6::uint32, and unix_time().
Referenced by accept_crypto_connection(), and handle_new_connection_handshake().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (source.ip.family == AF_INET || source.ip.family == AF_INET6) {
        if (!ipport_equal(&source, &conn->ip_port)) {
            if (!bs_list_add(&c->ip_port_list, (uint8_t *)&source,
      crypt_connection_id))
                return -1;
            bs_list_remove(&c->ip_port_list, (uint8_t *)&conn->
      ip_port, crypt_connection_id);
            conn->ip_port = source;
        }
        conn->direct_lastrecv_time = unix_time();
        return 0;
    } else if (source.ip.family == TCP_FAMILY) {
        if (add_tcp_number_relay_connection(c->
      tcp_c, conn->connection_number_tcp, source.ip.ip6.
      uint32[0]) == 0)
            return 1;
    }
    return -1;
}
unsigned int crypto_connection_status (const Net_Crypto * c, int crypt_connection_id, _Bool * direct_connected, unsigned int * online_tcp_relays)
Definition at line 2364 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, CRYPTO_CONN_NO_CONNECTION, Crypto_Connection::direct_lastrecv_time, get_crypto_connection(), Crypto_Connection::status, Net_Crypto::tcp_c, tcp_connection_to_online_tcp_relays(), UDP_DIRECT_TIMEOUT, and unix_time().
Referenced by do_tcp(), m_get_friend_connectionstatus(), and send_packet_to().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return CRYPTO_CONN_NO_CONNECTION;
    if (direct_connected) {
        *direct_connected = 0;
        if ((UDP_DIRECT_TIMEOUT + conn->direct_lastrecv_time) >
      unix_time())
            *direct_connected = 1;
    }
    if (online_tcp_relays) {
        *online_tcp_relays = tcp_connection_to_online_tcp_relays(c->
      tcp_c, conn->connection_number_tcp);
    }
    return conn->status;
}
static int crypto_id_ip_port (const Net_Crypto * c, IP_Port ip_port) [static]
Definition at line 1980 of file net_crypto.c.
References bs_list_find(), and Net_Crypto::ip_port_list.
Referenced by udp_handle_packet().
{
    return bs_list_find(&c->ip_port_list, (uint8_t *)&ip_port);
}
int crypto_kill (Net_Crypto * c, int crypt_connection_id)
Definition at line 2323 of file net_crypto.c.
References bs_list_remove(), clear_buffer(), clear_temp_packet(), Crypto_Connection::connection_number_tcp, Net_Crypto::connection_use_counter, Net_Crypto::connections_mutex, CRYPTO_CONN_ESTABLISHED, get_crypto_connection(), Crypto_Connection::ip_port, Net_Crypto::ip_port_list, kill_tcp_connection_to(), Crypto_Connection::recv_array, Crypto_Connection::send_array, send_kill_packet(), Crypto_Connection::status, Net_Crypto::tcp_c, Net_Crypto::tcp_mutex, and wipe_crypto_connection().
Referenced by connection_kill(), dht_pk_callback(), do_friend_connections(), kill_friend_connection(), and kill_net_crypto().
{
    while (1) { /* TODO: is this really the best way to do this? */
        pthread_mutex_lock(&c->connections_mutex);
        if (!c->connection_use_counter) {
            break;
        }
        pthread_mutex_unlock(&c->connections_mutex);
    }
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    int ret = -1;
    if (conn) {
        if (conn->status == CRYPTO_CONN_ESTABLISHED)
            send_kill_packet(c, crypt_connection_id);
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        bs_list_remove(&c->ip_port_list, (uint8_t *)&conn->
      ip_port, crypt_connection_id);
        clear_temp_packet(c, crypt_connection_id);
        clear_buffer(&conn->send_array);
        clear_buffer(&conn->recv_array);
        ret = wipe_crypto_connection(c, crypt_connection_id);
    }
    pthread_mutex_unlock(&c->connections_mutex);
    return ret;
}
uint32_t crypto_num_free_sendqueue_slots (const Net_Crypto * c, int crypt_connection_id)
Definition at line 2196 of file net_crypto.c.
References CRYPTO_PACKET_BUFFER_SIZE, get_crypto_connection(), num_packets_array(), Crypto_Connection::packets_left, and Crypto_Connection::send_array.
Referenced by do_reqchunk_filecb(), and file_data().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return 0;
    uint32_t max_packets = CRYPTO_PACKET_BUFFER_SIZE -
      num_packets_array(&conn->send_array);
    if (conn->packets_left < max_packets) {
        return conn->packets_left;
    } else {
        return max_packets;
    }
}
uint32_t crypto_run_interval (const Net_Crypto * c)
Definition at line 2491 of file net_crypto.c.
References Net_Crypto::current_sleep_time.
Referenced by messenger_run_interval().
{
    return c->current_sleep_time;
}
int cryptpacket_received (Net_Crypto * c, int crypt_connection_id, uint32_t packet_number)
Definition at line 2262 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, get_crypto_connection(), num, and Crypto_Connection::send_array.
Referenced by friend_received_packet().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint32_t num = conn->send_array.buffer_end - conn->
      send_array.buffer_start;
    uint32_t num1 = packet_number - conn->send_array.buffer_start;
    if (num < num1) {
        return 0;
    } else {
        return -1;
    }
}
void do_net_crypto (Net_Crypto * c)
Definition at line 2497 of file net_crypto.c.
References do_tcp(), kill_timedout(), send_crypto_packets(), and unix_time_update().
Referenced by do_messenger().
{
    unix_time_update();
    kill_timedout(c);
    do_tcp(c);
    send_crypto_packets(c);
}
static void do_tcp (Net_Crypto * c) [static]
Definition at line 1851 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, CRYPTO_CONN_ESTABLISHED, crypto_connection_status(), Net_Crypto::crypto_connections_length, do_tcp_connections(), get_crypto_connection(), i, set_tcp_connection_to_status(), Crypto_Connection::status, Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by do_net_crypto().
{
    pthread_mutex_lock(&c->tcp_mutex);
    do_tcp_connections(c->tcp_c);
    pthread_mutex_unlock(&c->tcp_mutex);
    uint32_t i;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        Crypto_Connection *conn = get_crypto_connection(c, i);
        if (conn == 0)
            return;
        if (conn->status == CRYPTO_CONN_ESTABLISHED) {
            _Bool direct_connected = 0;
            crypto_connection_status(c, i, &direct_connected, NULL);
            if (direct_connected) {
                pthread_mutex_lock(&c->tcp_mutex);
                set_tcp_connection_to_status(c->
      tcp_c, conn->connection_number_tcp, 0);
                pthread_mutex_unlock(&c->tcp_mutex);
            } else {
                pthread_mutex_lock(&c->tcp_mutex);
                set_tcp_connection_to_status(c->
      tcp_c, conn->connection_number_tcp, 1);
                pthread_mutex_unlock(&c->tcp_mutex);
            }
        }
    }
}
static int generate_request_packet (uint8_t * data, uint16_t length, const Packets_Array * recv_array) [static]
Definition at line 612 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, i, num, and PACKET_ID_REQUEST.
Referenced by send_request_packet().
{
    if (length == 0)
        return -1;
    data[0] = PACKET_ID_REQUEST;
    uint16_t cur_len = 1;
    if (recv_array->buffer_start == recv_array->buffer_end)
        return cur_len;
    if (length <= cur_len)
        return cur_len;
    uint32_t i, n = 1;
    for (i = recv_array->buffer_start; i != recv_array->buffer_end; ++i) {
        uint32_t num = i % CRYPTO_PACKET_BUFFER_SIZE;
        if (!recv_array->buffer[num]) {
            data[cur_len] = n;
            n = 0;
            ++cur_len;
            if (length <= cur_len)
                return cur_len;
        } else if (n == 255) {
            data[cur_len] = 0;
            n = 0;
            ++cur_len;
            if (length <= cur_len)
                return cur_len;
        }
        ++n;
    }
    return cur_len;
}
static Crypto_Connection* get_crypto_connection (const Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 378 of file net_crypto.c.
References crypt_connection_id_not_valid(), and Net_Crypto::crypto_connections.
Referenced by add_tcp_relay_peer(), clear_temp_packet(), connection_data_handler(), connection_kill(), connection_lossy_data_handler(), connection_status_handler(), create_send_handshake(), crypto_connection_add_source(), crypto_connection_status(), crypto_kill(), crypto_num_free_sendqueue_slots(), cryptpacket_received(), do_tcp(), handle_data_packet(), handle_data_packet_helper(), handle_new_connection_handshake(), handle_packet_connection(), kill_timedout(), nc_dht_pk_callback(), new_temp_packet(), reset_max_speed_reached(), send_crypto_packets(), send_data_packet(), send_kill_packet(), send_lossless_packet(), send_lossy_cryptpacket(), send_packet_to(), send_request_packet(), send_requested_packets(), send_temp_packet(), set_direct_ip_port(), tcp_data_callback(), udp_handle_packet(), and write_cryptpacket().
{
    if (crypt_connection_id_not_valid(c, crypt_connection_id))
        return 0;
    return &c->crypto_connections[crypt_connection_id];
}
static int get_data_pointer (const Packets_Array * array, Packet_Data ** data, uint32_t number) [static]
Definition at line 484 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, and num.
Referenced by handle_data_packet_helper(), reset_max_speed_reached(), send_lossless_packet(), and send_requested_packets().
{
    uint32_t num_spots = array->buffer_end - array->buffer_start;
    if (array->buffer_end - number > num_spots || number - array->
      buffer_start >= num_spots)
        return -1;
    uint32_t num = number % CRYPTO_PACKET_BUFFER_SIZE;
    if (!array->buffer[num])
        return 0;
    *data = array->buffer[num];
    return 1;
}
static uint16_t get_nonce_uint16 (const uint8_t * nonce) [static]
Definition at line 881 of file net_crypto.c.
References num.
Referenced by handle_data_packet().
{
    uint16_t num;
    memcpy(&num, nonce + (crypto_box_NONCEBYTES - sizeof(uint16_t)), sizeof(uint16_t));
    return ntohs(num);
}
int get_random_tcp_con_number (Net_Crypto * c)
Definition at line 1810 of file net_crypto.c.
References get_random_tcp_onion_conn_number(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by random_nodes_path_onion().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = get_random_tcp_onion_conn_number(c->
      tcp_c);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
static int getcryptconnection_id (const Net_Crypto * c, const uint8_t * public_key) [static]
Definition at line 1449 of file net_crypto.c.
References CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, Net_Crypto::crypto_connections_length, i, Crypto_Connection::public_key, and Crypto_Connection::status.
Referenced by accept_crypto_connection(), handle_new_connection_handshake(), and new_crypto_connection().
{
    uint32_t i;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        if (c->crypto_connections[i].status !=
      CRYPTO_CONN_NO_CONNECTION)
            if (memcmp(public_key, c->crypto_connections[i].
      public_key, crypto_box_PUBLICKEYBYTES) == 0)
                return i;
    }
    return -1;
}
static int handle_cookie_request (const Net_Crypto * c, uint8_t * request_plain, uint8_t * shared_key, uint8_t * dht_public_key, const uint8_t * packet, uint16_t length) [static]
Definition at line 174 of file net_crypto.c.
References COOKIE_REQUEST_LENGTH, COOKIE_REQUEST_PLAIN_LENGTH, decrypt_data_symmetric(), Net_Crypto::dht, and DHT_get_shared_key_sent().
Referenced by tcp_handle_cookie_request(), tcp_oob_handle_cookie_request(), and udp_handle_cookie_request().
{
    if (length != COOKIE_REQUEST_LENGTH)
        return -1;
    memcpy(dht_public_key, packet + 1, crypto_box_PUBLICKEYBYTES);
    DHT_get_shared_key_sent(c->dht, shared_key, dht_public_key);
    int len = decrypt_data_symmetric(shared_key, packet + 1 +
      crypto_box_PUBLICKEYBYTES,
                                     packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES,
      COOKIE_REQUEST_PLAIN_LENGTH + crypto_box_MACBYTES,
                                     request_plain);
    if (len != COOKIE_REQUEST_PLAIN_LENGTH)
        return -1;
    return 0;
}
static int handle_cookie_response (uint8_t * cookie, uint64_t * number, const uint8_t * packet, uint16_t length, const uint8_t * shared_key) [static]
Definition at line 267 of file net_crypto.c.
References COOKIE_LENGTH, COOKIE_RESPONSE_LENGTH, and decrypt_data_symmetric().
Referenced by handle_packet_connection().
{
    if (length != COOKIE_RESPONSE_LENGTH)
        return -1;
    uint8_t plain[COOKIE_LENGTH + sizeof(uint64_t)];
    int len = decrypt_data_symmetric(shared_key, packet + 1, packet + 1 +
      crypto_box_NONCEBYTES,
                                     length - (1 + crypto_box_NONCEBYTES), plain);
    if (len != sizeof(plain))
        return -1;
    memcpy(cookie, plain, COOKIE_LENGTH);
    memcpy(number, plain + COOKIE_LENGTH, sizeof(uint64_t));
    return COOKIE_LENGTH;
}
static int handle_crypto_handshake (const Net_Crypto * c, uint8_t * nonce, uint8_t * session_pk, uint8_t * peer_real_pk, uint8_t * dht_public_key, uint8_t * cookie, const uint8_t * packet, uint16_t length, const uint8_t * expected_real_pk) [static]
Definition at line 340 of file net_crypto.c.
References COOKIE_DATA_LENGTH, COOKIE_LENGTH, decrypt_data(), HANDSHAKE_PACKET_LENGTH, open_cookie(), public_key_cmp(), Net_Crypto::secret_symmetric_key, and Net_Crypto::self_secret_key.
Referenced by handle_new_connection_handshake(), and handle_packet_connection().
{
    if (length != HANDSHAKE_PACKET_LENGTH)
        return -1;
    uint8_t cookie_plain[COOKIE_DATA_LENGTH];
    if (open_cookie(cookie_plain, packet + 1, c->secret_symmetric_key) != 0)
        return -1;
    if (expected_real_pk)
        if (public_key_cmp(cookie_plain, expected_real_pk) != 0)
            return -1;
    uint8_t cookie_hash[crypto_hash_sha512_BYTES];
    crypto_hash_sha512(cookie_hash, packet + 1, COOKIE_LENGTH);
    uint8_t plain[crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_hash_sha512_BYTES +
      COOKIE_LENGTH];
    int len = decrypt_data(cookie_plain, c->self_secret_key, packet + 1 +
      COOKIE_LENGTH,
                           packet + 1 + COOKIE_LENGTH + crypto_box_NONCEBYTES,
                           HANDSHAKE_PACKET_LENGTH - (1 +
      COOKIE_LENGTH + crypto_box_NONCEBYTES), plain);
    if (len != sizeof(plain))
        return -1;
    if (memcmp(cookie_hash, plain + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
      crypto_hash_sha512_BYTES) != 0)
        return -1;
    memcpy(nonce, plain, crypto_box_NONCEBYTES);
    memcpy(session_pk, plain + crypto_box_NONCEBYTES, crypto_box_PUBLICKEYBYTES);
    memcpy(cookie, plain + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_hash_sha512_BYTES,
      COOKIE_LENGTH);
    memcpy(peer_real_pk, cookie_plain, crypto_box_PUBLICKEYBYTES);
    memcpy(dht_public_key, cookie_plain + crypto_box_PUBLICKEYBYTES, crypto_box_PUBLICKEYBYTES);
    return 0;
}
static int handle_data_packet (const Net_Crypto * c, int crypt_connection_id, uint8_t * data, const uint8_t * packet, uint16_t length) [static]
Definition at line 897 of file net_crypto.c.
References DATA_NUM_THRESHOLD, decrypt_data_symmetric(), get_crypto_connection(), get_nonce_uint16(), increment_nonce_number(), MAX_CRYPTO_PACKET_SIZE, nonce, num, Crypto_Connection::recv_nonce, and Crypto_Connection::shared_key.
Referenced by handle_data_packet_helper().
{
    if (length <= (1 + sizeof(uint16_t) + crypto_box_MACBYTES) || length >
      MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES];
    memcpy(nonce, conn->recv_nonce, crypto_box_NONCEBYTES);
    uint16_t num_cur_nonce = get_nonce_uint16(nonce);
    uint16_t num;
    memcpy(&num, packet + 1, sizeof(uint16_t));
    num = ntohs(num);
    uint16_t diff = num - num_cur_nonce;
    increment_nonce_number(nonce, diff);
    int len = decrypt_data_symmetric(conn->shared_key, nonce, packet + 1 +
      sizeof(uint16_t),
                                     length - (1 + sizeof(uint16_t)), data);
    if ((unsigned int)len != length - (1 + sizeof(uint16_t) + crypto_box_MACBYTES))
        return -1;
    if (diff > DATA_NUM_THRESHOLD * 2) {
        increment_nonce_number(conn->recv_nonce,
      DATA_NUM_THRESHOLD);
    }
    return len;
}
static int handle_data_packet_helper (Net_Crypto * c, int crypt_connection_id, const uint8_t * packet, uint16_t length) [static]
Definition at line 1138 of file net_crypto.c.
References add_data_to_buffer(), Packets_Array::buffer_start, clear_buffer_until(), clear_temp_packet(), Crypto_Connection::connection_data_callback, Crypto_Connection::connection_data_callback_id, Crypto_Connection::connection_data_callback_object, connection_kill(), Crypto_Connection::connection_lossy_data_callback, Crypto_Connection::connection_lossy_data_callback_id, Crypto_Connection::connection_lossy_data_callback_object, Crypto_Connection::connection_status_callback, Crypto_Connection::connection_status_callback_id, Crypto_Connection::connection_status_callback_object, CRYPTO_CONN_ESTABLISHED, CRYPTO_CONN_NOT_CONFIRMED, CRYPTO_DATA_PACKET_MIN_SIZE, CRYPTO_RESERVED_PACKETS, current_time_monotonic(), Packet_Data::data, make-funny-savefile::data, get_crypto_connection(), get_data_pointer(), handle_data_packet(), handle_request_packet(), Packet_Data::length, MAX_CRYPTO_PACKET_SIZE, MAX_DATA_DATA_PACKET_SIZE, Crypto_Connection::mutex, num, Crypto_Connection::packet_counter, PACKET_ID_KILL, PACKET_ID_LOSSY_RANGE_SIZE, PACKET_ID_LOSSY_RANGE_START, PACKET_ID_PADDING, PACKET_ID_REQUEST, read_data_beg_buffer(), Crypto_Connection::recv_array, Crypto_Connection::rtt_time, Crypto_Connection::send_array, Packet_Data::sent_time, set_buffer_end(), and Crypto_Connection::status.
Referenced by handle_packet_connection().
{
    if (length > MAX_CRYPTO_PACKET_SIZE || length <=
      CRYPTO_DATA_PACKET_MIN_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t data[MAX_DATA_DATA_PACKET_SIZE];
    int len = handle_data_packet(c, crypt_connection_id, data, packet, length);
    if (len <= (int)(sizeof(uint32_t) * 2))
        return -1;
    uint32_t buffer_start, num;
    memcpy(&buffer_start, data, sizeof(uint32_t));
    memcpy(&num, data + sizeof(uint32_t), sizeof(uint32_t));
    buffer_start = ntohl(buffer_start);
    num = ntohl(num);
    uint64_t rtt_calc_time = 0;
    if (buffer_start != conn->send_array.buffer_start) {
        Packet_Data *packet_time;
        if (get_data_pointer(&conn->send_array, &packet_time, conn->
      send_array.buffer_start) == 1) {
            rtt_calc_time = packet_time->sent_time;
        }
        if (clear_buffer_until(&conn->send_array, buffer_start) != 0) {
            return -1;
        }
    }
    uint8_t *real_data = data + (sizeof(uint32_t) * 2);
    uint16_t real_length = len - (sizeof(uint32_t) * 2);
    while (real_data[0] == PACKET_ID_PADDING) { /* Remove Padding */
        ++real_data;
        --real_length;
        if (real_length == 0)
            return -1;
    }
    if (real_data[0] == PACKET_ID_KILL) {
        connection_kill(c, crypt_connection_id);
        return 0;
    }
    if (conn->status == CRYPTO_CONN_NOT_CONFIRMED) {
        clear_temp_packet(c, crypt_connection_id);
        conn->status = CRYPTO_CONN_ESTABLISHED;
        if (conn->connection_status_callback)
            conn->connection_status_callback(conn->
      connection_status_callback_object, conn->
      connection_status_callback_id, 1);
    }
    if (real_data[0] == PACKET_ID_REQUEST) {
        int requested = handle_request_packet(&conn->
      send_array, real_data, real_length, &rtt_calc_time, conn->rtt_time);
        if (requested == -1) {
            return -1;
        } else {
            //TODO?
        }
        set_buffer_end(&conn->recv_array, num);
    } else if (real_data[0] >= CRYPTO_RESERVED_PACKETS && real_data[0] <
      PACKET_ID_LOSSY_RANGE_START) {
        Packet_Data dt;
        dt.length = real_length;
        memcpy(dt.data, real_data, real_length);
        if (add_data_to_buffer(&conn->recv_array, num, &dt) != 0)
            return -1;
        while (1) {
            pthread_mutex_lock(&conn->mutex);
            int ret = read_data_beg_buffer(&conn->recv_array, &dt);
            pthread_mutex_unlock(&conn->mutex);
            if (ret == -1)
                break;
            if (conn->connection_data_callback)
                conn->connection_data_callback(conn->
      connection_data_callback_object, conn->
      connection_data_callback_id, dt.data,
                                               dt.length);
            /* conn might get killed in callback. */
            conn = get_crypto_connection(c, crypt_connection_id);
            if (conn == 0)
                return -1;
        }
        /* Packet counter. */
        ++conn->packet_counter;
    } else if (real_data[0] >= PACKET_ID_LOSSY_RANGE_START &&
               real_data[0] < (PACKET_ID_LOSSY_RANGE_START +
      PACKET_ID_LOSSY_RANGE_SIZE)) {
        set_buffer_end(&conn->recv_array, num);
        if (conn->connection_lossy_data_callback)
            conn->connection_lossy_data_callback(conn->
      connection_lossy_data_callback_object,
                                                 conn->
      connection_lossy_data_callback_id, real_data, real_length);
    } else {
        return -1;
    }
    if (rtt_calc_time != 0) {
        uint64_t rtt_time = current_time_monotonic() - rtt_calc_time;
        if (rtt_time < conn->rtt_time)
            conn->rtt_time = rtt_time;
    }
    return 0;
}
static int handle_new_connection_handshake (Net_Crypto * c, IP_Port source, const uint8_t * data, uint16_t length) [static]
Definition at line 1515 of file net_crypto.c.
References connection_kill(), New_Connection::cookie, COOKIE_LENGTH, New_Connection::cookie_length, create_send_handshake(), CRYPTO_CONN_COOKIE_REQUESTING, CRYPTO_CONN_HANDSHAKE_SENT, CRYPTO_CONN_NOT_CONFIRMED, crypto_connection_add_source(), Crypto_Connection::dht_public_key, New_Connection::dht_public_key, encrypt_precompute(), get_crypto_connection(), getcryptconnection_id(), handle_crypto_handshake(), Net_Crypto::new_connection_callback, Net_Crypto::new_connection_callback_object, Crypto_Connection::peersessionpublic_key, New_Connection::peersessionpublic_key, New_Connection::public_key, public_key_cmp(), Crypto_Connection::recv_nonce, New_Connection::recv_nonce, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, New_Connection::source, and Crypto_Connection::status.
Referenced by tcp_oob_callback(), and udp_handle_packet().
{
    New_Connection n_c;
    n_c.cookie = malloc(COOKIE_LENGTH);
    if (n_c.cookie == NULL)
        return -1;
    n_c.source = source;
    n_c.cookie_length = COOKIE_LENGTH;
    if (handle_crypto_handshake(c, n_c.recv_nonce, n_c.
      peersessionpublic_key, n_c.public_key, n_c.
      dht_public_key,
                                n_c.cookie, data, length, 0) != 0) {
        free(n_c.cookie);
        return -1;
    }
    int crypt_connection_id = getcryptconnection_id(c, n_c.
      public_key);
    if (crypt_connection_id != -1) {
        Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
        if (public_key_cmp(n_c.dht_public_key, conn->
      dht_public_key) != 0) {
            connection_kill(c, crypt_connection_id);
        } else {
            int ret = -1;
            if (conn && (conn->status == CRYPTO_CONN_COOKIE_REQUESTING
      || conn->status == CRYPTO_CONN_HANDSHAKE_SENT)) {
                memcpy(conn->recv_nonce, n_c.recv_nonce, crypto_box_NONCEBYTES);
                memcpy(conn->peersessionpublic_key, n_c.
      peersessionpublic_key, crypto_box_PUBLICKEYBYTES);
                encrypt_precompute(conn->peersessionpublic_key, conn
      ->sessionsecret_key, conn->shared_key);
                crypto_connection_add_source(c, crypt_connection_id, source);
                if (create_send_handshake(c, crypt_connection_id, n_c.
      cookie, n_c.dht_public_key) == 0) {
                    conn->status = CRYPTO_CONN_NOT_CONFIRMED;
                    ret = 0;
                }
            }
            free(n_c.cookie);
            return ret;
        }
    }
    int ret = c->new_connection_callback(c->
      new_connection_callback_object, &n_c);
    free(n_c.cookie);
    return ret;
}
static int handle_packet_connection (Net_Crypto * c, int crypt_connection_id, const uint8_t * packet, uint16_t length) [static]
Definition at line 1266 of file net_crypto.c.
References COOKIE_LENGTH, Crypto_Connection::cookie_request_number, create_send_handshake(), CRYPTO_CONN_COOKIE_REQUESTING, CRYPTO_CONN_ESTABLISHED, CRYPTO_CONN_HANDSHAKE_SENT, CRYPTO_CONN_NOT_CONFIRMED, Crypto_Connection::dht_pk_callback, Crypto_Connection::dht_pk_callback_number, Crypto_Connection::dht_pk_callback_object, Crypto_Connection::dht_public_key, encrypt_precompute(), get_crypto_connection(), handle_cookie_response(), handle_crypto_handshake(), handle_data_packet_helper(), MAX_CRYPTO_PACKET_SIZE, NET_PACKET_COOKIE_RESPONSE, NET_PACKET_CRYPTO_DATA, NET_PACKET_CRYPTO_HS, Crypto_Connection::peersessionpublic_key, Crypto_Connection::public_key, public_key_cmp(), Crypto_Connection::recv_nonce, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, and Crypto_Connection::status.
Referenced by tcp_data_callback(), and udp_handle_packet().
{
    if (length == 0 || length > MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    switch (packet[0]) {
        case NET_PACKET_COOKIE_RESPONSE: {
            if (conn->status != CRYPTO_CONN_COOKIE_REQUESTING)
                return -1;
            uint8_t cookie[COOKIE_LENGTH];
            uint64_t number;
            if (handle_cookie_response(cookie, &number, packet, length, conn->
      shared_key) != sizeof(cookie))
                return -1;
            if (number != conn->cookie_request_number)
                return -1;
            if (create_send_handshake(c, crypt_connection_id, cookie, conn->
      dht_public_key) != 0)
                return -1;
            conn->status = CRYPTO_CONN_HANDSHAKE_SENT;
            return 0;
        }
        case NET_PACKET_CRYPTO_HS: {
            if (conn->status == CRYPTO_CONN_COOKIE_REQUESTING || conn->
      status == CRYPTO_CONN_HANDSHAKE_SENT
                    || conn->status == CRYPTO_CONN_NOT_CONFIRMED) {
                uint8_t peer_real_pk[crypto_box_PUBLICKEYBYTES];
                uint8_t dht_public_key[crypto_box_PUBLICKEYBYTES];
                uint8_t cookie[COOKIE_LENGTH];
                if (handle_crypto_handshake(c, conn->
      recv_nonce, conn->peersessionpublic_key, peer_real_pk, dht_public_key,
      cookie,
                                            packet, length, conn->public_key) != 0)
                    return -1;
                if (public_key_cmp(dht_public_key, conn->
      dht_public_key) == 0) {
                    encrypt_precompute(conn->
      peersessionpublic_key, conn->sessionsecret_key, conn->
      shared_key);
                    if (conn->status == CRYPTO_CONN_COOKIE_REQUESTING) {
                        if (create_send_handshake(c, crypt_connection_id, cookie,
      dht_public_key) != 0)
                            return -1;
                    }
                    conn->status = CRYPTO_CONN_NOT_CONFIRMED;
                } else {
                    if (conn->dht_pk_callback)
                        conn->dht_pk_callback(conn->
      dht_pk_callback_object, conn->dht_pk_callback_number,
      dht_public_key);
                }
            } else {
                return -1;
            }
            return 0;
        }
        case NET_PACKET_CRYPTO_DATA: {
            if (conn->status == CRYPTO_CONN_NOT_CONFIRMED || conn->
      status == CRYPTO_CONN_ESTABLISHED) {
                return handle_data_packet_helper(c, crypt_connection_id, packet,
      length);
            } else {
                return -1;
            }
            return 0;
        }
        default: {
            return -1;
        }
    }
    return 0;
}
static int handle_request_packet (Packets_Array * send_array, const uint8_t * data, uint16_t length, uint64_t * latest_send_time, uint64_t rtt_time) [static]
Definition at line 661 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, current_time_monotonic(), make-funny-savefile::data, i, num, PACKET_ID_REQUEST, and Packet_Data::sent_time.
Referenced by handle_data_packet_helper().
{
    if (length < 1)
        return -1;
    if (data[0] != PACKET_ID_REQUEST)
        return -1;
    if (length == 1)
        return 0;
    ++data;
    --length;
    uint32_t i, n = 1;
    uint32_t requested = 0;
    uint64_t temp_time = current_time_monotonic();
    uint64_t l_sent_time = ~0;
    for (i = send_array->buffer_start; i != send_array->buffer_end; ++i) {
        if (length == 0)
            break;
        uint32_t num = i % CRYPTO_PACKET_BUFFER_SIZE;
        if (n == data[0]) {
            if (send_array->buffer[num]) {
                uint64_t sent_time = send_array->buffer[num]->sent_time;
                if ((sent_time + rtt_time) < temp_time) {
                    send_array->buffer[num]->sent_time = 0;
                }
            }
            ++data;
            --length;
            n = 0;
            ++requested;
        } else {
            if (send_array->buffer[num]) {
                uint64_t sent_time = send_array->buffer[num]->sent_time;
                if (l_sent_time < sent_time)
                    l_sent_time = sent_time;
                free(send_array->buffer[num]);
                send_array->buffer[num] = NULL;
            }
        }
        if (n == 255) {
            n = 1;
            if (data[0] != 0)
                return -1;
            ++data;
            --length;
        } else {
            ++n;
        }
    }
    if (*latest_send_time < l_sent_time)
        *latest_send_time = l_sent_time;
    return requested;
}
void kill_net_crypto (Net_Crypto * c)
Definition at line 2505 of file net_crypto.c.
References bs_list_free(), Net_Crypto::connections_mutex, Net_Crypto::crypto_connections_length, crypto_kill(), Net_Crypto::dht, i, Net_Crypto::ip_port_list, kill_tcp_connections(), DHT::net, NET_PACKET_COOKIE_REQUEST, NET_PACKET_COOKIE_RESPONSE, NET_PACKET_CRYPTO_DATA, NET_PACKET_CRYPTO_HS, networking_registerhandler(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by kill_messenger(), kill_onions(), and new_messenger().
{
    uint32_t i;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        crypto_kill(c, i);
    }
    pthread_mutex_destroy(&c->tcp_mutex);
    pthread_mutex_destroy(&c->connections_mutex);
    kill_tcp_connections(c->tcp_c);
    bs_list_free(&c->ip_port_list);
    networking_registerhandler(c->dht->net,
      NET_PACKET_COOKIE_REQUEST, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_COOKIE_RESPONSE, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_CRYPTO_HS, NULL, NULL);
    networking_registerhandler(c->dht->net,
      NET_PACKET_CRYPTO_DATA, NULL, NULL);
    memset(c, 0, sizeof(Net_Crypto));
    free(c);
}
static void kill_timedout (Net_Crypto * c) [static]
Definition at line 2460 of file net_crypto.c.
References connection_kill(), CRYPTO_CONN_COOKIE_REQUESTING, CRYPTO_CONN_ESTABLISHED, CRYPTO_CONN_HANDSHAKE_SENT, CRYPTO_CONN_NO_CONNECTION, CRYPTO_CONN_NOT_CONFIRMED, Net_Crypto::crypto_connections_length, get_crypto_connection(), i, MAX_NUM_SENDPACKET_TRIES, Crypto_Connection::status, and Crypto_Connection::temp_packet_num_sent.
Referenced by do_net_crypto().
{
    uint32_t i;
    //uint64_t temp_time = current_time_monotonic();
    for (i = 0; i < c->crypto_connections_length; ++i) {
        Crypto_Connection *conn = get_crypto_connection(c, i);
        if (conn == 0)
            return;
        if (conn->status == CRYPTO_CONN_NO_CONNECTION)
            continue;
        if (conn->status == CRYPTO_CONN_COOKIE_REQUESTING || conn->
      status == CRYPTO_CONN_HANDSHAKE_SENT
                || conn->status == CRYPTO_CONN_NOT_CONFIRMED) {
            if (conn->temp_packet_num_sent <
      MAX_NUM_SENDPACKET_TRIES)
                continue;
            connection_kill(c, i);
        }
        if (conn->status == CRYPTO_CONN_ESTABLISHED) {
            //TODO: add a timeout here?
        }
    }
}
void load_secret_key (Net_Crypto * c, const uint8_t * sk)
Definition at line 2405 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by messenger_load_state_callback(), and tox_new().
{
    memcpy(c->self_secret_key, sk, crypto_box_SECRETKEYBYTES);
    crypto_scalarmult_curve25519_base(c->self_public_key, c->
      self_secret_key);
}
_Bool max_speed_reached (Net_Crypto * c, int crypt_connection_id)
Definition at line 2188 of file net_crypto.c.
References reset_max_speed_reached().
Referenced by do_reqchunk_filecb().
{
    return reset_max_speed_reached(c, crypt_connection_id) != 0;
}
int nc_dht_pk_callback (Net_Crypto * c, int crypt_connection_id, void(*)(void *data, int32_t number, const uint8_t *dht_public_key) function, void * object, uint32_t number)
Definition at line 1961 of file net_crypto.c.
References Crypto_Connection::dht_pk_callback, Crypto_Connection::dht_pk_callback_number, Crypto_Connection::dht_pk_callback_object, and get_crypto_connection().
Referenced by friend_new_connection(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    conn->dht_pk_callback = function;
    conn->dht_pk_callback_object = object;
    conn->dht_pk_callback_number = number;
    return 0;
}
void new_connection_handler (Net_Crypto * c, int(*)(void *object, New_Connection *n_c) new_connection_callback, void * object)
Definition at line 1502 of file net_crypto.c.
References Net_Crypto::new_connection_callback, and Net_Crypto::new_connection_callback_object.
Referenced by new_friend_connections().
{
    c->new_connection_callback = new_connection_callback;
    c->new_connection_callback_object = object;
}
int new_crypto_connection (Net_Crypto * c, const uint8_t * real_public_key, const uint8_t * dht_public_key)
Definition at line 1623 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, COOKIE_REQUEST_LENGTH, Crypto_Connection::cookie_request_number, create_cookie_request(), create_crypto_connection(), CRYPTO_CONN_COOKIE_REQUESTING, CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, CRYPTO_MIN_QUEUE_LENGTH, CRYPTO_PACKET_MIN_RATE, DEFAULT_PING_CONNECTION, Crypto_Connection::dht_public_key, getcryptconnection_id(), kill_tcp_connection_to(), new_tcp_connection_to(), new_temp_packet(), Crypto_Connection::packet_send_rate, Crypto_Connection::packets_left, Crypto_Connection::public_key, random_64b(), random_nonce(), Crypto_Connection::rtt_time, Crypto_Connection::sent_nonce, Crypto_Connection::sessionpublic_key, Crypto_Connection::sessionsecret_key, Crypto_Connection::shared_key, Crypto_Connection::status, Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by friend_new_connection().
{
    int crypt_connection_id = getcryptconnection_id(c, real_public_key);
    if (crypt_connection_id != -1)
        return crypt_connection_id;
    crypt_connection_id = create_crypto_connection(c);
    if (crypt_connection_id == -1)
        return -1;
    Crypto_Connection *conn = &c->crypto_connections[crypt_connection_id
      ];
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&c->tcp_mutex);
    int connection_number_tcp = new_tcp_connection_to(c->
      tcp_c, dht_public_key, crypt_connection_id);
    pthread_mutex_unlock(&c->tcp_mutex);
    if (connection_number_tcp == -1)
        return -1;
    conn->connection_number_tcp = connection_number_tcp;
    memcpy(conn->public_key, real_public_key, crypto_box_PUBLICKEYBYTES);
    random_nonce(conn->sent_nonce);
    crypto_box_keypair(conn->sessionpublic_key, conn->
      sessionsecret_key);
    conn->status = CRYPTO_CONN_COOKIE_REQUESTING;
    conn->packet_send_rate = CRYPTO_PACKET_MIN_RATE;
    conn->packets_left = CRYPTO_MIN_QUEUE_LENGTH;
    conn->rtt_time = DEFAULT_PING_CONNECTION;
    memcpy(conn->dht_public_key, dht_public_key, crypto_box_PUBLICKEYBYTES);
    conn->cookie_request_number = random_64b();
    uint8_t cookie_request[COOKIE_REQUEST_LENGTH];
    if (create_cookie_request(c, cookie_request, conn->
      dht_public_key, conn->cookie_request_number,
                              conn->shared_key) != sizeof(cookie_request)
            || new_temp_packet(c, crypt_connection_id, cookie_request, sizeof(cookie_request
      )) != 0) {
        pthread_mutex_lock(&c->tcp_mutex);
        kill_tcp_connection_to(c->tcp_c, conn->
      connection_number_tcp);
        pthread_mutex_unlock(&c->tcp_mutex);
        conn->status = CRYPTO_CONN_NO_CONNECTION;
        return -1;
    }
    return crypt_connection_id;
}
void new_keys (Net_Crypto * c)
Definition at line 2386 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by new_net_crypto().
{
    crypto_box_keypair(c->self_public_key, c->self_secret_key);
}
Net_Crypto* new_net_crypto (DHT * dht, TCP_Proxy_Info * proxy_info)
Definition at line 2414 of file net_crypto.c.
References bs_list_init(), Net_Crypto::connections_mutex, create_recursive_mutex(), CRYPTO_SEND_PACKET_INTERVAL, Net_Crypto::current_sleep_time, Net_Crypto::dht, Messenger::dht, Net_Crypto::ip_port_list, kill_tcp_connections(), DHT::net, NET_PACKET_COOKIE_REQUEST, NET_PACKET_COOKIE_RESPONSE, NET_PACKET_CRYPTO_DATA, NET_PACKET_CRYPTO_HS, networking_registerhandler(), new_keys(), new_symmetric_key(), new_tcp_connections(), Net_Crypto::secret_symmetric_key, DHT::self_secret_key, set_oob_packet_tcp_connection_callback(), set_packet_tcp_connection_callback(), Net_Crypto::tcp_c, tcp_data_callback(), Net_Crypto::tcp_mutex, tcp_oob_callback(), udp_handle_cookie_request(), udp_handle_packet(), and unix_time_update().
Referenced by new_messenger(), and new_onions().
{
    unix_time_update();
    if (dht == NULL)
        return NULL;
    Net_Crypto *temp = calloc(1, sizeof(Net_Crypto));
    if (temp == NULL)
        return NULL;
    temp->tcp_c = new_tcp_connections(dht->
      self_secret_key, proxy_info);
    if (temp->tcp_c == NULL) {
        free(temp);
        return NULL;
    }
    set_packet_tcp_connection_callback(temp->
      tcp_c, &tcp_data_callback, temp);
    set_oob_packet_tcp_connection_callback(temp->
      tcp_c, &tcp_oob_callback, temp);
    if (create_recursive_mutex(&temp->tcp_mutex) != 0 ||
            pthread_mutex_init(&temp->connections_mutex, NULL) != 0) {
        kill_tcp_connections(temp->tcp_c);
        free(temp);
        return NULL;
    }
    temp->dht = dht;
    new_keys(temp);
    new_symmetric_key(temp->secret_symmetric_key);
    temp->current_sleep_time = CRYPTO_SEND_PACKET_INTERVAL;
    networking_registerhandler(dht->net,
      NET_PACKET_COOKIE_REQUEST, &udp_handle_cookie_request,
      temp);
    networking_registerhandler(dht->net,
      NET_PACKET_COOKIE_RESPONSE, &udp_handle_packet, temp);
    networking_registerhandler(dht->net,
      NET_PACKET_CRYPTO_HS, &udp_handle_packet, temp);
    networking_registerhandler(dht->net,
      NET_PACKET_CRYPTO_DATA, &udp_handle_packet, temp);
    bs_list_init(&temp->ip_port_list, sizeof(IP_Port), 8);
    return temp;
}
static int new_temp_packet (const Net_Crypto * c, int crypt_connection_id, const uint8_t * packet, uint16_t length) [static]
Definition at line 1003 of file net_crypto.c.
References get_crypto_connection(), MAX_CRYPTO_PACKET_SIZE, Crypto_Connection::temp_packet, Crypto_Connection::temp_packet_length, Crypto_Connection::temp_packet_num_sent, and Crypto_Connection::temp_packet_sent_time.
Referenced by create_send_handshake(), and new_crypto_connection().
{
    if (length == 0 || length > MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t *temp_packet = malloc(length);
    if (temp_packet == 0)
        return -1;
    if (conn->temp_packet)
        free(conn->temp_packet);
    memcpy(temp_packet, packet, length);
    conn->temp_packet = temp_packet;
    conn->temp_packet_length = length;
    conn->temp_packet_sent_time = 0;
    conn->temp_packet_num_sent = 0;
    return 0;
}
static uint32_t num_packets_array (const Packets_Array * array) [static]
START: Array Related functions
Definition at line 444 of file net_crypto.c.
References Packets_Array::buffer_end, and Packets_Array::buffer_start.
Referenced by add_data_end_of_buffer(), crypto_num_free_sendqueue_slots(), send_crypto_packets(), and send_requested_packets().
{
    return array->buffer_end - array->buffer_start;
}
static int open_cookie (uint8_t * bytes, const uint8_t * cookie, const uint8_t * encryption_key) [static]
Definition at line 117 of file net_crypto.c.
References COOKIE_CONTENTS_LENGTH, COOKIE_DATA_LENGTH, COOKIE_LENGTH, COOKIE_TIMEOUT, decrypt_data_symmetric(), and unix_time().
Referenced by handle_crypto_handshake().
{
    uint8_t contents[COOKIE_CONTENTS_LENGTH];
    int len = decrypt_data_symmetric(encryption_key, cookie, cookie +
      crypto_box_NONCEBYTES,
                                     COOKIE_LENGTH - crypto_box_NONCEBYTES, contents);
    if (len != sizeof(contents))
        return -1;
    uint64_t cookie_time;
    memcpy(&cookie_time, contents, sizeof(cookie_time));
    uint64_t temp_time = unix_time();
    if (cookie_time + COOKIE_TIMEOUT < temp_time || temp_time < cookie_time)
        return -1;
    memcpy(bytes, contents + sizeof(cookie_time), COOKIE_DATA_LENGTH);
    return 0;
}
static int64_t read_data_beg_buffer (Packets_Array * array, Packet_Data * data) [static]
Definition at line 527 of file net_crypto.c.
References Packets_Array::buffer, Packets_Array::buffer_end, Packets_Array::buffer_start, CRYPTO_PACKET_BUFFER_SIZE, and num.
Referenced by handle_data_packet_helper().
{
    if (array->buffer_end == array->buffer_start)
        return -1;
    uint32_t num = array->buffer_start %
      CRYPTO_PACKET_BUFFER_SIZE;
    if (!array->buffer[num])
        return -1;
    memcpy(data, array->buffer[num], sizeof(Packet_Data));
    uint32_t id = array->buffer_start;
    ++array->buffer_start;
    free(array->buffer[num]);
    array->buffer[num] = NULL;
    return id;
}
static int realloc_cryptoconnection (Net_Crypto * c, uint32_t num) [static]
Definition at line 1352 of file net_crypto.c.
References Net_Crypto::crypto_connections.
Referenced by create_crypto_connection(), and wipe_crypto_connection().
{
    if (num == 0) {
        free(c->crypto_connections);
        c->crypto_connections = NULL;
        return 0;
    }
    Crypto_Connection *newcrypto_connections = realloc(c->
      crypto_connections, num * sizeof(Crypto_Connection));
    if (newcrypto_connections == NULL)
        return -1;
    c->crypto_connections = newcrypto_connections;
    return 0;
}
static int reset_max_speed_reached (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 791 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, current_time_monotonic(), Packet_Data::data, get_crypto_connection(), get_data_pointer(), Packet_Data::length, Crypto_Connection::maximum_speed_reached, Crypto_Connection::recv_array, Crypto_Connection::send_array, send_data_packet_helper(), and Packet_Data::sent_time.
Referenced by max_speed_reached(), and send_lossless_packet().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    /* If last packet send failed, try to send packet again.
       If sending it fails we won't be able to send the new packet. */
    if (conn->maximum_speed_reached) {
        Packet_Data *dt = NULL;
        uint32_t packet_num = conn->send_array.buffer_end - 1;
        int ret = get_data_pointer(&conn->send_array, &dt, packet_num);
        uint8_t send_failed = 0;
        if (ret == 1) {
            if (!dt->sent_time) {
                if (send_data_packet_helper(c, crypt_connection_id, conn->
      recv_array.buffer_start, packet_num, dt->data,
                                            dt->length) != 0) {
                    send_failed = 1;
                } else {
                    dt->sent_time = current_time_monotonic();
                }
            }
        }
        if (!send_failed) {
            conn->maximum_speed_reached = 0;
        } else {
            return -1;
        }
    }
    return 0;
}
void save_keys (const Net_Crypto * c, uint8_t * keys)
Definition at line 2396 of file net_crypto.c.
References Net_Crypto::self_public_key, and Net_Crypto::self_secret_key.
Referenced by messenger_save().
{
    memcpy(keys, c->self_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(keys + crypto_box_PUBLICKEYBYTES, c->self_secret_key, crypto_box_SECRETKEYBYTES);
}
static void send_crypto_packets (Net_Crypto * c) [static]
Definition at line 2042 of file net_crypto.c.
References CONGESTION_EVENT_TIMEOUT, CONGESTION_QUEUE_ARRAY_SIZE, CRYPTO_CONN_ESTABLISHED, CRYPTO_CONN_NOT_CONFIRMED, Net_Crypto::crypto_connections_length, CRYPTO_MIN_QUEUE_LENGTH, CRYPTO_PACKET_MIN_RATE, CRYPTO_SEND_PACKET_INTERVAL, Net_Crypto::current_sleep_time, current_time_monotonic(), get_crypto_connection(), i, Crypto_Connection::last_congestion_event, Crypto_Connection::last_num_packets_sent, Crypto_Connection::last_packets_left_set, Crypto_Connection::last_request_packet_sent, Crypto_Connection::last_sendqueue_counter, Crypto_Connection::last_sendqueue_size, num_packets_array(), Crypto_Connection::packet_counter, PACKET_COUNTER_AVERAGE_INTERVAL, Crypto_Connection::packet_counter_set, Crypto_Connection::packet_recv_rate, PACKET_RESEND_MULTIPLIER, Crypto_Connection::packet_send_rate, Crypto_Connection::packets_left, Crypto_Connection::packets_sent, Crypto_Connection::recv_array, REQUEST_PACKETS_COMPARE_CONSTANT, Crypto_Connection::send_array, send_request_packet(), send_requested_packets(), send_temp_packet(), Crypto_Connection::status, and Crypto_Connection::temp_packet_sent_time.
Referenced by do_net_crypto().
{
    uint32_t i;
    uint64_t temp_time = current_time_monotonic();
    double total_send_rate = 0;
    uint32_t peak_request_packet_interval = ~0;
    for (i = 0; i < c->crypto_connections_length; ++i) {
        Crypto_Connection *conn = get_crypto_connection(c, i);
        if (conn == 0)
            return;
        if (CRYPTO_SEND_PACKET_INTERVAL + conn->
      temp_packet_sent_time < temp_time) {
            send_temp_packet(c, i);
        }
        if ((conn->status == CRYPTO_CONN_NOT_CONFIRMED || conn->
      status == CRYPTO_CONN_ESTABLISHED)
                && (CRYPTO_SEND_PACKET_INTERVAL + conn->
      last_request_packet_sent) < temp_time) {
            if (send_request_packet(c, i) == 0) {
                conn->last_request_packet_sent = temp_time;
            }
        }
        if (conn->status == CRYPTO_CONN_ESTABLISHED) {
            if (conn->packet_recv_rate > CRYPTO_PACKET_MIN_RATE) {
                double request_packet_interval = (
      REQUEST_PACKETS_COMPARE_CONSTANT / (((double)
      num_packets_array(
                                                      &conn->recv_array) + 1.0) / (conn->
      packet_recv_rate + 1.0)));
                if (temp_time - conn->last_request_packet_sent > (uint64_t)
      request_packet_interval) {
                    if (send_request_packet(c, i) == 0) {
                        conn->last_request_packet_sent = temp_time;
                    }
                }
                if (request_packet_interval < peak_request_packet_interval) {
                    peak_request_packet_interval = request_packet_interval;
                }
            }
            if ((PACKET_COUNTER_AVERAGE_INTERVAL + conn->
      packet_counter_set) < temp_time) {
                double dt = temp_time - conn->packet_counter_set;
                conn->packet_recv_rate = (double)conn->
      packet_counter / (dt / 1000.0);
                conn->packet_counter = 0;
                conn->packet_counter_set = temp_time;
                uint32_t packets_sent = conn->packets_sent;
                conn->packets_sent = 0;
                /* conjestion control
                    calculate a new value of conn->packet_send_rate based on some data
                 */
                unsigned int pos = conn->last_sendqueue_counter %
      CONGESTION_QUEUE_ARRAY_SIZE;
                conn->last_sendqueue_size[pos] =
      num_packets_array(&conn->send_array);
                ++conn->last_sendqueue_counter;
                unsigned int j;
                long signed int sum = 0;
                sum = (long signed int)conn->last_sendqueue_size[(pos) %
      CONGESTION_QUEUE_ARRAY_SIZE] -
                      (long signed int)conn->last_sendqueue_size[(pos - (
      CONGESTION_QUEUE_ARRAY_SIZE - 1)) %
      CONGESTION_QUEUE_ARRAY_SIZE];
                conn->last_num_packets_sent[pos] = packets_sent;
                long signed int total_sent = 0;
                for (j = 0; j < CONGESTION_QUEUE_ARRAY_SIZE; ++j) {
                    total_sent += conn->last_num_packets_sent[j];
                }
                total_sent -= sum;
                double min_speed = 1000.0 * (((double)(total_sent)) / ((double)(
      CONGESTION_QUEUE_ARRAY_SIZE) *
                                             PACKET_COUNTER_AVERAGE_INTERVAL
      ));
                if (conn->last_congestion_event +
      CONGESTION_EVENT_TIMEOUT < temp_time) {
                    conn->packet_send_rate = min_speed * 1.25;
                } else {
                    conn->packet_send_rate = min_speed;
                }
                if (conn->packet_send_rate <
      CRYPTO_PACKET_MIN_RATE) {
                    conn->packet_send_rate =
      CRYPTO_PACKET_MIN_RATE;
                }
            }
            if (conn->last_packets_left_set == 0) {
                conn->last_packets_left_set = temp_time;
                conn->packets_left = CRYPTO_MIN_QUEUE_LENGTH;
            } else if (((uint64_t)((1000.0 / conn->packet_send_rate) + 0.5) + conn->
      last_packets_left_set) < temp_time) {
                uint32_t num_packets = conn->packet_send_rate * ((double)(temp_time - conn
      ->last_packets_left_set) / 1000.0) + 0.5;
                if (conn->packets_left > num_packets * 4 +
      CRYPTO_MIN_QUEUE_LENGTH) {
                    conn->packets_left = num_packets * 4 +
      CRYPTO_MIN_QUEUE_LENGTH;
                } else {
                    conn->packets_left += num_packets;
                }
                conn->last_packets_left_set = temp_time;
            }
            int ret = send_requested_packets(c, i, conn->
      packets_left * PACKET_RESEND_MULTIPLIER);
            if (ret != -1) {
                if ((unsigned int)ret < conn->packets_left) {
                    conn->packets_left -= ret;
                } else {
                    conn->last_congestion_event = temp_time;
                    conn->packets_left = 0;
                }
            }
            if (conn->packet_send_rate > CRYPTO_PACKET_MIN_RATE * 1.5
      ) {
                total_send_rate += conn->packet_send_rate;
            }
        }
    }
    c->current_sleep_time = ~0;
    uint32_t sleep_time = peak_request_packet_interval;
    if (c->current_sleep_time > sleep_time) {
        c->current_sleep_time = sleep_time;
    }
    if (total_send_rate > CRYPTO_PACKET_MIN_RATE) {
        sleep_time = (1000.0 / total_send_rate);
        if (c->current_sleep_time > sleep_time) {
            c->current_sleep_time = sleep_time + 1;
        }
    }
    sleep_time = CRYPTO_SEND_PACKET_INTERVAL;
    if (c->current_sleep_time > sleep_time) {
        c->current_sleep_time = sleep_time;
    }
}
static int send_data_packet (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length) [static]
Definition at line 741 of file net_crypto.c.
References encrypt_data_symmetric(), get_crypto_connection(), increment_nonce(), MAX_CRYPTO_PACKET_SIZE, Crypto_Connection::mutex, NET_PACKET_CRYPTO_DATA, send_packet_to(), Crypto_Connection::sent_nonce, and Crypto_Connection::shared_key.
Referenced by send_data_packet_helper().
{
    if (length == 0 || length + (1 + sizeof(uint16_t) + crypto_box_MACBYTES) >
      MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&conn->mutex);
    uint8_t packet[1 + sizeof(uint16_t) + length + crypto_box_MACBYTES];
    packet[0] = NET_PACKET_CRYPTO_DATA;
    memcpy(packet + 1, conn->sent_nonce + (crypto_box_NONCEBYTES - sizeof(uint16_t)), sizeof(
      uint16_t));
    int len = encrypt_data_symmetric(conn->shared_key, conn->
      sent_nonce, data, length, packet + 1 + sizeof(uint16_t));
    if (len + 1 + sizeof(uint16_t) != sizeof(packet)) {
        pthread_mutex_unlock(&conn->mutex);
        return -1;
    }
    increment_nonce(conn->sent_nonce);
    pthread_mutex_unlock(&conn->mutex);
    return send_packet_to(c, crypt_connection_id, packet, sizeof(packet));
}
static int send_data_packet_helper (Net_Crypto * c, int crypt_connection_id, uint32_t buffer_start, uint32_t num, const uint8_t * data, uint16_t length) [static]
Definition at line 773 of file net_crypto.c.
References CRYPTO_MAX_PADDING, MAX_CRYPTO_DATA_SIZE, PACKET_ID_PADDING, and send_data_packet().
Referenced by reset_max_speed_reached(), send_kill_packet(), send_lossless_packet(), send_lossy_cryptpacket(), send_request_packet(), and send_requested_packets().
{
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -1;
    num = htonl(num);
    buffer_start = htonl(buffer_start);
    uint16_t padding_length = (MAX_CRYPTO_DATA_SIZE - length) %
      CRYPTO_MAX_PADDING;
    uint8_t packet[sizeof(uint32_t) + sizeof(uint32_t) + padding_length + length];
    memcpy(packet, &buffer_start, sizeof(uint32_t));
    memcpy(packet + sizeof(uint32_t), &num, sizeof(uint32_t));
    memset(packet + (sizeof(uint32_t) * 2), PACKET_ID_PADDING, padding_length);
    memcpy(packet + (sizeof(uint32_t) * 2) + padding_length, data, length);
    return send_data_packet(c, crypt_connection_id, packet, sizeof(packet));
}
static int send_kill_packet (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 1107 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, get_crypto_connection(), PACKET_ID_KILL, Crypto_Connection::recv_array, Crypto_Connection::send_array, and send_data_packet_helper().
Referenced by crypto_kill().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t kill_packet = PACKET_ID_KILL;
    return send_data_packet_helper(c, crypt_connection_id, conn->
      recv_array.buffer_start, conn->send_array.
      buffer_end,
                                   &kill_packet, sizeof(kill_packet));
}
static int64_t send_lossless_packet (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length, uint8_t congestion_control) [static]
Definition at line 831 of file net_crypto.c.
References add_data_end_of_buffer(), Packets_Array::buffer_start, current_time_monotonic(), Packet_Data::data, get_crypto_connection(), get_data_pointer(), Packet_Data::length, LOGGER_ERROR, MAX_CRYPTO_DATA_SIZE, Crypto_Connection::maximum_speed_reached, Crypto_Connection::mutex, Crypto_Connection::recv_array, reset_max_speed_reached(), Crypto_Connection::send_array, send_data_packet_helper(), and Packet_Data::sent_time.
Referenced by write_cryptpacket().
{
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    /* If last packet send failed, try to send packet again.
       If sending it fails we won't be able to send the new packet. */
    reset_max_speed_reached(c, crypt_connection_id);
    if (conn->maximum_speed_reached && congestion_control) {
        return -1;
    }
    Packet_Data dt;
    dt.sent_time = 0;
    dt.length = length;
    memcpy(dt.data, data, length);
    pthread_mutex_lock(&conn->mutex);
    int64_t packet_num = add_data_end_of_buffer(&conn->
      send_array, &dt);
    pthread_mutex_unlock(&conn->mutex);
    if (packet_num == -1)
        return -1;
    if (!congestion_control && conn->maximum_speed_reached) {
        return packet_num;
    }
    if (send_data_packet_helper(c, crypt_connection_id, conn->
      recv_array.buffer_start, packet_num, data, length) == 0) {
        Packet_Data *dt1 = NULL;
        if (get_data_pointer(&conn->send_array, &dt1, packet_num) == 1)
            dt1->sent_time = current_time_monotonic();
    } else {
        conn->maximum_speed_reached = 1;
        LOGGER_ERROR("send_data_packet failed\n");
    }
    return packet_num;
}
int send_lossy_cryptpacket (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length)
Definition at line 2284 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, Net_Crypto::connection_use_counter, Net_Crypto::connections_mutex, get_crypto_connection(), MAX_CRYPTO_DATA_SIZE, Crypto_Connection::mutex, PACKET_ID_LOSSY_RANGE_SIZE, PACKET_ID_LOSSY_RANGE_START, Crypto_Connection::recv_array, Crypto_Connection::send_array, and send_data_packet_helper().
Referenced by send_custom_lossy_packet(), and send_lossy_group_peer().
{
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -1;
    if (data[0] < PACKET_ID_LOSSY_RANGE_START)
        return -1;
    if (data[0] >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_ID_LOSSY_RANGE_SIZE))
        return -1;
    pthread_mutex_lock(&c->connections_mutex);
    ++c->connection_use_counter;
    pthread_mutex_unlock(&c->connections_mutex);
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    int ret = -1;
    if (conn) {
        pthread_mutex_lock(&conn->mutex);
        uint32_t buffer_start = conn->recv_array.buffer_start;
        uint32_t buffer_end = conn->send_array.buffer_end;
        pthread_mutex_unlock(&conn->mutex);
        ret = send_data_packet_helper(c, crypt_connection_id, buffer_start,
      buffer_end, data, length);
    }
    pthread_mutex_lock(&c->connections_mutex);
    --c->connection_use_counter;
    pthread_mutex_unlock(&c->connections_mutex);
    return ret;
}
static int send_packet_to (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length) [static]
Definition at line 392 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, crypto_connection_status(), Net_Crypto::dht, IP::family, get_crypto_connection(), IP_Port::ip, Crypto_Connection::ip_port, Crypto_Connection::mutex, DHT::net, NET_PACKET_COOKIE_REQUEST, NET_PACKET_CRYPTO_HS, send_packet_tcp_connection(), sendpacket(), Net_Crypto::tcp_c, and Net_Crypto::tcp_mutex.
Referenced by send_data_packet(), and send_temp_packet().
{
//TODO TCP, etc...
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    int direct_send_attempt = 0;
    pthread_mutex_lock(&conn->mutex);
    //TODO: on bad networks, direct connections might not last indefinitely.
    if (conn->ip_port.ip.family != 0) {
        _Bool direct_connected = 0;
        crypto_connection_status(c, crypt_connection_id, &direct_connected, NULL);
        if (direct_connected) {
            if ((uint32_t)sendpacket(c->dht->net, conn->ip_port,
      data, length) == length) {
                pthread_mutex_unlock(&conn->mutex);
                return 0;
            } else {
                pthread_mutex_unlock(&conn->mutex);
                return -1;
            }
        }
        //TODO: a better way of sending packets directly to confirm the others ip.
        if (length < 96 || data[0] == NET_PACKET_COOKIE_REQUEST ||
      data[0] == NET_PACKET_CRYPTO_HS) {
            if ((uint32_t)sendpacket(c->dht->net, conn->ip_port,
      data, length) == length)
                direct_send_attempt = 1;
        }
    }
    pthread_mutex_unlock(&conn->mutex);
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = send_packet_tcp_connection(c->tcp_c, conn->
      connection_number_tcp, data, length);
    pthread_mutex_unlock(&c->tcp_mutex);
    if (ret == 0 || direct_send_attempt) {
        return 0;
    }
    return -1;
}
static int send_request_packet (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 934 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, make-funny-savefile::data, generate_request_packet(), get_crypto_connection(), MAX_CRYPTO_DATA_SIZE, Crypto_Connection::recv_array, Crypto_Connection::send_array, and send_data_packet_helper().
Referenced by send_crypto_packets().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint8_t data[MAX_CRYPTO_DATA_SIZE];
    int len = generate_request_packet(data, sizeof(data), &conn->
      recv_array);
    if (len == -1)
        return -1;
    return send_data_packet_helper(c, crypt_connection_id, conn->
      recv_array.buffer_start, conn->send_array.
      buffer_end, data,
                                   len);
}
static int send_requested_packets (Net_Crypto * c, int crypt_connection_id, uint32_t max_num) [static]
Definition at line 956 of file net_crypto.c.
References Packets_Array::buffer_start, current_time_monotonic(), Packet_Data::data, get_crypto_connection(), get_data_pointer(), i, Packet_Data::length, num_packets_array(), Crypto_Connection::recv_array, Crypto_Connection::send_array, send_data_packet_helper(), and Packet_Data::sent_time.
Referenced by send_crypto_packets().
{
    if (max_num == 0)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    uint64_t temp_time = current_time_monotonic();
    uint32_t i, num_sent = 0, array_size = num_packets_array(&conn->
      send_array);
    for (i = 0; i < array_size; ++i) {
        Packet_Data *dt;
        uint32_t packet_num = (i + conn->send_array.buffer_start);
        int ret = get_data_pointer(&conn->send_array, &dt, packet_num);
        if (ret == -1) {
            return -1;
        } else if (ret == 0) {
            continue;
        }
        if (dt->sent_time) {
            continue;
        }
        if (send_data_packet_helper(c, crypt_connection_id, conn->
      recv_array.buffer_start, packet_num, dt->data,
                                    dt->length) == 0) {
            dt->sent_time = temp_time;
            ++num_sent;
        }
        if (num_sent >= max_num)
            break;
    }
    return num_sent;
}
int send_tcp_onion_request (Net_Crypto * c, unsigned int tcp_connections_number, const uint8_t * data, uint16_t length)
Definition at line 1824 of file net_crypto.c.
References Net_Crypto::tcp_c, Net_Crypto::tcp_mutex, and tcp_send_onion_request().
Referenced by send_onion_packet_tcp_udp().
{
    pthread_mutex_lock(&c->tcp_mutex);
    int ret = tcp_send_onion_request(c->tcp_c, tcp_connections_number,
      data, length);
    pthread_mutex_unlock(&c->tcp_mutex);
    return ret;
}
static int send_temp_packet (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 1057 of file net_crypto.c.
References current_time_monotonic(), get_crypto_connection(), send_packet_to(), Crypto_Connection::temp_packet, Crypto_Connection::temp_packet_length, Crypto_Connection::temp_packet_num_sent, and Crypto_Connection::temp_packet_sent_time.
Referenced by create_send_handshake(), and send_crypto_packets().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (!conn->temp_packet)
        return -1;
    if (send_packet_to(c, crypt_connection_id, conn->temp_packet, conn->
      temp_packet_length) != 0)
        return -1;
    conn->temp_packet_sent_time = current_time_monotonic();
    ++conn->temp_packet_num_sent;
    return 0;
}
static int set_buffer_end (Packets_Array * array, uint32_t number) [static]
Definition at line 594 of file net_crypto.c.
References Packets_Array::buffer_end, Packets_Array::buffer_start, and CRYPTO_PACKET_BUFFER_SIZE.
Referenced by handle_data_packet_helper().
{
    if ((number - array->buffer_start) > CRYPTO_PACKET_BUFFER_SIZE)
        return -1;
    if ((number - array->buffer_end) > CRYPTO_PACKET_BUFFER_SIZE)
        return -1;
    array->buffer_end = number;
    return 0;
}
int set_direct_ip_port (Net_Crypto * c, int crypt_connection_id, IP_Port ip_port, _Bool connected)
Definition at line 1680 of file net_crypto.c.
References bs_list_add(), bs_list_remove(), Crypto_Connection::direct_lastrecv_time, IP::family, get_crypto_connection(), IP_Port::ip, Crypto_Connection::ip_port, Net_Crypto::ip_port_list, ipport_equal(), LAN_ip(), UDP_DIRECT_TIMEOUT, and unix_time().
Referenced by dht_ip_callback(), do_friend_connections(), and handle_new_connections().
{
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    if (!ipport_equal(&ip_port, &conn->ip_port)) {
        if ((UDP_DIRECT_TIMEOUT + conn->direct_lastrecv_time) >
      unix_time()) {
            /* We already know a LAN ip, no need to switch. */
            if (LAN_ip(conn->ip_port.ip) == 0)
                return -1;
            /* Prefer ipv6. */
            if (conn->ip_port.ip.family == AF_INET6 && ip_port.ip.
      family == AF_INET)
                return -1;
        }
        if (bs_list_add(&c->ip_port_list, (uint8_t *)&ip_port, crypt_connection_id))
       {
            bs_list_remove(&c->ip_port_list, (uint8_t *)&conn->
      ip_port, crypt_connection_id);
            conn->ip_port = ip_port;
            if (connected) {
                conn->direct_lastrecv_time = unix_time();
            } else {
                conn->direct_lastrecv_time = 0;
            }
            return 0;
        }
    }
    return -1;
}
static int tcp_data_callback (void * object, int id, const uint8_t * data, uint16_t length) [static]
Definition at line 1719 of file net_crypto.c.
References Crypto_Connection::connection_number_tcp, get_crypto_connection(), handle_packet_connection(), MAX_CRYPTO_PACKET_SIZE, NET_PACKET_COOKIE_REQUEST, tcp_handle_cookie_request(), and Net_Crypto::tcp_mutex.
Referenced by new_net_crypto().
{
    if (length == 0 || length > MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Net_Crypto *c = object;
    Crypto_Connection *conn = get_crypto_connection(c, id);
    if (conn == 0)
        return -1;
    if (data[0] == NET_PACKET_COOKIE_REQUEST) {
        return tcp_handle_cookie_request(c, conn->
      connection_number_tcp, data, length);
    }
    pthread_mutex_unlock(&c->tcp_mutex);
    int ret = handle_packet_connection(c, id, data, length);
    pthread_mutex_lock(&c->tcp_mutex);
    if (ret != 0)
        return -1;
    //TODO detect and kill bad TCP connections.
    return 0;
}
static int tcp_handle_cookie_request (Net_Crypto * c, int connections_number, const uint8_t * packet, uint16_t length) [static]
Definition at line 217 of file net_crypto.c.
References COOKIE_REQUEST_PLAIN_LENGTH, COOKIE_RESPONSE_LENGTH, create_cookie_response(), make-funny-savefile::data, handle_cookie_request(), send_packet_tcp_connection(), and Net_Crypto::tcp_c.
Referenced by tcp_data_callback().
{
    uint8_t request_plain[COOKIE_REQUEST_PLAIN_LENGTH];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    uint8_t dht_public_key[crypto_box_PUBLICKEYBYTES];
    if (handle_cookie_request(c, request_plain, shared_key, dht_public_key, packet,
      length) != 0)
        return -1;
    uint8_t data[COOKIE_RESPONSE_LENGTH];
    if (create_cookie_response(c, data, request_plain, shared_key, dht_public_key) !=
       sizeof(data))
        return -1;
    int ret = send_packet_tcp_connection(c->tcp_c, connections_number, data,
       sizeof(data));
    return ret;
}
static int tcp_oob_callback (void * object, const uint8_t * public_key, unsigned int tcp_connections_number, const uint8_t * data, uint16_t length) [static]
Definition at line 1746 of file net_crypto.c.
References IP::family, handle_new_connection_handshake(), IP_Port::ip, IP::ip6, MAX_CRYPTO_PACKET_SIZE, NET_PACKET_COOKIE_REQUEST, NET_PACKET_CRYPTO_HS, IP_Port::port, TCP_FAMILY, tcp_oob_handle_cookie_request(), and IP6::uint32.
Referenced by new_net_crypto().
{
    if (length == 0 || length > MAX_CRYPTO_PACKET_SIZE)
        return -1;
    Net_Crypto *c = object;
    if (data[0] == NET_PACKET_COOKIE_REQUEST) {
        return tcp_oob_handle_cookie_request(c, tcp_connections_number,
      public_key, data, length);
    } else if (data[0] == NET_PACKET_CRYPTO_HS) {
        IP_Port source;
        source.port = 0;
        source.ip.family = TCP_FAMILY;
        source.ip.ip6.uint32[0] = tcp_connections_number;
        if (handle_new_connection_handshake(c, source,
      data, length) != 0)
            return -1;
        return 0;
    } else {
        return -1;
    }
}
static int tcp_oob_handle_cookie_request (const Net_Crypto * c, unsigned int tcp_connections_number, const uint8_t * dht_public_key, const uint8_t * packet, uint16_t length) [static]
Definition at line 237 of file net_crypto.c.
References COOKIE_REQUEST_PLAIN_LENGTH, COOKIE_RESPONSE_LENGTH, create_cookie_response(), make-funny-savefile::data, handle_cookie_request(), Net_Crypto::tcp_c, and tcp_send_oob_packet().
Referenced by tcp_oob_callback().
{
    uint8_t request_plain[COOKIE_REQUEST_PLAIN_LENGTH];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    uint8_t dht_public_key_temp[crypto_box_PUBLICKEYBYTES];
    if (handle_cookie_request(c, request_plain, shared_key, dht_public_key_temp,
      packet, length) != 0)
        return -1;
    if (memcmp(dht_public_key, dht_public_key_temp, crypto_box_PUBLICKEYBYTES) != 0)
        return -1;
    uint8_t data[COOKIE_RESPONSE_LENGTH];
    if (create_cookie_response(c, data, request_plain, shared_key, dht_public_key) !=
       sizeof(data))
        return -1;
    int ret = tcp_send_oob_packet(c->tcp_c, tcp_connections_number, dht_public_key,
       data, sizeof(data));
    return ret;
}
static int udp_handle_cookie_request (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 194 of file net_crypto.c.
References COOKIE_REQUEST_PLAIN_LENGTH, COOKIE_RESPONSE_LENGTH, create_cookie_response(), make-funny-savefile::data, Net_Crypto::dht, handle_cookie_request(), DHT::net, and sendpacket().
Referenced by new_net_crypto().
{
    Net_Crypto *c = object;
    uint8_t request_plain[COOKIE_REQUEST_PLAIN_LENGTH];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    uint8_t dht_public_key[crypto_box_PUBLICKEYBYTES];
    if (handle_cookie_request(c, request_plain, shared_key, dht_public_key, packet,
      length) != 0)
        return 1;
    uint8_t data[COOKIE_RESPONSE_LENGTH];
    if (create_cookie_response(c, data, request_plain, shared_key, dht_public_key) !=
       sizeof(data))
        return 1;
    if ((uint32_t)sendpacket(c->dht->net, source, data, sizeof(data)) != sizeof(data))
        return 1;
    return 0;
}
static int udp_handle_packet (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 1995 of file net_crypto.c.
References crypto_id_ip_port(), Crypto_Connection::direct_lastrecv_time, get_crypto_connection(), handle_new_connection_handshake(), handle_packet_connection(), MAX_CRYPTO_PACKET_SIZE, Crypto_Connection::mutex, NET_PACKET_CRYPTO_HS, and unix_time().
Referenced by new_net_crypto().
{
    if (length <= CRYPTO_MIN_PACKET_SIZE || length > MAX_CRYPTO_PACKET_SIZE)
        return 1;
    Net_Crypto *c = object;
    int crypt_connection_id = crypto_id_ip_port(c, source);
    if (crypt_connection_id == -1) {
        if (packet[0] != NET_PACKET_CRYPTO_HS)
            return 1;
        if (handle_new_connection_handshake(c, source, packet, length) != 0)
            return 1;
        return 0;
    }
    if (handle_packet_connection(c, crypt_connection_id, packet, length) != 0)
        return 1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    pthread_mutex_lock(&conn->mutex);
    conn->direct_lastrecv_time = unix_time();
    pthread_mutex_unlock(&conn->mutex);
    return 0;
}
static int wipe_crypto_connection (Net_Crypto * c, int crypt_connection_id) [static]
Definition at line 1416 of file net_crypto.c.
References crypt_connection_id_not_valid(), CRYPTO_CONN_NO_CONNECTION, Net_Crypto::crypto_connections, Net_Crypto::crypto_connections_length, i, Crypto_Connection::mutex, realloc_cryptoconnection(), and Crypto_Connection::status.
Referenced by crypto_kill().
{
    if (crypt_connection_id_not_valid(c, crypt_connection_id))
        return -1;
    uint32_t i;
    /* Keep mutex, only destroy it when connection is realloced out. */
    pthread_mutex_t mutex = c->crypto_connections[crypt_connection_id].
      mutex;
    memset(&(c->crypto_connections[crypt_connection_id]), 0 , sizeof(
      Crypto_Connection));
    c->crypto_connections[crypt_connection_id].mutex = mutex;
    for (i = c->crypto_connections_length; i != 0; --i) {
        if (c->crypto_connections[i - 1].status ==
      CRYPTO_CONN_NO_CONNECTION) {
            pthread_mutex_destroy(&c->crypto_connections[i - 1].
      mutex);
        } else {
            break;
        }
    }
    if (c->crypto_connections_length != i) {
        c->crypto_connections_length = i;
        realloc_cryptoconnection(c, c->
      crypto_connections_length);
    }
    return 0;
}
int64_t write_cryptpacket (Net_Crypto * c, int crypt_connection_id, const uint8_t * data, uint16_t length, uint8_t congestion_control)
Definition at line 2219 of file net_crypto.c.
References CRYPTO_CONN_ESTABLISHED, CRYPTO_RESERVED_PACKETS, get_crypto_connection(), PACKET_ID_LOSSY_RANGE_START, Crypto_Connection::packets_left, Crypto_Connection::packets_sent, send_lossless_packet(), and Crypto_Connection::status.
Referenced by m_send_message_generic(), send_custom_lossless_packet(), send_file_data_packet(), send_friend_request_packet(), send_offline_packet(), send_online_packet(), send_packet_group_peer(), send_packet_online(), send_ping(), send_relays(), and write_cryptpacket_id().
{
    if (length == 0)
        return -1;
    if (data[0] < CRYPTO_RESERVED_PACKETS)
        return -1;
    if (data[0] >= PACKET_ID_LOSSY_RANGE_START)
        return -1;
    Crypto_Connection *conn = get_crypto_connection(c,
      crypt_connection_id);
    if (conn == 0)
        return -1;
    if (conn->status != CRYPTO_CONN_ESTABLISHED)
        return -1;
    if (congestion_control && conn->packets_left == 0)
        return -1;
    int64_t ret = send_lossless_packet(c, crypt_connection_id,
      data, length, congestion_control);
    if (ret == -1)
        return -1;
    if (congestion_control) {
        --conn->packets_left;
        conn->packets_sent++;
    }
    return ret;
}