toxcore/TCP_client.c File Reference
#include `TCP_client.h`
*
#include <sys/ioctl.h>
*
#include `util.h`
*
Functions
static int connect_sock_to (sock_t sock, IP_Port ip_port, TCP_Proxy_Info *proxy_info)
static int proxy_http_generate_connection_request (TCP_Client_Connection *TCP_conn)
static int proxy_http_read_connection_response (TCP_Client_Connection *TCP_conn)
static void proxy_socks5_generate_handshake (TCP_Client_Connection *TCP_conn)
static int socks5_read_handshake_response (TCP_Client_Connection *TCP_conn)
static void proxy_socks5_generate_connection_request (TCP_Client_Connection *TCP_conn)
static int proxy_socks5_read_connection_response (TCP_Client_Connection *TCP_conn)
static int generate_handshake (TCP_Client_Connection *TCP_conn)
static int handle_handshake (TCP_Client_Connection *TCP_conn, const uint8_t *data)
static int send_pending_data_nonpriority (TCP_Client_Connection *con)
static int send_pending_data (TCP_Client_Connection *con)
static _Bool add_priority (TCP_Client_Connection *con, const uint8_t *packet, uint16_t size, uint16_t sent)
static void wipe_priority_list (TCP_Client_Connection *con)
static int write_packet_TCP_secure_connection (TCP_Client_Connection *con, const uint8_t *data, uint16_t length, _Bool priority)
int send_routing_request (TCP_Client_Connection *con, uint8_t *public_key)
void routing_response_handler (TCP_Client_Connection *con, int(*response_callback)(void *object, uint8_t connection_id, const uint8_t *public_key), void *object)
void routing_status_handler (TCP_Client_Connection *con, int(*status_callback)(void *object, uint32_t number, uint8_t connection_id, uint8_t status), void *object)
static int send_ping_response (TCP_Client_Connection *con)
static int send_ping_request (TCP_Client_Connection *con)
int send_data (TCP_Client_Connection *con, uint8_t con_id, const uint8_t *data, uint16_t length)
int send_oob_packet (TCP_Client_Connection *con, const uint8_t *public_key, const uint8_t *data, uint16_t length)
int set_tcp_connection_number (TCP_Client_Connection *con, uint8_t con_id, uint32_t number)
void routing_data_handler (TCP_Client_Connection *con, int(*data_callback)(void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length), void *object)
void oob_data_handler (TCP_Client_Connection *con, int(*oob_data_callback)(void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length), void *object)
static int send_disconnect_notification (TCP_Client_Connection *con, uint8_t id)
int send_disconnect_request (TCP_Client_Connection *con, uint8_t con_id)
int send_onion_request (TCP_Client_Connection *con, const uint8_t *data, uint16_t length)
void onion_response_handler (TCP_Client_Connection *con, int(*onion_callback)(void *object, const uint8_t *data, uint16_t length), void *object)
TCP_Client_Connection * new_TCP_connection (IP_Port ip_port, const uint8_t *public_key, const uint8_t *self_public_key, const uint8_t *self_secret_key, TCP_Proxy_Info *proxy_info)
static int handle_TCP_packet (TCP_Client_Connection *conn, const uint8_t *data, uint16_t length)
static int do_confirmed_TCP (TCP_Client_Connection *conn)
void do_TCP_connection (TCP_Client_Connection *TCP_connection)
void kill_TCP_connection (TCP_Client_Connection *TCP_connection)
Function Documentation
static _Bool add_priority (TCP_Client_Connection * con, const uint8_t * packet, uint16_t size, uint16_t sent) [static]
Definition at line 325 of file TCP_client.c.
References TCP_Priority_List::next, TCP_Client_Connection::priority_queue_end, and TCP_Client_Connection::priority_queue_start.
Referenced by write_packet_TCP_secure_connection().
{
    TCP_Priority_List *p = con->priority_queue_end, *new;
    new = malloc(sizeof(TCP_Priority_List) + size);
    if (!new) {
        return 0;
    }
    new->next = NULL;
    new->size = size;
    new->sent = sent;
    memcpy(new->data, packet, size);
    if (p) {
        p->next = new;
    } else {
        con->priority_queue_start = new;
    }
    con->priority_queue_end = new;
    return 1;
}
static int connect_sock_to (sock_t sock, IP_Port ip_port, TCP_Proxy_Info * proxy_info) [static]
Definition at line 38 of file TCP_client.c.
References IP::family, IP6::in6_addr, IP4::in_addr, IP_Port::ip, IP::ip4, IP::ip6, TCP_Proxy_Info::ip_port, IP_Port::port, TCP_Proxy_Info::proxy_type, and TCP_PROXY_NONE.
Referenced by new_TCP_connection().
{
    if (proxy_info->proxy_type != TCP_PROXY_NONE) {
        ip_port = proxy_info->ip_port;
    }
    struct sockaddr_storage addr = {0};
    size_t addrsize;
    if (ip_port.ip.family == AF_INET) {
        struct sockaddr_in *addr4 = (struct sockaddr_in *)&addr;
        addrsize = sizeof(struct sockaddr_in);
        addr4->sin_family = AF_INET;
        addr4->sin_addr = ip_port.ip.ip4.in_addr;
        addr4->sin_port = ip_port.port;
    } else if (ip_port.ip.family == AF_INET6) {
        struct sockaddr_in6 *addr6 = (struct sockaddr_in6 *)&addr;
        addrsize = sizeof(struct sockaddr_in6);
        addr6->sin6_family = AF_INET6;
        addr6->sin6_addr = ip_port.ip.ip6.in6_addr;
        addr6->sin6_port = ip_port.port;
    } else {
        return 0;
    }
    /* nonblocking socket, connect will never return success */
    connect(sock, (struct sockaddr *)&addr, addrsize);
    return 1;
}
static int do_confirmed_TCP (TCP_Client_Connection * conn) [static]
Definition at line 827 of file TCP_client.c.
References handle_TCP_packet(), is_timeout(), TCP_Client_Connection::last_pinged, MAX_PACKET_SIZE, TCP_Client_Connection::next_packet_length, TCP_Client_Connection::ping_id, TCP_Client_Connection::ping_request_id, random_64b(), read_packet_TCP_secure_connection(), TCP_Client_Connection::recv_nonce, send_pending_data(), send_ping_request(), send_ping_response(), TCP_Client_Connection::shared_key, TCP_Client_Connection::sock, TCP_Client_Connection::status, TCP_CLIENT_DISCONNECTED, TCP_PING_FREQUENCY, TCP_PING_TIMEOUT, and unix_time().
Referenced by do_TCP_connection().
{
    send_pending_data(conn);
    send_ping_response(conn);
    send_ping_request(conn);
    uint8_t packet[MAX_PACKET_SIZE];
    int len;
    if (is_timeout(conn->last_pinged, TCP_PING_FREQUENCY)) {
        uint64_t ping_id = random_64b();
        if (!ping_id)
            ++ping_id;
        conn->ping_request_id = conn->ping_id = ping_id;
        send_ping_request(conn);
        conn->last_pinged = unix_time();
    }
    if (conn->ping_id && is_timeout(conn->last_pinged,
      TCP_PING_TIMEOUT)) {
        conn->status = TCP_CLIENT_DISCONNECTED;
        return 0;
    }
    while ((len = read_packet_TCP_secure_connection(conn->
      sock, &conn->next_packet_length, conn->shared_key,
                  conn->recv_nonce, packet, sizeof(packet)))) {
        if (len == -1) {
            conn->status = TCP_CLIENT_DISCONNECTED;
            break;
        }
        if (handle_TCP_packet(conn, packet, len) == -1) {
            conn->status = TCP_CLIENT_DISCONNECTED;
            break;
        }
    }
    return 0;
}
void do_TCP_connection (TCP_Client_Connection * TCP_connection)
Definition at line 870 of file TCP_client.c.
References make-funny-savefile::data, do_confirmed_TCP(), generate_handshake(), handle_handshake(), TCP_Client_Connection::kill_at, proxy_http_read_connection_response(), proxy_socks5_generate_connection_request(), proxy_socks5_read_connection_response(), read_TCP_packet(), send_pending_data(), TCP_Client_Connection::sock, socks5_read_handshake_response(), TCP_Client_Connection::status, TCP_CLIENT_CONFIRMED, TCP_CLIENT_CONNECTING, TCP_CLIENT_DISCONNECTED, TCP_CLIENT_PROXY_HTTP_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED, TCP_CLIENT_UNCONFIRMED, TCP_SERVER_HANDSHAKE_SIZE, unix_time(), and unix_time_update().
Referenced by do_tcp_conns(), and START_TEST().
{
    unix_time_update();
    if (TCP_connection->status == TCP_CLIENT_DISCONNECTED) {
        return;
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_HTTP_CONNECTING) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = proxy_http_read_connection_response(TCP_connection
      );
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                generate_handshake(TCP_connection);
                TCP_connection->status = TCP_CLIENT_CONNECTING;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_SOCKS5_CONNECTING
      ) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = socks5_read_handshake_response(TCP_connection);
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                proxy_socks5_generate_connection_request(
      TCP_connection);
                TCP_connection->status =
      TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_PROXY_SOCKS5_UNCONFIRMED
      ) {
        if (send_pending_data(TCP_connection) == 0) {
            int ret = proxy_socks5_read_connection_response(
      TCP_connection);
            if (ret == -1) {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
            if (ret == 1) {
                generate_handshake(TCP_connection);
                TCP_connection->status = TCP_CLIENT_CONNECTING;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_CONNECTING) {
        if (send_pending_data(TCP_connection) == 0) {
            TCP_connection->status = TCP_CLIENT_UNCONFIRMED;
        }
    }
    if (TCP_connection->status == TCP_CLIENT_UNCONFIRMED) {
        uint8_t data[TCP_SERVER_HANDSHAKE_SIZE];
        int len = read_TCP_packet(TCP_connection->sock, data, sizeof(data));
        if (sizeof(data) == len) {
            if (handle_handshake(TCP_connection, data) == 0) {
                TCP_connection->kill_at = ~0;
                TCP_connection->status = TCP_CLIENT_CONFIRMED;
            } else {
                TCP_connection->kill_at = 0;
                TCP_connection->status = TCP_CLIENT_DISCONNECTED;
            }
        }
    }
    if (TCP_connection->status == TCP_CLIENT_CONFIRMED) {
        do_confirmed_TCP(TCP_connection);
    }
    if (TCP_connection->kill_at <= unix_time()) {
        TCP_connection->status = TCP_CLIENT_DISCONNECTED;
    }
}
static int generate_handshake (TCP_Client_Connection * TCP_conn) [static]
Definition at line 219 of file TCP_client.c.
References encrypt_data_symmetric(), TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, TCP_Client_Connection::last_packet_sent, new_nonce(), random_nonce(), TCP_Client_Connection::self_public_key, TCP_Client_Connection::sent_nonce, TCP_Client_Connection::shared_key, and TCP_Client_Connection::temp_secret_key.
Referenced by do_TCP_connection(), and new_TCP_connection().
{
    uint8_t plain[crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES];
    crypto_box_keypair(plain, TCP_conn->temp_secret_key);
    random_nonce(TCP_conn->sent_nonce);
    memcpy(plain + crypto_box_PUBLICKEYBYTES, TCP_conn->sent_nonce, crypto_box_NONCEBYTES);
    memcpy(TCP_conn->last_packet, TCP_conn->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    new_nonce(TCP_conn->last_packet + crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(TCP_conn->shared_key, TCP_conn->
      last_packet + crypto_box_PUBLICKEYBYTES, plain,
                                     sizeof(plain), TCP_conn->last_packet +
      crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    if (len != sizeof(plain) + crypto_box_MACBYTES)
        return -1;
    TCP_conn->last_packet_length = crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES +
      sizeof(plain) + crypto_box_MACBYTES;
    TCP_conn->last_packet_sent = 0;
    return 0;
}
static int handle_handshake (TCP_Client_Connection * TCP_conn, const uint8_t * data) [static]
Definition at line 243 of file TCP_client.c.
References decrypt_data_symmetric(), encrypt_precompute(), TCP_Client_Connection::recv_nonce, TCP_Client_Connection::shared_key, TCP_SERVER_HANDSHAKE_SIZE, and TCP_Client_Connection::temp_secret_key.
Referenced by do_TCP_connection().
{
    uint8_t plain[crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES];
    int len = decrypt_data_symmetric(TCP_conn->shared_key,
      data, data + crypto_box_NONCEBYTES,
                                     TCP_SERVER_HANDSHAKE_SIZE -
      crypto_box_NONCEBYTES, plain);
    if (len != sizeof(plain))
        return -1;
    memcpy(TCP_conn->recv_nonce, plain + crypto_box_PUBLICKEYBYTES, crypto_box_NONCEBYTES);
    encrypt_precompute(plain, TCP_conn->temp_secret_key, TCP_conn->
      shared_key);
    memset(TCP_conn->temp_secret_key, 0, crypto_box_SECRETKEYBYTES);
    return 0;
}
static int handle_TCP_packet (TCP_Client_Connection * conn, const uint8_t * data, uint16_t length) [static]
Definition at line 695 of file TCP_client.c.
References TCP_Client_Connection::connections, TCP_Client_Connection::data_callback, TCP_Client_Connection::data_callback_object, NUM_RESERVED_PORTS, TCP_Client_Connection::number, TCP_Client_Connection::onion_callback, TCP_Client_Connection::onion_callback_object, TCP_Client_Connection::oob_data_callback, TCP_Client_Connection::oob_data_callback_object, TCP_Client_Connection::ping_id, TCP_Client_Connection::ping_response_id, TCP_Client_Connection::public_key, TCP_Client_Connection::response_callback, TCP_Client_Connection::response_callback_object, send_ping_response(), TCP_Client_Connection::status, TCP_Client_Connection::status_callback, TCP_Client_Connection::status_callback_object, TCP_PACKET_CONNECTION_NOTIFICATION, TCP_PACKET_DISCONNECT_NOTIFICATION, TCP_PACKET_ONION_RESPONSE, TCP_PACKET_OOB_RECV, TCP_PACKET_PING, TCP_PACKET_PONG, and TCP_PACKET_ROUTING_RESPONSE.
Referenced by do_confirmed_TCP().
{
    if (length <= 1)
        return -1;
    switch (data[0]) {
        case TCP_PACKET_ROUTING_RESPONSE: {
            if (length != 1 + 1 + crypto_box_PUBLICKEYBYTES)
                return -1;
            if (data[1] < NUM_RESERVED_PORTS)
                return 0;
            uint8_t con_id = data[1] - NUM_RESERVED_PORTS;
            if (conn->connections[con_id].status != 0)
                return 0;
            conn->connections[con_id].status = 1;
            conn->connections[con_id].number = ~0;
            memcpy(conn->connections[con_id].public_key,
      data + 2, crypto_box_PUBLICKEYBYTES);
            if (conn->response_callback)
                conn->response_callback(conn->
      response_callback_object, con_id, conn->connections[con_id].
      public_key);
            return 0;
        }
        case TCP_PACKET_CONNECTION_NOTIFICATION: {
            if (length != 1 + 1)
                return -1;
            if (data[1] < NUM_RESERVED_PORTS)
                return -1;
            uint8_t con_id = data[1] - NUM_RESERVED_PORTS;
            if (conn->connections[con_id].status != 1)
                return 0;
            conn->connections[con_id].status = 2;
            if (conn->status_callback)
                conn->status_callback(conn->
      status_callback_object, conn->connections[con_id].
      number, con_id,
                                      conn->connections[con_id].
      status);
            return 0;
        }
        case TCP_PACKET_DISCONNECT_NOTIFICATION: {
            if (length != 1 + 1)
                return -1;
            if (data[1] < NUM_RESERVED_PORTS)
                return -1;
            uint8_t con_id = data[1] - NUM_RESERVED_PORTS;
            if (conn->connections[con_id].status == 0)
                return 0;
            if (conn->connections[con_id].status != 2)
                return 0;
            conn->connections[con_id].status = 1;
            if (conn->status_callback)
                conn->status_callback(conn->
      status_callback_object, conn->connections[con_id].
      number, con_id,
                                      conn->connections[con_id].
      status);
            return 0;
        }
        case TCP_PACKET_PING: {
            if (length != 1 + sizeof(uint64_t))
                return -1;
            uint64_t ping_id;
            memcpy(&ping_id, data + 1, sizeof(uint64_t));
            conn->ping_response_id = ping_id;
            send_ping_response(conn);
            return 0;
        }
        case TCP_PACKET_PONG: {
            if (length != 1 + sizeof(uint64_t))
                return -1;
            uint64_t ping_id;
            memcpy(&ping_id, data + 1, sizeof(uint64_t));
            if (ping_id) {
                if (ping_id == conn->ping_id) {
                    conn->ping_id = 0;
                }
                return 0;
            } else {
                return -1;
            }
        }
        case TCP_PACKET_OOB_RECV: {
            if (length <= 1 + crypto_box_PUBLICKEYBYTES)
                return -1;
            if (conn->oob_data_callback)
                conn->oob_data_callback(conn->
      oob_data_callback_object, data + 1, data + 1 + crypto_box_PUBLICKEYBYTES,
                                        length - (1 + crypto_box_PUBLICKEYBYTES));
            return 0;
        }
        case TCP_PACKET_ONION_RESPONSE: {
            conn->onion_callback(conn->onion_callback_object,
      data + 1, length - 1);
            return 0;
        }
        default: {
            if (data[0] < NUM_RESERVED_PORTS)
                return -1;
            uint8_t con_id = data[0] - NUM_RESERVED_PORTS;
            if (conn->data_callback)
                conn->data_callback(conn->data_callback_object, conn->
      connections[con_id].number, con_id, data + 1, length - 1);
        }
    }
    return 0;
}
void kill_TCP_connection (TCP_Client_Connection * TCP_connection)
Definition at line 958 of file TCP_client.c.
References kill_sock(), TCP_Client_Connection::sock, and wipe_priority_list().
Referenced by kill_tcp_connections(), kill_tcp_relay_connection(), reconnect_tcp_relay_connection(), sleep_tcp_relay_connection(), and START_TEST().
{
    if (TCP_connection == NULL)
        return;
    wipe_priority_list(TCP_connection);
    kill_sock(TCP_connection->sock);
    memset(TCP_connection, 0, sizeof(TCP_Client_Connection));
    free(TCP_connection);
}
TCP_Client_Connection* new_TCP_connection (IP_Port ip_port, const uint8_t * public_key, const uint8_t * self_public_key, const uint8_t * self_secret_key, TCP_Proxy_Info * proxy_info)
Definition at line 611 of file TCP_client.c.
References connect_sock_to(), encrypt_precompute(), IP::family, generate_handshake(), IP_Port::ip, TCP_Proxy_Info::ip_port, TCP_Client_Connection::ip_port, TCP_Client_Connection::kill_at, kill_sock(), networking_at_startup(), proxy_http_generate_connection_request(), TCP_Client_Connection::proxy_info, proxy_socks5_generate_handshake(), TCP_Proxy_Info::proxy_type, TCP_Client_Connection::public_key, TCP_Client_Connection::self_public_key, set_socket_nonblock(), set_socket_nosigpipe(), TCP_Client_Connection::shared_key, sock, TCP_Client_Connection::sock, sock_valid(), TCP_Client_Connection::status, TCP_CLIENT_CONNECTING, TCP_CLIENT_PROXY_HTTP_CONNECTING, TCP_CLIENT_PROXY_SOCKS5_CONNECTING, TCP_CONNECTION_TIMEOUT, TCP_PROXY_HTTP, TCP_PROXY_NONE, TCP_PROXY_SOCKS5, and unix_time().
Referenced by add_tcp_relay_instance(), reconnect_tcp_relay_connection(), START_TEST(), and unsleep_tcp_relay_connection().
{
    if (networking_at_startup() != 0) {
        return NULL;
    }
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return NULL;
    uint8_t family = ip_port.ip.family;
    TCP_Proxy_Info default_proxyinfo;
    if (proxy_info == NULL) {
        default_proxyinfo.proxy_type = TCP_PROXY_NONE;
        proxy_info = &default_proxyinfo;
    }
    if (proxy_info->proxy_type != TCP_PROXY_NONE) {
        family = proxy_info->ip_port.ip.family;
    }
    sock_t sock = socket(family, SOCK_STREAM, IPPROTO_TCP);
    if (!sock_valid(sock)) {
        return NULL;
    }
    if (!set_socket_nosigpipe(sock)) {
        kill_sock(sock);
        return 0;
    }
    if (!(set_socket_nonblock(sock) && connect_sock_to(sock, ip_port,
      proxy_info))) {
        kill_sock(sock);
        return NULL;
    }
    TCP_Client_Connection *temp = calloc(sizeof(
      TCP_Client_Connection), 1);
    if (temp == NULL) {
        kill_sock(sock);
        return NULL;
    }
    temp->sock = sock;
    memcpy(temp->public_key, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(temp->self_public_key, self_public_key, crypto_box_PUBLICKEYBYTES);
    encrypt_precompute(temp->public_key, self_secret_key, temp->
      shared_key);
    temp->ip_port = ip_port;
    temp->proxy_info = *proxy_info;
    switch (proxy_info->proxy_type) {
        case TCP_PROXY_HTTP:
            temp->status = TCP_CLIENT_PROXY_HTTP_CONNECTING;
            proxy_http_generate_connection_request(temp);
            break;
        case TCP_PROXY_SOCKS5:
            temp->status = TCP_CLIENT_PROXY_SOCKS5_CONNECTING;
            proxy_socks5_generate_handshake(temp);
            break;
        case TCP_PROXY_NONE:
            temp->status = TCP_CLIENT_CONNECTING;
            if (generate_handshake(temp) == -1) {
                kill_sock(sock);
                free(temp);
                return NULL;
            }
            break;
    }
    temp->kill_at = unix_time() + TCP_CONNECTION_TIMEOUT;
    return temp;
}
void onion_response_handler (TCP_Client_Connection * con, int(*)(void *object, const uint8_t *data, uint16_t length) onion_callback, void * object)
Definition at line 602 of file TCP_client.c.
References TCP_Client_Connection::onion_callback, and TCP_Client_Connection::onion_callback_object.
Referenced by tcp_relay_set_callbacks().
{
    con->onion_callback = onion_callback;
    con->onion_callback_object = object;
}
void oob_data_handler (TCP_Client_Connection * con, int(*)(void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length) oob_data_callback, void * object)
Definition at line 515 of file TCP_client.c.
References TCP_Client_Connection::oob_data_callback, oob_data_callback(), and TCP_Client_Connection::oob_data_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->oob_data_callback = oob_data_callback;
    con->oob_data_callback_object = object;
}
static int proxy_http_generate_connection_request (TCP_Client_Connection * TCP_conn) [static]
Definition at line 74 of file TCP_client.c.
References ip, IP_Port::ip, ip_parse_addr(), TCP_Client_Connection::ip_port, TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, TCP_Client_Connection::last_packet_sent, MAX_PACKET_SIZE, port, and IP_Port::port.
Referenced by new_TCP_connection().
{
    char one[] = "CONNECT ";
    char two[] = " HTTP/1.1\nHost: ";
    char three[] = "\r\n\r\n";
    char ip[INET6_ADDRSTRLEN];
    if (!ip_parse_addr(&TCP_conn->ip_port.ip, ip, sizeof(ip))) {
        return 0;
    }
    const uint16_t port = ntohs(TCP_conn->ip_port.port);
    const int written = snprintf((char *)TCP_conn->last_packet,
      MAX_PACKET_SIZE, "%s%s:%hu%s%s:%hu%s", one, ip, port, two,
                                 ip, port, three);
    if (written < 0 || MAX_PACKET_SIZE < written) {
        return 0;
    }
    TCP_conn->last_packet_length = written;
    TCP_conn->last_packet_sent = 0;
    return 1;
}
static int proxy_http_read_connection_response (TCP_Client_Connection * TCP_conn) [static]
Definition at line 104 of file TCP_client.c.
References make-funny-savefile::data, read_TCP_packet(), TCP_Client_Connection::sock, and TCP_socket_data_recv_buffer().
Referenced by do_TCP_connection().
{
    char success[] = "200";
    uint8_t data[16]; // draining works the best if the length is a power of 2
    int ret = read_TCP_packet(TCP_conn->sock, data, sizeof(data) - 1);
    if (ret == -1) {
        return 0;
    }
    data[sizeof(data) - 1] = 0;
    if (strstr((char *)data, success)) {
        // drain all data
        unsigned int data_left = TCP_socket_data_recv_buffer(TCP_conn->
      sock);
        if (data_left) {
            uint8_t temp_data[data_left];
            read_TCP_packet(TCP_conn->sock, temp_data, data_left);
        }
        return 1;
    }
    return -1;
}
static void proxy_socks5_generate_connection_request (TCP_Client_Connection * TCP_conn) [static]
Definition at line 160 of file TCP_client.c.
References IP::family, IP_Port::ip, IP::ip4, IP::ip6, TCP_Client_Connection::ip_port, TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, TCP_Client_Connection::last_packet_sent, IP_Port::port, IP4::uint8, and IP6::uint8.
Referenced by do_TCP_connection().
{
    TCP_conn->last_packet[0] = 5; /* SOCKSv5 */
    TCP_conn->last_packet[1] = 1; /* command code: establish a TCP/IP stream connection */
    TCP_conn->last_packet[2] = 0; /* reserved, must be 0 */
    uint16_t length = 3;
    if (TCP_conn->ip_port.ip.family == AF_INET) {
        TCP_conn->last_packet[3] = 1; /* IPv4 address */
        ++length;
        memcpy(TCP_conn->last_packet + length, TCP_conn->ip_port.
      ip.ip4.uint8, sizeof(IP4));
        length += sizeof(IP4);
    } else {
        TCP_conn->last_packet[3] = 4; /* IPv6 address */
        ++length;
        memcpy(TCP_conn->last_packet + length, TCP_conn->ip_port.
      ip.ip6.uint8, sizeof(IP6));
        length += sizeof(IP6);
    }
    memcpy(TCP_conn->last_packet + length, &TCP_conn->ip_port.
      port, sizeof(uint16_t));
    length += sizeof(uint16_t);
    TCP_conn->last_packet_length = length;
    TCP_conn->last_packet_sent = 0;
}
static void proxy_socks5_generate_handshake (TCP_Client_Connection * TCP_conn) [static]
Definition at line 132 of file TCP_client.c.
References TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, and TCP_Client_Connection::last_packet_sent.
Referenced by new_TCP_connection().
{
    TCP_conn->last_packet[0] = 5; /* SOCKSv5 */
    TCP_conn->last_packet[1] = 1; /* number of authentication methods supported */
    TCP_conn->last_packet[2] = 0; /* No authentication */
    TCP_conn->last_packet_length = 3;
    TCP_conn->last_packet_sent = 0;
}
static int proxy_socks5_read_connection_response (TCP_Client_Connection * TCP_conn) [static]
Definition at line 190 of file TCP_client.c.
References make-funny-savefile::data, IP::family, IP_Port::ip, TCP_Client_Connection::ip_port, read_TCP_packet(), and TCP_Client_Connection::sock.
Referenced by do_TCP_connection().
{
    if (TCP_conn->ip_port.ip.family == AF_INET) {
        uint8_t data[4 + sizeof(IP4) + sizeof(uint16_t)];
        int ret = read_TCP_packet(TCP_conn->sock, data, sizeof(data));
        if (ret == -1)
            return 0;
        if (data[0] == 5 && data[1] == 0)
            return 1;
    } else {
        uint8_t data[4 + sizeof(IP6) + sizeof(uint16_t)];
        int ret = read_TCP_packet(TCP_conn->sock, data, sizeof(data));
        if (ret == -1)
            return 0;
        if (data[0] == 5 && data[1] == 0)
            return 1;
    }
    return -1;
}
void routing_data_handler (TCP_Client_Connection * con, int(*)(void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length) data_callback, void * object)
Definition at line 508 of file TCP_client.c.
References TCP_Client_Connection::data_callback, data_callback(), and TCP_Client_Connection::data_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->data_callback = data_callback;
    con->data_callback_object = object;
}
void routing_response_handler (TCP_Client_Connection * con, int(*)(void *object, uint8_t connection_id, const uint8_t *public_key) response_callback, void * object)
Definition at line 434 of file TCP_client.c.
References TCP_Client_Connection::response_callback, response_callback(), and TCP_Client_Connection::response_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->response_callback = response_callback;
    con->response_callback_object = object;
}
void routing_status_handler (TCP_Client_Connection * con, int(*)(void *object, uint32_t number, uint8_t connection_id, uint8_t status) status_callback, void * object)
Definition at line 441 of file TCP_client.c.
References TCP_Client_Connection::status_callback, status_callback(), and TCP_Client_Connection::status_callback_object.
Referenced by START_TEST(), and tcp_relay_set_callbacks().
{
    con->status_callback = status_callback;
    con->status_callback_object = object;
}
int send_data (TCP_Client_Connection * con, uint8_t con_id, const uint8_t * data, uint16_t length)
Definition at line 455 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, NUM_RESERVED_PORTS, send_ping_request(), send_ping_response(), TCP_Client_Connection::status, and write_packet_TCP_secure_connection().
Referenced by send_packet_tcp_connection(), and START_TEST().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    if (con->connections[con_id].status != 2)
        return -1;
    if (send_ping_response(con) == 0 || send_ping_request(con) == 0)
        return 0;
    uint8_t packet[1 + length];
    packet[0] = con_id + NUM_RESERVED_PORTS;
    memcpy(packet + 1, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
static int send_disconnect_notification (TCP_Client_Connection * con, uint8_t id) [static]
Definition at line 526 of file TCP_client.c.
References TCP_PACKET_DISCONNECT_NOTIFICATION, and write_packet_TCP_secure_connection().
Referenced by send_disconnect_request().
{
    uint8_t packet[1 + 1];
    packet[0] = TCP_PACKET_DISCONNECT_NOTIFICATION;
    packet[1] = id;
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 1);
}
int send_disconnect_request (TCP_Client_Connection * con, uint8_t con_id)
Definition at line 580 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, NUM_RESERVED_PORTS, TCP_Client_Connection::number, send_disconnect_notification(), and TCP_Client_Connection::status.
Referenced by kill_tcp_connection_to(), and START_TEST().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    con->connections[con_id].status = 0;
    con->connections[con_id].number = 0;
    return send_disconnect_notification(con, con_id +
      NUM_RESERVED_PORTS);
}
int send_onion_request (TCP_Client_Connection * con, const uint8_t * data, uint16_t length)
Definition at line 594 of file TCP_client.c.
References TCP_PACKET_ONION_REQUEST, and write_packet_TCP_secure_connection().
Referenced by tcp_send_onion_request().
{
    uint8_t packet[1 + length];
    packet[0] = TCP_PACKET_ONION_REQUEST;
    memcpy(packet + 1, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
int send_oob_packet (TCP_Client_Connection * con, const uint8_t * public_key, const uint8_t * data, uint16_t length)
Definition at line 476 of file TCP_client.c.
References TCP_MAX_OOB_DATA_LENGTH, TCP_PACKET_OOB_SEND, and write_packet_TCP_secure_connection().
Referenced by send_packet_tcp_connection(), START_TEST(), and tcp_send_oob_packet().
{
    if (length == 0 || length > TCP_MAX_OOB_DATA_LENGTH)
        return -1;
    uint8_t packet[1 + crypto_box_PUBLICKEYBYTES + length];
    packet[0] = TCP_PACKET_OOB_SEND;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, data, length);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 0);
}
static int send_pending_data (TCP_Client_Connection * con) [static]
Definition at line 286 of file TCP_client.c.
References TCP_Priority_List::data, TCP_Priority_List::next, TCP_Client_Connection::priority_queue_end, TCP_Client_Connection::priority_queue_start, send_pending_data_nonpriority(), TCP_Priority_List::sent, TCP_Priority_List::size, and TCP_Client_Connection::sock.
Referenced by do_confirmed_TCP(), do_TCP_connection(), and write_packet_TCP_secure_connection().
{
    /* finish sending current non-priority packet */
    if (send_pending_data_nonpriority(con) == -1) {
        return -1;
    }
    TCP_Priority_List *p = con->priority_queue_start;
    while (p) {
        uint16_t left = p->size - p->sent;
        int len = send(con->sock, p->data + p->sent, left, MSG_NOSIGNAL);
        if (len != left) {
            if (len > 0) {
                p->sent += len;
            }
            break;
        }
        TCP_Priority_List *pp = p;
        p = p->next;
        free(pp);
    }
    con->priority_queue_start = p;
    if (!p) {
        con->priority_queue_end = NULL;
        return 0;
    }
    return -1;
}
static int send_pending_data_nonpriority (TCP_Client_Connection * con) [static]
Definition at line 261 of file TCP_client.c.
References TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, TCP_Client_Connection::last_packet_sent, and TCP_Client_Connection::sock.
Referenced by send_pending_data().
{
    if (con->last_packet_length == 0) {
        return 0;
    }
    uint16_t left = con->last_packet_length - con->
      last_packet_sent;
    int len = send(con->sock, con->last_packet + con->
      last_packet_sent, left, MSG_NOSIGNAL);
    if (len <= 0)
        return -1;
    if (len == left) {
        con->last_packet_length = 0;
        con->last_packet_sent = 0;
        return 0;
    }
    con->last_packet_sent += len;
    return -1;
}
static int send_ping_request (TCP_Client_Connection * con) [static]
Definition at line 538 of file TCP_client.c.
References TCP_Client_Connection::ping_request_id, TCP_PACKET_PING, and write_packet_TCP_secure_connection().
Referenced by do_confirmed_TCP(), and send_data().
{
    if (!con->ping_request_id)
        return 1;
    uint8_t packet[1 + sizeof(uint64_t)];
    packet[0] = TCP_PACKET_PING;
    memcpy(packet + 1, &con->ping_request_id, sizeof(uint64_t));
    int ret;
    if ((ret = write_packet_TCP_secure_connection(con, packet, sizeof(
      packet), 1)) == 1) {
        con->ping_request_id = 0;
    }
    return ret;
}
static int send_ping_response (TCP_Client_Connection * con) [static]
Definition at line 559 of file TCP_client.c.
References TCP_Client_Connection::ping_response_id, TCP_PACKET_PONG, and write_packet_TCP_secure_connection().
Referenced by do_confirmed_TCP(), handle_TCP_packet(), and send_data().
{
    if (!con->ping_response_id)
        return 1;
    uint8_t packet[1 + sizeof(uint64_t)];
    packet[0] = TCP_PACKET_PONG;
    memcpy(packet + 1, &con->ping_response_id, sizeof(uint64_t));
    int ret;
    if ((ret = write_packet_TCP_secure_connection(con, packet, sizeof(
      packet), 1)) == 1) {
        con->ping_response_id = 0;
    }
    return ret;
}
int send_routing_request (TCP_Client_Connection * con, uint8_t * public_key)
Definition at line 426 of file TCP_client.c.
References TCP_PACKET_ROUTING_REQUEST, and write_packet_TCP_secure_connection().
Referenced by send_tcp_relay_routing_request(), and START_TEST().
{
    uint8_t packet[1 + crypto_box_PUBLICKEYBYTES];
    packet[0] = TCP_PACKET_ROUTING_REQUEST;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    return write_packet_TCP_secure_connection(con, packet, sizeof(packet)
      , 1);
}
int set_tcp_connection_number (TCP_Client_Connection * con, uint8_t con_id, uint32_t number)
Definition at line 496 of file TCP_client.c.
References TCP_Client_Connection::connections, NUM_CLIENT_CONNECTIONS, TCP_Client_Connection::number, and TCP_Client_Connection::status.
Referenced by response_callback(), and tcp_response_callback().
{
    if (con_id >= NUM_CLIENT_CONNECTIONS)
        return -1;
    if (con->connections[con_id].status == 0)
        return -1;
    con->connections[con_id].number = number;
    return 0;
}
static int socks5_read_handshake_response (TCP_Client_Connection * TCP_conn) [static]
Definition at line 146 of file TCP_client.c.
References make-funny-savefile::data, read_TCP_packet(), and TCP_Client_Connection::sock.
Referenced by do_TCP_connection().
{
    uint8_t data[2];
    int ret = read_TCP_packet(TCP_conn->sock, data, sizeof(data));
    if (ret == -1)
        return 0;
    if (data[0] == 5 && data[1] == 0)
        return 1;
    return -1;
}
static void wipe_priority_list (TCP_Client_Connection * con) [static]
Definition at line 349 of file TCP_client.c.
References TCP_Priority_List::next, and TCP_Client_Connection::priority_queue_start.
Referenced by kill_TCP_connection().
{
    TCP_Priority_List *p = con->priority_queue_start;
    while (p) {
        TCP_Priority_List *pp = p;
        p = p->next;
        free(pp);
    }
}
static int write_packet_TCP_secure_connection (TCP_Client_Connection * con, const uint8_t * data, uint16_t length, _Bool priority) [static]
Definition at line 365 of file TCP_client.c.
References add_priority(), encrypt_data_symmetric(), increment_nonce(), TCP_Client_Connection::last_packet, TCP_Client_Connection::last_packet_length, TCP_Client_Connection::last_packet_sent, MAX_PACKET_SIZE, send_pending_data(), TCP_Client_Connection::sent_nonce, TCP_Client_Connection::shared_key, and TCP_Client_Connection::sock.
Referenced by send_data(), send_disconnect_notification(), send_onion_request(), send_oob_packet(), send_ping_request(), send_ping_response(), and send_routing_request().
{
    if (length + crypto_box_MACBYTES > MAX_PACKET_SIZE)
        return -1;
    _Bool sendpriority = 1;
    if (send_pending_data(con) == -1) {
        if (priority) {
            sendpriority = 0;
        } else {
            return 0;
        }
    }
    uint8_t packet[sizeof(uint16_t) + length + crypto_box_MACBYTES];
    uint16_t c_length = htons(length + crypto_box_MACBYTES);
    memcpy(packet, &c_length, sizeof(uint16_t));
    int len = encrypt_data_symmetric(con->shared_key, con->
      sent_nonce, data, length, packet + sizeof(uint16_t));
    if ((unsigned int)len != (sizeof(packet) - sizeof(uint16_t)))
        return -1;
    if (priority) {
        len = sendpriority ? send(con->sock, packet, sizeof(packet), MSG_NOSIGNAL) : 0;
        if (len <= 0) {
            len = 0;
        }
        increment_nonce(con->sent_nonce);
        if ((unsigned int)len == sizeof(packet)) {
            return 1;
        }
        return add_priority(con, packet, sizeof(packet), len);
    }
    len = send(con->sock, packet, sizeof(packet), MSG_NOSIGNAL);
    if (len <= 0)
        return 0;
    increment_nonce(con->sent_nonce);
    if ((unsigned int)len == sizeof(packet))
        return 1;
    memcpy(con->last_packet, packet, sizeof(packet));
    con->last_packet_length = sizeof(packet);
    con->last_packet_sent = len;
    return 1;
}