toxcore/tox.h File Reference
#include <stdbool.h>
*
#include <stddef.h>
*
#include <stdint.h>
*
#include `tox_old.h`
*
Data Structures
struct Tox_Options
Macros
#define TOX_DEFINED
#define TOX_VERSION_MAJOR 0u
#define TOX_VERSION_MINOR 0u
#define TOX_VERSION_PATCH 0u
#define TOX_VERSION_IS_API_COMPATIBLE(MAJOR, MINOR, PATCH)
#define TOX_VERSION_REQUIRE(MAJOR, MINOR, PATCH) typedef char tox_required_version[TOX_IS_COMPATIBLE(MAJOR, MINOR, PATCH) ? 1 : -1]
#define TOX_VERSION_IS_ABI_COMPATIBLE() tox_version_is_compatible(TOX_VERSION_MAJOR, TOX_VERSION_MINOR, TOX_VERSION_PATCH)
#define TOX_PUBLIC_KEY_SIZE 32
#define TOX_SECRET_KEY_SIZE 32
#define TOX_ADDRESS_SIZE (TOX_PUBLIC_KEY_SIZE + sizeof(uint32_t) + sizeof(uint16_t))
#define TOX_MAX_NAME_LENGTH 128
#define TOX_MAX_STATUS_MESSAGE_LENGTH 1007
#define TOX_MAX_FRIEND_REQUEST_LENGTH 1016
#define TOX_MAX_MESSAGE_LENGTH 1372
#define TOX_MAX_CUSTOM_PACKET_SIZE 1373
#define TOX_HASH_LENGTH 32
#define TOX_FILE_ID_LENGTH 32
#define TOX_MAX_FILENAME_LENGTH 255
Typedefs
typedef struct Tox Tox
typedef enum TOX_USER_STATUS TOX_USER_STATUS
typedef enum TOX_MESSAGE_TYPE TOX_MESSAGE_TYPE
typedef enum TOX_PROXY_TYPE TOX_PROXY_TYPE
typedef enum TOX_SAVEDATA_TYPE TOX_SAVEDATA_TYPE
typedef enum TOX_ERR_OPTIONS_NEW TOX_ERR_OPTIONS_NEW
typedef enum TOX_ERR_NEW TOX_ERR_NEW
typedef enum TOX_ERR_BOOTSTRAP TOX_ERR_BOOTSTRAP
typedef enum TOX_CONNECTION TOX_CONNECTION
typedef void tox_self_connection_status_cb (Tox *tox, TOX_CONNECTION connection_status, void *user_data)
typedef enum TOX_ERR_SET_INFO TOX_ERR_SET_INFO
typedef enum TOX_ERR_FRIEND_ADD TOX_ERR_FRIEND_ADD
typedef enum TOX_ERR_FRIEND_DELETE TOX_ERR_FRIEND_DELETE
typedef enum
*
TOX_ERR_FRIEND_BY_PUBLIC_KEY TOX_ERR_FRIEND_BY_PUBLIC_KEY
typedef enum
*
TOX_ERR_FRIEND_GET_PUBLIC_KEY TOX_ERR_FRIEND_GET_PUBLIC_KEY
typedef enum
*
TOX_ERR_FRIEND_GET_LAST_ONLINE TOX_ERR_FRIEND_GET_LAST_ONLINE
typedef enum TOX_ERR_FRIEND_QUERY TOX_ERR_FRIEND_QUERY
typedef void tox_friend_name_cb (Tox *tox, uint32_t friend_number, const uint8_t *name, size_t length, void *user_data)
typedef void tox_friend_status_message_cb (Tox *tox, uint32_t friend_number, const uint8_t *message, size_t length, void *user_data)
typedef void tox_friend_status_cb (Tox *tox, uint32_t friend_number, TOX_USER_STATUS status, void *user_data)
typedef void tox_friend_connection_status_cb (Tox *tox, uint32_t friend_number, TOX_CONNECTION connection_status, void *user_data)
typedef void tox_friend_typing_cb (Tox *tox, uint32_t friend_number, bool is_typing, void *user_data)
typedef enum TOX_ERR_SET_TYPING TOX_ERR_SET_TYPING
typedef enum
*
TOX_ERR_FRIEND_SEND_MESSAGE TOX_ERR_FRIEND_SEND_MESSAGE
typedef void tox_friend_read_receipt_cb (Tox *tox, uint32_t friend_number, uint32_t message_id, void *user_data)
typedef void tox_friend_request_cb (Tox *tox, const uint8_t *public_key, const uint8_t *message, size_t length, void *user_data)
typedef void tox_friend_message_cb (Tox *tox, uint32_t friend_number, TOX_MESSAGE_TYPE type, const uint8_t *message, size_t length, void *user_data)
typedef enum TOX_FILE_CONTROL TOX_FILE_CONTROL
typedef enum TOX_ERR_FILE_CONTROL TOX_ERR_FILE_CONTROL
typedef void tox_file_recv_control_cb (Tox *tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, void *user_data)
typedef enum TOX_ERR_FILE_SEEK TOX_ERR_FILE_SEEK
typedef enum TOX_ERR_FILE_GET TOX_ERR_FILE_GET
typedef enum TOX_ERR_FILE_SEND TOX_ERR_FILE_SEND
typedef enum
*
TOX_ERR_FILE_SEND_CHUNK TOX_ERR_FILE_SEND_CHUNK
typedef void tox_file_chunk_request_cb (Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, size_t length, void *user_data)
typedef void tox_file_recv_cb (Tox *tox, uint32_t friend_number, uint32_t file_number, uint32_t kind, uint64_t file_size, const uint8_t *filename, size_t filename_length, void *user_data)
typedef void tox_file_recv_chunk_cb (Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, const uint8_t *data, size_t length, void *user_data)
typedef enum
*
TOX_ERR_FRIEND_CUSTOM_PACKET TOX_ERR_FRIEND_CUSTOM_PACKET
typedef void tox_friend_lossy_packet_cb (Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, void *user_data)
typedef void tox_friend_lossless_packet_cb (Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, void *user_data)
typedef enum TOX_ERR_GET_PORT TOX_ERR_GET_PORT
Enumerations
enum TOX_USER_STATUS { TOX_USER_STATUS_NONE,
TOX_USER_STATUS_AWAY,
TOX_USER_STATUS_BUSY
 }
enum TOX_MESSAGE_TYPE { TOX_MESSAGE_TYPE_NORMAL,
TOX_MESSAGE_TYPE_ACTION
 }
enum TOX_PROXY_TYPE { TOX_PROXY_TYPE_NONE,
TOX_PROXY_TYPE_HTTP,
TOX_PROXY_TYPE_SOCKS5
 }
enum TOX_SAVEDATA_TYPE { TOX_SAVEDATA_TYPE_NONE,
TOX_SAVEDATA_TYPE_TOX_SAVE,
TOX_SAVEDATA_TYPE_SECRET_KEY
 }
enum TOX_ERR_OPTIONS_NEW { TOX_ERR_OPTIONS_NEW_OK,
TOX_ERR_OPTIONS_NEW_MALLOC
 }
enum TOX_ERR_NEW {
*
TOX_ERR_NEW_OK,
TOX_ERR_NEW_NULL,
TOX_ERR_NEW_MALLOC,
TOX_ERR_NEW_PORT_ALLOC,
*
TOX_ERR_NEW_PROXY_BAD_TYPE,
TOX_ERR_NEW_PROXY_BAD_HOST,
TOX_ERR_NEW_PROXY_BAD_PORT,
TOX_ERR_NEW_PROXY_NOT_FOUND,
*
TOX_ERR_NEW_LOAD_ENCRYPTED,
TOX_ERR_NEW_LOAD_BAD_FORMAT
 }
enum TOX_ERR_BOOTSTRAP { TOX_ERR_BOOTSTRAP_OK,
TOX_ERR_BOOTSTRAP_NULL,
TOX_ERR_BOOTSTRAP_BAD_HOST,
TOX_ERR_BOOTSTRAP_BAD_PORT
 }
enum TOX_CONNECTION { TOX_CONNECTION_NONE,
TOX_CONNECTION_TCP,
TOX_CONNECTION_UDP
 }
enum TOX_ERR_SET_INFO { TOX_ERR_SET_INFO_OK,
TOX_ERR_SET_INFO_NULL,
TOX_ERR_SET_INFO_TOO_LONG
 }
enum TOX_ERR_FRIEND_ADD {
*
TOX_ERR_FRIEND_ADD_OK,
TOX_ERR_FRIEND_ADD_NULL,
TOX_ERR_FRIEND_ADD_TOO_LONG,
TOX_ERR_FRIEND_ADD_NO_MESSAGE,
*
TOX_ERR_FRIEND_ADD_OWN_KEY,
TOX_ERR_FRIEND_ADD_ALREADY_SENT,
TOX_ERR_FRIEND_ADD_BAD_CHECKSUM,
TOX_ERR_FRIEND_ADD_SET_NEW_NOSPAM,
*
TOX_ERR_FRIEND_ADD_MALLOC
 }
enum TOX_ERR_FRIEND_DELETE { TOX_ERR_FRIEND_DELETE_OK,
TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND
 }
enum TOX_ERR_FRIEND_BY_PUBLIC_KEY { TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK,
TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL,
TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND
 }
enum TOX_ERR_FRIEND_GET_PUBLIC_KEY { TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK,
TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND
 }
enum TOX_ERR_FRIEND_GET_LAST_ONLINE { TOX_ERR_FRIEND_GET_LAST_ONLINE_OK,
TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND
 }
enum TOX_ERR_FRIEND_QUERY { TOX_ERR_FRIEND_QUERY_OK,
TOX_ERR_FRIEND_QUERY_NULL,
TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND
 }
enum TOX_ERR_SET_TYPING { TOX_ERR_SET_TYPING_OK,
TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND
 }
enum TOX_ERR_FRIEND_SEND_MESSAGE {
*
TOX_ERR_FRIEND_SEND_MESSAGE_OK,
TOX_ERR_FRIEND_SEND_MESSAGE_NULL,
TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_FOUND,
TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_CONNECTED,
*
TOX_ERR_FRIEND_SEND_MESSAGE_SENDQ,
TOX_ERR_FRIEND_SEND_MESSAGE_TOO_LONG,
TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY
 }
enum TOX_FILE_KIND { TOX_FILE_KIND_DATA,
TOX_FILE_KIND_AVATAR
 }
enum TOX_FILE_CONTROL { TOX_FILE_CONTROL_RESUME,
TOX_FILE_CONTROL_PAUSE,
TOX_FILE_CONTROL_CANCEL
 }
enum TOX_ERR_FILE_CONTROL {
*
TOX_ERR_FILE_CONTROL_OK,
TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND,
TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED,
TOX_ERR_FILE_CONTROL_NOT_FOUND,
*
TOX_ERR_FILE_CONTROL_NOT_PAUSED,
TOX_ERR_FILE_CONTROL_DENIED,
TOX_ERR_FILE_CONTROL_ALREADY_PAUSED,
TOX_ERR_FILE_CONTROL_SENDQ
 }
enum TOX_ERR_FILE_SEEK {
*
TOX_ERR_FILE_SEEK_OK,
TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND,
TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED,
TOX_ERR_FILE_SEEK_NOT_FOUND,
*
TOX_ERR_FILE_SEEK_DENIED,
TOX_ERR_FILE_SEEK_INVALID_POSITION,
TOX_ERR_FILE_SEEK_SENDQ
 }
enum TOX_ERR_FILE_GET { TOX_ERR_FILE_GET_OK,
TOX_ERR_FILE_GET_NULL,
TOX_ERR_FILE_GET_FRIEND_NOT_FOUND,
TOX_ERR_FILE_GET_NOT_FOUND
 }
enum TOX_ERR_FILE_SEND {
*
TOX_ERR_FILE_SEND_OK,
TOX_ERR_FILE_SEND_NULL,
TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND,
TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED,
*
TOX_ERR_FILE_SEND_NAME_TOO_LONG,
TOX_ERR_FILE_SEND_TOO_MANY
 }
enum TOX_ERR_FILE_SEND_CHUNK {
*
TOX_ERR_FILE_SEND_CHUNK_OK,
TOX_ERR_FILE_SEND_CHUNK_NULL,
TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND,
TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED,
*
TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND,
TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING,
TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH,
TOX_ERR_FILE_SEND_CHUNK_SENDQ,
*
TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION
 }
enum TOX_ERR_FRIEND_CUSTOM_PACKET {
*
TOX_ERR_FRIEND_CUSTOM_PACKET_OK,
TOX_ERR_FRIEND_CUSTOM_PACKET_NULL,
TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND,
TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED,
*
TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID,
TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY,
TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG,
TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ
 }
enum TOX_ERR_GET_PORT { TOX_ERR_GET_PORT_OK,
TOX_ERR_GET_PORT_NOT_BOUND
 }
Functions
uint32_t tox_version_major (void)
uint32_t tox_version_minor (void)
uint32_t tox_version_patch (void)
bool tox_version_is_compatible (uint32_t major, uint32_t minor, uint32_t patch)
void tox_options_default (struct Tox_Options *options)
struct Tox_Options * tox_options_new (TOX_ERR_OPTIONS_NEW *error)
void tox_options_free (struct Tox_Options *options)
Tox * tox_new (const struct Tox_Options *options, TOX_ERR_NEW *error)
Creates and initialises a new Tox instance with the options passed.
void tox_kill (Tox *tox)
size_t tox_get_savedata_size (const Tox *tox)
void tox_get_savedata (const Tox *tox, uint8_t *savedata)
bool tox_bootstrap (Tox *tox, const char *address, uint16_t port, const uint8_t *public_key, TOX_ERR_BOOTSTRAP *error)
bool tox_add_tcp_relay (Tox *tox, const char *address, uint16_t port, const uint8_t *public_key, TOX_ERR_BOOTSTRAP *error)
TOX_CONNECTION tox_self_get_connection_status (const Tox *tox)
void tox_callback_self_connection_status (Tox *tox, tox_self_connection_status_cb *callback, void *user_data)
uint32_t tox_iteration_interval (const Tox *tox)
void tox_iterate (Tox *tox)
void tox_self_get_address (const Tox *tox, uint8_t *address)
void tox_self_set_nospam (Tox *tox, uint32_t nospam)
uint32_t tox_self_get_nospam (const Tox *tox)
void tox_self_get_public_key (const Tox *tox, uint8_t *public_key)
void tox_self_get_secret_key (const Tox *tox, uint8_t *secret_key)
bool tox_self_set_name (Tox *tox, const uint8_t *name, size_t length, TOX_ERR_SET_INFO *error)
size_t tox_self_get_name_size (const Tox *tox)
void tox_self_get_name (const Tox *tox, uint8_t *name)
bool tox_self_set_status_message (Tox *tox, const uint8_t *status_message, size_t length, TOX_ERR_SET_INFO *error)
size_t tox_self_get_status_message_size (const Tox *tox)
void tox_self_get_status_message (const Tox *tox, uint8_t *status_message)
void tox_self_set_status (Tox *tox, TOX_USER_STATUS status)
TOX_USER_STATUS tox_self_get_status (const Tox *tox)
uint32_t tox_friend_add (Tox *tox, const uint8_t *address, const uint8_t *message, size_t length, TOX_ERR_FRIEND_ADD *error)
uint32_t tox_friend_add_norequest (Tox *tox, const uint8_t *public_key, TOX_ERR_FRIEND_ADD *error)
bool tox_friend_delete (Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_DELETE *error)
uint32_t tox_friend_by_public_key (const Tox *tox, const uint8_t *public_key, TOX_ERR_FRIEND_BY_PUBLIC_KEY *error)
bool tox_friend_exists (const Tox *tox, uint32_t friend_number)
size_t tox_self_get_friend_list_size (const Tox *tox)
void tox_self_get_friend_list (const Tox *tox, uint32_t *friend_list)
bool tox_friend_get_public_key (const Tox *tox, uint32_t friend_number, uint8_t *public_key, TOX_ERR_FRIEND_GET_PUBLIC_KEY *error)
uint64_t tox_friend_get_last_online (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_GET_LAST_ONLINE *error)
size_t tox_friend_get_name_size (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error)
bool tox_friend_get_name (const Tox *tox, uint32_t friend_number, uint8_t *name, TOX_ERR_FRIEND_QUERY *error)
void tox_callback_friend_name (Tox *tox, tox_friend_name_cb *callback, void *user_data)
size_t tox_friend_get_status_message_size (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error)
bool tox_friend_get_status_message (const Tox *tox, uint32_t friend_number, uint8_t *status_message, TOX_ERR_FRIEND_QUERY *error)
void tox_callback_friend_status_message (Tox *tox, tox_friend_status_message_cb *callback, void *user_data)
TOX_USER_STATUS tox_friend_get_status (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error)
void tox_callback_friend_status (Tox *tox, tox_friend_status_cb *callback, void *user_data)
TOX_CONNECTION tox_friend_get_connection_status (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error)
void tox_callback_friend_connection_status (Tox *tox, tox_friend_connection_status_cb *callback, void *user_data)
bool tox_friend_get_typing (const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error)
void tox_callback_friend_typing (Tox *tox, tox_friend_typing_cb *callback, void *user_data)
bool tox_self_set_typing (Tox *tox, uint32_t friend_number, bool typing, TOX_ERR_SET_TYPING *error)
uint32_t tox_friend_send_message (Tox *tox, uint32_t friend_number, TOX_MESSAGE_TYPE type, const uint8_t *message, size_t length, TOX_ERR_FRIEND_SEND_MESSAGE *error)
void tox_callback_friend_read_receipt (Tox *tox, tox_friend_read_receipt_cb *callback, void *user_data)
void tox_callback_friend_request (Tox *tox, tox_friend_request_cb *callback, void *user_data)
void tox_callback_friend_message (Tox *tox, tox_friend_message_cb *callback, void *user_data)
bool tox_hash (uint8_t *hash, const uint8_t *data, size_t length)
bool tox_file_control (Tox *tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, TOX_ERR_FILE_CONTROL *error)
void tox_callback_file_recv_control (Tox *tox, tox_file_recv_control_cb *callback, void *user_data)
bool tox_file_seek (Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, TOX_ERR_FILE_SEEK *error)
bool tox_file_get_file_id (const Tox *tox, uint32_t friend_number, uint32_t file_number, uint8_t *file_id, TOX_ERR_FILE_GET *error)
uint32_t tox_file_send (Tox *tox, uint32_t friend_number, uint32_t kind, uint64_t file_size, const uint8_t *file_id, const uint8_t *filename, size_t filename_length, TOX_ERR_FILE_SEND *error)
bool tox_file_send_chunk (Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, const uint8_t *data, size_t length, TOX_ERR_FILE_SEND_CHUNK *error)
void tox_callback_file_chunk_request (Tox *tox, tox_file_chunk_request_cb *callback, void *user_data)
void tox_callback_file_recv (Tox *tox, tox_file_recv_cb *callback, void *user_data)
void tox_callback_file_recv_chunk (Tox *tox, tox_file_recv_chunk_cb *callback, void *user_data)
bool tox_friend_send_lossy_packet (Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, TOX_ERR_FRIEND_CUSTOM_PACKET *error)
bool tox_friend_send_lossless_packet (Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, TOX_ERR_FRIEND_CUSTOM_PACKET *error)
void tox_callback_friend_lossy_packet (Tox *tox, tox_friend_lossy_packet_cb *callback, void *user_data)
void tox_callback_friend_lossless_packet (Tox *tox, tox_friend_lossless_packet_cb *callback, void *user_data)
void tox_self_get_dht_id (const Tox *tox, uint8_t *dht_id)
uint16_t tox_self_get_udp_port (const Tox *tox, TOX_ERR_GET_PORT *error)
uint16_t tox_self_get_tcp_port (const Tox *tox, TOX_ERR_GET_PORT *error)
Macro Definition Documentation
#define TOX_ADDRESS_SIZE (TOX_PUBLIC_KEY_SIZE + sizeof(uint32_t) + sizeof(uint16_t))
The size of a Tox address in bytes. Tox addresses are in the format [Public Key (TOX_PUBLIC_KEY_SIZE bytes)][nospam (4 bytes)][checksum (2 bytes)].
The checksum is computed over the Public Key and the nospam value. The first byte is an XOR of all the even bytes (0, 2, 4, ...), the second byte is an XOR of all the odd bytes (1, 3, 5, ...) of the Public Key and nospam.
Definition at line 235 of file tox.h.
Referenced by fraddr_to_str(), get_id(), main(), print_friendlist(), and START_TEST().
#define TOX_DEFINED
Events are handled by callbacks. One callback can be registered per event. All events have a callback function type named tox_{event}_cb and a function to register it named tox_callback_{event}. Passing a NULL callback will result in no callback being registered for that event. Only one callback per event can be registered, so if a client needs multiple event listeners, it needs to implement the dispatch functionality itself.
It is possible to run multiple concurrent threads with a Tox instance for each thread. It is also possible to run all Tox instances in the same thread. A common way to run Tox (multiple or single instance) is to have one thread running a simple tox_iterate loop, sleeping for tox_iteration_interval milliseconds on each iteration.
If you want to access a single Tox instance from multiple threads, access to the instance must be synchronised. While multiple threads can concurrently access multiple different Tox instances, no more than one API function can operate on a single instance at any given time.
Functions that write to variable length byte arrays will always have a size function associated with them. The result of this size function is only valid until another mutating function (one that takes a pointer to non-const Tox) is called. Thus, clients must ensure that no other thread calls a mutating function between the call to the size function and the call to the retrieval function.
E.g. to get the current nickname, one would write
size_t length = tox_self_get_name_size(tox);
uint8_t *name = malloc(length);
if (!name) abort();
tox_self_get_name(tox, name);
If any other thread calls tox_self_set_name while this thread is allocating memory, the length may have become invalid, and the call to tox_self_get_name may cause undefined behaviour. The Tox instance type. All the state associated with a connection is held within the instance. Multiple instances can exist and operate concurrently. The maximum number of Tox instances that can exist on a single network device is limited. Note that this is not just a per-process limit, since the limiting factor is the number of usable ports on a device.
Definition at line 129 of file tox.h.
#define TOX_FILE_ID_LENGTH 32
The number of bytes in a file id.
Definition at line 270 of file tox.h.
Referenced by tox_file_receive().
#define TOX_HASH_LENGTH 32
The number of bytes in a hash generated by tox_hash.
Definition at line 265 of file tox.h.
#define TOX_MAX_CUSTOM_PACKET_SIZE 1373
Maximum size of custom packets. TODO: should be LENGTH?
Definition at line 260 of file tox.h.
Referenced by handle_custom_packet(), and START_TEST().
#define TOX_MAX_FILENAME_LENGTH 255
Maximum file name length for file transfers.
Definition at line 275 of file tox.h.
#define TOX_MAX_FRIEND_REQUEST_LENGTH 1016
Maximum length of a friend request message in bytes.
Definition at line 250 of file tox.h.
Referenced by START_TEST().
#define TOX_MAX_MESSAGE_LENGTH 1372
Maximum length of a single message after which it should be split.
Definition at line 255 of file tox.h.
Referenced by main(), print_message(), and START_TEST().
#define TOX_MAX_NAME_LENGTH 128
Maximum length of a nickname in bytes.
Definition at line 240 of file tox.h.
Referenced by copy_groupmessage(), line_eval(), main(), print_formatted_message(), print_friendlist(), print_groupchatpeers(), print_groupmessage(), print_groupnamelistchange(), print_nickchange(), print_statuschange(), and START_TEST().
#define TOX_MAX_STATUS_MESSAGE_LENGTH 1007
Maximum length of a status message in bytes.
Definition at line 245 of file tox.h.
Referenced by line_eval().
#define TOX_PUBLIC_KEY_SIZE 32
The size of a Tox Public Key in bytes.
Definition at line 220 of file tox.h.
Referenced by fraddr_to_str(), print_request(), and START_TEST().
#define TOX_SECRET_KEY_SIZE 32
The size of a Tox Secret Key in bytes.
Definition at line 225 of file tox.h.
Referenced by START_TEST(), and tox_new().
#define TOX_VERSION_IS_ABI_COMPATIBLE() tox_version_is_compatible(TOX_VERSION_MAJOR, TOX_VERSION_MINOR, TOX_VERSION_PATCH)
A convenience macro to call tox_version_is_compatible with the currently compiling API version.
Definition at line 205 of file tox.h.
#define TOX_VERSION_IS_API_COMPATIBLE(MAJOR, MINOR, PATCH)
Value:
(TOX_VERSION_MAJOR == MAJOR && \
   (TOX_VERSION_MINOR > MINOR || \
    (TOX_VERSION_MINOR == MINOR &&
      \
     TOX_VERSION_PATCH >= PATCH)))
A macro to check at preprocessing time whether the client code is compatible with the installed version of Tox.
Definition at line 165 of file tox.h.
#define TOX_VERSION_MAJOR 0u
The major version number. Incremented when the API or ABI changes in an incompatible way.
Definition at line 146 of file tox.h.
#define TOX_VERSION_MINOR 0u
The minor version number. Incremented when functionality is added without breaking the API or ABI. Set to 0 when the major version number is incremented.
Definition at line 153 of file tox.h.
#define TOX_VERSION_PATCH 0u
The patch or revision number. Incremented when bugfixes are applied without changing any functionality or API or ABI.
Definition at line 159 of file tox.h.
#define TOX_VERSION_REQUIRE(MAJOR, MINOR, PATCH) typedef char tox_required_version[TOX_IS_COMPATIBLE(MAJOR, MINOR, PATCH) ? 1 : -1]
A macro to make compilation fail if the client code is not compatible with the installed version of Tox.
Definition at line 175 of file tox.h.
Typedef Documentation
typedef struct Tox Tox
Definition at line 130 of file tox.h.
typedef enum TOX_CONNECTION TOX_CONNECTION
Protocols that can be used to connect to the network or friends.
typedef enum TOX_ERR_BOOTSTRAP TOX_ERR_BOOTSTRAP
typedef enum TOX_ERR_FILE_CONTROL TOX_ERR_FILE_CONTROL
typedef enum TOX_ERR_FILE_GET TOX_ERR_FILE_GET
typedef enum TOX_ERR_FILE_SEEK TOX_ERR_FILE_SEEK
typedef enum TOX_ERR_FILE_SEND TOX_ERR_FILE_SEND
typedef enum TOX_ERR_FILE_SEND_CHUNK TOX_ERR_FILE_SEND_CHUNK
typedef enum TOX_ERR_FRIEND_ADD TOX_ERR_FRIEND_ADD
typedef enum TOX_ERR_FRIEND_BY_PUBLIC_KEY TOX_ERR_FRIEND_BY_PUBLIC_KEY
typedef enum TOX_ERR_FRIEND_CUSTOM_PACKET TOX_ERR_FRIEND_CUSTOM_PACKET
typedef enum TOX_ERR_FRIEND_DELETE TOX_ERR_FRIEND_DELETE
typedef enum TOX_ERR_FRIEND_GET_LAST_ONLINE TOX_ERR_FRIEND_GET_LAST_ONLINE
typedef enum TOX_ERR_FRIEND_GET_PUBLIC_KEY TOX_ERR_FRIEND_GET_PUBLIC_KEY
typedef enum TOX_ERR_FRIEND_QUERY TOX_ERR_FRIEND_QUERY
Common error codes for friend state query functions.
typedef enum TOX_ERR_FRIEND_SEND_MESSAGE TOX_ERR_FRIEND_SEND_MESSAGE
typedef enum TOX_ERR_GET_PORT TOX_ERR_GET_PORT
typedef enum TOX_ERR_NEW TOX_ERR_NEW
typedef enum TOX_ERR_OPTIONS_NEW TOX_ERR_OPTIONS_NEW
typedef enum TOX_ERR_SET_INFO TOX_ERR_SET_INFO
Common error codes for all functions that set a piece of user-visible client information.
typedef enum TOX_ERR_SET_TYPING TOX_ERR_SET_TYPING
typedef void tox_file_chunk_request_cb(Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, size_t length, void *user_data)
If the length parameter is 0, the file transfer is finished, and the client's resources associated with the file number should be released. After a call with zero length, the file number can be reused for future file transfers.
If the requested position is not equal to the client's idea of the current file or stream position, it will need to seek. In case of read-once streams, the client should keep the last read chunk so that a seek back can be supported. A seek-back only ever needs to read from the last requested chunk. This happens when a chunk was requested, but the send failed. A seek-back request can occur an arbitrary number of times for any given chunk.
In response to receiving this callback, the client should call the function tox_file_send_chunk with the requested chunk. If the number of bytes sent through that function is zero, the file transfer is assumed complete. A client must send the full length of data requested with this callback.
Parameters
friend_number The friend number of the receiving friend for this file.
file_number The file transfer identifier returned by tox_file_send.
position The file or stream position from which to continue reading.
length The number of bytes requested for the current chunk.
Definition at line 2033 of file tox.h.
typedef enum TOX_FILE_CONTROL TOX_FILE_CONTROL
typedef void tox_file_recv_cb(Tox *tox, uint32_t friend_number, uint32_t file_number, uint32_t kind, uint64_t file_size, const uint8_t *filename, size_t filename_length, void *user_data)
The client should acquire resources to be associated with the file transfer. Incoming file transfers start in the PAUSED state. After this callback returns, a transfer can be rejected by sending a TOX_FILE_CONTROL_CANCEL control command before any other control commands. It can be accepted by sending TOX_FILE_CONTROL_RESUME.
Parameters
friend_number The friend number of the friend who is sending the file transfer request.
file_number The friend-specific file number the data received is associated with.
kind The meaning of the file to be sent.
file_size Size in bytes of the file the client wants to send, UINT64_MAX if unknown or streaming.
filename Name of the file. Does not need to be the actual name. This name will be sent along with the file send request.
filename_length Size in bytes of the filename.
Definition at line 2071 of file tox.h.
typedef void tox_file_recv_chunk_cb(Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, const uint8_t *data, size_t length, void *user_data)
When length is 0, the transfer is finished and the client should release the resources it acquired for the transfer. After a call with length = 0, the file number can be reused for new file transfers.
If position is equal to file_size (received in the file_receive callback) when the transfer finishes, the file was received completely. Otherwise, if file_size was UINT64_MAX, streaming ended successfully when length is 0.
Parameters
friend_number The friend number of the friend who is sending the file.
file_number The friend-specific file number the data received is associated with.
position The file position of the first byte in data.
data A byte array containing the received chunk.
length The length of the received chunk.
Definition at line 2098 of file tox.h.
typedef void tox_file_recv_control_cb(Tox *tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, void *user_data)
When receiving TOX_FILE_CONTROL_CANCEL, the client should release the resources associated with the file number and consider the transfer failed.
Parameters
friend_number The friend number of the friend who is sending the file.
file_number The friend-specific file number the data received is associated with.
control The file control command received.
Definition at line 1728 of file tox.h.
typedef void tox_friend_connection_status_cb(Tox *tox, uint32_t friend_number, TOX_CONNECTION connection_status, void *user_data)
Parameters
friend_number The friend number of the friend whose connection status changed.
connection_status The result of calling tox_friend_get_connection_status on the passed friend_number.
Definition at line 1363 of file tox.h.
typedef void tox_friend_lossless_packet_cb(Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, void *user_data)
Parameters
friend_number The friend number of the friend who sent the packet.
data A byte array containing the received packet data.
length The length of the packet data byte array.
Definition at line 2245 of file tox.h.
typedef void tox_friend_lossy_packet_cb(Tox *tox, uint32_t friend_number, const uint8_t *data, size_t length, void *user_data)
Parameters
friend_number The friend number of the friend who sent a lossy packet.
data A byte array containing the received packet data.
length The length of the packet data byte array.
Definition at line 2230 of file tox.h.
typedef void tox_friend_message_cb(Tox *tox, uint32_t friend_number, TOX_MESSAGE_TYPE type, const uint8_t *message, size_t length, void *user_data)
Parameters
friend_number The friend number of the friend who sent the message.
time_delta Time between composition and sending.
message The message data they sent.
length The size of the message byte array.
See also
friend_request for more information on time_delta.
Definition at line 1561 of file tox.h.
typedef void tox_friend_name_cb(Tox *tox, uint32_t friend_number, const uint8_t *name, size_t length, void *user_data)
Parameters
friend_number The friend number of the friend whose name changed.
name A byte array containing the same data as tox_friend_get_name would write to its name parameter.
length A value equal to the return value of tox_friend_get_name_size.
Definition at line 1269 of file tox.h.
typedef void tox_friend_read_receipt_cb(Tox *tox, uint32_t friend_number, uint32_t message_id, void *user_data)
Parameters
friend_number The friend number of the friend who received the message.
message_id The message ID as returned from tox_friend_send_message corresponding to the message sent.
Definition at line 1512 of file tox.h.
typedef void tox_friend_request_cb(Tox *tox, const uint8_t *public_key, const uint8_t *message, size_t length, void *user_data)
Parameters
public_key The Public Key of the user who sent the friend request.
time_delta A delta in seconds between when the message was composed and when it is being transmitted. For messages that are sent immediately, it will be 0. If a message was written and couldn't be sent immediately (due to a connection failure, for example), the time_delta is an approximation of when it was composed.
message The message they sent along with the request.
length The size of the message byte array.
Definition at line 1542 of file tox.h.
typedef void tox_friend_status_cb(Tox *tox, uint32_t friend_number, TOX_USER_STATUS status, void *user_data)
Parameters
friend_number The friend number of the friend whose user status changed.
status The new user status.
Definition at line 1333 of file tox.h.
typedef void tox_friend_status_message_cb(Tox *tox, uint32_t friend_number, const uint8_t *message, size_t length, void *user_data)
Parameters
friend_number The friend number of the friend whose status message changed.
message A byte array containing the same data as tox_friend_get_status_message would write to its status_message parameter.
length A value equal to the return value of tox_friend_get_status_message_size.
Definition at line 1308 of file tox.h.
typedef void tox_friend_typing_cb(Tox *tox, uint32_t friend_number, bool is_typing, void *user_data)
Parameters
friend_number The friend number of the friend who started or stopped typing.
is_typing The result of calling tox_friend_get_typing on the passed friend_number.
Definition at line 1395 of file tox.h.
typedef enum TOX_MESSAGE_TYPE TOX_MESSAGE_TYPE
Represents message types for tox_friend_send_message and group chat messages.
typedef enum TOX_PROXY_TYPE TOX_PROXY_TYPE
Type of proxy used to connect to TCP relays.
typedef enum TOX_SAVEDATA_TYPE TOX_SAVEDATA_TYPE
Type of savedata to create the Tox instance from.
typedef void tox_self_connection_status_cb(Tox *tox, TOX_CONNECTION connection_status, void *user_data)
Parameters
connection_status Whether we are connected to the DHT.
Definition at line 765 of file tox.h.
typedef enum TOX_USER_STATUS TOX_USER_STATUS
Represents the possible statuses a client can have.
Enumeration Type Documentation
enum TOX_CONNECTION
Protocols that can be used to connect to the network or friends.
Enumerator
TOX_CONNECTION_NONE
 There is no connection. This instance, or the friend the state change is about, is now offline.
TOX_CONNECTION_TCP
 A TCP connection has been established. For the own instance, this means it is connected through a TCP relay, only. For a friend, this means that the connection to that particular friend goes through a TCP relay.
TOX_CONNECTION_UDP
 A UDP connection has been established. For the own instance, this means it is able to send UDP packets to DHT nodes, but may still be connected to a TCP relay. For a friend, this means that the connection to that particular friend was built using direct UDP packets.
Definition at line 730 of file tox.h.
                            {
    TOX_CONNECTION_NONE,
    TOX_CONNECTION_TCP,
    TOX_CONNECTION_UDP,
} TOX_CONNECTION;
enum TOX_ERR_BOOTSTRAP
Enumerator
TOX_ERR_BOOTSTRAP_OK
 The function returned successfully.
TOX_ERR_BOOTSTRAP_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_BOOTSTRAP_BAD_HOST
 The address could not be resolved to an IP address, or the IP address passed was invalid.
TOX_ERR_BOOTSTRAP_BAD_PORT
 The port passed was invalid. The valid port range is (1, 65535).
Definition at line 669 of file tox.h.
                               {
    TOX_ERR_BOOTSTRAP_OK,
    TOX_ERR_BOOTSTRAP_NULL,
    TOX_ERR_BOOTSTRAP_BAD_HOST,
    TOX_ERR_BOOTSTRAP_BAD_PORT,
} TOX_ERR_BOOTSTRAP;
enum TOX_ERR_FILE_CONTROL
Enumerator
TOX_ERR_FILE_CONTROL_OK
 The function returned successfully.
TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND
 The friend_number passed did not designate a valid friend.
TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FILE_CONTROL_NOT_FOUND
 No file transfer with the given file number was found for the given friend.
TOX_ERR_FILE_CONTROL_NOT_PAUSED
 A RESUME control was sent, but the file transfer is running normally.
TOX_ERR_FILE_CONTROL_DENIED
 A RESUME control was sent, but the file transfer was paused by the other party. Only the party that paused the transfer can resume it.
TOX_ERR_FILE_CONTROL_ALREADY_PAUSED
 A PAUSE control was sent, but the file transfer was already paused.
TOX_ERR_FILE_CONTROL_SENDQ
 Packet queue is full.
Definition at line 1660 of file tox.h.
                                  {
    TOX_ERR_FILE_CONTROL_OK,
    TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND,
    TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED,
    TOX_ERR_FILE_CONTROL_NOT_FOUND,
    TOX_ERR_FILE_CONTROL_NOT_PAUSED,
    TOX_ERR_FILE_CONTROL_DENIED,
    TOX_ERR_FILE_CONTROL_ALREADY_PAUSED,
    TOX_ERR_FILE_CONTROL_SENDQ,
} TOX_ERR_FILE_CONTROL;
enum TOX_ERR_FILE_GET
Enumerator
TOX_ERR_FILE_GET_OK
 The function returned successfully.
TOX_ERR_FILE_GET_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FILE_GET_FRIEND_NOT_FOUND
 The friend_number passed did not designate a valid friend.
TOX_ERR_FILE_GET_NOT_FOUND
 No file transfer with the given file number was found for the given friend.
Definition at line 1793 of file tox.h.
                              {
    TOX_ERR_FILE_GET_OK,
    TOX_ERR_FILE_GET_NULL,
    TOX_ERR_FILE_GET_FRIEND_NOT_FOUND,
    TOX_ERR_FILE_GET_NOT_FOUND,
} TOX_ERR_FILE_GET;
enum TOX_ERR_FILE_SEEK
Enumerator
TOX_ERR_FILE_SEEK_OK
 The function returned successfully.
TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND
 The friend_number passed did not designate a valid friend.
TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FILE_SEEK_NOT_FOUND
 No file transfer with the given file number was found for the given friend.
TOX_ERR_FILE_SEEK_DENIED
 File was not in a state where it could be seeked.
TOX_ERR_FILE_SEEK_INVALID_POSITION
 Seek position was invalid
TOX_ERR_FILE_SEEK_SENDQ
 Packet queue is full.
Definition at line 1740 of file tox.h.
                               {
    TOX_ERR_FILE_SEEK_OK,
    TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND,
    TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED,
    TOX_ERR_FILE_SEEK_NOT_FOUND,
    TOX_ERR_FILE_SEEK_DENIED,
    TOX_ERR_FILE_SEEK_INVALID_POSITION,
    TOX_ERR_FILE_SEEK_SENDQ,
} TOX_ERR_FILE_SEEK;
enum TOX_ERR_FILE_SEND
Enumerator
TOX_ERR_FILE_SEND_OK
 The function returned successfully.
TOX_ERR_FILE_SEND_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND
 The friend_number passed did not designate a valid friend.
TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FILE_SEND_NAME_TOO_LONG
 Filename length exceeded TOX_MAX_FILENAME_LENGTH bytes.
TOX_ERR_FILE_SEND_TOO_MANY
 Too many ongoing transfers. The maximum number of concurrent file transfers is 256 per friend per direction (sending and receiving).
Definition at line 1841 of file tox.h.
                               {
    TOX_ERR_FILE_SEND_OK,
    TOX_ERR_FILE_SEND_NULL,
    TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND,
    TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED,
    TOX_ERR_FILE_SEND_NAME_TOO_LONG,
    TOX_ERR_FILE_SEND_TOO_MANY,
} TOX_ERR_FILE_SEND;
enum TOX_ERR_FILE_SEND_CHUNK
Enumerator
TOX_ERR_FILE_SEND_CHUNK_OK
 The function returned successfully.
TOX_ERR_FILE_SEND_CHUNK_NULL
 The length parameter was non-zero, but data was NULL.
TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND
 The friend_number passed did not designate a valid friend.
TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND
 No file transfer with the given file number was found for the given friend.
TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING
 File transfer was found but isn't in a transferring state: (paused, done, broken, etc...) (happens only when not called from the request chunk callback).
TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH
 Attempted to send more or less data than requested. The requested data size is adjusted according to maximum transmission unit and the expected end of the file. Trying to send less or more than requested will return this error.
TOX_ERR_FILE_SEND_CHUNK_SENDQ
 Packet queue is full.
TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION
 Position parameter was wrong.
Definition at line 1939 of file tox.h.
                                     {
    TOX_ERR_FILE_SEND_CHUNK_OK,
    TOX_ERR_FILE_SEND_CHUNK_NULL,
    TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND,
    TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED,
    TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND,
    TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING,
    TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH,
    TOX_ERR_FILE_SEND_CHUNK_SENDQ,
    TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION,
} TOX_ERR_FILE_SEND_CHUNK;
enum TOX_ERR_FRIEND_ADD
Enumerator
TOX_ERR_FRIEND_ADD_OK
 The function returned successfully.
TOX_ERR_FRIEND_ADD_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FRIEND_ADD_TOO_LONG
 The length of the friend request message exceeded TOX_MAX_FRIEND_REQUEST_LENGTH.
TOX_ERR_FRIEND_ADD_NO_MESSAGE
 The friend request message was empty. This, and the TOO_LONG code will never be returned from tox_friend_add_norequest.
TOX_ERR_FRIEND_ADD_OWN_KEY
 The friend address belongs to the sending client.
TOX_ERR_FRIEND_ADD_ALREADY_SENT
 A friend request has already been sent, or the address belongs to a friend that is already on the friend list.
TOX_ERR_FRIEND_ADD_BAD_CHECKSUM
 The friend address checksum failed.
TOX_ERR_FRIEND_ADD_SET_NEW_NOSPAM
 The friend was already there, but the nospam value was different.
TOX_ERR_FRIEND_ADD_MALLOC
 A memory allocation failed when trying to increase the friend list size.
Definition at line 965 of file tox.h.
                                {
    TOX_ERR_FRIEND_ADD_OK,
    TOX_ERR_FRIEND_ADD_NULL,
    TOX_ERR_FRIEND_ADD_TOO_LONG,
    TOX_ERR_FRIEND_ADD_NO_MESSAGE,
    TOX_ERR_FRIEND_ADD_OWN_KEY,
    TOX_ERR_FRIEND_ADD_ALREADY_SENT,
    TOX_ERR_FRIEND_ADD_BAD_CHECKSUM,
    TOX_ERR_FRIEND_ADD_SET_NEW_NOSPAM,
    TOX_ERR_FRIEND_ADD_MALLOC,
} TOX_ERR_FRIEND_ADD;
enum TOX_ERR_FRIEND_BY_PUBLIC_KEY
Enumerator
TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK
 The function returned successfully.
TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND
 No friend with the given Public Key exists on the friend list.
Definition at line 1101 of file tox.h.
                                          {
    TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK,
    TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL,
    TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND,
} TOX_ERR_FRIEND_BY_PUBLIC_KEY;
enum TOX_ERR_FRIEND_CUSTOM_PACKET
Enumerator
TOX_ERR_FRIEND_CUSTOM_PACKET_OK
 The function returned successfully.
TOX_ERR_FRIEND_CUSTOM_PACKET_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND
 The friend number did not designate a valid friend.
TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID
 The first byte of data was not in the specified range for the packet type. This range is 200-254 for lossy, and 160-191 for lossless packets.
TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY
 Attempted to send an empty packet.
TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG
 Packet data length exceeded TOX_MAX_CUSTOM_PACKET_SIZE.
TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ
 Packet queue is full.
Definition at line 2137 of file tox.h.
                                          {
    TOX_ERR_FRIEND_CUSTOM_PACKET_OK,
    TOX_ERR_FRIEND_CUSTOM_PACKET_NULL,
    TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND,
    TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED,
    TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID,
    TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY,
    TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG,
    TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ,
} TOX_ERR_FRIEND_CUSTOM_PACKET;
enum TOX_ERR_FRIEND_DELETE
Enumerator
TOX_ERR_FRIEND_DELETE_OK
 The function returned successfully.
TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND
 There was no friend with the given friend number. No friends were deleted.
Definition at line 1064 of file tox.h.
                                   {
    TOX_ERR_FRIEND_DELETE_OK,
    TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND,
} TOX_ERR_FRIEND_DELETE;
enum TOX_ERR_FRIEND_GET_LAST_ONLINE
Enumerator
TOX_ERR_FRIEND_GET_LAST_ONLINE_OK
 The function returned successfully.
TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND
 No friend with the given number exists on the friend list.
Definition at line 1180 of file tox.h.
                                            {
    TOX_ERR_FRIEND_GET_LAST_ONLINE_OK,
    TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND,
} TOX_ERR_FRIEND_GET_LAST_ONLINE;
enum TOX_ERR_FRIEND_GET_PUBLIC_KEY
Enumerator
TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK
 The function returned successfully.
TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND
 No friend with the given number exists on the friend list.
Definition at line 1153 of file tox.h.
                                           {
    TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK,
    TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND,
} TOX_ERR_FRIEND_GET_PUBLIC_KEY;
enum TOX_ERR_FRIEND_QUERY
Common error codes for friend state query functions.
Enumerator
TOX_ERR_FRIEND_QUERY_OK
 The function returned successfully.
TOX_ERR_FRIEND_QUERY_NULL
 The pointer parameter for storing the query result (name, message) was NULL. Unlike the _self_ variants of these functions, which have no effect when a parameter is NULL, these functions return an error in that case.
TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND
 The friend_number did not designate a valid friend.
Definition at line 1215 of file tox.h.
                                  {
    TOX_ERR_FRIEND_QUERY_OK,
    TOX_ERR_FRIEND_QUERY_NULL,
    TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND,
} TOX_ERR_FRIEND_QUERY;
enum TOX_ERR_FRIEND_SEND_MESSAGE
Enumerator
TOX_ERR_FRIEND_SEND_MESSAGE_OK
 The function returned successfully.
TOX_ERR_FRIEND_SEND_MESSAGE_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_FOUND
 The friend number did not designate a valid friend.
TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_CONNECTED
 This client is currently not connected to the friend.
TOX_ERR_FRIEND_SEND_MESSAGE_SENDQ
 An allocation error occurred while increasing the send queue size.
TOX_ERR_FRIEND_SEND_MESSAGE_TOO_LONG
 Message length exceeded TOX_MAX_MESSAGE_LENGTH.
TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY
 Attempted to send a zero-length message.
Definition at line 1441 of file tox.h.
                                         {
    TOX_ERR_FRIEND_SEND_MESSAGE_OK,
    TOX_ERR_FRIEND_SEND_MESSAGE_NULL,
    TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_FOUND,
    TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_CONNECTED,
    TOX_ERR_FRIEND_SEND_MESSAGE_SENDQ,
    TOX_ERR_FRIEND_SEND_MESSAGE_TOO_LONG,
    TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY,
} TOX_ERR_FRIEND_SEND_MESSAGE;
enum TOX_ERR_GET_PORT
Enumerator
TOX_ERR_GET_PORT_OK
 The function returned successfully.
TOX_ERR_GET_PORT_NOT_BOUND
 The instance was not bound to any port.
Definition at line 2278 of file tox.h.
                              {
    TOX_ERR_GET_PORT_OK,
    TOX_ERR_GET_PORT_NOT_BOUND,
} TOX_ERR_GET_PORT;
enum TOX_ERR_NEW
Enumerator
TOX_ERR_NEW_OK
 The function returned successfully.
TOX_ERR_NEW_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_NEW_MALLOC
 The function was unable to allocate enough memory to store the internal structures for the Tox object.
TOX_ERR_NEW_PORT_ALLOC
 The function was unable to bind to a port. This may mean that all ports have already been bound, e.g. by other Tox instances, or it may mean a permission error. You may be able to gather more information from errno.
TOX_ERR_NEW_PROXY_BAD_TYPE
 proxy_type was invalid.
TOX_ERR_NEW_PROXY_BAD_HOST
 proxy_type was valid but the proxy_host passed had an invalid format or was NULL.
TOX_ERR_NEW_PROXY_BAD_PORT
 proxy_type was valid, but the proxy_port was invalid.
TOX_ERR_NEW_PROXY_NOT_FOUND
 The proxy address passed could not be resolved.
TOX_ERR_NEW_LOAD_ENCRYPTED
 The byte array to be loaded contained an encrypted save.
TOX_ERR_NEW_LOAD_BAD_FORMAT
 The data format was invalid. This can happen when loading data that was saved by an older version of Tox, or when the data has been corrupted. When loading from badly formatted data, some data may have been loaded, and the rest is discarded. Passing an invalid length parameter also causes this error.
Definition at line 553 of file tox.h.
                         {
    TOX_ERR_NEW_OK,
    TOX_ERR_NEW_NULL,
    TOX_ERR_NEW_MALLOC,
    TOX_ERR_NEW_PORT_ALLOC,
    TOX_ERR_NEW_PROXY_BAD_TYPE,
    TOX_ERR_NEW_PROXY_BAD_HOST,
    TOX_ERR_NEW_PROXY_BAD_PORT,
    TOX_ERR_NEW_PROXY_NOT_FOUND,
    TOX_ERR_NEW_LOAD_ENCRYPTED,
    TOX_ERR_NEW_LOAD_BAD_FORMAT,
} TOX_ERR_NEW;
enum TOX_ERR_OPTIONS_NEW
Enumerator
TOX_ERR_OPTIONS_NEW_OK
 The function returned successfully.
TOX_ERR_OPTIONS_NEW_MALLOC
 The function failed to allocate enough memory for the options struct.
Definition at line 509 of file tox.h.
                                 {
    TOX_ERR_OPTIONS_NEW_OK,
    TOX_ERR_OPTIONS_NEW_MALLOC,
} TOX_ERR_OPTIONS_NEW;
enum TOX_ERR_SET_INFO
Common error codes for all functions that set a piece of user-visible client information.
Enumerator
TOX_ERR_SET_INFO_OK
 The function returned successfully.
TOX_ERR_SET_INFO_NULL
 One of the arguments to the function was NULL when it was not expected.
TOX_ERR_SET_INFO_TOO_LONG
 Information length exceeded maximum permissible size.
Definition at line 854 of file tox.h.
                              {
    TOX_ERR_SET_INFO_OK,
    TOX_ERR_SET_INFO_NULL,
    TOX_ERR_SET_INFO_TOO_LONG,
} TOX_ERR_SET_INFO;
enum TOX_ERR_SET_TYPING
Enumerator
TOX_ERR_SET_TYPING_OK
 The function returned successfully.
TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND
 The friend number did not designate a valid friend.
Definition at line 1414 of file tox.h.
                                {
    TOX_ERR_SET_TYPING_OK,
    TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND,
} TOX_ERR_SET_TYPING;
enum TOX_FILE_CONTROL
Enumerator
TOX_FILE_CONTROL_RESUME
 Sent by the receiving side to accept a file send request. Also sent after a TOX_FILE_CONTROL_PAUSE command to continue sending or receiving.
TOX_FILE_CONTROL_PAUSE
 Sent by clients to pause the file transfer. The initial state of a file transfer is always paused on the receiving side and running on the sending side. If both the sending and receiving side pause the transfer, then both need to send TOX_FILE_CONTROL_RESUME for the transfer to resume.
TOX_FILE_CONTROL_CANCEL
 Sent by the receiving side to reject a file send request before any other commands are sent. Also sent by either side to terminate a file transfer.
Definition at line 1635 of file tox.h.
                              {
    TOX_FILE_CONTROL_RESUME,
    TOX_FILE_CONTROL_PAUSE,
    TOX_FILE_CONTROL_CANCEL,
} TOX_FILE_CONTROL;
enum TOX_FILE_KIND
Enumerator
TOX_FILE_KIND_DATA
 Arbitrary file data. Clients can choose to handle it based on the file name or magic or any other way they choose.
TOX_FILE_KIND_AVATAR
 Avatar file_id. This consists of tox_hash(image). Avatar data. This consists of the image data.
Avatars can be sent at any time the client wishes. Generally, a client will send the avatar to a friend when that friend comes online, and to all friends when the avatar changed. A client can save some traffic by remembering which friend received the updated avatar already and only send it if the friend has an out of date avatar.
Clients who receive avatar send requests can reject it (by sending TOX_FILE_CONTROL_CANCEL before any other controls), or accept it (by sending TOX_FILE_CONTROL_RESUME). The file_id of length TOX_HASH_LENGTH bytes (same length as TOX_FILE_ID_LENGTH) will contain the hash. A client can compare this hash with a saved hash and send TOX_FILE_CONTROL_CANCEL to terminate the avatar transfer if it matches.
When file_size is set to 0 in the transfer request it means that the client has no avatar.
Definition at line 1602 of file tox.h.
                   {
    TOX_FILE_KIND_DATA,
    TOX_FILE_KIND_AVATAR,
};
enum TOX_MESSAGE_TYPE
Represents message types for tox_friend_send_message and group chat messages.
Enumerator
TOX_MESSAGE_TYPE_NORMAL
 Normal text message. Similar to PRIVMSG on IRC.
TOX_MESSAGE_TYPE_ACTION
 A message describing an user action. This is similar to /me (CTCP ACTION) on IRC.
Definition at line 315 of file tox.h.
                              {
    TOX_MESSAGE_TYPE_NORMAL,
    TOX_MESSAGE_TYPE_ACTION,
} TOX_MESSAGE_TYPE;
enum TOX_PROXY_TYPE
Type of proxy used to connect to TCP relays.
Enumerator
TOX_PROXY_TYPE_NONE
 Don't use a proxy.
TOX_PROXY_TYPE_HTTP
 HTTP proxy using CONNECT.
TOX_PROXY_TYPE_SOCKS5
 SOCKS proxy for simple socket pipes.
Definition at line 343 of file tox.h.
                            {
    TOX_PROXY_TYPE_NONE,
    TOX_PROXY_TYPE_HTTP,
    TOX_PROXY_TYPE_SOCKS5,
} TOX_PROXY_TYPE;
enum TOX_SAVEDATA_TYPE
Type of savedata to create the Tox instance from.
Enumerator
TOX_SAVEDATA_TYPE_NONE
 No savedata.
TOX_SAVEDATA_TYPE_TOX_SAVE
 Savedata is one that was obtained from tox_get_savedata
TOX_SAVEDATA_TYPE_SECRET_KEY
 Savedata is a secret key of length TOX_SECRET_KEY_SIZE
Definition at line 366 of file tox.h.
                               {
    TOX_SAVEDATA_TYPE_NONE,
    TOX_SAVEDATA_TYPE_TOX_SAVE,
    TOX_SAVEDATA_TYPE_SECRET_KEY,
} TOX_SAVEDATA_TYPE;
enum TOX_USER_STATUS
Represents the possible statuses a client can have.
Enumerator
TOX_USER_STATUS_NONE
 User is online and available.
TOX_USER_STATUS_AWAY
 User is away. Clients can set this e.g. after a user defined inactivity time.
TOX_USER_STATUS_BUSY
 User is busy. Signals to other clients that this client does not currently wish to communicate.
Definition at line 289 of file tox.h.
                             {
    TOX_USER_STATUS_NONE,
    TOX_USER_STATUS_AWAY,
    TOX_USER_STATUS_BUSY,
} TOX_USER_STATUS;
Function Documentation
bool tox_add_tcp_relay (Tox * tox, const char * address, uint16_t port, const uint8_t * public_key, TOX_ERR_BOOTSTRAP * error)
Adds additional host:port pair as TCP relay.
This function can be used to initiate TCP connections to different ports on the same bootstrap node, or to add TCP relays without using them as bootstrap nodes.
Parameters
address The hostname or IP address (IPv4 or IPv6) of the TCP relay.
port The port on the host on which the TCP relay is listening.
public_key The long term public key of the TCP relay (TOX_PUBLIC_KEY_SIZE bytes).
Returns
true on success.
Definition at line 317 of file tox.c.
References add_tcp_relay(), IP::family, IP6::in6_addr, IP4::in_addr, IP_Port::ip, IP::ip4, IP::ip6, m, Messenger::net_crypto, IP_Port::port, SET_ERROR_PARAMETER, TOX_ERR_BOOTSTRAP_BAD_HOST, TOX_ERR_BOOTSTRAP_BAD_PORT, TOX_ERR_BOOTSTRAP_NULL, and TOX_ERR_BOOTSTRAP_OK.
Referenced by START_TEST().
{
    if (!address || !public_key) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_NULL);
        return 0;
    }
    if (port == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_PORT);
        return 0;
    }
    struct addrinfo *root, *info;
    if (getaddrinfo(address, NULL, NULL, &root) != 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_HOST);
        return 0;
    }
    info = root;
    unsigned int count = 0;
    do {
        IP_Port ip_port;
        ip_port.port = htons(port);
        ip_port.ip.family = info->ai_family;
        if (info->ai_socktype && info->ai_socktype != SOCK_STREAM) {
            continue;
        }
        if (info->ai_family == AF_INET) {
            ip_port.ip.ip4.in_addr = ((struct sockaddr_in *)info->ai_addr)->sin_addr;
        } else if (info->ai_family == AF_INET6) {
            ip_port.ip.ip6.in6_addr = ((struct sockaddr_in6 *)info->ai_addr)->sin6_addr;
        } else {
            continue;
        }
        Messenger *m = tox;
        add_tcp_relay(m->net_crypto, ip_port, public_key);
        ++count;
    } while ((info = info->ai_next));
    freeaddrinfo(root);
    if (count) {
        SET_ERROR_PARAMETER(error, TOX_ERR_BOOTSTRAP_OK);
        return 1;
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_HOST);
        return 0;
    }
}
bool tox_bootstrap (Tox * tox, const char * address, uint16_t port, const uint8_t * public_key, TOX_ERR_BOOTSTRAP * error)
Sends a `get nodes` request to the given bootstrap node with IP, port, and public key to setup connections.
This function will attempt to connect to the node using UDP. You must use this function even if Tox_Options.udp_enabled was set to false.
Parameters
address The hostname or IP address (IPv4 or IPv6) of the node.
port The port on the host on which the bootstrap Tox instance is listening.
public_key The long term public key of the bootstrap node (TOX_PUBLIC_KEY_SIZE bytes).
Returns
true on success.
Definition at line 260 of file tox.c.
References Messenger::dht, DHT_bootstrap(), IP::family, IP6::in6_addr, IP4::in_addr, IP_Port::ip, IP::ip4, IP::ip6, m, onion_add_bs_path_node(), Messenger::onion_c, IP_Port::port, SET_ERROR_PARAMETER, TOX_ERR_BOOTSTRAP_BAD_HOST, TOX_ERR_BOOTSTRAP_BAD_PORT, TOX_ERR_BOOTSTRAP_NULL, and TOX_ERR_BOOTSTRAP_OK.
Referenced by init_tox(), main(), and START_TEST().
{
    if (!address || !public_key) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_NULL);
        return 0;
    }
    if (port == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_PORT);
        return 0;
    }
    struct addrinfo *root, *info;
    if (getaddrinfo(address, NULL, NULL, &root) != 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_HOST);
        return 0;
    }
    info = root;
    unsigned int count = 0;
    do {
        IP_Port ip_port;
        ip_port.port = htons(port);
        ip_port.ip.family = info->ai_family;
        if (info->ai_socktype && info->ai_socktype != SOCK_DGRAM) {
            continue;
        }
        if (info->ai_family == AF_INET) {
            ip_port.ip.ip4.in_addr = ((struct sockaddr_in *)info->ai_addr)->sin_addr;
        } else if (info->ai_family == AF_INET6) {
            ip_port.ip.ip6.in6_addr = ((struct sockaddr_in6 *)info->ai_addr)->sin6_addr;
        } else {
            continue;
        }
        Messenger *m = tox;
        onion_add_bs_path_node(m->onion_c, ip_port,
      public_key);
        DHT_bootstrap(m->dht, ip_port, public_key);
        ++count;
    } while ((info = info->ai_next));
    freeaddrinfo(root);
    if (count) {
        SET_ERROR_PARAMETER(error, TOX_ERR_BOOTSTRAP_OK);
        return 1;
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_BOOTSTRAP_BAD_HOST);
        return 0;
    }
}
void tox_callback_file_chunk_request (Tox * tox, tox_file_chunk_request_cb * callback, void * user_data)
Set the callback for the file_chunk_request event. Pass NULL to unset.
This event is triggered when Core is ready to send more file data.
Definition at line 1125 of file tox.c.
References callback_file_reqchunk(), and m.
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    callback_file_reqchunk(m, function, user_data);
}
void tox_callback_file_recv (Tox * tox, tox_file_recv_cb * callback, void * user_data)
Set the callback for the file_recv event. Pass NULL to unset.
This event is triggered when a file transfer request is received.
Definition at line 1131 of file tox.c.
References callback_file_sendrequest(), and m.
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    callback_file_sendrequest(m, function, user_data);
}
void tox_callback_file_recv_chunk (Tox * tox, tox_file_recv_chunk_cb * callback, void * user_data)
Set the callback for the file_recv_chunk event. Pass NULL to unset.
This event is first triggered when a file transfer request is received, and subsequently when a chunk of file data for an accepted request was received.
Definition at line 1137 of file tox.c.
References callback_file_data(), and m.
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    callback_file_data(m, function, user_data);
}
void tox_callback_file_recv_control (Tox * tox, tox_file_recv_control_cb * callback, void * user_data)
Set the callback for the file_recv_control event. Pass NULL to unset.
This event is triggered when a file control command is received from a friend.
Definition at line 1005 of file tox.c.
References callback_file_control(), and m.
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    callback_file_control(m, function, user_data);
}
void tox_callback_friend_connection_status (Tox * tox, tox_friend_connection_status_cb * callback, void * user_data)
Set the callback for the friend_connection_status event. Pass NULL to unset.
This event is triggered when a friend goes offline after having been online, or when a friend goes online.
This callback is not called when adding friends. It is assumed that when adding friends, their connection status is initially offline.
Definition at line 799 of file tox.c.
References m, and m_callback_connectionstatus().
Referenced by main().
{
    Messenger *m = tox;
    m_callback_connectionstatus(m, function, user_data);
}
void tox_callback_friend_lossless_packet (Tox * tox, tox_friend_lossless_packet_cb * callback, void * user_data)
Set the callback for the friend_lossless_packet event. Pass NULL to unset.
Definition at line 1235 of file tox.c.
References custom_lossless_packet_registerhandler(), and m.
Referenced by START_TEST().
{
    Messenger *m = tox;
    custom_lossless_packet_registerhandler(m, function, user_data);
}
void tox_callback_friend_lossy_packet (Tox * tox, tox_friend_lossy_packet_cb * callback, void * user_data)
Set the callback for the friend_lossy_packet event. Pass NULL to unset.
Definition at line 1203 of file tox.c.
References custom_lossy_packet_registerhandler(), and m.
Referenced by START_TEST().
{
    Messenger *m = tox;
    custom_lossy_packet_registerhandler(m, function, user_data);
}
void tox_callback_friend_message (Tox * tox, tox_friend_message_cb * callback, void * user_data)
Set the callback for the friend_message event. Pass NULL to unset.
This event is triggered when a message from a friend is received.
Definition at line 898 of file tox.c.
References m, and m_callback_friendmessage().
Referenced by init_tox(), main(), and START_TEST().
{
    Messenger *m = tox;
    m_callback_friendmessage(m, function, user_data);
}
void tox_callback_friend_name (Tox * tox, tox_friend_name_cb * callback, void * user_data)
Set the callback for the friend_name event. Pass NULL to unset.
This event is triggered when a friend changes their name.
Definition at line 716 of file tox.c.
References m, and m_callback_namechange().
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    m_callback_namechange(m, function, user_data);
}
void tox_callback_friend_read_receipt (Tox * tox, tox_friend_read_receipt_cb * callback, void * user_data)
Set the callback for the friend_read_receipt event. Pass NULL to unset.
This event is triggered when the friend receives the message sent with tox_friend_send_message with the corresponding message ID.
Definition at line 886 of file tox.c.
References m, and m_callback_read_receipt().
{
    Messenger *m = tox;
    m_callback_read_receipt(m, function, user_data);
}
void tox_callback_friend_request (Tox * tox, tox_friend_request_cb * callback, void * user_data)
Set the callback for the friend_request event. Pass NULL to unset.
This event is triggered when a friend request is received.
Definition at line 892 of file tox.c.
References m, and m_callback_friendrequest().
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    m_callback_friendrequest(m, function, user_data);
}
void tox_callback_friend_status (Tox * tox, tox_friend_status_cb * callback, void * user_data)
Set the callback for the friend_status event. Pass NULL to unset.
This event is triggered when a friend changes their user status.
Definition at line 778 of file tox.c.
References m, and m_callback_userstatus().
{
    Messenger *m = tox;
    m_callback_userstatus(m, function, user_data);
}
void tox_callback_friend_status_message (Tox * tox, tox_friend_status_message_cb * callback, void * user_data)
Set the callback for the friend_status_message event. Pass NULL to unset.
This event is triggered when a friend changes their status message.
Definition at line 757 of file tox.c.
References m, and m_callback_statusmessage().
Referenced by main(), and START_TEST().
{
    Messenger *m = tox;
    m_callback_statusmessage(m, function, user_data);
}
void tox_callback_friend_typing (Tox * tox, tox_friend_typing_cb * callback, void * user_data)
Set the callback for the friend_typing event. Pass NULL to unset.
This event is triggered when a friend starts or stops typing.
Definition at line 819 of file tox.c.
References m, and m_callback_typingchange().
Referenced by START_TEST().
{
    Messenger *m = tox;
    m_callback_typingchange(m, function, user_data);
}
void tox_callback_self_connection_status (Tox * tox, tox_self_connection_status_cb * callback, void * user_data)
Set the callback for the self_connection_status event. Pass NULL to unset.
This event is triggered whenever there is a change in the DHT connection state. When disconnected, a client may choose to call tox_bootstrap again, to reconnect to the DHT. Note that this state may frequently change for short amounts of time. Clients should therefore not immediately bootstrap on receiving a disconnect.
TODO: how long should a client wait before bootstrapping again?
Definition at line 390 of file tox.c.
References m, and m_callback_core_connection().
Referenced by START_TEST().
{
    Messenger *m = tox;
    m_callback_core_connection(m, function, user_data);
}
bool tox_file_control (Tox * tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, TOX_ERR_FILE_CONTROL * error)
Sends a file control command to a friend for a given file transfer.
Parameters
friend_number The friend number of the friend the file is being transferred to or received from.
file_number The friend-specific identifier for the file transfer.
control The control command to send.
Returns
true on success.
Definition at line 914 of file tox.c.
References file_control(), m, SET_ERROR_PARAMETER, TOX_ERR_FILE_CONTROL_ALREADY_PAUSED, TOX_ERR_FILE_CONTROL_DENIED, TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED, TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND, TOX_ERR_FILE_CONTROL_NOT_FOUND, TOX_ERR_FILE_CONTROL_NOT_PAUSED, TOX_ERR_FILE_CONTROL_OK, and TOX_ERR_FILE_CONTROL_SENDQ.
Referenced by file_request_accept(), and tox_file_receive().
{
    Messenger *m = tox;
    int ret = file_control(m, friend_number, file_number, control);
    if (ret == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_OK);
        return 1;
    }
    switch (ret) {
        case -1:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND);
            return 0;
        case -2:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED);
            return 0;
        case -3:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_NOT_FOUND);
            return 0;
        case -4:
            /* can't happen */
            return 0;
        case -5:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_ALREADY_PAUSED);
            return 0;
        case -6:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_DENIED);
            return 0;
        case -7:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_NOT_PAUSED);
            return 0;
        case -8:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_CONTROL_SENDQ);
            return 0;
    }
    /* can't happen */
    return 0;
}
bool tox_file_get_file_id (const Tox * tox, uint32_t friend_number, uint32_t file_number, uint8_t * file_id, TOX_ERR_FILE_GET * error)
Copy the file id associated to the file transfer to a byte array.
Parameters
friend_number The friend number of the friend the file is being transferred to or received from.
file_number The friend-specific identifier for the file transfer.
file_id A memory region of at least TOX_FILE_ID_LENGTH bytes. If this parameter is NULL, this function has no effect.
Returns
true on success.
Definition at line 1011 of file tox.c.
References file_get_id(), m, SET_ERROR_PARAMETER, TOX_ERR_FILE_GET_FRIEND_NOT_FOUND, TOX_ERR_FILE_GET_NOT_FOUND, TOX_ERR_FILE_GET_NULL, and TOX_ERR_FILE_GET_OK.
Referenced by START_TEST(), and tox_file_receive().
{
    if (!file_id) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FILE_GET_NULL);
        return 0;
    }
    const Messenger *m = tox;
    int ret = file_get_id(m, friend_number, file_number, file_id);
    if (ret == 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FILE_GET_OK);
        return 1;
    } else if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_GET_FRIEND_NOT_FOUND);
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_GET_NOT_FOUND);
    }
    return 0;
}
bool tox_file_seek (Tox * tox, uint32_t friend_number, uint32_t file_number, uint64_t position, TOX_ERR_FILE_SEEK * error)
Sends a file seek control command to a friend for a given file transfer.
This function can only be called to resume a file transfer right before TOX_FILE_CONTROL_RESUME is sent.
Parameters
friend_number The friend number of the friend the file is being received from.
file_number The friend-specific identifier for the file transfer.
position The position that the file should be seeked to.
Definition at line 963 of file tox.c.
References file_seek(), m, SET_ERROR_PARAMETER, TOX_ERR_FILE_SEEK_DENIED, TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED, TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND, TOX_ERR_FILE_SEEK_INVALID_POSITION, TOX_ERR_FILE_SEEK_NOT_FOUND, TOX_ERR_FILE_SEEK_OK, and TOX_ERR_FILE_SEEK_SENDQ.
Referenced by tox_file_receive().
{
    Messenger *m = tox;
    int ret = file_seek(m, friend_number, file_number, position);
    if (ret == 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FILE_SEEK_OK);
        return 1;
    }
    switch (ret) {
        case -1:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND);
            return 0;
        case -2:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED);
            return 0;
        case -3:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_NOT_FOUND);
            return 0;
        case -4:
        case -5:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_DENIED);
            return 0;
        case -6:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_INVALID_POSITION);
            return 0;
        case -8:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEEK_SENDQ);
            return 0;
    }
    /* can't happen */
    return 0;
}
uint32_t tox_file_send (Tox * tox, uint32_t friend_number, uint32_t kind, uint64_t file_size, const uint8_t * file_id, const uint8_t * filename, size_t filename_length, TOX_ERR_FILE_SEND * error)
Send a file transmission request.
Maximum filename length is TOX_MAX_FILENAME_LENGTH bytes. The filename should generally just be a file name, not a path with directory names.
If a non-UINT64_MAX file size is provided, it can be used by both sides to determine the sending progress. File size can be set to UINT64_MAX for streaming data of unknown size.
File transmission occurs in chunks, which are requested through the file_chunk_request event.
When a friend goes offline, all file transfers associated with the friend are purged from core.
If the file contents change during a transfer, the behaviour is unspecified in general. What will actually happen depends on the mode in which the file was modified and how the client determines the file size.
If the file size was increased
and sending mode was streaming (file_size = UINT64_MAX), the behaviour will be as expected.
and sending mode was file (file_size != UINT64_MAX), the file_chunk_request callback will receive length = 0 when Core thinks the file transfer has finished. If the client remembers the file size as it was when sending the request, it will terminate the transfer normally. If the client re-reads the size, it will think the friend cancelled the transfer.
If the file size was decreased
and sending mode was streaming, the behaviour is as expected.
and sending mode was file, the callback will return 0 at the new (earlier) end-of-file, signalling to the friend that the transfer was cancelled.
If the file contents were modified
at a position before the current read, the two files (local and remote) will differ after the transfer terminates.
at a position after the current read, the file transfer will succeed as expected.
In either case, both sides will regard the transfer as complete and successful.
Parameters
friend_number The friend number of the friend the file send request should be sent to.
kind The meaning of the file to be sent.
file_size Size in bytes of the file the client wants to send, UINT64_MAX if unknown or streaming.
file_id A file identifier of length TOX_FILE_ID_LENGTH that can be used to uniquely identify file transfers across core restarts. If NULL, a random one will be generated by core. It can then be obtained by using tox_file_get_file_id().
filename Name of the file. Does not need to be the actual name. This name will be sent along with the file send request.
filename_length Size in bytes of the filename.
Returns
A file number used as an identifier in subsequent callbacks. This number is per friend. File numbers are reused after a transfer terminates. On failure, this function returns UINT32_MAX. Any pattern in file numbers should not be relied on.
Definition at line 1034 of file tox.c.
References FILE_ID_LENGTH, m, new_filesender(), new_symmetric_key(), SET_ERROR_PARAMETER, TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED, TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND, TOX_ERR_FILE_SEND_NAME_TOO_LONG, TOX_ERR_FILE_SEND_NULL, TOX_ERR_FILE_SEND_OK, and TOX_ERR_FILE_SEND_TOO_MANY.
Referenced by add_filesender(), and START_TEST().
{
    if (filename_length && !filename) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_NULL);
        return UINT32_MAX;
    }
    uint8_t f_id[FILE_ID_LENGTH];
    if (!file_id) {
        /* Tox keys are 32 bytes like FILE_ID_LENGTH. */
        new_symmetric_key(f_id);
        file_id = f_id;
    }
    Messenger *m = tox;
    long int file_num = new_filesender(m, friend_number, kind,
      file_size, file_id, filename, filename_length);
    if (file_num >= 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FILE_SEND_OK);
        return file_num;
    }
    switch (file_num) {
        case -1:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND);
            return UINT32_MAX;
        case -2:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_NAME_TOO_LONG);
            return UINT32_MAX;
        case -3:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_TOO_MANY);
            return UINT32_MAX;
        case -4:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED);
            return UINT32_MAX;
    }
    /* can't happen */
    return UINT32_MAX;
}
bool tox_file_send_chunk (Tox * tox, uint32_t friend_number, uint32_t file_number, uint64_t position, const uint8_t * data, size_t length, TOX_ERR_FILE_SEND_CHUNK * error)
Send a chunk of file data to a friend.
This function is called in response to the file_chunk_request callback. The length parameter should be equal to the one received though the callback. If it is zero, the transfer is assumed complete. For files with known size, Core will know that the transfer is complete after the last byte has been received, so it is not necessary (though not harmful) to send a zero-length chunk to terminate. For streams, core will know that the transfer is finished if a chunk with length less than the length requested in the callback is sent.
Parameters
friend_number The friend number of the receiving friend for this file.
file_number The file transfer identifier returned by tox_file_send.
position The file or stream position from which to continue reading.
Returns
true on success.
Definition at line 1080 of file tox.c.
References file_data(), m, SET_ERROR_PARAMETER, TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED, TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND, TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH, TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND, TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING, TOX_ERR_FILE_SEND_CHUNK_OK, TOX_ERR_FILE_SEND_CHUNK_SENDQ, and TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION.
Referenced by tox_file_chunk_request().
{
    Messenger *m = tox;
    int ret = file_data(m, friend_number, file_number, position,
      data, length);
    if (ret == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_OK);
        return 1;
    }
    switch (ret) {
        case -1:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND);
            return 0;
        case -2:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED);
            return 0;
        case -3:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND);
            return 0;
        case -4:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING);
            return 0;
        case -5:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH);
            return 0;
        case -6:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_SENDQ);
            return 0;
        case -7:
            SET_ERROR_PARAMETER(error,
      TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION);
            return 0;
    }
    /* can't happen */
    return 0;
}
uint32_t tox_friend_add (Tox * tox, const uint8_t * address, const uint8_t * message, size_t length, TOX_ERR_FRIEND_ADD * error)
Add a friend to the friend list and send a friend request.
A friend request message must be at least 1 byte long and at most TOX_MAX_FRIEND_REQUEST_LENGTH.
Friend numbers are unique identifiers used in all functions that operate on friends. Once added, a friend number is stable for the lifetime of the Tox object. After saving the state and reloading it, the friend numbers may not be the same as before. Deleting a friend creates a gap in the friend number set, which is filled by the next adding of a friend. Any pattern in friend numbers should not be relied on.
If more than INT32_MAX friends are added, this function causes undefined behaviour.
Parameters
address The address of the friend (returned by tox_self_get_address of the friend you wish to add) it must be TOX_ADDRESS_SIZE bytes.
message The message that will be sent along with the friend request.
length The length of the data byte array.
Returns
the friend number on success, UINT32_MAX on failure.
Definition at line 557 of file tox.c.
References m, m_addfriend(), SET_ERROR_PARAMETER, set_friend_error(), TOX_ERR_FRIEND_ADD_NULL, and TOX_ERR_FRIEND_ADD_OK.
Referenced by init_tox(), line_eval(), main(), and START_TEST().
{
    if (!address || !message) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_ADD_NULL);
        return UINT32_MAX;
    }
    Messenger *m = tox;
    int32_t ret = m_addfriend(m, address, message, length);
    if (ret >= 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_ADD_OK);
        return ret;
    }
    set_friend_error(ret, error);
    return UINT32_MAX;
}
uint32_t tox_friend_add_norequest (Tox * tox, const uint8_t * public_key, TOX_ERR_FRIEND_ADD * error)
Add a friend without sending a friend request.
This function is used to add a friend in response to a friend request. If the client receives a friend request, it can be reasonably sure that the other client added this client as a friend, eliminating the need for a friend request.
This function is also useful in a situation where both instances are controlled by the same entity, so that this entity can perform the mutual friend adding. In this case, there is no need for a friend request, either.
Parameters
public_key A byte array of length TOX_PUBLIC_KEY_SIZE containing the Public Key (not the Address) of the friend to add.
Returns
the friend number on success, UINT32_MAX on failure.
See also
tox_friend_add for a more detailed description of friend numbers.
Definition at line 577 of file tox.c.
References m, m_addfriend_norequest(), SET_ERROR_PARAMETER, set_friend_error(), TOX_ERR_FRIEND_ADD_NULL, and TOX_ERR_FRIEND_ADD_OK.
Referenced by accept_friend_request(), g_accept_friend_request(), and line_eval().
{
    if (!public_key) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_ADD_NULL);
        return UINT32_MAX;
    }
    Messenger *m = tox;
    int32_t ret = m_addfriend_norequest(m, public_key);
    if (ret >= 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_ADD_OK);
        return ret;
    }
    set_friend_error(ret, error);
    return UINT32_MAX;
}
uint32_t tox_friend_by_public_key (const Tox * tox, const uint8_t * public_key, TOX_ERR_FRIEND_BY_PUBLIC_KEY * error)
Return the friend number associated with that Public Key.
Returns
the friend number on success, UINT32_MAX on failure.
Parameters
public_key A byte array containing the Public Key.
Definition at line 611 of file tox.c.
References getfriend_id(), m, SET_ERROR_PARAMETER, TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND, TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL, and TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK.
{
    if (!public_key) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL);
        return UINT32_MAX;
    }
    const Messenger *m = tox;
    int32_t ret = getfriend_id(m, public_key);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND);
        return UINT32_MAX;
    }
    SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK);
    return ret;
}
bool tox_friend_delete (Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_DELETE * error)
Remove a friend from the friend list.
This does not notify the friend of their deletion. After calling this function, this client will appear offline to the friend and no communication can occur between the two.
Parameters
friend_number Friend number for the friend to be deleted.
Returns
true on success.
Definition at line 596 of file tox.c.
References m, m_delfriend(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_DELETE_OK.
Referenced by line_eval().
{
    Messenger *m = tox;
    int ret = m_delfriend(m, friend_number);
    //TODO handle if realloc fails?
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_DELETE_OK);
    return 1;
}
bool tox_friend_exists (const Tox * tox, uint32_t friend_number)
Checks if a friend with the given friend number exists and returns true if it does.
Definition at line 648 of file tox.c.
References m, and m_friend_exists().
Referenced by line_eval().
{
    const Messenger *m = tox;
    return m_friend_exists(m, friend_number);
}
TOX_CONNECTION tox_friend_get_connection_status (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY * error)
Check whether a friend is currently connected to this client.
The result of this function is equal to the last value received by the friend_connection_status callback.
Parameters
friend_number The friend number for which to query the connection status.
Returns
the friend's connection status as it was received through the friend_connection_status event.
Definition at line 784 of file tox.c.
References m, m_get_friend_connectionstatus(), SET_ERROR_PARAMETER, TOX_CONNECTION_NONE, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by main(), START_TEST(), and while().
{
    const Messenger *m = tox;
    int ret = m_get_friend_connectionstatus(m,
      friend_number);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return TOX_CONNECTION_NONE;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return ret;
}
uint64_t tox_friend_get_last_online (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_GET_LAST_ONLINE * error)
Return a unix-time timestamp of the last time the friend associated with a given friend number was seen online. This function will return UINT64_MAX on error.
Parameters
friend_number The friend number you want to query.
Definition at line 654 of file tox.c.
References m, m_get_last_online(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_GET_LAST_ONLINE_OK.
{
    const Messenger *m = tox;
    uint64_t timestamp = m_get_last_online(m, friend_number);
    if (timestamp == UINT64_MAX) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND)
        return UINT64_MAX;
    }
    SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_GET_LAST_ONLINE_OK);
    return timestamp;
}
bool tox_friend_get_name (const Tox * tox, uint32_t friend_number, uint8_t * name, TOX_ERR_FRIEND_QUERY * error)
Write the name of the friend designated by the given friend number to a byte array.
Call tox_friend_get_name_size to determine the allocation size for the name parameter.
The data written to name is equal to the data received by the last friend_name callback.
Parameters
name A valid memory region large enough to store the friend's name.
Returns
true on success.
Definition at line 697 of file tox.c.
References getname(), m, SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, TOX_ERR_FRIEND_QUERY_NULL, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by getfriendname_terminated(), and START_TEST().
{
    if (!name) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_NULL);
        return 0;
    }
    const Messenger *m = tox;
    int ret = getname(m, friend_number, name);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return 1;
}
size_t tox_friend_get_name_size (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY * error)
Return the length of the friend's name. If the friend number is invalid, the return value is unspecified.
The return value is equal to the length argument received by the last friend_name callback.
Definition at line 683 of file tox.c.
References m, m_get_name_size(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by getfriendname_terminated(), and START_TEST().
{
    const Messenger *m = tox;
    int ret = m_get_name_size(m, friend_number);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return SIZE_MAX;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return ret;
}
bool tox_friend_get_public_key (const Tox * tox, uint32_t friend_number, uint8_t * public_key, TOX_ERR_FRIEND_GET_PUBLIC_KEY * error)
Copies the Public Key associated with a given friend number to a byte array.
Parameters
friend_number The friend number you want the Public Key of.
public_key A memory region of at least TOX_PUBLIC_KEY_SIZE bytes. If this parameter is NULL, this function has no effect.
Returns
true on success.
Definition at line 630 of file tox.c.
References get_real_pk(), m, SET_ERROR_PARAMETER, TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK.
Referenced by print_friendlist(), and START_TEST().
{
    if (!public_key) {
        return 0;
    }
    const Messenger *m = tox;
    if (get_real_pk(m, friend_number, public_key) == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK);
    return 1;
}
TOX_USER_STATUS tox_friend_get_status (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY * error)
Return the friend's user status (away/busy/...). If the friend number is invalid, the return value is unspecified.
The status returned is equal to the last status received through the friend_status callback.
Definition at line 763 of file tox.c.
References m, m_get_userstatus(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, TOX_ERR_FRIEND_QUERY_OK, TOX_USER_STATUS_BUSY, and USERSTATUS_INVALID.
{
    const Messenger *m = tox;
    int ret = m_get_userstatus(m, friend_number);
    if (ret == USERSTATUS_INVALID) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return TOX_USER_STATUS_BUSY + 1;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return ret;
}
bool tox_friend_get_status_message (const Tox * tox, uint32_t friend_number, uint8_t * status_message, TOX_ERR_FRIEND_QUERY * error)
Write the status message of the friend designated by the given friend number to a byte array.
Call tox_friend_get_status_message_size to determine the allocation size for the status_name parameter.
The data written to status_message is equal to the data received by the last friend_status_message callback.
Parameters
status_message A valid memory region large enough to store the friend's status message.
Definition at line 736 of file tox.c.
References m, m_copy_statusmessage(), m_get_statusmessage_size(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, TOX_ERR_FRIEND_QUERY_NULL, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by START_TEST().
{
    if (!message) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_NULL);
        return 0;
    }
    const Messenger *m = tox;
    //TODO: size parameter?
    int ret = m_copy_statusmessage(m, friend_number, message,
      m_get_statusmessage_size(m, friend_number));
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return 1;
}
size_t tox_friend_get_status_message_size (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY * error)
Return the length of the friend's status message. If the friend number is invalid, the return value is SIZE_MAX.
Definition at line 722 of file tox.c.
References m, m_get_statusmessage_size(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    int ret = m_get_statusmessage_size(m, friend_number);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return SIZE_MAX;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return ret;
}
bool tox_friend_get_typing (const Tox * tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY * error)
Check whether a friend is currently typing a message.
Parameters
friend_number The friend number for which to query the typing status.
Returns
true if the friend is typing.
false if the friend is not typing, or the friend number was invalid. Inspect the error code to determine which case it is.
Definition at line 805 of file tox.c.
References m, m_get_istyping(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND, and TOX_ERR_FRIEND_QUERY_OK.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    int ret = m_get_istyping(m, friend_number);
    if (ret == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_FRIEND_QUERY_OK);
    return !!ret;
}
bool tox_friend_send_lossless_packet (Tox * tox, uint32_t friend_number, const uint8_t * data, size_t length, TOX_ERR_FRIEND_CUSTOM_PACKET * error)
Send a custom lossless packet to a friend.
The first byte of data must be in the range 160-191. Maximum length of a custom packet is TOX_MAX_CUSTOM_PACKET_SIZE.
Lossless packet behaviour is comparable to TCP (reliability, arrive in order) but with packets instead of a stream.
Parameters
friend_number The friend number of the friend this lossless packet should be sent to.
data A byte array containing the packet data.
length The length of the packet data byte array.
Returns
true on success.
Definition at line 1209 of file tox.c.
References m, send_custom_lossless_packet(), set_custom_packet_error(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY, and TOX_ERR_FRIEND_CUSTOM_PACKET_NULL.
Referenced by START_TEST().
{
    if (!data) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_CUSTOM_PACKET_NULL);
        return 0;
    }
    Messenger *m = tox;
    if (length == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY);
        return 0;
    }
    int ret = send_custom_lossless_packet(m,
      friend_number, data, length);
    set_custom_packet_error(ret, error);
    if (ret == 0) {
        return 1;
    } else {
        return 0;
    }
}
bool tox_friend_send_lossy_packet (Tox * tox, uint32_t friend_number, const uint8_t * data, size_t length, TOX_ERR_FRIEND_CUSTOM_PACKET * error)
Send a custom lossy packet to a friend.
The first byte of data must be in the range 200-254. Maximum length of a custom packet is TOX_MAX_CUSTOM_PACKET_SIZE.
Lossy packets behave like UDP packets, meaning they might never reach the other side or might arrive more than once (if someone is messing with the connection) or might arrive in the wrong order.
Unless latency is an issue, it is recommended that you use lossless custom packets instead.
Parameters
friend_number The friend number of the friend this lossy packet should be sent to.
data A byte array containing the packet data.
length The length of the packet data byte array.
Returns
true on success.
Definition at line 1172 of file tox.c.
References m, PACKET_ID_LOSSY_RANGE_START, PACKET_LOSSY_AV_RESERVED, send_custom_lossy_packet(), set_custom_packet_error(), SET_ERROR_PARAMETER, TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY, TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID, and TOX_ERR_FRIEND_CUSTOM_PACKET_NULL.
Referenced by START_TEST().
{
    if (!data) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_CUSTOM_PACKET_NULL);
        return 0;
    }
    Messenger *m = tox;
    if (length == 0) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY);
        return 0;
    }
    if (data[0] < (PACKET_ID_LOSSY_RANGE_START +
      PACKET_LOSSY_AV_RESERVED)) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID);
        return 0;
    }
    int ret = send_custom_lossy_packet(m, friend_number,
      data, length);
    set_custom_packet_error(ret, error);
    if (ret == 0) {
        return 1;
    } else {
        return 0;
    }
}
uint32_t tox_friend_send_message (Tox * tox, uint32_t friend_number, TOX_MESSAGE_TYPE type, const uint8_t * message, size_t length, TOX_ERR_FRIEND_SEND_MESSAGE * error)
Send a text chat message to an online friend.
This function creates a chat message packet and pushes it into the send queue.
The message length may not exceed TOX_MAX_MESSAGE_LENGTH. Larger messages must be split by the client and sent as separate messages. Other clients can then reassemble the fragments. Messages may not be empty.
The return value of this function is the message ID. If a read receipt is received, the triggered friend_read_receipt event will be passed this message ID.
Message IDs are unique per friend. The first message ID is 0. Message IDs are incremented by 1 each time a message is sent. If UINT32_MAX messages were sent, the next message ID is 0.
Parameters
type Message type (normal, action, ...).
friend_number The friend number of the friend to send the message to.
message A non-NULL pointer to the first element of a byte array containing the message text.
length Length of the message to be sent.
Definition at line 867 of file tox.c.
References m, m_send_message_generic(), SET_ERROR_PARAMETER, set_message_error(), TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY, and TOX_ERR_FRIEND_SEND_MESSAGE_NULL.
Referenced by line_eval(), main(), and START_TEST().
{
    if (!message) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_SEND_MESSAGE_NULL);
        return 0;
    }
    if (!length) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY);
        return 0;
    }
    Messenger *m = tox;
    uint32_t message_id = 0;
    set_message_error(m_send_message_generic(m,
      friend_number, type, message, length, &message_id), error);
    return message_id;
}
void tox_get_savedata (const Tox * tox, uint8_t * savedata)
Store all information associated with the tox instance to a byte array.
Parameters
data A memory region large enough to store the tox instance data. Call tox_get_savedata_size to find the number of bytes required. If this parameter is NULL, this function has no effect.
Definition at line 252 of file tox.c.
References m, and messenger_save().
Referenced by save_data(), and START_TEST().
{
    if (data) {
        const Messenger *m = tox;
        messenger_save(m, data);
    }
}
size_t tox_get_savedata_size (const Tox * tox)
Calculates the number of bytes required to store the tox instance with tox_get_savedata. This function cannot fail. The result is always greater than 0.
See also
threading for concurrency implications.
Definition at line 246 of file tox.c.
References m, and messenger_size().
Referenced by save_data(), and START_TEST().
{
    const Messenger *m = tox;
    return messenger_size(m);
}
bool tox_hash (uint8_t * hash, const uint8_t * data, size_t length)
Generates a cryptographic hash of the given data.
This function may be used by clients for any purpose, but is provided primarily for validating cached avatars. This use is highly recommended to avoid unnecessary avatar updates.
If hash is NULL or data is NULL while length is not 0 the function returns false, otherwise it returns true.
This function is a wrapper to internal message-digest functions.
Parameters
hash A valid memory location the hash data. It must be at least TOX_HASH_LENGTH bytes in size.
data Data to be hashed or NULL.
length Size of the data array or 0.
Returns
true if hash was not NULL.
Definition at line 904 of file tox.c.
{
    if (!hash || (length && !data)) {
        return 0;
    }
    crypto_hash_sha256(hash, data, length);
    return 1;
}
void tox_iterate (Tox * tox)
The main loop that needs to be run in intervals of tox_iteration_interval() milliseconds.
Definition at line 402 of file tox.c.
References do_groupchats(), do_messenger(), Messenger::group_chat_object, and m.
Referenced by line_eval(), main(), START_TEST(), and while().
{
    Messenger *m = tox;
    do_messenger(m);
    do_groupchats(m->group_chat_object);
}
uint32_t tox_iteration_interval (const Tox * tox)
Return the time in milliseconds before tox_iterate() should be called again for optimal performance.
Definition at line 396 of file tox.c.
References m, and messenger_run_interval().
Referenced by START_TEST(), and timeout_getch().
{
    const Messenger *m = tox;
    return messenger_run_interval(m);
}
void tox_kill (Tox * tox)
Releases all resources associated with the Tox instance and disconnects from the network.
After calling this function, the Tox pointer becomes invalid. No other functions can be called, and the pointer value can no longer be read.
Definition at line 238 of file tox.c.
References Messenger::group_chat_object, kill_groupchats(), kill_messenger(), logger_kill_global(), and m.
{
    Messenger *m = tox;
    kill_groupchats(m->group_chat_object);
    kill_messenger(m);
    logger_kill_global();
}
Tox* tox_new (const struct Tox_Options * options, TOX_ERR_NEW * error)
Creates and initialises a new Tox instance with the options passed.
This function will bring the instance into a valid state. Running the event loop with a new instance will operate correctly.
If loading failed or succeeded only partially, the new or partially loaded instance is returned and an error code is set.
Parameters
options An options object as described above. If this parameter is NULL, the default options are used.
See also
tox_iterate for the event loop.
Returns
A new Tox instance pointer on success or NULL on failure.
Definition at line 124 of file tox.c.
References addr_resolve_or_parse_ip(), Tox_Options::end_port, IP::family, IP_Port::ip, ip_init(), TCP_Proxy_Info::ip_port, Tox_Options::ipv6_enabled, Messenger_Options::ipv6enabled, kill_messenger(), load_secret_key(), logger_get_global(), LOGGER_LEVEL, logger_new(), LOGGER_OUTPUT_FILE, logger_set_global(), m, MESSENGER_ERROR_PORT, MESSENGER_ERROR_TCP_SERVER, messenger_load(), Messenger::net_crypto, new_groupchats(), new_messenger(), IP_Port::port, Messenger_Options::port_range, Tox_Options::proxy_host, Messenger_Options::proxy_info, Tox_Options::proxy_port, TCP_Proxy_Info::proxy_type, Tox_Options::proxy_type, Tox_Options::savedata_data, Tox_Options::savedata_length, Tox_Options::savedata_type, SET_ERROR_PARAMETER, Tox_Options::start_port, Tox_Options::tcp_port, TCP_PROXY_HTTP, TCP_PROXY_NONE, TCP_PROXY_SOCKS5, Messenger_Options::tcp_server_port, TOX_ENABLE_IPV6_DEFAULT, TOX_ENC_SAVE_MAGIC_LENGTH, TOX_ENC_SAVE_MAGIC_NUMBER, TOX_ERR_NEW_LOAD_BAD_FORMAT, TOX_ERR_NEW_LOAD_ENCRYPTED, TOX_ERR_NEW_MALLOC, TOX_ERR_NEW_OK, TOX_ERR_NEW_PORT_ALLOC, TOX_ERR_NEW_PROXY_BAD_HOST, TOX_ERR_NEW_PROXY_BAD_PORT, TOX_ERR_NEW_PROXY_BAD_TYPE, TOX_PROXY_TYPE_HTTP, TOX_PROXY_TYPE_NONE, TOX_PROXY_TYPE_SOCKS5, TOX_SAVEDATA_TYPE_NONE, TOX_SAVEDATA_TYPE_SECRET_KEY, TOX_SAVEDATA_TYPE_TOX_SAVE, TOX_SECRET_KEY_SIZE, Messenger_Options::udp_disabled, and Tox_Options::udp_enabled.
Referenced by init_tox(), load_data(), main(), and START_TEST().
{
    if (!logger_get_global())
        logger_set_global(logger_new(
      LOGGER_OUTPUT_FILE, LOGGER_LEVEL, "toxcore"));
    Messenger_Options m_options = {0};
    _Bool load_savedata_sk = 0, load_savedata_tox = 0;
    if (options == NULL) {
        m_options.ipv6enabled = TOX_ENABLE_IPV6_DEFAULT;
    } else {
        if (options->savedata_type != TOX_SAVEDATA_TYPE_NONE) {
            if (options->savedata_data == NULL || options->
      savedata_length == 0) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_LOAD_BAD_FORMAT);
                return NULL;
            }
        }
        if (options->savedata_type == TOX_SAVEDATA_TYPE_SECRET_KEY
      ) {
            if (options->savedata_length != TOX_SECRET_KEY_SIZE) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_LOAD_BAD_FORMAT);
                return NULL;
            }
            load_savedata_sk = 1;
        } else if (options->savedata_type ==
      TOX_SAVEDATA_TYPE_TOX_SAVE) {
            if (options->savedata_length <
      TOX_ENC_SAVE_MAGIC_LENGTH) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_LOAD_BAD_FORMAT);
                return NULL;
            }
            if (memcmp(options->savedata_data,
      TOX_ENC_SAVE_MAGIC_NUMBER, TOX_ENC_SAVE_MAGIC_LENGTH) ==
      0) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_LOAD_ENCRYPTED);
                return NULL;
            }
            load_savedata_tox = 1;
        }
        m_options.ipv6enabled = options->ipv6_enabled;
        m_options.udp_disabled = !options->udp_enabled;
        m_options.port_range[0] = options->start_port;
        m_options.port_range[1] = options->end_port;
        m_options.tcp_server_port = options->tcp_port;
        switch (options->proxy_type) {
            case TOX_PROXY_TYPE_HTTP:
                m_options.proxy_info.proxy_type =
      TCP_PROXY_HTTP;
                break;
            case TOX_PROXY_TYPE_SOCKS5:
                m_options.proxy_info.proxy_type =
      TCP_PROXY_SOCKS5;
                break;
            case TOX_PROXY_TYPE_NONE:
                m_options.proxy_info.proxy_type =
      TCP_PROXY_NONE;
                break;
            default:
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_PROXY_BAD_TYPE);
                return NULL;
        }
        if (m_options.proxy_info.proxy_type !=
      TCP_PROXY_NONE) {
            if (options->proxy_port == 0) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_PROXY_BAD_PORT);
                return NULL;
            }
            ip_init(&m_options.proxy_info.ip_port.ip, m_options.
      ipv6enabled);
            if (m_options.ipv6enabled)
                m_options.proxy_info.ip_port.ip.family = AF_UNSPEC;
            if (!addr_resolve_or_parse_ip(options->
      proxy_host, &m_options.proxy_info.ip_port.ip, NULL)) {
                SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_PROXY_BAD_HOST);
                //TODO: TOX_ERR_NEW_PROXY_NOT_FOUND if domain.
                return NULL;
            }
            m_options.proxy_info.ip_port.port = htons(options->
      proxy_port);
        }
    }
    unsigned int m_error;
    Messenger *m = new_messenger(&m_options, &m_error);
    if (!new_groupchats(m)) {
        kill_messenger(m);
        if (m_error == MESSENGER_ERROR_PORT) {
            SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_PORT_ALLOC);
        } else if (m_error == MESSENGER_ERROR_TCP_SERVER) {
            SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_PORT_ALLOC);
        } else {
            SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_MALLOC);
        }
        return NULL;
    }
    if (load_savedata_tox && messenger_load(m, options->
      savedata_data, options->savedata_length) == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_NEW_LOAD_BAD_FORMAT);
    } else if (load_savedata_sk) {
        load_secret_key(m->net_crypto, options->
      savedata_data);
        SET_ERROR_PARAMETER(error, TOX_ERR_NEW_OK);
    } else {
        SET_ERROR_PARAMETER(error, TOX_ERR_NEW_OK);
    }
    return m;
}
void tox_options_default (struct Tox_Options * options)
Initialises a Tox_Options object with the default options.
The result of this function is independent of the original options. All values will be overwritten, no values will be read (so it is permissible to pass an uninitialised object).
If options is NULL, this function has no effect.
Parameters
options An options object to be filled with default options.
Definition at line 95 of file tox.c.
References Tox_Options::ipv6_enabled, Tox_Options::proxy_type, TOX_PROXY_TYPE_NONE, and Tox_Options::udp_enabled.
Referenced by load_data(), START_TEST(), and tox_options_new().
{
    if (options) {
        memset(options, 0, sizeof(struct Tox_Options));
        options->ipv6_enabled = 1;
        options->udp_enabled = 1;
        options->proxy_type = TOX_PROXY_TYPE_NONE;
    }
}
void tox_options_free (struct Tox_Options * options)
Releases all resources associated with an options objects.
Passing a pointer that was not returned by tox_options_new results in undefined behaviour.
Definition at line 119 of file tox.c.
Referenced by START_TEST().
{
    free(options);
}
struct Tox_Options* tox_options_new (TOX_ERR_OPTIONS_NEW * error)
Allocates a new Tox_Options object and initialises it with the default options. This function can be used to preserve long term ABI compatibility by giving the responsibility of allocation and deallocation to the Tox library.
Objects returned from this function must be freed using the tox_options_free function.
Returns
A new Tox_Options object with default options or NULL on failure.
Definition at line 105 of file tox.c.
References SET_ERROR_PARAMETER, TOX_ERR_OPTIONS_NEW_MALLOC, TOX_ERR_OPTIONS_NEW_OK, and tox_options_default().
Referenced by START_TEST().
{
    struct Tox_Options *options = calloc(sizeof(struct Tox_Options), 1);
    if (options) {
        tox_options_default(options);
        SET_ERROR_PARAMETER(error,
      TOX_ERR_OPTIONS_NEW_OK);
        return options;
    }
    SET_ERROR_PARAMETER(error,
      TOX_ERR_OPTIONS_NEW_MALLOC);
    return NULL;
}
void tox_self_get_address (const Tox * tox, uint8_t * address)
Writes the Tox friend address of the client to a byte array. The address is not in human-readable format. If a client wants to display the address, formatting is required.
Parameters
address A memory region of at least TOX_ADDRESS_SIZE bytes. If this parameter is NULL, this function has no effect.
See also
TOX_ADDRESS_SIZE for the address format.
Definition at line 409 of file tox.c.
References getaddress(), and m.
Referenced by get_id(), main(), and START_TEST().
{
    if (address) {
        const Messenger *m = tox;
        getaddress(m, address);
    }
}
TOX_CONNECTION tox_self_get_connection_status (const Tox * tox)
Return whether we are connected to the DHT. The return value is equal to the last value received through the self_connection_status callback.
Definition at line 374 of file tox.c.
References m, Messenger::onion_c, onion_connection_status(), TOX_CONNECTION_NONE, TOX_CONNECTION_TCP, and TOX_CONNECTION_UDP.
Referenced by main(), START_TEST(), and while().
{
    const Messenger *m = tox;
    unsigned int ret = onion_connection_status(m->onion_c);
    if (ret == 2) {
        return TOX_CONNECTION_UDP;
    } else if (ret == 1) {
        return TOX_CONNECTION_TCP;
    } else {
        return TOX_CONNECTION_NONE;
    }
}
void tox_self_get_dht_id (const Tox * tox, uint8_t * dht_id)
Writes the temporary DHT public key of this instance to a byte array.
This can be used in combination with an externally accessible IP address and the bound port (from tox_self_get_udp_port) to run a temporary bootstrap node.
Be aware that every time a new instance is created, the DHT public key changes, meaning this cannot be used to run a permanent bootstrap node.
Parameters
dht_id A memory region of at least TOX_PUBLIC_KEY_SIZE bytes. If this parameter is NULL, this function has no effect.
Definition at line 1241 of file tox.c.
References Messenger::dht, m, and DHT::self_public_key.
Referenced by START_TEST().
{
    if (dht_id) {
        const Messenger *m = tox;
        memcpy(dht_id , m->dht->self_public_key, crypto_box_PUBLICKEYBYTES);
    }
}
void tox_self_get_friend_list (const Tox * tox, uint32_t * friend_list)
Copy a list of valid friend numbers into an array.
Call tox_self_get_friend_list_size to determine the number of elements to allocate.
Parameters
list A memory region with enough space to hold the friend list. If this parameter is NULL, this function has no effect.
Definition at line 674 of file tox.c.
References copy_friendlist(), m, and tox_self_get_friend_list_size().
{
    if (list) {
        const Messenger *m = tox;
        //TODO: size parameter?
        copy_friendlist(m, list, tox_self_get_friend_list_size(
      tox));
    }
}
size_t tox_self_get_friend_list_size (const Tox * tox)
Return the number of friends on the friend list.
This function can be used to determine how much memory to allocate for tox_self_get_friend_list.
Definition at line 668 of file tox.c.
References count_friendlist(), and m.
Referenced by START_TEST(), and tox_self_get_friend_list().
{
    const Messenger *m = tox;
    return count_friendlist(m);
}
void tox_self_get_name (const Tox * tox, uint8_t * name)
Write the nickname set by tox_self_set_name to a byte array.
If no nickname was set before calling this function, the name is empty, and this function has no effect.
Call tox_self_get_name_size to find out how much memory to allocate for the result.
Parameters
name A valid memory location large enough to hold the nickname. If this parameter is NULL, the function has no effect.
Definition at line 471 of file tox.c.
References getself_name(), and m.
Referenced by main(), and START_TEST().
{
    if (name) {
        const Messenger *m = tox;
        getself_name(m, name);
    }
}
size_t tox_self_get_name_size (const Tox * tox)
Return the length of the current nickname as passed to tox_self_set_name.
If no nickname was set before calling this function, the name is empty, and this function returns 0.
See also
threading for concurrency implications.
Definition at line 465 of file tox.c.
References m, and m_get_self_name_size().
Referenced by main(), and START_TEST().
{
    const Messenger *m = tox;
    return m_get_self_name_size(m);
}
uint32_t tox_self_get_nospam (const Tox * tox)
Get the 4-byte nospam part of the address.
Definition at line 423 of file tox.c.
References Messenger::fr, get_nospam(), and m.
{
    const Messenger *m = tox;
    return get_nospam(&(m->fr));
}
void tox_self_get_public_key (const Tox * tox, uint8_t * public_key)
Copy the Tox Public Key (long term) from the Tox object.
Parameters
public_key A memory region of at least TOX_PUBLIC_KEY_SIZE bytes. If this parameter is NULL, this function has no effect.
Definition at line 429 of file tox.c.
References m, Messenger::net_crypto, and Net_Crypto::self_public_key.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    if (public_key)
        memcpy(public_key, m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES);
}
void tox_self_get_secret_key (const Tox * tox, uint8_t * secret_key)
Copy the Tox Secret Key from the Tox object.
Parameters
secret_key A memory region of at least TOX_SECRET_KEY_SIZE bytes. If this parameter is NULL, this function has no effect.
Definition at line 437 of file tox.c.
References m, Messenger::net_crypto, and Net_Crypto::self_secret_key.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    if (secret_key)
        memcpy(secret_key, m->net_crypto->self_secret_key,
      crypto_box_SECRETKEYBYTES);
}
TOX_USER_STATUS tox_self_get_status (const Tox * tox)
Returns the client's user status.
Definition at line 517 of file tox.c.
References m, and m_get_self_userstatus().
{
    const Messenger *m = tox;
    return m_get_self_userstatus(m);
}
void tox_self_get_status_message (const Tox * tox, uint8_t * status_message)
Write the status message set by tox_self_set_status_message to a byte array.
If no status message was set before calling this function, the status is empty, and this function has no effect.
Call tox_self_get_status_message_size to find out how much memory to allocate for the result.
Parameters
status A valid memory location large enough to hold the status message. If this parameter is NULL, the function has no effect.
Definition at line 503 of file tox.c.
References m, and m_copy_self_statusmessage().
{
    if (status) {
        const Messenger *m = tox;
        m_copy_self_statusmessage(m, status);
    }
}
size_t tox_self_get_status_message_size (const Tox * tox)
Return the length of the current status message as passed to tox_self_set_status_message.
If no status message was set before calling this function, the status is empty, and this function returns 0.
See also
threading for concurrency implications.
Definition at line 497 of file tox.c.
References m, and m_get_self_statusmessage_size().
{
    const Messenger *m = tox;
    return m_get_self_statusmessage_size(m);
}
uint16_t tox_self_get_tcp_port (const Tox * tox, TOX_ERR_GET_PORT * error)
Return the TCP port this Tox instance is bound to. This is only relevant if the instance is acting as a TCP relay.
Definition at line 1263 of file tox.c.
References m, Messenger::options, SET_ERROR_PARAMETER, Messenger::tcp_server, Messenger_Options::tcp_server_port, TOX_ERR_GET_PORT_NOT_BOUND, and TOX_ERR_GET_PORT_OK.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    if (m->tcp_server) {
        SET_ERROR_PARAMETER(error, TOX_ERR_GET_PORT_OK);
        return m->options.tcp_server_port;
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_GET_PORT_NOT_BOUND);
        return 0;
    }
}
uint16_t tox_self_get_udp_port (const Tox * tox, TOX_ERR_GET_PORT * error)
Return the UDP port this Tox instance is bound to.
Definition at line 1249 of file tox.c.
References m, Messenger::net, port, Networking_Core::port, SET_ERROR_PARAMETER, TOX_ERR_GET_PORT_NOT_BOUND, and TOX_ERR_GET_PORT_OK.
Referenced by START_TEST().
{
    const Messenger *m = tox;
    uint16_t port = htons(m->net->port);
    if (port) {
        SET_ERROR_PARAMETER(error, TOX_ERR_GET_PORT_OK);
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_GET_PORT_NOT_BOUND);
    }
    return port;
}
bool tox_self_set_name (Tox * tox, const uint8_t * name, size_t length, TOX_ERR_SET_INFO * error)
Set the nickname for the Tox client.
Nickname length cannot exceed TOX_MAX_NAME_LENGTH. If length is 0, the name parameter is ignored (it can be NULL), and the nickname is set back to empty.
Parameters
name A byte array containing the new nickname.
length The size of the name byte array.
Returns
true on success.
Definition at line 445 of file tox.c.
References Messenger::group_chat_object, m, send_name_all_groups(), SET_ERROR_PARAMETER, setname(), TOX_ERR_SET_INFO_NULL, TOX_ERR_SET_INFO_OK, and TOX_ERR_SET_INFO_TOO_LONG.
Referenced by init_tox(), line_eval(), and START_TEST().
{
    if (!name && length != 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_SET_INFO_NULL);
        return 0;
    }
    Messenger *m = tox;
    if (setname(m, name, length) == 0) {
        //TODO: function to set different per group names?
        send_name_all_groups(m->group_chat_object);
        SET_ERROR_PARAMETER(error, TOX_ERR_SET_INFO_OK);
        return 1;
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_SET_INFO_TOO_LONG);
        return 0;
    }
}
void tox_self_set_nospam (Tox * tox, uint32_t nospam)
Set the 4-byte nospam part of the address.
Parameters
nospam Any 32 bit unsigned integer.
Definition at line 417 of file tox.c.
References Messenger::fr, m, and set_nospam().
{
    Messenger *m = tox;
    set_nospam(&(m->fr), nospam);
}
void tox_self_set_status (Tox * tox, TOX_USER_STATUS status)
Set the client's user status.
Parameters
user_status One of the user statuses listed in the enumeration above.
Definition at line 511 of file tox.c.
References m, and m_set_userstatus().
{
    Messenger *m = tox;
    m_set_userstatus(m, user_status);
}
bool tox_self_set_status_message (Tox * tox, const uint8_t * status_message, size_t length, TOX_ERR_SET_INFO * error)
Set the client's status message.
Status message length cannot exceed TOX_MAX_STATUS_MESSAGE_LENGTH. If length is 0, the status parameter is ignored (it can be NULL), and the user status is set back to empty.
Definition at line 479 of file tox.c.
References m, m_set_statusmessage(), SET_ERROR_PARAMETER, TOX_ERR_SET_INFO_NULL, TOX_ERR_SET_INFO_OK, and TOX_ERR_SET_INFO_TOO_LONG.
Referenced by line_eval(), and START_TEST().
{
    if (!status && length != 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_SET_INFO_NULL);
        return 0;
    }
    Messenger *m = tox;
    if (m_set_statusmessage(m, status, length) == 0) {
        SET_ERROR_PARAMETER(error, TOX_ERR_SET_INFO_OK);
        return 1;
    } else {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_SET_INFO_TOO_LONG);
        return 0;
    }
}
bool tox_self_set_typing (Tox * tox, uint32_t friend_number, bool typing, TOX_ERR_SET_TYPING * error)
Set the client's typing status for a friend.
The client is responsible for turning it on or off.
Parameters
friend_number The friend to which the client is typing a message.
typing The typing status. True means the client is typing.
Returns
true on success.
Definition at line 825 of file tox.c.
References m, m_set_usertyping(), SET_ERROR_PARAMETER, TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND, and TOX_ERR_SET_TYPING_OK.
Referenced by START_TEST().
{
    Messenger *m = tox;
    if (m_set_usertyping(m, friend_number, is_typing) == -1) {
        SET_ERROR_PARAMETER(error,
      TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND);
        return 0;
    }
    SET_ERROR_PARAMETER(error, TOX_ERR_SET_TYPING_OK);
    return 1;
}
bool tox_version_is_compatible (uint32_t major, uint32_t minor, uint32_t patch)
Return whether the compiled library version is compatible with the passed version numbers.
Definition at line 88 of file tox.c.
{
    //TODO
    return 1;
}
uint32_t tox_version_major (void)
Return the major version number of the library. Can be used to display the Tox library version or to check whether the client is compatible with the dynamically linked version of Tox.
Definition at line 73 of file tox.c.
{
    return 0;
}
uint32_t tox_version_minor (void)
Return the minor version number of the library.
Definition at line 78 of file tox.c.
{
    return 0;
}
uint32_t tox_version_patch (void)
Return the patch number of the library.
Definition at line 83 of file tox.c.
{
    return 0;
}