toxcore/onion_announce.h File Reference
#include `onion.h`
*
Data Structures
struct Onion_Announce_Entry
struct Onion_Announce
Macros
#define ONION_ANNOUNCE_MAX_ENTRIES 160
#define ONION_ANNOUNCE_TIMEOUT 300
#define ONION_PING_ID_SIZE crypto_hash_sha256_BYTES
#define ONION_ANNOUNCE_SENDBACK_DATA_LENGTH (sizeof(uint64_t))
#define ONION_ANNOUNCE_REQUEST_SIZE (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES + crypto_box_PUBLICKEYBYTES + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH + crypto_box_MACBYTES)
#define ONION_ANNOUNCE_RESPONSE_MIN_SIZE (1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH + crypto_box_NONCEBYTES + 1 + ONION_PING_ID_SIZE + crypto_box_MACBYTES)
#define ONION_ANNOUNCE_RESPONSE_MAX_SIZE (ONION_ANNOUNCE_RESPONSE_MIN_SIZE + sizeof(Node_format)*MAX_SENT_NODES)
#define ONION_DATA_RESPONSE_MIN_SIZE (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
#define ONION_DATA_REQUEST_MIN_SIZE (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
#define MAX_DATA_REQUEST_SIZE (ONION_MAX_DATA_SIZE - ONION_DATA_REQUEST_MIN_SIZE)
Functions
int create_announce_request (uint8_t *packet, uint16_t max_packet_length, const uint8_t *dest_client_id, const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *ping_id, const uint8_t *client_id, const uint8_t *data_public_key, uint64_t sendback_data)
int create_data_request (uint8_t *packet, uint16_t max_packet_length, const uint8_t *public_key, const uint8_t *encrypt_public_key, const uint8_t *nonce, const uint8_t *data, uint16_t length)
int send_announce_request (Networking_Core *net, const Onion_Path *path, Node_format dest, const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *ping_id, const uint8_t *client_id, const uint8_t *data_public_key, uint64_t sendback_data)
int send_data_request (Networking_Core *net, const Onion_Path *path, IP_Port dest, const uint8_t *public_key, const uint8_t *encrypt_public_key, const uint8_t *nonce, const uint8_t *data, uint16_t length)
Onion_Announce * new_onion_announce (DHT *dht)
void kill_onion_announce (Onion_Announce *onion_a)
Macro Definition Documentation
#define MAX_DATA_REQUEST_SIZE (ONION_MAX_DATA_SIZE - ONION_DATA_REQUEST_MIN_SIZE)
Definition at line 46 of file onion_announce.h.
Referenced by handle_data_response(), and send_onion_data().
#define ONION_ANNOUNCE_MAX_ENTRIES 160
Definition at line 28 of file onion_announce.h.
Referenced by add_to_entries(), in_entries(), and START_TEST().
#define ONION_ANNOUNCE_REQUEST_SIZE (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES + crypto_box_PUBLICKEYBYTES + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH + crypto_box_MACBYTES)
Definition at line 34 of file onion_announce.h.
Referenced by client_send_announce_request(), create_announce_request(), and send_announce_request().
#define ONION_ANNOUNCE_RESPONSE_MAX_SIZE (ONION_ANNOUNCE_RESPONSE_MIN_SIZE + sizeof(Node_format)*MAX_SENT_NODES)
Definition at line 37 of file onion_announce.h.
Referenced by handle_announce_request(), and handle_announce_response().
#define ONION_ANNOUNCE_RESPONSE_MIN_SIZE (1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH + crypto_box_NONCEBYTES + 1 + ONION_PING_ID_SIZE + crypto_box_MACBYTES)
Definition at line 36 of file onion_announce.h.
Referenced by handle_announce_response().
#define ONION_ANNOUNCE_SENDBACK_DATA_LENGTH (sizeof(uint64_t))
Definition at line 32 of file onion_announce.h.
Referenced by create_announce_request(), handle_announce_request(), handle_announce_response(), and handle_test_3().
#define ONION_ANNOUNCE_TIMEOUT 300
Definition at line 29 of file onion_announce.h.
Referenced by add_to_entries(), cmp_entry(), and in_entries().
#define ONION_DATA_REQUEST_MIN_SIZE (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
Definition at line 45 of file onion_announce.h.
#define ONION_DATA_RESPONSE_MIN_SIZE (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
Definition at line 39 of file onion_announce.h.
Referenced by handle_data_response().
#define ONION_PING_ID_SIZE crypto_hash_sha256_BYTES
Definition at line 30 of file onion_announce.h.
Referenced by client_add_to_list(), client_send_announce_request(), create_announce_request(), handle_announce_request(), and handle_announce_response().
Function Documentation
int create_announce_request (uint8_t * packet, uint16_t max_packet_length, const uint8_t * dest_client_id, const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * ping_id, const uint8_t * client_id, const uint8_t * data_public_key, uint64_t sendback_data)
Definition at line 50 of file onion_announce.c.
References encrypt_data(), NET_PACKET_ANNOUNCE_REQUEST, ONION_ANNOUNCE_REQUEST_SIZE, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, ONION_PING_ID_SIZE, and random_nonce().
Referenced by client_send_announce_request(), and send_announce_request().
{
    if (max_packet_length < ONION_ANNOUNCE_REQUEST_SIZE)
        return -1;
    uint8_t plain[ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES +
                  ONION_ANNOUNCE_SENDBACK_DATA_LENGTH];
    memcpy(plain, ping_id, ONION_PING_ID_SIZE);
    memcpy(plain + ONION_PING_ID_SIZE, client_id, crypto_box_PUBLICKEYBYTES);
    memcpy(plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES, data_public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES, &sendback_data,
           sizeof(sendback_data));
    packet[0] = NET_PACKET_ANNOUNCE_REQUEST;
    random_nonce(packet + 1);
    int len = encrypt_data(dest_client_id, secret_key, packet + 1, plain, sizeof(plain),
                           packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES);
    if ((uint32_t)len + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES !=
      ONION_ANNOUNCE_REQUEST_SIZE)
        return -1;
    memcpy(packet + 1 + crypto_box_NONCEBYTES, public_key, crypto_box_PUBLICKEYBYTES);
    return ONION_ANNOUNCE_REQUEST_SIZE;
}
int create_data_request (uint8_t * packet, uint16_t max_packet_length, const uint8_t * public_key, const uint8_t * encrypt_public_key, const uint8_t * nonce, const uint8_t * data, uint16_t length)
Definition at line 89 of file onion_announce.c.
References DATA_REQUEST_MIN_SIZE, encrypt_data(), NET_PACKET_ONION_DATA_REQUEST, and ONION_MAX_DATA_SIZE.
Referenced by send_data_request(), and send_onion_data().
{
    if (DATA_REQUEST_MIN_SIZE + length > max_packet_length)
        return -1;
    if ((unsigned int)DATA_REQUEST_MIN_SIZE + length >
      ONION_MAX_DATA_SIZE)
        return -1;
    packet[0] = NET_PACKET_ONION_DATA_REQUEST;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
    uint8_t random_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t random_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(random_public_key, random_secret_key);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES, random_public_key,
      crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data(encrypt_public_key, random_secret_key, packet + 1 +
      crypto_box_PUBLICKEYBYTES, data, length,
                           packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES +
      crypto_box_PUBLICKEYBYTES);
    if (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + len !=
      DATA_REQUEST_MIN_SIZE +
            length)
        return -1;
    return DATA_REQUEST_MIN_SIZE + length;
}
void kill_onion_announce (Onion_Announce * onion_a)
Definition at line 428 of file onion_announce.c.
References Onion_Announce::net, NET_PACKET_ANNOUNCE_REQUEST, NET_PACKET_ONION_DATA_REQUEST, and networking_registerhandler().
Referenced by kill_messenger(), kill_onions(), new_messenger(), and START_TEST().
{
    if (onion_a == NULL)
        return;
    networking_registerhandler(onion_a->net,
      NET_PACKET_ANNOUNCE_REQUEST, NULL, NULL);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ONION_DATA_REQUEST, NULL, NULL);
    free(onion_a);
}
Onion_Announce* new_onion_announce (DHT * dht)
Definition at line 408 of file onion_announce.c.
References Onion_Announce::dht, handle_announce_request(), handle_data_request(), Onion_Announce::net, DHT::net, NET_PACKET_ANNOUNCE_REQUEST, NET_PACKET_ONION_DATA_REQUEST, networking_registerhandler(), new_symmetric_key(), and Onion_Announce::secret_bytes.
Referenced by main(), new_messenger(), new_onions(), and START_TEST().
{
    if (dht == NULL)
        return NULL;
    Onion_Announce *onion_a = calloc(1, sizeof(Onion_Announce));
    if (onion_a == NULL)
        return NULL;
    onion_a->dht = dht;
    onion_a->net = dht->net;
    new_symmetric_key(onion_a->secret_bytes);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ANNOUNCE_REQUEST, &handle_announce_request,
      onion_a);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ONION_DATA_REQUEST, &handle_data_request,
      onion_a);
    return onion_a;
}
int send_announce_request (Networking_Core * net, const Onion_Path * path, Node_format dest, const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * ping_id, const uint8_t * client_id, const uint8_t * data_public_key, uint64_t sendback_data)
Definition at line 132 of file onion_announce.c.
References create_announce_request(), create_onion_packet(), Node_format::ip_port, Onion_Path::ip_port1, ONION_ANNOUNCE_REQUEST_SIZE, ONION_MAX_PACKET_SIZE, Node_format::public_key, and sendpacket().
Referenced by START_TEST().
{
    uint8_t request[ONION_ANNOUNCE_REQUEST_SIZE];
    int len = create_announce_request(request, sizeof(request), dest.
      public_key, public_key, secret_key, ping_id, client_id,
                                      data_public_key, sendback_data);
    if (len != sizeof(request))
        return -1;
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    len = create_onion_packet(packet, sizeof(packet), path, dest.
      ip_port, request, sizeof(request));
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}
int send_data_request (Networking_Core * net, const Onion_Path * path, IP_Port dest, const uint8_t * public_key, const uint8_t * encrypt_public_key, const uint8_t * nonce, const uint8_t * data, uint16_t length)
Definition at line 169 of file onion_announce.c.
References create_data_request(), create_onion_packet(), Onion_Path::ip_port1, ONION_MAX_DATA_SIZE, ONION_MAX_PACKET_SIZE, and sendpacket().
Referenced by START_TEST().
{
    uint8_t request[ONION_MAX_DATA_SIZE];
    int len = create_data_request(request, sizeof(request),
      public_key, encrypt_public_key, nonce, data, length);
    if (len == -1)
        return -1;
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    len = create_onion_packet(packet, sizeof(packet), path, dest, request, len);
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}