toxcore/onion.c File Reference
#include `onion.h`
*
#include `util.h`
*
Macros
#define RETURN_1 ONION_RETURN_1
#define RETURN_2 ONION_RETURN_2
#define RETURN_3 ONION_RETURN_3
#define SEND_BASE ONION_SEND_BASE
#define SEND_3 ONION_SEND_3
#define SEND_2 ONION_SEND_2
#define SEND_1 ONION_SEND_1
#define KEY_REFRESH_INTERVAL (2 * 60 * 60)
Functions
static void change_symmetric_key (Onion *onion)
static void ip_pack (uint8_t *data, IP source)
static int ip_unpack (IP *target, const uint8_t *data, unsigned int data_size, _Bool disable_family_check)
static void ipport_pack (uint8_t *data, const IP_Port *source)
static int ipport_unpack (IP_Port *target, const uint8_t *data, unsigned int data_size, _Bool disable_family_check)
int create_onion_path (const DHT *dht, Onion_Path *new_path, const Node_format *nodes)
int onion_path_to_nodes (Node_format *nodes, unsigned int num_nodes, const Onion_Path *path)
int create_onion_packet (uint8_t *packet, uint16_t max_packet_length, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int create_onion_packet_tcp (uint8_t *packet, uint16_t max_packet_length, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int send_onion_packet (Networking_Core *net, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int send_onion_response (Networking_Core *net, IP_Port dest, const uint8_t *data, uint16_t length, const uint8_t *ret)
static int handle_send_initial (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
int onion_send_1 (const Onion *onion, const uint8_t *plain, uint16_t len, IP_Port source, const uint8_t *nonce)
static int handle_send_1 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_send_2 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_recv_3 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_recv_2 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_recv_1 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
void set_callback_handle_recv_1 (Onion *onion, int(*function)(void *, IP_Port, const uint8_t *, uint16_t), void *object)
Onion * new_onion (DHT *dht)
void kill_onion (Onion *onion)
Macro Definition Documentation
#define KEY_REFRESH_INTERVAL (2 * 60 * 60)
Definition at line 39 of file onion.c.
Referenced by change_symmetric_key().
#define RETURN_1 ONION_RETURN_1
Definition at line 29 of file onion.c.
Referenced by handle_recv_1(), handle_recv_2(), and handle_send_1().
#define RETURN_2 ONION_RETURN_2
Definition at line 30 of file onion.c.
Referenced by handle_recv_2(), handle_recv_3(), handle_send_1(), and handle_send_2().
#define RETURN_3 ONION_RETURN_3
Definition at line 31 of file onion.c.
Referenced by handle_recv_3(), handle_send_2(), and send_onion_response().
#define SEND_1 ONION_SEND_1
Definition at line 36 of file onion.c.
Referenced by create_onion_packet(), and handle_send_initial().
#define SEND_2 ONION_SEND_2
Definition at line 35 of file onion.c.
Referenced by handle_send_1().
#define SEND_3 ONION_SEND_3
Definition at line 34 of file onion.c.
Referenced by handle_send_2().
#define SEND_BASE ONION_SEND_BASE
Definition at line 33 of file onion.c.
Referenced by create_onion_packet(), create_onion_packet_tcp(), and onion_send_1().
Function Documentation
static void change_symmetric_key (Onion * onion) [static]
Definition at line 40 of file onion.c.
References is_timeout(), KEY_REFRESH_INTERVAL, new_symmetric_key(), Onion::secret_symmetric_key, Onion::timestamp, and unix_time().
Referenced by handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), and handle_send_initial().
{
    if (is_timeout(onion->timestamp, KEY_REFRESH_INTERVAL)) {
        new_symmetric_key(onion->secret_symmetric_key);
        onion->timestamp = unix_time();
    }
}
int create_onion_packet (uint8_t * packet, uint16_t max_packet_length, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 173 of file onion.c.
References encrypt_data_symmetric(), Onion_Path::ip_port2, Onion_Path::ip_port3, ipport_pack(), NET_PACKET_ONION_SEND_INITIAL, nonce, Onion_Path::public_key1, Onion_Path::public_key2, Onion_Path::public_key3, random_nonce(), SEND_1, SEND_BASE, Onion_Path::shared_key1, Onion_Path::shared_key2, Onion_Path::shared_key3, and SIZE_IPPORT.
Referenced by send_announce_request(), send_data_request(), send_onion_packet(), and send_onion_packet_tcp_udp().
{
    if (1 + length + SEND_1 > max_packet_length || length == 0)
        return -1;
    uint8_t step1[SIZE_IPPORT + length];
    ipport_pack(step1, &dest);
    memcpy(step1 + SIZE_IPPORT, data, length);
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t step2[SIZE_IPPORT + SEND_BASE + length];
    ipport_pack(step2, &path->ip_port3);
    memcpy(step2 + SIZE_IPPORT, path->public_key3, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(path->shared_key3, nonce, step1,
      sizeof(step1),
                                     step2 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + length + crypto_box_MACBYTES)
        return -1;
    uint8_t step3[SIZE_IPPORT + SEND_BASE * 2 + length];
    ipport_pack(step3, &path->ip_port2);
    memcpy(step3 + SIZE_IPPORT, path->public_key2, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key2, nonce, step2, sizeof(
      step2),
                                 step3 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE + length + crypto_box_MACBYTES)
        return -1;
    packet[0] = NET_PACKET_ONION_SEND_INITIAL;
    memcpy(packet + 1, nonce, crypto_box_NONCEBYTES);
    memcpy(packet + 1 + crypto_box_NONCEBYTES, path->public_key1, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key1, nonce, step3, sizeof(
      step3),
                                 packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE * 2 + length + crypto_box_MACBYTES)
        return -1;
    return 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + len;
}
int create_onion_packet_tcp (uint8_t * packet, uint16_t max_packet_length, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 228 of file onion.c.
References encrypt_data_symmetric(), Onion_Path::ip_port2, Onion_Path::ip_port3, ipport_pack(), nonce, Onion_Path::public_key2, Onion_Path::public_key3, random_nonce(), SEND_BASE, Onion_Path::shared_key2, Onion_Path::shared_key3, and SIZE_IPPORT.
Referenced by send_onion_packet_tcp_udp().
{
    if (crypto_box_NONCEBYTES + SIZE_IPPORT + SEND_BASE * 2 + length >
      max_packet_length || length == 0)
        return -1;
    uint8_t step1[SIZE_IPPORT + length];
    ipport_pack(step1, &dest);
    memcpy(step1 + SIZE_IPPORT, data, length);
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t step2[SIZE_IPPORT + SEND_BASE + length];
    ipport_pack(step2, &path->ip_port3);
    memcpy(step2 + SIZE_IPPORT, path->public_key3, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(path->shared_key3, nonce, step1,
      sizeof(step1),
                                     step2 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + length + crypto_box_MACBYTES)
        return -1;
    ipport_pack(packet + crypto_box_NONCEBYTES, &path->ip_port2);
    memcpy(packet + crypto_box_NONCEBYTES + SIZE_IPPORT, path->
      public_key2, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key2, nonce, step2, sizeof(
      step2),
                                 packet + crypto_box_NONCEBYTES + SIZE_IPPORT +
      crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE + length + crypto_box_MACBYTES)
        return -1;
    memcpy(packet, nonce, crypto_box_NONCEBYTES);
    return crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES + len;
}
int create_onion_path (const DHT * dht, Onion_Path * new_path, const Node_format * nodes)
Definition at line 114 of file onion.c.
References encrypt_precompute(), Node_format::ip_port, Onion_Path::ip_port1, Onion_Path::ip_port2, Onion_Path::ip_port3, Onion_Path::node_public_key1, Onion_Path::node_public_key2, Onion_Path::node_public_key3, make-funny-savefile::public_key, Node_format::public_key, Onion_Path::public_key1, Onion_Path::public_key2, Onion_Path::public_key3, DHT::self_public_key, DHT::self_secret_key, Onion_Path::shared_key1, Onion_Path::shared_key2, and Onion_Path::shared_key3.
Referenced by random_path(), and START_TEST().
{
    if (!new_path || !nodes)
        return -1;
    encrypt_precompute(nodes[0].public_key, dht->
      self_secret_key, new_path->shared_key1);
    memcpy(new_path->public_key1, dht->self_public_key, crypto_box_PUBLICKEYBYTES
      );
    uint8_t random_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t random_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(random_public_key, random_secret_key);
    encrypt_precompute(nodes[1].public_key, random_secret_key, new_path->
      shared_key2);
    memcpy(new_path->public_key2, random_public_key, crypto_box_PUBLICKEYBYTES);
    crypto_box_keypair(random_public_key, random_secret_key);
    encrypt_precompute(nodes[2].public_key, random_secret_key, new_path->
      shared_key3);
    memcpy(new_path->public_key3, random_public_key, crypto_box_PUBLICKEYBYTES);
    new_path->ip_port1 = nodes[0].ip_port;
    new_path->ip_port2 = nodes[1].ip_port;
    new_path->ip_port3 = nodes[2].ip_port;
    memcpy(new_path->node_public_key1, nodes[0].public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(new_path->node_public_key2, nodes[1].public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(new_path->node_public_key3, nodes[2].public_key,
      crypto_box_PUBLICKEYBYTES);
    return 0;
}
static int handle_recv_1 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 541 of file onion.c.
References Onion::callback_object, change_symmetric_key(), decrypt_data_symmetric(), IP::family, IP_Port::ip, ipport_unpack(), Onion::net, ONION_MAX_PACKET_SIZE, Onion::recv_1_function, RETURN_1, Onion::secret_symmetric_key, sendpacket(), and SIZE_IPPORT.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + RETURN_1)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[SIZE_IPPORT];
    int len = decrypt_data_symmetric(onion->
      secret_symmetric_key, packet + 1, packet + 1 + crypto_box_NONCEBYTES,
                                     SIZE_IPPORT + crypto_box_MACBYTES, plain);
    if ((uint32_t)len != SIZE_IPPORT)
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 1) == -1)
        return 1;
    uint16_t data_len = length - (1 + RETURN_1);
    if (onion->recv_1_function && send_to.ip.family != AF_INET && send_to.
      ip.family != AF_INET6)
        return onion->recv_1_function(onion->callback_object, send_to, packet
       + (1 + RETURN_1), data_len);
    if ((uint32_t)sendpacket(onion->net, send_to, packet + (1 +
      RETURN_1), data_len) != data_len)
        return 1;
    return 0;
}
static int handle_recv_2 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 505 of file onion.c.
References change_symmetric_key(), make-funny-savefile::data, decrypt_data_symmetric(), ipport_unpack(), Onion::net, NET_PACKET_ONION_RECV_1, ONION_MAX_PACKET_SIZE, RETURN_1, RETURN_2, Onion::secret_symmetric_key, sendpacket(), and SIZE_IPPORT.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + RETURN_2)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[SIZE_IPPORT + RETURN_1];
    int len = decrypt_data_symmetric(onion->
      secret_symmetric_key, packet + 1, packet + 1 + crypto_box_NONCEBYTES,
                                     SIZE_IPPORT + RETURN_1 + crypto_box_MACBYTES, plain
      );
    if ((uint32_t)len != sizeof(plain))
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t data[ONION_MAX_PACKET_SIZE];
    data[0] = NET_PACKET_ONION_RECV_1;
    memcpy(data + 1, plain + SIZE_IPPORT, RETURN_1);
    memcpy(data + 1 + RETURN_1, packet + 1 + RETURN_2, length - (1 +
      RETURN_2));
    uint16_t data_len = 1 + RETURN_1 + (length - (1 + RETURN_2));
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
static int handle_recv_3 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 469 of file onion.c.
References change_symmetric_key(), make-funny-savefile::data, decrypt_data_symmetric(), ipport_unpack(), Onion::net, NET_PACKET_ONION_RECV_2, ONION_MAX_PACKET_SIZE, RETURN_2, RETURN_3, Onion::secret_symmetric_key, sendpacket(), and SIZE_IPPORT.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + RETURN_3)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[SIZE_IPPORT + RETURN_2];
    int len = decrypt_data_symmetric(onion->
      secret_symmetric_key, packet + 1, packet + 1 + crypto_box_NONCEBYTES,
                                     SIZE_IPPORT + RETURN_2 + crypto_box_MACBYTES, plain
      );
    if ((uint32_t)len != sizeof(plain))
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t data[ONION_MAX_PACKET_SIZE];
    data[0] = NET_PACKET_ONION_RECV_2;
    memcpy(data + 1, plain + SIZE_IPPORT, RETURN_2);
    memcpy(data + 1 + RETURN_2, packet + 1 + RETURN_3, length - (1 +
      RETURN_3));
    uint16_t data_len = 1 + RETURN_2 + (length - (1 + RETURN_3));
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
static int handle_send_1 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 370 of file onion.c.
References change_symmetric_key(), make-funny-savefile::data, decrypt_data_symmetric(), Onion::dht, encrypt_data_symmetric(), get_shared_key(), ipport_pack(), ipport_unpack(), Onion::net, NET_PACKET_ONION_SEND_2, new_nonce(), ONION_MAX_PACKET_SIZE, RETURN_1, RETURN_2, Onion::secret_symmetric_key, DHT::self_secret_key, SEND_2, sendpacket(), Onion::shared_keys_2, and SIZE_IPPORT.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + SEND_2)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[ONION_MAX_PACKET_SIZE];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    get_shared_key(&onion->shared_keys_2, shared_key, onion->
      dht->self_secret_key, packet + 1 + crypto_box_NONCEBYTES);
    int len = decrypt_data_symmetric(shared_key, packet + 1, packet + 1 +
      crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
                                     length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES +
      RETURN_1), plain);
    if (len != length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES +
      RETURN_1 + crypto_box_MACBYTES))
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t data[ONION_MAX_PACKET_SIZE];
    data[0] = NET_PACKET_ONION_SEND_2;
    memcpy(data + 1, packet + 1, crypto_box_NONCEBYTES);
    memcpy(data + 1 + crypto_box_NONCEBYTES, plain + SIZE_IPPORT, len -
      SIZE_IPPORT);
    uint16_t data_len = 1 + crypto_box_NONCEBYTES + (len - SIZE_IPPORT);
    uint8_t *ret_part = data + data_len;
    new_nonce(ret_part);
    uint8_t ret_data[RETURN_1 + SIZE_IPPORT];
    ipport_pack(ret_data, &source);
    memcpy(ret_data + SIZE_IPPORT, packet + (length - RETURN_1),
      RETURN_1);
    len = encrypt_data_symmetric(onion->
      secret_symmetric_key, ret_part, ret_data, sizeof(ret_data),
                                 ret_part + crypto_box_NONCEBYTES);
    if (len != RETURN_2 - crypto_box_NONCEBYTES)
        return 1;
    data_len += crypto_box_NONCEBYTES + len;
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
static int handle_send_2 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 420 of file onion.c.
References change_symmetric_key(), make-funny-savefile::data, decrypt_data_symmetric(), Onion::dht, encrypt_data_symmetric(), get_shared_key(), ipport_pack(), ipport_unpack(), Onion::net, new_nonce(), ONION_MAX_PACKET_SIZE, RETURN_2, RETURN_3, Onion::secret_symmetric_key, DHT::self_secret_key, SEND_3, sendpacket(), Onion::shared_keys_3, and SIZE_IPPORT.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + SEND_3)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[ONION_MAX_PACKET_SIZE];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    get_shared_key(&onion->shared_keys_3, shared_key, onion->
      dht->self_secret_key, packet + 1 + crypto_box_NONCEBYTES);
    int len = decrypt_data_symmetric(shared_key, packet + 1, packet + 1 +
      crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
                                     length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES +
      RETURN_2), plain);
    if (len != length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES +
      RETURN_2 + crypto_box_MACBYTES))
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t data[ONION_MAX_PACKET_SIZE];
    memcpy(data, plain + SIZE_IPPORT, len - SIZE_IPPORT);
    uint16_t data_len = (len - SIZE_IPPORT);
    uint8_t *ret_part = data + (len - SIZE_IPPORT);
    new_nonce(ret_part);
    uint8_t ret_data[RETURN_2 + SIZE_IPPORT];
    ipport_pack(ret_data, &source);
    memcpy(ret_data + SIZE_IPPORT, packet + (length - RETURN_2),
      RETURN_2);
    len = encrypt_data_symmetric(onion->
      secret_symmetric_key, ret_part, ret_data, sizeof(ret_data),
                                 ret_part + crypto_box_NONCEBYTES);
    if (len != RETURN_3 - crypto_box_NONCEBYTES)
        return 1;
    data_len += RETURN_3;
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
static int handle_send_initial (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 309 of file onion.c.
References change_symmetric_key(), decrypt_data_symmetric(), Onion::dht, get_shared_key(), ONION_MAX_PACKET_SIZE, onion_send_1(), DHT::self_secret_key, SEND_1, and Onion::shared_keys_1.
Referenced by new_onion().
{
    Onion *onion = object;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    if (length <= 1 + SEND_1)
        return 1;
    change_symmetric_key(onion);
    uint8_t plain[ONION_MAX_PACKET_SIZE];
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    get_shared_key(&onion->shared_keys_1, shared_key, onion->
      dht->self_secret_key, packet + 1 + crypto_box_NONCEBYTES);
    int len = decrypt_data_symmetric(shared_key, packet + 1, packet + 1 +
      crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
                                     length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES),
      plain);
    if (len != length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES))
        return 1;
    return onion_send_1(onion, plain, len, source, packet + 1);
}
static void ip_pack (uint8_t * data, IP source) [static]
Definition at line 49 of file onion.c.
References IP::family, IP::ip4, IP::ip6, SIZE_IP4, SIZE_IP6, to_net_family(), TOX_AF_INET, TOX_TCP_INET, IP4::uint8, and IP6::uint8.
Referenced by ipport_pack().
{
    to_net_family(&source);
    data[0] = source.family;
    if (source.family == TOX_AF_INET || source.family ==
      TOX_TCP_INET) {
        memset(data + 1, 0, SIZE_IP6);
        memcpy(data + 1, source.ip4.uint8, SIZE_IP4);
    } else {
        memcpy(data + 1, source.ip6.uint8, SIZE_IP6);
    }
}
static int ip_unpack (IP * target, const uint8_t * data, unsigned int data_size, _Bool disable_family_check) [static]
Definition at line 64 of file onion.c.
References IP::family, IP::ip4, IP::ip6, SIZE_IP4, SIZE_IP6, to_host_family(), TOX_AF_INET, TOX_TCP_INET, IP4::uint8, and IP6::uint8.
Referenced by ipport_unpack().
{
    if (data_size < (1 + SIZE_IP6))
        return -1;
    target->family = data[0];
    if (target->family == TOX_AF_INET || target->family ==
      TOX_TCP_INET) {
        memcpy(target->ip4.uint8, data + 1, SIZE_IP4);
    } else {
        memcpy(target->ip6.uint8, data + 1, SIZE_IP6);
    }
    if (!disable_family_check) {
        return to_host_family(target);
    } else {
        to_host_family(target);
        return 0;
    }
}
static void ipport_pack (uint8_t * data, const IP_Port * source) [static]
Definition at line 85 of file onion.c.
References IP_Port::ip, ip_pack(), IP_Port::port, SIZE_IP, and SIZE_PORT.
Referenced by create_onion_packet(), create_onion_packet_tcp(), handle_send_1(), handle_send_2(), and onion_send_1().
{
    ip_pack(data, source->ip);
    memcpy(data + SIZE_IP, &source->port, SIZE_PORT);
}
static int ipport_unpack (IP_Port * target, const uint8_t * data, unsigned int data_size, _Bool disable_family_check) [static]
Definition at line 92 of file onion.c.
References IP_Port::ip, ip_unpack(), IP_Port::port, SIZE_IP, and SIZE_PORT.
Referenced by handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), and onion_send_1().
{
    if (data_size < (SIZE_IP + SIZE_PORT))
        return -1;
    if (ip_unpack(&target->ip, data, data_size, disable_family_check) == -1)
        return -1;
    memcpy(&target->port, data + SIZE_IP, SIZE_PORT);
    return 0;
}
void kill_onion (Onion * onion)
Definition at line 608 of file onion.c.
References Onion::net, NET_PACKET_ONION_RECV_1, NET_PACKET_ONION_RECV_2, NET_PACKET_ONION_RECV_3, NET_PACKET_ONION_SEND_1, NET_PACKET_ONION_SEND_2, NET_PACKET_ONION_SEND_INITIAL, and networking_registerhandler().
Referenced by kill_messenger(), kill_onions(), new_messenger(), and START_TEST().
{
    if (onion == NULL)
        return;
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_INITIAL, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_1, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_2, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_3, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_2, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_1, NULL, NULL);
    free(onion);
}
Onion* new_onion (DHT * dht)
Definition at line 582 of file onion.c.
References Onion::dht, handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), handle_send_initial(), Onion::net, DHT::net, NET_PACKET_ONION_RECV_1, NET_PACKET_ONION_RECV_2, NET_PACKET_ONION_RECV_3, NET_PACKET_ONION_SEND_1, NET_PACKET_ONION_SEND_2, NET_PACKET_ONION_SEND_INITIAL, networking_registerhandler(), new_symmetric_key(), Onion::secret_symmetric_key, Onion::timestamp, and unix_time().
Referenced by main(), new_messenger(), new_onions(), and START_TEST().
{
    if (dht == NULL)
        return NULL;
    Onion *onion = calloc(1, sizeof(Onion));
    if (onion == NULL)
        return NULL;
    onion->dht = dht;
    onion->net = dht->net;
    new_symmetric_key(onion->secret_symmetric_key);
    onion->timestamp = unix_time();
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_INITIAL, &handle_send_initial, onion)
      ;
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_1, &handle_send_1, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_2, &handle_send_2, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_3, &handle_recv_3, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_2, &handle_recv_2, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_1, &handle_recv_1, onion);
    return onion;
}
int onion_path_to_nodes (Node_format * nodes, unsigned int num_nodes, const Onion_Path * path)
Definition at line 149 of file onion.c.
References Node_format::ip_port, Onion_Path::ip_port1, Onion_Path::ip_port2, Onion_Path::ip_port3, Onion_Path::node_public_key1, Onion_Path::node_public_key2, Onion_Path::node_public_key3, ONION_PATH_LENGTH, and make-funny-savefile::public_key.
Referenced by set_path_timeouts().
{
    if (num_nodes < ONION_PATH_LENGTH)
        return -1;
    nodes[0].ip_port = path->ip_port1;
    nodes[1].ip_port = path->ip_port2;
    nodes[2].ip_port = path->ip_port3;
    memcpy(nodes[0].public_key, path->node_public_key1, crypto_box_PUBLICKEYBYTES
      );
    memcpy(nodes[1].public_key, path->node_public_key2, crypto_box_PUBLICKEYBYTES
      );
    memcpy(nodes[2].public_key, path->node_public_key3, crypto_box_PUBLICKEYBYTES
      );
    return 0;
}
int onion_send_1 (const Onion * onion, const uint8_t * plain, uint16_t len, IP_Port source, const uint8_t * nonce)
Definition at line 333 of file onion.c.
References make-funny-savefile::data, encrypt_data_symmetric(), ipport_pack(), ipport_unpack(), Onion::net, NET_PACKET_ONION_SEND_1, new_nonce(), ONION_MAX_PACKET_SIZE, ONION_RETURN_1, Onion::secret_symmetric_key, SEND_BASE, sendpacket(), and SIZE_IPPORT.
Referenced by handle_send_initial(), and handle_TCP_packet().
{
    if (len > ONION_MAX_PACKET_SIZE + SIZE_IPPORT - (1 +
      crypto_box_NONCEBYTES + ONION_RETURN_1))
        return 1;
    if (len <= SIZE_IPPORT + SEND_BASE * 2)
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t ip_port[SIZE_IPPORT];
    ipport_pack(ip_port, &source);
    uint8_t data[ONION_MAX_PACKET_SIZE];
    data[0] = NET_PACKET_ONION_SEND_1;
    memcpy(data + 1, nonce, crypto_box_NONCEBYTES);
    memcpy(data + 1 + crypto_box_NONCEBYTES, plain + SIZE_IPPORT, len -
      SIZE_IPPORT);
    uint16_t data_len = 1 + crypto_box_NONCEBYTES + (len - SIZE_IPPORT);
    uint8_t *ret_part = data + data_len;
    new_nonce(ret_part);
    len = encrypt_data_symmetric(onion->
      secret_symmetric_key, ret_part, ip_port, SIZE_IPPORT,
                                 ret_part + crypto_box_NONCEBYTES);
    if (len != SIZE_IPPORT + crypto_box_MACBYTES)
        return 1;
    data_len += crypto_box_NONCEBYTES + len;
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
int send_onion_packet (Networking_Core * net, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 273 of file onion.c.
References create_onion_packet(), Onion_Path::ip_port1, ONION_MAX_PACKET_SIZE, and sendpacket().
Referenced by START_TEST().
{
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    int len = create_onion_packet(packet, sizeof(packet), path, dest,
      data, length);
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}
int send_onion_response (Networking_Core * net, IP_Port dest, const uint8_t * data, uint16_t length, const uint8_t * ret)
Definition at line 293 of file onion.c.
References NET_PACKET_ONION_RECV_3, ONION_RESPONSE_MAX_DATA_SIZE, RETURN_3, and sendpacket().
Referenced by handle_announce_request(), handle_data_request(), and handle_test_1().
{
    if (length > ONION_RESPONSE_MAX_DATA_SIZE || length == 0)
        return -1;
    uint8_t packet[1 + RETURN_3 + length];
    packet[0] = NET_PACKET_ONION_RECV_3;
    memcpy(packet + 1, ret, RETURN_3);
    memcpy(packet + 1 + RETURN_3, data, length);
    if ((uint32_t)sendpacket(net, dest, packet, sizeof(packet)) != sizeof(packet))
        return -1;
    return 0;
}
void set_callback_handle_recv_1 (Onion * onion, int(*)(void *, IP_Port, const uint8_t *, uint16_t) function, void * object)
Definition at line 576 of file onion.c.
References Onion::callback_object, and Onion::recv_1_function.
Referenced by kill_TCP_server(), and new_TCP_server().
{
    onion->recv_1_function = function;
    onion->callback_object = object;
}