testing/Messenger_test.c File Reference
#include `../toxcore/Messenger.h`
*
#include `misc_tools.c`
*
#include <unistd.h>
*
#include <arpa/inet.h>
*
Macros
#define c_sleep(x) usleep(1000*x)
#define PORT 33445
Functions
void print_message (Messenger *m, uint32_t friendnumber, unsigned int type, const uint8_t *string, size_t length, void *userdata)
void print_request (Messenger *m, const uint8_t *public_key, const uint8_t *data, size_t length, void *userdata)
int main (int argc, char *argv[])
Variables
static Messenger * m
Macro Definition Documentation
#define c_sleep(x) usleep(1000*x)
Definition at line 54 of file Messenger_test.c.
Referenced by main().
#define PORT 33445
Definition at line 55 of file Messenger_test.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 97 of file Messenger_test.c.
References c_sleep, cmdline_parsefor_ipv46(), Messenger::dht, DHT_bootstrap_from_address(), do_messenger(), FRIEND_ADDRESS_SIZE, getaddress(), getname(), hex_string_to_bin(), i, Messenger_Options::ipv6enabled, kill_messenger(), m_addfriend(), m_callback_friendmessage(), m_callback_friendrequest(), m_send_message_generic(), MESSAGE_NORMAL, messenger_load(), messenger_save(), messenger_size(), new_messenger(), num, port, print_message(), print_request(), printf(), setname(), and TOX_ENABLE_IPV6_DEFAULT.
{
    /* let user override default by cmdline */
    uint8_t ipv6enabled = TOX_ENABLE_IPV6_DEFAULT; /* x */
    int argvoffset = cmdline_parsefor_ipv46(argc, argv, &ipv6enabled);
    if (argvoffset < 0)
        exit(1);
    /* with optional --ipvx, now it can be 1-4 arguments... */
    if ((argc != argvoffset + 2) && (argc != argvoffset + 4)) {
        printf("Usage: %s [--ipv4|--ipv6] ip port public_key (of the DHT bootstrap node)\n", argv[0])
      ;
        printf("or\n");
        printf(" %s [--ipv4|--ipv6] Save.bak (to read Save.bak as state file)\n", argv[0]);
        exit(0);
    }
    Messenger_Options options = {0};
    options.ipv6enabled = ipv6enabled;
    m = new_messenger(&options, 0);
    if (!m) {
        fputs("Failed to allocate messenger datastructure\n", stderr);
        exit(0);
    }
    if (argc == argvoffset + 4) {
        uint16_t port = htons(atoi(argv[argvoffset + 2]));
        uint8_t *bootstrap_key = hex_string_to_bin(argv[argvoffset + 3]);
        int res = DHT_bootstrap_from_address(m->dht, argv[argvoffset + 1],
                                             ipv6enabled, port, bootstrap_key);
        free(bootstrap_key);
        if (!res) {
            printf("Failed to convert \"%s\" into an IP address. Exiting...\n", argv[argvoffset + 1])
      ;
            exit(1);
        }
    } else {
        FILE *file = fopen(argv[argvoffset + 1], "rb");
        if (file == NULL) {
            printf("Failed to open \"%s\" - does it exist?\n", argv[argvoffset + 1]);
            return 1;
        }
        int read;
        uint8_t buffer[128000];
        read = fread(buffer, 1, 128000, file);
        printf("Messenger loaded: %i\n", messenger_load(m, buffer, read));
        fclose(file);
    }
    m_callback_friendrequest(m, print_request, NULL);
    m_callback_friendmessage(m, print_message, NULL);
    printf("OUR ID: ");
    uint32_t i;
    uint8_t address[FRIEND_ADDRESS_SIZE];
    getaddress(m, address);
    for (i = 0; i < FRIEND_ADDRESS_SIZE; i++) {
        if (address[i] < 16)
            printf("0");
        printf("%hhX", address[i]);
    }
    setname(m, (uint8_t *)"Anon", 5);
    char temp_hex_id[128];
    printf("\nEnter the address of the friend you wish to add (38 bytes HEX format):\n");
    if (!fgets(temp_hex_id, sizeof(temp_hex_id), stdin))
        exit(0);
    if ((strlen(temp_hex_id) > 0) && (temp_hex_id[strlen(temp_hex_id) - 1] == '\n'))
        temp_hex_id[strlen(temp_hex_id) - 1] = '\0';
    uint8_t *bin_id = hex_string_to_bin(temp_hex_id);
    int num = m_addfriend(m, bin_id, (uint8_t *)"Install Gentoo", sizeof("Install Gentoo"));
    free(bin_id);
    perror("Initialization");
    while (1) {
        uint8_t name[128];
        getname(m, num, name);
        printf("%s\n", name);
        m_send_message_generic(m, num, MESSAGE_NORMAL, (uint8_t *)"
      Test", 5, 0);
        do_messenger(m);
        c_sleep(30);
        FILE *file = fopen("Save.bak", "wb");
        if (file == NULL) {
            return 1;
        }
        uint8_t *buffer = malloc(messenger_size(m));
        messenger_save(m, buffer);
        size_t write_result = fwrite(buffer, 1, messenger_size(m), file);
        if (write_result < messenger_size(m)) {
            return 1;
        }
        free(buffer);
        fclose(file);
    }
    kill_messenger(m);
}
void print_message (Messenger * m, uint32_t friendnumber, unsigned int type, const uint8_t * string, size_t length, void * userdata)
Definition at line 59 of file Messenger_test.c.
References m_send_message_generic(), and printf().
Referenced by main().
{
    printf("Message with length %lu received from %u: %s \n", length, friendnumber, string);
    m_send_message_generic(m, friendnumber, type, (uint8_t *)"Test1", 6, 0);
}
void print_request (Messenger * m, const uint8_t * public_key, const uint8_t * data, size_t length, void * userdata)
Definition at line 70 of file Messenger_test.c.
References m_addfriend_norequest(), and printf().
Referenced by main().
{
    printf("Friend request received from: \n");
    printf("ClientID: ");
    uint32_t j;
    for (j = 0; j < 32; j++) {
        if (public_key[j] < 16)
            printf("0");
        printf("%hhX", public_key[j]);
    }
    printf("\nOf length: %lu with data: %s \n", length, data);
    if (length != sizeof("Install Gentoo")) {
        return;
    }
    if (memcmp(data , "Install Gentoo", sizeof("Install Gentoo")) == 0)
        //if the request contained the message of peace the person is obviously a friend so we add him.
    {
        printf("Friend request accepted.\n");
        m_addfriend_norequest(m, public_key);
    }
}
Variable Documentation
Messenger* m [static]
Definition at line 68 of file Messenger_test.c.