toxcore/util.c File Reference
#include <time.h>
*
#include `crypto_core.h`
*
#include `util.h`
*
Functions
void unix_time_update ()
uint64_t unix_time ()
int is_timeout (uint64_t timestamp, uint64_t timeout)
bool id_equal (const uint8_t *dest, const uint8_t *src)
uint32_t id_copy (uint8_t *dest, const uint8_t *src)
void host_to_net (uint8_t *num, uint16_t numbytes)
uint16_t lendian_to_host16 (uint16_t lendian)
void host_to_lendian32 (uint8_t *dest, uint32_t num)
void lendian_to_host32 (uint32_t *dest, const uint8_t *lendian)
int load_state (load_state_callback_func load_state_callback, void *outer, const uint8_t *data, uint32_t length, uint16_t cookie_inner)
int create_recursive_mutex (pthread_mutex_t *mutex)
Variables
static uint64_t unix_time_value
static uint64_t unix_base_time_value
Function Documentation
int create_recursive_mutex (pthread_mutex_t * mutex)
Definition at line 173 of file util.c.
Referenced by cs_new(), msi_new(), new_net_crypto(), and toxav_new().
{
    pthread_mutexattr_t attr;
    if (pthread_mutexattr_init(&attr) != 0)
        return -1;
    if (pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE) != 0) {
        pthread_mutexattr_destroy(&attr);
        return -1;
    }
    /* Create queue mutex */
    if (pthread_mutex_init(mutex, &attr) != 0) {
        pthread_mutexattr_destroy(&attr);
        return -1;
    }
    pthread_mutexattr_destroy(&attr);
    return 0;
}
void host_to_lendian32 (uint8_t * dest, uint32_t num)
Definition at line 96 of file util.c.
Referenced by DHT_save(), messenger_save(), and z_state_save_subheader().
{
#ifdef WORDS_BIGENDIAN
    num = ((num << 8) & 0xFF00FF00) | ((num >> 8) & 0xFF00FF);
    num = (num << 16) | (num >> 16);
#endif
    memcpy(dest, &num, sizeof(uint32_t));
}
void host_to_net (uint8_t * num, uint16_t numbytes)
Definition at line 72 of file util.c.
References i.
Referenced by file_seek(), file_sendrequest(), friends_list_save(), and send_dhtpk_announce().
{
#ifndef WORDS_BIGENDIAN
    uint32_t i;
    uint8_t buff[numbytes];
    for (i = 0; i < numbytes; ++i) {
        buff[i] = num[numbytes - i - 1];
    }
    memcpy(num, buff, numbytes);
#endif
    return;
}
uint32_t id_copy (uint8_t * dest, const uint8_t * src)
Definition at line 66 of file util.c.
Referenced by addpeer(), addto_receivedlist(), Assoc_self_client_id_changed(), candidates_create_new(), friends_list_load(), get_close_nodes(), getaddress(), init_new_friend(), m_addfriend(), new_Assoc(), replace_all(), send_LANdiscovery(), send_ping_request(), send_ping_response(), test_addto_lists_bad(), test_addto_lists_possible_bad(), and test_addto_lists_update().
{
    memcpy(dest, src, crypto_box_PUBLICKEYBYTES);
    return crypto_box_PUBLICKEYBYTES;
}
bool id_equal (const uint8_t * dest, const uint8_t * src)
Definition at line 61 of file util.c.
Referenced by Assoc_add_entry(), candidates_search(), client_id_self_update(), client_in_list(), client_in_nodelist(), client_or_ip_port_in_list(), delpeer(), DHT_getfriendip(), do_hardening(), do_messenger(), friend_iplist(), friend_number(), get_close_nodes_inner(), getfriend_id(), getnodes(), handle_getnodes(), handle_ping_request(), handle_ping_response(), have_nodes_closelist(), in_list(), m_addfriend(), m_addfriend_norequest(), peer_in_chat(), remove_request_received(), request_received(), returnedip_ports(), route_packet(), send_ping_request(), send_ping_response(), sendnodes_ipv6(), and START_TEST().
{
    return memcmp(dest, src, crypto_box_PUBLICKEYBYTES) == 0;
}
int is_timeout (uint64_t timestamp, uint64_t timeout)
Definition at line 54 of file util.c.
References unix_time().
Referenced by add_to_entries(), Assoc_get_close_entries(), candidates_create_internal(), change_symmetric_key(), client_add_to_list(), client_ping_nodes(), closelist_nodes(), cmp_dht_entry(), cmp_entry(), DHT_getfriendip(), DHT_isconnected(), DHT_non_lan_connected(), do_announce(), do_Assoc(), do_confirmed_TCP(), do_friend(), do_hardening(), do_onion_client(), do_ping_and_sendnode_requests(), do_TCP_confirmed(), do_tcp_conns(), do_to_ping(), entry_heard_store(), friend_iplist(), get_close_nodes_inner(), get_shared_key(), good_to_ping(), groupchat_clear_timedout(), handle_hardening(), have_nodes_closelist(), in_entries(), in_list(), is_path_used(), kill_nonused_tcp(), main(), onion_isconnected(), path_timed_out(), ping_array_check(), ping_array_clear_timedout(), ping_groupchat(), queue(), route_tofriend(), routeone_tofriend(), send_onion_data(), and store_node_ok().
{
    return timestamp + timeout <= unix_time();
}
uint16_t lendian_to_host16 (uint16_t lendian)
Definition at line 87 of file util.c.
Referenced by load_state().
{
#ifdef WORDS_BIGENDIAN
    return (lendian << 8) | (lendian >> 8);
#else
    return lendian;
#endif
}
void lendian_to_host32 (uint32_t * dest, const uint8_t * lendian)
Definition at line 105 of file util.c.
Referenced by DHT_load(), load_state(), and messenger_load().
{
    uint32_t d;
    memcpy(&d, lendian, sizeof(uint32_t));
#ifdef WORDS_BIGENDIAN
    d = ((d << 8) & 0xFF00FF00) | ((d >> 8) & 0xFF00FF);
    d = (d << 16) | (d >> 16);
#endif
    *dest = d;
}
int load_state (load_state_callback_func load_state_callback, void * outer, const uint8_t * data, uint32_t length, uint16_t cookie_inner)
Definition at line 117 of file util.c.
References lendian_to_host16(), and lendian_to_host32().
Referenced by DHT_load(), and messenger_load().
{
    if (!load_state_callback || !data) {
#ifdef DEBUG
        fprintf(stderr, "load_state() called with invalid args.\n");
#endif
        return -1;
    }
    uint16_t type;
    uint32_t length_sub, cookie_type;
    uint32_t size_head = sizeof(uint32_t) * 2;
    while (length >= size_head) {
        lendian_to_host32(&length_sub, data);
        lendian_to_host32(&cookie_type, data + sizeof(length_sub));
        data += size_head;
        length -= size_head;
        if (length < length_sub) {
            /* file truncated */
#ifdef DEBUG
            fprintf(stderr, "state file too short: %u < %u\n", length, length_sub);
#endif
            return -1;
        }
        if (lendian_to_host16((cookie_type >> 16)) != cookie_inner) {
            /* something is not matching up in a bad way, give up */
#ifdef DEBUG
            fprintf(stderr, "state file garbeled: %04hx != %04hx\n", (cookie_type >> 16), cookie_inner);
#endif
            return -1;
        }
        type = lendian_to_host16(cookie_type & 0xFFFF);
        int ret = load_state_callback(outer, data, length_sub, type);
        if (ret == -1) {
            return -1;
        }
        /* -2 means end of save. */
        if (ret == -2)
            return 0;
        data += length_sub;
        length -= length_sub;
    }
    return length == 0 ? 0 : -1;
};
uint64_t unix_time ()
Definition at line 49 of file util.c.
References unix_time_value.
Referenced by add_accepted(), add_tcp_number_relay_connection(), add_to_entries(), addpeer(), addto_lists(), candidates_create_new(), candidates_update_assoc(), change_dht_pk(), change_symmetric_key(), client_add_to_list(), client_or_ip_port_in_list(), create_cookie(), crypto_connection_add_source(), crypto_connection_status(), dht_ip_callback(), do_announce(), do_Assoc(), do_Close(), do_confirmed_TCP(), do_DHT(), do_friend(), do_friend_connections(), do_friends(), do_hardening(), do_messenger(), do_NAT(), do_onion_client(), do_ping_and_sendnode_requests(), do_TCP_confirmed(), do_TCP_connection(), do_to_ping(), get_shared_key(), good_to_ping(), handle_announce_request(), handle_announce_response(), handle_dhtpk_announce(), handle_message_packet_group(), handle_NATping(), handle_new_connections(), handle_packet(), handle_status(), is_timeout(), LANdiscovery(), main(), mark_bad(), mark_good(), mark_possible_bad(), new_Assoc(), new_onion(), new_TCP_connection(), onion_set_friend_DHT_pubkey(), onion_set_friend_online(), open_cookie(), ping_array_add(), ping_groupchat(), queue(), random_path(), replace_all(), returnedip_ports(), send_dhtpk_announce(), send_ping(), send_relays(), set_direct_ip_port(), set_path_timeouts(), START_TEST(), tcp_relay_on_online(), and udp_handle_packet().
{
    return unix_time_value;
}
void unix_time_update ()
Definition at line 41 of file util.c.
References current_time_monotonic(), unix_base_time_value, and unix_time_value.
Referenced by DHT_isconnected(), DHT_non_lan_connected(), do_DHT(), do_messenger(), do_net_crypto(), do_TCP_connection(), do_TCP_server(), main(), networking_poll(), new_DHT(), new_net_crypto(), and START_TEST().
{
    if (unix_base_time_value == 0)
        unix_base_time_value = ((uint64_t)time(NULL) - (
      current_time_monotonic() / 1000ULL));
    unix_time_value = (current_time_monotonic() / 1000ULL) +
      unix_base_time_value;
}
Variable Documentation
uint64_t unix_base_time_value [static]
Definition at line 39 of file util.c.
Referenced by unix_time_update().
uint64_t unix_time_value [static]
Definition at line 38 of file util.c.
Referenced by unix_time(), and unix_time_update().