toxcore/tox_old.h File Reference
Enumerations
enum { TOX_GROUPCHAT_TYPE_TEXT,
TOX_GROUPCHAT_TYPE_AV
 }
enum TOX_CHAT_CHANGE { TOX_CHAT_CHANGE_PEER_ADD,
TOX_CHAT_CHANGE_PEER_DEL,
TOX_CHAT_CHANGE_PEER_NAME
 }
Functions
void tox_callback_group_invite (Tox *tox, void(*function)(Tox *tox, int32_t, uint8_t, const uint8_t *, uint16_t, void *), void *userdata)
void tox_callback_group_message (Tox *tox, void(*function)(Tox *tox, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void tox_callback_group_action (Tox *tox, void(*function)(Tox *tox, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void tox_callback_group_title (Tox *tox, void(*function)(Tox *tox, int, int, const uint8_t *, uint8_t, void *), void *userdata)
void tox_callback_group_namelist_change (Tox *tox, void(*function)(Tox *tox, int, int, uint8_t, void *), void *userdata)
int tox_add_groupchat (Tox *tox)
int tox_del_groupchat (Tox *tox, int groupnumber)
int tox_group_peername (const Tox *tox, int groupnumber, int peernumber, uint8_t *name)
int tox_group_peer_pubkey (const Tox *tox, int groupnumber, int peernumber, uint8_t *public_key)
int tox_invite_friend (Tox *tox, int32_t friendnumber, int groupnumber)
int tox_join_groupchat (Tox *tox, int32_t friendnumber, const uint8_t *data, uint16_t length)
int tox_group_message_send (Tox *tox, int groupnumber, const uint8_t *message, uint16_t length)
int tox_group_action_send (Tox *tox, int groupnumber, const uint8_t *action, uint16_t length)
int tox_group_set_title (Tox *tox, int groupnumber, const uint8_t *title, uint8_t length)
int tox_group_get_title (Tox *tox, int groupnumber, uint8_t *title, uint32_t max_length)
unsigned int tox_group_peernumber_is_ours (const Tox *tox, int groupnumber, int peernumber)
int tox_group_number_peers (const Tox *tox, int groupnumber)
int tox_group_get_names (const Tox *tox, int groupnumber, uint8_t names[][TOX_MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
uint32_t tox_count_chatlist (const Tox *tox)
uint32_t tox_get_chatlist (const Tox *tox, int32_t *out_list, uint32_t list_size)
int tox_group_get_type (const Tox *tox, int groupnumber)
Enumeration Type Documentation
anonymous enum
Enumerator
TOX_GROUPCHAT_TYPE_TEXT
TOX_GROUPCHAT_TYPE_AV
Definition at line 8 of file tox_old.h.
     {
    TOX_GROUPCHAT_TYPE_TEXT,
    TOX_GROUPCHAT_TYPE_AV
};
enum TOX_CHAT_CHANGE
Enumerator
TOX_CHAT_CHANGE_PEER_ADD
TOX_CHAT_CHANGE_PEER_DEL
TOX_CHAT_CHANGE_PEER_NAME
Definition at line 51 of file tox_old.h.
             {
    TOX_CHAT_CHANGE_PEER_ADD,
    TOX_CHAT_CHANGE_PEER_DEL,
    TOX_CHAT_CHANGE_PEER_NAME,
} TOX_CHAT_CHANGE;
Function Documentation
int tox_add_groupchat (Tox * tox)
Definition at line 66 of file tox_old_code.h.
References add_groupchat(), Messenger::group_chat_object, GROUPCHAT_TYPE_TEXT, and m.
Referenced by line_eval(), and START_TEST().
{
    Messenger *m = tox;
    return add_groupchat(m->group_chat_object,
      GROUPCHAT_TYPE_TEXT);
}
void tox_callback_group_action (Tox * tox, void(*)(Tox *tox, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 31 of file tox_old_code.h.
References g_callback_group_action(), Messenger::group_chat_object, and m.
Referenced by init_tox().
{
    Messenger *m = tox;
    g_callback_group_action(m->group_chat_object, function,
      userdata);
}
void tox_callback_group_invite (Tox * tox, void(*)(Tox *tox, int32_t, uint8_t, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 9 of file tox_old_code.h.
References g_callback_group_invite(), Messenger::group_chat_object, and m.
Referenced by init_tox(), main(), and START_TEST().
{
    Messenger *m = tox;
    g_callback_group_invite(m->group_chat_object, function,
      userdata);
}
void tox_callback_group_message (Tox * tox, void(*)(Tox *tox, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 20 of file tox_old_code.h.
References g_callback_group_message(), Messenger::group_chat_object, and m.
Referenced by init_tox(), main(), and START_TEST().
{
    Messenger *m = tox;
    g_callback_group_message(m->group_chat_object, function,
      userdata);
}
void tox_callback_group_namelist_change (Tox * tox, void(*)(Tox *tox, int, int, uint8_t, void *) function, void * userdata)
Definition at line 55 of file tox_old_code.h.
References g_callback_group_namelistchange(), Messenger::group_chat_object, and m.
Referenced by main().
{
    Messenger *m = tox;
    g_callback_group_namelistchange(m->
      group_chat_object, function, userdata);
}
void tox_callback_group_title (Tox * tox, void(*)(Tox *tox, int, int, const uint8_t *, uint8_t, void *) function, void * userdata)
Definition at line 43 of file tox_old_code.h.
References g_callback_group_title(), Messenger::group_chat_object, and m.
{
    Messenger *m = tox;
    g_callback_group_title(m->group_chat_object, function, userdata)
      ;
}
uint32_t tox_count_chatlist (const Tox * tox)
Definition at line 211 of file tox_old_code.h.
References count_chatlist(), Messenger::group_chat_object, and m.
{
    const Messenger *m = tox;
    return count_chatlist(m->group_chat_object);
}
int tox_del_groupchat (Tox * tox, int groupnumber)
Definition at line 77 of file tox_old_code.h.
References del_groupchat(), Messenger::group_chat_object, and m.
Referenced by callback_friend_message(), and START_TEST().
{
    Messenger *m = tox;
    return del_groupchat(m->group_chat_object, groupnumber);
}
uint32_t tox_get_chatlist (const Tox * tox, int32_t * out_list, uint32_t list_size)
Definition at line 222 of file tox_old_code.h.
References copy_chatlist(), Messenger::group_chat_object, and m.
{
    const Messenger *m = tox;
    return copy_chatlist(m->group_chat_object, out_list, list_size);
}
int tox_group_action_send (Tox * tox, int groupnumber, const uint8_t * action, uint16_t length)
Definition at line 143 of file tox_old_code.h.
References group_action_send(), Messenger::group_chat_object, and m.
{
    Messenger *m = tox;
    return group_action_send(m->group_chat_object, groupnumber, action,
      length);
}
int tox_group_get_names (const Tox * tox, int groupnumber, uint8_t names[][TOX_MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
Definition at line 201 of file tox_old_code.h.
References Messenger::group_chat_object, group_names(), and m.
Referenced by print_groupchatpeers().
{
    const Messenger *m = tox;
    return group_names(m->group_chat_object, groupnumber, names, lengths,
      length);
}
int tox_group_get_title (Tox * tox, int groupnumber, uint8_t * title, uint32_t max_length)
Definition at line 165 of file tox_old_code.h.
References Messenger::group_chat_object, group_title_get(), and m.
Referenced by START_TEST().
{
    Messenger *m = tox;
    return group_title_get(m->group_chat_object, groupnumber, title,
      max_length);
}
int tox_group_get_type (const Tox * tox, int groupnumber)
Definition at line 233 of file tox_old_code.h.
References Messenger::group_chat_object, group_get_type(), and m.
{
    const Messenger *m = tox;
    return group_get_type(m->group_chat_object, groupnumber);
}
int tox_group_message_send (Tox * tox, int groupnumber, const uint8_t * message, uint16_t length)
Definition at line 133 of file tox_old_code.h.
References Messenger::group_chat_object, group_message_send(), and m.
Referenced by line_eval(), send_irc_group(), and START_TEST().
{
    Messenger *m = tox;
    return group_message_send(m->group_chat_object, groupnumber, message
      , length);
}
int tox_group_number_peers (const Tox * tox, int groupnumber)
Definition at line 185 of file tox_old_code.h.
References Messenger::group_chat_object, group_number_peers(), and m.
Referenced by line_eval(), print_groupchatpeers(), print_groupnamelistchange(), and START_TEST().
{
    const Messenger *m = tox;
    return group_number_peers(m->group_chat_object, groupnumber);
}
int tox_group_peer_pubkey (const Tox * tox, int groupnumber, int peernumber, uint8_t * public_key)
Definition at line 101 of file tox_old_code.h.
References Messenger::group_chat_object, group_peer_pubkey(), and m.
{
    const Messenger *m = tox;
    return group_peer_pubkey(m->group_chat_object, groupnumber,
      peernumber, public_key);
}
int tox_group_peername (const Tox * tox, int groupnumber, int peernumber, uint8_t * name)
Definition at line 89 of file tox_old_code.h.
References Messenger::group_chat_object, group_peername(), and m.
Referenced by copy_groupmessage(), print_groupmessage(), and print_groupnamelistchange().
{
    const Messenger *m = tox;
    return group_peername(m->group_chat_object, groupnumber, peernumber,
      name);
}
unsigned int tox_group_peernumber_is_ours (const Tox * tox, int groupnumber, int peernumber)
Definition at line 176 of file tox_old_code.h.
References Messenger::group_chat_object, group_peernumber_is_ours(), and m.
Referenced by copy_groupmessage().
{
    const Messenger *m = tox;
    return group_peernumber_is_ours(m->group_chat_object,
      groupnumber, peernumber);
}
int tox_group_set_title (Tox * tox, int groupnumber, const uint8_t * title, uint8_t length)
Definition at line 153 of file tox_old_code.h.
References Messenger::group_chat_object, group_title_send(), and m.
Referenced by START_TEST().
{
    Messenger *m = tox;
    return group_title_send(m->group_chat_object, groupnumber, title,
      length);
}
int tox_invite_friend (Tox * tox, int32_t friendnumber, int groupnumber)
Definition at line 111 of file tox_old_code.h.
References Messenger::group_chat_object, invite_friend(), and m.
Referenced by callback_friend_message(), line_eval(), and START_TEST().
{
    Messenger *m = tox;
    return invite_friend(m->group_chat_object, friendnumber, groupnumber);
}
int tox_join_groupchat (Tox * tox, int32_t friendnumber, const uint8_t * data, uint16_t length)
Definition at line 123 of file tox_old_code.h.
References Messenger::group_chat_object, GROUPCHAT_TYPE_TEXT, join_groupchat(), and m.
Referenced by callback_group_invite(), print_group_invite_callback(), and print_invite().
{
    Messenger *m = tox;
    return join_groupchat(m->group_chat_object, friendnumber,
      GROUPCHAT_TYPE_TEXT, data, length);
}