toxcore/group.h File Reference
#include `Messenger.h`
*
Data Structures
struct Group_Peer
struct Group_c
struct Group_Chats
Macros
#define MAX_LOSSY_COUNT 256
#define DESIRED_CLOSE_CONNECTIONS 4
#define MAX_GROUP_CONNECTIONS 16
#define GROUP_IDENTIFIER_LENGTH (1 + crypto_box_KEYBYTES) /* type + crypto_box_KEYBYTES so we can use new_symmetric_key(...) to fill it */
Enumerations
enum { GROUPCHAT_STATUS_NONE,
GROUPCHAT_STATUS_VALID,
GROUPCHAT_STATUS_CONNECTED
 }
enum { GROUPCHAT_TYPE_TEXT,
GROUPCHAT_TYPE_AV
 }
enum { GROUPCHAT_CLOSE_NONE,
GROUPCHAT_CLOSE_CONNECTION,
GROUPCHAT_CLOSE_ONLINE
 }
enum { CHAT_CHANGE_PEER_ADD,
CHAT_CHANGE_PEER_DEL,
CHAT_CHANGE_PEER_NAME
 }
Functions
void g_callback_group_invite (Group_Chats *g_c, void(*function)(Messenger *m, int32_t, uint8_t, const uint8_t *, uint16_t, void *), void *userdata)
void g_callback_group_message (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void g_callback_group_action (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void g_callback_group_title (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint8_t, void *), void *userdata)
void g_callback_group_namelistchange (Group_Chats *g_c, void(*function)(Messenger *m, int, int, uint8_t, void *), void *userdata)
int add_groupchat (Group_Chats *g_c, uint8_t type)
int del_groupchat (Group_Chats *g_c, int groupnumber)
int group_peer_pubkey (const Group_Chats *g_c, int groupnumber, int peernumber, uint8_t *pk)
int group_peername (const Group_Chats *g_c, int groupnumber, int peernumber, uint8_t *name)
int invite_friend (Group_Chats *g_c, int32_t friendnumber, int groupnumber)
int join_groupchat (Group_Chats *g_c, int32_t friendnumber, uint8_t expected_type, const uint8_t *data, uint16_t length)
int group_message_send (const Group_Chats *g_c, int groupnumber, const uint8_t *message, uint16_t length)
int group_action_send (const Group_Chats *g_c, int groupnumber, const uint8_t *action, uint16_t length)
int group_title_send (const Group_Chats *g_c, int groupnumber, const uint8_t *title, uint8_t title_len)
int group_title_get (const Group_Chats *g_c, int groupnumber, uint8_t *title, uint32_t max_length)
int group_number_peers (const Group_Chats *g_c, int groupnumber)
unsigned int group_peernumber_is_ours (const Group_Chats *g_c, int groupnumber, int peernumber)
int group_names (const Group_Chats *g_c, int groupnumber, uint8_t names[][MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
void group_lossy_packet_registerhandler (Group_Chats *g_c, uint8_t byte, int(*function)(void *, int, int, void *, const uint8_t *, uint16_t))
int send_group_lossy_packet (const Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length)
uint32_t count_chatlist (Group_Chats *g_c)
uint32_t copy_chatlist (Group_Chats *g_c, int32_t *out_list, uint32_t list_size)
int group_get_type (const Group_Chats *g_c, int groupnumber)
void send_name_all_groups (Group_Chats *g_c)
int group_set_object (const Group_Chats *g_c, int groupnumber, void *object)
int group_peer_set_object (const Group_Chats *g_c, int groupnumber, int peernumber, void *object)
void * group_get_object (const Group_Chats *g_c, int groupnumber)
void * group_peer_get_object (const Group_Chats *g_c, int groupnumber, int peernumber)
int callback_groupchat_peer_new (const Group_Chats *g_c, int groupnumber, void(*function)(void *, int, int))
int callback_groupchat_peer_delete (Group_Chats *g_c, int groupnumber, void(*function)(void *, int, int, void *))
int callback_groupchat_delete (Group_Chats *g_c, int groupnumber, void(*function)(void *, int))
Group_Chats * new_groupchats (Messenger *m)
void do_groupchats (Group_Chats *g_c)
void kill_groupchats (Group_Chats *g_c)
Macro Definition Documentation
#define DESIRED_CLOSE_CONNECTIONS 4
Definition at line 61 of file group.h.
Referenced by add_to_closest(), connect_to_closest(), delpeer(), handle_packet_online(), pk_in_closest_peers(), and send_lossy_all_close().
#define GROUP_IDENTIFIER_LENGTH (1 + crypto_box_KEYBYTES) /* type + crypto_box_KEYBYTES so we can use new_symmetric_key(...) to fill it */
Definition at line 63 of file group.h.
Referenced by get_group_num(), handle_friend_invite_packet(), invite_friend(), join_groupchat(), and send_packet_online().
#define MAX_GROUP_CONNECTIONS 16
Definition at line 62 of file group.h.
Referenced by add_conn_to_groupchat(), connect_to_closest(), count_close_connected(), del_groupchat(), friend_in_close(), remove_close_conn(), send_lossy_all_close(), send_message_all_close(), and set_conns_type_close().
#define MAX_LOSSY_COUNT 256
Definition at line 41 of file group.h.
Referenced by lossy_packet_not_received().
Enumeration Type Documentation
anonymous enum
Enumerator
GROUPCHAT_STATUS_NONE
GROUPCHAT_STATUS_VALID
GROUPCHAT_STATUS_CONNECTED
Definition at line 30 of file group.h.
     {
    GROUPCHAT_STATUS_NONE,
    GROUPCHAT_STATUS_VALID,
    GROUPCHAT_STATUS_CONNECTED
};
anonymous enum
Enumerator
GROUPCHAT_TYPE_TEXT
GROUPCHAT_TYPE_AV
Definition at line 36 of file group.h.
     {
    GROUPCHAT_TYPE_TEXT,
    GROUPCHAT_TYPE_AV
};
anonymous enum
Enumerator
GROUPCHAT_CLOSE_NONE
GROUPCHAT_CLOSE_CONNECTION
GROUPCHAT_CLOSE_ONLINE
Definition at line 65 of file group.h.
     {
    GROUPCHAT_CLOSE_NONE,
    GROUPCHAT_CLOSE_CONNECTION,
    GROUPCHAT_CLOSE_ONLINE
};
anonymous enum
Enumerator
CHAT_CHANGE_PEER_ADD
CHAT_CHANGE_PEER_DEL
CHAT_CHANGE_PEER_NAME
Definition at line 171 of file group.h.
     {
    CHAT_CHANGE_PEER_ADD,
    CHAT_CHANGE_PEER_DEL,
    CHAT_CHANGE_PEER_NAME,
};
Function Documentation
int add_groupchat (Group_Chats * g_c, uint8_t type)
Definition at line 667 of file group.c.
References addpeer(), Group_Chats::chats, create_group_chat(), Messenger::dht, GROUPCHAT_STATUS_CONNECTED, Group_c::identifier, Group_Chats::m, Messenger::name, Messenger::name_length, Messenger::net_crypto, new_symmetric_key(), Group_c::number_joined, Group_c::peer_number, Group_c::real_pk, Net_Crypto::self_public_key, DHT::self_public_key, setnick(), and Group_c::status.
Referenced by add_av_groupchat(), and tox_add_groupchat().
{
    int groupnumber = create_group_chat(g_c);
    if (groupnumber == -1)
        return -1;
    Group_c *g = &g_c->chats[groupnumber];
    g->status = GROUPCHAT_STATUS_CONNECTED;
    g->number_joined = -1;
    new_symmetric_key(g->identifier + 1);
    g->identifier[0] = type;
    g->peer_number = 0; /* Founder is peer 0. */
    memcpy(g->real_pk, g_c->m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    int peer_index = addpeer(g_c, groupnumber, g->real_pk, g_c->m->
      dht->self_public_key, 0);
    if (peer_index == -1) {
        return -1;
    }
    setnick(g_c, groupnumber, peer_index, g_c->m->name, g_c->m->
      name_length);
    return groupnumber;
}
int callback_groupchat_delete (Group_Chats * g_c, int groupnumber, void(*)(void *, int) function)
Definition at line 1098 of file group.c.
References get_group_c(), and Group_c::group_on_delete.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->group_on_delete = function;
    return 0;
}
int callback_groupchat_peer_delete (Group_Chats * g_c, int groupnumber, void(*)(void *, int, int, void *) function)
Definition at line 1080 of file group.c.
References get_group_c(), and Group_c::peer_on_leave.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->peer_on_leave = function;
    return 0;
}
int callback_groupchat_peer_new (const Group_Chats * g_c, int groupnumber, void(*)(void *, int, int) function)
Definition at line 1062 of file group.c.
References get_group_c(), and Group_c::peer_on_join.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->peer_on_join = function;
    return 0;
}
uint32_t copy_chatlist (Group_Chats * g_c, int32_t * out_list, uint32_t list_size)
Definition at line 2298 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, i, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_get_chatlist().
{
    if (!out_list) {
        return 0;
    }
    if (g_c->num_chats == 0) {
        return 0;
    }
    uint32_t i, ret = 0;
    for (i = 0; i < g_c->num_chats; ++i) {
        if (ret >= list_size) {
            break; /* Abandon ship */
        }
        if (g_c->chats[i].status > GROUPCHAT_STATUS_NONE) {
            out_list[ret] = i;
            ret++;
        }
    }
    return ret;
}
uint32_t count_chatlist (Group_Chats * g_c)
Definition at line 2279 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, i, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_count_chatlist().
{
    uint32_t ret = 0;
    uint32_t i;
    for (i = 0; i < g_c->num_chats; i++) {
        if (g_c->chats[i].status != GROUPCHAT_STATUS_NONE) {
            ret++;
        }
    }
    return ret;
}
int del_groupchat (Group_Chats * g_c, int groupnumber)
Definition at line 699 of file group.c.
References Group_c::close, Group_Chats::fr_c, get_group_c(), Group_c::group, group_kill_peer_send(), Group_c::group_on_delete, GROUPCHAT_CLOSE_NONE, i, kill_friend_connection(), MAX_GROUP_CONNECTIONS, Group_c::number, Group_c::numpeers, Group_Peer::object, Group_c::object, Group_c::peer_number, Group_c::peer_on_leave, Group_c::type, and wipe_group_chat().
Referenced by add_av_groupchat(), join_av_groupchat(), kill_groupchats(), and tox_del_groupchat().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    group_kill_peer_send(g_c, groupnumber, g->peer_number);
    unsigned int i;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        g->close[i].type = GROUPCHAT_CLOSE_NONE;
        kill_friend_connection(g_c->fr_c, g->close[i].
      number);
    }
    for (i = 0; i < g->numpeers; ++i) {
        if (g->peer_on_leave)
            g->peer_on_leave(g->object, groupnumber, i, g->
      group[i].object);
    }
    free(g->group);
    if (g->group_on_delete)
        g->group_on_delete(g->object, groupnumber);
    return wipe_group_chat(g_c, groupnumber);
}
void do_groupchats (Group_Chats * g_c)
Definition at line 2241 of file group.c.
References connect_to_closest(), get_group_c(), groupchat_clear_timedout(), GROUPCHAT_STATUS_CONNECTED, i, Group_Chats::num_chats, ping_groupchat(), and Group_c::status.
Referenced by tox_iterate().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        Group_c *g = get_group_c(g_c, i);
        if (!g)
            continue;
        if (g->status == GROUPCHAT_STATUS_CONNECTED) {
            connect_to_closest(g_c, i);
            ping_groupchat(g_c, i);
            groupchat_clear_timedout(g_c, i);
        }
    }
    //TODO
}
void g_callback_group_action (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1012 of file group.c.
References Group_Chats::action_callback, and Group_Chats::action_callback_userdata.
Referenced by tox_callback_group_action().
{
    g_c->action_callback = function;
    g_c->action_callback_userdata = userdata;
}
void g_callback_group_invite (Group_Chats * g_c, void(*)(Messenger *m, int32_t, uint8_t, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 990 of file group.c.
References Group_Chats::invite_callback, and Group_Chats::invite_callback_userdata.
Referenced by tox_callback_group_invite().
{
    g_c->invite_callback = function;
    g_c->invite_callback_userdata = userdata;
}
void g_callback_group_message (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1001 of file group.c.
References Group_Chats::message_callback, and Group_Chats::message_callback_userdata.
Referenced by tox_callback_group_message().
{
    g_c->message_callback = function;
    g_c->message_callback_userdata = userdata;
}
void g_callback_group_namelistchange (Group_Chats * g_c, void(*)(Messenger *m, int, int, uint8_t, void *) function, void * userdata)
Definition at line 1036 of file group.c.
References Group_Chats::group_namelistchange_userdata, and Group_Chats::peer_namelistchange.
Referenced by tox_callback_group_namelist_change().
{
    g_c->peer_namelistchange = function;
    g_c->group_namelistchange_userdata = userdata;
}
void g_callback_group_title (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint8_t, void *) function, void * userdata)
Definition at line 1048 of file group.c.
References Group_Chats::title_callback, and Group_Chats::title_callback_userdata.
Referenced by tox_callback_group_title().
{
    g_c->title_callback = function;
    g_c->title_callback_userdata = userdata;
}
int group_action_send (const Group_Chats * g_c, int groupnumber, const uint8_t * action, uint16_t length)
Definition at line 1768 of file group.c.
References PACKET_ID_ACTION, and send_message_group().
Referenced by tox_group_action_send().
{
    if (send_message_group(g_c, groupnumber, PACKET_ID_ACTION, action,
      length)) {
        return 0;
    } else {
        return -1;
    }
}
void* group_get_object (const Group_Chats * g_c, int groupnumber)
Definition at line 2136 of file group.c.
References get_group_c(), and Group_c::object.
Referenced by group_send_audio(), and send_audio_packet().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return NULL;
    return g->object;
}
int group_get_type (const Group_Chats * g_c, int groupnumber)
Definition at line 840 of file group.c.
References get_group_c(), and Group_c::identifier.
Referenced by tox_group_get_type().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    return g->identifier[0];
}
void group_lossy_packet_registerhandler (Group_Chats * g_c, uint8_t byte, int(*)(void *, int, int, void *, const uint8_t *, uint16_t) function)
Definition at line 1025 of file group.c.
References Group_Chats::function, and Group_Chats::lossy_packethandlers.
Referenced by groupchat_enable_av().
{
    g_c->lossy_packethandlers[byte].function = function;
}
int group_message_send (const Group_Chats * g_c, int groupnumber, const uint8_t * message, uint16_t length)
Definition at line 1755 of file group.c.
References PACKET_ID_MESSAGE, and send_message_group().
Referenced by tox_group_message_send().
{
    if (send_message_group(g_c, groupnumber, PACKET_ID_MESSAGE, message,
       length)) {
        return 0;
    } else {
        return -1;
    }
}
int group_names (const Group_Chats * g_c, int groupnumber, uint8_t names[][MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
Definition at line 786 of file group.c.
References get_group_c(), group_peername(), i, and Group_c::numpeers.
Referenced by tox_group_get_names().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    unsigned int i;
    for (i = 0; i < g->numpeers && i < length; ++i) {
        lengths[i] = group_peername(g_c, groupnumber, i, names[i]);
    }
    return i;
}
int group_number_peers (const Group_Chats * g_c, int groupnumber)
Definition at line 806 of file group.c.
References get_group_c(), and Group_c::numpeers.
Referenced by tox_group_number_peers().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    return g->numpeers;
}
void* group_peer_get_object (const Group_Chats * g_c, int groupnumber, int peernumber)
Definition at line 2151 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::object.
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return NULL;
    if ((uint32_t)peernumber >= g->numpeers)
        return NULL;
    return g->group[peernumber].object;
}
int group_peer_pubkey (const Group_Chats * g_c, int groupnumber, int peernumber, uint8_t * pk)
Definition at line 737 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::real_pk.
Referenced by tox_group_peer_pubkey().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    memcpy(pk, g->group[peernumber].real_pk, crypto_box_PUBLICKEYBYTES);
    return 0;
}
int group_peer_set_object (const Group_Chats * g_c, int groupnumber, int peernumber, void * object)
Definition at line 2117 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::object.
Referenced by group_av_peer_new().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    g->group[peernumber].object = object;
    return 0;
}
int group_peername (const Group_Chats * g_c, int groupnumber, int peernumber, uint8_t * name)
Definition at line 757 of file group.c.
References get_group_c(), Group_c::group, Group_Peer::nick, Group_Peer::nick_len, and Group_c::numpeers.
Referenced by group_names(), and tox_group_peername().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    if (g->group[peernumber].nick_len == 0) {
        memcpy(name, "Tox User", 8);
        return 8;
    }
    memcpy(name, g->group[peernumber].nick, g->group[peernumber].
      nick_len);
    return g->group[peernumber].nick_len;
}
unsigned int group_peernumber_is_ours (const Group_Chats * g_c, int groupnumber, int peernumber)
Definition at line 819 of file group.c.
References get_group_c(), Group_c::group, GROUPCHAT_STATUS_CONNECTED, Group_c::numpeers, Group_Peer::peer_number, Group_c::peer_number, and Group_c::status.
Referenced by tox_group_peernumber_is_ours().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return 0;
    if (g->status != GROUPCHAT_STATUS_CONNECTED)
        return 0;
    if ((uint32_t)peernumber >= g->numpeers)
        return 0;
    return g->peer_number == g->group[peernumber].peer_number;
}
int group_set_object (const Group_Chats * g_c, int groupnumber, void * object)
Definition at line 2101 of file group.c.
References get_group_c(), and Group_c::object.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->object = object;
    return 0;
}
int group_title_get (const Group_Chats * g_c, int groupnumber, uint8_t * title, uint32_t max_length)
Definition at line 1222 of file group.c.
References get_group_c(), MAX_NAME_LENGTH, Group_c::title, and Group_c::title_len.
Referenced by tox_group_get_title().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if (g->title_len == 0 || g->title_len > MAX_NAME_LENGTH)
        return -1;
    if (max_length > g->title_len)
        max_length = g->title_len;
    memcpy(title, g->title, max_length);
    return max_length;
}
int group_title_send (const Group_Chats * g_c, int groupnumber, const uint8_t * title, uint8_t title_len)
Definition at line 1190 of file group.c.
References get_group_c(), GROUP_MESSAGE_TITLE_ID, MAX_NAME_LENGTH, Group_c::numpeers, send_message_group(), Group_c::title, and Group_c::title_len.
Referenced by tox_group_set_title().
{
    if (title_len > MAX_NAME_LENGTH || title_len == 0)
        return -1;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    /* same as already set? */
    if (g->title_len == title_len && !memcmp(g->title, title, title_len))
        return 0;
    memcpy(g->title, title, title_len);
    g->title_len = title_len;
    if (g->numpeers == 1)
        return 0;
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_TITLE_ID, title, title_len))
        return 0;
    else
        return -1;
}
int invite_friend (Group_Chats * g_c, int32_t friendnumber, int groupnumber)
Definition at line 900 of file group.c.
References get_group_c(), GROUP_IDENTIFIER_LENGTH, Group_c::identifier, invite, INVITE_ID, INVITE_PACKET_SIZE, Group_Chats::m, send_group_invite_packet(), and wipe_group_chat().
Referenced by tox_invite_friend().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint8_t invite[INVITE_PACKET_SIZE];
    invite[0] = INVITE_ID;
    uint16_t groupchat_num = htons((uint16_t)groupnumber);
    memcpy(invite + 1, &groupchat_num, sizeof(groupchat_num));
    memcpy(invite + 1 + sizeof(groupchat_num), g->identifier,
      GROUP_IDENTIFIER_LENGTH);
    if (send_group_invite_packet(g_c->m, friendnumber, invite, sizeof(invite))) {
        return 0;
    } else {
        wipe_group_chat(g_c, groupnumber);
        return -1;
    }
}
int join_groupchat (Group_Chats * g_c, int32_t friendnumber, uint8_t expected_type, const uint8_t * data, uint16_t length)
Definition at line 930 of file group.c.
References add_conn_to_groupchat(), Group_Chats::chats, Group_c::close, create_group_chat(), get_group_num(), getfriendcon_id(), GROUP_IDENTIFIER_LENGTH, Group_c::group_number, GROUPCHAT_CLOSE_ONLINE, GROUPCHAT_STATUS_NONE, GROUPCHAT_STATUS_VALID, Group_c::identifier, INVITE_RESPONSE_ID, INVITE_RESPONSE_PACKET_SIZE, Group_Chats::m, Messenger::net_crypto, Group_c::number_joined, Group_c::real_pk, Net_Crypto::self_public_key, send_group_invite_packet(), send_peer_query(), Group_c::status, and Group_c::type.
Referenced by join_av_groupchat(), and tox_join_groupchat().
{
    if (length != sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
        return -1;
    if (data[sizeof(uint16_t)] != expected_type)
        return -1;
    int friendcon_id = getfriendcon_id(g_c->m, friendnumber);
    if (friendcon_id == -1)
        return -1;
    if (get_group_num(g_c, data + sizeof(uint16_t)) != -1)
        return -1;
    int groupnumber = create_group_chat(g_c);
    if (groupnumber == -1)
        return -1;
    Group_c *g = &g_c->chats[groupnumber];
    uint16_t group_num = htons(groupnumber);
    g->status = GROUPCHAT_STATUS_VALID;
    g->number_joined = -1;
    memcpy(g->real_pk, g_c->m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    uint8_t response[INVITE_RESPONSE_PACKET_SIZE];
    response[0] = INVITE_RESPONSE_ID;
    memcpy(response + 1, &group_num, sizeof(uint16_t));
    memcpy(response + 1 + sizeof(uint16_t), data, sizeof(uint16_t) +
      GROUP_IDENTIFIER_LENGTH);
    if (send_group_invite_packet(g_c->m, friendnumber, response, sizeof(response))
      ) {
        uint16_t other_groupnum;
        memcpy(&other_groupnum, data, sizeof(other_groupnum));
        other_groupnum = ntohs(other_groupnum);
        memcpy(g->identifier, data + sizeof(uint16_t),
      GROUP_IDENTIFIER_LENGTH);
        int close_index = add_conn_to_groupchat(g_c, friendcon_id, groupnumber, 0, 1);
        if (close_index != -1) {
            g->close[close_index].group_number = other_groupnum;
            g->close[close_index].type = GROUPCHAT_CLOSE_ONLINE;
            g->number_joined = friendcon_id;
        }
        send_peer_query(g_c, friendcon_id, other_groupnum);
        return groupnumber;
    } else {
        g->status = GROUPCHAT_STATUS_NONE;
        return -1;
    }
}
void kill_groupchats (Group_Chats * g_c)
Definition at line 2262 of file group.c.
References del_groupchat(), Messenger::group_chat_object, i, Group_Chats::m, m_callback_group_invite(), and Group_Chats::num_chats.
Referenced by tox_kill().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        del_groupchat(g_c, i);
    }
    m_callback_group_invite(g_c->m, NULL);
    g_c->m->group_chat_object = 0;
    free(g_c);
}
Group_Chats* new_groupchats (Messenger * m)
Definition at line 2222 of file group.c.
References Group_Chats::fr_c, Messenger::fr_c, Messenger::group_chat_object, handle_friend_invite_packet(), m, Group_Chats::m, and m_callback_group_invite().
Referenced by tox_new().
{
    if (!m)
        return NULL;
    Group_Chats *temp = calloc(1, sizeof(Group_Chats));
    if (temp == NULL)
        return NULL;
    temp->m = m;
    temp->fr_c = m->fr_c;
    m->group_chat_object = temp;
    m_callback_group_invite(m, &
      handle_friend_invite_packet);
    return temp;
}
int send_group_lossy_packet (const Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length)
Definition at line 1782 of file group.c.
References get_group_c(), Group_c::lossy_message_number, Group_c::peer_number, and send_lossy_all_close().
Referenced by send_audio_packet().
{
    //TODO: length check here?
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint8_t packet[sizeof(uint16_t) * 2 + length];
    uint16_t peer_number = htons(g->peer_number);
    memcpy(packet, &peer_number, sizeof(uint16_t));
    uint16_t message_num = htons(g->lossy_message_number);
    memcpy(packet + sizeof(uint16_t), &message_num, sizeof(uint16_t));
    memcpy(packet + sizeof(uint16_t) * 2, data, length);
    if (send_lossy_all_close(g_c, groupnumber, packet, sizeof(packet), -1) == 0) {
        return -1;
    }
    ++g->lossy_message_number;
    return 0;
}
void send_name_all_groups (Group_Chats * g_c)
Definition at line 2205 of file group.c.
References get_group_c(), group_name_send(), GROUPCHAT_STATUS_CONNECTED, i, Group_Chats::m, Messenger::name, Messenger::name_length, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_self_set_name().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        Group_c *g = get_group_c(g_c, i);
        if (!g)
            continue;
        if (g->status == GROUPCHAT_STATUS_CONNECTED) {
            group_name_send(g_c, i, g_c->m->name, g_c->m->
      name_length);
        }
    }
}