toxcore/TCP_connection.c File Reference
#include `TCP_connection.h`
*
#include `util.h`
*
Macros
#define realloc_tox_array(array, element_size, num, temp_pointer) (num ? (temp_pointer = realloc(array, ((num) * (element_size))), temp_pointer ? (array = temp_pointer, 0) : (-1)) : (free(array), array = NULL, 0))
Functions
static _Bool connections_number_not_valid (const TCP_Connections *tcp_c, int connections_number)
static _Bool tcp_connections_number_not_valid (const TCP_Connections *tcp_c, int tcp_connections_number)
static int create_connection (TCP_Connections *tcp_c)
static int create_tcp_connection (TCP_Connections *tcp_c)
static int wipe_connection (TCP_Connections *tcp_c, int connections_number)
static int wipe_tcp_connection (TCP_Connections *tcp_c, int tcp_connections_number)
static TCP_Connection_to * get_connection (const TCP_Connections *tcp_c, int connections_number)
static TCP_con * get_tcp_connection (const TCP_Connections *tcp_c, int tcp_connections_number)
int send_packet_tcp_connection (TCP_Connections *tcp_c, int connections_number, const uint8_t *packet, uint16_t length)
int get_random_tcp_onion_conn_number (TCP_Connections *tcp_c)
int tcp_send_onion_request (TCP_Connections *tcp_c, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length)
int tcp_send_oob_packet (TCP_Connections *tcp_c, unsigned int tcp_connections_number, const uint8_t *public_key, const uint8_t *packet, uint16_t length)
void set_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object)
void set_oob_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_oob_callback)(void *object, const uint8_t *public_key, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length), void *object)
void set_onion_packet_tcp_connection_callback (TCP_Connections *tcp_c, int(*tcp_onion_callback)(void *object, const uint8_t *data, uint16_t length), void *object)
static int find_tcp_connection_to (TCP_Connections *tcp_c, const uint8_t *public_key)
static int find_tcp_connection_relay (TCP_Connections *tcp_c, const uint8_t *relay_pk)
int new_tcp_connection_to (TCP_Connections *tcp_c, const uint8_t *public_key, int id)
int kill_tcp_connection_to (TCP_Connections *tcp_c, int connections_number)
int set_tcp_connection_to_status (TCP_Connections *tcp_c, int connections_number, _Bool status)
static _Bool tcp_connection_in_conn (TCP_Connection_to *con_to, unsigned int tcp_connections_number)
static int add_tcp_connection_to_conn (TCP_Connection_to *con_to, unsigned int tcp_connections_number)
static int rm_tcp_connection_from_conn (TCP_Connection_to *con_to, unsigned int tcp_connections_number)
static unsigned int online_tcp_connection_from_conn (TCP_Connection_to *con_to)
static int set_tcp_connection_status (TCP_Connection_to *con_to, unsigned int tcp_connections_number, unsigned int status, uint8_t connection_id)
static int kill_tcp_relay_connection (TCP_Connections *tcp_c, int tcp_connections_number)
static int reconnect_tcp_relay_connection (TCP_Connections *tcp_c, int tcp_connections_number)
static int sleep_tcp_relay_connection (TCP_Connections *tcp_c, int tcp_connections_number)
static int unsleep_tcp_relay_connection (TCP_Connections *tcp_c, int tcp_connections_number)
static int send_tcp_relay_routing_request (TCP_Connections *tcp_c, int tcp_connections_number, uint8_t *public_key)
static int tcp_response_callback (void *object, uint8_t connection_id, const uint8_t *public_key)
static int tcp_status_callback (void *object, uint32_t number, uint8_t connection_id, uint8_t status)
static int tcp_data_callback (void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length)
static int tcp_oob_callback (void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length)
static int tcp_onion_callback (void *object, const uint8_t *data, uint16_t length)
static int tcp_relay_set_callbacks (TCP_Connections *tcp_c, int tcp_connections_number)
static int tcp_relay_on_online (TCP_Connections *tcp_c, int tcp_connections_number)
static int add_tcp_relay_instance (TCP_Connections *tcp_c, IP_Port ip_port, const uint8_t *relay_pk)
int add_tcp_relay_global (TCP_Connections *tcp_c, IP_Port ip_port, const uint8_t *relay_pk)
int add_tcp_number_relay_connection (TCP_Connections *tcp_c, int connections_number, unsigned int tcp_connections_number)
int add_tcp_relay_connection (TCP_Connections *tcp_c, int connections_number, IP_Port ip_port, const uint8_t *relay_pk)
unsigned int tcp_connection_to_online_tcp_relays (TCP_Connections *tcp_c, int connections_number)
unsigned int tcp_copy_connected_relays (TCP_Connections *tcp_c, Node_format *tcp_relays, uint16_t max_num)
int set_tcp_onion_status (TCP_Connections *tcp_c, _Bool status)
TCP_Connections * new_tcp_connections (const uint8_t *secret_key, TCP_Proxy_Info *proxy_info)
static void do_tcp_conns (TCP_Connections *tcp_c)
static void kill_nonused_tcp (TCP_Connections *tcp_c)
void do_tcp_connections (TCP_Connections *tcp_c)
void kill_tcp_connections (TCP_Connections *tcp_c)
Macro Definition Documentation
#define realloc_tox_array(array, element_size, num, temp_pointer) (num ? (temp_pointer = realloc(array, ((num) * (element_size))), temp_pointer ? (array = temp_pointer, 0) : (-1)) : (free(array), array = NULL, 0))
Definition at line 36 of file TCP_connection.c.
Referenced by create_connection(), create_tcp_connection(), wipe_connection(), and wipe_tcp_connection().
Function Documentation
static int add_tcp_connection_to_conn (TCP_Connection_to * con_to, unsigned int tcp_connections_number) [static]
Definition at line 571 of file TCP_connection.c.
References TCP_Connection_to::connection_id, TCP_Connection_to::connections, i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::status, TCP_Connection_to::tcp_connection, tcp_connection_in_conn(), and TCP_CONNECTIONS_STATUS_NONE.
Referenced by add_tcp_number_relay_connection(), and add_tcp_relay_connection().
{
    unsigned int i;
    if (tcp_connection_in_conn(con_to, tcp_connections_number))
        return -1;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection == 0) {
            con_to->connections[i].tcp_connection = tcp_connections_number + 1;
            con_to->connections[i].status =
      TCP_CONNECTIONS_STATUS_NONE;
            con_to->connections[i].connection_id = 0;
            return i;
        }
    }
    return -1;
}
int add_tcp_number_relay_connection (TCP_Connections * tcp_c, int connections_number, unsigned int tcp_connections_number)
Definition at line 1064 of file TCP_connection.c.
References add_tcp_connection_to_conn(), TCP_con::connected_time, get_connection(), get_tcp_connection(), TCP_Connection_to::public_key, send_tcp_relay_routing_request(), TCP_Connection_to::status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, unix_time(), and TCP_con::unsleep.
Referenced by add_tcp_relay_connection(), and crypto_connection_add_source().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (con_to->status != TCP_CONN_SLEEPING && tcp_con->
      status == TCP_CONN_SLEEPING) {
        tcp_con->unsleep = 1;
    }
    if (add_tcp_connection_to_conn(con_to, tcp_connections_number) == -1)
        return -1;
    if (tcp_con->status == TCP_CONN_CONNECTED) {
        if (send_tcp_relay_routing_request(tcp_c, tcp_connections_number,
      con_to->public_key) == 0) {
            tcp_con->connected_time = unix_time();
        }
    }
    return 0;
}
int add_tcp_relay_connection (TCP_Connections * tcp_c, int connections_number, IP_Port ip_port, const uint8_t * relay_pk)
Definition at line 1099 of file TCP_connection.c.
References add_tcp_connection_to_conn(), add_tcp_number_relay_connection(), add_tcp_relay_instance(), find_tcp_connection_relay(), get_connection(), get_tcp_connection(), online_tcp_connection_from_conn(), and RECOMMENDED_FRIEND_TCP_CONNECTIONS.
Referenced by add_tcp_relay_peer(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    int tcp_connections_number = find_tcp_connection_relay(tcp_c, relay_pk);
    if (tcp_connections_number != -1) {
        return add_tcp_number_relay_connection(tcp_c, connections_number,
      tcp_connections_number);
    } else {
        if (online_tcp_connection_from_conn(con_to) >=
      RECOMMENDED_FRIEND_TCP_CONNECTIONS) {
            return -1;
        }
        int tcp_connections_number = add_tcp_relay_instance(tcp_c, ip_port, relay_pk)
      ;
        TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
        if (!tcp_con)
            return -1;
        if (add_tcp_connection_to_conn(con_to, tcp_connections_number) == -1) {
            return -1;
        }
        return 0;
    }
}
int add_tcp_relay_global (TCP_Connections * tcp_c, IP_Port ip_port, const uint8_t * relay_pk)
Definition at line 1046 of file TCP_connection.c.
References add_tcp_relay_instance(), and find_tcp_connection_relay().
Referenced by add_tcp_relay(), and START_TEST().
{
    int tcp_connections_number = find_tcp_connection_relay(tcp_c, relay_pk);
    if (tcp_connections_number != -1)
        return -1;
    if (add_tcp_relay_instance(tcp_c, ip_port, relay_pk) == -1)
        return -1;
    return 0;
}
static int add_tcp_relay_instance (TCP_Connections * tcp_c, IP_Port ip_port, const uint8_t * relay_pk) [static]
Definition at line 1011 of file TCP_connection.c.
References TCP_con::connection, create_tcp_connection(), IP::family, IP_Port::ip, new_TCP_connection(), TCP_Connections::proxy_info, TCP_Connections::self_public_key, TCP_Connections::self_secret_key, TCP_con::status, TCP_CONN_VALID, TCP_Connections::tcp_connections, TCP_INET, and TCP_INET6.
Referenced by add_tcp_relay_connection(), and add_tcp_relay_global().
{
    if (ip_port.ip.family == TCP_INET) {
        ip_port.ip.family = AF_INET;
    } else if (ip_port.ip.family == TCP_INET6) {
        ip_port.ip.family = AF_INET6;
    }
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    int tcp_connections_number = create_tcp_connection(tcp_c);
    if (tcp_connections_number == -1)
        return -1;
    TCP_con *tcp_con = &tcp_c->tcp_connections[tcp_connections_number];
    tcp_con->connection = new_TCP_connection(ip_port, relay_pk, tcp_c->
      self_public_key, tcp_c->self_secret_key,
                          &tcp_c->proxy_info);
    if (!tcp_con->connection)
        return -1;
    tcp_con->status = TCP_CONN_VALID;
    return tcp_connections_number;
}
static _Bool connections_number_not_valid (const TCP_Connections * tcp_c, int connections_number) [static]
Definition at line 42 of file TCP_connection.c.
References TCP_Connections::connections, TCP_Connections::connections_length, TCP_Connection_to::status, and TCP_CONN_NONE.
Referenced by get_connection(), and wipe_connection().
{
    if ((unsigned int)connections_number >= tcp_c->connections_length)
        return 1;
    if (tcp_c->connections == NULL)
        return 1;
    if (tcp_c->connections[connections_number].status ==
      TCP_CONN_NONE)
        return 1;
    return 0;
}
static int create_connection (TCP_Connections * tcp_c) [static]
Definition at line 78 of file TCP_connection.c.
References TCP_Connections::connections, TCP_Connections::connections_length, i, realloc_tox_array, TCP_Connection_to::status, and TCP_CONN_NONE.
Referenced by new_tcp_connection_to().
{
    uint32_t i;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        if (tcp_c->connections[i].status == TCP_CONN_NONE)
            return i;
    }
    int id = -1;
    TCP_Connection_to *temp_pointer;
    if (realloc_tox_array(tcp_c->connections, sizeof(
      TCP_Connection_to), tcp_c->connections_length + 1,
                          temp_pointer) == 0) {
        id = tcp_c->connections_length;
        ++tcp_c->connections_length;
        memset(&(tcp_c->connections[id]), 0, sizeof(TCP_Connection_to));
    }
    return id;
}
static int create_tcp_connection (TCP_Connections * tcp_c) [static]
Definition at line 106 of file TCP_connection.c.
References i, realloc_tox_array, TCP_con::status, TCP_CONN_NONE, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by add_tcp_relay_instance().
{
    uint32_t i;
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        if (tcp_c->tcp_connections[i].status ==
      TCP_CONN_NONE)
            return i;
    }
    int id = -1;
    TCP_con *temp_pointer;
    if (realloc_tox_array(tcp_c->tcp_connections, sizeof(
      TCP_con), tcp_c->tcp_connections_length + 1, temp_pointer) == 0) {
        id = tcp_c->tcp_connections_length;
        ++tcp_c->tcp_connections_length;
        memset(&(tcp_c->tcp_connections[id]), 0, sizeof(TCP_con));
    }
    return id;
}
void do_tcp_connections (TCP_Connections * tcp_c)
Definition at line 1346 of file TCP_connection.c.
References do_tcp_conns(), and kill_nonused_tcp().
Referenced by do_tcp(), and START_TEST().
{
    do_tcp_conns(tcp_c);
    kill_nonused_tcp(tcp_c);
}
static void do_tcp_conns (TCP_Connections * tcp_c) [static]
Definition at line 1268 of file TCP_connection.c.
References TCP_con::connected_time, TCP_con::connection, do_TCP_connection(), get_tcp_connection(), i, is_timeout(), kill_tcp_relay_connection(), TCP_con::lock_count, TCP_con::onion, reconnect_tcp_relay_connection(), TCP_con::sleep_count, sleep_tcp_relay_connection(), TCP_Client_Connection::status, TCP_con::status, TCP_CLIENT_CONFIRMED, TCP_CLIENT_DISCONNECTED, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_CONN_VALID, TCP_CONNECTION_ANNOUNCE_TIMEOUT, TCP_Connections::tcp_connections_length, tcp_relay_on_online(), TCP_con::unsleep, and unsleep_tcp_relay_connection().
Referenced by do_tcp_connections().
{
    unsigned int i;
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
        if (tcp_con) {
            if (tcp_con->status != TCP_CONN_SLEEPING) {
                do_TCP_connection(tcp_con->connection);
                /* callbacks can change TCP connection address. */
                tcp_con = get_tcp_connection(tcp_c, i);
                if (tcp_con->connection->status ==
      TCP_CLIENT_DISCONNECTED) {
                    if (tcp_con->status == TCP_CONN_CONNECTED) {
                        reconnect_tcp_relay_connection(tcp_c, i);
                    } else {
                        kill_tcp_relay_connection(tcp_c, i);
                    }
                    continue;
                }
                if (tcp_con->status == TCP_CONN_VALID && tcp_con->
      connection->status == TCP_CLIENT_CONFIRMED) {
                    tcp_relay_on_online(tcp_c, i);
                }
                if (tcp_con->status == TCP_CONN_CONNECTED && !tcp_con->
      onion && tcp_con->lock_count
                        && tcp_con->lock_count == tcp_con->sleep_count
                        && is_timeout(tcp_con->connected_time,
      TCP_CONNECTION_ANNOUNCE_TIMEOUT)) {
                    sleep_tcp_relay_connection(tcp_c, i);
                }
            }
            if (tcp_con->status == TCP_CONN_SLEEPING && tcp_con->
      unsleep) {
                unsleep_tcp_relay_connection(tcp_c, i);
            }
        }
    }
}
static int find_tcp_connection_relay (TCP_Connections * tcp_c, const uint8_t * relay_pk) [static]
Definition at line 401 of file TCP_connection.c.
References TCP_con::connection, get_tcp_connection(), i, TCP_Client_Connection::public_key, TCP_con::relay_pk, TCP_con::status, TCP_CONN_SLEEPING, and TCP_Connections::tcp_connections_length.
Referenced by add_tcp_relay_connection(), and add_tcp_relay_global().
{
    unsigned int i;
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
        if (tcp_con) {
            if (tcp_con->status == TCP_CONN_SLEEPING) {
                if (memcmp(tcp_con->relay_pk, relay_pk, crypto_box_PUBLICKEYBYTES) == 0) {
                    return i;
                }
            } else {
                if (memcmp(tcp_con->connection->public_key, relay_pk,
      crypto_box_PUBLICKEYBYTES) == 0) {
                    return i;
                }
            }
        }
    }
    return -1;
}
static int find_tcp_connection_to (TCP_Connections * tcp_c, const uint8_t * public_key) [static]
Definition at line 379 of file TCP_connection.c.
References TCP_Connections::connections_length, get_connection(), i, and TCP_Connection_to::public_key.
Referenced by new_tcp_connection_to(), tcp_oob_callback(), and tcp_response_callback().
{
    unsigned int i;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        TCP_Connection_to *con_to = get_connection(tcp_c, i);
        if (con_to) {
            if (memcmp(con_to->public_key, public_key, crypto_box_PUBLICKEYBYTES) == 0)
       {
                return i;
            }
        }
    }
    return -1;
}
static TCP_Connection_to* get_connection (const TCP_Connections * tcp_c, int connections_number) [static]
Definition at line 182 of file TCP_connection.c.
References TCP_Connections::connections, and connections_number_not_valid().
Referenced by add_tcp_number_relay_connection(), add_tcp_relay_connection(), find_tcp_connection_to(), kill_tcp_connection_to(), kill_tcp_relay_connection(), reconnect_tcp_relay_connection(), send_packet_tcp_connection(), set_tcp_connection_to_status(), sleep_tcp_relay_connection(), tcp_connection_to_online_tcp_relays(), tcp_data_callback(), tcp_oob_callback(), tcp_relay_on_online(), tcp_response_callback(), and tcp_status_callback().
{
    if (connections_number_not_valid(tcp_c, connections_number))
        return 0;
    return &tcp_c->connections[connections_number];
}
int get_random_tcp_onion_conn_number (TCP_Connections * tcp_c)
Definition at line 285 of file TCP_connection.c.
References i, TCP_con::onion, TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by do_onion_client(), and get_random_tcp_con_number().
{
    unsigned int i, r = rand();
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        unsigned int index = ((i + r) % tcp_c->tcp_connections_length);
        if (tcp_c->tcp_connections[index].onion && tcp_c->
      tcp_connections[index].status == TCP_CONN_CONNECTED) {
            return index;
        }
    }
    return -1;
}
static TCP_con* get_tcp_connection (const TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 190 of file TCP_connection.c.
References TCP_Connections::tcp_connections, and tcp_connections_number_not_valid().
Referenced by add_tcp_number_relay_connection(), add_tcp_relay_connection(), do_tcp_conns(), find_tcp_connection_relay(), kill_nonused_tcp(), kill_tcp_connection_to(), kill_tcp_relay_connection(), reconnect_tcp_relay_connection(), send_packet_tcp_connection(), send_tcp_relay_routing_request(), set_tcp_connection_to_status(), set_tcp_onion_status(), sleep_tcp_relay_connection(), tcp_copy_connected_relays(), tcp_data_callback(), tcp_oob_callback(), tcp_relay_on_online(), tcp_relay_set_callbacks(), tcp_response_callback(), tcp_send_oob_packet(), tcp_status_callback(), and unsleep_tcp_relay_connection().
{
    if (tcp_connections_number_not_valid(tcp_c, tcp_connections_number))
        return 0;
    return &tcp_c->tcp_connections[tcp_connections_number];
}
static void kill_nonused_tcp (TCP_Connections * tcp_c) [static]
Definition at line 1310 of file TCP_connection.c.
References TCP_con::connected_time, get_tcp_connection(), i, is_timeout(), kill_tcp_relay_connection(), TCP_con::lock_count, TCP_con::onion, RECOMMENDED_FRIEND_TCP_CONNECTIONS, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONNECTION_ANNOUNCE_TIMEOUT, and TCP_Connections::tcp_connections_length.
Referenced by do_tcp_connections().
{
    if (tcp_c->tcp_connections_length == 0)
        return;
    unsigned int i, num_online = 0, num_kill = 0, to_kill[tcp_c->
      tcp_connections_length];
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
        if (tcp_con) {
            if (tcp_con->status == TCP_CONN_CONNECTED) {
                if (!tcp_con->onion && !tcp_con->lock_count &&
      is_timeout(tcp_con->connected_time,
      TCP_CONNECTION_ANNOUNCE_TIMEOUT)) {
                    to_kill[num_kill] = i;
                    ++num_kill;
                }
                ++num_online;
            }
        }
    }
    if (num_online <= RECOMMENDED_FRIEND_TCP_CONNECTIONS) {
        return;
    } else {
        unsigned int n = num_online - RECOMMENDED_FRIEND_TCP_CONNECTIONS;
        if (n < num_kill)
            num_kill = n;
    }
    for (i = 0; i < num_kill; ++i) {
        kill_tcp_relay_connection(tcp_c, to_kill[i]);
    }
}
int kill_tcp_connection_to (TCP_Connections * tcp_c, int connections_number)
Definition at line 455 of file TCP_connection.c.
References TCP_con::connection, TCP_Connection_to::connection_id, TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, TCP_con::lock_count, MAX_FRIEND_TCP_CONNECTIONS, send_disconnect_request(), TCP_con::sleep_count, TCP_Connection_to::status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and wipe_connection().
Referenced by accept_crypto_connection(), crypto_kill(), new_crypto_connection(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection) {
            unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
            TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
            if (!tcp_con)
                continue;
            if (tcp_con->status == TCP_CONN_CONNECTED) {
                send_disconnect_request(tcp_con->
      connection, con_to->connections[i].connection_id);
            }
            if (con_to->connections[i].status ==
      TCP_CONNECTIONS_STATUS_ONLINE) {
                --tcp_con->lock_count;
                if (con_to->status == TCP_CONN_SLEEPING) {
                    --tcp_con->sleep_count;
                }
            }
        }
    }
    return wipe_connection(tcp_c, connections_number);
}
void kill_tcp_connections (TCP_Connections * tcp_c)
Definition at line 1352 of file TCP_connection.c.
References TCP_con::connection, TCP_Connections::connections, i, kill_TCP_connection(), TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by kill_net_crypto(), new_net_crypto(), and START_TEST().
{
    unsigned int i;
    for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
        kill_TCP_connection(tcp_c->tcp_connections[i].
      connection);
    }
    free(tcp_c->tcp_connections);
    free(tcp_c->connections);
    free(tcp_c);
}
static int kill_tcp_relay_connection (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 656 of file TCP_connection.c.
References TCP_con::connection, TCP_Connections::connections_length, get_connection(), get_tcp_connection(), i, kill_TCP_connection(), TCP_con::onion, TCP_Connections::onion_num_conns, rm_tcp_connection_from_conn(), and wipe_tcp_connection().
Referenced by do_tcp_conns(), kill_nonused_tcp(), reconnect_tcp_relay_connection(), and unsleep_tcp_relay_connection().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    unsigned int i;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        TCP_Connection_to *con_to = get_connection(tcp_c, i);
        if (con_to) {
            rm_tcp_connection_from_conn(con_to, tcp_connections_number);
        }
    }
    if (tcp_con->onion) {
        --tcp_c->onion_num_conns;
    }
    kill_TCP_connection(tcp_con->connection);
    return wipe_tcp_connection(tcp_c, tcp_connections_number);
}
int new_tcp_connection_to (TCP_Connections * tcp_c, const uint8_t * public_key, int id)
Definition at line 433 of file TCP_connection.c.
References TCP_Connections::connections, create_connection(), find_tcp_connection_to(), TCP_Connection_to::id, TCP_Connection_to::public_key, TCP_Connection_to::status, and TCP_CONN_VALID.
Referenced by accept_crypto_connection(), new_crypto_connection(), and START_TEST().
{
    if (find_tcp_connection_to(tcp_c, public_key) != -1)
        return -1;
    int connections_number = create_connection(tcp_c);
    if (connections_number == -1)
        return -1;
    TCP_Connection_to *con_to = &tcp_c->connections[connections_number];
    con_to->status = TCP_CONN_VALID;
    memcpy(con_to->public_key, public_key, crypto_box_PUBLICKEYBYTES);
    con_to->id = id;
    return connections_number;
}
TCP_Connections* new_tcp_connections (const uint8_t * secret_key, TCP_Proxy_Info * proxy_info)
Definition at line 1251 of file TCP_connection.c.
References TCP_Connections::proxy_info, TCP_Connections::self_public_key, and TCP_Connections::self_secret_key.
Referenced by new_net_crypto(), and START_TEST().
{
    if (secret_key == NULL)
        return NULL;
    TCP_Connections *temp = calloc(1, sizeof(TCP_Connections));
    if (temp == NULL)
        return NULL;
    memcpy(temp->self_secret_key, secret_key, crypto_box_SECRETKEYBYTES);
    crypto_scalarmult_curve25519_base(temp->self_public_key, temp->
      self_secret_key);
    temp->proxy_info = *proxy_info;
    return temp;
}
static unsigned int online_tcp_connection_from_conn (TCP_Connection_to * con_to) [static]
Definition at line 612 of file TCP_connection.c.
References TCP_Connection_to::connections, i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::status, TCP_Connection_to::tcp_connection, and TCP_CONNECTIONS_STATUS_ONLINE.
Referenced by add_tcp_relay_connection(), and tcp_connection_to_online_tcp_relays().
{
    unsigned int i, count = 0;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection) {
            if (con_to->connections[i].status ==
      TCP_CONNECTIONS_STATUS_ONLINE) {
                ++count;
            }
        }
    }
    return count;
}
static int reconnect_tcp_relay_connection (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 682 of file TCP_connection.c.
References TCP_con::connected_time, TCP_con::connection, TCP_Connections::connections_length, get_connection(), get_tcp_connection(), i, TCP_Client_Connection::ip_port, kill_TCP_connection(), kill_tcp_relay_connection(), TCP_con::lock_count, new_TCP_connection(), TCP_con::onion, TCP_Connections::onion_num_conns, TCP_Connections::proxy_info, TCP_Client_Connection::public_key, TCP_Connections::self_public_key, TCP_Connections::self_secret_key, set_tcp_connection_status(), TCP_con::sleep_count, TCP_con::status, TCP_CONN_SLEEPING, TCP_CONN_VALID, TCP_CONNECTIONS_STATUS_NONE, and TCP_con::unsleep.
Referenced by do_tcp_conns().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status == TCP_CONN_SLEEPING)
        return -1;
    IP_Port ip_port = tcp_con->connection->ip_port;
    uint8_t relay_pk[crypto_box_PUBLICKEYBYTES];
    memcpy(relay_pk, tcp_con->connection->public_key, crypto_box_PUBLICKEYBYTES);
    kill_TCP_connection(tcp_con->connection);
    tcp_con->connection = new_TCP_connection(ip_port, relay_pk, tcp_c->
      self_public_key, tcp_c->self_secret_key,
                          &tcp_c->proxy_info);
    if (!tcp_con->connection) {
        kill_tcp_relay_connection(tcp_c, tcp_connections_number);
        return -1;
    }
    unsigned int i;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        TCP_Connection_to *con_to = get_connection(tcp_c, i);
        if (con_to) {
            set_tcp_connection_status(con_to, tcp_connections_number,
      TCP_CONNECTIONS_STATUS_NONE, 0);
        }
    }
    if (tcp_con->onion) {
        --tcp_c->onion_num_conns;
        tcp_con->onion = 0;
    }
    tcp_con->lock_count = 0;
    tcp_con->sleep_count = 0;
    tcp_con->connected_time = 0;
    tcp_con->status = TCP_CONN_VALID;
    tcp_con->unsleep = 0;
    return 0;
}
static int rm_tcp_connection_from_conn (TCP_Connection_to * con_to, unsigned int tcp_connections_number) [static]
Definition at line 593 of file TCP_connection.c.
References TCP_Connection_to::connection_id, TCP_Connection_to::connections, i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::status, TCP_Connection_to::tcp_connection, and TCP_CONNECTIONS_STATUS_NONE.
Referenced by kill_tcp_relay_connection().
{
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection == (tcp_connections_number + 1))
       {
            con_to->connections[i].tcp_connection = 0;
            con_to->connections[i].status =
      TCP_CONNECTIONS_STATUS_NONE;
            con_to->connections[i].connection_id = 0;
            return i;
        }
    }
    return -1;
}
int send_packet_tcp_connection (TCP_Connections * tcp_c, int connections_number, const uint8_t * packet, uint16_t length)
Definition at line 203 of file TCP_connection.c.
References TCP_con::connection, TCP_Connection_to::connection_id, TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::public_key, send_data(), send_oob_packet(), TCP_Connection_to::status, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and TCP_CONNECTIONS_STATUS_REGISTERED.
Referenced by send_packet_to(), START_TEST(), and tcp_handle_cookie_request().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to) {
        return -1;
    }
    //TODO: detect and kill bad relays.
    //TODO: thread safety?
    unsigned int i;
    int ret = -1;
    _Bool limit_reached = 0;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        uint32_t tcp_con_num = con_to->connections[i].tcp_connection;
        uint8_t status = con_to->connections[i].status;
        uint8_t connection_id = con_to->connections[i].connection_id;
        if (tcp_con_num && status == TCP_CONNECTIONS_STATUS_ONLINE) {
            tcp_con_num -= 1;
            TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_con_num);
            if (!tcp_con) {
                continue;
            }
            ret = send_data(tcp_con->connection, connection_id, packet, length);
            if (ret == 0) {
                limit_reached = 1;
            }
            if (ret == 1) {
                break;
            }
        }
    }
    if (ret == 1) {
        return 0;
    } else if (!limit_reached) {
        ret = 0;
        /* Send oob packets to all relays tied to the connection. */
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            uint32_t tcp_con_num = con_to->connections[i].
      tcp_connection;
            uint8_t status = con_to->connections[i].status;
            if (tcp_con_num && status == TCP_CONNECTIONS_STATUS_REGISTERED
      ) {
                tcp_con_num -= 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_con_num);
                if (!tcp_con) {
                    continue;
                }
                if (send_oob_packet(tcp_con->connection, con_to->
      public_key, packet, length) == 1) {
                    ret += 1;
                }
            }
        }
        if (ret >= 1) {
            return 0;
        } else {
            return -1;
        }
    } else {
        return -1;
    }
}
static int send_tcp_relay_routing_request (TCP_Connections * tcp_c, int tcp_connections_number, uint8_t * public_key) [static]
Definition at line 802 of file TCP_connection.c.
References TCP_con::connection, get_tcp_connection(), send_routing_request(), TCP_con::status, and TCP_CONN_SLEEPING.
Referenced by add_tcp_number_relay_connection(), and tcp_relay_on_online().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status == TCP_CONN_SLEEPING)
        return -1;
    if (send_routing_request(tcp_con->connection,
      public_key) != 1)
        return -1;
    return 0;
}
void set_onion_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, const uint8_t *data, uint16_t length) tcp_onion_callback, void * object)
Definition at line 366 of file TCP_connection.c.
References TCP_Connections::tcp_onion_callback, tcp_onion_callback(), and TCP_Connections::tcp_onion_callback_object.
Referenced by kill_onion_client(), and new_onion_client().
{
    tcp_c->tcp_onion_callback = tcp_onion_callback;
    tcp_c->tcp_onion_callback_object = object;
}
void set_oob_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, const uint8_t *public_key, unsigned int tcp_connections_number, const uint8_t *data, uint16_t length) tcp_oob_callback, void * object)
Definition at line 357 of file TCP_connection.c.
References TCP_Connections::tcp_oob_callback, tcp_oob_callback(), and TCP_Connections::tcp_oob_callback_object.
Referenced by new_net_crypto(), and START_TEST().
{
    tcp_c->tcp_oob_callback = tcp_oob_callback;
    tcp_c->tcp_oob_callback_object = object;
}
void set_packet_tcp_connection_callback (TCP_Connections * tcp_c, int(*)(void *object, int id, const uint8_t *data, uint16_t length) tcp_data_callback, void * object)
Definition at line 348 of file TCP_connection.c.
References TCP_Connections::tcp_data_callback, tcp_data_callback(), and TCP_Connections::tcp_data_callback_object.
Referenced by new_net_crypto(), and START_TEST().
{
    tcp_c->tcp_data_callback = tcp_data_callback;
    tcp_c->tcp_data_callback_object = object;
}
static int set_tcp_connection_status (TCP_Connection_to * con_to, unsigned int tcp_connections_number, unsigned int status, uint8_t connection_id) [static]
Definition at line 630 of file TCP_connection.c.
References TCP_Connection_to::connection_id, TCP_Connection_to::connections, i, MAX_FRIEND_TCP_CONNECTIONS, TCP_Connection_to::status, and TCP_Connection_to::tcp_connection.
Referenced by reconnect_tcp_relay_connection(), sleep_tcp_relay_connection(), tcp_response_callback(), and tcp_status_callback().
{
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection == (tcp_connections_number + 1))
       {
            if (con_to->connections[i].status == status) {
                return -1;
            }
            con_to->connections[i].status = status;
            con_to->connections[i].connection_id = connection_id;
            return i;
        }
    }
    return -1;
}
int set_tcp_connection_to_status (TCP_Connections * tcp_c, int connections_number, _Bool status)
Definition at line 499 of file TCP_connection.c.
References TCP_Connection_to::connections, get_connection(), get_tcp_connection(), i, MAX_FRIEND_TCP_CONNECTIONS, TCP_con::sleep_count, TCP_Connection_to::status, TCP_con::status, TCP_CONN_SLEEPING, TCP_CONN_VALID, TCP_Connection_to::tcp_connection, TCP_CONNECTIONS_STATUS_ONLINE, and TCP_con::unsleep.
Referenced by do_tcp().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return -1;
    if (status) {
        /* Conection is unsleeping. */
        if (con_to->status != TCP_CONN_SLEEPING)
            return -1;
        unsigned int i;
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            if (con_to->connections[i].tcp_connection) {
                unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c,
      tcp_connections_number);
                if (!tcp_con)
                    continue;
                if (tcp_con->status == TCP_CONN_SLEEPING) {
                    tcp_con->unsleep = 1;
                }
            }
        }
        con_to->status = TCP_CONN_VALID;
        return 0;
    } else {
        /* Conection is going to sleep. */
        if (con_to->status != TCP_CONN_VALID)
            return -1;
        unsigned int i;
        for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++
      i) {
            if (con_to->connections[i].tcp_connection) {
                unsigned int tcp_connections_number = con_to->connections[
      i].tcp_connection - 1;
                TCP_con *tcp_con = get_tcp_connection(tcp_c,
      tcp_connections_number);
                if (!tcp_con)
                    continue;
                if (con_to->connections[i].status ==
      TCP_CONNECTIONS_STATUS_ONLINE) {
                    ++tcp_con->sleep_count;
                }
            }
        }
        con_to->status = TCP_CONN_SLEEPING;
        return 0;
    }
}
int set_tcp_onion_status (TCP_Connections * tcp_c, _Bool status)
Definition at line 1184 of file TCP_connection.c.
References get_tcp_connection(), i, NUM_ONION_TCP_CONNECTIONS, TCP_con::onion, TCP_Connections::onion_num_conns, TCP_Connections::onion_status, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_Connections::tcp_connections_length, and TCP_con::unsleep.
Referenced by do_onion_client().
{
    if (tcp_c->onion_status == status)
        return -1;
    if (status) {
        unsigned int i;
        for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
            TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
            if (tcp_con) {
                if (tcp_con->status == TCP_CONN_CONNECTED && !tcp_con->
      onion) {
                    ++tcp_c->onion_num_conns;
                    tcp_con->onion = 1;
                }
            }
            if (tcp_c->onion_num_conns >=
      NUM_ONION_TCP_CONNECTIONS)
                break;
        }
        if (tcp_c->onion_num_conns < NUM_ONION_TCP_CONNECTIONS) {
            unsigned int wakeup = NUM_ONION_TCP_CONNECTIONS - tcp_c->
      onion_num_conns;
            for (i = 0; i < tcp_c->tcp_connections_length; ++
      i) {
                TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
                if (tcp_con) {
                    if (tcp_con->status == TCP_CONN_SLEEPING) {
                        tcp_con->unsleep = 1;
                    }
                }
                if (!wakeup)
                    break;
            }
        }
        tcp_c->onion_status = 1;
    } else {
        unsigned int i;
        for (i = 0; i < tcp_c->tcp_connections_length; ++i) {
            TCP_con *tcp_con = get_tcp_connection(tcp_c, i);
            if (tcp_con) {
                if (tcp_con->onion) {
                    --tcp_c->onion_num_conns;
                    tcp_con->onion = 0;
                }
            }
        }
        tcp_c->onion_status = 0;
    }
    return 0;
}
static int sleep_tcp_relay_connection (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 728 of file TCP_connection.c.
References TCP_con::connected_time, TCP_con::connection, TCP_Connections::connections_length, get_connection(), get_tcp_connection(), i, TCP_Client_Connection::ip_port, TCP_con::ip_port, kill_TCP_connection(), TCP_con::lock_count, TCP_con::onion, TCP_Connections::onion_num_conns, TCP_Client_Connection::public_key, TCP_con::relay_pk, set_tcp_connection_status(), TCP_con::sleep_count, TCP_con::status, TCP_CONN_CONNECTED, TCP_CONN_SLEEPING, TCP_CONNECTIONS_STATUS_NONE, and TCP_con::unsleep.
Referenced by do_tcp_conns().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status != TCP_CONN_CONNECTED)
        return -1;
    if (tcp_con->lock_count != tcp_con->sleep_count)
        return -1;
    tcp_con->ip_port = tcp_con->connection->ip_port;
    memcpy(tcp_con->relay_pk, tcp_con->connection->public_key,
      crypto_box_PUBLICKEYBYTES);
    kill_TCP_connection(tcp_con->connection);
    tcp_con->connection = NULL;
    unsigned int i;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        TCP_Connection_to *con_to = get_connection(tcp_c, i);
        if (con_to) {
            set_tcp_connection_status(con_to, tcp_connections_number,
      TCP_CONNECTIONS_STATUS_NONE, 0);
        }
    }
    if (tcp_con->onion) {
        --tcp_c->onion_num_conns;
        tcp_con->onion = 0;
    }
    tcp_con->lock_count = 0;
    tcp_con->sleep_count = 0;
    tcp_con->connected_time = 0;
    tcp_con->status = TCP_CONN_SLEEPING;
    tcp_con->unsleep = 0;
    return 0;
}
static _Bool tcp_connection_in_conn (TCP_Connection_to * con_to, unsigned int tcp_connections_number) [static]
Definition at line 555 of file TCP_connection.c.
References TCP_Connection_to::connections, i, MAX_FRIEND_TCP_CONNECTIONS, and TCP_Connection_to::tcp_connection.
Referenced by add_tcp_connection_to_conn(), tcp_oob_callback(), and tcp_relay_on_online().
{
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_TCP_CONNECTIONS; ++i) {
        if (con_to->connections[i].tcp_connection == (tcp_connections_number + 1))
       {
            return 1;
        }
    }
    return 0;
}
unsigned int tcp_connection_to_online_tcp_relays (TCP_Connections * tcp_c, int connections_number)
Definition at line 1133 of file TCP_connection.c.
References get_connection(), and online_tcp_connection_from_conn().
Referenced by crypto_connection_status(), and START_TEST().
{
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (!con_to)
        return 0;
    return online_tcp_connection_from_conn(con_to);
}
static _Bool tcp_connections_number_not_valid (const TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 59 of file TCP_connection.c.
References TCP_con::status, TCP_CONN_NONE, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by get_tcp_connection(), and wipe_tcp_connection().
{
    if ((unsigned int)tcp_connections_number >= tcp_c->tcp_connections_length)
        return 1;
    if (tcp_c->tcp_connections == NULL)
        return 1;
    if (tcp_c->tcp_connections[tcp_connections_number].status ==
      TCP_CONN_NONE)
        return 1;
    return 0;
}
unsigned int tcp_copy_connected_relays (TCP_Connections * tcp_c, Node_format * tcp_relays, uint16_t max_num)
Definition at line 1149 of file TCP_connection.c.
References TCP_con::connection, IP::family, get_tcp_connection(), i, IP_Port::ip, TCP_Client_Connection::ip_port, Node_format::ip_port, TCP_Client_Connection::public_key, make-funny-savefile::public_key, TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections_length, TCP_INET, and TCP_INET6.
Referenced by copy_connected_tcp_relays().
{
    unsigned int i, copied = 0, r = rand();
    for (i = 0; (i < tcp_c->tcp_connections_length) && (copied < max_num); ++
      i) {
        TCP_con *tcp_con = get_tcp_connection(tcp_c, (i + r) % tcp_c->
      tcp_connections_length);
        if (!tcp_con) {
            continue;
        }
        if (tcp_con->status == TCP_CONN_CONNECTED) {
            memcpy(tcp_relays[copied].public_key, tcp_con->connection->
      public_key, crypto_box_PUBLICKEYBYTES);
            tcp_relays[copied].ip_port = tcp_con->connection->
      ip_port;
            if (tcp_relays[copied].ip_port.ip.family == AF_INET) {
                tcp_relays[copied].ip_port.ip.family = TCP_INET;
            } else if (tcp_relays[copied].ip_port.ip.family == AF_INET6) {
                tcp_relays[copied].ip_port.ip.family = TCP_INET6;
            }
            ++copied;
        }
    }
    return copied;
}
static int tcp_data_callback (void * object, uint32_t number, uint8_t connection_id, const uint8_t * data, uint16_t length) [static]
Definition at line 882 of file TCP_connection.c.
References TCP_Client_Connection::custom_object, TCP_Client_Connection::custom_uint, get_connection(), get_tcp_connection(), TCP_Connection_to::id, TCP_Connections::tcp_data_callback, and TCP_Connections::tcp_data_callback_object.
Referenced by set_packet_tcp_connection_callback(), tcp_oob_callback(), and tcp_relay_set_callbacks().
{
    if (length == 0)
        return -1;
    TCP_Client_Connection *TCP_client_con = object;
    TCP_Connections *tcp_c = TCP_client_con->custom_object;
    unsigned int tcp_connections_number = TCP_client_con->custom_uint;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    TCP_Connection_to *con_to = get_connection(tcp_c, number);
    if (!con_to)
        return -1;
    if (tcp_c->tcp_data_callback)
        tcp_c->tcp_data_callback(tcp_c->
      tcp_data_callback_object, con_to->id, data, length);
    return 0;
}
static int tcp_onion_callback (void * object, const uint8_t * data, uint16_t length) [static]
Definition at line 937 of file TCP_connection.c.
References TCP_Connections::tcp_onion_callback, and TCP_Connections::tcp_onion_callback_object.
Referenced by set_onion_packet_tcp_connection_callback(), and tcp_relay_set_callbacks().
{
    TCP_Connections *tcp_c = object;
    if (tcp_c->tcp_onion_callback)
        tcp_c->tcp_onion_callback(tcp_c->
      tcp_onion_callback_object, data, length);
    return 0;
}
static int tcp_oob_callback (void * object, const uint8_t * public_key, const uint8_t * data, uint16_t length) [static]
Definition at line 908 of file TCP_connection.c.
References TCP_Client_Connection::custom_object, TCP_Client_Connection::custom_uint, find_tcp_connection_to(), get_connection(), get_tcp_connection(), tcp_connection_in_conn(), tcp_data_callback(), TCP_Connections::tcp_oob_callback, and TCP_Connections::tcp_oob_callback_object.
Referenced by set_oob_packet_tcp_connection_callback(), and tcp_relay_set_callbacks().
{
    if (length == 0)
        return -1;
    TCP_Client_Connection *TCP_client_con = object;
    TCP_Connections *tcp_c = TCP_client_con->custom_object;
    unsigned int tcp_connections_number = TCP_client_con->custom_uint;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    /* TODO: optimize */
    int connections_number = find_tcp_connection_to(tcp_c,
      public_key);
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (con_to && tcp_connection_in_conn(con_to, tcp_connections_number)) {
        return tcp_data_callback(object, connections_number, 0,
      data, length);
    } else {
        if (tcp_c->tcp_oob_callback)
            tcp_c->tcp_oob_callback(tcp_c->
      tcp_oob_callback_object, public_key, tcp_connections_number,
      data, length);
    }
    return 0;
}
static int tcp_relay_on_online (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 972 of file TCP_connection.c.
References TCP_con::connected_time, TCP_Connections::connections_length, get_connection(), get_tcp_connection(), i, NUM_ONION_TCP_CONNECTIONS, TCP_con::onion, TCP_Connections::onion_num_conns, TCP_Connections::onion_status, TCP_Connection_to::public_key, send_tcp_relay_routing_request(), TCP_con::status, TCP_CONN_CONNECTED, tcp_connection_in_conn(), tcp_relay_set_callbacks(), and unix_time().
Referenced by do_tcp_conns().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    unsigned int i, sent = 0;
    for (i = 0; i < tcp_c->connections_length; ++i) {
        TCP_Connection_to *con_to = get_connection(tcp_c, i);
        if (con_to) {
            if (tcp_connection_in_conn(con_to, tcp_connections_number)) {
                if (send_tcp_relay_routing_request(tcp_c,
      tcp_connections_number, con_to->public_key) == 0) {
                    ++sent;
                }
            }
        }
    }
    tcp_relay_set_callbacks(tcp_c, tcp_connections_number);
    tcp_con->status = TCP_CONN_CONNECTED;
    /* If this connection isn't used by any connection, we don't need to wait for them to come online. */
    if (sent) {
        tcp_con->connected_time = unix_time();
    } else {
        tcp_con->connected_time = 0;
    }
    if (tcp_c->onion_status && tcp_c->onion_num_conns <
      NUM_ONION_TCP_CONNECTIONS) {
        tcp_con->onion = 1;
        ++tcp_c->onion_num_conns;
    }
    return 0;
}
static int tcp_relay_set_callbacks (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 952 of file TCP_connection.c.
References TCP_con::connection, TCP_Client_Connection::custom_object, TCP_Client_Connection::custom_uint, get_tcp_connection(), onion_response_handler(), oob_data_handler(), routing_data_handler(), routing_response_handler(), routing_status_handler(), tcp_data_callback(), tcp_onion_callback(), tcp_oob_callback(), tcp_response_callback(), and tcp_status_callback().
Referenced by tcp_relay_on_online().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    TCP_Client_Connection *con = tcp_con->connection;
    con->custom_object = tcp_c;
    con->custom_uint = tcp_connections_number;
    onion_response_handler(con, &tcp_onion_callback, tcp_c);
    routing_response_handler(con, &tcp_response_callback, con)
      ;
    routing_status_handler(con, &tcp_status_callback, con);
    routing_data_handler(con, &tcp_data_callback, con);
    oob_data_handler(con, &tcp_oob_callback, con);
    return 0;
}
static int tcp_response_callback (void * object, uint8_t connection_id, const uint8_t * public_key) [static]
Definition at line 818 of file TCP_connection.c.
References TCP_con::connection, TCP_Client_Connection::custom_object, TCP_Client_Connection::custom_uint, find_tcp_connection_to(), get_connection(), get_tcp_connection(), set_tcp_connection_number(), set_tcp_connection_status(), and TCP_CONNECTIONS_STATUS_REGISTERED.
Referenced by tcp_relay_set_callbacks().
{
    TCP_Client_Connection *TCP_client_con = object;
    TCP_Connections *tcp_c = TCP_client_con->custom_object;
    unsigned int tcp_connections_number = TCP_client_con->custom_uint;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    int connections_number = find_tcp_connection_to(tcp_c,
      public_key);
    if (connections_number == -1)
        return -1;
    TCP_Connection_to *con_to = get_connection(tcp_c, connections_number);
    if (con_to == NULL)
        return -1;
    if (set_tcp_connection_status(con_to, tcp_connections_number,
      TCP_CONNECTIONS_STATUS_REGISTERED, connection_id) == -1)
        return -1;
    set_tcp_connection_number(tcp_con->connection, connection_id,
      connections_number);
    return 0;
}
int tcp_send_onion_request (TCP_Connections * tcp_c, unsigned int tcp_connections_number, const uint8_t * data, uint16_t length)
Definition at line 305 of file TCP_connection.c.
References TCP_con::connection, send_onion_request(), TCP_con::status, TCP_CONN_CONNECTED, TCP_Connections::tcp_connections, and TCP_Connections::tcp_connections_length.
Referenced by send_tcp_onion_request().
{
    if (tcp_connections_number >= tcp_c->tcp_connections_length) {
        return -1;
    }
    if (tcp_c->tcp_connections[tcp_connections_number].status ==
      TCP_CONN_CONNECTED) {
        int ret = send_onion_request(tcp_c->tcp_connections[
      tcp_connections_number].connection, data, length);
        if (ret == 1)
            return 0;
    }
    return -1;
}
int tcp_send_oob_packet (TCP_Connections * tcp_c, unsigned int tcp_connections_number, const uint8_t * public_key, const uint8_t * packet, uint16_t length)
Definition at line 327 of file TCP_connection.c.
References TCP_con::connection, get_tcp_connection(), send_oob_packet(), TCP_con::status, and TCP_CONN_CONNECTED.
Referenced by tcp_oob_handle_cookie_request(), and tcp_oobdata_callback().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status != TCP_CONN_CONNECTED)
        return -1;
    int ret = send_oob_packet(tcp_con->connection,
      public_key, packet, length);
    if (ret == 1)
        return 0;
    return -1;
}
static int tcp_status_callback (void * object, uint32_t number, uint8_t connection_id, uint8_t status) [static]
Definition at line 847 of file TCP_connection.c.
References TCP_Client_Connection::custom_object, TCP_Client_Connection::custom_uint, get_connection(), get_tcp_connection(), TCP_con::lock_count, set_tcp_connection_status(), TCP_con::sleep_count, TCP_Connection_to::status, TCP_CONN_SLEEPING, TCP_CONNECTIONS_STATUS_ONLINE, and TCP_CONNECTIONS_STATUS_REGISTERED.
Referenced by tcp_relay_set_callbacks().
{
    TCP_Client_Connection *TCP_client_con = object;
    TCP_Connections *tcp_c = TCP_client_con->custom_object;
    unsigned int tcp_connections_number = TCP_client_con->custom_uint;
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    TCP_Connection_to *con_to = get_connection(tcp_c, number);
    if (!con_to || !tcp_con)
        return -1;
    if (status == 1) {
        if (set_tcp_connection_status(con_to, tcp_connections_number,
      TCP_CONNECTIONS_STATUS_REGISTERED, connection_id) == -1)
            return -1;
        --tcp_con->lock_count;
        if (con_to->status == TCP_CONN_SLEEPING) {
            --tcp_con->sleep_count;
        }
    } else if (status == 2) {
        if (set_tcp_connection_status(con_to, tcp_connections_number,
      TCP_CONNECTIONS_STATUS_ONLINE, connection_id) == -1)
            return -1;
        ++tcp_con->lock_count;
        if (con_to->status == TCP_CONN_SLEEPING) {
            ++tcp_con->sleep_count;
        }
    }
    return 0;
}
static int unsleep_tcp_relay_connection (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 771 of file TCP_connection.c.
References TCP_con::connected_time, TCP_con::connection, get_tcp_connection(), TCP_con::ip_port, kill_tcp_relay_connection(), TCP_con::lock_count, new_TCP_connection(), TCP_Connections::proxy_info, TCP_con::relay_pk, TCP_Connections::self_public_key, TCP_Connections::self_secret_key, TCP_con::sleep_count, TCP_con::status, TCP_CONN_SLEEPING, TCP_CONN_VALID, and TCP_con::unsleep.
Referenced by do_tcp_conns().
{
    TCP_con *tcp_con = get_tcp_connection(tcp_c, tcp_connections_number);
    if (!tcp_con)
        return -1;
    if (tcp_con->status != TCP_CONN_SLEEPING)
        return -1;
    tcp_con->connection = new_TCP_connection(tcp_con->
      ip_port, tcp_con->relay_pk, tcp_c->self_public_key,
                          tcp_c->self_secret_key, &tcp_c->
      proxy_info);
    if (!tcp_con->connection) {
        kill_tcp_relay_connection(tcp_c, tcp_connections_number);
        return -1;
    }
    tcp_con->lock_count = 0;
    tcp_con->sleep_count = 0;
    tcp_con->connected_time = 0;
    tcp_con->status = TCP_CONN_VALID;
    tcp_con->unsleep = 0;
    return 0;
}
static int wipe_connection (TCP_Connections * tcp_c, int connections_number) [static]
Definition at line 133 of file TCP_connection.c.
References TCP_Connections::connections, TCP_Connections::connections_length, connections_number_not_valid(), i, realloc_tox_array, TCP_Connection_to::status, and TCP_CONN_NONE.
Referenced by kill_tcp_connection_to().
{
    if (connections_number_not_valid(tcp_c, connections_number))
        return -1;
    uint32_t i;
    memset(&(tcp_c->connections[connections_number]), 0 , sizeof(
      TCP_Connection_to));
    for (i = tcp_c->connections_length; i != 0; --i) {
        if (tcp_c->connections[i - 1].status != TCP_CONN_NONE)
            break;
    }
    if (tcp_c->connections_length != i) {
        tcp_c->connections_length = i;
        TCP_Connection_to *temp_pointer;
        realloc_tox_array(tcp_c->connections, sizeof(
      TCP_Connection_to), tcp_c->connections_length, temp_pointer);
    }
    return 0;
}
static int wipe_tcp_connection (TCP_Connections * tcp_c, int tcp_connections_number) [static]
Definition at line 160 of file TCP_connection.c.
References i, realloc_tox_array, TCP_con::status, TCP_CONN_NONE, TCP_Connections::tcp_connections, TCP_Connections::tcp_connections_length, and tcp_connections_number_not_valid().
Referenced by kill_tcp_relay_connection().
{
    if (tcp_connections_number_not_valid(tcp_c, tcp_connections_number))
        return -1;
    uint32_t i;
    memset(&(tcp_c->tcp_connections[tcp_connections_number]), 0 , sizeof(
      TCP_con));
    for (i = tcp_c->tcp_connections_length; i != 0; --i) {
        if (tcp_c->tcp_connections[i - 1].status !=
      TCP_CONN_NONE)
            break;
    }
    if (tcp_c->tcp_connections_length != i) {
        tcp_c->tcp_connections_length = i;
        TCP_con *temp_pointer;
        realloc_tox_array(tcp_c->tcp_connections, sizeof(
      TCP_con), tcp_c->tcp_connections_length, temp_pointer);
    }
    return 0;
}