toxcore/assoc.c File Reference
#include `logger.h`
*
#include `DHT.h`
*
#include `assoc.h`
*
#include `ping.h`
*
#include `LAN_discovery.h`
*
#include <assert.h>
*
#include `util.h`
*
Data Structures
struct Client_entry
struct candidates_bucket
struct Assoc
Macros
#define HASH_COLLIDE_COUNT 5
#define HASH_COLLIDE_PRIME 101
#define CANDIDATES_SEEN_TIMEOUT 1800
#define CANDIDATES_HEARD_TIMEOUT 600
#define DISTANCE_INDEX_INDEX_BITS (64 - DISTANCE_INDEX_DISTANCE_BITS)
#define DISTANCE_INDEX_INDEX_MASK ((1 << DISTANCE_INDEX_INDEX_BITS) - 1)
Typedefs
typedef uint16_t bucket_t
typedef uint32_t hash_t
typedef uint16_t usecnt_t
typedef
*
Assoc_distance_relative_callback dist_rel_cb
typedef
*
Assoc_distance_absolute_callback dist_abs_cb
typedef struct Client_entry Client_entry
typedef struct candidates_bucket candidates_bucket
Functions
static uint64_t id_distance (const Assoc *assoc, void *callback_data, const uint8_t *id_ref, const uint8_t *id_test)
static int dist_index_comp (const void *a, const void *b)
static Client_entry * dist_index_entry (Assoc *assoc, uint64_t dist_ind)
static uint8_t * dist_index_id (Assoc *assoc, uint64_t dist_ind)
static void dist_index_bubble (Assoc *assoc, uint64_t *dist_list, size_t first, size_t last, uint8_t *id, void *custom_data, Assoc_distance_relative_callback dist_rel_func)
static hash_t id_hash (const Assoc *assoc, const uint8_t *id)
static hash_t hash_collide (const Assoc *assoc, hash_t hash)
static IPPTsPng * entry_assoc (Client_entry *cl_entry, const IP_Port *ipp)
static IP_Port * entry_heard_get (Client_entry *entry, const IP_Port *ipp)
static int entry_heard_store (Client_entry *entry, const IPPTs *ippts)
static int assoc_id_closest (const Assoc *assoc, void *callback_data, const uint8_t *client_id, const uint8_t *client_id1, const uint8_t *client_id2)
static bucket_t id_bucket (const uint8_t *id, uint8_t bits)
static bucket_t candidates_id_bucket (const Assoc *assoc, const uint8_t *id)
static uint8_t candidates_search (const Assoc *assoc, const uint8_t *id, hash_t hash, Client_entry **entryptr)
static void candidates_update_assoc (const Assoc *assoc, Client_entry *entry, uint8_t used, const IPPTs *ippts_send, const IP_Port *ipp_recv)
static uint8_t candidates_create_internal (const Assoc *assoc, hash_t const hash, const uint8_t *id, uint8_t seen, uint8_t used, bucket_t *bucketptr, size_t *posptr)
static uint8_t candidates_create_new (const Assoc *assoc, hash_t hash, const uint8_t *id, uint8_t used, const IPPTs *ippts_send, const IP_Port *ipp_recv)
static void client_id_self_update (Assoc *assoc)
uint8_t Assoc_add_entry (Assoc *assoc, const uint8_t *id, const IPPTs *ippts_send, const IP_Port *ipp_recv, uint8_t used)
uint8_t Assoc_get_close_entries (Assoc *assoc, Assoc_close_entries *state)
static uint8_t odd_min9_is_prime (size_t value)
static size_t prime_upto_min9 (size_t limit)
Assoc * new_Assoc (size_t bits, size_t entries, const uint8_t *public_id)
Assoc * new_Assoc_default (const uint8_t *public_id)
void Assoc_self_client_id_changed (Assoc *assoc, const uint8_t *id)
void do_Assoc (Assoc *assoc, DHT *dht)
void kill_Assoc (Assoc *assoc)
Macro Definition Documentation
#define CANDIDATES_HEARD_TIMEOUT 600
Definition at line 47 of file assoc.c.
Referenced by candidates_create_internal(), do_Assoc(), and entry_heard_store().
#define CANDIDATES_SEEN_TIMEOUT 1800
Definition at line 46 of file assoc.c.
Referenced by candidates_create_internal(), and do_Assoc().
#define DISTANCE_INDEX_INDEX_BITS (64 - DISTANCE_INDEX_DISTANCE_BITS)
Definition at line 50 of file assoc.c.
Referenced by Assoc_get_close_entries().
#define DISTANCE_INDEX_INDEX_MASK ((1 << DISTANCE_INDEX_INDEX_BITS) - 1)
Definition at line 51 of file assoc.c.
Referenced by Assoc_get_close_entries(), and dist_index_entry().
#define HASH_COLLIDE_COUNT 5
Definition at line 40 of file assoc.c.
Referenced by candidates_create_internal(), candidates_search(), and client_id_self_update().
#define HASH_COLLIDE_PRIME 101
Definition at line 43 of file assoc.c.
Referenced by hash_collide(), and new_Assoc().
Typedef Documentation
typedef uint16_t bucket_t
Definition at line 54 of file assoc.c.
typedef struct candidates_bucket candidates_bucket
typedef struct Client_entry Client_entry
typedef Assoc_distance_absolute_callback dist_abs_cb
Definition at line 60 of file assoc.c.
typedef Assoc_distance_relative_callback dist_rel_cb
Definition at line 59 of file assoc.c.
typedef uint32_t hash_t
Definition at line 55 of file assoc.c.
typedef uint16_t usecnt_t
Definition at line 56 of file assoc.c.
Function Documentation
uint8_t Assoc_add_entry (Assoc * assoc, const uint8_t * id, const IPPTs * ippts_send, const IP_Port * ipp_recv, uint8_t used)
Definition at line 552 of file assoc.c.
References candidates_create_new(), candidates_search(), candidates_update_assoc(), client_id_self_update(), id_equal(), id_hash(), IPPTs::ip_port, ipport_isset(), Assoc::self_client_id, and Assoc::self_hash.
Referenced by addto_lists(), returnedip_ports(), and START_TEST().
{
    if (!assoc || !id || !ippts_send)
        return 0;
    if (!assoc->self_hash) {
        client_id_self_update(assoc);
        if (!assoc->self_hash)
            return 0;
    }
    if (!ipport_isset(&ippts_send->ip_port))
        return 0;
    if (ipp_recv && !ipport_isset(ipp_recv))
        ipp_recv = NULL;
    hash_t hash = id_hash(assoc, id);
    if (hash == assoc->self_hash)
        if (id_equal(id, assoc->self_client_id))
            return 0;
    /* if it's new:
     * callback, if there's desire, add to clients, else to candidates
     *
     * if it's "old":
     * if it's client: refresh
     * if it's candidate:
     * if !ipp_recv, refresh
     * if ipp_recv: callback, if there's desire, move to candidates
     */
    Client_entry *cnd_entry;
    if (!candidates_search(assoc, id, hash, &cnd_entry)) {
        if (candidates_create_new(assoc, hash, id, used, ippts_send, ipp_recv))
            return 1;
        else
            return 0;
    } else {
        candidates_update_assoc(assoc, cnd_entry, used, ippts_send, ipp_recv);
        return 2;
    }
}
uint8_t Assoc_get_close_entries (Assoc * assoc, Assoc_close_entries * state)
Definition at line 602 of file assoc.c.
References Client_data::assoc4, Client_data::assoc6, assoc_id_closest(), BAD_NODE_TIMEOUT, Assoc::candidates, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, Client_entry::client, client_id_self_update(), Assoc_close_entries::count_good, Assoc_close_entries::custom_data, dist_index_bubble(), dist_index_comp(), dist_index_entry(), Assoc_close_entries::distance_absolute_func, DISTANCE_INDEX_INDEX_BITS, DISTANCE_INDEX_INDEX_MASK, Assoc_close_entries::distance_relative_func, Assoc_close_entries::flags, Client_entry::hash, i, id_distance(), IP_Port::ip, IPPTsPng::ip_port, ipport_isset(), is_timeout(), LAN_ip(), LANOk, candidates_bucket::list, ProtoIPv4, ProtoIPv6, Client_data::public_key, Assoc_close_entries::result, Client_entry::seen_at, Assoc::self_hash, IPPTsPng::timestamp, and Assoc_close_entries::wanted_id.
Referenced by DHT_addfriend(), get_close_nodes(), and START_TEST().
{
    if (!assoc || !state || !state->wanted_id || !state->result)
        return 0;
    if (!assoc->self_hash) {
        client_id_self_update(assoc);
        if (!assoc->self_hash)
            return 0;
    }
    if (!state->distance_relative_func)
        state->distance_relative_func = assoc_id_closest;
    if (!state->distance_absolute_func)
        state->distance_absolute_func = id_distance;
    size_t dist_list_len = assoc->candidates_bucket_count * assoc->
      candidates_bucket_size;
    uint64_t dist_list[dist_list_len];
    memset(dist_list, ~0, dist_list_len * sizeof(dist_list[0]));
    bucket_t b;
    size_t i;
    for (b = 0; b < assoc->candidates_bucket_count; b++) {
        candidates_bucket *cnd_bckt = &assoc->candidates[b];
        for (i = 0; i < assoc->candidates_bucket_size; i++) {
            Client_entry *entry = &cnd_bckt->list[i];
            if (entry->hash) {
                if (state->flags & ProtoIPv4) {
                    if (!ipport_isset(&entry->client.assoc4.
      ip_port))
                        continue;
                    if (!(state->flags & LANOk))
                        if (!LAN_ip(entry->client.assoc4.
      ip_port.ip))
                            continue;
                }
                if (state->flags & ProtoIPv6) {
                    if (!ipport_isset(&entry->client.assoc6.
      ip_port))
                        continue;
                    if (!(state->flags & LANOk))
                        if (!LAN_ip(entry->client.assoc6.
      ip_port.ip))
                            continue;
                }
                uint64_t dist = state->distance_absolute_func(assoc, state->
      custom_data, state->wanted_id, entry->client.
      public_key);
                uint32_t index = b * assoc->candidates_bucket_size +
      i;
                dist_list[index] = (dist << DISTANCE_INDEX_INDEX_BITS) | index;
            }
        }
    }
    qsort(dist_list, dist_list_len, sizeof(dist_list[0]), dist_index_comp);
    /* ok, ok, it's not *perfectly* sorted, because we used an absolute distance
     * go over the result and see if we need to "smoothen things out"
     * because those should be only very few and short streaks, the worst regularly
     * used sorting function aka bubble sort is used */
    uint64_t dist_prev = ~0;
    size_t ind_prev = ~0, ind_curr;
    size_t len = 1;
    for (ind_curr = 0; ind_curr < dist_list_len; ind_curr++) {
        /* sorted increasingly, so an invalid entry marks the end */
        if ((dist_list[ind_curr] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
            break;
        uint64_t dist_curr = dist_list[ind_curr] >> DISTANCE_INDEX_INDEX_BITS;
        if (dist_prev == dist_curr)
            len++;
        else {
            if (len > 1)
                dist_index_bubble(assoc, dist_list, ind_prev, ind_curr - 1, state->
      wanted_id, state->custom_data,
                                  state->distance_relative_func);
            dist_prev = dist_curr;
            ind_prev = ind_curr;
            len = 1;
        }
    }
    if (len > 1)
        dist_index_bubble(assoc, dist_list, ind_prev, ind_curr - 1, state->
      wanted_id, state->custom_data,
                          state->distance_relative_func);
    /* ok, now dist_list is a strictly ascending sorted list of nodes
     * a) extract CLOSE_QUOTA_USED clients, not timed out
     * b) extract (1 - QUOTA) (better!) clients & candidates, not timed out
     * c) save candidates which would be better, if contact can be established */
    size_t client_quota_good = 0, pos = 0;
    size_t client_quota_max = state->count_good;
    ssize_t taken_last = - 1;
    for (i = 0; (i < dist_list_len) && (pos < state->count); i++) {
        /* sorted increasingly, so an invalid entry marks the end */
        if ((dist_list[i] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
            break;
        Client_entry *entry = dist_index_entry(assoc, dist_list[i]);
        if (entry && entry->hash) {
            if (client_quota_good >= client_quota_max) {
                state->result[pos++] = &entry->client;
                taken_last = i;
            } else {
                if (state->flags & (ProtoIPv4 | ProtoIPv6)) {
                    if ((state->flags & ProtoIPv4) && is_timeout(entry->
      client.assoc4.timestamp, BAD_NODE_TIMEOUT))
                        continue;
                    if ((state->flags & ProtoIPv6) && is_timeout(entry->
      client.assoc6.timestamp, BAD_NODE_TIMEOUT))
                        continue;
                } else if (is_timeout(entry->seen_at,
      BAD_NODE_TIMEOUT))
                    continue;
                state->result[pos++] = &entry->client;
                client_quota_good++;
                taken_last = i;
            }
        }
    }
    /* if we had not enough valid entries the list might still not be filled.
     *
     * start again from last taken client, but leave out any requirement
     */
    if (pos < state->count) {
        for (i = taken_last + 1; (i < dist_list_len) && (pos < state->count); i++) {
            /* sorted increasingly, so an invalid entry marks the end */
            if ((dist_list[i] & DISTANCE_INDEX_INDEX_MASK) ==
      DISTANCE_INDEX_INDEX_MASK)
                break;
            Client_entry *entry = dist_index_entry(assoc, dist_list[i]);
            if (entry && entry->hash)
                state->result[pos++] = &entry->client;
        }
    }
    return pos;
}
static int assoc_id_closest (const Assoc * assoc, void * callback_data, const uint8_t * client_id, const uint8_t * client_id1, const uint8_t * client_id2) [static]
Definition at line 318 of file assoc.c.
References id_closest().
Referenced by Assoc_get_close_entries().
{
    return id_closest(client_id, client_id1, client_id2);
}
void Assoc_self_client_id_changed (Assoc * assoc, const uint8_t * id)
Definition at line 872 of file assoc.c.
References client_id_self_update(), id_copy(), Assoc::self_client_id, and Assoc::self_hash.
{
    if (assoc && id) {
        assoc->self_hash = 0;
        id_copy(assoc->self_client_id, id);
        client_id_self_update(assoc);
    }
}
static uint8_t candidates_create_internal (const Assoc * assoc, hash_t const hash, const uint8_t * id, uint8_t seen, uint8_t used, bucket_t * bucketptr, size_t * posptr) [static]
Definition at line 401 of file assoc.c.
References BAD, BAD_NODE_TIMEOUT, Assoc::candidates, Assoc::candidates_bucket_size, CANDIDATES_HEARD_TIMEOUT, candidates_id_bucket(), CANDIDATES_SEEN_TIMEOUT, Client_entry::hash, hash_collide(), HASH_COLLIDE_COUNT, Client_entry::heard_at, i, is_timeout(), candidates_bucket::list, Client_entry::seen_at, SEENB_HEARDG, SEENG, USED, and Client_entry::used_at.
Referenced by candidates_create_new().
{
    if (!assoc || !id || !bucketptr || !posptr)
        return 0;
    bucket_t bucket = candidates_id_bucket(assoc, id);
    candidates_bucket *cnd_bckt = &assoc->candidates[bucket];
    size_t coll, pos = hash % assoc->candidates_bucket_size, check;
    size_t pos_check[6];
    memset(pos_check, 0, sizeof(pos_check));
    for (coll = 0; coll < HASH_COLLIDE_COUNT; pos =
      hash_collide(assoc, pos) , coll++) {
        Client_entry *entry = &cnd_bckt->list[pos];
        /* unset */
        if (!entry->hash) {
            *bucketptr = bucket;
            *posptr = pos;
            return 1;
        }
        /* 0. bad
         * 1. seen bad, heard good
         * 2. seen good
         * 3. used */
        // enumerated lists are superior to magic numbers
        if (!is_timeout(entry->used_at, BAD_NODE_TIMEOUT))
            check = USED;
        else if (!is_timeout(entry->seen_at,
      CANDIDATES_SEEN_TIMEOUT))
            check = SEENG;
        else if (!is_timeout(entry->heard_at,
      CANDIDATES_HEARD_TIMEOUT))
            check = SEENB_HEARDG;
        else
            check = BAD;
        if (!pos_check[check])
            pos_check[check] = pos + 1;
    }
    /* used > seen > heard > bad */
    size_t i, pos_max = used ? USED : (seen ? SEENG : SEENB_HEARDG);
    for (i = 0; i < pos_max; i++)
        if (pos_check[i]) {
            *bucketptr = bucket;
            *posptr = pos_check[i] - 1;
            return 1;
        }
    return 0;
}
static uint8_t candidates_create_new (const Assoc * assoc, hash_t hash, const uint8_t * id, uint8_t used, const IPPTs * ippts_send, const IP_Port * ipp_recv) [static]
Definition at line 458 of file assoc.c.
References Assoc::candidates, candidates_create_internal(), Client_entry::client, entry_assoc(), entry_heard_get(), IP::family, Client_entry::hash, Client_entry::heard_at, Client_entry::heard_family, id_copy(), IP_Port::ip, IPPTs::ip_port, IPPTsPng::ip_port, ipport_isset(), candidates_bucket::list, Client_data::public_key, IPPTsPng::ret_ip_port, IPPTsPng::ret_timestamp, Client_entry::seen_at, Client_entry::seen_family, IPPTs::timestamp, IPPTsPng::timestamp, unix_time(), and Client_entry::used_at.
Referenced by Assoc_add_entry().
{
    if (!assoc || !id || !ippts_send)
        return 0;
    bucket_t bucket;
    size_t pos;
    if (!candidates_create_internal(assoc, hash, id, ipp_recv != NULL, used, &
      bucket, &pos))
        return 0;
    candidates_bucket *cnd_bckt = &assoc->candidates[bucket];
    Client_entry *entry = &cnd_bckt->list[pos];
    memset(entry, 0, sizeof(*entry));
    IPPTsPng *ipptsp = entry_assoc(entry, &ippts_send->
      ip_port);
    if (!ipptsp)
        return 0;
    entry->hash = hash;
    id_copy(entry->client.public_key, id);
    if (used)
        entry->used_at = unix_time();
    if (ipp_recv && !ipport_isset(ipp_recv))
        ipp_recv = NULL;
    if (ipp_recv) {
        entry->seen_at = ippts_send->timestamp;
        entry->seen_family = ippts_send->ip_port.ip.family;
        ipptsp->ip_port = ippts_send->ip_port;
        ipptsp->timestamp = ippts_send->timestamp;
        ipptsp->ret_ip_port = *ipp_recv;
        ipptsp->ret_timestamp = unix_time();
    } else {
        IP_Port *heard = entry_heard_get(entry, &ippts_send->
      ip_port);
        if (heard) {
            entry->heard_at = ippts_send->timestamp;
            entry->heard_family = ippts_send->ip_port.ip.
      family;
            *heard = ippts_send->ip_port;
        }
    }
    return 1;
}
static bucket_t candidates_id_bucket (const Assoc * assoc, const uint8_t * id) [static]
Definition at line 344 of file assoc.c.
References Assoc::candidates_bucket_bits, and id_bucket().
Referenced by candidates_create_internal(), candidates_search(), and client_id_self_update().
{
    return id_bucket(id, assoc->candidates_bucket_bits);
}
static uint8_t candidates_search (const Assoc * assoc, const uint8_t * id, hash_t hash, Client_entry ** entryptr) [static]
Definition at line 349 of file assoc.c.
References Assoc::candidates, Assoc::candidates_bucket_size, candidates_id_bucket(), Client_entry::client, Client_entry::hash, hash_collide(), HASH_COLLIDE_COUNT, id_equal(), candidates_bucket::list, and Client_data::public_key.
Referenced by Assoc_add_entry().
{
    bucket_t bucket = candidates_id_bucket(assoc, id);
    candidates_bucket *cnd_bckt = &assoc->candidates[bucket];
    size_t coll, pos = hash % assoc->candidates_bucket_size;
    for (coll = 0; coll < HASH_COLLIDE_COUNT; pos =
      hash_collide(assoc, pos) , coll++) {
        Client_entry *entry = &cnd_bckt->list[pos];
        if (entry->hash == hash)
            if (id_equal(entry->client.public_key, id)) {
                *entryptr = entry;
                return 1;
            }
    }
    *entryptr = NULL;
    return 0;
}
static void candidates_update_assoc (const Assoc * assoc, Client_entry * entry, uint8_t used, const IPPTs * ippts_send, const IP_Port * ipp_recv) [static]
Definition at line 369 of file assoc.c.
References entry_assoc(), entry_heard_store(), IP::family, IP_Port::ip, IPPTs::ip_port, IPPTsPng::ip_port, IPPTsPng::ret_ip_port, IPPTsPng::ret_timestamp, Client_entry::seen_at, Client_entry::seen_family, IPPTs::timestamp, IPPTsPng::timestamp, unix_time(), and Client_entry::used_at.
Referenced by Assoc_add_entry().
{
    if (!assoc || !entry || !ippts_send)
        return;
    IPPTsPng *ipptsp = entry_assoc(entry, &ippts_send->
      ip_port);
    if (!ipptsp)
        return;
    if (used)
        entry->used_at = unix_time();
    /* do NOT do anything related to wanted, that's handled outside,
     * just update the assoc (in the most sensible way)
     */
    if (ipp_recv) {
        ipptsp->ip_port = ippts_send->ip_port;
        ipptsp->timestamp = ippts_send->timestamp;
        ipptsp->ret_ip_port = *ipp_recv;
        ipptsp->ret_timestamp = unix_time();
        entry->seen_at = unix_time();
        entry->seen_family = ippts_send->ip_port.ip.family;
        return;
    }
    entry_heard_store(entry, ippts_send);
}
static void client_id_self_update (Assoc * assoc) [static]
Definition at line 511 of file assoc.c.
References Assoc::candidates, Assoc::candidates_bucket_size, candidates_id_bucket(), Client_entry::client, Client_entry::hash, hash_collide(), HASH_COLLIDE_COUNT, i, id_equal(), id_hash(), candidates_bucket::list, LOGGER_DEBUG, Client_data::public_key, Assoc::self_client_id, and Assoc::self_hash.
Referenced by Assoc_add_entry(), Assoc_get_close_entries(), Assoc_self_client_id_changed(), and new_Assoc().
{
    if (assoc->self_hash)
        return;
    size_t i, sum = 0;
    for (i = 0; i < crypto_box_PUBLICKEYBYTES; i++)
        sum |= assoc->self_client_id[i];
    if (!sum)
        return;
    assoc->self_hash = id_hash(assoc, assoc->self_client_id);
    LOGGER_DEBUG("id is now set, purging cache of self-references");
    /* if we already added some (or loaded some) entries,
     * look and remove if we find a match
     */
    bucket_t b_id = candidates_id_bucket(assoc, assoc->
      self_client_id);
    candidates_bucket *cnd_bckt = &assoc->candidates[b_id];
    size_t pos = assoc->self_hash % assoc->candidates_bucket_size;
    for (i = 0; i < HASH_COLLIDE_COUNT; pos = hash_collide(assoc, pos), i++)
      {
        Client_entry *entry = &cnd_bckt->list[pos];
        if (entry->hash == assoc->self_hash)
            if (id_equal(entry->client.public_key, assoc->
      self_client_id))
                entry->hash = 0;
    }
}
static void dist_index_bubble (Assoc * assoc, uint64_t * dist_list, size_t first, size_t last, uint8_t * id, void * custom_data, Assoc_distance_relative_callback dist_rel_func) [static]
Definition at line 172 of file assoc.c.
References dist_index_id(), i, last, and swap.
Referenced by Assoc_get_close_entries().
{
    size_t i, k;
    for (i = first; i <= last; i++) {
        uint8_t *id1 = dist_index_id(assoc, dist_list[i]);
        for (k = i + 1; k <= last; k++) {
            uint8_t *id2 = dist_index_id(assoc, dist_list[k]);
            if (id1 && id2)
                if (dist_rel_func(assoc, custom_data, id, id1, id2) == 2) {
                    uint64_t swap = dist_list[i];
                    dist_list[i] = dist_list[k];
                    dist_list[k] = swap;
                }
        }
    }
}
static int dist_index_comp (const void * a, const void * b) [static]
Definition at line 124 of file assoc.c.
Referenced by Assoc_get_close_entries().
{
    const uint64_t *_a = a;
    const uint64_t *_b = b;
    if (*_a < *_b)
        return -1;
    if (*_a > *_b)
        return 1;
    return 0;
}
static Client_entry* dist_index_entry (Assoc * assoc, uint64_t dist_ind) [static]
Definition at line 139 of file assoc.c.
References Assoc::candidates, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, DISTANCE_INDEX_INDEX_MASK, Client_entry::hash, and candidates_bucket::list.
Referenced by Assoc_get_close_entries(), and dist_index_id().
{
    if ((dist_ind & DISTANCE_INDEX_INDEX_MASK) == DISTANCE_INDEX_INDEX_MASK)
        return NULL;
    size_t total = assoc->candidates_bucket_count * assoc->
      candidates_bucket_size;
    uint32_t index = dist_ind & DISTANCE_INDEX_INDEX_MASK;
    if (index < total) {
        bucket_t b_id = index / assoc->candidates_bucket_size;
        candidates_bucket *cnd_bckt = &assoc->candidates[b_id];
        size_t b_ix = index % assoc->candidates_bucket_size;
        Client_entry *entry = &cnd_bckt->list[b_ix];
        if (entry->hash)
            return entry;
    }
    return NULL;
}
static uint8_t* dist_index_id (Assoc * assoc, uint64_t dist_ind) [static]
Definition at line 161 of file assoc.c.
References Client_entry::client, dist_index_entry(), and Client_data::public_key.
Referenced by dist_index_bubble().
{
    Client_entry *entry = dist_index_entry(assoc, dist_ind);
    if (entry)
        return entry->client.public_key;
    return NULL;
}
void do_Assoc (Assoc * assoc, DHT * dht)
Definition at line 886 of file assoc.c.
References ASSOC_BUCKET_REFRESH, Assoc::candidates, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, CANDIDATES_HEARD_TIMEOUT, CANDIDATES_SEEN_TIMEOUT, Client_entry::client, DHT_getnodes(), for(), Client_entry::getnodes, Assoc::getnodes, Client_entry::hash, Client_entry::heard_at, i, IP_Port::ip, ip_ntoa(), IPPTsPng::ip_port, is_timeout(), candidates_bucket::list, LOGGER_DEBUG, LOGGER_SCOPE, m, IP_Port::port, Client_data::public_key, Client_entry::seen_at, and unix_time().
Referenced by do_DHT().
{
    if (is_timeout(assoc->getnodes, ASSOC_BUCKET_REFRESH)) {
        assoc->getnodes = unix_time();
        size_t candidate = (rand() % assoc->candidates_bucket_count) + assoc->
      candidates_bucket_count;
        /* in that bucket or the buckets closest to it:
         * find the best heard candidate
         * find the best seen candidate
         * send getnode() requests to both */
        uint8_t *target_id = NULL;
        Client_entry *heard = NULL, *seen = NULL;
        size_t i, k, m;
        for (i = 1; i < assoc->candidates_bucket_count; i++) {
            if (i % 2)
                k = - (i >> 1);
            else
                k = i >> 1;
            size_t bckt = (candidate + k) % assoc->candidates_bucket_count;
            for (m = 0; m < assoc->candidates_bucket_size;
      m++)
                if (assoc->candidates[bckt].list[m].hash) {
                    Client_entry *entry = &assoc->candidates[bckt].
      list[m];
                    if (!is_timeout(entry->getnodes,
      CANDIDATES_SEEN_TIMEOUT))
                        continue;
                    if (!target_id)
                        target_id = entry->client.public_key;
                    if (entry->seen_at) {
                        if (!seen)
                            if (!is_timeout(entry->seen_at,
      CANDIDATES_SEEN_TIMEOUT))
                                seen = entry;
                    }
                    if (entry->heard_at) {
                        if (!heard)
                            if (!is_timeout(entry->heard_at,
      CANDIDATES_HEARD_TIMEOUT))
                                heard = entry;
                    }
                    if (seen && heard)
                        break;
                }
            if (seen && heard)
                break;
        }
        if (seen) {
            IPPTsPng *ippts = seen->seen_family == AF_INET ? &seen->client.assoc4 : &seen->client.
      assoc6;
            LOGGER_DEBUG("[%u] => S[%s...] %s:%u", (uint32_t)(candidate % assoc->
      candidates_bucket_count),
                         idpart2str(seen->client.public_key, 8), ip_ntoa(&ippts->
      ip_port.ip), htons(ippts->ip_port.port));
            DHT_getnodes(dht, &ippts->ip_port, seen->client.public_key, target_id);
            seen->getnodes = unix_time();
        }
        if (heard && (heard != seen)) {
            IP_Port *ipp = heard->heard_family == AF_INET ? &heard->assoc_heard4 : &heard->
      assoc_heard6;
            LOGGER_DEBUG("[%u] => H[%s...] %s:%u", (uint32_t)(candidate % assoc->
      candidates_bucket_count),
                         idpart2str(heard->client.public_key, 8), ip_ntoa(&ipp->
      ip), htons(ipp->port));
            DHT_getnodes(dht, ipp, heard->client.public_key, target_id);
            heard->getnodes = unix_time();
        }
        LOGGER_SCOPE (
            if (!heard && !seen)
            LOGGER_DEBUG("[%u] => no nodes to talk to??", (uint32_t)(candidate % assoc->
      candidates_bucket_count));
        );
    }
}
static IPPTsPng* entry_assoc (Client_entry * cl_entry, const IP_Port * ipp) [static]
Definition at line 244 of file assoc.c.
References Client_data::assoc4, Client_data::assoc6, Client_entry::client, IP::family, and IP_Port::ip.
Referenced by candidates_create_new(), and candidates_update_assoc().
{
    if (!cl_entry)
        return NULL;
    if (ipp->ip.family == AF_INET)
        return &cl_entry->client.assoc4;
    if (ipp->ip.family == AF_INET6)
        return &cl_entry->client.assoc6;
    return NULL;
}
static IP_Port* entry_heard_get (Client_entry * entry, const IP_Port * ipp) [static]
Definition at line 259 of file assoc.c.
References Client_entry::assoc_heard4, Client_entry::assoc_heard6, IP::family, and IP_Port::ip.
Referenced by candidates_create_new().
{
    if (ipp->ip.family == AF_INET)
        return &entry->assoc_heard4;
    else if (ipp->ip.family == AF_INET6)
        return &entry->assoc_heard6;
    else
        return NULL;
}
static int entry_heard_store (Client_entry * entry, const IPPTs * ippts) [static]
Definition at line 274 of file assoc.c.
References Client_entry::assoc_heard4, Client_entry::assoc_heard6, CANDIDATES_HEARD_TIMEOUT, IP::family, Client_entry::heard_at, Client_entry::heard_family, IP_Port::ip, IPPTs::ip_port, ipport_equal(), ipport_isset(), is_timeout(), LAN_ip(), and IPPTs::timestamp.
Referenced by candidates_update_assoc().
{
    if (!entry || !ippts)
        return 0;
    if (!ipport_isset(&ippts->ip_port))
        return 0;
    IP_Port *heard;
    const IP_Port *ipp = &ippts->ip_port;
    if (ipp->ip.family == AF_INET)
        heard = &entry->assoc_heard4;
    else if (ipp->ip.family == AF_INET6)
        heard = &entry->assoc_heard6;
    else
        return 0;
    if (ipport_equal(ipp, heard))
        return 0;
    if (!ipport_isset(heard)) {
        *heard = *ipp;
        entry->heard_at = ippts->timestamp;
        entry->heard_family = ipp->ip.family;
        return 1;
    }
    /* don't destroy a good address with a crappy one
     * (unless we're very timed out) */
    uint8_t LAN_ipp = LAN_ip(ipp->ip) == 0;
    uint8_t LAN_entry = LAN_ip(heard->ip) == 0;
    if (LAN_ipp && !LAN_entry && !is_timeout(entry->heard_at,
      CANDIDATES_HEARD_TIMEOUT))
        return 0;
    *heard = *ipp;
    entry->heard_at = ippts->timestamp;
    entry->heard_family = ipp->ip.family;
    return 1;
}
static hash_t hash_collide (const Assoc * assoc, hash_t hash) [static]
Definition at line 216 of file assoc.c.
References Assoc::candidates_bucket_size, and HASH_COLLIDE_PRIME.
Referenced by candidates_create_internal(), candidates_search(), and client_id_self_update().
{
    uint64_t hash64 = hash % assoc->candidates_bucket_size;
    hash64 = (hash64 * HASH_COLLIDE_PRIME) % assoc->
      candidates_bucket_size;
    hash_t retval = hash64;
    /* this should never happen when CANDIDATES_TO_KEEP is prime and hash not a multiple
     * (id_hash() checks for a multiple and returns a different hash in that case)
     *
     * (1 .. (prime - 1) is a group over multiplication and every number has its inverse
     * in the group, so no multiplication should ever end on zero as long neither
     * of the two factors was zero-equivalent)
     *
     * BUT: because the usage of the word "never" invokes Murphy's law, catch it */
    if (!retval) {
#ifdef DEBUG
        fprintf(stderr, "assoc::hash_collide: hash %u, bucket size %u => %u!", hash, (uint)assoc->
      candidates_bucket_size,
                retval);
        assert(retval != 0);
#endif
        retval = 1;
    }
    return retval;
}
static bucket_t id_bucket (const uint8_t * id, uint8_t bits) [static]
Definition at line 324 of file assoc.c.
Referenced by candidates_id_bucket().
{
    /* return the first "bits" bits of id */
    bucket_t retval = 0;
    uint8_t pos = 0;
    while (bits > 8) {
        retval = (retval << 8) | id[pos++];
        bits -= 8;
    }
    return (retval << bits) | (id[pos] >> (8 - bits));
}
static uint64_t id_distance (const Assoc * assoc, void * callback_data, const uint8_t * id_ref, const uint8_t * id_test) [static]
Definition at line 106 of file assoc.c.
References DISTANCE_INDEX_DISTANCE_BITS.
Referenced by Assoc_get_close_entries().
{
    /* with BIG_ENDIAN, this would be a one-liner... */
    uint64_t retval = 0;
    uint8_t pos = 0, bits = DISTANCE_INDEX_DISTANCE_BITS;
    while (bits > 8) {
        uint8_t distance = abs((int8_t)id_ref[pos] ^ (int8_t)id_test[pos]);
        retval = (retval << 8) | distance;
        bits -= 8;
        pos++;
    }
    return (retval << bits) | ((id_ref[pos] ^ id_test[pos]) >> (8 - bits));
}
static hash_t id_hash (const Assoc * assoc, const uint8_t * id) [static]
Definition at line 199 of file assoc.c.
References Assoc::candidates_bucket_size, and i.
Referenced by Assoc_add_entry(), and client_id_self_update().
{
    uint32_t i, res = 0x19a64e82;
    for (i = 0; i < crypto_box_PUBLICKEYBYTES; i++)
        res = ((res << 1) ^ id[i]) + (res >> 31);
    /* can't have zero as hash, a) marks an unused spot,
     * b) collision function is multiplicative */
    if (!(res % assoc->candidates_bucket_size))
        res++;
    return res;
}
void kill_Assoc (Assoc * assoc)
Definition at line 968 of file assoc.c.
References Assoc::candidates, and candidates_bucket::list.
Referenced by kill_DHT(), and START_TEST().
{
    if (assoc) {
        free(assoc->candidates->list);
        free(assoc->candidates);
        free(assoc);
    }
}
Assoc* new_Assoc (size_t bits, size_t entries, const uint8_t * public_id)
Definition at line 779 of file assoc.c.
References Assoc::candidates, Assoc::candidates_bucket_bits, Assoc::candidates_bucket_count, Assoc::candidates_bucket_size, client_id_self_update(), Assoc::getnodes, Client_entry::hash, HASH_COLLIDE_PRIME, id_copy(), candidates_bucket::list, LOGGER_DEBUG, prime_upto_min9(), Assoc::self_client_id, and unix_time().
Referenced by new_Assoc_default(), and START_TEST().
{
    if (!public_id)
        return NULL;
    Assoc *assoc = calloc(1, sizeof(*assoc));
    if (!assoc)
        return NULL;
    /*
     * bits must be in [ 2 .. 15 ]
     * entries must be a prime
     */
    if (bits < 2)
        bits = 2;
    else if (bits > 15)
        bits = 15;
    assoc->candidates_bucket_bits = bits;
    assoc->candidates_bucket_count = 1U << bits;
    if (entries < 25) {
        if (entries <= 6)
            entries = 5;
        else {
            entries = entries - (1 - (entries % 2)); /* even => odd */
            /* 7..23: all odds but 9&15 are prime */
            if (!(entries % 3)) /* 9, 15 */
                entries -= 2; /* 7, 13 */
        }
    } else if (entries > ((1 << 17) - 1)) /* 130k+ */
        entries = (1 << 17) - 1;
    else {
        /* 9+: test and find a prime less or equal */
        size_t entries_test = prime_upto_min9(entries);
        if (entries_test == HASH_COLLIDE_PRIME) /* disallowed */
            entries_test = prime_upto_min9(entries_test - 1);
        if (entries_test != entries) {
            LOGGER_DEBUG("trimmed %i to %i.\n", (int)entries, (int)entries_test);
            entries = (size_t)entries_test;
        }
    }
    assoc->candidates_bucket_size = entries;
    /* allocation: preferably few blobs */
    size_t bckt, cix;
    Client_entry *clients = malloc(sizeof(*clients) * assoc->
      candidates_bucket_count * assoc->candidates_bucket_size);
    if (!clients) {
        free(assoc);
        return NULL;
    }
    candidates_bucket *lists = malloc(sizeof(*lists) * assoc->
      candidates_bucket_count);
    if (!lists) {
        free(assoc);
        free(clients);
        return NULL;
    }
    for (bckt = 0; bckt < assoc->candidates_bucket_count; bckt++) {
        candidates_bucket *list = &lists[bckt];
        list->list = &clients[bckt * assoc->candidates_bucket_size];
        for (cix = 0; cix < assoc->candidates_bucket_size; cix++)
            list->list[cix].hash = 0;
    }
    assoc->candidates = lists;
    assoc->getnodes = unix_time();
    id_copy(assoc->self_client_id, public_id);
    client_id_self_update(assoc);
    return assoc;
}
Assoc* new_Assoc_default (const uint8_t * public_id)
Definition at line 864 of file assoc.c.
References new_Assoc().
Referenced by new_DHT(), and START_TEST().
{
    /* original 8, 251 averages to ~32k entries... probably the whole DHT :D
     * 320 entries is fine, hopefully */
    return new_Assoc(6, 15, public_id);
}
static uint8_t odd_min9_is_prime (size_t value) [static]
Definition at line 753 of file assoc.c.
References i.
Referenced by prime_upto_min9().
{
    size_t i = 3;
    while (i * i <= value) {
        if (!(value % i))
            return 0;
        i += 2;
    }
    return 1;
}
static size_t prime_upto_min9 (size_t limit) [static]
Definition at line 767 of file assoc.c.
References odd_min9_is_prime().
Referenced by new_Assoc().
{
    /* even => odd */
    limit = limit - (1 - (limit % 2));
    while (!odd_min9_is_prime(limit))
        limit -= 2;
    return limit;
}