auto_tests/TCP_test.c File Reference
#include <sys/types.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <check.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include `../toxcore/TCP_server.h`
*
#include `../toxcore/TCP_client.h`
*
#include `../toxcore/util.h`
*
#include `helpers.h`
*
#include <unistd.h>
*
#include `../toxcore/TCP_connection.h`
*
Data Structures
struct sec_TCP_con
Macros
#define c_sleep(x) usleep(1000*x)
#define NUM_PORTS 3
Functions
START_TEST (test_basic)
struct sec_TCP_con * new_TCP_con (TCP_Server *tcp_s)
void kill_TCP_con (struct sec_TCP_con *con)
int write_packet_TCP_secure_connection (struct sec_TCP_con *con, uint8_t *data, uint16_t length)
int read_packet_sec_TCP (struct sec_TCP_con *con, uint8_t *data, uint16_t length)
START_TEST (test_some)
static int response_callback (void *object, uint8_t connection_id, const uint8_t *public_key)
static int status_callback (void *object, uint32_t number, uint8_t connection_id, uint8_t status)
static int data_callback (void *object, uint32_t number, uint8_t connection_id, const uint8_t *data, uint16_t length)
static int oob_data_callback (void *object, const uint8_t *public_key, const uint8_t *data, uint16_t length)
START_TEST (test_client)
END_TEST START_TEST (test_client_invalid)
static int tcp_data_callback (void *object, int id, const uint8_t *data, uint16_t length)
START_TEST (test_tcp_connection)
static int tcp_oobdata_callback (void *object, const uint8_t *public_key, unsigned int id, const uint8_t *data, uint16_t length)
START_TEST (test_tcp_connection2)
END_TEST Suite * TCP_suite (void)
int main (int argc, char *argv[])
Variables
uint16_t ports [NUM_PORTS] = {1234, 33445, 25643}
static END_TEST int response_callback_good
static uint8_t response_callback_connection_id
static uint8_t response_callback_public_key [crypto_box_PUBLICKEYBYTES]
static int status_callback_good
static uint8_t status_callback_connection_id
static uint8_t status_callback_status
static int data_callback_good
static int oob_data_callback_good
static uint8_t oob_pubkey [crypto_box_PUBLICKEYBYTES]
END_TEST _Bool tcp_data_callback_called
END_TEST _Bool tcp_oobdata_callback_called
Macro Definition Documentation
#define c_sleep(x) usleep(1000*x)
Definition at line 23 of file TCP_test.c.
Referenced by new_TCP_con(), and START_TEST().
#define NUM_PORTS 3
Definition at line 26 of file TCP_test.c.
Referenced by new_TCP_con(), and START_TEST().
Function Documentation
static int data_callback (void * object, uint32_t number, uint8_t connection_id, const uint8_t * data, uint16_t length) [static]
Definition at line 337 of file TCP_test.c.
References data_callback_good.
Referenced by friend_connection_callbacks(), routing_data_handler(), and START_TEST().
{
    if (object != (void *)3)
        return 1;
    if (number != 7)
        return 1;
    if (length != 5)
        return 1;
    if (data[0] == 1 && data[1] == 2 && data[2] == 3 && data[3] == 4 &&
      data[4] == 5) {
        data_callback_good++;
        return 0;
    }
    return 1;
}
void kill_TCP_con (struct sec_TCP_con * con)
Definition at line 179 of file TCP_test.c.
References kill_sock(), and sec_TCP_con::sock.
Referenced by START_TEST().
{
    kill_sock(con->sock);
    free(con);
}
int main (int argc, char * argv[])
Definition at line 728 of file TCP_test.c.
References TCP_suite().
{
    srand((unsigned int) time(NULL));
    Suite *TCP = TCP_suite();
    SRunner *test_runner = srunner_create(TCP);
    int number_failed = 0;
    srunner_run_all(test_runner, CK_NORMAL);
    number_failed = srunner_ntests_failed(test_runner);
    srunner_free(test_runner);
    return number_failed;
}
struct sec_TCP_con* new_TCP_con (TCP_Server * tcp_s)
Definition at line 133 of file TCP_test.c.
References c_sleep, ck_assert_msg(), decrypt_data(), do_TCP_server(), encrypt_data(), encrypt_precompute(), new_nonce(), NUM_PORTS, ports, sec_TCP_con::public_key, TCP_Server::public_key, random_nonce(), sec_TCP_con::recv_nonce, sec_TCP_con::sent_nonce, sec_TCP_con::shared_key, sock, sec_TCP_con::sock, TCP_CLIENT_HANDSHAKE_SIZE, TCP_HANDSHAKE_PLAIN_SIZE, and TCP_SERVER_HANDSHAKE_SIZE.
Referenced by START_TEST().
{
    struct sec_TCP_con *sec_c = malloc(sizeof(struct sec_TCP_con));
    sock_t sock = socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP);
    struct sockaddr_in6 addr6_loopback = {0};
    addr6_loopback.sin6_family = AF_INET6;
    addr6_loopback.sin6_port = htons(ports[rand() % NUM_PORTS]);
    addr6_loopback.sin6_addr = in6addr_loopback;
    int ret = connect(sock, (struct sockaddr *)&addr6_loopback, sizeof(addr6_loopback));
    ck_assert_msg(ret == 0, "Failed to connect to TCP relay server");
    uint8_t f_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(sec_c->public_key, f_secret_key);
    random_nonce(sec_c->sent_nonce);
    uint8_t t_secret_key[crypto_box_SECRETKEYBYTES];
    uint8_t handshake_plain[TCP_HANDSHAKE_PLAIN_SIZE];
    crypto_box_keypair(handshake_plain, t_secret_key);
    memcpy(handshake_plain + crypto_box_PUBLICKEYBYTES, sec_c->sent_nonce, crypto_box_NONCEBYTES)
      ;
    uint8_t handshake[TCP_CLIENT_HANDSHAKE_SIZE];
    memcpy(handshake, sec_c->public_key, crypto_box_PUBLICKEYBYTES);
    new_nonce(handshake + crypto_box_PUBLICKEYBYTES);
    ret = encrypt_data(tcp_s->public_key, f_secret_key, handshake +
      crypto_box_PUBLICKEYBYTES, handshake_plain,
                       TCP_HANDSHAKE_PLAIN_SIZE, handshake +
      crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    ck_assert_msg(ret == TCP_CLIENT_HANDSHAKE_SIZE - (
      crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES),
                  "Encrypt failed.");
    ck_assert_msg(send(sock, handshake, TCP_CLIENT_HANDSHAKE_SIZE - 1
      , 0) == TCP_CLIENT_HANDSHAKE_SIZE - 1, "send Failed.");
    do_TCP_server(tcp_s);
    c_sleep(50);
    ck_assert_msg(send(sock, handshake + (TCP_CLIENT_HANDSHAKE_SIZE -
       1), 1, 0) == 1, "send Failed.");
    c_sleep(50);
    do_TCP_server(tcp_s);
    uint8_t response[TCP_SERVER_HANDSHAKE_SIZE];
    uint8_t response_plain[TCP_HANDSHAKE_PLAIN_SIZE];
    ck_assert_msg(recv(sock, response, TCP_SERVER_HANDSHAKE_SIZE, 0)
      == TCP_SERVER_HANDSHAKE_SIZE, "recv Failed.");
    ret = decrypt_data(tcp_s->public_key, f_secret_key, response, response +
      crypto_box_NONCEBYTES,
                       TCP_SERVER_HANDSHAKE_SIZE - crypto_box_NONCEBYTES,
      response_plain);
    ck_assert_msg(ret == TCP_HANDSHAKE_PLAIN_SIZE, "Decrypt Failed.");
    encrypt_precompute(response_plain, t_secret_key, sec_c->
      shared_key);
    memcpy(sec_c->recv_nonce, response_plain + crypto_box_BEFORENMBYTES, crypto_box_NONCEBYTES);
    sec_c->sock = sock;
    return sec_c;
}
static int oob_data_callback (void * object, const uint8_t * public_key, const uint8_t * data, uint16_t length) [static]
Definition at line 358 of file TCP_test.c.
References oob_data_callback_good, and oob_pubkey.
Referenced by oob_data_handler(), and START_TEST().
{
    if (object != (void *)4)
        return 1;
    if (length != 5)
        return 1;
    if (memcmp(public_key, oob_pubkey, crypto_box_PUBLICKEYBYTES) != 0)
        return 1;
    if (data[0] == 1 && data[1] == 2 && data[2] == 3 && data[3] == 4 &&
      data[4] == 5) {
        oob_data_callback_good++;
        return 0;
    }
    return 1;
}
int read_packet_sec_TCP (struct sec_TCP_con * con, uint8_t * data, uint16_t length)
Definition at line 202 of file TCP_test.c.
References ck_assert_msg(), decrypt_data_symmetric(), increment_nonce(), sec_TCP_con::recv_nonce, sec_TCP_con::shared_key, and sec_TCP_con::sock.
Referenced by START_TEST().
{
    int len;
    ck_assert_msg((len = recv(con->sock, data, length, 0)) == length, "wrong len %i\n"
      , len);
    ck_assert_msg((len = decrypt_data_symmetric(con->
      shared_key, con->recv_nonce, data + 2, length - 2, data)) != -1,
                  "Decrypt failed");
    increment_nonce(con->recv_nonce);
    return len;
}
static int response_callback (void * object, uint8_t connection_id, const uint8_t * public_key) [static]
Definition at line 310 of file TCP_test.c.
References response_callback_connection_id, response_callback_good, response_callback_public_key, and set_tcp_connection_number().
Referenced by routing_response_handler(), and START_TEST().
{
    if (set_tcp_connection_number(object - 2, connection_id, 7) != 0)
        return 1;
    response_callback_connection_id = connection_id;
    memcpy(response_callback_public_key, public_key,
      crypto_box_PUBLICKEYBYTES);
    response_callback_good++;
    return 0;
}
START_TEST (test_basic)
Definition at line 30 of file TCP_test.c.
References c_sleep, ck_assert_msg(), decrypt_data(), decrypt_data_symmetric(), do_TCP_server(), encrypt_data(), encrypt_data_symmetric(), encrypt_precompute(), i, increment_nonce(), kill_TCP_server(), new_nonce(), new_TCP_server(), TCP_Server::num_listening_socks, NUM_PORTS, ports, random_nonce(), sock, TCP_CLIENT_HANDSHAKE_SIZE, TCP_HANDSHAKE_PLAIN_SIZE, and TCP_SERVER_HANDSHAKE_SIZE.
{
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Server *tcp_s = new_TCP_server(1, NUM_PORTS,
      ports, self_secret_key, NULL);
    ck_assert_msg(tcp_s != NULL, "Failed to create TCP relay server");
    ck_assert_msg(tcp_s->num_listening_socks ==
      NUM_PORTS, "Failed to bind to all ports");
    sock_t sock = socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP);
    struct sockaddr_in6 addr6_loopback = {0};
    addr6_loopback.sin6_family = AF_INET6;
    addr6_loopback.sin6_port = htons(ports[rand() % NUM_PORTS]);
    addr6_loopback.sin6_addr = in6addr_loopback;
    int ret = connect(sock, (struct sockaddr *)&addr6_loopback, sizeof(addr6_loopback));
    ck_assert_msg(ret == 0, "Failed to connect to TCP relay server");
    uint8_t f_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t f_secret_key[crypto_box_SECRETKEYBYTES];
    uint8_t f_nonce[crypto_box_NONCEBYTES];
    crypto_box_keypair(f_public_key, f_secret_key);
    random_nonce(f_nonce);
    uint8_t t_secret_key[crypto_box_SECRETKEYBYTES];
    uint8_t handshake_plain[TCP_HANDSHAKE_PLAIN_SIZE];
    crypto_box_keypair(handshake_plain, t_secret_key);
    memcpy(handshake_plain + crypto_box_PUBLICKEYBYTES, f_nonce, crypto_box_NONCEBYTES);
    uint8_t handshake[TCP_CLIENT_HANDSHAKE_SIZE];
    memcpy(handshake, f_public_key, crypto_box_PUBLICKEYBYTES);
    new_nonce(handshake + crypto_box_PUBLICKEYBYTES);
    ret = encrypt_data(self_public_key, f_secret_key, handshake + crypto_box_PUBLICKEYBYTES,
      handshake_plain,
                       TCP_HANDSHAKE_PLAIN_SIZE, handshake +
      crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    ck_assert_msg(ret == TCP_CLIENT_HANDSHAKE_SIZE - (
      crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES),
                  "Encrypt failed.");
    ck_assert_msg(send(sock, handshake, TCP_CLIENT_HANDSHAKE_SIZE - 1
      , 0) == TCP_CLIENT_HANDSHAKE_SIZE - 1, "send Failed.");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    ck_assert_msg(send(sock, handshake + (TCP_CLIENT_HANDSHAKE_SIZE -
       1), 1, 0) == 1, "send Failed.");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    uint8_t response[TCP_SERVER_HANDSHAKE_SIZE];
    uint8_t response_plain[TCP_HANDSHAKE_PLAIN_SIZE];
    ck_assert_msg(recv(sock, response, TCP_SERVER_HANDSHAKE_SIZE, 0)
      == TCP_SERVER_HANDSHAKE_SIZE, "recv Failed.");
    ret = decrypt_data(self_public_key, f_secret_key, response, response +
      crypto_box_NONCEBYTES,
                       TCP_SERVER_HANDSHAKE_SIZE - crypto_box_NONCEBYTES,
      response_plain);
    ck_assert_msg(ret == TCP_HANDSHAKE_PLAIN_SIZE, "Decrypt Failed.");
    uint8_t f_nonce_r[crypto_box_NONCEBYTES];
    uint8_t f_shared_key[crypto_box_BEFORENMBYTES];
    encrypt_precompute(response_plain, t_secret_key, f_shared_key);
    memcpy(f_nonce_r, response_plain + crypto_box_BEFORENMBYTES, crypto_box_NONCEBYTES);
    uint8_t r_req_p[1 + crypto_box_PUBLICKEYBYTES] = {0};
    memcpy(r_req_p + 1, f_public_key, crypto_box_PUBLICKEYBYTES);
    uint8_t r_req[2 + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES];
    uint16_t size = 1 + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES;
    size = htons(size);
    ret = encrypt_data_symmetric(f_shared_key, f_nonce, r_req_p, 1 +
      crypto_box_PUBLICKEYBYTES, r_req + 2);
    increment_nonce(f_nonce);
    memcpy(r_req, &size, 2);
    uint32_t i;
    for (i = 0; i < sizeof(r_req); ++i) {
        ck_assert_msg(send(sock, r_req + i, 1, 0) == 1, "send Failed.");
        //ck_assert_msg(send(sock, r_req, sizeof(r_req), 0) == sizeof(r_req), "send Failed.");
        do_TCP_server(tcp_s);
        c_sleep(50);
    }
    do_TCP_server(tcp_s);
    c_sleep(50);
    uint8_t packet_resp[4096];
    int recv_data_len;
    ck_assert_msg((recv_data_len = recv(sock, packet_resp, 2 + 2 + crypto_box_PUBLICKEYBYTES +
       crypto_box_MACBYTES,
                                        0)) == 2 + 2 + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES, "
      recv Failed. %u", recv_data_len);
    memcpy(&size, packet_resp, 2);
    ck_assert_msg(ntohs(size) == 2 + crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES, "Wrong
       packet size.");
    uint8_t packet_resp_plain[4096];
    ret = decrypt_data_symmetric(f_shared_key, f_nonce_r, packet_resp + 2,
      recv_data_len - 2, packet_resp_plain);
    ck_assert_msg(ret != -1, "decryption failed");
    increment_nonce(f_nonce_r);
    ck_assert_msg(packet_resp_plain[0] == 1, "wrong packet id %u", packet_resp_plain[0]);
    ck_assert_msg(packet_resp_plain[1] == 0, "connection not refused %u", packet_resp_plain[1]
      );
    ck_assert_msg(memcmp(packet_resp_plain + 2, f_public_key, crypto_box_PUBLICKEYBYTES) == 0,
       "key in packet wrong");
    kill_TCP_server(tcp_s);
}
START_TEST (test_some)
Definition at line 212 of file TCP_test.c.
References c_sleep, ck_assert_msg(), make-funny-savefile::data, do_TCP_server(), kill_TCP_con(), kill_TCP_server(), new_TCP_con(), new_TCP_server(), TCP_Server::num_listening_socks, NUM_PORTS, ports, sec_TCP_con::public_key, read_packet_sec_TCP(), and write_packet_TCP_secure_connection().
{
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Server *tcp_s = new_TCP_server(1, NUM_PORTS,
      ports, self_secret_key, NULL);
    ck_assert_msg(tcp_s != NULL, "Failed to create TCP relay server");
    ck_assert_msg(tcp_s->num_listening_socks ==
      NUM_PORTS, "Failed to bind to all ports");
    struct sec_TCP_con *con1 = new_TCP_con(tcp_s);
    struct sec_TCP_con *con2 = new_TCP_con(tcp_s);
    struct sec_TCP_con *con3 = new_TCP_con(tcp_s);
    uint8_t requ_p[1 + crypto_box_PUBLICKEYBYTES];
    requ_p[0] = 0;
    memcpy(requ_p + 1, con3->public_key, crypto_box_PUBLICKEYBYTES);
    write_packet_TCP_secure_connection(con1, requ_p, sizeof(requ_p));
    memcpy(requ_p + 1, con1->public_key, crypto_box_PUBLICKEYBYTES);
    write_packet_TCP_secure_connection(con3, requ_p, sizeof(requ_p));
    do_TCP_server(tcp_s);
    c_sleep(50);
    uint8_t data[2048];
    int len = read_packet_sec_TCP(con1, data, 2 + 1 + 1 + crypto_box_PUBLICKEYBYTES +
      crypto_box_MACBYTES);
    ck_assert_msg(len == 1 + 1 + crypto_box_PUBLICKEYBYTES, "wrong len %u", len);
    ck_assert_msg(data[0] == 1, "wrong packet id %u", data[0]);
    ck_assert_msg(data[1] == 16, "connection not refused %u", data[1]);
    ck_assert_msg(memcmp(data + 2, con3->public_key, crypto_box_PUBLICKEYBYTES) == 0
      , "key in packet wrong");
    len = read_packet_sec_TCP(con3, data, 2 + 1 + 1 + crypto_box_PUBLICKEYBYTES +
      crypto_box_MACBYTES);
    ck_assert_msg(len == 1 + 1 + crypto_box_PUBLICKEYBYTES, "wrong len %u", len);
    ck_assert_msg(data[0] == 1, "wrong packet id %u", data[0]);
    ck_assert_msg(data[1] == 16, "connection not refused %u", data[1]);
    ck_assert_msg(memcmp(data + 2, con1->public_key, crypto_box_PUBLICKEYBYTES) == 0
      , "key in packet wrong");
    uint8_t test_packet[512] = {16, 17, 16, 86, 99, 127, 255, 189, 78};
    write_packet_TCP_secure_connection(con3, test_packet, sizeof(
      test_packet));
    write_packet_TCP_secure_connection(con3, test_packet, sizeof(
      test_packet));
    write_packet_TCP_secure_connection(con3, test_packet, sizeof(
      test_packet));
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    len = read_packet_sec_TCP(con1, data, 2 + 2 + crypto_box_MACBYTES);
    ck_assert_msg(len == 2, "wrong len %u", len);
    ck_assert_msg(data[0] == 2, "wrong packet id %u", data[0]);
    ck_assert_msg(data[1] == 16, "wrong peer id %u", data[1]);
    len = read_packet_sec_TCP(con3, data, 2 + 2 + crypto_box_MACBYTES);
    ck_assert_msg(len == 2, "wrong len %u", len);
    ck_assert_msg(data[0] == 2, "wrong packet id %u", data[0]);
    ck_assert_msg(data[1] == 16, "wrong peer id %u", data[1]);
    len = read_packet_sec_TCP(con1, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    len = read_packet_sec_TCP(con1, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    len = read_packet_sec_TCP(con1, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    write_packet_TCP_secure_connection(con1, test_packet, sizeof(
      test_packet));
    write_packet_TCP_secure_connection(con1, test_packet, sizeof(
      test_packet));
    write_packet_TCP_secure_connection(con1, test_packet, sizeof(
      test_packet));
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    len = read_packet_sec_TCP(con3, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    len = read_packet_sec_TCP(con3, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    len = read_packet_sec_TCP(con3, data, 2 + sizeof(test_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(test_packet), "wrong len %u", len);
    ck_assert_msg(memcmp(data, test_packet, sizeof(test_packet)) == 0, "packet is wrong %u %u
       %u %u", data[0], data[1],
                  data[sizeof(test_packet) - 2], data[sizeof(test_packet) - 1]);
    uint8_t ping_packet[1 + sizeof(uint64_t)] = {4, 8, 6, 9, 67};
    write_packet_TCP_secure_connection(con1, ping_packet, sizeof(
      ping_packet));
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    len = read_packet_sec_TCP(con1, data, 2 + sizeof(ping_packet) + crypto_box_MACBYTES)
      ;
    ck_assert_msg(len == sizeof(ping_packet), "wrong len %u", len);
    ck_assert_msg(data[0] == 5, "wrong packet id %u", data[0]);
    ck_assert_msg(memcmp(ping_packet + 1, data + 1, sizeof(uint64_t)) == 0, "wrong packet data
      ");
    kill_TCP_server(tcp_s);
    kill_TCP_con(con1);
    kill_TCP_con(con2);
    kill_TCP_con(con3);
}
START_TEST (test_client)
Definition at line 377 of file TCP_test.c.
References c_sleep, ck_assert_msg(), make-funny-savefile::data, data_callback(), data_callback_good, do_TCP_connection(), do_TCP_server(), IP::family, IP6::in6_addr, IP_Port::ip, IP::ip6, kill_TCP_connection(), kill_TCP_server(), new_TCP_connection(), new_TCP_server(), TCP_Server::num_listening_socks, NUM_PORTS, oob_data_callback(), oob_data_callback_good, oob_data_handler(), oob_pubkey, IP_Port::port, ports, response_callback(), response_callback_connection_id, response_callback_good, response_callback_public_key, routing_data_handler(), routing_response_handler(), routing_status_handler(), send_data(), send_disconnect_request(), send_oob_packet(), send_routing_request(), TCP_Client_Connection::status, status_callback(), status_callback_connection_id, status_callback_good, status_callback_status, TCP_CLIENT_CONFIRMED, TCP_CLIENT_UNCONFIRMED, and unix_time_update().
{
    unix_time_update();
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Server *tcp_s = new_TCP_server(1, NUM_PORTS,
      ports, self_secret_key, NULL);
    ck_assert_msg(tcp_s != NULL, "Failed to create TCP relay server");
    ck_assert_msg(tcp_s->num_listening_socks ==
      NUM_PORTS, "Failed to bind to all ports");
    uint8_t f_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t f_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(f_public_key, f_secret_key);
    IP_Port ip_port_tcp_s;
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    ip_port_tcp_s.ip.family = AF_INET6;
    ip_port_tcp_s.ip.ip6.in6_addr = in6addr_loopback;
    TCP_Client_Connection *conn = new_TCP_connection(ip_port_tcp_s,
      self_public_key, f_public_key, f_secret_key, 0);
    c_sleep(50);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_UNCONFIRMED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_UNCONFIRMED,
                  conn->status);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_CONFIRMED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONFIRMED,
                  conn->status);
    c_sleep(500);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_CONFIRMED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONFIRMED,
                  conn->status);
    c_sleep(500);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_CONFIRMED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONFIRMED,
                  conn->status);
    do_TCP_server(tcp_s);
    c_sleep(50);
    ck_assert_msg(conn->status == TCP_CLIENT_CONFIRMED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONFIRMED,
                  conn->status);
    uint8_t f2_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t f2_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(f2_public_key, f2_secret_key);
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    TCP_Client_Connection *conn2 = new_TCP_connection(ip_port_tcp_s,
       self_public_key, f2_public_key, f2_secret_key, 0);
    routing_response_handler(conn, response_callback, ((void *)
      conn) + 2);
    routing_status_handler(conn, status_callback, (void *)2);
    routing_data_handler(conn, data_callback, (void *)3);
    oob_data_handler(conn, oob_data_callback, (void *)4);
    oob_data_callback_good = response_callback_good =
      status_callback_good = data_callback_good = 0;
    c_sleep(50);
    do_TCP_connection(conn);
    do_TCP_connection(conn2);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_connection(conn);
    do_TCP_connection(conn2);
    c_sleep(50);
    uint8_t data[5] = {1, 2, 3, 4, 5};
    memcpy(oob_pubkey, f2_public_key, crypto_box_PUBLICKEYBYTES);
    send_oob_packet(conn2, f_public_key, data, 5);
    send_routing_request(conn, f2_public_key);
    send_routing_request(conn2, f_public_key);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_connection(conn);
    do_TCP_connection(conn2);
    ck_assert_msg(oob_data_callback_good == 1, "oob callback not called"
      );
    ck_assert_msg(response_callback_good == 1, "response callback not
       called");
    ck_assert_msg(memcmp(response_callback_public_key,
      f2_public_key, crypto_box_PUBLICKEYBYTES) == 0, "wrong public key");
    ck_assert_msg(status_callback_good == 1, "status callback not called")
      ;
    ck_assert_msg(status_callback_status == 2, "wrong status");
    ck_assert_msg(status_callback_connection_id ==
      response_callback_connection_id, "connection ids not equal");
    c_sleep(50);
    do_TCP_server(tcp_s);
    ck_assert_msg(send_data(conn2, 0, data, 5) == 1, "send data failed");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_connection(conn);
    do_TCP_connection(conn2);
    ck_assert_msg(data_callback_good == 1, "data callback not called");
    status_callback_good = 0;
    send_disconnect_request(conn2, 0);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_TCP_connection(conn);
    do_TCP_connection(conn2);
    ck_assert_msg(status_callback_good == 1, "status callback not called")
      ;
    ck_assert_msg(status_callback_status == 1, "wrong status");
    kill_TCP_server(tcp_s);
    kill_TCP_connection(conn);
    kill_TCP_connection(conn2);
}
END_TEST START_TEST (test_client_invalid)
Definition at line 478 of file TCP_test.c.
References c_sleep, ck_assert_msg(), do_TCP_connection(), IP::family, IP6::in6_addr, IP_Port::ip, IP::ip6, kill_TCP_connection(), new_TCP_connection(), NUM_PORTS, IP_Port::port, ports, TCP_Client_Connection::status, TCP_CLIENT_CONNECTING, TCP_CLIENT_DISCONNECTED, and unix_time_update().
{
    unix_time_update();
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    uint8_t f_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t f_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(f_public_key, f_secret_key);
    IP_Port ip_port_tcp_s;
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    ip_port_tcp_s.ip.family = AF_INET6;
    ip_port_tcp_s.ip.ip6.in6_addr = in6addr_loopback;
    TCP_Client_Connection *conn = new_TCP_connection(ip_port_tcp_s,
      self_public_key, f_public_key, f_secret_key, 0);
    c_sleep(50);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_CONNECTING, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONNECTING,
                  conn->status);
    c_sleep(5000);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_CONNECTING, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_CONNECTING,
                  conn->status);
    c_sleep(6000);
    do_TCP_connection(conn);
    ck_assert_msg(conn->status == TCP_CLIENT_DISCONNECTED, "Wrong
       status. Expected: %u, is: %u", TCP_CLIENT_DISCONNECTED,
                  conn->status);
    kill_TCP_connection(conn);
}
START_TEST (test_tcp_connection)
Definition at line 533 of file TCP_test.c.
References add_tcp_relay_connection(), c_sleep, ck_assert_msg(), do_tcp_connections(), do_TCP_server(), IP::family, IP6::in6_addr, IP_Port::ip, IP::ip6, kill_tcp_connection_to(), kill_tcp_connections(), kill_TCP_server(), new_tcp_connection_to(), new_tcp_connections(), new_TCP_server(), NUM_PORTS, IP_Port::port, ports, TCP_Proxy_Info::proxy_type, TCP_Server::public_key, TCP_Connections::self_public_key, send_packet_tcp_connection(), set_packet_tcp_connection_callback(), tcp_connection_to_online_tcp_relays(), tcp_data_callback(), tcp_data_callback_called, TCP_PROXY_NONE, and unix_time_update().
{
    tcp_data_callback_called = 0;
    unix_time_update();
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Server *tcp_s = new_TCP_server(1, NUM_PORTS,
      ports, self_secret_key, NULL);
    ck_assert_msg(memcmp(tcp_s->public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    TCP_Proxy_Info proxy_info;
    proxy_info.proxy_type = TCP_PROXY_NONE;
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Connections *tc_1 = new_tcp_connections(self_secret_key, &
      proxy_info);
    ck_assert_msg(memcmp(tc_1->self_public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Connections *tc_2 = new_tcp_connections(self_secret_key, &
      proxy_info);
    ck_assert_msg(memcmp(tc_2->self_public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    IP_Port ip_port_tcp_s;
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    ip_port_tcp_s.ip.family = AF_INET6;
    ip_port_tcp_s.ip.ip6.in6_addr = in6addr_loopback;
    int connection = new_tcp_connection_to(tc_1, tc_2->
      self_public_key, 123);
    ck_assert_msg(connection == 0, "Connection id wrong");
    ck_assert_msg(add_tcp_relay_connection(tc_1, connection,
      ip_port_tcp_s, tcp_s->public_key) == 0,
                  "Could not add tcp relay to connection\n");
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    connection = new_tcp_connection_to(tc_2, tc_1->
      self_public_key, 123);
    ck_assert_msg(connection == 0, "Connection id wrong");
    ck_assert_msg(add_tcp_relay_connection(tc_2, connection,
      ip_port_tcp_s, tcp_s->public_key) == 0,
                  "Could not add tcp relay to connection\n");
    ck_assert_msg(new_tcp_connection_to(tc_2, tc_1->
      self_public_key, 123) == -1, "Managed to readd same connection\n");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    int ret = send_packet_tcp_connection(tc_1, 0, "Gentoo", 6);
    ck_assert_msg(ret == 0, "could not send packet.");
    set_packet_tcp_connection_callback(tc_2, &
      tcp_data_callback, (void *) 120397);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    ck_assert_msg(tcp_data_callback_called, "could not recv packet.");
    ck_assert_msg(tcp_connection_to_online_tcp_relays(tc_1,
       0) == 1, "Wrong number of connected relays");
    ck_assert_msg(kill_tcp_connection_to(tc_1, 0) == 0, "could not kill
       connection to\n");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    ck_assert_msg(send_packet_tcp_connection(tc_1, 0, "Gentoo", 6)
      == -1, "could send packet.");
    ck_assert_msg(kill_tcp_connection_to(tc_2, 0) == 0, "could not kill
       connection to\n");
    kill_TCP_server(tcp_s);
    kill_tcp_connections(tc_1);
    kill_tcp_connections(tc_2);
}
START_TEST (test_tcp_connection2)
Definition at line 634 of file TCP_test.c.
References add_tcp_relay_connection(), add_tcp_relay_global(), c_sleep, ck_assert_msg(), do_tcp_connections(), do_TCP_server(), IP::family, IP6::in6_addr, IP_Port::ip, IP::ip6, kill_tcp_connection_to(), kill_tcp_connections(), kill_TCP_server(), new_tcp_connection_to(), new_tcp_connections(), new_TCP_server(), NUM_PORTS, IP_Port::port, ports, TCP_Proxy_Info::proxy_type, TCP_Server::public_key, TCP_Connections::self_public_key, send_packet_tcp_connection(), set_oob_packet_tcp_connection_callback(), set_packet_tcp_connection_callback(), tcp_data_callback(), tcp_data_callback_called, tcp_oobdata_callback(), tcp_oobdata_callback_called, TCP_PROXY_NONE, and unix_time_update().
{
    tcp_oobdata_callback_called = 0;
    tcp_data_callback_called = 0;
    unix_time_update();
    uint8_t self_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t self_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Server *tcp_s = new_TCP_server(1, NUM_PORTS,
      ports, self_secret_key, NULL);
    ck_assert_msg(memcmp(tcp_s->public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    TCP_Proxy_Info proxy_info;
    proxy_info.proxy_type = TCP_PROXY_NONE;
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Connections *tc_1 = new_tcp_connections(self_secret_key, &
      proxy_info);
    ck_assert_msg(memcmp(tc_1->self_public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    crypto_box_keypair(self_public_key, self_secret_key);
    TCP_Connections *tc_2 = new_tcp_connections(self_secret_key, &
      proxy_info);
    ck_assert_msg(memcmp(tc_2->self_public_key, self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0, "Wrong public key");
    IP_Port ip_port_tcp_s;
    ip_port_tcp_s.port = htons(ports[rand() % NUM_PORTS]);
    ip_port_tcp_s.ip.family = AF_INET6;
    ip_port_tcp_s.ip.ip6.in6_addr = in6addr_loopback;
    int connection = new_tcp_connection_to(tc_1, tc_2->
      self_public_key, 123);
    ck_assert_msg(connection == 0, "Connection id wrong");
    ck_assert_msg(add_tcp_relay_connection(tc_1, connection,
      ip_port_tcp_s, tcp_s->public_key) == 0,
                  "Could not add tcp relay to connection\n");
    ck_assert_msg(add_tcp_relay_global(tc_2, ip_port_tcp_s, tcp_s->
      public_key) == 0, "Could not add global relay");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    int ret = send_packet_tcp_connection(tc_1, 0, "Gentoo", 6);
    ck_assert_msg(ret == 0, "could not send packet.");
    set_oob_packet_tcp_connection_callback(tc_2, &
      tcp_oobdata_callback, tc_2);
    set_packet_tcp_connection_callback(tc_1, &
      tcp_data_callback, (void *) 120397);
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    ck_assert_msg(tcp_oobdata_callback_called, "could not recv
       packet.");
    c_sleep(50);
    do_TCP_server(tcp_s);
    c_sleep(50);
    do_tcp_connections(tc_1);
    do_tcp_connections(tc_2);
    ck_assert_msg(tcp_data_callback_called, "could not recv packet.");
    ck_assert_msg(kill_tcp_connection_to(tc_1, 0) == 0, "could not kill
       connection to\n");
    kill_TCP_server(tcp_s);
    kill_tcp_connections(tc_1);
    kill_tcp_connections(tc_2);
}
static int status_callback (void * object, uint32_t number, uint8_t connection_id, uint8_t status) [static]
Definition at line 323 of file TCP_test.c.
References status_callback_connection_id, status_callback_good, and status_callback_status.
Referenced by friend_connection_callbacks(), routing_status_handler(), and START_TEST().
{
    if (object != (void *)2)
        return 1;
    if (number != 7)
        return 1;
    status_callback_connection_id = connection_id;
    status_callback_status = status;
    status_callback_good++;
    return 0;
}
static int tcp_data_callback (void * object, int id, const uint8_t * data, uint16_t length) [static]
Definition at line 514 of file TCP_test.c.
References tcp_data_callback_called.
Referenced by START_TEST().
{
    if (object != (void *)120397)
        return -1;
    if (id != 123)
        return -1;
    if (length != 6)
        return -1;
    if (memcmp(data, "Gentoo", length) != 0)
        return -1;
    tcp_data_callback_called = 1;
    return 0;
}
static int tcp_oobdata_callback (void * object, const uint8_t * public_key, unsigned int id, const uint8_t * data, uint16_t length) [static]
Definition at line 619 of file TCP_test.c.
References tcp_oobdata_callback_called, and tcp_send_oob_packet().
Referenced by START_TEST().
{
    if (length != 6)
        return -1;
    if (memcmp(data, "Gentoo", length) != 0)
        return -1;
    if (tcp_send_oob_packet(object, id, public_key,
      data, length) == 0)
        tcp_oobdata_callback_called = 1;
    return 0;
}
END_TEST Suite* TCP_suite (void)
Definition at line 715 of file TCP_test.c.
References DEFTESTCASE_SLOW.
Referenced by main().
{
    Suite *s = suite_create("TCP");
    DEFTESTCASE_SLOW(basic, 5);
    DEFTESTCASE_SLOW(some, 10);
    DEFTESTCASE_SLOW(client, 10);
    DEFTESTCASE_SLOW(client_invalid, 15);
    DEFTESTCASE_SLOW(tcp_connection, 20);
    DEFTESTCASE_SLOW(tcp_connection2, 20);
    return s;
}
int write_packet_TCP_secure_connection (struct sec_TCP_con * con, uint8_t * data, uint16_t length)
Definition at line 185 of file TCP_test.c.
References ck_assert_msg(), encrypt_data_symmetric(), increment_nonce(), sec_TCP_con::sent_nonce, sec_TCP_con::shared_key, and sec_TCP_con::sock.
Referenced by START_TEST().
{
    uint8_t packet[sizeof(uint16_t) + length + crypto_box_MACBYTES];
    uint16_t c_length = htons(length + crypto_box_MACBYTES);
    memcpy(packet, &c_length, sizeof(uint16_t));
    int len = encrypt_data_symmetric(con->shared_key, con->
      sent_nonce, data, length, packet + sizeof(uint16_t));
    if ((unsigned int)len != (sizeof(packet) - sizeof(uint16_t)))
        return -1;
    increment_nonce(con->sent_nonce);
    ck_assert_msg(send(con->sock, packet, sizeof(packet), 0) == sizeof(packet), "send
       failed");
    return 0;
}
Variable Documentation
int data_callback_good [static]
Definition at line 336 of file TCP_test.c.
Referenced by data_callback(), and START_TEST().
int oob_data_callback_good [static]
Definition at line 356 of file TCP_test.c.
Referenced by oob_data_callback(), and START_TEST().
uint8_t oob_pubkey[crypto_box_PUBLICKEYBYTES] [static]
Definition at line 357 of file TCP_test.c.
Referenced by oob_data_callback(), and START_TEST().
uint16_t ports[NUM_PORTS] = {1234, 33445, 25643}
Definition at line 28 of file TCP_test.c.
Referenced by main(), new_TCP_con(), and START_TEST().
uint8_t response_callback_connection_id [static]
Definition at line 308 of file TCP_test.c.
Referenced by response_callback(), and START_TEST().
END_TEST int response_callback_good [static]
Definition at line 307 of file TCP_test.c.
Referenced by response_callback(), and START_TEST().
uint8_t response_callback_public_key[crypto_box_PUBLICKEYBYTES] [static]
Definition at line 309 of file TCP_test.c.
Referenced by response_callback(), and START_TEST().
uint8_t status_callback_connection_id [static]
Definition at line 321 of file TCP_test.c.
Referenced by START_TEST(), and status_callback().
int status_callback_good [static]
Definition at line 320 of file TCP_test.c.
Referenced by START_TEST(), and status_callback().
uint8_t status_callback_status [static]
Definition at line 322 of file TCP_test.c.
Referenced by START_TEST(), and status_callback().
END_TEST _Bool tcp_data_callback_called
Definition at line 513 of file TCP_test.c.
Referenced by START_TEST(), and tcp_data_callback().
END_TEST _Bool tcp_oobdata_callback_called
Definition at line 618 of file TCP_test.c.
Referenced by START_TEST(), and tcp_oobdata_callback().