toxcore/onion.h File Reference
#include `DHT.h`
*
Data Structures
struct Onion
struct Onion_Path
Macros
#define ONION_MAX_PACKET_SIZE 1400
#define ONION_RETURN_1 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES)
#define ONION_RETURN_2 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES + ONION_RETURN_1)
#define ONION_RETURN_3 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES + ONION_RETURN_2)
#define ONION_SEND_BASE (crypto_box_PUBLICKEYBYTES + SIZE_IPPORT + crypto_box_MACBYTES)
#define ONION_SEND_3 (crypto_box_NONCEBYTES + ONION_SEND_BASE + ONION_RETURN_2)
#define ONION_SEND_2 (crypto_box_NONCEBYTES + ONION_SEND_BASE*2 + ONION_RETURN_1)
#define ONION_SEND_1 (crypto_box_NONCEBYTES + ONION_SEND_BASE*3)
#define ONION_MAX_DATA_SIZE (ONION_MAX_PACKET_SIZE - (ONION_SEND_1 + 1))
#define ONION_RESPONSE_MAX_DATA_SIZE (ONION_MAX_PACKET_SIZE - (1 + ONION_RETURN_3))
#define ONION_PATH_LENGTH 3
Functions
int create_onion_path (const DHT *dht, Onion_Path *new_path, const Node_format *nodes)
int onion_path_to_nodes (Node_format *nodes, unsigned int num_nodes, const Onion_Path *path)
int create_onion_packet (uint8_t *packet, uint16_t max_packet_length, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int create_onion_packet_tcp (uint8_t *packet, uint16_t max_packet_length, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int send_onion_packet (Networking_Core *net, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
int send_onion_response (Networking_Core *net, IP_Port dest, const uint8_t *data, uint16_t length, const uint8_t *ret)
int onion_send_1 (const Onion *onion, const uint8_t *plain, uint16_t len, IP_Port source, const uint8_t *nonce)
void set_callback_handle_recv_1 (Onion *onion, int(*function)(void *, IP_Port, const uint8_t *, uint16_t), void *object)
Onion * new_onion (DHT *dht)
void kill_onion (Onion *onion)
Macro Definition Documentation
#define ONION_MAX_DATA_SIZE (ONION_MAX_PACKET_SIZE - (ONION_SEND_1 + 1))
Definition at line 53 of file onion.h.
Referenced by create_data_request(), and send_data_request().
#define ONION_MAX_PACKET_SIZE 1400
Definition at line 42 of file onion.h.
Referenced by handle_data_request(), handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), handle_send_initial(), onion_send_1(), send_announce_request(), send_data_request(), send_onion_data(), send_onion_packet(), and send_onion_packet_tcp_udp().
#define ONION_PATH_LENGTH 3
Definition at line 56 of file onion.h.
Referenced by is_path_used(), onion_path_to_nodes(), random_path(), and set_path_timeouts().
#define ONION_RESPONSE_MAX_DATA_SIZE (ONION_MAX_PACKET_SIZE - (1 + ONION_RETURN_3))
Definition at line 54 of file onion.h.
Referenced by send_onion_response().
#define ONION_RETURN_1 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES)
Definition at line 44 of file onion.h.
Referenced by onion_send_1().
#define ONION_RETURN_2 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES + ONION_RETURN_1)
Definition at line 45 of file onion.h.
#define ONION_RETURN_3 (crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_MACBYTES + ONION_RETURN_2)
Definition at line 46 of file onion.h.
Referenced by add_to_entries(), handle_announce_request(), and handle_data_request().
#define ONION_SEND_1 (crypto_box_NONCEBYTES + ONION_SEND_BASE*3)
Definition at line 51 of file onion.h.
#define ONION_SEND_2 (crypto_box_NONCEBYTES + ONION_SEND_BASE*2 + ONION_RETURN_1)
Definition at line 50 of file onion.h.
#define ONION_SEND_3 (crypto_box_NONCEBYTES + ONION_SEND_BASE + ONION_RETURN_2)
Definition at line 49 of file onion.h.
#define ONION_SEND_BASE (crypto_box_PUBLICKEYBYTES + SIZE_IPPORT + crypto_box_MACBYTES)
Definition at line 48 of file onion.h.
Referenced by handle_TCP_packet().
Function Documentation
int create_onion_packet (uint8_t * packet, uint16_t max_packet_length, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 173 of file onion.c.
References encrypt_data_symmetric(), Onion_Path::ip_port2, Onion_Path::ip_port3, ipport_pack(), NET_PACKET_ONION_SEND_INITIAL, nonce, Onion_Path::public_key1, Onion_Path::public_key2, Onion_Path::public_key3, random_nonce(), SEND_1, SEND_BASE, Onion_Path::shared_key1, Onion_Path::shared_key2, Onion_Path::shared_key3, and SIZE_IPPORT.
Referenced by send_announce_request(), send_data_request(), send_onion_packet(), and send_onion_packet_tcp_udp().
{
    if (1 + length + SEND_1 > max_packet_length || length == 0)
        return -1;
    uint8_t step1[SIZE_IPPORT + length];
    ipport_pack(step1, &dest);
    memcpy(step1 + SIZE_IPPORT, data, length);
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t step2[SIZE_IPPORT + SEND_BASE + length];
    ipport_pack(step2, &path->ip_port3);
    memcpy(step2 + SIZE_IPPORT, path->public_key3, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(path->shared_key3, nonce, step1,
      sizeof(step1),
                                     step2 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + length + crypto_box_MACBYTES)
        return -1;
    uint8_t step3[SIZE_IPPORT + SEND_BASE * 2 + length];
    ipport_pack(step3, &path->ip_port2);
    memcpy(step3 + SIZE_IPPORT, path->public_key2, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key2, nonce, step2, sizeof(
      step2),
                                 step3 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE + length + crypto_box_MACBYTES)
        return -1;
    packet[0] = NET_PACKET_ONION_SEND_INITIAL;
    memcpy(packet + 1, nonce, crypto_box_NONCEBYTES);
    memcpy(packet + 1 + crypto_box_NONCEBYTES, path->public_key1, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key1, nonce, step3, sizeof(
      step3),
                                 packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE * 2 + length + crypto_box_MACBYTES)
        return -1;
    return 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + len;
}
int create_onion_packet_tcp (uint8_t * packet, uint16_t max_packet_length, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 228 of file onion.c.
References encrypt_data_symmetric(), Onion_Path::ip_port2, Onion_Path::ip_port3, ipport_pack(), nonce, Onion_Path::public_key2, Onion_Path::public_key3, random_nonce(), SEND_BASE, Onion_Path::shared_key2, Onion_Path::shared_key3, and SIZE_IPPORT.
Referenced by send_onion_packet_tcp_udp().
{
    if (crypto_box_NONCEBYTES + SIZE_IPPORT + SEND_BASE * 2 + length >
      max_packet_length || length == 0)
        return -1;
    uint8_t step1[SIZE_IPPORT + length];
    ipport_pack(step1, &dest);
    memcpy(step1 + SIZE_IPPORT, data, length);
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t step2[SIZE_IPPORT + SEND_BASE + length];
    ipport_pack(step2, &path->ip_port3);
    memcpy(step2 + SIZE_IPPORT, path->public_key3, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(path->shared_key3, nonce, step1,
      sizeof(step1),
                                     step2 + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + length + crypto_box_MACBYTES)
        return -1;
    ipport_pack(packet + crypto_box_NONCEBYTES, &path->ip_port2);
    memcpy(packet + crypto_box_NONCEBYTES + SIZE_IPPORT, path->
      public_key2, crypto_box_PUBLICKEYBYTES);
    len = encrypt_data_symmetric(path->shared_key2, nonce, step2, sizeof(
      step2),
                                 packet + crypto_box_NONCEBYTES + SIZE_IPPORT +
      crypto_box_PUBLICKEYBYTES);
    if (len != SIZE_IPPORT + SEND_BASE + length + crypto_box_MACBYTES)
        return -1;
    memcpy(packet, nonce, crypto_box_NONCEBYTES);
    return crypto_box_NONCEBYTES + SIZE_IPPORT + crypto_box_PUBLICKEYBYTES + len;
}
int create_onion_path (const DHT * dht, Onion_Path * new_path, const Node_format * nodes)
Definition at line 114 of file onion.c.
References encrypt_precompute(), Node_format::ip_port, Onion_Path::ip_port1, Onion_Path::ip_port2, Onion_Path::ip_port3, Onion_Path::node_public_key1, Onion_Path::node_public_key2, Onion_Path::node_public_key3, make-funny-savefile::public_key, Node_format::public_key, Onion_Path::public_key1, Onion_Path::public_key2, Onion_Path::public_key3, DHT::self_public_key, DHT::self_secret_key, Onion_Path::shared_key1, Onion_Path::shared_key2, and Onion_Path::shared_key3.
Referenced by random_path(), and START_TEST().
{
    if (!new_path || !nodes)
        return -1;
    encrypt_precompute(nodes[0].public_key, dht->
      self_secret_key, new_path->shared_key1);
    memcpy(new_path->public_key1, dht->self_public_key, crypto_box_PUBLICKEYBYTES
      );
    uint8_t random_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t random_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(random_public_key, random_secret_key);
    encrypt_precompute(nodes[1].public_key, random_secret_key, new_path->
      shared_key2);
    memcpy(new_path->public_key2, random_public_key, crypto_box_PUBLICKEYBYTES);
    crypto_box_keypair(random_public_key, random_secret_key);
    encrypt_precompute(nodes[2].public_key, random_secret_key, new_path->
      shared_key3);
    memcpy(new_path->public_key3, random_public_key, crypto_box_PUBLICKEYBYTES);
    new_path->ip_port1 = nodes[0].ip_port;
    new_path->ip_port2 = nodes[1].ip_port;
    new_path->ip_port3 = nodes[2].ip_port;
    memcpy(new_path->node_public_key1, nodes[0].public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(new_path->node_public_key2, nodes[1].public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(new_path->node_public_key3, nodes[2].public_key,
      crypto_box_PUBLICKEYBYTES);
    return 0;
}
void kill_onion (Onion * onion)
Definition at line 608 of file onion.c.
References Onion::net, NET_PACKET_ONION_RECV_1, NET_PACKET_ONION_RECV_2, NET_PACKET_ONION_RECV_3, NET_PACKET_ONION_SEND_1, NET_PACKET_ONION_SEND_2, NET_PACKET_ONION_SEND_INITIAL, and networking_registerhandler().
Referenced by kill_messenger(), kill_onions(), new_messenger(), and START_TEST().
{
    if (onion == NULL)
        return;
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_INITIAL, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_1, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_2, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_3, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_2, NULL, NULL);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_1, NULL, NULL);
    free(onion);
}
Onion* new_onion (DHT * dht)
Definition at line 582 of file onion.c.
References Onion::dht, handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), handle_send_initial(), Onion::net, DHT::net, NET_PACKET_ONION_RECV_1, NET_PACKET_ONION_RECV_2, NET_PACKET_ONION_RECV_3, NET_PACKET_ONION_SEND_1, NET_PACKET_ONION_SEND_2, NET_PACKET_ONION_SEND_INITIAL, networking_registerhandler(), new_symmetric_key(), Onion::secret_symmetric_key, Onion::timestamp, and unix_time().
Referenced by main(), new_messenger(), new_onions(), and START_TEST().
{
    if (dht == NULL)
        return NULL;
    Onion *onion = calloc(1, sizeof(Onion));
    if (onion == NULL)
        return NULL;
    onion->dht = dht;
    onion->net = dht->net;
    new_symmetric_key(onion->secret_symmetric_key);
    onion->timestamp = unix_time();
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_INITIAL, &handle_send_initial, onion)
      ;
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_1, &handle_send_1, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_SEND_2, &handle_send_2, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_3, &handle_recv_3, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_2, &handle_recv_2, onion);
    networking_registerhandler(onion->net,
      NET_PACKET_ONION_RECV_1, &handle_recv_1, onion);
    return onion;
}
int onion_path_to_nodes (Node_format * nodes, unsigned int num_nodes, const Onion_Path * path)
Definition at line 149 of file onion.c.
References Node_format::ip_port, Onion_Path::ip_port1, Onion_Path::ip_port2, Onion_Path::ip_port3, Onion_Path::node_public_key1, Onion_Path::node_public_key2, Onion_Path::node_public_key3, ONION_PATH_LENGTH, and make-funny-savefile::public_key.
Referenced by set_path_timeouts().
{
    if (num_nodes < ONION_PATH_LENGTH)
        return -1;
    nodes[0].ip_port = path->ip_port1;
    nodes[1].ip_port = path->ip_port2;
    nodes[2].ip_port = path->ip_port3;
    memcpy(nodes[0].public_key, path->node_public_key1, crypto_box_PUBLICKEYBYTES
      );
    memcpy(nodes[1].public_key, path->node_public_key2, crypto_box_PUBLICKEYBYTES
      );
    memcpy(nodes[2].public_key, path->node_public_key3, crypto_box_PUBLICKEYBYTES
      );
    return 0;
}
int onion_send_1 (const Onion * onion, const uint8_t * plain, uint16_t len, IP_Port source, const uint8_t * nonce)
Definition at line 333 of file onion.c.
References make-funny-savefile::data, encrypt_data_symmetric(), ipport_pack(), ipport_unpack(), Onion::net, NET_PACKET_ONION_SEND_1, new_nonce(), ONION_MAX_PACKET_SIZE, ONION_RETURN_1, Onion::secret_symmetric_key, SEND_BASE, sendpacket(), and SIZE_IPPORT.
Referenced by handle_send_initial(), and handle_TCP_packet().
{
    if (len > ONION_MAX_PACKET_SIZE + SIZE_IPPORT - (1 +
      crypto_box_NONCEBYTES + ONION_RETURN_1))
        return 1;
    if (len <= SIZE_IPPORT + SEND_BASE * 2)
        return 1;
    IP_Port send_to;
    if (ipport_unpack(&send_to, plain, len, 0) == -1)
        return 1;
    uint8_t ip_port[SIZE_IPPORT];
    ipport_pack(ip_port, &source);
    uint8_t data[ONION_MAX_PACKET_SIZE];
    data[0] = NET_PACKET_ONION_SEND_1;
    memcpy(data + 1, nonce, crypto_box_NONCEBYTES);
    memcpy(data + 1 + crypto_box_NONCEBYTES, plain + SIZE_IPPORT, len -
      SIZE_IPPORT);
    uint16_t data_len = 1 + crypto_box_NONCEBYTES + (len - SIZE_IPPORT);
    uint8_t *ret_part = data + data_len;
    new_nonce(ret_part);
    len = encrypt_data_symmetric(onion->
      secret_symmetric_key, ret_part, ip_port, SIZE_IPPORT,
                                 ret_part + crypto_box_NONCEBYTES);
    if (len != SIZE_IPPORT + crypto_box_MACBYTES)
        return 1;
    data_len += crypto_box_NONCEBYTES + len;
    if ((uint32_t)sendpacket(onion->net, send_to, data, data_len) != data_len)
        return 1;
    return 0;
}
int send_onion_packet (Networking_Core * net, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length)
Definition at line 273 of file onion.c.
References create_onion_packet(), Onion_Path::ip_port1, ONION_MAX_PACKET_SIZE, and sendpacket().
Referenced by START_TEST().
{
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    int len = create_onion_packet(packet, sizeof(packet), path, dest,
      data, length);
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}
int send_onion_response (Networking_Core * net, IP_Port dest, const uint8_t * data, uint16_t length, const uint8_t * ret)
Definition at line 293 of file onion.c.
References NET_PACKET_ONION_RECV_3, ONION_RESPONSE_MAX_DATA_SIZE, RETURN_3, and sendpacket().
Referenced by handle_announce_request(), handle_data_request(), and handle_test_1().
{
    if (length > ONION_RESPONSE_MAX_DATA_SIZE || length == 0)
        return -1;
    uint8_t packet[1 + RETURN_3 + length];
    packet[0] = NET_PACKET_ONION_RECV_3;
    memcpy(packet + 1, ret, RETURN_3);
    memcpy(packet + 1 + RETURN_3, data, length);
    if ((uint32_t)sendpacket(net, dest, packet, sizeof(packet)) != sizeof(packet))
        return -1;
    return 0;
}
void set_callback_handle_recv_1 (Onion * onion, int(*)(void *, IP_Port, const uint8_t *, uint16_t) function, void * object)
Definition at line 576 of file onion.c.
References Onion::callback_object, and Onion::recv_1_function.
Referenced by kill_TCP_server(), and new_TCP_server().
{
    onion->recv_1_function = function;
    onion->callback_object = object;
}