toxcore/onion_client.c File Reference
#include `onion_client.h`
*
#include `util.h`
*
#include `LAN_discovery.h`
*
Macros
#define ANNOUNCE_ARRAY_SIZE 256
#define ANNOUNCE_TIMEOUT 10
#define DATA_IN_RESPONSE_MIN_SIZE ONION_DATA_IN_RESPONSE_MIN_SIZE
#define DHTPK_DATA_MIN_LENGTH (1 + sizeof(uint64_t) + crypto_box_PUBLICKEYBYTES)
#define DHTPK_DATA_MAX_LENGTH (DHTPK_DATA_MIN_LENGTH + sizeof(Node_format)*MAX_SENT_NODES)
#define ANNOUNCE_FRIEND (ONION_NODE_PING_INTERVAL * 6)
#define ANNOUNCE_FRIEND_BEGINNING 3
#define FRIEND_ONION_NODE_TIMEOUT (ONION_NODE_TIMEOUT * 6)
#define RUN_COUNT_FRIEND_ANNOUNCE_BEGINNING 17
#define ANNOUNCE_INTERVAL_NOT_ANNOUNCED 3
#define ANNOUNCE_INTERVAL_ANNOUNCED ONION_NODE_PING_INTERVAL
#define ONION_CONNECTION_SECONDS 2
Functions
int onion_add_bs_path_node (Onion_Client *onion_c, IP_Port ip_port, const uint8_t *public_key)
static int onion_add_path_node (Onion_Client *onion_c, IP_Port ip_port, const uint8_t *public_key)
uint16_t onion_backup_nodes (const Onion_Client *onion_c, Node_format *nodes, uint16_t max_num)
static uint16_t random_nodes_path_onion (const Onion_Client *onion_c, Node_format *nodes, uint16_t max_num)
static int is_path_used (const Onion_Client_Paths *onion_paths, const Node_format *nodes)
static _Bool path_timed_out (Onion_Client_Paths *onion_paths, uint32_t pathnum)
static int random_path (const Onion_Client *onion_c, Onion_Client_Paths *onion_paths, uint32_t pathnum, Onion_Path *path)
static _Bool path_exists (Onion_Client_Paths *onion_paths, uint32_t path_num)
static uint32_t set_path_timeouts (Onion_Client *onion_c, uint32_t num, uint32_t path_num)
static int send_onion_packet_tcp_udp (const Onion_Client *onion_c, const Onion_Path *path, IP_Port dest, const uint8_t *data, uint16_t length)
static int new_sendback (Onion_Client *onion_c, uint32_t num, const uint8_t *public_key, IP_Port ip_port, uint32_t path_num, uint64_t *sendback)
static uint32_t check_sendback (Onion_Client *onion_c, const uint8_t *sendback, uint8_t *ret_pubkey, IP_Port *ret_ip_port, uint32_t *path_num)
static int client_send_announce_request (Onion_Client *onion_c, uint32_t num, IP_Port dest, const uint8_t *dest_pubkey, const uint8_t *ping_id, uint32_t pathnum)
static int cmp_entry (const void *a, const void *b)
static int client_add_to_list (Onion_Client *onion_c, uint32_t num, const uint8_t *public_key, IP_Port ip_port, uint8_t is_stored, const uint8_t *pingid_or_key, uint32_t path_num)
static int good_to_ping (Last_Pinged *last_pinged, uint8_t *last_pinged_index, const uint8_t *public_key)
static int client_ping_nodes (Onion_Client *onion_c, uint32_t num, const Node_format *nodes, uint16_t num_nodes, IP_Port source)
static int handle_announce_response (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_data_response (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_dhtpk_announce (void *object, const uint8_t *source_pubkey, const uint8_t *data, uint16_t length)
static int handle_tcp_onion (void *object, const uint8_t *data, uint16_t length)
int send_onion_data (Onion_Client *onion_c, int friend_num, const uint8_t *data, uint16_t length)
static int send_dht_dhtpk (const Onion_Client *onion_c, int friend_num, const uint8_t *data, uint16_t length)
static int handle_dht_dhtpk (void *object, IP_Port source, const uint8_t *source_pubkey, const uint8_t *packet, uint16_t length)
static int send_dhtpk_announce (Onion_Client *onion_c, uint16_t friend_num, uint8_t onion_dht_both)
int onion_friend_num (const Onion_Client *onion_c, const uint8_t *public_key)
static int realloc_onion_friends (Onion_Client *onion_c, uint32_t num)
int onion_addfriend (Onion_Client *onion_c, const uint8_t *public_key)
int onion_delfriend (Onion_Client *onion_c, int friend_num)
int recv_tcp_relay_handler (Onion_Client *onion_c, int friend_num, int(*tcp_relay_node_callback)(void *object, uint32_t number, IP_Port ip_port, const uint8_t *public_key), void *object, uint32_t number)
int onion_dht_pk_callback (Onion_Client *onion_c, int friend_num, void(*function)(void *data, int32_t number, const uint8_t *dht_public_key), void *object, uint32_t number)
int onion_set_friend_DHT_pubkey (Onion_Client *onion_c, int friend_num, const uint8_t *dht_key)
unsigned int onion_getfriend_DHT_pubkey (const Onion_Client *onion_c, int friend_num, uint8_t *dht_key)
int onion_getfriendip (const Onion_Client *onion_c, int friend_num, IP_Port *ip_port)
int onion_set_friend_online (Onion_Client *onion_c, int friend_num, uint8_t is_online)
static void populate_path_nodes (Onion_Client *onion_c)
static void populate_path_nodes_tcp (Onion_Client *onion_c)
static void do_friend (Onion_Client *onion_c, uint16_t friendnum)
void oniondata_registerhandler (Onion_Client *onion_c, uint8_t byte, oniondata_handler_callback cb, void *object)
static void do_announce (Onion_Client *onion_c)
static int onion_isconnected (const Onion_Client *onion_c)
unsigned int onion_connection_status (const Onion_Client *onion_c)
void do_onion_client (Onion_Client *onion_c)
Onion_Client * new_onion_client (Net_Crypto *c)
void kill_onion_client (Onion_Client *onion_c)
Variables
static uint8_t cmp_public_key [crypto_box_PUBLICKEYBYTES]
Macro Definition Documentation
#define ANNOUNCE_ARRAY_SIZE 256
Definition at line 33 of file onion_client.c.
Referenced by new_onion_client().
#define ANNOUNCE_FRIEND (ONION_NODE_PING_INTERVAL * 6)
Definition at line 1231 of file onion_client.c.
Referenced by do_friend().
#define ANNOUNCE_FRIEND_BEGINNING 3
Definition at line 1232 of file onion_client.c.
Referenced by do_friend().
#define ANNOUNCE_INTERVAL_ANNOUNCED ONION_NODE_PING_INTERVAL
Definition at line 1317 of file onion_client.c.
Referenced by do_announce().
#define ANNOUNCE_INTERVAL_NOT_ANNOUNCED 3
Definition at line 1316 of file onion_client.c.
Referenced by do_announce().
#define ANNOUNCE_TIMEOUT 10
Definition at line 34 of file onion_client.c.
Referenced by new_onion_client().
#define DATA_IN_RESPONSE_MIN_SIZE ONION_DATA_IN_RESPONSE_MIN_SIZE
Definition at line 667 of file onion_client.c.
Referenced by handle_data_response(), handle_dht_dhtpk(), send_dht_dhtpk(), and send_onion_data().
#define DHTPK_DATA_MAX_LENGTH (DHTPK_DATA_MIN_LENGTH + sizeof(Node_format)*MAX_SENT_NODES)
Definition at line 702 of file onion_client.c.
Referenced by handle_dht_dhtpk(), handle_dhtpk_announce(), and send_dhtpk_announce().
#define DHTPK_DATA_MIN_LENGTH (1 + sizeof(uint64_t) + crypto_box_PUBLICKEYBYTES)
Definition at line 701 of file onion_client.c.
Referenced by handle_dht_dhtpk(), handle_dhtpk_announce(), and send_dhtpk_announce().
#define FRIEND_ONION_NODE_TIMEOUT (ONION_NODE_TIMEOUT * 6)
Definition at line 1233 of file onion_client.c.
Referenced by do_friend().
#define ONION_CONNECTION_SECONDS 2
Definition at line 1412 of file onion_client.c.
Referenced by do_onion_client(), and onion_connection_status().
#define RUN_COUNT_FRIEND_ANNOUNCE_BEGINNING 17
Definition at line 1235 of file onion_client.c.
Referenced by do_friend().
Function Documentation
static uint32_t check_sendback (Onion_Client * onion_c, const uint8_t * sendback, uint8_t * ret_pubkey, IP_Port * ret_ip_port, uint32_t * path_num) [static]
Definition at line 379 of file onion_client.c.
References Onion_Client::announce_ping_array, make-funny-savefile::data, num, and ping_array_check().
Referenced by handle_announce_response().
{
    uint64_t sback;
    memcpy(&sback, sendback, sizeof(uint64_t));
    uint8_t data[sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + sizeof(
      IP_Port) + sizeof(uint32_t)];
    if (ping_array_check(data, sizeof(data), &onion_c->
      announce_ping_array, sback) != sizeof(data))
        return ~0;
    memcpy(ret_pubkey, data + sizeof(uint32_t), crypto_box_PUBLICKEYBYTES);
    memcpy(ret_ip_port, data + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES, sizeof(
      IP_Port));
    memcpy(path_num, data + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + sizeof(
      IP_Port), sizeof(uint32_t));
    uint32_t num;
    memcpy(&num, data, sizeof(uint32_t));
    return num;
}
static int client_add_to_list (Onion_Client * onion_c, uint32_t num, const uint8_t * public_key, IP_Port ip_port, uint8_t is_stored, const uint8_t * pingid_or_key, uint32_t path_num) [static]
Definition at line 472 of file onion_client.c.
References Onion_Client::c, Onion_Client::clients_announce_list, Onion_Friend::clients_list, cmp_entry(), cmp_public_key, Onion_Client::friends_list, i, id_closest(), Onion_Node::ip_port, Onion_Node::is_stored, is_timeout(), Onion_Node::last_pinged, MAX_ONION_CLIENTS, Onion_Client::num_friends, onion_add_path_node(), ONION_NODE_TIMEOUT, ONION_PING_ID_SIZE, Onion_Node::path_used, Onion_Friend::real_public_key, Net_Crypto::self_public_key, set_path_timeouts(), Onion_Client::temp_public_key, Onion_Node::timestamp, and unix_time().
Referenced by handle_announce_response().
{
    if (num > onion_c->num_friends)
        return -1;
    Onion_Node *list_nodes = NULL;
    uint8_t *reference_id = NULL;
    if (num == 0) {
        list_nodes = onion_c->clients_announce_list;
        reference_id = onion_c->c->self_public_key;
        if (is_stored == 1 && memcmp(pingid_or_key, onion_c->temp_public_key,
      crypto_box_PUBLICKEYBYTES) != 0) {
            is_stored = 0;
        }
    } else {
        if (is_stored >= 2)
            return -1;
        list_nodes = onion_c->friends_list[num - 1].clients_list;
        reference_id = onion_c->friends_list[num - 1].
      real_public_key;
    }
    memcpy(cmp_public_key, reference_id, crypto_box_PUBLICKEYBYTES);
    qsort(list_nodes, MAX_ONION_CLIENTS, sizeof(Onion_Node),
      cmp_entry);
    int index = -1, stored = 0;
    unsigned int i;
    if (is_timeout(list_nodes[0].timestamp, ONION_NODE_TIMEOUT)
            || id_closest(reference_id, list_nodes[0].public_key, public_key) == 2) {
        index = 0;
    }
    for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
        if (memcmp(list_nodes[i].public_key, public_key, crypto_box_PUBLICKEYBYTES) == 0) {
            index = i;
            stored = 1;
            break;
        }
    }
    if (index == -1)
        return 0;
    memcpy(list_nodes[index].public_key, public_key, crypto_box_PUBLICKEYBYTES);
    list_nodes[index].ip_port = ip_port;
    //TODO: remove this and find a better source of nodes to use for paths.
    onion_add_path_node(onion_c, ip_port, public_key);
    if (is_stored == 1) {
        memcpy(list_nodes[index].data_public_key, pingid_or_key, crypto_box_PUBLICKEYBYTES);
    } else {
        memcpy(list_nodes[index].ping_id, pingid_or_key, ONION_PING_ID_SIZE);
    }
    list_nodes[index].is_stored = is_stored;
    list_nodes[index].timestamp = unix_time();
    if (!stored)
        list_nodes[index].last_pinged = 0;
    list_nodes[index].path_used = set_path_timeouts(onion_c,
      num, path_num);
    return 0;
}
static int client_ping_nodes (Onion_Client * onion_c, uint32_t num, const Node_format * nodes, uint16_t num_nodes, IP_Port source) [static]
Definition at line 557 of file onion_client.c.
References Onion_Client::c, client_send_announce_request(), Onion_Client::clients_announce_list, Onion_Friend::clients_list, Onion_Client::friends_list, good_to_ping(), i, id_closest(), IP_Port::ip, is_timeout(), LAN_ip(), Onion_Friend::last_pinged, Onion_Client::last_pinged, Onion_Friend::last_pinged_index, Onion_Client::last_pinged_index, MAX_ONION_CLIENTS, Onion_Client::num_friends, ONION_NODE_TIMEOUT, make-funny-savefile::public_key, Onion_Friend::real_public_key, and Net_Crypto::self_public_key.
Referenced by handle_announce_response().
{
    if (num > onion_c->num_friends)
        return -1;
    if (num_nodes == 0)
        return 0;
    Onion_Node *list_nodes = NULL;
    uint8_t *reference_id = NULL;
    Last_Pinged *last_pinged = NULL;
    uint8_t *last_pinged_index = NULL;
    if (num == 0) {
        list_nodes = onion_c->clients_announce_list;
        reference_id = onion_c->c->self_public_key;
        last_pinged = onion_c->last_pinged;
        last_pinged_index = &onion_c->last_pinged_index;
    } else {
        list_nodes = onion_c->friends_list[num - 1].clients_list;
        reference_id = onion_c->friends_list[num - 1].
      real_public_key;
        last_pinged = onion_c->friends_list[num - 1].last_pinged;
        last_pinged_index = &onion_c->friends_list[num - 1].
      last_pinged_index;
    }
    unsigned int i, j;
    int lan_ips_accepted = (LAN_ip(source.ip) == 0);
    for (i = 0; i < num_nodes; ++i) {
        if (!lan_ips_accepted)
            if (LAN_ip(nodes[i].ip_port.ip) == 0)
                continue;
        if (is_timeout(list_nodes[0].timestamp, ONION_NODE_TIMEOUT)
                || id_closest(reference_id, list_nodes[0].public_key, nodes[i].
      public_key) == 2) {
            /* check if node is already in list. */
            for (j = 0; j < MAX_ONION_CLIENTS; ++j) {
                if (memcmp(list_nodes[j].public_key, nodes[i].public_key,
      crypto_box_PUBLICKEYBYTES) == 0) {
                    break;
                }
            }
            if (j == MAX_ONION_CLIENTS && good_to_ping(last_pinged, last_pinged_index, nodes[i]
      .public_key)) {
                client_send_announce_request(onion_c,
      num, nodes[i].ip_port, nodes[i].public_key, NULL, ~0);
            }
        }
    }
    return 0;
}
static int client_send_announce_request (Onion_Client * onion_c, uint32_t num, IP_Port dest, const uint8_t * dest_pubkey, const uint8_t * ping_id, uint32_t pathnum) [static]
Definition at line 398 of file onion_client.c.
References Onion_Client::c, create_announce_request(), Onion_Client::friends_list, new_sendback(), Onion_Client::num_friends, ONION_ANNOUNCE_REQUEST_SIZE, Onion_Client::onion_paths_friends, Onion_Client::onion_paths_self, ONION_PING_ID_SIZE, path, Onion_Path::path_num, random_path(), Onion_Friend::real_public_key, Net_Crypto::self_public_key, Net_Crypto::self_secret_key, send_onion_packet_tcp_udp(), Onion_Friend::temp_public_key, Onion_Client::temp_public_key, and Onion_Friend::temp_secret_key.
Referenced by client_ping_nodes(), do_announce(), and do_friend().
{
    if (num > onion_c->num_friends)
        return -1;
    uint64_t sendback;
    Onion_Path path;
    if (num == 0) {
        if (random_path(onion_c, &onion_c->onion_paths_self, pathnum, &path) ==
      -1)
            return -1;
    } else {
        if (random_path(onion_c, &onion_c->onion_paths_friends, pathnum, &
      path) == -1)
            return -1;
    }
    if (new_sendback(onion_c, num, dest_pubkey, dest, path.
      path_num, &sendback) == -1)
        return -1;
    uint8_t zero_ping_id[ONION_PING_ID_SIZE] = {0};
    if (ping_id == NULL)
        ping_id = zero_ping_id;
    uint8_t request[ONION_ANNOUNCE_REQUEST_SIZE];
    int len;
    if (num == 0) {
        len = create_announce_request(request, sizeof(request), dest_pubkey, onion_c
      ->c->self_public_key,
                                      onion_c->c->self_secret_key, ping_id, onion_c->
      c->self_public_key, onion_c->temp_public_key, sendback);
    } else {
        len = create_announce_request(request, sizeof(request), dest_pubkey, onion_c
      ->friends_list[num - 1].temp_public_key,
                                      onion_c->friends_list[num - 1].
      temp_secret_key, ping_id, onion_c->friends_list[num - 1].
      real_public_key, zero_ping_id,
                                      sendback);
    }
    if (len == -1) {
        return -1;
    }
    return send_onion_packet_tcp_udp(onion_c, &path, dest, request, len);
}
static int cmp_entry (const void * a, const void * b) [static]
Definition at line 444 of file onion_client.c.
References cmp_public_key, id_closest(), is_timeout(), ONION_NODE_TIMEOUT, Onion_Node::public_key, and Onion_Node::timestamp.
Referenced by client_add_to_list().
{
    Onion_Node entry1, entry2;
    memcpy(&entry1, a, sizeof(Onion_Node));
    memcpy(&entry2, b, sizeof(Onion_Node));
    int t1 = is_timeout(entry1.timestamp, ONION_NODE_TIMEOUT);
    int t2 = is_timeout(entry2.timestamp, ONION_NODE_TIMEOUT);
    if (t1 && t2)
        return 0;
    if (t1)
        return -1;
    if (t2)
        return 1;
    int close = id_closest(cmp_public_key, entry1.
      public_key, entry2.public_key);
    if (close == 1)
        return 1;
    if (close == 2)
        return -1;
    return 0;
}
static void do_announce (Onion_Client * onion_c) [static]
Definition at line 1319 of file onion_client.c.
References ANNOUNCE_INTERVAL_ANNOUNCED, ANNOUNCE_INTERVAL_NOT_ANNOUNCED, client_send_announce_request(), Onion_Client::clients_announce_list, i, is_timeout(), Onion_Node::last_pinged, MAX_ONION_CLIENTS, MAX_PATH_NODES, num, ONION_NODE_TIMEOUT, Onion_Client::onion_paths_self, path_exists(), Onion_Client::path_nodes, Onion_Client::path_nodes_bs, Onion_Client::path_nodes_index, Onion_Client::path_nodes_index_bs, Onion_Node::path_used, make-funny-savefile::public_key, and unix_time().
Referenced by do_onion_client().
{
    unsigned int i, count = 0;
    Onion_Node *list_nodes = onion_c->clients_announce_list;
    for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
        if (is_timeout(list_nodes[i].timestamp, ONION_NODE_TIMEOUT))
            continue;
        ++count;
        /* Don't announce ourselves the first time this is run to new peers */
        if (list_nodes[i].last_pinged == 0) {
            list_nodes[i].last_pinged = 1;
            continue;
        }
        unsigned int interval = ANNOUNCE_INTERVAL_NOT_ANNOUNCED;
        if (list_nodes[i].is_stored && path_exists(&onion_c->
      onion_paths_self, list_nodes[i].path_used)) {
            interval = ANNOUNCE_INTERVAL_ANNOUNCED;
        }
        if (is_timeout(list_nodes[i].last_pinged, interval)) {
            if (client_send_announce_request(onion_c, 0, list_nodes[i].ip_port,
       list_nodes[i].public_key,
                                             list_nodes[i].ping_id, list_nodes[i].path_used) == 0) {
                list_nodes[i].last_pinged = unix_time();
            }
        }
    }
    if (count != MAX_ONION_CLIENTS) {
        unsigned int num_nodes;
        Node_format *path_nodes;
        if (rand() % 2 == 0 || onion_c->path_nodes_index == 0) {
            num_nodes = (onion_c->path_nodes_index_bs <
      MAX_PATH_NODES) ? onion_c->path_nodes_index_bs :
      MAX_PATH_NODES;
            path_nodes = onion_c->path_nodes_bs;
        } else {
            num_nodes = (onion_c->path_nodes_index <
      MAX_PATH_NODES) ? onion_c->path_nodes_index :
      MAX_PATH_NODES;
            path_nodes = onion_c->path_nodes;
        }
        if (count < (uint32_t)rand() % MAX_ONION_CLIENTS) {
            if (num_nodes != 0) {
                for (i = 0; i < (MAX_ONION_CLIENTS / 2); ++i) {
                    unsigned int num = rand() % num_nodes;
                    client_send_announce_request(onion_c, 0, path_nodes[num].
      ip_port, path_nodes[num].public_key, 0, ~0);
                }
            }
        }
    }
}
static void do_friend (Onion_Client * onion_c, uint16_t friendnum) [static]
Definition at line 1237 of file onion_client.c.
References ANNOUNCE_FRIEND, ANNOUNCE_FRIEND_BEGINNING, client_send_announce_request(), Onion_Friend::clients_list, DHT_DHTPK_SEND_INTERVAL, FRIEND_ONION_NODE_TIMEOUT, Onion_Client::friends_list, i, Node_format::ip_port, Onion_Friend::is_online, is_timeout(), Onion_Friend::last_dht_pk_dht_sent, Onion_Friend::last_dht_pk_onion_sent, Onion_Node::last_pinged, MAX_ONION_CLIENTS, MAX_PATH_NODES, num, Onion_Client::num_friends, ONION_DHTPK_SEND_INTERVAL, Onion_Client::path_nodes, Onion_Client::path_nodes_index, make-funny-savefile::public_key, Node_format::public_key, Onion_Friend::run_count, RUN_COUNT_FRIEND_ANNOUNCE_BEGINNING, send_dhtpk_announce(), Onion_Friend::status, and unix_time().
Referenced by do_onion_client().
{
    if (friendnum >= onion_c->num_friends)
        return;
    if (onion_c->friends_list[friendnum].status == 0)
        return;
    unsigned int interval = ANNOUNCE_FRIEND;
    if (onion_c->friends_list[friendnum].run_count <
      RUN_COUNT_FRIEND_ANNOUNCE_BEGINNING)
        interval = ANNOUNCE_FRIEND_BEGINNING;
    unsigned int i, count = 0;
    Onion_Node *list_nodes = onion_c->friends_list[friendnum].
      clients_list;
    if (!onion_c->friends_list[friendnum].is_online) {
        for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
            if (is_timeout(list_nodes[i].timestamp,
      FRIEND_ONION_NODE_TIMEOUT))
                continue;
            ++count;
            if (list_nodes[i].last_pinged == 0) {
                list_nodes[i].last_pinged = unix_time();
                continue;
            }
            if (is_timeout(list_nodes[i].last_pinged, interval)) {
                if (client_send_announce_request(onion_c, friendnum + 1,
      list_nodes[i].ip_port, list_nodes[i].public_key, 0, ~0) == 0) {
                    list_nodes[i].last_pinged = unix_time();
                }
            }
        }
        if (count != MAX_ONION_CLIENTS) {
            unsigned int num_nodes = (onion_c->path_nodes_index <
      MAX_PATH_NODES) ? onion_c->path_nodes_index :
      MAX_PATH_NODES;
            unsigned int n = num_nodes;
            if (num_nodes > (MAX_ONION_CLIENTS / 2))
                n = (MAX_ONION_CLIENTS / 2);
            if (num_nodes != 0) {
                unsigned int j;
                for (j = 0; j < n; ++j) {
                    unsigned int num = rand() % num_nodes;
                    client_send_announce_request(onion_c, friendnum + 1,
      onion_c->path_nodes[num].ip_port,
                                                 onion_c->path_nodes[num].
      public_key, 0, ~0);
                }
                ++onion_c->friends_list[friendnum].run_count;
            }
        } else {
            ++onion_c->friends_list[friendnum].run_count;
        }
        /* send packets to friend telling them our DHT public key. */
        if (is_timeout(onion_c->friends_list[friendnum].
      last_dht_pk_onion_sent, ONION_DHTPK_SEND_INTERVAL))
            if (send_dhtpk_announce(onion_c, friendnum, 0) >= 1)
                onion_c->friends_list[friendnum].
      last_dht_pk_onion_sent = unix_time();
        if (is_timeout(onion_c->friends_list[friendnum].
      last_dht_pk_dht_sent, DHT_DHTPK_SEND_INTERVAL))
            if (send_dhtpk_announce(onion_c, friendnum, 1) >= 1)
                onion_c->friends_list[friendnum].
      last_dht_pk_dht_sent = unix_time();
    }
}
void do_onion_client (Onion_Client * onion_c)
Definition at line 1431 of file onion_client.c.
References Onion_Client::c, Onion_Client::dht, DHT_non_lan_connected(), do_announce(), do_friend(), Onion_Client::first_run, get_random_tcp_onion_conn_number(), i, is_timeout(), Onion_Client::last_run, Onion_Client::num_friends, Onion_Client::onion_connected, ONION_CONNECTION_SECONDS, onion_connection_status(), onion_isconnected(), populate_path_nodes(), populate_path_nodes_tcp(), set_tcp_onion_status(), Net_Crypto::tcp_c, Onion_Client::UDP_connected, and unix_time().
Referenced by do_messenger(), and do_onions().
{
    unsigned int i;
    if (onion_c->last_run == unix_time())
        return;
    populate_path_nodes(onion_c);
    do_announce(onion_c);
    if (onion_isconnected(onion_c)) {
        if (onion_c->onion_connected < ONION_CONNECTION_SECONDS * 2)
       {
            ++onion_c->onion_connected;
        }
    } else {
        populate_path_nodes_tcp(onion_c);
        if (onion_c->onion_connected != 0) {
            --onion_c->onion_connected;
        }
    }
    _Bool UDP_connected = DHT_non_lan_connected(onion_c->
      dht);
    if (is_timeout(onion_c->first_run,
      ONION_CONNECTION_SECONDS)) {
        set_tcp_onion_status(onion_c->c->tcp_c, !UDP_connected);
    }
    onion_c->UDP_connected = UDP_connected
                             || get_random_tcp_onion_conn_number(onion_c->
      c->tcp_c) == -1; /* Check if connected to any TCP relays. */
    if (onion_connection_status(onion_c)) {
        for (i = 0; i < onion_c->num_friends; ++i) {
            do_friend(onion_c, i);
        }
    }
    if (onion_c->last_run == 0) {
        onion_c->first_run = unix_time();
    }
    onion_c->last_run = unix_time();
}
static int good_to_ping (Last_Pinged * last_pinged, uint8_t * last_pinged_index, const uint8_t * public_key) [static]
Definition at line 541 of file onion_client.c.
References i, is_timeout(), MAX_STORED_PINGED_NODES, MIN_NODE_PING_TIME, Last_Pinged::timestamp, and unix_time().
Referenced by client_ping_nodes().
{
    unsigned int i;
    for (i = 0; i < MAX_STORED_PINGED_NODES; ++i) {
        if (!is_timeout(last_pinged[i].timestamp, MIN_NODE_PING_TIME))
            if (memcmp(last_pinged[i].public_key, public_key, crypto_box_PUBLICKEYBYTES) == 0)
                return 0;
    }
    memcpy(last_pinged[*last_pinged_index % MAX_STORED_PINGED_NODES].public_key, public_key,
      crypto_box_PUBLICKEYBYTES);
    last_pinged[*last_pinged_index % MAX_STORED_PINGED_NODES].
      timestamp = unix_time();
    ++*last_pinged_index;
    return 1;
}
static int handle_announce_response (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 611 of file onion_client.c.
References Onion_Client::c, check_sendback(), client_add_to_list(), client_ping_nodes(), decrypt_data(), Onion_Client::friends_list, Onion_Client::last_packet_recv, MAX_SENT_NODES, num, Onion_Client::num_friends, ONION_ANNOUNCE_RESPONSE_MAX_SIZE, ONION_ANNOUNCE_RESPONSE_MIN_SIZE, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, ONION_PING_ID_SIZE, make-funny-savefile::public_key, Net_Crypto::self_secret_key, Onion_Friend::status, Onion_Friend::temp_secret_key, unix_time(), and unpack_nodes().
Referenced by handle_tcp_onion(), and new_onion_client().
{
    Onion_Client *onion_c = object;
    if (length < ONION_ANNOUNCE_RESPONSE_MIN_SIZE || length >
      ONION_ANNOUNCE_RESPONSE_MAX_SIZE)
        return 1;
    uint16_t len_nodes = length - ONION_ANNOUNCE_RESPONSE_MIN_SIZE;
    uint8_t public_key[crypto_box_PUBLICKEYBYTES];
    IP_Port ip_port;
    uint32_t path_num;
    uint32_t num = check_sendback(onion_c, packet + 1, public_key, &ip_port, &path_num);
    if (num > onion_c->num_friends)
        return 1;
    uint8_t plain[1 + ONION_PING_ID_SIZE + len_nodes];
    int len = -1;
    if (num == 0) {
        len = decrypt_data(public_key, onion_c->c->self_secret_key, packet + 1
      + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH,
                           packet + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES,
                           length - (1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES), plain);
    } else {
        if (onion_c->friends_list[num - 1].status == 0)
            return 1;
        len = decrypt_data(public_key, onion_c->friends_list[num - 1].
      temp_secret_key,
                           packet + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
      ,
                           packet + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES,
                           length - (1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES), plain);
    }
    if ((uint32_t)len != sizeof(plain))
        return 1;
    if (client_add_to_list(onion_c, num, public_key, ip_port, plain[0], plain + 1,
      path_num) == -1)
        return 1;
    if (len_nodes != 0) {
        Node_format nodes[MAX_SENT_NODES];
        int num_nodes = unpack_nodes(nodes, MAX_SENT_NODES, 0, plain + 1 +
      ONION_PING_ID_SIZE, len_nodes, 0);
        if (num_nodes <= 0)
            return 1;
        if (client_ping_nodes(onion_c, num, nodes, num_nodes, source) == -1)
            return 1;
    }
    //TODO: LAN vs non LAN ips?, if we are connected only to LAN, are we offline?
    onion_c->last_packet_recv = unix_time();
    return 0;
}
static int handle_data_response (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 669 of file onion_client.c.
References Onion_Client::c, DATA_IN_RESPONSE_MIN_SIZE, decrypt_data(), Onion_Client::function, MAX_DATA_REQUEST_SIZE, Onion_Client::object, Onion_Client::Onion_Data_Handlers, ONION_DATA_RESPONSE_MIN_SIZE, Net_Crypto::self_secret_key, and Onion_Client::temp_secret_key.
Referenced by handle_tcp_onion(), and new_onion_client().
{
    Onion_Client *onion_c = object;
    if (length <= (ONION_DATA_RESPONSE_MIN_SIZE +
      DATA_IN_RESPONSE_MIN_SIZE))
        return 1;
    if (length > MAX_DATA_REQUEST_SIZE)
        return 1;
    uint8_t temp_plain[length - ONION_DATA_RESPONSE_MIN_SIZE];
    int len = decrypt_data(packet + 1 + crypto_box_NONCEBYTES, onion_c->
      temp_secret_key, packet + 1,
                           packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
                           length - (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES), temp_plain);
    if ((uint32_t)len != sizeof(temp_plain))
        return 1;
    uint8_t plain[sizeof(temp_plain) - DATA_IN_RESPONSE_MIN_SIZE];
    len = decrypt_data(temp_plain, onion_c->c->self_secret_key, packet + 1,
      temp_plain + crypto_box_PUBLICKEYBYTES,
                       sizeof(temp_plain) - crypto_box_PUBLICKEYBYTES, plain);
    if ((uint32_t)len != sizeof(plain))
        return 1;
    if (!onion_c->Onion_Data_Handlers[plain[0]].function)
        return 1;
    return onion_c->Onion_Data_Handlers[plain[0]].function(onion_c->
      Onion_Data_Handlers[plain[0]].object, temp_plain, plain,
            sizeof(plain));
}
static int handle_dht_dhtpk (void * object, IP_Port source, const uint8_t * source_pubkey, const uint8_t * packet, uint16_t length) [static]
Definition at line 888 of file onion_client.c.
References Onion_Client::c, DATA_IN_RESPONSE_MIN_SIZE, decrypt_data(), DHTPK_DATA_MAX_LENGTH, DHTPK_DATA_MIN_LENGTH, handle_dhtpk_announce(), and Net_Crypto::self_secret_key.
Referenced by new_onion_client().
{
    Onion_Client *onion_c = object;
    if (length < DHTPK_DATA_MIN_LENGTH +
      DATA_IN_RESPONSE_MIN_SIZE + crypto_box_NONCEBYTES)
        return 1;
    if (length > DHTPK_DATA_MAX_LENGTH +
      DATA_IN_RESPONSE_MIN_SIZE + crypto_box_NONCEBYTES)
        return 1;
    uint8_t plain[DHTPK_DATA_MAX_LENGTH];
    int len = decrypt_data(packet, onion_c->c->self_secret_key, packet +
      crypto_box_PUBLICKEYBYTES,
                           packet + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES,
                           length - (crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES), plain);
    if (len != length - (DATA_IN_RESPONSE_MIN_SIZE + crypto_box_NONCEBYTES))
        return 1;
    if (memcmp(source_pubkey, plain + 1 + sizeof(uint64_t), crypto_box_PUBLICKEYBYTES) != 0)
        return 1;
    return handle_dhtpk_announce(onion_c, packet, plain, len);
}
static int handle_dhtpk_announce (void * object, const uint8_t * source_pubkey, const uint8_t * data, uint16_t length) [static]
Definition at line 703 of file onion_client.c.
References Onion_Client::dht, DHT_getnodes(), Onion_Friend::dht_pk_callback, Onion_Friend::dht_pk_callback_number, Onion_Friend::dht_pk_callback_object, Onion_Friend::dht_public_key, DHTPK_DATA_MAX_LENGTH, DHTPK_DATA_MIN_LENGTH, IP::family, Onion_Client::friends_list, i, IP_Port::ip, Node_format::ip_port, Onion_Friend::last_noreplay, Onion_Friend::last_seen, MAX_SENT_NODES, net_to_host, onion_friend_num(), onion_set_friend_DHT_pubkey(), make-funny-savefile::public_key, Node_format::public_key, TCP_INET, TCP_INET6, Onion_Friend::tcp_relay_node_callback, Onion_Friend::tcp_relay_node_callback_number, Onion_Friend::tcp_relay_node_callback_object, unix_time(), and unpack_nodes().
Referenced by handle_dht_dhtpk(), and new_onion_client().
{
    Onion_Client *onion_c = object;
    if (length < DHTPK_DATA_MIN_LENGTH)
        return 1;
    if (length > DHTPK_DATA_MAX_LENGTH)
        return 1;
    int friend_num = onion_friend_num(onion_c, source_pubkey);
    if (friend_num == -1)
        return 1;
    uint64_t no_replay;
    memcpy(&no_replay, data + 1, sizeof(uint64_t));
    net_to_host((uint8_t *) &no_replay, sizeof(no_replay));
    if (no_replay <= onion_c->friends_list[friend_num].last_noreplay)
        return 1;
    onion_c->friends_list[friend_num].last_noreplay = no_replay;
    if (onion_c->friends_list[friend_num].dht_pk_callback)
        onion_c->friends_list[friend_num].dht_pk_callback(onion_c->
      friends_list[friend_num].dht_pk_callback_object,
                onion_c->friends_list[friend_num].
      dht_pk_callback_number, data + 1 + sizeof(uint64_t));
    onion_set_friend_DHT_pubkey(onion_c, friend_num,
      data + 1 + sizeof(uint64_t));
    onion_c->friends_list[friend_num].last_seen = unix_time();
    uint16_t len_nodes = length - DHTPK_DATA_MIN_LENGTH;
    if (len_nodes != 0) {
        Node_format nodes[MAX_SENT_NODES];
        int num_nodes = unpack_nodes(nodes, MAX_SENT_NODES, 0,
      data + 1 + sizeof(uint64_t) + crypto_box_PUBLICKEYBYTES,
                                     len_nodes, 1);
        if (num_nodes <= 0)
            return 1;
        int i;
        for (i = 0; i < num_nodes; ++i) {
            uint8_t family = nodes[i].ip_port.ip.family;
            if (family == AF_INET || family == AF_INET6) {
                DHT_getnodes(onion_c->dht, &nodes[i].ip_port, nodes[i].
      public_key, onion_c->friends_list[friend_num].
      dht_public_key);
            } else if (family == TCP_INET || family == TCP_INET6) {
                if (onion_c->friends_list[friend_num].
      tcp_relay_node_callback) {
                    void *obj = onion_c->friends_list[friend_num].
      tcp_relay_node_callback_object;
                    uint32_t number = onion_c->friends_list[friend_num].
      tcp_relay_node_callback_number;
                    onion_c->friends_list[friend_num].
      tcp_relay_node_callback(obj, number, nodes[i].ip_port, nodes[i].
      public_key);
                }
            }
        }
    }
    return 0;
}
static int handle_tcp_onion (void * object, const uint8_t * data, uint16_t length) [static]
Definition at line 764 of file onion_client.c.
References IP::family, handle_announce_response(), handle_data_response(), IP_Port::ip, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, and TCP_FAMILY.
Referenced by new_onion_client().
{
    if (length == 0)
        return 1;
    IP_Port ip_port = {0};
    ip_port.ip.family = TCP_FAMILY;
    if (data[0] == NET_PACKET_ANNOUNCE_RESPONSE) {
        return handle_announce_response(object, ip_port,
      data, length);
    } else if (data[0] == NET_PACKET_ONION_DATA_RESPONSE) {
        return handle_data_response(object, ip_port, data, length);
    }
    return 1;
}
static int is_path_used (const Onion_Client_Paths * onion_paths, const Node_format * nodes) [static]
Definition at line 180 of file onion_client.c.
References i, Node_format::ip_port, Onion_Path::ip_port1, ipport_equal(), is_timeout(), Onion_Client_Paths::last_path_success, NUMBER_ONION_PATHS, ONION_PATH_LENGTH, ONION_PATH_MAX_LIFETIME, ONION_PATH_TIMEOUT, Onion_Client_Paths::path_creation_time, and Onion_Client_Paths::paths.
Referenced by random_path().
{
    unsigned int i;
    for (i = 0; i < NUMBER_ONION_PATHS; ++i) {
        if (is_timeout(onion_paths->last_path_success[i],
      ONION_PATH_TIMEOUT)) {
            continue;
        }
        if (is_timeout(onion_paths->path_creation_time[i],
      ONION_PATH_MAX_LIFETIME)) {
            continue;
        }
        if (ipport_equal(&onion_paths->paths[i].ip_port1, &nodes[
      ONION_PATH_LENGTH - 1].ip_port)) {
            return i;
        }
    }
    return -1;
}
void kill_onion_client (Onion_Client * onion_c)
Definition at line 1506 of file onion_client.c.
References Onion_Client::announce_ping_array, Onion_Client::c, CRYPTO_PACKET_DHTPK, cryptopacket_registerhandler(), Onion_Client::dht, Onion_Client::net, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, networking_registerhandler(), ONION_DATA_DHTPK, oniondata_registerhandler(), ping_array_free_all(), realloc_onion_friends(), set_onion_packet_tcp_connection_callback(), and Net_Crypto::tcp_c.
Referenced by kill_messenger(), kill_onions(), and new_messenger().
{
    if (onion_c == NULL)
        return;
    ping_array_free_all(&onion_c->announce_ping_array);
    realloc_onion_friends(onion_c, 0);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ANNOUNCE_RESPONSE, NULL, NULL);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ONION_DATA_RESPONSE, NULL, NULL);
    oniondata_registerhandler(onion_c, ONION_DATA_DHTPK, NULL,
      NULL);
    cryptopacket_registerhandler(onion_c->dht,
      CRYPTO_PACKET_DHTPK, NULL, NULL);
    set_onion_packet_tcp_connection_callback(onion_c->
      c->tcp_c, NULL, NULL);
    memset(onion_c, 0, sizeof(Onion_Client));
    free(onion_c);
}
Onion_Client* new_onion_client (Net_Crypto * c)
Definition at line 1477 of file onion_client.c.
References ANNOUNCE_ARRAY_SIZE, Onion_Client::announce_ping_array, ANNOUNCE_TIMEOUT, Onion_Client::c, CRYPTO_PACKET_DHTPK, cryptopacket_registerhandler(), Onion_Client::dht, Net_Crypto::dht, handle_announce_response(), handle_data_response(), handle_dht_dhtpk(), handle_dhtpk_announce(), handle_tcp_onion(), Onion_Client::net, DHT::net, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, networking_registerhandler(), new_symmetric_key(), ONION_DATA_DHTPK, oniondata_registerhandler(), ping_array_init(), Onion_Client::secret_symmetric_key, set_onion_packet_tcp_connection_callback(), Net_Crypto::tcp_c, Onion_Client::temp_public_key, and Onion_Client::temp_secret_key.
Referenced by new_messenger(), and new_onions().
{
    if (c == NULL)
        return NULL;
    Onion_Client *onion_c = calloc(1, sizeof(Onion_Client));
    if (onion_c == NULL)
        return NULL;
    if (ping_array_init(&onion_c->announce_ping_array,
      ANNOUNCE_ARRAY_SIZE, ANNOUNCE_TIMEOUT) != 0) {
        free(onion_c);
        return NULL;
    }
    onion_c->dht = c->dht;
    onion_c->net = c->dht->net;
    onion_c->c = c;
    new_symmetric_key(onion_c->secret_symmetric_key);
    crypto_box_keypair(onion_c->temp_public_key, onion_c->
      temp_secret_key);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ANNOUNCE_RESPONSE, &
      handle_announce_response, onion_c);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ONION_DATA_RESPONSE, &
      handle_data_response, onion_c);
    oniondata_registerhandler(onion_c, ONION_DATA_DHTPK, &
      handle_dhtpk_announce, onion_c);
    cryptopacket_registerhandler(onion_c->dht,
      CRYPTO_PACKET_DHTPK, &handle_dht_dhtpk, onion_c);
    set_onion_packet_tcp_connection_callback(onion_c->
      c->tcp_c, &handle_tcp_onion, onion_c);
    return onion_c;
}
static int new_sendback (Onion_Client * onion_c, uint32_t num, const uint8_t * public_key, IP_Port ip_port, uint32_t path_num, uint64_t * sendback) [static]
Definition at line 353 of file onion_client.c.
References Onion_Client::announce_ping_array, make-funny-savefile::data, and ping_array_add().
Referenced by client_send_announce_request().
{
    uint8_t data[sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + sizeof(
      IP_Port) + sizeof(uint32_t)];
    memcpy(data, &num, sizeof(uint32_t));
    memcpy(data + sizeof(uint32_t), public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(data + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES, &ip_port, sizeof(
      IP_Port));
    memcpy(data + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + sizeof(
      IP_Port), &path_num, sizeof(uint32_t));
    *sendback = ping_array_add(&onion_c->announce_ping_array,
      data, sizeof(data));
    if (*sendback == 0)
        return -1;
    return 0;
}
int onion_add_bs_path_node (Onion_Client * onion_c, IP_Port ip_port, const uint8_t * public_key)
Definition at line 41 of file onion_client.c.
References IP::family, i, IP_Port::ip, Node_format::ip_port, last, MAX_PATH_NODES, Onion_Client::path_nodes_bs, Onion_Client::path_nodes_index_bs, and Node_format::public_key.
Referenced by messenger_load_state_callback(), populate_path_nodes_tcp(), and tox_bootstrap().
{
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_PATH_NODES; ++i) {
        if (memcmp(public_key, onion_c->path_nodes_bs[i].
      public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return -1;
    }
    onion_c->path_nodes_bs[onion_c->path_nodes_index_bs %
      MAX_PATH_NODES].ip_port = ip_port;
    memcpy(onion_c->path_nodes_bs[onion_c->path_nodes_index_bs %
      MAX_PATH_NODES].public_key, public_key,
           crypto_box_PUBLICKEYBYTES);
    uint16_t last = onion_c->path_nodes_index_bs;
    ++onion_c->path_nodes_index_bs;
    if (onion_c->path_nodes_index_bs < last)
        onion_c->path_nodes_index_bs = MAX_PATH_NODES + 1;
    return 0;
}
static int onion_add_path_node (Onion_Client * onion_c, IP_Port ip_port, const uint8_t * public_key) [static]
Definition at line 71 of file onion_client.c.
References IP::family, i, IP_Port::ip, Node_format::ip_port, last, MAX_PATH_NODES, Onion_Client::path_nodes, Onion_Client::path_nodes_index, and Node_format::public_key.
Referenced by client_add_to_list(), populate_path_nodes(), and set_path_timeouts().
{
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_PATH_NODES; ++i) {
        if (memcmp(public_key, onion_c->path_nodes[i].
      public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return -1;
    }
    onion_c->path_nodes[onion_c->path_nodes_index %
      MAX_PATH_NODES].ip_port = ip_port;
    memcpy(onion_c->path_nodes[onion_c->path_nodes_index % MAX_PATH_NODES].
      public_key, public_key,
           crypto_box_PUBLICKEYBYTES);
    uint16_t last = onion_c->path_nodes_index;
    ++onion_c->path_nodes_index;
    if (onion_c->path_nodes_index < last)
        onion_c->path_nodes_index = MAX_PATH_NODES + 1;
    return 0;
}
int onion_addfriend (Onion_Client * onion_c, const uint8_t * public_key)
Definition at line 1010 of file onion_client.c.
References Onion_Client::friends_list, i, num, Onion_Client::num_friends, onion_friend_num(), Onion_Friend::real_public_key, realloc_onion_friends(), Onion_Friend::status, Onion_Friend::temp_public_key, and Onion_Friend::temp_secret_key.
Referenced by new_friend_connection(), and START_TEST().
{
    int num = onion_friend_num(onion_c, public_key);
    if (num != -1)
        return num;
    unsigned int i, index = ~0;
    for (i = 0; i < onion_c->num_friends; ++i) {
        if (onion_c->friends_list[i].status == 0) {
            index = i;
            break;
        }
    }
    if (index == (uint32_t)~0) {
        if (realloc_onion_friends(onion_c, onion_c->
      num_friends + 1) == -1)
            return -1;
        index = onion_c->num_friends;
        memset(&(onion_c->friends_list[onion_c->num_friends]), 0, sizeof(
      Onion_Friend));
        ++onion_c->num_friends;
    }
    onion_c->friends_list[index].status = 1;
    memcpy(onion_c->friends_list[index].real_public_key,
      public_key, crypto_box_PUBLICKEYBYTES);
    crypto_box_keypair(onion_c->friends_list[index].temp_public_key, onion_c->
      friends_list[index].temp_secret_key);
    return index;
}
uint16_t onion_backup_nodes (const Onion_Client * onion_c, Node_format * nodes, uint16_t max_num)
Definition at line 100 of file onion_client.c.
References i, MAX_PATH_NODES, Onion_Client::path_nodes, and Onion_Client::path_nodes_index.
Referenced by messenger_save().
{
    unsigned int i;
    if (!max_num)
        return 0;
    unsigned int num_nodes = (onion_c->path_nodes_index <
      MAX_PATH_NODES) ? onion_c->path_nodes_index :
      MAX_PATH_NODES;
    if (num_nodes == 0)
        return 0;
    if (num_nodes < max_num)
        max_num = num_nodes;
    for (i = 0; i < max_num; ++i) {
        nodes[i] = onion_c->path_nodes[(onion_c->path_nodes_index - (1 +
      i)) % num_nodes];
    }
    return max_num;
}
unsigned int onion_connection_status (const Onion_Client * onion_c)
Definition at line 1418 of file onion_client.c.
References Onion_Client::onion_connected, ONION_CONNECTION_SECONDS, and Onion_Client::UDP_connected.
Referenced by connection_status_cb(), do_onion_client(), and tox_self_get_connection_status().
{
    if (onion_c->onion_connected >= ONION_CONNECTION_SECONDS) {
        if (onion_c->UDP_connected) {
            return 2;
        } else {
            return 1;
        }
    }
    return 0;
}
int onion_delfriend (Onion_Client * onion_c, int friend_num)
Definition at line 1046 of file onion_client.c.
References Onion_Client::friends_list, i, Onion_Client::num_friends, realloc_onion_friends(), and Onion_Friend::status.
Referenced by kill_friend_connection().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    //if (onion_c->friends_list[friend_num].know_dht_public_key)
    // DHT_delfriend(onion_c->dht, onion_c->friends_list[friend_num].dht_public_key, 0);
    memset(&(onion_c->friends_list[friend_num]), 0, sizeof(
      Onion_Friend));
    unsigned int i;
    for (i = onion_c->num_friends; i != 0; --i) {
        if (onion_c->friends_list[i - 1].status != 0)
            break;
    }
    if (onion_c->num_friends != i) {
        onion_c->num_friends = i;
        realloc_onion_friends(onion_c, onion_c->num_friends);
    }
    return friend_num;
}
int onion_dht_pk_callback (Onion_Client * onion_c, int friend_num, void(*)(void *data, int32_t number, const uint8_t *dht_public_key) function, void * object, uint32_t number)
Definition at line 1098 of file onion_client.c.
References Onion_Friend::dht_pk_callback, Onion_Friend::dht_pk_callback_number, Onion_Friend::dht_pk_callback_object, Onion_Client::friends_list, and Onion_Client::num_friends.
Referenced by new_friend_connection(), and START_TEST().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    onion_c->friends_list[friend_num].dht_pk_callback = function;
    onion_c->friends_list[friend_num].dht_pk_callback_object = object;
    onion_c->friends_list[friend_num].dht_pk_callback_number = number;
    return 0;
}
int onion_friend_num (const Onion_Client * onion_c, const uint8_t * public_key)
Definition at line 968 of file onion_client.c.
References Onion_Client::friends_list, i, Onion_Client::num_friends, Onion_Friend::real_public_key, and Onion_Friend::status.
Referenced by handle_dhtpk_announce(), and onion_addfriend().
{
    unsigned int i;
    for (i = 0; i < onion_c->num_friends; ++i) {
        if (onion_c->friends_list[i].status == 0)
            continue;
        if (memcmp(public_key, onion_c->friends_list[i].
      real_public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return i;
    }
    return -1;
}
unsigned int onion_getfriend_DHT_pubkey (const Onion_Client * onion_c, int friend_num, uint8_t * dht_key)
Definition at line 1143 of file onion_client.c.
References Onion_Friend::dht_public_key, Onion_Client::friends_list, Onion_Friend::know_dht_public_key, Onion_Client::num_friends, and Onion_Friend::status.
Referenced by onion_getfriendip().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return 0;
    if (onion_c->friends_list[friend_num].status == 0)
        return 0;
    if (!onion_c->friends_list[friend_num].know_dht_public_key)
        return 0;
    memcpy(dht_key, onion_c->friends_list[friend_num].dht_public_key,
      crypto_box_PUBLICKEYBYTES);
    return 1;
}
int onion_getfriendip (const Onion_Client * onion_c, int friend_num, IP_Port * ip_port)
Definition at line 1165 of file onion_client.c.
References Onion_Client::dht, DHT_getfriendip(), and onion_getfriend_DHT_pubkey().
Referenced by START_TEST().
{
    uint8_t dht_public_key[crypto_box_PUBLICKEYBYTES];
    if (onion_getfriend_DHT_pubkey(onion_c, friend_num, dht_public_key) == 0)
        return -1;
    return DHT_getfriendip(onion_c->dht, dht_public_key, ip_port);
}
static int onion_isconnected (const Onion_Client * onion_c) [static]
Definition at line 1376 of file onion_client.c.
References Onion_Client::clients_announce_list, i, Onion_Node::is_stored, is_timeout(), Onion_Client::last_packet_recv, MAX_ONION_CLIENTS, num, ONION_NODE_TIMEOUT, ONION_OFFLINE_TIMEOUT, Onion_Client::path_nodes_index, and Onion_Node::timestamp.
Referenced by do_onion_client().
{
    unsigned int i, num = 0, announced = 0;
    if (is_timeout(onion_c->last_packet_recv,
      ONION_OFFLINE_TIMEOUT))
        return 0;
    if (onion_c->path_nodes_index == 0)
        return 0;
    for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
        if (!is_timeout(onion_c->clients_announce_list[i].
      timestamp, ONION_NODE_TIMEOUT)) {
            ++num;
            if (onion_c->clients_announce_list[i].is_stored) {
                ++announced;
            }
        }
    }
    unsigned int pnodes = onion_c->path_nodes_index;
    if (pnodes > MAX_ONION_CLIENTS) {
        pnodes = MAX_ONION_CLIENTS;
    }
    /* Consider ourselves online if we are announced to half or more nodes
      we are connected to */
    if (num && announced) {
        if ((num / 2) <= announced && (pnodes / 2) <= num)
            return 1;
    }
    return 0;
}
int onion_set_friend_DHT_pubkey (Onion_Client * onion_c, int friend_num, const uint8_t * dht_key)
Definition at line 1115 of file onion_client.c.
References Onion_Friend::dht_public_key, Onion_Client::friends_list, Onion_Friend::know_dht_public_key, Onion_Friend::last_seen, Onion_Client::num_friends, Onion_Friend::status, and unix_time().
Referenced by dht_pk_callback(), and handle_dhtpk_announce().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (onion_c->friends_list[friend_num].status == 0)
        return -1;
    if (onion_c->friends_list[friend_num].know_dht_public_key) {
        if (memcmp(dht_key, onion_c->friends_list[friend_num].
      dht_public_key, crypto_box_PUBLICKEYBYTES) == 0) {
            return -1;
        }
        onion_c->friends_list[friend_num].know_dht_public_key = 0;
    }
    onion_c->friends_list[friend_num].last_seen = unix_time();
    onion_c->friends_list[friend_num].know_dht_public_key = 1;
    memcpy(onion_c->friends_list[friend_num].dht_public_key, dht_key,
      crypto_box_PUBLICKEYBYTES);
    return 0;
}
int onion_set_friend_online (Onion_Client * onion_c, int friend_num, uint8_t is_online)
Definition at line 1185 of file onion_client.c.
References Onion_Client::friends_list, Onion_Friend::is_online, Onion_Friend::last_noreplay, Onion_Friend::last_seen, Onion_Client::num_friends, Onion_Friend::run_count, and unix_time().
Referenced by handle_status().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (is_online == 0 && onion_c->friends_list[friend_num].
      is_online == 1)
        onion_c->friends_list[friend_num].last_seen =
      unix_time();
    onion_c->friends_list[friend_num].is_online = is_online;
    /* This should prevent some clock related issues */
    if (!is_online) {
        onion_c->friends_list[friend_num].last_noreplay = 0;
        onion_c->friends_list[friend_num].run_count = 0;
    }
    return 0;
}
void oniondata_registerhandler (Onion_Client * onion_c, uint8_t byte, oniondata_handler_callback cb, void * object)
Definition at line 1310 of file onion_client.c.
References Onion_Client::function, Onion_Client::object, and Onion_Client::Onion_Data_Handlers.
Referenced by kill_onion_client(), new_onion_client(), and set_friend_request_callback().
{
    onion_c->Onion_Data_Handlers[byte].function = cb;
    onion_c->Onion_Data_Handlers[byte].object = object;
}
static _Bool path_exists (Onion_Client_Paths * onion_paths, uint32_t path_num) [static]
Definition at line 262 of file onion_client.c.
References NUMBER_ONION_PATHS, Onion_Path::path_num, path_timed_out(), and Onion_Client_Paths::paths.
Referenced by do_announce().
{
    if (path_timed_out(onion_paths, path_num))
        return 0;
    return onion_paths->paths[path_num % NUMBER_ONION_PATHS].
      path_num == path_num;
}
static _Bool path_timed_out (Onion_Client_Paths * onion_paths, uint32_t pathnum) [static]
Definition at line 202 of file onion_client.c.
References is_timeout(), Onion_Client_Paths::last_path_success, Onion_Client_Paths::last_path_used_times, NUMBER_ONION_PATHS, ONION_PATH_MAX_LIFETIME, ONION_PATH_MAX_NO_RESPONSE_USES, and Onion_Client_Paths::path_creation_time.
Referenced by path_exists(), and random_path().
{
    pathnum = pathnum % NUMBER_ONION_PATHS;
    return ((onion_paths->last_path_success[pathnum] + ONION_PATH_TIMEOUT < onion_paths->
      last_path_used[pathnum]
             && onion_paths->last_path_used_times[pathnum] >=
      ONION_PATH_MAX_NO_RESPONSE_USES)
            || is_timeout(onion_paths->path_creation_time[pathnum],
      ONION_PATH_MAX_LIFETIME));
}
static void populate_path_nodes (Onion_Client * onion_c) [static]
Definition at line 1204 of file onion_client.c.
References Onion_Client::dht, get_close_nodes(), i, MAX_SENT_NODES, onion_add_path_node(), and make-funny-savefile::public_key.
Referenced by do_onion_client().
{
    Node_format nodes_list[MAX_SENT_NODES];
    uint8_t public_key[crypto_box_PUBLICKEYBYTES];
    uint32_t random_num = rand();
    memcpy(public_key, &random_num, sizeof(random_num));
    unsigned int num_nodes = get_close_nodes(onion_c->dht, public_key, nodes_list, (rand(
      ) % 2) ? AF_INET : AF_INET6, 1, 0);
    unsigned int i;
    for (i = 0; i < num_nodes; ++i) {
        onion_add_path_node(onion_c, nodes_list[i].ip_port, nodes_list[i].public_key);
    }
}
static void populate_path_nodes_tcp (Onion_Client * onion_c) [static]
Definition at line 1219 of file onion_client.c.
References Onion_Client::c, copy_connected_tcp_relays(), i, MAX_SENT_NODES, onion_add_bs_path_node(), and make-funny-savefile::public_key.
Referenced by do_onion_client().
{
    Node_format nodes_list[MAX_SENT_NODES];
    unsigned int num_nodes = copy_connected_tcp_relays(onion_c->
      c, nodes_list, MAX_SENT_NODES);;
    unsigned int i;
    for (i = 0; i < num_nodes; ++i) {
        onion_add_bs_path_node(onion_c, nodes_list[i].ip_port, nodes_list[i].
      public_key);
    }
}
static uint16_t random_nodes_path_onion (const Onion_Client * onion_c, Node_format * nodes, uint16_t max_num) [static]
Definition at line 126 of file onion_client.c.
References Onion_Client::c, Onion_Client::dht, DHT_isconnected(), IP::family, get_random_tcp_con_number(), i, IP_Port::ip, IP::ip4, Node_format::ip_port, MAX_PATH_NODES, Onion_Client::path_nodes, Onion_Client::path_nodes_bs, Onion_Client::path_nodes_index, Onion_Client::path_nodes_index_bs, TCP_FAMILY, and IP4::uint32.
Referenced by random_path().
{
    unsigned int i;
    if (!max_num)
        return 0;
    unsigned int num_nodes = (onion_c->path_nodes_index <
      MAX_PATH_NODES) ? onion_c->path_nodes_index :
      MAX_PATH_NODES;
    //if (DHT_non_lan_connected(onion_c->dht)) {
    if (DHT_isconnected(onion_c->dht)) {
        if (num_nodes == 0)
            return 0;
        for (i = 0; i < max_num; ++i) {
            nodes[i] = onion_c->path_nodes[rand() % num_nodes];
        }
    } else {
        int random_tcp = get_random_tcp_con_number(onion_c->
      c);
        if (random_tcp == -1) {
            return 0;
        }
        if (num_nodes >= 2) {
            nodes[0].ip_port.ip.family = TCP_FAMILY;
            nodes[0].ip_port.ip.ip4.uint32 = random_tcp;
            for (i = 1; i < max_num; ++i) {
                nodes[i] = onion_c->path_nodes[rand() % num_nodes];
            }
        } else {
            unsigned int num_nodes_bs = (onion_c->path_nodes_index_bs <
      MAX_PATH_NODES) ? onion_c->path_nodes_index_bs :
                                        MAX_PATH_NODES;
            if (num_nodes_bs == 0)
                return 0;
            nodes[0].ip_port.ip.family = TCP_FAMILY;
            nodes[0].ip_port.ip.ip4.uint32 = random_tcp;
            for (i = 1; i < max_num; ++i) {
                nodes[i] = onion_c->path_nodes_bs[rand() % num_nodes_bs];
            }
        }
    }
    return max_num;
}
static int random_path (const Onion_Client * onion_c, Onion_Client_Paths * onion_paths, uint32_t pathnum, Onion_Path * path) [static]
Definition at line 220 of file onion_client.c.
References create_onion_path(), Onion_Client::dht, is_path_used(), Onion_Client_Paths::last_path_success, Onion_Client_Paths::last_path_used, Onion_Client_Paths::last_path_used_times, NUMBER_ONION_PATHS, ONION_PATH_FIRST_TIMEOUT, ONION_PATH_LENGTH, ONION_PATH_MAX_NO_RESPONSE_USES, ONION_PATH_TIMEOUT, Onion_Client_Paths::path_creation_time, Onion_Path::path_num, path_timed_out(), Onion_Client_Paths::paths, random_nodes_path_onion(), and unix_time().
Referenced by client_send_announce_request(), and send_onion_data().
{
    if (pathnum == UINT32_MAX) {
        pathnum = rand() % NUMBER_ONION_PATHS;
    } else {
        pathnum = pathnum % NUMBER_ONION_PATHS;
    }
    if (path_timed_out(onion_paths, pathnum)) {
        Node_format nodes[ONION_PATH_LENGTH];
        if (random_nodes_path_onion(onion_c, nodes,
      ONION_PATH_LENGTH) != ONION_PATH_LENGTH)
            return -1;
        int n = is_path_used(onion_paths, nodes);
        if (n == -1) {
            if (create_onion_path(onion_c->dht, &onion_paths->
      paths[pathnum], nodes) == -1)
                return -1;
            onion_paths->last_path_success[pathnum] = unix_time() +
      ONION_PATH_FIRST_TIMEOUT - ONION_PATH_TIMEOUT;
            onion_paths->path_creation_time[pathnum] =
      unix_time();
            onion_paths->last_path_used_times[pathnum] =
      ONION_PATH_MAX_NO_RESPONSE_USES / 2;
            uint32_t path_num = rand();
            path_num /= NUMBER_ONION_PATHS;
            path_num *= NUMBER_ONION_PATHS;
            path_num += pathnum;
            onion_paths->paths[pathnum].path_num = path_num;
        } else {
            pathnum = n;
        }
    }
    ++onion_paths->last_path_used_times[pathnum];
    onion_paths->last_path_used[pathnum] = unix_time();
    memcpy(path, &onion_paths->paths[pathnum], sizeof(Onion_Path));
    return 0;
}
static int realloc_onion_friends (Onion_Client * onion_c, uint32_t num) [static]
Definition at line 988 of file onion_client.c.
References Onion_Client::friends_list.
Referenced by kill_onion_client(), onion_addfriend(), and onion_delfriend().
{
    if (num == 0) {
        free(onion_c->friends_list);
        onion_c->friends_list = NULL;
        return 0;
    }
    Onion_Friend *newonion_friends = realloc(onion_c->friends_list,
      num * sizeof(Onion_Friend));
    if (newonion_friends == NULL)
        return -1;
    onion_c->friends_list = newonion_friends;
    return 0;
}
int recv_tcp_relay_handler (Onion_Client * onion_c, int friend_num, int(*)(void *object, uint32_t number, IP_Port ip_port, const uint8_t *public_key) tcp_relay_node_callback, void * object, uint32_t number)
Definition at line 1078 of file onion_client.c.
References Onion_Client::friends_list, Onion_Client::num_friends, Onion_Friend::tcp_relay_node_callback, tcp_relay_node_callback(), Onion_Friend::tcp_relay_node_callback_number, and Onion_Friend::tcp_relay_node_callback_object.
Referenced by new_friend_connection().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    onion_c->friends_list[friend_num].tcp_relay_node_callback =
      tcp_relay_node_callback;
    onion_c->friends_list[friend_num].tcp_relay_node_callback_object
       = object;
    onion_c->friends_list[friend_num].tcp_relay_node_callback_number
       = number;
    return 0;
}
static int send_dht_dhtpk (const Onion_Client * onion_c, int friend_num, const uint8_t * data, uint16_t length) [static]
Definition at line 858 of file onion_client.c.
References Onion_Client::c, create_request(), CRYPTO_PACKET_DHTPK, DATA_IN_RESPONSE_MIN_SIZE, Onion_Client::dht, Onion_Friend::dht_public_key, encrypt_data(), Onion_Client::friends_list, Onion_Friend::know_dht_public_key, MAX_CRYPTO_REQUEST_SIZE, new_nonce(), nonce, Onion_Client::num_friends, Onion_Friend::real_public_key, route_tofriend(), Net_Crypto::self_public_key, DHT::self_public_key, Net_Crypto::self_secret_key, and DHT::self_secret_key.
Referenced by send_dhtpk_announce().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (!onion_c->friends_list[friend_num].know_dht_public_key)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES];
    new_nonce(nonce);
    uint8_t temp[DATA_IN_RESPONSE_MIN_SIZE + crypto_box_NONCEBYTES + length];
    memcpy(temp, onion_c->c->self_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(temp + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
    int len = encrypt_data(onion_c->friends_list[friend_num].
      real_public_key, onion_c->c->self_secret_key, nonce,
      data,
                           length, temp + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES);
    if ((uint32_t)len + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES != sizeof(temp))
        return -1;
    uint8_t packet[MAX_CRYPTO_REQUEST_SIZE];
    len = create_request(onion_c->dht->self_public_key, onion_c->
      dht->self_secret_key, packet,
                         onion_c->friends_list[friend_num].
      dht_public_key, temp, sizeof(temp), CRYPTO_PACKET_DHTPK);
    if (len == -1)
        return -1;
    return route_tofriend(onion_c->dht, onion_c->friends_list[friend_num].
      dht_public_key, packet, len);
}
static int send_dhtpk_announce (Onion_Client * onion_c, uint16_t friend_num, uint8_t onion_dht_both) [static]
Definition at line 921 of file onion_client.c.
References Onion_Client::c, closelist_nodes(), copy_connected_tcp_relays(), make-funny-savefile::data, Onion_Client::dht, DHTPK_DATA_MAX_LENGTH, DHTPK_DATA_MIN_LENGTH, host_to_net(), MAX_SENT_NODES, Onion_Client::num_friends, ONION_DATA_DHTPK, pack_nodes(), DHT::self_public_key, send_dht_dhtpk(), send_onion_data(), and unix_time().
Referenced by do_friend().
{
    if (friend_num >= onion_c->num_friends)
        return -1;
    uint8_t data[DHTPK_DATA_MAX_LENGTH];
    data[0] = ONION_DATA_DHTPK;
    uint64_t no_replay = unix_time();
    host_to_net((uint8_t *)&no_replay, sizeof(no_replay));
    memcpy(data + 1, &no_replay, sizeof(no_replay));
    memcpy(data + 1 + sizeof(uint64_t), onion_c->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    Node_format nodes[MAX_SENT_NODES];
    uint16_t num_relays = copy_connected_tcp_relays(onion_c->
      c, nodes, (MAX_SENT_NODES / 2));
    uint16_t num_nodes = closelist_nodes(onion_c->dht, &nodes[num_relays],
      MAX_SENT_NODES - num_relays);
    num_nodes += num_relays;
    int nodes_len = 0;
    if (num_nodes != 0) {
        nodes_len = pack_nodes(data + DHTPK_DATA_MIN_LENGTH,
      DHTPK_DATA_MAX_LENGTH - DHTPK_DATA_MIN_LENGTH, nodes,
                               num_nodes);
        if (nodes_len <= 0)
            return -1;
    }
    int num1 = -1, num2 = -1;
    if (onion_dht_both != 1)
        num1 = send_onion_data(onion_c, friend_num, data,
      DHTPK_DATA_MIN_LENGTH + nodes_len);
    if (onion_dht_both != 0)
        num2 = send_dht_dhtpk(onion_c, friend_num, data,
      DHTPK_DATA_MIN_LENGTH + nodes_len);
    if (num1 == -1)
        return num2;
    if (num2 == -1)
        return num1;
    return num1 + num2;
}
int send_onion_data (Onion_Client * onion_c, int friend_num, const uint8_t * data, uint16_t length)
Definition at line 789 of file onion_client.c.
References Onion_Client::c, Onion_Friend::clients_list, create_data_request(), DATA_IN_RESPONSE_MIN_SIZE, Onion_Node::data_public_key, encrypt_data(), Onion_Client::friends_list, i, is_timeout(), MAX_DATA_REQUEST_SIZE, MAX_ONION_CLIENTS, nonce, Onion_Client::num_friends, ONION_MAX_PACKET_SIZE, ONION_NODE_TIMEOUT, Onion_Client::onion_paths_friends, path, random_nonce(), random_path(), Onion_Friend::real_public_key, Net_Crypto::self_public_key, Net_Crypto::self_secret_key, and send_onion_packet_tcp_udp().
Referenced by send_dhtpk_announce(), and send_friend_request_packet().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (length + DATA_IN_RESPONSE_MIN_SIZE >
      MAX_DATA_REQUEST_SIZE)
        return -1;
    if (length == 0)
        return -1;
    unsigned int i, good_nodes[MAX_ONION_CLIENTS], num_good = 0, num_nodes = 0;
    Onion_Node *list_nodes = onion_c->friends_list[friend_num].
      clients_list;
    for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
        if (is_timeout(list_nodes[i].timestamp, ONION_NODE_TIMEOUT))
            continue;
        ++num_nodes;
        if (list_nodes[i].is_stored) {
            good_nodes[num_good] = i;
            ++num_good;
        }
    }
    if (num_good < (num_nodes / 4) + 1)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t packet[DATA_IN_RESPONSE_MIN_SIZE + length];
    memcpy(packet, onion_c->c->self_public_key, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data(onion_c->friends_list[friend_num].
      real_public_key, onion_c->c->self_secret_key, nonce,
      data,
                           length, packet + crypto_box_PUBLICKEYBYTES);
    if ((uint32_t)len + crypto_box_PUBLICKEYBYTES != sizeof(packet))
        return -1;
    unsigned int good = 0;
    for (i = 0; i < num_good; ++i) {
        Onion_Path path;
        if (random_path(onion_c, &onion_c->onion_paths_friends, ~0, &path) ==
       -1)
            continue;
        uint8_t o_packet[ONION_MAX_PACKET_SIZE];
        len = create_data_request(o_packet, sizeof(o_packet), onion_c->
      friends_list[friend_num].real_public_key,
                                  list_nodes[good_nodes[i]].data_public_key, nonce, packet,
      sizeof(packet));
        if (len == -1)
            continue;
        if (send_onion_packet_tcp_udp(onion_c, &path, list_nodes[good_nodes[i]].
      ip_port, o_packet, len) == 0)
            ++good;
    }
    return good;
}
static int send_onion_packet_tcp_udp (const Onion_Client * onion_c, const Onion_Path * path, IP_Port dest, const uint8_t * data, uint16_t length) [static]
Definition at line 311 of file onion_client.c.
References Onion_Client::c, create_onion_packet(), create_onion_packet_tcp(), IP::family, IP_Port::ip, IP::ip4, Onion_Path::ip_port1, Onion_Client::net, ONION_MAX_PACKET_SIZE, send_tcp_onion_request(), sendpacket(), TCP_FAMILY, and IP4::uint32.
Referenced by client_send_announce_request(), and send_onion_data().
{
    if (path->ip_port1.ip.family == AF_INET || path->ip_port1.
      ip.family == AF_INET6) {
        uint8_t packet[ONION_MAX_PACKET_SIZE];
        int len = create_onion_packet(packet, sizeof(packet), path, dest,
      data, length);
        if (len == -1)
            return -1;
        if (sendpacket(onion_c->net, path->ip_port1, packet, len) != len)
            return -1;
        return 0;
    } else if (path->ip_port1.ip.family == TCP_FAMILY) {
        uint8_t packet[ONION_MAX_PACKET_SIZE];
        int len = create_onion_packet_tcp(packet, sizeof(packet), path, dest,
      data, length);
        if (len == -1)
            return -1;
        return send_tcp_onion_request(onion_c->c, path->
      ip_port1.ip.ip4.uint32, packet, len);
    } else {
        return -1;
    }
}
static uint32_t set_path_timeouts (Onion_Client * onion_c, uint32_t num, uint32_t path_num) [static]
Definition at line 273 of file onion_client.c.
References i, Onion_Client_Paths::last_path_success, Onion_Client_Paths::last_path_used_times, Onion_Client::num_friends, NUMBER_ONION_PATHS, onion_add_path_node(), ONION_PATH_LENGTH, onion_path_to_nodes(), Onion_Client::onion_paths_friends, Onion_Client::onion_paths_self, Onion_Path::path_num, Onion_Client_Paths::paths, make-funny-savefile::public_key, and unix_time().
Referenced by client_add_to_list().
{
    if (num > onion_c->num_friends)
        return -1;
    Onion_Client_Paths *onion_paths;
    if (num == 0) {
        onion_paths = &onion_c->onion_paths_self;
    } else {
        onion_paths = &onion_c->onion_paths_friends;
    }
    if (onion_paths->paths[path_num % NUMBER_ONION_PATHS].
      path_num == path_num) {
        onion_paths->last_path_success[path_num %
      NUMBER_ONION_PATHS] = unix_time();
        onion_paths->last_path_used_times[path_num %
      NUMBER_ONION_PATHS] = 0;
        Node_format nodes[ONION_PATH_LENGTH];
        if (onion_path_to_nodes(nodes, ONION_PATH_LENGTH, &onion_paths
      ->paths[path_num % NUMBER_ONION_PATHS]) == 0) {
            unsigned int i;
            for (i = 0; i < ONION_PATH_LENGTH; ++i) {
                onion_add_path_node(onion_c, nodes[i].ip_port, nodes[i].
      public_key);
            }
        }
        return path_num;
    }
    return ~0;
}
Variable Documentation
uint8_t cmp_public_key[crypto_box_PUBLICKEYBYTES] [static]
Definition at line 443 of file onion_client.c.
Referenced by client_add_to_list(), and cmp_entry().