toxcore/Messenger.h File Reference
#include `friend_requests.h`
*
#include `friend_connection.h`
*
Data Structures
struct Messenger_Options
struct Receipts
struct File_Transfers
struct Friend
struct Messenger
Macros
#define MAX_NAME_LENGTH 128
#define MAX_STATUSMESSAGE_LENGTH 1007
#define FRIEND_ADDRESS_SIZE (crypto_box_PUBLICKEYBYTES + sizeof(uint32_t) + sizeof(uint16_t))
#define PACKET_ID_ONLINE 24
#define PACKET_ID_OFFLINE 25
#define PACKET_ID_NICKNAME 48
#define PACKET_ID_STATUSMESSAGE 49
#define PACKET_ID_USERSTATUS 50
#define PACKET_ID_TYPING 51
#define PACKET_ID_MESSAGE 64
#define PACKET_ID_ACTION (PACKET_ID_MESSAGE + MESSAGE_ACTION) /* 65 */
#define PACKET_ID_MSI 69
#define PACKET_ID_FILE_SENDREQUEST 80
#define PACKET_ID_FILE_CONTROL 81
#define PACKET_ID_FILE_DATA 82
#define PACKET_ID_INVITE_GROUPCHAT 96
#define PACKET_ID_ONLINE_PACKET 97
#define PACKET_ID_DIRECT_GROUPCHAT 98
#define PACKET_ID_MESSAGE_GROUPCHAT 99
#define PACKET_ID_LOSSY_GROUPCHAT 199
#define PACKET_ID_LOSSLESS_RANGE_START 160
#define PACKET_ID_LOSSLESS_RANGE_SIZE 32
#define PACKET_LOSSY_AV_RESERVED 8 /* Number of lossy packet types at start of range reserved for A/V. */
#define FRIENDREQUEST_TIMEOUT 5;
#define FILE_ID_LENGTH 32
#define MAX_CONCURRENT_FILE_PIPES 256
#define NUM_SAVED_TCP_RELAYS 8
Typedefs
typedef struct Messenger Messenger
Enumerations
enum { MESSAGE_NORMAL,
MESSAGE_ACTION
 }
enum {
*
NOFRIEND,
FRIEND_ADDED,
FRIEND_REQUESTED,
FRIEND_CONFIRMED,
*
FRIEND_ONLINE
 }
enum {
*
FAERR_TOOLONG = -1,
FAERR_NOMESSAGE = -2,
FAERR_OWNKEY = -3,
FAERR_ALREADYSENT = -4,
*
FAERR_BADCHECKSUM = -6,
FAERR_SETNEWNOSPAM = -7,
FAERR_NOMEM = -8
 }
enum { CONNECTION_NONE,
CONNECTION_TCP,
CONNECTION_UDP,
CONNECTION_UNKNOWN
 }
enum USERSTATUS { USERSTATUS_NONE,
USERSTATUS_AWAY,
USERSTATUS_BUSY,
USERSTATUS_INVALID
 }
enum { FILESTATUS_NONE,
FILESTATUS_NOT_ACCEPTED,
FILESTATUS_TRANSFERRING,
FILESTATUS_FINISHED
 }
enum { FILE_PAUSE_NOT,
FILE_PAUSE_US,
FILE_PAUSE_OTHER,
FILE_PAUSE_BOTH
 }
enum { FILECONTROL_ACCEPT,
FILECONTROL_PAUSE,
FILECONTROL_KILL,
FILECONTROL_SEEK
 }
enum { FILEKIND_DATA,
FILEKIND_AVATAR
 }
enum { MESSENGER_ERROR_NONE,
MESSENGER_ERROR_PORT,
MESSENGER_ERROR_TCP_SERVER,
MESSENGER_ERROR_OTHER
 }
Functions
void getaddress (const Messenger *m, uint8_t *address)
int32_t m_addfriend (Messenger *m, const uint8_t *address, const uint8_t *data, uint16_t length)
int32_t m_addfriend_norequest (Messenger *m, const uint8_t *real_pk)
int32_t getfriend_id (const Messenger *m, const uint8_t *real_pk)
int get_real_pk (const Messenger *m, int32_t friendnumber, uint8_t *real_pk)
int getfriendcon_id (const Messenger *m, int32_t friendnumber)
int m_delfriend (Messenger *m, int32_t friendnumber)
int m_get_friend_connectionstatus (const Messenger *m, int32_t friendnumber)
int m_friend_exists (const Messenger *m, int32_t friendnumber)
int m_send_message_generic (Messenger *m, int32_t friendnumber, uint8_t type, const uint8_t *message, uint32_t length, uint32_t *message_id)
int setfriendname (Messenger *m, int32_t friendnumber, const uint8_t *name, uint16_t length)
int setname (Messenger *m, const uint8_t *name, uint16_t length)
uint16_t getself_name (const Messenger *m, uint8_t *name)
int getname (const Messenger *m, int32_t friendnumber, uint8_t *name)
int m_get_name_size (const Messenger *m, int32_t friendnumber)
int m_get_self_name_size (const Messenger *m)
int m_set_statusmessage (Messenger *m, const uint8_t *status, uint16_t length)
int m_set_userstatus (Messenger *m, uint8_t status)
int m_get_statusmessage_size (const Messenger *m, int32_t friendnumber)
int m_get_self_statusmessage_size (const Messenger *m)
int m_copy_statusmessage (const Messenger *m, int32_t friendnumber, uint8_t *buf, uint32_t maxlen)
int m_copy_self_statusmessage (const Messenger *m, uint8_t *buf)
uint8_t m_get_userstatus (const Messenger *m, int32_t friendnumber)
uint8_t m_get_self_userstatus (const Messenger *m)
uint64_t m_get_last_online (const Messenger *m, int32_t friendnumber)
int m_set_usertyping (Messenger *m, int32_t friendnumber, uint8_t is_typing)
int m_get_istyping (const Messenger *m, int32_t friendnumber)
void m_callback_friendrequest (Messenger *m, void(*function)(Messenger *m, const uint8_t *, const uint8_t *, size_t, void *), void *userdata)
void m_callback_friendmessage (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, const uint8_t *, size_t, void *), void *userdata)
void m_callback_namechange (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, size_t, void *), void *userdata)
void m_callback_statusmessage (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, size_t, void *), void *userdata)
void m_callback_userstatus (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, void *), void *userdata)
void m_callback_typingchange (Messenger *m, void(*function)(Messenger *m, uint32_t, _Bool, void *), void *userdata)
void m_callback_read_receipt (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, void *), void *userdata)
void m_callback_connectionstatus (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, void *), void *userdata)
void m_callback_connectionstatus_internal_av (Messenger *m, void(*function)(Messenger *m, uint32_t, uint8_t, void *), void *userdata)
void m_callback_core_connection (Messenger *m, void(*function)(Messenger *m, unsigned int, void *), void *userdata)
void m_callback_group_invite (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, uint16_t))
int send_group_invite_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint16_t length)
void callback_file_sendrequest (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *), void *userdata)
void callback_file_control (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, unsigned int, void *), void *userdata)
void callback_file_data (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *), void *userdata)
void callback_file_reqchunk (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint64_t, size_t, void *), void *userdata)
int file_get_id (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint8_t *file_id)
long int new_filesender (const Messenger *m, int32_t friendnumber, uint32_t file_type, uint64_t filesize, const uint8_t *file_id, const uint8_t *filename, uint16_t filename_length)
int file_control (const Messenger *m, int32_t friendnumber, uint32_t filenumber, unsigned int control)
int file_seek (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint64_t position)
int file_data (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t *data, uint16_t length)
uint64_t file_dataremaining (const Messenger *m, int32_t friendnumber, uint8_t filenumber, uint8_t send_receive)
void m_callback_msi_packet (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, uint16_t, void *), void *userdata)
int m_msi_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint16_t length)
int m_callback_rtp_packet (Messenger *m, int32_t friendnumber, uint8_t byte, int(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t len, void *object), void *object)
void custom_lossy_packet_registerhandler (Messenger *m, void(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object), void *object)
int send_custom_lossy_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint32_t length)
void custom_lossless_packet_registerhandler (Messenger *m, void(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object), void *object)
int send_custom_lossless_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint32_t length)
Messenger * new_messenger (Messenger_Options *options, unsigned int *error)
void kill_messenger (Messenger *m)
void do_messenger (Messenger *m)
uint32_t messenger_run_interval (const Messenger *m)
uint32_t messenger_size (const Messenger *m)
void messenger_save (const Messenger *m, uint8_t *data)
int messenger_load (Messenger *m, const uint8_t *data, uint32_t length)
uint32_t count_friendlist (const Messenger *m)
uint32_t copy_friendlist (const Messenger *m, uint32_t *out_list, uint32_t list_size)
Macro Definition Documentation
#define FILE_ID_LENGTH 32
Definition at line 128 of file Messenger.h.
Referenced by file_get_id(), file_sendrequest(), handle_packet(), new_filesender(), and tox_file_send().
#define FRIEND_ADDRESS_SIZE (crypto_box_PUBLICKEYBYTES + sizeof(uint32_t) + sizeof(uint16_t))
Definition at line 37 of file Messenger.h.
Referenced by friends_list_load(), getaddress(), m_addfriend(), main(), and tox_decrypt_dns3_TXT().
#define FRIENDREQUEST_TIMEOUT 5;
Definition at line 107 of file Messenger.h.
Referenced by m_addfriend().
#define MAX_CONCURRENT_FILE_PIPES 256
Definition at line 156 of file Messenger.h.
Referenced by break_files(), do_reqchunk_filecb(), file_control(), file_data(), file_get_id(), file_seek(), handle_packet(), and new_filesender().
#define MAX_NAME_LENGTH 128
Definition at line 32 of file Messenger.h.
Referenced by group_name_send(), group_title_get(), group_title_send(), handle_packet(), handle_send_peers(), m_sendname(), messenger_load_state_callback(), setfriendname(), setname(), setnick(), settitle(), and START_TEST().
#define MAX_STATUSMESSAGE_LENGTH 1007
Definition at line 34 of file Messenger.h.
Referenced by handle_packet(), m_set_statusmessage(), messenger_load_state_callback(), set_friend_statusmessage(), and START_TEST().
#define NUM_SAVED_TCP_RELAYS 8
Definition at line 236 of file Messenger.h.
Referenced by do_messenger(), messenger_load_state_callback(), messenger_save(), and messenger_size().
#define PACKET_ID_ACTION (PACKET_ID_MESSAGE + MESSAGE_ACTION) /* 65 */
Definition at line 52 of file Messenger.h.
Referenced by group_action_send(), handle_message_packet_group(), and handle_packet().
#define PACKET_ID_DIRECT_GROUPCHAT 98
Definition at line 59 of file Messenger.h.
Referenced by handle_packet(), send_peer_kill(), send_peer_query(), and send_peers().
#define PACKET_ID_FILE_CONTROL 81
Definition at line 55 of file Messenger.h.
Referenced by handle_packet(), and send_file_control_packet().
#define PACKET_ID_FILE_DATA 82
Definition at line 56 of file Messenger.h.
Referenced by handle_packet(), and send_file_data_packet().
#define PACKET_ID_FILE_SENDREQUEST 80
Definition at line 54 of file Messenger.h.
Referenced by file_sendrequest(), and handle_packet().
#define PACKET_ID_INVITE_GROUPCHAT 96
Definition at line 57 of file Messenger.h.
Referenced by handle_packet(), and send_group_invite_packet().
#define PACKET_ID_LOSSLESS_RANGE_SIZE 32
Definition at line 65 of file Messenger.h.
Referenced by handle_custom_lossless_packet(), and send_custom_lossless_packet().
#define PACKET_ID_LOSSLESS_RANGE_START 160
Definition at line 64 of file Messenger.h.
Referenced by handle_custom_lossless_packet(), and send_custom_lossless_packet().
#define PACKET_ID_LOSSY_GROUPCHAT 199
Definition at line 61 of file Messenger.h.
Referenced by handle_lossy(), and send_lossy_all_close().
#define PACKET_ID_MESSAGE 64
Definition at line 51 of file Messenger.h.
Referenced by group_message_send(), handle_message_packet_group(), handle_packet(), and m_send_message_generic().
#define PACKET_ID_MESSAGE_GROUPCHAT 99
Definition at line 60 of file Messenger.h.
Referenced by handle_packet(), and send_message_all_close().
#define PACKET_ID_MSI 69
Definition at line 53 of file Messenger.h.
Referenced by handle_packet(), and m_msi_packet().
#define PACKET_ID_NICKNAME 48
Definition at line 47 of file Messenger.h.
Referenced by handle_packet(), and m_sendname().
#define PACKET_ID_OFFLINE 25
Definition at line 46 of file Messenger.h.
Referenced by handle_packet(), and send_offline_packet().
#define PACKET_ID_ONLINE 24
Definition at line 45 of file Messenger.h.
Referenced by handle_packet(), and send_online_packet().
#define PACKET_ID_ONLINE_PACKET 97
Definition at line 58 of file Messenger.h.
Referenced by handle_packet(), and send_packet_online().
#define PACKET_ID_STATUSMESSAGE 49
Definition at line 48 of file Messenger.h.
Referenced by handle_packet(), and send_statusmessage().
#define PACKET_ID_TYPING 51
Definition at line 50 of file Messenger.h.
Referenced by handle_packet(), and send_user_istyping().
#define PACKET_ID_USERSTATUS 50
Definition at line 49 of file Messenger.h.
Referenced by handle_packet(), and send_userstatus().
#define PACKET_LOSSY_AV_RESERVED 8 /* Number of lossy packet types at start of range reserved for A/V. */
Definition at line 66 of file Messenger.h.
Referenced by handle_custom_lossy_packet(), m_callback_rtp_packet(), and tox_friend_send_lossy_packet().
Typedef Documentation
typedef struct Messenger Messenger
Definition at line 171 of file Messenger.h.
Enumeration Type Documentation
anonymous enum
Enumerator
MESSAGE_NORMAL
MESSAGE_ACTION
Definition at line 39 of file Messenger.h.
     {
    MESSAGE_NORMAL,
    MESSAGE_ACTION
};
anonymous enum
Enumerator
NOFRIEND
FRIEND_ADDED
FRIEND_REQUESTED
FRIEND_CONFIRMED
FRIEND_ONLINE
Definition at line 84 of file Messenger.h.
     {
    NOFRIEND,
    FRIEND_ADDED,
    FRIEND_REQUESTED,
    FRIEND_CONFIRMED,
    FRIEND_ONLINE,
};
anonymous enum
Enumerator
FAERR_TOOLONG
FAERR_NOMESSAGE
FAERR_OWNKEY
FAERR_ALREADYSENT
FAERR_BADCHECKSUM
FAERR_SETNEWNOSPAM
FAERR_NOMEM
Definition at line 95 of file Messenger.h.
     {
    FAERR_TOOLONG = -1,
    FAERR_NOMESSAGE = -2,
    FAERR_OWNKEY = -3,
    FAERR_ALREADYSENT = -4,
    FAERR_BADCHECKSUM = -6,
    FAERR_SETNEWNOSPAM = -7,
    FAERR_NOMEM = -8
};
anonymous enum
Enumerator
CONNECTION_NONE
CONNECTION_TCP
CONNECTION_UDP
CONNECTION_UNKNOWN
Definition at line 109 of file Messenger.h.
     {
    CONNECTION_NONE,
    CONNECTION_TCP,
    CONNECTION_UDP,
    CONNECTION_UNKNOWN
};
anonymous enum
Enumerator
FILESTATUS_NONE
FILESTATUS_NOT_ACCEPTED
FILESTATUS_TRANSFERRING
FILESTATUS_FINISHED
Definition at line 140 of file Messenger.h.
     {
    FILESTATUS_NONE,
    FILESTATUS_NOT_ACCEPTED,
    FILESTATUS_TRANSFERRING,
    //FILESTATUS_BROKEN,
    FILESTATUS_FINISHED
};
anonymous enum
Enumerator
FILE_PAUSE_NOT
FILE_PAUSE_US
FILE_PAUSE_OTHER
FILE_PAUSE_BOTH
Definition at line 148 of file Messenger.h.
     {
    FILE_PAUSE_NOT,
    FILE_PAUSE_US,
    FILE_PAUSE_OTHER,
    FILE_PAUSE_BOTH
};
anonymous enum
Enumerator
FILECONTROL_ACCEPT
FILECONTROL_PAUSE
FILECONTROL_KILL
FILECONTROL_SEEK
Definition at line 158 of file Messenger.h.
     {
    FILECONTROL_ACCEPT,
    FILECONTROL_PAUSE,
    FILECONTROL_KILL,
    FILECONTROL_SEEK
};
anonymous enum
Enumerator
FILEKIND_DATA
FILEKIND_AVATAR
Definition at line 165 of file Messenger.h.
     {
    FILEKIND_DATA,
    FILEKIND_AVATAR
};
anonymous enum
Enumerator
MESSENGER_ERROR_NONE
MESSENGER_ERROR_PORT
MESSENGER_ERROR_TCP_SERVER
MESSENGER_ERROR_OTHER
Definition at line 729 of file Messenger.h.
     {
    MESSENGER_ERROR_NONE,
    MESSENGER_ERROR_PORT,
    MESSENGER_ERROR_TCP_SERVER,
    MESSENGER_ERROR_OTHER
};
enum USERSTATUS
Enumerator
USERSTATUS_NONE
USERSTATUS_AWAY
USERSTATUS_BUSY
USERSTATUS_INVALID
Definition at line 120 of file Messenger.h.
             {
    USERSTATUS_NONE,
    USERSTATUS_AWAY,
    USERSTATUS_BUSY,
    USERSTATUS_INVALID
}
Function Documentation
void callback_file_control (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 954 of file Messenger.c.
References Messenger::file_filecontrol, and Messenger::file_filecontrol_userdata.
Referenced by tox_callback_file_recv_control().
{
    m->file_filecontrol = function;
    m->file_filecontrol_userdata = userdata;
}
void callback_file_data (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 966 of file Messenger.c.
References Messenger::file_filedata, and Messenger::file_filedata_userdata.
Referenced by tox_callback_file_recv_chunk().
{
    m->file_filedata = function;
    m->file_filedata_userdata = userdata;
}
void callback_file_reqchunk (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint64_t, size_t, void *) function, void * userdata)
Definition at line 978 of file Messenger.c.
References Messenger::file_reqchunk, and Messenger::file_reqchunk_userdata.
Referenced by tox_callback_file_chunk_request().
{
    m->file_reqchunk = function;
    m->file_reqchunk_userdata = userdata;
}
void callback_file_sendrequest (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 942 of file Messenger.c.
References Messenger::file_sendrequest, and Messenger::file_sendrequest_userdata.
Referenced by tox_callback_file_recv().
{
    m->file_sendrequest = function;
    m->file_sendrequest_userdata = userdata;
}
uint32_t copy_friendlist (const Messenger * m, uint32_t * out_list, uint32_t list_size)
Definition at line 2784 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, and Friend::status.
Referenced by tox_self_get_friend_list().
{
    if (!out_list)
        return 0;
    if (m->numfriends == 0) {
        return 0;
    }
    uint32_t i;
    uint32_t ret = 0;
    for (i = 0; i < m->numfriends; i++) {
        if (ret >= list_size) {
            break; /* Abandon ship */
        }
        if (m->friendlist[i].status > 0) {
            out_list[ret] = i;
            ret++;
        }
    }
    return ret;
}
uint32_t count_friendlist (const Messenger * m)
Definition at line 2765 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, and Friend::status.
Referenced by saved_friendslist_size(), and tox_self_get_friend_list_size().
{
    uint32_t ret = 0;
    uint32_t i;
    for (i = 0; i < m->numfriends; i++) {
        if (m->friendlist[i].status > 0) {
            ret++;
        }
    }
    return ret;
}
void custom_lossless_packet_registerhandler (Messenger * m, void(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object) packet_handler_callback, void * object)
Definition at line 1707 of file Messenger.c.
References Messenger::lossless_packethandler, and Messenger::lossless_packethandler_userdata.
Referenced by tox_callback_friend_lossless_packet().
{
    m->lossless_packethandler = packet_handler_callback;
    m->lossless_packethandler_userdata = object;
}
void custom_lossy_packet_registerhandler (Messenger * m, void(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object) packet_handler_callback, void * object)
Definition at line 1637 of file Messenger.c.
References Messenger::lossy_packethandler, and Messenger::lossy_packethandler_userdata.
Referenced by tox_callback_friend_lossy_packet().
{
    m->lossy_packethandler = packet_handler_callback;
    m->lossy_packethandler_userdata = object;
}
void do_messenger (Messenger * m)
Definition at line 2280 of file Messenger.c.
References add_tcp_relay(), Client_data::assoc4, DHT_Friend::client_list, DHT::close_clientlist, connection_status_cb(), Messenger::dht, do_DHT(), do_friend_connections(), do_friends(), do_net_crypto(), do_onion_client(), do_TCP_server(), IP::family, Messenger::fr_c, Messenger::friendlist, DHT::friends_list, Messenger::has_added_relays, i, id_equal(), IP_Port::ip, IP::ip4, ip_isset(), ip_ntoa(), IPPTsPng::ip_port, Node_format::ip_port, IPPTsPng::last_pinged, LCLIENT_LIST, Messenger::loaded_relays, LOGGER_TRACE, MAX_FRIEND_CLIENTS, Friend::name, Messenger::net, Messenger::net_crypto, networking_poll(), DHT::num_friends, NUM_SAVED_TCP_RELAYS, Messenger::numfriends, Messenger::onion_c, Messenger::options, IP_Port::port, Client_data::public_key, DHT_Friend::public_key, TCP_Server::public_key, Node_format::public_key, Friend::real_pk, Messenger::tcp_server, Messenger_Options::tcp_server_port, Messenger_Options::udp_disabled, IP4::uint32, unix_time(), and unix_time_update().
Referenced by main(), and tox_iterate().
{
    // Add the TCP relays, but only if this is the first time calling do_messenger
    if (m->has_added_relays == 0) {
        m->has_added_relays = 1;
        int i;
        for (i = 0; i < NUM_SAVED_TCP_RELAYS; ++i) {
            add_tcp_relay(m->net_crypto, m->loaded_relays[i].
      ip_port, m->loaded_relays[i].public_key);
        }
        if (m->tcp_server) {
            /* Add self tcp server. */
            IP_Port local_ip_port;
            local_ip_port.port = m->options.tcp_server_port;
            local_ip_port.ip.family = AF_INET;
            local_ip_port.ip.ip4.uint32 = INADDR_LOOPBACK;
            add_tcp_relay(m->net_crypto, local_ip_port, m->
      tcp_server->public_key);
        }
    }
    unix_time_update();
    if (!m->options.udp_disabled) {
        networking_poll(m->net);
        do_DHT(m->dht);
    }
    if (m->tcp_server) {
        do_TCP_server(m->tcp_server);
    }
    do_net_crypto(m->net_crypto);
    do_onion_client(m->onion_c);
    do_friend_connections(m->fr_c);
    do_friends(m);
    connection_status_cb(m);
#ifdef LOGGING
    if (unix_time() > lastdump + DUMPING_CLIENTS_FRIENDS_EVERY_N_SECONDS) {
#ifdef ENABLE_ASSOC_DHT
        Assoc_status(m->dht->assoc);
#endif
        lastdump = unix_time();
        uint32_t client, last_pinged;
        for (client = 0; client < LCLIENT_LIST; client++) {
            Client_data *cptr = &m->dht->close_clientlist[client];
            IPPTsPng *assoc = NULL;
            uint32_t a;
            for (a = 0, assoc = &cptr->assoc4; a < 2; a++, assoc = &cptr->assoc6)
                if (ip_isset(&assoc->ip_port.ip)) {
                    last_pinged = lastdump - assoc->last_pinged;
                    if (last_pinged > 999)
                        last_pinged = 999;
                    LOGGER_TRACE("C[%2u] %s:%u [%3u] %s",
                                 client, ip_ntoa(&assoc->ip_port.
      ip), ntohs(assoc->ip_port.port),
                                 last_pinged, ID2String(cptr->public_key));
                }
        }
        uint32_t friend, dhtfriend;
        /* dht contains additional "friends" (requests) */
        uint32_t num_dhtfriends = m->dht->num_friends;
        int32_t m2dht[num_dhtfriends];
        int32_t dht2m[num_dhtfriends];
        for (friend = 0; friend < num_dhtfriends; friend++) {
            m2dht[friend] = -1;
            dht2m[friend] = -1;
            if (friend >= m->numfriends)
                continue;
            for (dhtfriend = 0; dhtfriend < m->dht->num_friends; dhtfriend++)
                if (id_equal(m->friendlist[friend].real_pk, m->
      dht->friends_list[dhtfriend].public_key)) {
                    m2dht[friend] = dhtfriend;
                    break;
                }
        }
        for (friend = 0; friend < num_dhtfriends; friend++)
            if (m2dht[friend] >= 0)
                dht2m[m2dht[friend]] = friend;
        if (m->numfriends != m->dht->num_friends) {
            LOGGER_TRACE("Friend num in DHT %u != friend num in msger %u\n", m->
      dht->num_friends, m->numfriends);
        }
        Friend *msgfptr;
        DHT_Friend *dhtfptr;
        for (friend = 0; friend < num_dhtfriends; friend++) {
            if (dht2m[friend] >= 0)
                msgfptr = &m->friendlist[dht2m[friend]];
            else
                msgfptr = NULL;
            dhtfptr = &m->dht->friends_list[friend];
            if (msgfptr) {
                LOGGER_TRACE("F[%2u:%2u] <%s> %s",
                             dht2m[friend], friend, msgfptr->name,
                             ID2String(msgfptr->real_pk));
            } else {
                LOGGER_TRACE("F[--:%2u] %s", friend, ID2String(dhtfptr->
      public_key));
            }
            for (client = 0; client < MAX_FRIEND_CLIENTS; client++) {
                Client_data *cptr = &dhtfptr->client_list[client];
                IPPTsPng *assoc = NULL;
                uint32_t a;
                for (a = 0, assoc = &cptr->assoc4; a < 2; a++, assoc = &cptr->assoc6)
                    if (ip_isset(&assoc->ip_port.ip)) {
                        last_pinged = lastdump - assoc->last_pinged;
                        if (last_pinged > 999)
                            last_pinged = 999;
                        LOGGER_TRACE("F[%2u] => C[%2u] %s:%u [%3u] %s",
                                     friend, client, ip_ntoa(&assoc->
      ip_port.ip),
                                     ntohs(assoc->ip_port.port), last_pinged,
                                     ID2String(cptr->public_key));
                    }
            }
        }
    }
#endif /* LOGGING */
}
int file_control (const Messenger * m, int32_t friendnumber, uint32_t filenumber, unsigned int control)
Definition at line 1137 of file Messenger.c.
References FILE_PAUSE_OTHER, FILE_PAUSE_US, Friend::file_receiving, Friend::file_sending, FILECONTROL_ACCEPT, FILECONTROL_KILL, FILECONTROL_PAUSE, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, FILESTATUS_TRANSFERRING, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, MAX_CONCURRENT_FILE_PIPES, Friend::num_sending_files, File_Transfers::paused, send_file_control_packet(), File_Transfers::status, and Friend::status.
Referenced by tox_file_control().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        send_receive = 0;
        temp_filenum = filenumber;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -3;
    if (control > FILECONTROL_KILL)
        return -4;
    if (control == FILECONTROL_PAUSE && ((ft->paused &
      FILE_PAUSE_US) || ft->status != FILESTATUS_TRANSFERRING))
        return -5;
    if (control == FILECONTROL_ACCEPT) {
        if (ft->status == FILESTATUS_TRANSFERRING) {
            if (!(ft->paused & FILE_PAUSE_US)) {
                if (ft->paused & FILE_PAUSE_OTHER) {
                    return -6;
                } else {
                    return -7;
                }
            }
        } else {
            if (ft->status != FILESTATUS_NOT_ACCEPTED)
                return -7;
            if (!send_receive)
                return -6;
        }
    }
    if (send_file_control_packet(m, friendnumber, send_receive, file_number,
      control, 0, 0)) {
        if (control == FILECONTROL_KILL) {
            ft->status = FILESTATUS_NONE;
            if (send_receive == 0) {
                --m->friendlist[friendnumber].num_sending_files;
            }
        } else if (control == FILECONTROL_PAUSE) {
            ft->paused |= FILE_PAUSE_US;
        } else if (control == FILECONTROL_ACCEPT) {
            ft->status = FILESTATUS_TRANSFERRING;
            if (ft->paused & FILE_PAUSE_US) {
                ft->paused ^= FILE_PAUSE_US;
            }
        }
    } else {
        return -8;
    }
    return 0;
}
int file_data (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t * data, uint16_t length)
Definition at line 1318 of file Messenger.c.
References crypto_num_free_sendqueue_slots(), Friend::file_sending, FILESTATUS_FINISHED, FILESTATUS_TRANSFERRING, Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, File_Transfers::last_packet_number, MAX_CONCURRENT_FILE_PIPES, MAX_FILE_DATA_SIZE, MIN_SLOTS_FREE, Messenger::net_crypto, File_Transfers::requested, send_file_data_packet(), File_Transfers::size, File_Transfers::slots_allocated, File_Transfers::status, Friend::status, and File_Transfers::transferred.
Referenced by do_reqchunk_filecb(), handle_packet(), and tox_file_send_chunk().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    if (filenumber >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    struct File_Transfers *ft = &m->friendlist[friendnumber].
      file_sending[filenumber];
    if (ft->status != FILESTATUS_TRANSFERRING)
        return -4;
    if (length > MAX_FILE_DATA_SIZE)
        return -5;
    if (ft->size - ft->transferred < length) {
        return -5;
    }
    if (ft->size != UINT64_MAX && length != MAX_FILE_DATA_SIZE && (ft->
      transferred + length) != ft->size) {
        return -5;
    }
    if (position != ft->transferred || (ft->requested <= position && ft->
      size != 0)) {
        return -7;
    }
    /* Prevent file sending from filling up the entire buffer preventing messages from being sent. TODO:
       remove */
    if (crypto_num_free_sendqueue_slots(m->
      net_crypto, friend_connection_crypt_connection_id(m->
      fr_c,
                                        m->friendlist[friendnumber].
      friendcon_id)) < MIN_SLOTS_FREE)
        return -6;
    int64_t ret = send_file_data_packet(m, friendnumber, filenumber,
      data, length);
    if (ret != -1) {
        //TODO record packet ids to check if other received complete file.
        ft->transferred += length;
        if (ft->slots_allocated) {
            --ft->slots_allocated;
        }
        if (length != MAX_FILE_DATA_SIZE || ft->size == ft->
      transferred) {
            ft->status = FILESTATUS_FINISHED;
            ft->last_packet_number = ret;
        }
        return 0;
    }
    return -6;
}
uint64_t file_dataremaining (const Messenger * m, int32_t friendnumber, uint8_t filenumber, uint8_t send_receive)
Definition at line 1384 of file Messenger.c.
References Friend::file_receiving, Friend::file_sending, FILESTATUS_NONE, friend_not_valid(), Messenger::friendlist, File_Transfers::size, File_Transfers::status, and File_Transfers::transferred.
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    if (send_receive == 0) {
        if (m->friendlist[friendnumber].file_sending[filenumber].
      status == FILESTATUS_NONE)
            return 0;
        return m->friendlist[friendnumber].file_sending[filenumber].
      size -
               m->friendlist[friendnumber].file_sending[filenumber].
      transferred;
    } else {
        if (m->friendlist[friendnumber].file_receiving[filenumber].
      status == FILESTATUS_NONE)
            return 0;
        return m->friendlist[friendnumber].file_receiving[filenumber].
      size -
               m->friendlist[friendnumber].file_receiving[filenumber].
      transferred;
    }
}
int file_get_id (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint8_t * file_id)
Definition at line 993 of file Messenger.c.
References FILE_ID_LENGTH, Friend::file_receiving, Friend::file_sending, FILESTATUS_NONE, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, File_Transfers::id, MAX_CONCURRENT_FILE_PIPES, File_Transfers::status, and Friend::status.
Referenced by tox_file_get_file_id().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        send_receive = 0;
        temp_filenum = filenumber;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -2;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -2;
    memcpy(file_id, ft->id, FILE_ID_LENGTH);
    return 0;
}
int file_seek (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint64_t position)
Definition at line 1230 of file Messenger.c.
References Friend::file_receiving, Friend::file_sending, FILECONTROL_SEEK, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, host_to_net(), MAX_CONCURRENT_FILE_PIPES, send_file_control_packet(), sending_pos, File_Transfers::size, File_Transfers::status, Friend::status, and File_Transfers::transferred.
Referenced by tox_file_seek().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        return -4;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -3;
    if (ft->status != FILESTATUS_NOT_ACCEPTED)
        return -5;
    if (position > ft->size) {
        return -6;
    }
    uint64_t sending_pos = position;
    host_to_net((uint8_t *)&sending_pos, sizeof(sending_pos));
    if (send_file_control_packet(m, friendnumber, send_receive, file_number,
      FILECONTROL_SEEK, (uint8_t *)&sending_pos,
                                 sizeof(sending_pos))) {
        ft->transferred = position;
    } else {
        return -8;
    }
    return 0;
}
int get_real_pk (const Messenger * m, int32_t friendnumber, uint8_t * real_pk)
Definition at line 98 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::real_pk.
Referenced by tox_friend_get_public_key().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    memcpy(real_pk, m->friendlist[friendnumber].real_pk, crypto_box_PUBLICKEYBYTES);
    return 0;
}
void getaddress (const Messenger * m, uint8_t * address)
Definition at line 138 of file Messenger.c.
References address_checksum(), Messenger::fr, FRIEND_ADDRESS_SIZE, get_nospam(), id_copy(), Messenger::net_crypto, make-funny-savefile::nospam, and Net_Crypto::self_public_key.
Referenced by main(), and tox_self_get_address().
{
    id_copy(address, m->net_crypto->self_public_key);
    uint32_t nospam = get_nospam(&(m->fr));
    memcpy(address + crypto_box_PUBLICKEYBYTES, &nospam, sizeof(nospam));
    uint16_t checksum = address_checksum(address,
      FRIEND_ADDRESS_SIZE - sizeof(checksum));
    memcpy(address + crypto_box_PUBLICKEYBYTES + sizeof(nospam), &checksum, sizeof(checksum));
}
int32_t getfriend_id (const Messenger * m, const uint8_t * real_pk)
Definition at line 79 of file Messenger.c.
References Messenger::friendlist, i, id_equal(), Messenger::numfriends, Friend::real_pk, and Friend::status.
Referenced by friend_already_added(), m_addfriend(), m_addfriend_norequest(), main(), and tox_friend_by_public_key().
{
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i) {
        if (m->friendlist[i].status > 0)
            if (id_equal(real_pk, m->friendlist[i].real_pk))
                return i;
    }
    return -1;
}
int getfriendcon_id (const Messenger * m, int32_t friendnumber)
Definition at line 110 of file Messenger.c.
References friend_not_valid(), Friend::friendcon_id, and Messenger::friendlist.
Referenced by handle_friend_invite_packet(), and join_groupchat().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].friendcon_id;
}
int getname (const Messenger * m, int32_t friendnumber, uint8_t * name)
Definition at line 570 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::name, and Friend::name_length.
Referenced by main(), messenger_suite(), START_TEST(), and tox_friend_get_name().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    memcpy(name, m->friendlist[friendnumber].name, m->friendlist[friendnumber].
      name_length);
    return m->friendlist[friendnumber].name_length;
}
uint16_t getself_name (const Messenger * m, uint8_t * name)
Definition at line 553 of file Messenger.c.
References Messenger::name, and Messenger::name_length.
Referenced by messenger_suite(), START_TEST(), and tox_self_get_name().
{
    if (name == NULL) {
        return 0;
    }
    memcpy(name, m->name, m->name_length);
    return m->name_length;
}
void kill_messenger (Messenger * m)
Definition at line 1848 of file Messenger.c.
References clear_receipts(), Messenger::dht, Messenger::fr_c, Messenger::friendlist, i, kill_DHT(), kill_friend_connections(), kill_net_crypto(), kill_networking(), kill_onion(), kill_onion_announce(), kill_onion_client(), kill_TCP_server(), Messenger::net, Messenger::net_crypto, Messenger::numfriends, Messenger::onion, Messenger::onion_a, Messenger::onion_c, and Messenger::tcp_server.
Referenced by main(), tox_kill(), and tox_new().
{
    if (!m)
        return;
    uint32_t i;
    if (m->tcp_server) {
        kill_TCP_server(m->tcp_server);
    }
    kill_friend_connections(m->fr_c);
    kill_onion(m->onion);
    kill_onion_announce(m->onion_a);
    kill_onion_client(m->onion_c);
    kill_net_crypto(m->net_crypto);
    kill_DHT(m->dht);
    kill_networking(m->net);
    for (i = 0; i < m->numfriends; ++i) {
        clear_receipts(m, i);
    }
    free(m->friendlist);
    free(m);
}
int32_t m_addfriend (Messenger * m, const uint8_t * address, const uint8_t * data, uint16_t length)
Definition at line 226 of file Messenger.c.
References address_checksum(), FAERR_ALREADYSENT, FAERR_BADCHECKSUM, FAERR_NOMESSAGE, FAERR_OWNKEY, FAERR_SETNEWNOSPAM, FAERR_TOOLONG, FRIEND_ADDED, FRIEND_ADDRESS_SIZE, FRIEND_CONFIRMED, friend_id, Messenger::friendlist, Friend::friendrequest_nospam, FRIENDREQUEST_TIMEOUT, Friend::friendrequest_timeout, getfriend_id(), id_copy(), id_equal(), Friend::info, Friend::info_size, init_new_friend(), MAX_FRIEND_REQUEST_DATA_SIZE, Messenger::net_crypto, make-funny-savefile::nospam, public_key_valid(), Net_Crypto::self_public_key, and Friend::status.
Referenced by friends_list_load(), main(), parent_friend_request(), and tox_friend_add().
{
    if (length > MAX_FRIEND_REQUEST_DATA_SIZE)
        return FAERR_TOOLONG;
    uint8_t real_pk[crypto_box_PUBLICKEYBYTES];
    id_copy(real_pk, address);
    if (!public_key_valid(real_pk))
        return FAERR_BADCHECKSUM;
    uint16_t check, checksum = address_checksum(address,
      FRIEND_ADDRESS_SIZE - sizeof(checksum));
    memcpy(&check, address + crypto_box_PUBLICKEYBYTES + sizeof(uint32_t), sizeof(check));
    if (check != checksum)
        return FAERR_BADCHECKSUM;
    if (length < 1)
        return FAERR_NOMESSAGE;
    if (id_equal(real_pk, m->net_crypto->self_public_key))
        return FAERR_OWNKEY;
    int32_t friend_id = getfriend_id(m, real_pk);
    if (friend_id != -1) {
        if (m->friendlist[friend_id].status >= FRIEND_CONFIRMED)
            return FAERR_ALREADYSENT;
        uint32_t nospam;
        memcpy(&nospam, address + crypto_box_PUBLICKEYBYTES, sizeof(nospam));
        if (m->friendlist[friend_id].friendrequest_nospam == nospam)
            return FAERR_ALREADYSENT;
        m->friendlist[friend_id].friendrequest_nospam =
      nospam;
        return FAERR_SETNEWNOSPAM;
    }
    int32_t ret = init_new_friend(m, real_pk, FRIEND_ADDED);
    if (ret < 0) {
        return ret;
    }
    m->friendlist[ret].friendrequest_timeout =
      FRIENDREQUEST_TIMEOUT;
    memcpy(m->friendlist[ret].info, data, length);
    m->friendlist[ret].info_size = length;
    memcpy(&(m->friendlist[ret].friendrequest_nospam), address +
      crypto_box_PUBLICKEYBYTES, sizeof(uint32_t));
    return ret;
}
int32_t m_addfriend_norequest (Messenger * m, const uint8_t * real_pk)
Definition at line 279 of file Messenger.c.
References FAERR_ALREADYSENT, FAERR_BADCHECKSUM, FAERR_OWNKEY, FRIEND_CONFIRMED, getfriend_id(), id_equal(), init_new_friend(), Messenger::net_crypto, public_key_valid(), and Net_Crypto::self_public_key.
Referenced by child_got_request(), friends_list_load(), main(), print_request(), and tox_friend_add_norequest().
{
    if (getfriend_id(m, real_pk) != -1)
        return FAERR_ALREADYSENT;
    if (!public_key_valid(real_pk))
        return FAERR_BADCHECKSUM;
    if (id_equal(real_pk, m->net_crypto->self_public_key))
        return FAERR_OWNKEY;
    return init_new_friend(m, real_pk, FRIEND_CONFIRMED);
}
void m_callback_connectionstatus (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 812 of file Messenger.c.
References Messenger::friend_connectionstatuschange, and Messenger::friend_connectionstatuschange_userdata.
Referenced by tox_callback_friend_connection_status().
{
    m->friend_connectionstatuschange = function;
    m->friend_connectionstatuschange_userdata = userdata;
}
void m_callback_connectionstatus_internal_av (Messenger * m, void(*)(Messenger *m, uint32_t, uint8_t, void *) function, void * userdata)
Definition at line 825 of file Messenger.c.
References Messenger::friend_connectionstatuschange_internal, and Messenger::friend_connectionstatuschange_internal_userdata.
Referenced by msi_new().
{
    m->friend_connectionstatuschange_internal = function;
    m->friend_connectionstatuschange_internal_userdata =
      userdata;
}
void m_callback_core_connection (Messenger * m, void(*)(Messenger *m, unsigned int, void *) function, void * userdata)
Definition at line 819 of file Messenger.c.
References Messenger::core_connection_change, and Messenger::core_connection_change_userdata.
Referenced by tox_callback_self_connection_status().
{
    m->core_connection_change = function;
    m->core_connection_change_userdata = userdata;
}
void m_callback_friendmessage (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 773 of file Messenger.c.
References Messenger::friend_message, and Messenger::friend_message_userdata.
Referenced by main(), and tox_callback_friend_message().
{
    m->friend_message = function;
    m->friend_message_userdata = userdata;
}
void m_callback_friendrequest (Messenger * m, void(*)(Messenger *m, const uint8_t *, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 765 of file Messenger.c.
References callback_friendrequest(), and Messenger::fr.
Referenced by main(), and tox_callback_friend_request().
{
    void (*handle_friendrequest)(void *, const uint8_t *, const uint8_t *, size_t, void *) = (void *)
      function;
    callback_friendrequest(&(m->fr), handle_friendrequest, m, userdata);
}
void m_callback_group_invite (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, uint16_t) function)
Definition at line 919 of file Messenger.c.
References Messenger::group_invite.
Referenced by kill_groupchats(), and new_groupchats().
{
    m->group_invite = function;
}
void m_callback_msi_packet (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1598 of file Messenger.c.
References Messenger::msi_packet, and Messenger::msi_packet_userdata.
Referenced by msi_kill(), and msi_new().
{
    m->msi_packet = function;
    m->msi_packet_userdata = userdata;
}
void m_callback_namechange (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 780 of file Messenger.c.
References Messenger::friend_namechange, and Messenger::friend_namechange_userdata.
Referenced by tox_callback_friend_name().
{
    m->friend_namechange = function;
    m->friend_namechange_userdata = userdata;
}
void m_callback_read_receipt (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, void *) function, void * userdata)
Definition at line 806 of file Messenger.c.
References Messenger::read_receipt, and Messenger::read_receipt_userdata.
Referenced by tox_callback_friend_read_receipt().
{
    m->read_receipt = function;
    m->read_receipt_userdata = userdata;
}
int m_callback_rtp_packet (Messenger * m, int32_t friendnumber, uint8_t byte, int(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t len, void *object) packet_handler_callback, void * object)
Definition at line 1644 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::function, Friend::lossy_rtp_packethandlers, Friend::object, PACKET_ID_LOSSY_RANGE_START, and PACKET_LOSSY_AV_RESERVED.
Referenced by rtp_kill(), and rtp_new().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (byte < PACKET_ID_LOSSY_RANGE_START)
        return -1;
    if (byte >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_LOSSY_AV_RESERVED))
        return -1;
    m->friendlist[friendnumber].lossy_rtp_packethandlers[byte %
      PACKET_LOSSY_AV_RESERVED].function =
        packet_handler_callback;
    m->friendlist[friendnumber].lossy_rtp_packethandlers[byte %
      PACKET_LOSSY_AV_RESERVED].object = object;
    return 0;
}
void m_callback_statusmessage (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 787 of file Messenger.c.
References Messenger::friend_statusmessagechange, and Messenger::friend_statusmessagechange_userdata.
Referenced by main(), and tox_callback_friend_status_message().
{
    m->friend_statusmessagechange = function;
    m->friend_statusmessagechange_userdata = userdata;
}
void m_callback_typingchange (Messenger * m, void(*)(Messenger *m, uint32_t, _Bool, void *) function, void * userdata)
Definition at line 800 of file Messenger.c.
References Messenger::friend_typingchange, and Messenger::friend_typingchange_userdata.
Referenced by tox_callback_friend_typing().
{
    m->friend_typingchange = function;
    m->friend_typingchange_userdata = userdata;
}
void m_callback_userstatus (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 794 of file Messenger.c.
References Messenger::friend_userstatuschange, and Messenger::friend_userstatuschange_userdata.
Referenced by tox_callback_friend_status().
{
    m->friend_userstatuschange = function;
    m->friend_userstatuschange_userdata = userdata;
}
int m_copy_self_statusmessage (const Messenger * m, uint8_t * buf)
Definition at line 664 of file Messenger.c.
References Messenger::statusmessage, and Messenger::statusmessage_length.
Referenced by tox_self_get_status_message().
{
    memcpy(buf, m->statusmessage, m->statusmessage_length);
    return m->statusmessage_length;
}
int m_copy_statusmessage (const Messenger * m, int32_t friendnumber, uint8_t * buf, uint32_t maxlen)
Definition at line 644 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, MIN, Friend::statusmessage, and Friend::statusmessage_length.
Referenced by tox_friend_get_status_message().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    int msglen = MIN(maxlen, m->friendlist[friendnumber].
      statusmessage_length);
    memcpy(buf, m->friendlist[friendnumber].statusmessage, msglen);
    memset(buf + msglen, 0, maxlen - msglen);
    return msglen;
}
int m_delfriend (Messenger * m, int32_t friendnumber)
Definition at line 379 of file Messenger.c.
References clear_receipts(), FAERR_NOMEM, Messenger::fr, Messenger::fr_c, friend_con_connected(), friend_connection_callbacks(), Messenger::friend_connectionstatuschange_internal, Messenger::friend_connectionstatuschange_internal_userdata, friend_not_valid(), Friend::friendcon_id, FRIENDCONN_STATUS_CONNECTED, Messenger::friendlist, i, kill_friend_connection(), MESSENGER_CALLBACK_INDEX, NOFRIEND, Messenger::numfriends, Friend::real_pk, realloc_friendlist(), remove_request_received(), send_offline_packet(), and Friend::status.
Referenced by messenger_suite(), START_TEST(), and tox_friend_delete().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friend_connectionstatuschange_internal)
        m->friend_connectionstatuschange_internal(m, friendnumber, 0,
       m->friend_connectionstatuschange_internal_userdata);
    clear_receipts(m, friendnumber);
    remove_request_received(&(m->fr), m->friendlist[friendnumber].
      real_pk);
    friend_connection_callbacks(m->fr_c, m->
      friendlist[friendnumber].friendcon_id,
      MESSENGER_CALLBACK_INDEX, 0, 0, 0, 0, 0);
    if (friend_con_connected(m->fr_c, m->friendlist[friendnumber].
      friendcon_id) == FRIENDCONN_STATUS_CONNECTED) {
        send_offline_packet(m, m->friendlist[friendnumber].
      friendcon_id);
    }
    kill_friend_connection(m->fr_c, m->friendlist[friendnumber].
      friendcon_id);
    memset(&(m->friendlist[friendnumber]), 0, sizeof(Friend));
    uint32_t i;
    for (i = m->numfriends; i != 0; --i) {
        if (m->friendlist[i - 1].status != NOFRIEND)
            break;
    }
    m->numfriends = i;
    if (realloc_friendlist(m, m->numfriends) != 0)
        return FAERR_NOMEM;
    return 0;
}
int m_friend_exists (const Messenger * m, int32_t friendnumber)
Definition at line 437 of file Messenger.c.
References friend_not_valid().
Referenced by messenger_suite(), START_TEST(), and tox_friend_exists().
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    return 1;
}
int m_get_friend_connectionstatus (const Messenger * m, int32_t friendnumber)
Definition at line 412 of file Messenger.c.
References CONNECTION_NONE, CONNECTION_TCP, CONNECTION_UDP, CONNECTION_UNKNOWN, crypto_connection_status(), Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, Messenger::net_crypto, and Friend::status.
Referenced by check_friend_tcp_udp(), messenger_suite(), START_TEST(), and tox_friend_get_connection_status().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status == FRIEND_ONLINE) {
        _Bool direct_connected = 0;
        unsigned int num_online_relays = 0;
        crypto_connection_status(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                 m->friendlist[friendnumber].
      friendcon_id), &direct_connected, &num_online_relays);
        if (direct_connected) {
            return CONNECTION_UDP;
        } else {
            if (num_online_relays) {
                return CONNECTION_TCP;
            } else {
                return CONNECTION_UNKNOWN;
            }
        }
    } else {
        return CONNECTION_NONE;
    }
}
int m_get_istyping (const Messenger * m, int32_t friendnumber)
Definition at line 715 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::is_typing.
Referenced by tox_friend_get_typing().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].is_typing;
}
uint64_t m_get_last_online (const Messenger * m, int32_t friendnumber)
Definition at line 689 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::last_seen_time.
Referenced by tox_friend_get_last_online().
{
    if (friend_not_valid(m, friendnumber))
        return UINT64_MAX;
    return m->friendlist[friendnumber].last_seen_time;
}
int m_get_name_size (const Messenger * m, int32_t friendnumber)
Definition at line 579 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::name_length.
Referenced by tox_friend_get_name_size().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].name_length;
}
int m_get_self_name_size (const Messenger * m)
Definition at line 587 of file Messenger.c.
References Messenger::name_length.
Referenced by tox_self_get_name_size().
{
    return m->name_length;
}
int m_get_self_statusmessage_size (const Messenger * m)
Definition at line 659 of file Messenger.c.
References Messenger::statusmessage_length.
Referenced by tox_self_get_status_message_size().
{
    return m->statusmessage_length;
}
uint8_t m_get_self_userstatus (const Messenger * m)
Definition at line 684 of file Messenger.c.
References Messenger::userstatus.
Referenced by tox_self_get_status().
{
    return m->userstatus;
}
int m_get_statusmessage_size (const Messenger * m, int32_t friendnumber)
Definition at line 633 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::statusmessage_length.
Referenced by START_TEST(), tox_friend_get_status_message(), and tox_friend_get_status_message_size().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].statusmessage_length;
}
uint8_t m_get_userstatus (const Messenger * m, int32_t friendnumber)
Definition at line 670 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::userstatus, USERSTATUS_INVALID, and USERSTATUS_NONE.
Referenced by tox_friend_get_status().
{
    if (friend_not_valid(m, friendnumber))
        return USERSTATUS_INVALID;
    uint8_t status = m->friendlist[friendnumber].userstatus;
    if (status >= USERSTATUS_INVALID) {
        status = USERSTATUS_NONE;
    }
    return status;
}
int m_msi_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint16_t length)
Definition at line 1610 of file Messenger.c.
References PACKET_ID_MSI, and write_cryptpacket_id().
Referenced by send_message().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_MSI, data, length, 0);
}
int m_send_message_generic (Messenger * m, int32_t friendnumber, uint8_t type, const uint8_t * message, uint32_t length, uint32_t * message_id)
Definition at line 454 of file Messenger.c.
References add_receipt(), Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, MESSAGE_ACTION, Friend::message_id, Receipts::msg_id, Messenger::net_crypto, PACKET_ID_MESSAGE, Receipts::packet_num, Friend::status, and write_cryptpacket().
Referenced by main(), print_message(), START_TEST(), and tox_friend_send_message().
{
    if (type > MESSAGE_ACTION)
        return -5;
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length >= MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -3;
    uint8_t packet[length + 1];
    packet[0] = type + PACKET_ID_MESSAGE;
    if (length != 0)
        memcpy(packet + 1, message, length);
    int64_t packet_num = write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                           m->friendlist[friendnumber].
      friendcon_id), packet, length + 1, 0);
    if (packet_num == -1)
        return -4;
    uint32_t msg_id = ++m->friendlist[friendnumber].message_id;
    add_receipt(m, friendnumber, packet_num, msg_id);
    if (message_id)
        *message_id = msg_id;
    return 0;
}
int m_set_statusmessage (Messenger * m, const uint8_t * status, uint16_t length)
Definition at line 592 of file Messenger.c.
References Messenger::friendlist, i, MAX_STATUSMESSAGE_LENGTH, Messenger::numfriends, Messenger::statusmessage, Messenger::statusmessage_length, and Friend::statusmessage_sent.
Referenced by messenger_load_state_callback(), START_TEST(), and tox_self_set_status_message().
{
    if (length > MAX_STATUSMESSAGE_LENGTH)
        return -1;
    if (m->statusmessage_length == length && (length == 0 || memcmp(m->
      statusmessage, status, length) == 0))
        return 0;
    if (length)
        memcpy(m->statusmessage, status, length);
    m->statusmessage_length = length;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].statusmessage_sent = 0;
    return 0;
}
int m_set_userstatus (Messenger * m, uint8_t status)
Definition at line 613 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, Messenger::userstatus, USERSTATUS_INVALID, and Friend::userstatus_sent.
Referenced by messenger_load_state_callback(), messenger_suite(), and tox_self_set_status().
{
    if (status >= USERSTATUS_INVALID)
        return -1;
    if (m->userstatus == status)
        return 0;
    m->userstatus = status;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].userstatus_sent = 0;
    return 0;
}
int m_set_usertyping (Messenger * m, int32_t friendnumber, uint8_t is_typing)
Definition at line 697 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::user_istyping, and Friend::user_istyping_sent.
Referenced by tox_self_set_typing().
{
    if (is_typing != 0 && is_typing != 1)
        return -1;
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].user_istyping == is_typing)
        return 0;
    m->friendlist[friendnumber].user_istyping = is_typing;
    m->friendlist[friendnumber].user_istyping_sent = 0;
    return 0;
}
int messenger_load (Messenger * m, const uint8_t * data, uint32_t length)
Definition at line 2744 of file Messenger.c.
References lendian_to_host32(), load_state(), messenger_load_state_callback(), MESSENGER_STATE_COOKIE_GLOBAL, and MESSENGER_STATE_COOKIE_TYPE.
Referenced by main(), START_TEST(), and tox_new().
{
    uint32_t data32[2];
    uint32_t cookie_len = sizeof(data32);
    if (length < cookie_len)
        return -1;
    memcpy(data32, data, sizeof(uint32_t));
    lendian_to_host32(data32 + 1, data + sizeof(uint32_t));
    if (!data32[0] && (data32[1] == MESSENGER_STATE_COOKIE_GLOBAL))
        return load_state(messenger_load_state_callback, m,
      data + cookie_len,
                          length - cookie_len, MESSENGER_STATE_COOKIE_TYPE);
    else
        return -1;
}
uint32_t messenger_run_interval (const Messenger * m)
Definition at line 2268 of file Messenger.c.
References crypto_run_interval(), MIN_RUN_INTERVAL, and Messenger::net_crypto.
Referenced by tox_iteration_interval().
{
    uint32_t crypto_interval = crypto_run_interval(m->
      net_crypto);
    if (crypto_interval > MIN_RUN_INTERVAL) {
        return MIN_RUN_INTERVAL;
    } else {
        return crypto_interval;
    }
}
void messenger_save (const Messenger * m, uint8_t * data)
Definition at line 2565 of file Messenger.c.
References copy_connected_tcp_relays(), make-funny-savefile::data, Messenger::dht, DHT_save(), DHT_size(), Messenger::fr, friends_list_save(), get_nospam(), host_to_lendian32(), messenger_size(), MESSENGER_STATE_COOKIE_GLOBAL, MESSENGER_STATE_TYPE_DHT, MESSENGER_STATE_TYPE_END, MESSENGER_STATE_TYPE_FRIENDS, MESSENGER_STATE_TYPE_NAME, MESSENGER_STATE_TYPE_NOSPAMKEYS, MESSENGER_STATE_TYPE_PATH_NODE, MESSENGER_STATE_TYPE_STATUS, MESSENGER_STATE_TYPE_STATUSMESSAGE, MESSENGER_STATE_TYPE_TCP_RELAY, Messenger::name, Messenger::name_length, Messenger::net_crypto, num, NUM_SAVED_PATH_NODES, NUM_SAVED_TCP_RELAYS, onion_backup_nodes(), Messenger::onion_c, pack_nodes(), packed_node_size(), save_keys(), saved_friendslist_size(), Messenger::statusmessage, Messenger::statusmessage_length, TCP_INET6, Messenger::userstatus, and z_state_save_subheader().
Referenced by main(), START_TEST(), and tox_get_savedata().
{
    memset(data, 0, messenger_size(m));
    uint32_t len;
    uint16_t type;
    uint32_t size32 = sizeof(uint32_t);
    memset(data, 0, size32);
    data += size32;
    host_to_lendian32(data, MESSENGER_STATE_COOKIE_GLOBAL
      );
    data += size32;
#ifdef DEBUG
    assert(sizeof(get_nospam(&(m->fr))) == sizeof(uint32_t));
#endif
    len = size32 + crypto_box_PUBLICKEYBYTES + crypto_box_SECRETKEYBYTES;
    type = MESSENGER_STATE_TYPE_NOSPAMKEYS;
    data = z_state_save_subheader(data, len, type);
    *(uint32_t *)data = get_nospam(&(m->fr));
    save_keys(m->net_crypto, data + size32);
    data += len;
    len = saved_friendslist_size(m);
    type = MESSENGER_STATE_TYPE_FRIENDS;
    data = z_state_save_subheader(data, len, type);
    friends_list_save(m, data);
    data += len;
    len = m->name_length;
    type = MESSENGER_STATE_TYPE_NAME;
    data = z_state_save_subheader(data, len, type);
    memcpy(data, m->name, len);
    data += len;
    len = m->statusmessage_length;
    type = MESSENGER_STATE_TYPE_STATUSMESSAGE;
    data = z_state_save_subheader(data, len, type);
    memcpy(data, m->statusmessage, len);
    data += len;
    len = 1;
    type = MESSENGER_STATE_TYPE_STATUS;
    data = z_state_save_subheader(data, len, type);
    *data = m->userstatus;
    data += len;
    len = DHT_size(m->dht);
    type = MESSENGER_STATE_TYPE_DHT;
    data = z_state_save_subheader(data, len, type);
    DHT_save(m->dht, data);
    data += len;
    Node_format relays[NUM_SAVED_TCP_RELAYS];
    type = MESSENGER_STATE_TYPE_TCP_RELAY;
    uint8_t *temp_data = data;
    data = z_state_save_subheader(temp_data, 0, type);
    unsigned int num = copy_connected_tcp_relays(m->
      net_crypto, relays, NUM_SAVED_TCP_RELAYS);
    int l = pack_nodes(data, NUM_SAVED_TCP_RELAYS *
      packed_node_size(TCP_INET6), relays, num);
    if (l > 0) {
        len = l;
        data = z_state_save_subheader(temp_data, len, type);
        data += len;
    }
    Node_format nodes[NUM_SAVED_PATH_NODES];
    type = MESSENGER_STATE_TYPE_PATH_NODE;
    temp_data = data;
    data = z_state_save_subheader(data, 0, type);
    memset(nodes, 0, sizeof(nodes));
    num = onion_backup_nodes(m->onion_c, nodes,
      NUM_SAVED_PATH_NODES);
    l = pack_nodes(data, NUM_SAVED_PATH_NODES *
      packed_node_size(TCP_INET6), nodes, num);
    if (l > 0) {
        len = l;
        data = z_state_save_subheader(temp_data, len, type);
        data += len;
    }
    z_state_save_subheader(data, 0,
      MESSENGER_STATE_TYPE_END);
}
uint32_t messenger_size (const Messenger * m)
Definition at line 2540 of file Messenger.c.
References Messenger::dht, DHT_size(), Messenger::name_length, NUM_SAVED_PATH_NODES, NUM_SAVED_TCP_RELAYS, packed_node_size(), saved_friendslist_size(), Messenger::statusmessage_length, and TCP_INET6.
Referenced by main(), messenger_save(), START_TEST(), and tox_get_savedata_size().
{
    uint32_t size32 = sizeof(uint32_t), sizesubhead = size32 * 2;
    return size32 * 2 // global cookie
             + sizesubhead + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + crypto_box_SECRETKEYBYTES
             + sizesubhead + DHT_size(m->dht) // DHT
             + sizesubhead + saved_friendslist_size(m) // Friendlist itself.
             + sizesubhead + m->name_length // Own nickname.
             + sizesubhead + m->statusmessage_length // status message
             + sizesubhead + 1 // status
             + sizesubhead + NUM_SAVED_TCP_RELAYS *
      packed_node_size(TCP_INET6) //TCP relays
             + sizesubhead + NUM_SAVED_PATH_NODES *
      packed_node_size(TCP_INET6) //saved path nodes
             + sizesubhead;
}
long int new_filesender (const Messenger * m, int32_t friendnumber, uint32_t file_type, uint64_t filesize, const uint8_t * file_id, const uint8_t * filename, uint16_t filename_length)
Definition at line 1070 of file Messenger.c.
References FILE_ID_LENGTH, FILE_PAUSE_NOT, Friend::file_sending, file_sendrequest(), FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, friend_not_valid(), Messenger::friendlist, i, File_Transfers::id, MAX_CONCURRENT_FILE_PIPES, MAX_FILENAME_LENGTH, Friend::num_sending_files, File_Transfers::paused, File_Transfers::requested, File_Transfers::size, File_Transfers::slots_allocated, File_Transfers::status, and File_Transfers::transferred.
Referenced by tox_file_send().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (filename_length > MAX_FILENAME_LENGTH)
        return -2;
    uint32_t i;
    for (i = 0; i < MAX_CONCURRENT_FILE_PIPES; ++i) {
        if (m->friendlist[friendnumber].file_sending[i].
      status == FILESTATUS_NONE)
            break;
    }
    if (i == MAX_CONCURRENT_FILE_PIPES)
        return -3;
    if (file_sendrequest(m, friendnumber, i, file_type, filesize, file_id, filename,
      filename_length) == 0)
        return -4;
    struct File_Transfers *ft = &m->friendlist[friendnumber].
      file_sending[i];
    ft->status = FILESTATUS_NOT_ACCEPTED;
    ft->size = filesize;
    ft->transferred = 0;
    ft->requested = 0;
    ft->slots_allocated = 0;
    ft->paused = FILE_PAUSE_NOT;
    memcpy(ft->id, file_id, FILE_ID_LENGTH);
    ++m->friendlist[friendnumber].num_sending_files;
    return i;
}
Messenger* new_messenger (Messenger_Options * options, unsigned int * error)
Definition at line 1751 of file Messenger.c.
References Messenger::dht, Messenger::fr, Messenger::fr_c, friend_already_added(), friendreq_init(), ip, ip_init(), Messenger_Options::ipv6enabled, kill_DHT(), kill_friend_connections(), kill_net_crypto(), kill_networking(), kill_onion(), kill_onion_announce(), kill_onion_client(), m, MESSENGER_ERROR_NONE, MESSENGER_ERROR_OTHER, MESSENGER_ERROR_PORT, MESSENGER_ERROR_TCP_SERVER, Messenger::net, Messenger::net_crypto, new_DHT(), new_friend_connections(), new_net_crypto(), new_networking_ex(), new_onion(), new_onion_announce(), new_onion_client(), new_TCP_server(), Messenger::onion, Messenger::onion_a, Messenger::onion_c, Messenger::options, Messenger_Options::port_range, Messenger_Options::proxy_info, random_int(), DHT::self_secret_key, set_filter_function(), set_nospam(), Messenger::tcp_server, Messenger_Options::tcp_server_port, and Messenger_Options::udp_disabled.
Referenced by main(), and tox_new().
{
    Messenger *m = calloc(1, sizeof(Messenger));
    if (error)
        *error = MESSENGER_ERROR_OTHER;
    if (! m)
        return NULL;
    unsigned int net_err = 0;
    if (options->udp_disabled) {
        /* this is the easiest way to completely disable UDP without changing too much code. */
        m->net = calloc(1, sizeof(Networking_Core));
    } else {
        IP ip;
        ip_init(&ip, options->ipv6enabled);
        m->net = new_networking_ex(ip, options->port_range[0], options->
      port_range[1], &net_err);
    }
    if (m->net == NULL) {
        free(m);
        if (error && net_err == 1) {
            *error = MESSENGER_ERROR_PORT;
        }
        return NULL;
    }
    m->dht = new_DHT(m->net);
    if (m->dht == NULL) {
        kill_networking(m->net);
        free(m);
        return NULL;
    }
    m->net_crypto = new_net_crypto(m->dht, &options->
      proxy_info);
    if (m->net_crypto == NULL) {
        kill_networking(m->net);
        kill_DHT(m->dht);
        free(m);
        return NULL;
    }
    m->onion = new_onion(m->dht);
    m->onion_a = new_onion_announce(m->dht);
    m->onion_c = new_onion_client(m->net_crypto);
    m->fr_c = new_friend_connections(m->onion_c);
    if (!(m->onion && m->onion_a && m->onion_c)) {
        kill_friend_connections(m->fr_c);
        kill_onion(m->onion);
        kill_onion_announce(m->onion_a);
        kill_onion_client(m->onion_c);
        kill_net_crypto(m->net_crypto);
        kill_DHT(m->dht);
        kill_networking(m->net);
        free(m);
        return NULL;
    }
    if (options->tcp_server_port) {
        m->tcp_server = new_TCP_server(options->
      ipv6enabled, 1, &options->tcp_server_port, m->dht->
      self_secret_key, m->onion);
        if (m->tcp_server == NULL) {
            kill_friend_connections(m->fr_c);
            kill_onion(m->onion);
            kill_onion_announce(m->onion_a);
            kill_onion_client(m->onion_c);
            kill_net_crypto(m->net_crypto);
            kill_DHT(m->dht);
            kill_networking(m->net);
            free(m);
            if (error)
                *error = MESSENGER_ERROR_TCP_SERVER;
            return NULL;
        }
    }
    m->options = *options;
    friendreq_init(&(m->fr), m->fr_c);
    set_nospam(&(m->fr), random_int());
    set_filter_function(&(m->fr), &friend_already_added, m);
    if (error)
        *error = MESSENGER_ERROR_NONE;
    return m;
}
int send_custom_lossless_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint32_t length)
Definition at line 1714 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, Messenger::net_crypto, PACKET_ID_LOSSLESS_RANGE_SIZE, PACKET_ID_LOSSLESS_RANGE_START, Friend::status, and write_cryptpacket().
Referenced by tox_friend_send_lossless_packet().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (data[0] < PACKET_ID_LOSSLESS_RANGE_START)
        return -3;
    if (data[0] >= (PACKET_ID_LOSSLESS_RANGE_START +
      PACKET_ID_LOSSLESS_RANGE_SIZE))
        return -3;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -4;
    if (write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                          m->friendlist[friendnumber].friendcon_id),
      data, length, 1) == -1) {
        return -5;
    } else {
        return 0;
    }
}
int send_custom_lossy_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint32_t length)
Definition at line 1663 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, Messenger::net_crypto, PACKET_ID_LOSSY_RANGE_SIZE, PACKET_ID_LOSSY_RANGE_START, send_lossy_cryptpacket(), and Friend::status.
Referenced by rtp_send_msg(), and tox_friend_send_lossy_packet().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (data[0] < PACKET_ID_LOSSY_RANGE_START)
        return -3;
    if (data[0] >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_ID_LOSSY_RANGE_SIZE))
        return -3;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -4;
    if (send_lossy_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                               m->friendlist[friendnumber].
      friendcon_id), data, length) == -1) {
        return -5;
    } else {
        return 0;
    }
}
int send_group_invite_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint16_t length)
Definition at line 930 of file Messenger.c.
References PACKET_ID_INVITE_GROUPCHAT, and write_cryptpacket_id().
Referenced by invite_friend(), and join_groupchat().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_INVITE_GROUPCHAT, data, length, 0);
}
int setfriendname (Messenger * m, int32_t friendnumber, const uint8_t * name, uint16_t length)
Definition at line 507 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, MAX_NAME_LENGTH, Friend::name, and Friend::name_length.
Referenced by friends_list_load().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length > MAX_NAME_LENGTH || length == 0)
        return -1;
    m->friendlist[friendnumber].name_length = length;
    memcpy(m->friendlist[friendnumber].name, name, length);
    return 0;
}
int setname (Messenger * m, const uint8_t * name, uint16_t length)
Definition at line 528 of file Messenger.c.
References Messenger::friendlist, i, MAX_NAME_LENGTH, Messenger::name, Messenger::name_length, Friend::name_sent, and Messenger::numfriends.
Referenced by main(), messenger_load_state_callback(), messenger_suite(), START_TEST(), and tox_self_set_name().
{
    if (length > MAX_NAME_LENGTH)
        return -1;
    if (m->name_length == length && (length == 0 || memcmp(name, m->
      name, length) == 0))
        return 0;
    if (length)
        memcpy(m->name, name, length);
    m->name_length = length;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].name_sent = 0;
    return 0;
}