testing/tox_sync.c File Reference
#include `../toxcore/tox.h`
*
#include `misc_tools.c`
*
#include <unistd.h>
*
#include <dirent.h>
*
#include <stdio.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
Data Structures
struct File_t
Macros
#define c_sleep(x) usleep(1000*x)
#define NUM_FILE_SENDERS 256
Functions
void tox_file_chunk_request (Tox *tox, uint32_t friend_number, uint32_t file_number, uint64_t position, size_t length, void *user_data)
uint32_t add_filesender (Tox *m, uint16_t friendnum, char *filename)
void kill_filesender (Tox *m, uint32_t filenum)
int not_sending ()
void file_request_accept (Tox *tox, uint32_t friend_number, uint32_t file_number, uint32_t type, uint64_t file_size, const uint8_t *filename, size_t filename_length, void *user_data)
void file_print_control (Tox *tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, void *user_data)
void write_file (Tox *tox, uint32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t *data, size_t length, void *user_data)
void print_online (Tox *tox, uint32_t friendnumber, TOX_CONNECTION status, void *userdata)
int main (int argc, char *argv[])
Variables
File_t file_senders [NUM_FILE_SENDERS]
File_t file_recv [NUM_FILE_SENDERS]
uint8_t numfilesenders
static char path [1024]
Macro Definition Documentation
#define c_sleep(x) usleep(1000*x)
Definition at line 39 of file tox_sync.c.
Referenced by main().
#define NUM_FILE_SENDERS 256
Definition at line 46 of file tox_sync.c.
Referenced by kill_filesender(), not_sending(), print_online(), and tox_file_chunk_request().
Function Documentation
uint32_t add_filesender (Tox * m, uint16_t friendnum, char * filename)
Definition at line 81 of file tox_sync.c.
References File_t::file, filenum, File_t::filenumber, File_t::friendnum, numfilesenders, TOX_FILE_KIND_DATA, and tox_file_send().
Referenced by main().
{
    FILE *tempfile = fopen(filename, "rb");
    if (tempfile == 0)
        return -1;
    fseek(tempfile, 0, SEEK_END);
    uint64_t filesize = ftell(tempfile);
    fseek(tempfile, 0, SEEK_SET);
    uint32_t filenum = tox_file_send(m, friendnum,
      TOX_FILE_KIND_DATA, filesize, 0, (uint8_t *)filename,
                                     strlen(filename), 0);
    if (filenum == -1)
        return -1;
    file_senders[numfilesenders].file = tempfile;
    file_senders[numfilesenders].friendnum = friendnum;
    file_senders[numfilesenders].filenumber =
      filenum;
    ++numfilesenders;
    return filenum;
}
void file_print_control (Tox * tox, uint32_t friend_number, uint32_t file_number, TOX_FILE_CONTROL control, void * user_data)
Definition at line 172 of file tox_sync.c.
References File_t::file, kill_filesender(), printf(), and TOX_FILE_CONTROL_CANCEL.
Referenced by main().
{
    if (file_number < (1 << 15) && (control == TOX_FILE_CONTROL_CANCEL)) {
        kill_filesender(tox, file_number);
        return;
    }
    if (file_number > (1 << 15) && (control == TOX_FILE_CONTROL_CANCEL)) {
        uint8_t file_index = (file_number >> 16) - 1;
        fclose(file_recv[file_index].file);
        printf("File closed\n");
        file_recv[file_index].file = 0;
        return;
    }
}
void file_request_accept (Tox * tox, uint32_t friend_number, uint32_t file_number, uint32_t type, uint64_t file_size, const uint8_t * filename, size_t filename_length, void * user_data)
Definition at line 127 of file tox_sync.c.
References File_t::file, i, path, printf(), tox_file_control(), TOX_FILE_CONTROL_CANCEL, TOX_FILE_CONTROL_RESUME, and TOX_FILE_KIND_DATA.
Referenced by main().
{
    if (type != TOX_FILE_KIND_DATA) {
        printf("Refused invalid file type.");
        tox_file_control(tox, friend_number, file_number,
      TOX_FILE_CONTROL_CANCEL, 0);
        return;
    }
    char fullpath[1024];
    uint32_t i;
    uint16_t rm = 0;
    for (i = 0; i < strlen((char *)filename); ++i) {
        if (filename[i] == '/')
            rm = i;
    }
    if (path[strlen(path) - 1] == '/')
        sprintf(fullpath, "%s%s", path, filename + rm + 1);
    else
        sprintf(fullpath, "%s/%s", path, filename + rm + 1);
    FILE *tempfile = fopen(fullpath, "rb");
    if (tempfile != 0) {
        fclose(tempfile);
        tox_file_control(tox, friend_number, file_number,
      TOX_FILE_CONTROL_CANCEL, 0);
        return;
    }
    uint8_t file_index = (file_number >> 16) - 1;
    file_recv[file_index].file = fopen(fullpath, "wb");
    if (file_recv[file_index].file == 0) {
        tox_file_control(tox, friend_number, file_number,
      TOX_FILE_CONTROL_CANCEL, 0);
        return;
    }
    if (tox_file_control(tox, friend_number, file_number,
      TOX_FILE_CONTROL_RESUME, 0)) {
        printf("Accepted file transfer. (file: %s)\n", fullpath);
    }
}
void kill_filesender (Tox * m, uint32_t filenum)
Definition at line 104 of file tox_sync.c.
References File_t::file, i, and NUM_FILE_SENDERS.
Referenced by file_print_control().
{
    uint32_t i;
    for (i = 0; i < NUM_FILE_SENDERS; ++i)
        if (file_senders[i].file != 0 && file_senders[i].filenumber ==
      filenum) {
            fclose(file_senders[i].file);
            file_senders[i].file = 0;
        }
}
int main (int argc, char * argv[])
Definition at line 232 of file tox_sync.c.
References add_filesender(), c_sleep, cmdline_parsefor_ipv46(), file_print_control(), file_request_accept(), hex_string_to_bin(), i, not_sending(), num, path, port, print_online(), printf(), TOX_ADDRESS_SIZE, tox_bootstrap(), tox_callback_file_chunk_request(), tox_callback_file_recv(), tox_callback_file_recv_chunk(), tox_callback_file_recv_control(), tox_callback_friend_connection_status(), tox_file_chunk_request(), tox_friend_add(), tox_friend_get_connection_status(), tox_iterate(), tox_new(), tox_self_get_address(), tox_self_get_connection_status(), and write_file().
{
    uint8_t ipv6enabled = 1; /* x */
    int argvoffset = cmdline_parsefor_ipv46(argc, argv, &ipv6enabled);
    if (argvoffset < 0)
        exit(1);
    /* with optional --ipvx, now it can be 1-4 arguments... */
    if ((argc != argvoffset + 3) && (argc != argvoffset + 5)) {
        printf("Usage: %s [--ipv4|--ipv6] ip port public_key (of the DHT bootstrap node) folder (to
       sync)\n", argv[0]);
        exit(0);
    }
    Tox *tox = tox_new(0, 0);
    tox_callback_file_recv_chunk(tox, write_file, NULL);
    tox_callback_file_recv_control(tox,
      file_print_control, NULL);
    tox_callback_file_recv(tox, file_request_accept, NULL);
    tox_callback_file_chunk_request(tox,
      tox_file_chunk_request, NULL);
    tox_callback_friend_connection_status(tox,
      print_online, NULL);
    uint16_t port = atoi(argv[argvoffset + 2]);
    unsigned char *binary_string = hex_string_to_bin(argv[argvoffset + 3]);
    int res = tox_bootstrap(tox, argv[argvoffset + 1], port, binary_string, 0);
    free(binary_string);
    if (!res) {
        printf("Failed to convert \"%s\" into an IP address. Exiting...\n", argv[argvoffset + 1]);
        exit(1);
    }
    uint8_t address[TOX_ADDRESS_SIZE];
    tox_self_get_address(tox, address);
    uint32_t i;
    for (i = 0; i < TOX_ADDRESS_SIZE; i++) {
        printf("%02X", address[i]);
    }
    char temp_id[128];
    printf("\nEnter the address of the other id you want to sync with (38 bytes HEX format):\n");
    if (scanf("%s", temp_id) != 1) {
        return 1;
    }
    uint8_t *bin_id = hex_string_to_bin(temp_id);
    uint32_t num = tox_friend_add(tox, bin_id, (uint8_t *)"Install Gentoo", sizeof("
      Install Gentoo"), 0);
    free(bin_id);
    if (num == UINT32_MAX) {
        printf("\nSomething went wrong when adding friend.\n");
        return 1;
    }
    memcpy(path, argv[argvoffset + 4], strlen(argv[argvoffset + 4]));
    DIR *d;
    struct dirent *dir;
    uint8_t notconnected = 1;
    while (1) {
        if (tox_self_get_connection_status(tox) && notconnected) {
            printf("\nDHT connected.\n");
            notconnected = 0;
        }
        if (not_sending() && tox_friend_get_connection_status(
      tox, num, 0)) {
            d = opendir(path);
            if (d) {
                while ((dir = readdir(d)) != NULL) {
                    if (dir->d_type == DT_REG) {
                        char fullpath[1024];
                        if (path[strlen(path) - 1] == '/')
                            sprintf(fullpath, "%s%s", path, dir->d_name);
                        else
                            sprintf(fullpath, "%s/%s", path, dir->d_name);
                        add_filesender(tox, num, fullpath);
                    }
                }
                closedir(d);
            } else {
                printf("\nFailed to open directory.\n");
                return 1;
            }
        }
        tox_iterate(tox);
        c_sleep(1);
    }
    return 0;
}
int not_sending ()
Definition at line 114 of file tox_sync.c.
References i, and NUM_FILE_SENDERS.
Referenced by main().
{
    uint32_t i;
    for (i = 0; i < NUM_FILE_SENDERS; ++i)
        if (file_senders[i].file != 0)
            return 0;
    return 1;
}
void print_online (Tox * tox, uint32_t friendnumber, TOX_CONNECTION status, void * userdata)
Definition at line 210 of file tox_sync.c.
References File_t::file, i, NUM_FILE_SENDERS, and printf().
Referenced by main().
{
    if (status)
        printf("\nOther went online.\n");
    else {
        printf("\nOther went offline.\n");
        unsigned int i;
        for (i = 0; i < NUM_FILE_SENDERS; ++i) {
            if (file_senders[i].file != 0) {
                fclose(file_senders[i].file);
                file_senders[i].file = 0;
            }
            if (file_recv[i].file != 0) {
                fclose(file_recv[i].file);
                file_recv[i].file = 0;
            }
        }
    }
}
void tox_file_chunk_request (Tox * tox, uint32_t friend_number, uint32_t file_number, uint64_t position, size_t length, void * user_data)
Definition at line 56 of file tox_sync.c.
References make-funny-savefile::data, File_t::file, i, NUM_FILE_SENDERS, printf(), and tox_file_send_chunk().
Referenced by main().
{
    unsigned int i;
    for (i = 0; i < NUM_FILE_SENDERS; ++i) {
        /* This is slow */
        if (file_senders[i].file && file_senders[i].friendnum ==
      friend_number && file_senders[i].filenumber == file_number) {
            if (length == 0) {
                fclose(file_senders[i].file);
                file_senders[i].file = 0;
                printf("[t] %u file transfer: %u completed\n",
      file_senders[i].friendnum, file_senders[i].filenumber);
                break;
            }
            fseek(file_senders[i].file, position, SEEK_SET);
            uint8_t data[length];
            int len = fread(data, 1, length, file_senders[i].file);
            tox_file_send_chunk(tox, friend_number, file_number, position,
      data, len, 0);
            break;
        }
    }
}
void write_file (Tox * tox, uint32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t * data, size_t length, void * user_data)
Definition at line 189 of file tox_sync.c.
References File_t::file, and printf().
Referenced by main().
{
    uint8_t file_index = (filenumber >> 16) - 1;
    if (length == 0) {
        fclose(file_recv[file_index].file);
        printf("File closed\n");
        file_recv[file_index].file = 0;
        printf("%u file transfer: %u completed\n", friendnumber, filenumber);
        return;
    }
    if (file_recv[file_index].file != 0) {
        fseek(file_recv[file_index].file, position, SEEK_SET);
        if (fwrite(data, length, 1, file_recv[file_index].file) != 1)
            printf("Error writing data\n");
    }
}
Variable Documentation
File_t file_recv[NUM_FILE_SENDERS]
Definition at line 53 of file tox_sync.c.
File_t file_senders[NUM_FILE_SENDERS]
Definition at line 52 of file tox_sync.c.
uint8_t numfilesenders
Definition at line 54 of file tox_sync.c.
Referenced by add_filesender().
char path[1024] [static]
Definition at line 125 of file tox_sync.c.
Referenced by client_send_announce_request(), file_request_accept(), main(), save_data_file(), send_onion_data(), and START_TEST().