toxcore/friend_connection.c File Reference
#include `friend_connection.h`
*
#include `util.h`
*
Functions
static uint8_t friendconn_id_not_valid (const Friend_Connections *fr_c, int friendcon_id)
static int realloc_friendconns (Friend_Connections *fr_c, uint32_t num)
static int create_friend_conn (Friend_Connections *fr_c)
static int wipe_friend_conn (Friend_Connections *fr_c, int friendcon_id)
static Friend_Conn * get_conn (const Friend_Connections *fr_c, int friendcon_id)
int getfriend_conn_id_pk (Friend_Connections *fr_c, const uint8_t *real_pk)
int friend_add_tcp_relay (Friend_Connections *fr_c, int friendcon_id, IP_Port ip_port, const uint8_t *public_key)
static void connect_to_saved_tcp_relays (Friend_Connections *fr_c, int friendcon_id, unsigned int number)
static unsigned int send_relays (Friend_Connections *fr_c, int friendcon_id)
static int tcp_relay_node_callback (void *object, uint32_t number, IP_Port ip_port, const uint8_t *public_key)
static int friend_new_connection (Friend_Connections *fr_c, int friendcon_id)
static void dht_ip_callback (void *object, int32_t number, IP_Port ip_port)
static void change_dht_pk (Friend_Connections *fr_c, int friendcon_id, const uint8_t *dht_public_key)
static int handle_status (void *object, int number, uint8_t status)
static void dht_pk_callback (void *object, int32_t number, const uint8_t *dht_public_key)
static int handle_packet (void *object, int number, uint8_t *data, uint16_t length)
static int handle_lossy_packet (void *object, int number, const uint8_t *data, uint16_t length)
static int handle_new_connections (void *object, New_Connection *n_c)
static int send_ping (const Friend_Connections *fr_c, int friendcon_id)
int friend_connection_lock (Friend_Connections *fr_c, int friendcon_id)
unsigned int friend_con_connected (Friend_Connections *fr_c, int friendcon_id)
int get_friendcon_public_keys (uint8_t *real_pk, uint8_t *dht_temp_pk, Friend_Connections *fr_c, int friendcon_id)
void set_dht_temp_pk (Friend_Connections *fr_c, int friendcon_id, const uint8_t *dht_temp_pk)
int friend_connection_callbacks (Friend_Connections *fr_c, int friendcon_id, unsigned int index, int(*status_callback)(void *object, int id, uint8_t status), int(*data_callback)(void *object, int id, uint8_t *data, uint16_t length), int(*lossy_data_callback)(void *object, int id, const uint8_t *data, uint16_t length), void *object, int number)
int friend_connection_crypt_connection_id (Friend_Connections *fr_c, int friendcon_id)
int new_friend_connection (Friend_Connections *fr_c, const uint8_t *real_public_key)
int kill_friend_connection (Friend_Connections *fr_c, int friendcon_id)
void set_friend_request_callback (Friend_Connections *fr_c, int(*fr_request_callback)(void *, const uint8_t *, const uint8_t *, uint16_t), void *object)
int send_friend_request_packet (Friend_Connections *fr_c, int friendcon_id, uint32_t nospam_num, const uint8_t *data, uint16_t length)
Friend_Connections * new_friend_connections (Onion_Client *onion_c)
static void LANdiscovery (Friend_Connections *fr_c)
void do_friend_connections (Friend_Connections *fr_c)
void kill_friend_connections (Friend_Connections *fr_c)
Function Documentation
static void change_dht_pk (Friend_Connections * fr_c, int friendcon_id, const uint8_t * dht_public_key) [static]
Definition at line 287 of file friend_connection.c.
References Friend_Connections::dht, DHT_addfriend(), DHT_delfriend(), dht_ip_callback(), Friend_Conn::dht_lock, Friend_Conn::dht_pk_lastrecv, Friend_Conn::dht_temp_pk, get_conn(), printf(), and unix_time().
Referenced by dht_pk_callback(), and handle_new_connections().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return;
    friend_con->dht_pk_lastrecv = unix_time();
    if (friend_con->dht_lock) {
        if (DHT_delfriend(fr_c->dht, friend_con->dht_temp_pk, friend_con->
      dht_lock) != 0) {
            printf("a. Could not delete dht peer. Please report this.\n");
            return;
        }
        friend_con->dht_lock = 0;
    }
    DHT_addfriend(fr_c->dht, dht_public_key, dht_ip_callback, fr_c,
      friendcon_id, &friend_con->dht_lock);
    memcpy(friend_con->dht_temp_pk, dht_public_key, crypto_box_PUBLICKEYBYTES);
}
static void connect_to_saved_tcp_relays (Friend_Connections * fr_c, int friendcon_id, unsigned int number) [static]
Definition at line 189 of file friend_connection.c.
References add_tcp_relay_peer(), Friend_Conn::crypt_connection_id, IP::family, FRIEND_MAX_STORED_TCP_RELAYS, get_conn(), i, IP_Port::ip, Node_format::ip_port, Friend_Connections::net_crypto, Node_format::public_key, Friend_Conn::tcp_relay_counter, and Friend_Conn::tcp_relays.
Referenced by do_friend_connections().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return;
    unsigned int i;
    for (i = 0; (i < FRIEND_MAX_STORED_TCP_RELAYS) && (number != 0); ++
      i) {
        uint16_t index = (friend_con->tcp_relay_counter - (i + 1)) %
      FRIEND_MAX_STORED_TCP_RELAYS;
        if (friend_con->tcp_relays[index].ip_port.ip.family) {
            if (add_tcp_relay_peer(fr_c->net_crypto, friend_con->
      crypt_connection_id, friend_con->tcp_relays[index].
      ip_port,
                                   friend_con->tcp_relays[index].
      public_key) == 0) {
                --number;
            }
        }
    }
}
static int create_friend_conn (Friend_Connections * fr_c) [static]
Definition at line 76 of file friend_connection.c.
References Friend_Connections::conns, FRIENDCONN_STATUS_NONE, i, Friend_Connections::num_cons, realloc_friendconns(), and Friend_Conn::status.
Referenced by new_friend_connection().
{
    uint32_t i;
    for (i = 0; i < fr_c->num_cons; ++i) {
        if (fr_c->conns[i].status == FRIENDCONN_STATUS_NONE)
            return i;
    }
    int id = -1;
    if (realloc_friendconns(fr_c, fr_c->num_cons + 1) == 0) {
        id = fr_c->num_cons;
        ++fr_c->num_cons;
        memset(&(fr_c->conns[id]), 0, sizeof(Friend_Conn));
    }
    return id;
}
static void dht_ip_callback (void * object, int32_t number, IP_Port ip_port) [static]
Definition at line 265 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, Friend_Conn::dht_ip_port, Friend_Conn::dht_ip_port_lastrecv, Friend_Conn::dht_temp_pk, friend_add_tcp_relay(), friend_new_connection(), get_conn(), Friend_Conn::hosting_tcp_relay, Friend_Connections::net_crypto, set_direct_ip_port(), and unix_time().
Referenced by change_dht_pk().
{
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return;
    if (friend_con->crypt_connection_id == -1) {
        friend_new_connection(fr_c, number);
    }
    set_direct_ip_port(fr_c->net_crypto, friend_con->
      crypt_connection_id, ip_port, 1);
    friend_con->dht_ip_port = ip_port;
    friend_con->dht_ip_port_lastrecv = unix_time();
    if (friend_con->hosting_tcp_relay) {
        friend_add_tcp_relay(fr_c, number, ip_port, friend_con->
      dht_temp_pk);
        friend_con->hosting_tcp_relay = 0;
    }
}
static void dht_pk_callback (void * object, int32_t number, const uint8_t * dht_public_key) [static]
Definition at line 351 of file friend_connection.c.
References change_dht_pk(), Friend_Conn::crypt_connection_id, crypto_kill(), Friend_Conn::dht_temp_pk, friend_new_connection(), get_conn(), handle_status(), Friend_Connections::net_crypto, Friend_Connections::onion_c, Friend_Conn::onion_friendnum, and onion_set_friend_DHT_pubkey().
Referenced by friend_new_connection(), handle_new_connections(), new_friend_connection(), and set_dht_temp_pk().
{
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return;
    if (memcmp(friend_con->dht_temp_pk, dht_public_key, crypto_box_PUBLICKEYBYTES) == 0)
        return;
    change_dht_pk(fr_c, number, dht_public_key);
    /* if pk changed, create a new connection.*/
    if (friend_con->crypt_connection_id != -1) {
        crypto_kill(fr_c->net_crypto, friend_con->
      crypt_connection_id);
        friend_con->crypt_connection_id = -1;
        handle_status(object, number, 0); /* Going offline. */
    }
    friend_new_connection(fr_c, number);
    onion_set_friend_DHT_pubkey(fr_c->onion_c, friend_con->
      onion_friendnum, dht_public_key);
}
void do_friend_connections (Friend_Connections * fr_c)
Definition at line 791 of file friend_connection.c.
References connect_to_saved_tcp_relays(), Friend_Conn::crypt_connection_id, crypto_kill(), Friend_Connections::dht, DHT_delfriend(), Friend_Conn::dht_ip_port, Friend_Conn::dht_ip_port_lastrecv, Friend_Conn::dht_lock, Friend_Conn::dht_pk_lastrecv, Friend_Conn::dht_temp_pk, IP::family, FRIEND_CONNECTION_TIMEOUT, FRIEND_DHT_TIMEOUT, friend_new_connection(), FRIEND_PING_INTERVAL, FRIENDCONN_STATUS_CONNECTED, FRIENDCONN_STATUS_CONNECTING, get_conn(), handle_status(), i, IP_Port::ip, LANdiscovery(), MAX_FRIEND_TCP_CONNECTIONS, Friend_Connections::net_crypto, Friend_Connections::num_cons, Friend_Conn::ping_lastrecv, Friend_Conn::ping_lastsent, send_ping(), send_relays(), set_direct_ip_port(), SHARE_RELAYS_INTERVAL, Friend_Conn::share_relays_lastsent, Friend_Conn::status, and unix_time().
Referenced by do_messenger().
{
    uint32_t i;
    uint64_t temp_time = unix_time();
    for (i = 0; i < fr_c->num_cons; ++i) {
        Friend_Conn *friend_con = get_conn(fr_c, i);
        if (friend_con) {
            if (friend_con->status == FRIENDCONN_STATUS_CONNECTING) {
                if (friend_con->dht_pk_lastrecv +
      FRIEND_DHT_TIMEOUT < temp_time) {
                    if (friend_con->dht_lock) {
                        DHT_delfriend(fr_c->dht, friend_con->
      dht_temp_pk, friend_con->dht_lock);
                        friend_con->dht_lock = 0;
                    }
                }
                if (friend_con->dht_ip_port_lastrecv +
      FRIEND_DHT_TIMEOUT < temp_time) {
                    friend_con->dht_ip_port.ip.family = 0;
                }
                if (friend_con->dht_lock) {
                    if (friend_new_connection(fr_c, i) == 0) {
                        set_direct_ip_port(fr_c->net_crypto, friend_con->
      crypt_connection_id, friend_con->dht_ip_port, 0);
                        connect_to_saved_tcp_relays(fr_c, i, (
      MAX_FRIEND_TCP_CONNECTIONS / 2)); /* Only fill it half up. */
                    }
                }
            } else if (friend_con->status == FRIENDCONN_STATUS_CONNECTED)
      {
                if (friend_con->ping_lastsent +
      FRIEND_PING_INTERVAL < temp_time) {
                    send_ping(fr_c, i);
                }
                if (friend_con->share_relays_lastsent +
      SHARE_RELAYS_INTERVAL < temp_time) {
                    send_relays(fr_c, i);
                }
                if (friend_con->ping_lastrecv +
      FRIEND_CONNECTION_TIMEOUT < temp_time) {
                    /* If we stopped receiving ping packets, kill it. */
                    crypto_kill(fr_c->net_crypto, friend_con->
      crypt_connection_id);
                    friend_con->crypt_connection_id = -1;
                    handle_status(fr_c, i, 0); /* Going offline. */
                }
            }
        }
    }
    LANdiscovery(fr_c);
}
int friend_add_tcp_relay (Friend_Connections * fr_c, int friendcon_id, IP_Port ip_port, const uint8_t * public_key)
Definition at line 154 of file friend_connection.c.
References add_tcp_relay_peer(), Friend_Conn::crypt_connection_id, Friend_Conn::dht_ip_port, Friend_Conn::dht_temp_pk, IP::family, FRIEND_MAX_STORED_TCP_RELAYS, get_conn(), Friend_Conn::hosting_tcp_relay, i, IP_Port::ip, Node_format::ip_port, Local_ip(), Friend_Connections::net_crypto, Node_format::public_key, Friend_Conn::tcp_relay_counter, and Friend_Conn::tcp_relays.
Referenced by dht_ip_callback(), handle_packet(), send_relays(), and tcp_relay_node_callback().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    /* Local ip and same pk means that they are hosting a TCP relay. */
    if (Local_ip(ip_port.ip) && memcmp(friend_con->dht_temp_pk,
      public_key, crypto_box_PUBLICKEYBYTES) == 0) {
        if (friend_con->dht_ip_port.ip.family != 0) {
            ip_port.ip = friend_con->dht_ip_port.ip;
        } else {
            friend_con->hosting_tcp_relay = 0;
        }
    }
    unsigned int i;
    uint16_t index = friend_con->tcp_relay_counter %
      FRIEND_MAX_STORED_TCP_RELAYS;
    for (i = 0; i < FRIEND_MAX_STORED_TCP_RELAYS; ++
      i) {
        if (friend_con->tcp_relays[i].ip_port.ip.family != 0
                && memcmp(friend_con->tcp_relays[i].public_key,
      public_key, crypto_box_PUBLICKEYBYTES) == 0) {
            memset(&friend_con->tcp_relays[i], 0, sizeof(Node_format));
        }
    }
    friend_con->tcp_relays[index].ip_port = ip_port;
    memcpy(friend_con->tcp_relays[index].public_key,
      public_key, crypto_box_PUBLICKEYBYTES);
    ++friend_con->tcp_relay_counter;
    return add_tcp_relay_peer(fr_c->net_crypto, friend_con->
      crypt_connection_id, ip_port, public_key);
}
unsigned int friend_con_connected (Friend_Connections * fr_c, int friendcon_id)
Definition at line 561 of file friend_connection.c.
References get_conn(), and Friend_Conn::status.
Referenced by connect_to_closest(), init_new_friend(), and m_delfriend().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return 0;
    return friend_con->status;
}
int friend_connection_callbacks (Friend_Connections * fr_c, int friendcon_id, unsigned int index, int(*)(void *object, int id, uint8_t status) status_callback, int(*)(void *object, int id, uint8_t *data, uint16_t length) data_callback, int(*)(void *object, int id, const uint8_t *data, uint16_t length) lossy_data_callback, void * object, int number)
Definition at line 605 of file friend_connection.c.
References Friend_Conn::callbacks, Friend_Conn::data_callback, data_callback(), Friend_Conn::data_callback_id, Friend_Conn::data_callback_object, get_conn(), Friend_Conn::lossy_data_callback, Friend_Conn::lossy_data_callback_id, Friend_Conn::lossy_data_callback_object, MAX_FRIEND_CONNECTION_CALLBACKS, Friend_Conn::status_callback, status_callback(), Friend_Conn::status_callback_id, and Friend_Conn::status_callback_object.
Referenced by add_conn_to_groupchat(), init_new_friend(), and m_delfriend().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (index >= MAX_FRIEND_CONNECTION_CALLBACKS)
        return -1;
    friend_con->callbacks[index].status_callback =
      status_callback;
    friend_con->callbacks[index].data_callback =
      data_callback;
    friend_con->callbacks[index].lossy_data_callback = lossy_data_callback;
    friend_con->callbacks[index].status_callback_object =
        friend_con->callbacks[index].data_callback_object =
            friend_con->callbacks[index].lossy_data_callback_object =
      object;
    friend_con->callbacks[index].status_callback_id =
        friend_con->callbacks[index].data_callback_id =
            friend_con->callbacks[index].lossy_data_callback_id = number;
    return 0;
}
int friend_connection_crypt_connection_id (Friend_Connections * fr_c, int friendcon_id)
Definition at line 637 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, and get_conn().
Referenced by do_reqchunk_filecb(), file_data(), friend_received_packet(), m_get_friend_connectionstatus(), m_send_message_generic(), send_custom_lossless_packet(), send_custom_lossy_packet(), send_file_data_packet(), send_lossy_group_peer(), send_offline_packet(), send_online_packet(), send_packet_group_peer(), send_packet_online(), and write_cryptpacket_id().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    return friend_con->crypt_connection_id;
}
int friend_connection_lock (Friend_Connections * fr_c, int friendcon_id)
Definition at line 546 of file friend_connection.c.
References get_conn(), and Friend_Conn::lock_count.
Referenced by add_conn_to_groupchat().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    ++friend_con->lock_count;
    return 0;
}
static int friend_new_connection (Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 493 of file friend_connection.c.
References connection_data_handler(), connection_lossy_data_handler(), connection_status_handler(), Friend_Conn::crypt_connection_id, Friend_Conn::dht_lock, dht_pk_callback(), Friend_Conn::dht_temp_pk, get_conn(), handle_lossy_packet(), handle_packet(), handle_status(), nc_dht_pk_callback(), Friend_Connections::net_crypto, new_crypto_connection(), and Friend_Conn::real_public_key.
Referenced by dht_ip_callback(), dht_pk_callback(), and do_friend_connections().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (friend_con->crypt_connection_id != -1) {
        return -1;
    }
    /* If dht_temp_pk does not contains a pk. */
    if (!friend_con->dht_lock) {
        return -1;
    }
    int id = new_crypto_connection(fr_c->net_crypto, friend_con->
      real_public_key, friend_con->dht_temp_pk);
    if (id == -1)
        return -1;
    friend_con->crypt_connection_id = id;
    connection_status_handler(fr_c->net_crypto, id, &
      handle_status, fr_c, friendcon_id);
    connection_data_handler(fr_c->net_crypto, id, &
      handle_packet, fr_c, friendcon_id);
    connection_lossy_data_handler(fr_c->net_crypto, id, &
      handle_lossy_packet, fr_c, friendcon_id);
    nc_dht_pk_callback(fr_c->net_crypto, id, &
      dht_pk_callback, fr_c, friendcon_id);
    return 0;
}
static uint8_t friendconn_id_not_valid (const Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 34 of file friend_connection.c.
References Friend_Connections::conns, FRIENDCONN_STATUS_NONE, Friend_Connections::num_cons, and Friend_Conn::status.
Referenced by get_conn(), and wipe_friend_conn().
{
    if ((unsigned int)friendcon_id >= fr_c->num_cons)
        return 1;
    if (fr_c->conns == NULL)
        return 1;
    if (fr_c->conns[friendcon_id].status == FRIENDCONN_STATUS_NONE)
        return 1;
    return 0;
}
static Friend_Conn* get_conn (const Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 122 of file friend_connection.c.
References Friend_Connections::conns, and friendconn_id_not_valid().
Referenced by change_dht_pk(), connect_to_saved_tcp_relays(), dht_ip_callback(), dht_pk_callback(), do_friend_connections(), friend_add_tcp_relay(), friend_con_connected(), friend_connection_callbacks(), friend_connection_crypt_connection_id(), friend_connection_lock(), friend_new_connection(), get_friendcon_public_keys(), getfriend_conn_id_pk(), handle_lossy_packet(), handle_new_connections(), handle_packet(), handle_status(), kill_friend_connection(), send_friend_request_packet(), send_ping(), send_relays(), and tcp_relay_node_callback().
{
    if (friendconn_id_not_valid(fr_c, friendcon_id))
        return 0;
    return &fr_c->conns[friendcon_id];
}
int get_friendcon_public_keys (uint8_t * real_pk, uint8_t * dht_temp_pk, Friend_Connections * fr_c, int friendcon_id)
Definition at line 576 of file friend_connection.c.
References Friend_Conn::dht_temp_pk, get_conn(), and Friend_Conn::real_public_key.
Referenced by connect_to_closest(), handle_friend_invite_packet(), and send_lossy_all_close().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (real_pk)
        memcpy(real_pk, friend_con->real_public_key, crypto_box_PUBLICKEYBYTES);
    if (dht_temp_pk)
        memcpy(dht_temp_pk, friend_con->dht_temp_pk, crypto_box_PUBLICKEYBYTES);
    return 0;
}
int getfriend_conn_id_pk (Friend_Connections * fr_c, const uint8_t * real_pk)
Definition at line 133 of file friend_connection.c.
References get_conn(), i, Friend_Connections::num_cons, and Friend_Conn::real_public_key.
Referenced by connect_to_closest(), delpeer(), handle_new_connections(), and new_friend_connection().
{
    uint32_t i;
    for (i = 0; i < fr_c->num_cons; ++i) {
        Friend_Conn *friend_con = get_conn(fr_c, i);
        if (friend_con) {
            if (memcmp(friend_con->real_public_key, real_pk, crypto_box_PUBLICKEYBYTES) == 0
      )
                return i;
        }
    }
    return -1;
}
static int handle_lossy_packet (void * object, int number, const uint8_t * data, uint16_t length) [static]
Definition at line 426 of file friend_connection.c.
References Friend_Conn::callbacks, get_conn(), i, Friend_Conn::lossy_data_callback, Friend_Conn::lossy_data_callback_id, Friend_Conn::lossy_data_callback_object, and MAX_FRIEND_CONNECTION_CALLBACKS.
Referenced by friend_new_connection(), and handle_new_connections().
{
    if (length == 0)
        return -1;
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_CONNECTION_CALLBACKS; ++
      i) {
        if (friend_con->callbacks[i].lossy_data_callback)
            friend_con->callbacks[i].lossy_data_callback(friend_con->
      callbacks[i].lossy_data_callback_object,
                    friend_con->callbacks[i].lossy_data_callback_id,
      data, length);
        friend_con = get_conn(fr_c, number);
        if (!friend_con)
            return -1;
    }
    return 0;
}
static int handle_new_connections (void * object, New_Connection * n_c) [static]
Definition at line 453 of file friend_connection.c.
References accept_crypto_connection(), change_dht_pk(), connection_data_handler(), connection_lossy_data_handler(), connection_status_handler(), Friend_Conn::crypt_connection_id, Friend_Conn::dht_ip_port, Friend_Conn::dht_ip_port_lastrecv, dht_pk_callback(), New_Connection::dht_public_key, Friend_Conn::dht_temp_pk, IP::family, get_conn(), getfriend_conn_id_pk(), handle_lossy_packet(), handle_packet(), handle_status(), IP_Port::ip, nc_dht_pk_callback(), Friend_Connections::net_crypto, New_Connection::public_key, set_direct_ip_port(), New_Connection::source, and unix_time().
Referenced by new_friend_connections().
{
    Friend_Connections *fr_c = object;
    int friendcon_id = getfriend_conn_id_pk(fr_c, n_c->
      public_key);
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (friend_con) {
        if (friend_con->crypt_connection_id != -1)
            return -1;
        int id = accept_crypto_connection(fr_c->
      net_crypto, n_c);
        if (id == -1) {
            return -1;
        }
        connection_status_handler(fr_c->net_crypto, id, &
      handle_status, fr_c, friendcon_id);
        connection_data_handler(fr_c->net_crypto, id, &
      handle_packet, fr_c, friendcon_id);
        connection_lossy_data_handler(fr_c->
      net_crypto, id, &handle_lossy_packet, fr_c, friendcon_id);
        friend_con->crypt_connection_id = id;
        if (n_c->source.ip.family != AF_INET && n_c->source.
      ip.family != AF_INET6) {
            set_direct_ip_port(fr_c->net_crypto, friend_con->
      crypt_connection_id, friend_con->dht_ip_port, 0);
        } else {
            friend_con->dht_ip_port = n_c->source;
            friend_con->dht_ip_port_lastrecv = unix_time();
        }
        if (memcmp(friend_con->dht_temp_pk, n_c->dht_public_key,
      crypto_box_PUBLICKEYBYTES) != 0) {
            change_dht_pk(fr_c, friendcon_id, n_c->dht_public_key);
        }
        nc_dht_pk_callback(fr_c->net_crypto, id, &
      dht_pk_callback, fr_c, friendcon_id);
        return 0;
    }
    return -1;
}
static int handle_packet (void * object, int number, uint8_t * data, uint16_t length) [static]
Definition at line 375 of file friend_connection.c.
References Friend_Conn::callbacks, Friend_Conn::data_callback, Friend_Conn::data_callback_id, Friend_Conn::data_callback_object, Friend_Connections::fr_request_callback, Friend_Connections::fr_request_object, friend_add_tcp_relay(), get_conn(), i, MAX_FRIEND_CONNECTION_CALLBACKS, MAX_SHARED_RELAYS, PACKET_ID_ALIVE, PACKET_ID_FRIEND_REQUESTS, PACKET_ID_SHARE_RELAYS, Friend_Conn::ping_lastrecv, make-funny-savefile::public_key, Friend_Conn::real_public_key, unix_time(), and unpack_nodes().
Referenced by friend_new_connection(), and handle_new_connections().
{
    if (length == 0)
        return -1;
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return -1;
    if (data[0] == PACKET_ID_FRIEND_REQUESTS) {
        if (fr_c->fr_request_callback)
            fr_c->fr_request_callback(fr_c->fr_request_object,
      friend_con->real_public_key, data, length);
        return 0;
    } else if (data[0] == PACKET_ID_ALIVE) {
        friend_con->ping_lastrecv = unix_time();
        return 0;
    } else if (data[0] == PACKET_ID_SHARE_RELAYS) {
        Node_format nodes[MAX_SHARED_RELAYS];
        int n;
        if ((n = unpack_nodes(nodes, MAX_SHARED_RELAYS, NULL,
      data + 1, length - 1, 1)) == -1)
            return -1;
        int j;
        for (j = 0; j < n; j++) {
            friend_add_tcp_relay(fr_c, number, nodes[j].ip_port, nodes[j].
      public_key);
        }
        return 0;
    }
    unsigned int i;
    for (i = 0; i < MAX_FRIEND_CONNECTION_CALLBACKS; ++
      i) {
        if (friend_con->callbacks[i].data_callback)
            friend_con->callbacks[i].data_callback(friend_con->
      callbacks[i].data_callback_object,
                                                   friend_con->callbacks[i].
      data_callback_id, data, length);
        friend_con = get_conn(fr_c, number);
        if (!friend_con)
            return -1;
    }
    return 0;
}
static int handle_status (void * object, int number, uint8_t status) [static]
Definition at line 309 of file friend_connection.c.
References Friend_Conn::callbacks, Friend_Conn::crypt_connection_id, Friend_Conn::dht_pk_lastrecv, FRIENDCONN_STATUS_CONNECTED, FRIENDCONN_STATUS_CONNECTING, get_conn(), Friend_Conn::hosting_tcp_relay, i, MAX_FRIEND_CONNECTION_CALLBACKS, Friend_Connections::onion_c, Friend_Conn::onion_friendnum, onion_set_friend_online(), Friend_Conn::ping_lastrecv, Friend_Conn::share_relays_lastsent, Friend_Conn::status, Friend_Conn::status_callback, Friend_Conn::status_callback_id, Friend_Conn::status_callback_object, and unix_time().
Referenced by dht_pk_callback(), do_friend_connections(), friend_new_connection(), and handle_new_connections().
{
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return -1;
    _Bool call_cb = 0;
    if (status) { /* Went online. */
        call_cb = 1;
        friend_con->status = FRIENDCONN_STATUS_CONNECTED;
        friend_con->ping_lastrecv = unix_time();
        friend_con->share_relays_lastsent = 0;
        onion_set_friend_online(fr_c->onion_c, friend_con->
      onion_friendnum, status);
    } else { /* Went offline. */
        if (friend_con->status != FRIENDCONN_STATUS_CONNECTING) {
            call_cb = 1;
            friend_con->dht_pk_lastrecv = unix_time();
            onion_set_friend_online(fr_c->onion_c, friend_con->
      onion_friendnum, status);
        }
        friend_con->status = FRIENDCONN_STATUS_CONNECTING;
        friend_con->crypt_connection_id = -1;
        friend_con->hosting_tcp_relay = 0;
    }
    if (call_cb) {
        unsigned int i;
        for (i = 0; i < MAX_FRIEND_CONNECTION_CALLBACKS; ++
      i) {
            if (friend_con->callbacks[i].status_callback)
                friend_con->callbacks[i].status_callback(friend_con->
      callbacks[i].status_callback_object,
                        friend_con->callbacks[i].status_callback_id, status);
        }
    }
    return 0;
}
int kill_friend_connection (Friend_Connections * fr_c, int friendcon_id)
Definition at line 690 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, crypto_kill(), Friend_Connections::dht, DHT_delfriend(), Friend_Conn::dht_lock, Friend_Conn::dht_temp_pk, get_conn(), Friend_Conn::lock_count, Friend_Connections::net_crypto, Friend_Connections::onion_c, onion_delfriend(), Friend_Conn::onion_friendnum, and wipe_friend_conn().
Referenced by connect_to_closest(), del_groupchat(), handle_direct_packet(), handle_packet_online(), kill_friend_connections(), m_delfriend(), and remove_close_conn().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    if (friend_con->lock_count) {
        --friend_con->lock_count;
        return 0;
    }
    onion_delfriend(fr_c->onion_c, friend_con->
      onion_friendnum);
    crypto_kill(fr_c->net_crypto, friend_con->
      crypt_connection_id);
    if (friend_con->dht_lock) {
        DHT_delfriend(fr_c->dht, friend_con->dht_temp_pk, friend_con->
      dht_lock);
    }
    return wipe_friend_conn(fr_c, friendcon_id);
}
void kill_friend_connections (Friend_Connections * fr_c)
Definition at line 842 of file friend_connection.c.
References Friend_Connections::dht, i, kill_friend_connection(), LANdiscovery_kill(), and Friend_Connections::num_cons.
Referenced by kill_messenger(), and new_messenger().
{
    if (!fr_c)
        return;
    uint32_t i;
    for (i = 0; i < fr_c->num_cons; ++i) {
        kill_friend_connection(fr_c, i);
    }
    LANdiscovery_kill(fr_c->dht);
    free(fr_c);
}
static void LANdiscovery (Friend_Connections * fr_c) [static]
Definition at line 782 of file friend_connection.c.
References Friend_Connections::dht, LAN_DISCOVERY_INTERVAL, Friend_Connections::last_LANdiscovery, send_LANdiscovery(), TOX_PORT_DEFAULT, and unix_time().
Referenced by do_friend_connections().
{
    if (fr_c->last_LANdiscovery + LAN_DISCOVERY_INTERVAL <
      unix_time()) {
        send_LANdiscovery(htons(TOX_PORT_DEFAULT), fr_c->
      dht);
        fr_c->last_LANdiscovery = unix_time();
    }
}
int new_friend_connection (Friend_Connections * fr_c, const uint8_t * real_public_key)
Definition at line 653 of file friend_connection.c.
References Friend_Connections::conns, create_friend_conn(), Friend_Conn::crypt_connection_id, dht_pk_callback(), FRIENDCONN_STATUS_CONNECTING, getfriend_conn_id_pk(), Friend_Conn::lock_count, onion_addfriend(), Friend_Connections::onion_c, onion_dht_pk_callback(), Friend_Conn::onion_friendnum, Friend_Conn::real_public_key, recv_tcp_relay_handler(), Friend_Conn::status, and tcp_relay_node_callback().
Referenced by connect_to_closest(), and init_new_friend().
{
    int friendcon_id = getfriend_conn_id_pk(fr_c, real_public_key);
    if (friendcon_id != -1) {
        ++fr_c->conns[friendcon_id].lock_count;
        return friendcon_id;
    }
    friendcon_id = create_friend_conn(fr_c);
    if (friendcon_id == -1)
        return -1;
    int32_t onion_friendnum = onion_addfriend(fr_c->onion_c, real_public_key);
    if (onion_friendnum == -1)
        return -1;
    Friend_Conn *friend_con = &fr_c->conns[friendcon_id];
    friend_con->crypt_connection_id = -1;
    friend_con->status = FRIENDCONN_STATUS_CONNECTING;
    memcpy(friend_con->real_public_key, real_public_key, crypto_box_PUBLICKEYBYTES);
    friend_con->onion_friendnum = onion_friendnum;
    recv_tcp_relay_handler(fr_c->onion_c, onion_friendnum, &
      tcp_relay_node_callback, fr_c, friendcon_id);
    onion_dht_pk_callback(fr_c->onion_c, onion_friendnum, &
      dht_pk_callback, fr_c, friendcon_id);
    return friendcon_id;
}
Friend_Connections* new_friend_connections (Onion_Client * onion_c)
Definition at line 761 of file friend_connection.c.
References Onion_Client::c, Friend_Connections::dht, Onion_Client::dht, handle_new_connections(), LANdiscovery_init(), Friend_Connections::net_crypto, new_connection_handler(), and Friend_Connections::onion_c.
Referenced by new_messenger().
{
    if (!onion_c)
        return NULL;
    Friend_Connections *temp = calloc(1, sizeof(
      Friend_Connections));
    if (temp == NULL)
        return NULL;
    temp->dht = onion_c->dht;
    temp->net_crypto = onion_c->c;
    temp->onion_c = onion_c;
    new_connection_handler(temp->net_crypto, &
      handle_new_connections, temp);
    LANdiscovery_init(temp->dht);
    return temp;
}
static int realloc_friendconns (Friend_Connections * fr_c, uint32_t num) [static]
Definition at line 54 of file friend_connection.c.
References Friend_Connections::conns.
Referenced by create_friend_conn(), and wipe_friend_conn().
{
    if (num == 0) {
        free(fr_c->conns);
        fr_c->conns = NULL;
        return 0;
    }
    Friend_Conn *newgroup_cons = realloc(fr_c->conns, num * sizeof(
      Friend_Conn));
    if (newgroup_cons == NULL)
        return -1;
    fr_c->conns = newgroup_cons;
    return 0;
}
int send_friend_request_packet (Friend_Connections * fr_c, int friendcon_id, uint32_t nospam_num, const uint8_t * data, uint16_t length)
Definition at line 731 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, CRYPTO_PACKET_FRIEND_REQ, FRIENDCONN_STATUS_CONNECTED, get_conn(), Friend_Connections::net_crypto, num, Friend_Connections::onion_c, ONION_CLIENT_MAX_DATA_SIZE, Friend_Conn::onion_friendnum, PACKET_ID_FRIEND_REQUESTS, send_onion_data(), Friend_Conn::status, and write_cryptpacket().
Referenced by do_friends().
{
    if (1 + sizeof(nospam_num) + length > ONION_CLIENT_MAX_DATA_SIZE || length ==
       0)
        return -1;
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    uint8_t packet[1 + sizeof(nospam_num) + length];
    memcpy(packet + 1, &nospam_num, sizeof(nospam_num));
    memcpy(packet + 1 + sizeof(nospam_num), data, length);
    if (friend_con->status == FRIENDCONN_STATUS_CONNECTED) {
        packet[0] = PACKET_ID_FRIEND_REQUESTS;
        return write_cryptpacket(fr_c->net_crypto, friend_con->
      crypt_connection_id, packet, sizeof(packet), 0) != -1;
    } else {
        packet[0] = CRYPTO_PACKET_FRIEND_REQ;
        int num = send_onion_data(fr_c->onion_c, friend_con->
      onion_friendnum, packet, sizeof(packet));
        if (num <= 0)
            return -1;
        return num;
    }
}
static int send_ping (const Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 523 of file friend_connection.c.
References Friend_Conn::crypt_connection_id, get_conn(), Friend_Connections::net_crypto, PACKET_ID_ALIVE, Friend_Conn::ping_lastsent, unix_time(), and write_cryptpacket().
Referenced by do_friend_connections().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return -1;
    uint8_t ping = PACKET_ID_ALIVE;
    int64_t ret = write_cryptpacket(fr_c->net_crypto, friend_con->
      crypt_connection_id, &ping, sizeof(ping), 0);
    if (ret != -1) {
        friend_con->ping_lastsent = unix_time();
        return 0;
    }
    return -1;
}
static unsigned int send_relays (Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 210 of file friend_connection.c.
References copy_connected_tcp_relays(), Friend_Conn::crypt_connection_id, make-funny-savefile::data, friend_add_tcp_relay(), get_conn(), i, MAX_SHARED_RELAYS, Friend_Connections::net_crypto, pack_nodes(), PACKET_ID_SHARE_RELAYS, make-funny-savefile::public_key, Friend_Conn::share_relays_lastsent, unix_time(), and write_cryptpacket().
Referenced by do_friend_connections().
{
    Friend_Conn *friend_con = get_conn(fr_c, friendcon_id);
    if (!friend_con)
        return 0;
    Node_format nodes[MAX_SHARED_RELAYS];
    uint8_t data[1024];
    int n, length;
    n = copy_connected_tcp_relays(fr_c->net_crypto, nodes,
      MAX_SHARED_RELAYS);
    int i;
    for (i = 0; i < n; ++i) {
        /* Associated the relays being sent with this connection.
           On receiving the peer will do the same which will establish the connection. */
        friend_add_tcp_relay(fr_c, friendcon_id, nodes[i].ip_port, nodes[i].
      public_key);
    }
    length = pack_nodes(data + 1, sizeof(data) - 1, nodes, n);
    if (length <= 0)
        return 0;
    data[0] = PACKET_ID_SHARE_RELAYS;
    ++length;
    if (write_cryptpacket(fr_c->net_crypto, friend_con->
      crypt_connection_id, data, length, 0) != -1) {
        friend_con->share_relays_lastsent = unix_time();
        return 1;
    }
    return 0;
}
void set_dht_temp_pk (Friend_Connections * fr_c, int friendcon_id, const uint8_t * dht_temp_pk)
Definition at line 594 of file friend_connection.c.
References dht_pk_callback().
Referenced by connect_to_closest().
{
    dht_pk_callback(fr_c, friendcon_id, dht_temp_pk);
}
void set_friend_request_callback (Friend_Connections * fr_c, int(*)(void *, const uint8_t *, const uint8_t *, uint16_t) fr_request_callback, void * object)
Definition at line 717 of file friend_connection.c.
References CRYPTO_PACKET_FRIEND_REQ, Friend_Connections::fr_request_callback, Friend_Connections::fr_request_object, Friend_Connections::onion_c, and oniondata_registerhandler().
Referenced by friendreq_init().
{
    fr_c->fr_request_callback = fr_request_callback;
    fr_c->fr_request_object = object;
    oniondata_registerhandler(fr_c->onion_c,
      CRYPTO_PACKET_FRIEND_REQ, fr_request_callback, object);
}
static int tcp_relay_node_callback (void * object, uint32_t number, IP_Port ip_port, const uint8_t * public_key) [static]
Definition at line 248 of file friend_connection.c.
References add_tcp_relay(), Friend_Conn::crypt_connection_id, friend_add_tcp_relay(), get_conn(), and Friend_Connections::net_crypto.
Referenced by new_friend_connection(), and recv_tcp_relay_handler().
{
    Friend_Connections *fr_c = object;
    Friend_Conn *friend_con = get_conn(fr_c, number);
    if (!friend_con)
        return -1;
    if (friend_con->crypt_connection_id != -1) {
        return friend_add_tcp_relay(fr_c, number, ip_port,
      public_key);
    } else {
        return add_tcp_relay(fr_c->net_crypto, ip_port,
      public_key);
    }
}
static int wipe_friend_conn (Friend_Connections * fr_c, int friendcon_id) [static]
Definition at line 101 of file friend_connection.c.
References Friend_Connections::conns, friendconn_id_not_valid(), FRIENDCONN_STATUS_NONE, i, Friend_Connections::num_cons, realloc_friendconns(), and Friend_Conn::status.
Referenced by kill_friend_connection().
{
    if (friendconn_id_not_valid(fr_c, friendcon_id))
        return -1;
    uint32_t i;
    memset(&(fr_c->conns[friendcon_id]), 0 , sizeof(Friend_Conn));
    for (i = fr_c->num_cons; i != 0; --i) {
        if (fr_c->conns[i - 1].status != FRIENDCONN_STATUS_NONE)
            break;
    }
    if (fr_c->num_cons != i) {
        fr_c->num_cons = i;
        realloc_friendconns(fr_c, fr_c->num_cons);
    }
    return 0;
}