toxcore/DHT.h File Reference
#include `crypto_core.h`
*
#include `network.h`
*
#include `ping_array.h`
*
Data Structures
struct IPPTs
struct Hardening
struct IPPTsPng
struct Client_data
struct NAT
struct DHT_Friend
struct Node_format
struct Shared_Keys
struct Cryptopacket_Handles
struct DHT
Macros
#define MAX_FRIEND_CLIENTS 8
#define LCLIENT_LIST 32
#define MAX_SENT_NODES 4
#define PING_TIMEOUT 3
#define DHT_PING_ARRAY_SIZE 512
#define PING_INTERVAL 60
#define PINGS_MISSED_NODE_GOES_BAD 1
#define PING_ROUNDTRIP 2
#define BAD_NODE_TIMEOUT (PING_INTERVAL + PINGS_MISSED_NODE_GOES_BAD * (PING_INTERVAL + PING_ROUNDTRIP))
#define TOX_AF_INET 2
#define TOX_AF_INET6 10
#define TOX_TCP_INET 130
#define TOX_TCP_INET6 138
#define DHT_FAKE_FRIEND_NUMBER 4
#define DHT_FRIEND_MAX_LOCKS 32
#define MAX_KEYS_PER_SLOT 4
#define KEYS_TIMEOUT 600
Typedefs
typedef int(* cryptopacket_handler_callback)(void *object, IP_Port ip_port, const uint8_t *source_pubkey, const uint8_t *data, uint16_t len)
Functions
void to_net_family (IP *ip)
int to_host_family (IP *ip)
int packed_node_size (uint8_t ip_family)
int pack_nodes (uint8_t *data, uint16_t length, const Node_format *nodes, uint16_t number)
int unpack_nodes (Node_format *nodes, uint16_t max_num_nodes, uint16_t *processed_data_len, const uint8_t *data, uint16_t length, uint8_t tcp_enabled)
void get_shared_key (Shared_Keys *shared_keys, uint8_t *shared_key, const uint8_t *secret_key, const uint8_t *public_key)
void DHT_get_shared_key_recv (DHT *dht, uint8_t *shared_key, const uint8_t *public_key)
void DHT_get_shared_key_sent (DHT *dht, uint8_t *shared_key, const uint8_t *public_key)
void DHT_getnodes (DHT *dht, const IP_Port *from_ipp, const uint8_t *from_id, const uint8_t *which_id)
int DHT_addfriend (DHT *dht, const uint8_t *public_key, void(*ip_callback)(void *data, int32_t number, IP_Port), void *data, int32_t number, uint16_t *lock_count)
int DHT_delfriend (DHT *dht, const uint8_t *public_key, uint16_t lock_count)
int DHT_getfriendip (const DHT *dht, const uint8_t *public_key, IP_Port *ip_port)
int id_closest (const uint8_t *pk, const uint8_t *pk1, const uint8_t *pk2)
int get_close_nodes (const DHT *dht, const uint8_t *public_key, Node_format *nodes_list, sa_family_t sa_family, uint8_t is_LAN, uint8_t want_good)
uint16_t closelist_nodes (DHT *dht, Node_format *nodes, uint16_t max_num)
void do_DHT (DHT *dht)
void DHT_bootstrap (DHT *dht, IP_Port ip_port, const uint8_t *public_key)
int DHT_bootstrap_from_address (DHT *dht, const char *address, uint8_t ipv6enabled, uint16_t port, const uint8_t *public_key)
int DHT_connect_after_load (DHT *dht)
int route_packet (const DHT *dht, const uint8_t *public_key, const uint8_t *packet, uint16_t length)
int route_tofriend (const DHT *dht, const uint8_t *friend_id, const uint8_t *packet, uint16_t length)
void cryptopacket_registerhandler (DHT *dht, uint8_t byte, cryptopacket_handler_callback cb, void *object)
uint32_t DHT_size (const DHT *dht)
void DHT_save (DHT *dht, uint8_t *data)
int DHT_load (DHT *dht, const uint8_t *data, uint32_t length)
DHT * new_DHT (Networking_Core *net)
void kill_DHT (DHT *dht)
int DHT_isconnected (const DHT *dht)
int DHT_non_lan_connected (const DHT *dht)
int addto_lists (DHT *dht, IP_Port ip_port, const uint8_t *public_key)
Macro Definition Documentation
#define BAD_NODE_TIMEOUT (PING_INTERVAL + PINGS_MISSED_NODE_GOES_BAD * (PING_INTERVAL + PING_ROUNDTRIP))
Definition at line 52 of file DHT.h.
Referenced by Assoc_get_close_entries(), candidates_create_internal(), closelist_nodes(), cmp_dht_entry(), DHT_getfriendip(), DHT_isconnected(), DHT_non_lan_connected(), do_Close(), do_hardening(), do_ping_and_sendnode_requests(), friend_iplist(), get_close_nodes_inner(), have_nodes_closelist(), in_list(), mark_bad(), route_tofriend(), routeone_tofriend(), and store_node_ok().
#define DHT_FAKE_FRIEND_NUMBER 4
Definition at line 61 of file DHT.h.
Referenced by DHT_save(), DHT_size(), and new_DHT().
#define DHT_FRIEND_MAX_LOCKS 32
Definition at line 124 of file DHT.h.
Referenced by DHT_addfriend().
#define DHT_PING_ARRAY_SIZE 512
Definition at line 44 of file DHT.h.
Referenced by new_DHT().
#define KEYS_TIMEOUT 600
Definition at line 179 of file DHT.h.
Referenced by get_shared_key().
#define LCLIENT_LIST 32
Definition at line 35 of file DHT.h.
Referenced by add_to_ping(), addto_lists(), closelist_nodes(), DHT_isconnected(), DHT_non_lan_connected(), DHT_save(), DHT_size(), do_Close(), do_hardening(), do_messenger(), get_closelist_IPPTsPng(), get_somewhat_close_nodes(), print_clientlist(), returnedip_ports(), route_packet(), and test_addto_lists().
#define MAX_FRIEND_CLIENTS 8
Definition at line 32 of file DHT.h.
Referenced by addto_lists(), DHT_addfriend(), DHT_getfriendip(), DHT_save(), DHT_size(), do_DHT_friends(), do_messenger(), do_NAT(), friend_iplist(), get_somewhat_close_nodes(), NAT_commonip(), print_friendlist(), punch_holes(), returnedip_ports(), route_tofriend(), routeone_tofriend(), and test_addto_lists().
#define MAX_KEYS_PER_SLOT 4
Definition at line 178 of file DHT.h.
Referenced by get_shared_key().
#define MAX_SENT_NODES 4
Definition at line 38 of file DHT.h.
Referenced by get_close_nodes(), get_close_nodes_inner(), handle_announce_request(), handle_announce_response(), handle_dhtpk_announce(), handle_hardening(), handle_sendnodes_core(), handle_sendnodes_ipv6(), populate_path_nodes(), populate_path_nodes_tcp(), random_node(), send_dhtpk_announce(), and sendnodes_ipv6().
#define PING_INTERVAL 60
Definition at line 47 of file DHT.h.
Referenced by do_ping_and_sendnode_requests().
#define PING_ROUNDTRIP 2
Definition at line 51 of file DHT.h.
#define PING_TIMEOUT 3
Definition at line 41 of file DHT.h.
Referenced by new_DHT(), and new_ping().
#define PINGS_MISSED_NODE_GOES_BAD 1
Definition at line 50 of file DHT.h.
#define TOX_AF_INET 2
Definition at line 55 of file DHT.h.
Referenced by ip_pack(), ip_unpack(), pack_nodes(), to_host_family(), to_net_family(), and unpack_nodes().
#define TOX_AF_INET6 10
Definition at line 56 of file DHT.h.
Referenced by pack_nodes(), to_host_family(), to_net_family(), and unpack_nodes().
#define TOX_TCP_INET 130
Definition at line 57 of file DHT.h.
Referenced by ip_pack(), ip_unpack(), pack_nodes(), and unpack_nodes().
#define TOX_TCP_INET6 138
Definition at line 58 of file DHT.h.
Referenced by pack_nodes(), and unpack_nodes().
Typedef Documentation
typedef int(* cryptopacket_handler_callback)(void *object, IP_Port ip_port, const uint8_t *source_pubkey, const uint8_t *data, uint16_t len)
Definition at line 192 of file DHT.h.
Function Documentation
int addto_lists (DHT * dht, IP_Port ip_port, const uint8_t * public_key)
Definition at line 771 of file DHT.c.
References Assoc_add_entry(), DHT_Friend::callbacks, DHT_Friend::client_list, client_or_ip_port_in_list(), DHT::close_clientlist, DHT_Friend::data, IP::family, DHT::friends_list, i, IP_Port::ip, IP::ip4, IP::ip6, DHT_Friend::ip_callback, IPPTs::ip_port, IPV6_IPV4_IN_V6, LCLIENT_LIST, DHT_Friend::lock_count, MAX_FRIEND_CLIENTS, DHT::num_friends, DHT_Friend::number, DHT_Friend::public_key, replace_all(), DHT::self_public_key, IPPTs::timestamp, IP4::uint32, IP6::uint32, and unix_time().
Referenced by handle_ping_response(), handle_sendnodes_core(), test_addto_lists(), test_addto_lists_bad(), test_addto_lists_good(), test_addto_lists_possible_bad(), and test_addto_lists_update().
{
    uint32_t i, used = 0;
    /* convert IPv4-in-IPv6 to IPv4 */
    if ((ip_port.ip.family == AF_INET6) && IPV6_IPV4_IN_V6(ip_port.
      ip.ip6)) {
        ip_port.ip.family = AF_INET;
        ip_port.ip.ip4.uint32 = ip_port.ip.ip6.uint32[3];
    }
    /* NOTE: Current behavior if there are two clients with the same id is
     * to replace the first ip by the second.
     */
    if (!client_or_ip_port_in_list(dht->
      close_clientlist, LCLIENT_LIST, public_key, ip_port)) {
        if (replace_all(dht->close_clientlist,
      LCLIENT_LIST, public_key, ip_port, dht->self_public_key))
            used++;
    } else
        used++;
    DHT_Friend *friend_foundip = 0;
    for (i = 0; i < dht->num_friends; ++i) {
        if (!client_or_ip_port_in_list(dht->
      friends_list[i].client_list,
                                       MAX_FRIEND_CLIENTS,
      public_key, ip_port)) {
            if (replace_all(dht->friends_list[i].
      client_list, MAX_FRIEND_CLIENTS,
                            public_key, ip_port, dht->friends_list[i].
      public_key)) {
                DHT_Friend *friend = &dht->friends_list[i];
                if (memcmp(public_key, friend->public_key, crypto_box_PUBLICKEYBYTES) == 0) {
                    friend_foundip = friend;
                }
                used++;
            }
        } else {
            DHT_Friend *friend = &dht->friends_list[i];
            if (memcmp(public_key, friend->public_key, crypto_box_PUBLICKEYBYTES) == 0) {
                friend_foundip = friend;
            }
            used++;
        }
    }
    if (friend_foundip) {
        uint32_t j;
        for (j = 0; j < friend_foundip->lock_count; ++j) {
            if (friend_foundip->callbacks[j].ip_callback)
                friend_foundip->callbacks[j].ip_callback(friend_foundip->
      callbacks[j].data, friend_foundip->callbacks[j].number,
                        ip_port);
        }
    }
#ifdef ENABLE_ASSOC_DHT
    if (dht->assoc) {
        IPPTs ippts;
        ippts.ip_port = ip_port;
        ippts.timestamp = unix_time();
        Assoc_add_entry(dht->assoc, public_key, &ippts, NULL, used ? 1 : 0);
    }
#endif
    return used;
}
uint16_t closelist_nodes (DHT * dht, Node_format * nodes, uint16_t max_num)
Definition at line 2066 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, BAD_NODE_TIMEOUT, DHT::close_clientlist, i, IPPTsPng::ip_port, Node_format::ip_port, is_timeout(), and LCLIENT_LIST.
Referenced by send_dhtpk_announce().
{
    if (max_num == 0)
        return 0;
    uint16_t count = 0;
    Client_data *list = dht->close_clientlist;
    uint32_t i;
    for (i = LCLIENT_LIST; i != 0; --i) {
        IPPTsPng *assoc = NULL;
        if (!is_timeout(list[i - 1].assoc4.timestamp, BAD_NODE_TIMEOUT))
            assoc = &list[i - 1].assoc4;
        if (!is_timeout(list[i - 1].assoc6.timestamp, BAD_NODE_TIMEOUT)) {
            if (assoc == NULL)
                assoc = &list[i - 1].assoc6;
            else if (rand() % 2)
                assoc = &list[i - 1].assoc6;
        }
        if (assoc != NULL) {
            memcpy(nodes[count].public_key, list[i - 1].public_key, crypto_box_PUBLICKEYBYTES);
            nodes[count].ip_port = assoc->ip_port;
            ++count;
            if (count >= max_num)
                return count;
        }
    }
    return count;
}
void cryptopacket_registerhandler (DHT * dht, uint8_t byte, cryptopacket_handler_callback cb, void * object)
Definition at line 2154 of file DHT.c.
References DHT::cryptopackethandlers, Cryptopacket_Handles::function, and Cryptopacket_Handles::object.
Referenced by kill_DHT(), kill_onion_client(), new_DHT(), and new_onion_client().
{
    dht->cryptopackethandlers[byte].function = cb;
    dht->cryptopackethandlers[byte].object = object;
}
int DHT_addfriend (DHT * dht, const uint8_t * public_key, void(*)(void *data, int32_t number, IP_Port) ip_callback, void * data, int32_t number, uint16_t * lock_count)
Definition at line 1167 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, Assoc_get_close_entries(), Assoc_close_entries::count, Assoc_close_entries::count_good, make-funny-savefile::data, DHT_FRIEND_MAX_LOCKS, friend_number(), DHT::friends_list, getnodes(), i, IPPTsPng::ip_port, ipport_isset(), DHT_Friend::lock_count, MAX_FRIEND_CLIENTS, DHT::num_friends, make-funny-savefile::public_key, Client_data::public_key, random_64b(), Assoc_close_entries::result, and Assoc_close_entries::wanted_id.
Referenced by change_dht_pk(), dht_pk_callback(), main(), and new_DHT().
{
    int friend_num = friend_number(dht, public_key);
    uint16_t lock_num;
    if (friend_num != -1) { /* Is friend already in DHT? */
        DHT_Friend *friend = &dht->friends_list[friend_num];
        if (friend->lock_count == DHT_FRIEND_MAX_LOCKS)
            return -1;
        lock_num = friend->lock_count;
        ++friend->lock_count;
        friend->callbacks[lock_num].ip_callback = ip_callback;
        friend->callbacks[lock_num].data = data;
        friend->callbacks[lock_num].number = number;
        if (lock_count)
            *lock_count = lock_num + 1;
        return 0;
    }
    DHT_Friend *temp;
    temp = realloc(dht->friends_list, sizeof(DHT_Friend) * (dht->
      num_friends + 1));
    if (temp == NULL)
        return -1;
    dht->friends_list = temp;
    DHT_Friend *friend = &dht->friends_list[dht->
      num_friends];
    memset(friend, 0, sizeof(DHT_Friend));
    memcpy(friend->public_key, public_key, crypto_box_PUBLICKEYBYTES);
    friend->nat.NATping_id = random_64b();
    ++dht->num_friends;
    lock_num = friend->lock_count;
    ++friend->lock_count;
    friend->callbacks[lock_num].ip_callback = ip_callback;
    friend->callbacks[lock_num].data = data;
    friend->callbacks[lock_num].number = number;
    if (lock_count)
        *lock_count = lock_num + 1;
#ifdef ENABLE_ASSOC_DHT
    if (dht->assoc) {
        /* get up to MAX_FRIEND_CLIENTS connectable nodes */
        DHT_Friend *friend = &dht->friends_list[dht->
      num_friends - 1];
        Assoc_close_entries close_entries;
        memset(&close_entries, 0, sizeof(close_entries));
        close_entries.wanted_id = public_key;
        close_entries.count_good = MAX_FRIEND_CLIENTS / 2;
        close_entries.count = MAX_FRIEND_CLIENTS;
        close_entries.result = calloc(MAX_FRIEND_CLIENTS, sizeof(*close_entries.
      result));
        uint8_t i, found = Assoc_get_close_entries(dht->assoc, &close_entries);
        for (i = 0; i < found; i++)
            memcpy(&friend->client_list[i], close_entries.result[i], sizeof(*close_entries.
      result[i]));
        if (found) {
            /* send getnodes to the "best" entry */
            Client_data *client = &friend->client_list[0];
            if (ipport_isset(&client->assoc4.ip_port))
                getnodes(dht, client->assoc4.ip_port, client->
      public_key, friend->public_key, NULL);
            if (ipport_isset(&client->assoc6.ip_port))
                getnodes(dht, client->assoc6.ip_port, client->
      public_key, friend->public_key, NULL);
        }
    }
#endif
    return 0;
}
void DHT_bootstrap (DHT * dht, IP_Port ip_port, const uint8_t * public_key)
Definition at line 1420 of file DHT.c.
References getnodes(), and DHT::self_public_key.
Referenced by DHT_bootstrap_from_address(), DHT_connect_after_load(), handle_LANdiscovery(), START_TEST(), and tox_bootstrap().
{
    /*#ifdef ENABLE_ASSOC_DHT
       if (dht->assoc) {
           IPPTs ippts;
           ippts.ip_port = ip_port;
           ippts.timestamp = 0;
           Assoc_add_entry(dht->assoc, public_key, &ippts, NULL, 0);
       }
       #endif*/
    getnodes(dht, ip_port, public_key, dht->self_public_key, NULL);
}
int DHT_bootstrap_from_address (DHT * dht, const char * address, uint8_t ipv6enabled, uint16_t port, const uint8_t * public_key)
Definition at line 1434 of file DHT.c.
References addr_resolve_or_parse_ip(), DHT_bootstrap(), IP::family, IP_Port::ip, ip_init(), ip_isset(), ip_reset(), port, and IP_Port::port.
Referenced by bootstrap_from_config(), and main().
{
    IP_Port ip_port_v64;
    IP *ip_extra = NULL;
    IP_Port ip_port_v4;
    ip_init(&ip_port_v64.ip, ipv6enabled);
    if (ipv6enabled) {
        /* setup for getting BOTH: an IPv6 AND an IPv4 address */
        ip_port_v64.ip.family = AF_UNSPEC;
        ip_reset(&ip_port_v4.ip);
        ip_extra = &ip_port_v4.ip;
    }
    if (addr_resolve_or_parse_ip(address, &ip_port_v64.
      ip, ip_extra)) {
        ip_port_v64.port = port;
        DHT_bootstrap(dht, ip_port_v64, public_key);
        if ((ip_extra != NULL) && ip_isset(ip_extra)) {
            ip_port_v4.port = port;
            DHT_bootstrap(dht, ip_port_v4, public_key);
        }
        return 1;
    } else
        return 0;
}
int DHT_connect_after_load (DHT * dht)
Definition at line 2382 of file DHT.c.
References DHT_bootstrap(), DHT_non_lan_connected(), i, Node_format::ip_port, DHT::loaded_nodes_index, DHT::loaded_nodes_list, DHT::loaded_num_nodes, Node_format::public_key, and SAVE_BOOTSTAP_FREQUENCY.
Referenced by do_DHT().
{
    if (dht == NULL)
        return -1;
    if (!dht->loaded_nodes_list)
        return -1;
    /* DHT is connected, stop. */
    if (DHT_non_lan_connected(dht)) {
        free(dht->loaded_nodes_list);
        dht->loaded_nodes_list = NULL;
        dht->loaded_num_nodes = 0;
        return 0;
    }
    unsigned int i;
    for (i = 0; i < dht->loaded_num_nodes && i <
      SAVE_BOOTSTAP_FREQUENCY; ++i) {
        unsigned int index = dht->loaded_nodes_index % dht->
      loaded_num_nodes;
        DHT_bootstrap(dht, dht->loaded_nodes_list[index].
      ip_port, dht->loaded_nodes_list[index].public_key);
        ++dht->loaded_nodes_index;
    }
    return 0;
}
int DHT_delfriend (DHT * dht, const uint8_t * public_key, uint16_t lock_count)
Definition at line 1250 of file DHT.c.
References friend_number(), DHT::friends_list, DHT_Friend::lock_count, and DHT::num_friends.
Referenced by change_dht_pk(), do_friend_connections(), and kill_friend_connection().
{
    int friend_num = friend_number(dht, public_key);
    if (friend_num == -1) {
        return -1;
    }
    DHT_Friend *friend = &dht->friends_list[friend_num];
    --friend->lock_count;
    if (friend->lock_count && lock_count) { /* DHT friend is still in use.*/
        --lock_count;
        friend->callbacks[lock_count].ip_callback = NULL;
        friend->callbacks[lock_count].data = NULL;
        friend->callbacks[lock_count].number = 0;
        return 0;
    }
    DHT_Friend *temp;
    --dht->num_friends;
    if (dht->num_friends != friend_num) {
        memcpy(&dht->friends_list[friend_num],
                &dht->friends_list[dht->num_friends],
                sizeof(DHT_Friend));
    }
    if (dht->num_friends == 0) {
        free(dht->friends_list);
        dht->friends_list = NULL;
        return 0;
    }
    temp = realloc(dht->friends_list, sizeof(DHT_Friend) * (dht->
      num_friends));
    if (temp == NULL)
        return -1;
    dht->friends_list = temp;
    return 0;
}
void DHT_get_shared_key_recv (DHT * dht, uint8_t * shared_key, const uint8_t * public_key)
Definition at line 146 of file DHT.c.
References get_shared_key(), DHT::self_secret_key, and DHT::shared_keys_recv.
Referenced by handle_getnodes(), and handle_ping_request().
{
    get_shared_key(&dht->shared_keys_recv, shared_key, dht->
      self_secret_key, public_key);
}
void DHT_get_shared_key_sent (DHT * dht, uint8_t * shared_key, const uint8_t * public_key)
Definition at line 154 of file DHT.c.
References get_shared_key(), DHT::self_secret_key, and DHT::shared_keys_sent.
Referenced by create_cookie_request(), getnodes(), handle_cookie_request(), handle_ping_response(), handle_sendnodes_core(), and send_ping_request().
{
    get_shared_key(&dht->shared_keys_sent, shared_key, dht->
      self_secret_key, public_key);
}
int DHT_getfriendip (const DHT * dht, const uint8_t * public_key, IP_Port * ip_port)
Definition at line 1295 of file DHT.c.
References Client_data::assoc6, BAD_NODE_TIMEOUT, DHT_Friend::client_list, DHT::friends_list, i, id_equal(), IP_Port::ip, IPPTsPng::ip_port, ip_reset(), is_timeout(), MAX_FRIEND_CLIENTS, DHT::num_friends, IP_Port::port, Client_data::public_key, DHT_Friend::public_key, and IPPTsPng::timestamp.
Referenced by onion_getfriendip(), and print_friendlist().
{
    uint32_t i, j;
    ip_reset(&ip_port->ip);
    ip_port->port = 0;
    for (i = 0; i < dht->num_friends; ++i) {
        /* Equal */
        if (id_equal(dht->friends_list[i].public_key,
      public_key)) {
            for (j = 0; j < MAX_FRIEND_CLIENTS; ++j) {
                Client_data *client = &dht->friends_list[
      i].client_list[j];
                if (id_equal(client->public_key, public_key)) {
                    IPPTsPng *assoc = NULL;
                    uint32_t a;
                    for (a = 0, assoc = &client->assoc6; a < 2; a++, assoc = &client->assoc4)
                        if (!is_timeout(assoc->timestamp,
      BAD_NODE_TIMEOUT)) {
                            *ip_port = assoc->ip_port;
                            return 1;
                        }
                }
            }
            return 0;
        }
    }
    return -1;
}
void DHT_getnodes (DHT * dht, const IP_Port * from_ipp, const uint8_t * from_id, const uint8_t * which_id)
Definition at line 1415 of file DHT.c.
References getnodes().
Referenced by do_Assoc(), and handle_dhtpk_announce().
{
    getnodes(dht, *from_ipp, from_id, which_id, NULL);
}
int DHT_isconnected (const DHT * dht)
Definition at line 2471 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, BAD_NODE_TIMEOUT, DHT::close_clientlist, i, is_timeout(), LCLIENT_LIST, IPPTsPng::timestamp, and unix_time_update().
Referenced by do_tox(), main(), random_nodes_path_onion(), and START_TEST().
{
    uint32_t i;
    unix_time_update();
    for (i = 0; i < LCLIENT_LIST; ++i) {
        const Client_data *client = &dht->close_clientlist[
      i];
        if (!is_timeout(client->assoc4.timestamp,
      BAD_NODE_TIMEOUT) ||
                !is_timeout(client->assoc6.timestamp,
      BAD_NODE_TIMEOUT))
            return 1;
    }
    return 0;
}
int DHT_load (DHT * dht, const uint8_t * data, uint32_t length)
Definition at line 2452 of file DHT.c.
References dht_load_state_callback(), DHT_STATE_COOKIE_GLOBAL, DHT_STATE_COOKIE_TYPE, lendian_to_host32(), and load_state().
Referenced by messenger_load_state_callback(), and START_TEST().
{
    uint32_t cookie_len = sizeof(uint32_t);
    if (length > cookie_len) {
        uint32_t data32;
        lendian_to_host32(&data32, data);
        if (data32 == DHT_STATE_COOKIE_GLOBAL)
            return load_state(dht_load_state_callback, dht,
      data + cookie_len,
                              length - cookie_len, DHT_STATE_COOKIE_TYPE);
    }
    return -1;
}
int DHT_non_lan_connected (const DHT * dht)
Definition at line 2490 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, BAD_NODE_TIMEOUT, DHT::close_clientlist, i, IP_Port::ip, IPPTsPng::ip_port, is_timeout(), LAN_ip(), LCLIENT_LIST, IPPTsPng::timestamp, and unix_time_update().
Referenced by DHT_connect_after_load(), and do_onion_client().
{
    uint32_t i;
    unix_time_update();
    for (i = 0; i < LCLIENT_LIST; ++i) {
        const Client_data *client = &dht->close_clientlist[
      i];
        if (!is_timeout(client->assoc4.timestamp,
      BAD_NODE_TIMEOUT) && LAN_ip(client->assoc4.ip_port.
      ip) == -1)
            return 1;
        if (!is_timeout(client->assoc6.timestamp,
      BAD_NODE_TIMEOUT) && LAN_ip(client->assoc6.ip_port.
      ip) == -1)
            return 1;
    }
    return 0;
}
void DHT_save (DHT * dht, uint8_t * data)
Definition at line 2329 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, DHT_Friend::client_list, DHT::close_clientlist, make-funny-savefile::data, DHT_FAKE_FRIEND_NUMBER, DHT_STATE_COOKIE_GLOBAL, DHT_STATE_TYPE_NODES, DHT::friends_list, host_to_lendian32(), i, IPPTsPng::ip_port, Node_format::ip_port, LCLIENT_LIST, MAX_FRIEND_CLIENTS, MAX_SAVED_DHT_NODES, num, DHT::num_friends, pack_nodes(), Client_data::public_key, IPPTsPng::timestamp, and z_state_save_subheader().
Referenced by messenger_save(), and START_TEST().
{
    host_to_lendian32(data, DHT_STATE_COOKIE_GLOBAL);
    data += sizeof(uint32_t);
    uint32_t num, i, j;
    uint8_t *old_data = data;
    /* get right offset. we write the actual header later. */
    data = z_state_save_subheader(data, 0, 0);
    Node_format clients[MAX_SAVED_DHT_NODES];
    for (num = 0, i = 0; i < LCLIENT_LIST; ++i) {
        if (dht->close_clientlist[i].assoc4.timestamp != 0) {
            memcpy(clients[num].public_key, dht->close_clientlist[i].
      public_key, crypto_box_PUBLICKEYBYTES);
            clients[num].ip_port = dht->close_clientlist[
      i].assoc4.ip_port;
            ++num;
        }
        if (dht->close_clientlist[i].assoc6.timestamp != 0) {
            memcpy(clients[num].public_key, dht->close_clientlist[i].
      public_key, crypto_box_PUBLICKEYBYTES);
            clients[num].ip_port = dht->close_clientlist[
      i].assoc6.ip_port;
            ++num;
        }
    }
    for (i = 0; i < DHT_FAKE_FRIEND_NUMBER && i < dht->
      num_friends; ++i) {
        DHT_Friend *fr = &dht->friends_list[i];
        for (j = 0; j < MAX_FRIEND_CLIENTS; ++j) {
            if (fr->client_list[j].assoc4.timestamp != 0) {
                memcpy(clients[num].public_key, fr->client_list[j].
      public_key, crypto_box_PUBLICKEYBYTES);
                clients[num].ip_port = fr->client_list[j].
      assoc4.ip_port;
                ++num;
            }
            if (fr->client_list[j].assoc6.timestamp != 0) {
                memcpy(clients[num].public_key, fr->client_list[j].
      public_key, crypto_box_PUBLICKEYBYTES);
                clients[num].ip_port = fr->client_list[j].
      assoc6.ip_port;
                ++num;
            }
        }
    }
    z_state_save_subheader(old_data, pack_nodes(
      data, sizeof(Node_format) * num, clients, num),
      DHT_STATE_TYPE_NODES);
}
uint32_t DHT_size (const DHT * dht)
Definition at line 2295 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, DHT_Friend::client_list, DHT::close_clientlist, DHT_FAKE_FRIEND_NUMBER, DHT::friends_list, i, LCLIENT_LIST, MAX_FRIEND_CLIENTS, DHT::num_friends, packed_node_size(), and IPPTsPng::timestamp.
Referenced by messenger_save(), messenger_size(), and START_TEST().
{
    uint32_t numv4 = 0, numv6 = 0, i, j;
    for (i = 0; i < LCLIENT_LIST; ++i) {
        numv4 += (dht->close_clientlist[i].assoc4.
      timestamp != 0);
        numv6 += (dht->close_clientlist[i].assoc6.
      timestamp != 0);
    }
    for (i = 0; i < DHT_FAKE_FRIEND_NUMBER && i < dht->
      num_friends; ++i) {
        DHT_Friend *fr = &dht->friends_list[i];
        for (j = 0; j < MAX_FRIEND_CLIENTS; ++j) {
            numv4 += (fr->client_list[j].assoc4.timestamp != 0);
            numv6 += (fr->client_list[j].assoc6.timestamp != 0);
        }
    }
    uint32_t size32 = sizeof(uint32_t), sizesubhead = size32 * 2;
    return size32 + sizesubhead + (packed_node_size(AF_INET) * numv4) + (
      packed_node_size(AF_INET6) * numv6);
}
void do_DHT (DHT * dht)
Definition at line 2242 of file DHT.c.
References DHT_connect_after_load(), do_Assoc(), do_Close(), do_DHT_friends(), do_hardening(), do_NAT(), do_to_ping(), DHT::last_run, DHT::loaded_num_nodes, DHT::ping, unix_time(), and unix_time_update().
Referenced by do_messenger(), do_onion(), do_onions(), and main().
{
    unix_time_update();
    if (dht->last_run == unix_time()) {
        return;
    }
    // Load friends/clients if first call to do_DHT
    if (dht->loaded_num_nodes) {
        DHT_connect_after_load(dht);
    }
    do_Close(dht);
    do_DHT_friends(dht);
    do_NAT(dht);
    do_to_ping(dht->ping);
    do_hardening(dht);
#ifdef ENABLE_ASSOC_DHT
    if (dht->assoc)
        do_Assoc(dht->assoc, dht);
#endif
    dht->last_run = unix_time();
}
int get_close_nodes (const DHT * dht, const uint8_t * public_key, Node_format * nodes_list, sa_family_t sa_family, uint8_t is_LAN, uint8_t want_good)
Definition at line 570 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, Assoc_get_close_entries(), Assoc_close_entries::count, Assoc_close_entries::count_good, Assoc_close_entries::flags, get_somewhat_close_nodes(), i, id_copy(), IPPTsPng::ip_port, Node_format::ip_port, ipport_isset(), LANOk, LOGGER_DEBUG, MAX_SENT_NODES, ProtoIPv4, ProtoIPv6, make-funny-savefile::public_key, Client_data::public_key, Assoc_close_entries::result, and Assoc_close_entries::wanted_id.
Referenced by handle_announce_request(), populate_path_nodes(), random_node(), and sendnodes_ipv6().
{
    memset(nodes_list, 0, MAX_SENT_NODES * sizeof(Node_format));
#ifdef ENABLE_ASSOC_DHT
    if (!dht->assoc)
#endif
        return get_somewhat_close_nodes(dht, public_key, nodes_list,
      sa_family, is_LAN, want_good);
#ifdef ENABLE_ASSOC_DHT
    //TODO: assoc, sa_family 0 (don't care if ipv4 or ipv6) support.
    Client_data *result[MAX_SENT_NODES];
    Assoc_close_entries request;
    memset(&request, 0, sizeof(request));
    request.count = MAX_SENT_NODES;
    request.count_good = MAX_SENT_NODES - 2; /* allow 2 'indirect' nodes */
    request.result = result;
    request.wanted_id = public_key;
    request.flags = (is_LAN ? LANOk : 0) + (sa_family == AF_INET ?
      ProtoIPv4 : ProtoIPv6);
    uint8_t num_found = Assoc_get_close_entries(dht->assoc, &request);
    if (!num_found) {
        LOGGER_DEBUG("get_close_nodes(): Assoc_get_close_entries() returned zero nodes");
        return get_somewhat_close_nodes(dht, public_key, nodes_list,
      sa_family, is_LAN, want_good);
    }
    LOGGER_DEBUG("get_close_nodes(): Assoc_get_close_entries() returned %i 'direct' and %i
       'indirect' nodes",
                 request.count_good, num_found - request.count_good);
    uint8_t i, num_returned = 0;
    for (i = 0; i < num_found; i++) {
        Client_data *client = result[i];
        if (client) {
            id_copy(nodes_list[num_returned].public_key, client->
      public_key);
            if (sa_family == AF_INET)
                if (ipport_isset(&client->assoc4.ip_port)) {
                    nodes_list[num_returned].ip_port = client->assoc4.
      ip_port;
                    num_returned++;
                    continue;
                }
            if (sa_family == AF_INET6)
                if (ipport_isset(&client->assoc6.ip_port)) {
                    nodes_list[num_returned].ip_port = client->assoc6.
      ip_port;
                    num_returned++;
                    continue;
                }
        }
    }
    return num_returned;
#endif
}
void get_shared_key (Shared_Keys * shared_keys, uint8_t * shared_key, const uint8_t * secret_key, const uint8_t * public_key)
Definition at line 100 of file DHT.c.
References encrypt_precompute(), i, is_timeout(), Shared_Keys::keys, KEYS_TIMEOUT, MAX_KEYS_PER_SLOT, num, Shared_Keys::public_key, Shared_Keys::shared_key, Shared_Keys::stored, Shared_Keys::time_last_requested, Shared_Keys::times_requested, and unix_time().
Referenced by DHT_get_shared_key_recv(), DHT_get_shared_key_sent(), handle_announce_request(), handle_send_1(), handle_send_2(), and handle_send_initial().
{
    uint32_t i, num = ~0, curr = 0;
    for (i = 0; i < MAX_KEYS_PER_SLOT; ++i) {
        int index = public_key[30] * MAX_KEYS_PER_SLOT + i;
        if (shared_keys->keys[index].stored) {
            if (memcmp(public_key, shared_keys->keys[index].
      public_key, crypto_box_PUBLICKEYBYTES) == 0) {
                memcpy(shared_key, shared_keys->keys[index].shared_key,
      crypto_box_BEFORENMBYTES);
                ++shared_keys->keys[index].times_requested;
                shared_keys->keys[index].time_last_requested =
      unix_time();
                return;
            }
            if (num != 0) {
                if (is_timeout(shared_keys->keys[index].
      time_last_requested, KEYS_TIMEOUT)) {
                    num = 0;
                    curr = index;
                } else if (num > shared_keys->keys[index].times_requested) {
                    num = shared_keys->keys[index].times_requested;
                    curr = index;
                }
            }
        } else {
            if (num != 0) {
                num = 0;
                curr = index;
            }
        }
    }
    encrypt_precompute(public_key, secret_key, shared_key);
    if (num != (uint32_t)~0) {
        shared_keys->keys[curr].stored = 1;
        shared_keys->keys[curr].times_requested = 1;
        memcpy(shared_keys->keys[curr].public_key, public_key,
      crypto_box_PUBLICKEYBYTES);
        memcpy(shared_keys->keys[curr].shared_key, shared_key, crypto_box_BEFORENMBYTES);
        shared_keys->keys[curr].time_last_requested =
      unix_time();
    }
}
int id_closest (const uint8_t * pk, const uint8_t * pk1, const uint8_t * pk2)
Definition at line 74 of file DHT.c.
References i.
Referenced by add_to_entries(), add_to_ping(), assoc_id_closest(), client_add_to_list(), client_ping_nodes(), cmp_dht_entry(), cmp_entry(), get_close_nodes_inner(), is_furthest(), store_node_ok(), and test_addto_lists_possible_bad().
{
    size_t i;
    uint8_t distance1, distance2;
    for (i = 0; i < crypto_box_PUBLICKEYBYTES; ++i) {
        distance1 = pk[i] ^ pk1[i];
        distance2 = pk[i] ^ pk2[i];
        if (distance1 < distance2)
            return 1;
        if (distance1 > distance2)
            return 2;
    }
    return 0;
}
void kill_DHT (DHT * dht)
Definition at line 2268 of file DHT.c.
References CRYPTO_PACKET_HARDENING, CRYPTO_PACKET_NAT_PING, cryptopacket_registerhandler(), DHT::dht_harden_ping_array, DHT::dht_ping_array, DHT::friends_list, kill_Assoc(), kill_ping(), DHT::loaded_nodes_list, DHT::net, NET_PACKET_GET_NODES, NET_PACKET_SEND_NODES_IPV6, networking_registerhandler(), DHT::ping, and ping_array_free_all().
Referenced by kill_messenger(), kill_onions(), new_DHT(), new_messenger(), START_TEST(), and test_addto_lists().
{
#ifdef ENABLE_ASSOC_DHT
    kill_Assoc(dht->assoc);
#endif
    networking_registerhandler(dht->net,
      NET_PACKET_GET_NODES, NULL, NULL);
    networking_registerhandler(dht->net,
      NET_PACKET_SEND_NODES_IPV6, NULL, NULL);
    cryptopacket_registerhandler(dht,
      CRYPTO_PACKET_NAT_PING, NULL, NULL);
    cryptopacket_registerhandler(dht,
      CRYPTO_PACKET_HARDENING, NULL, NULL);
    ping_array_free_all(&dht->dht_ping_array);
    ping_array_free_all(&dht->dht_harden_ping_array);
    kill_ping(dht->ping);
    free(dht->friends_list);
    free(dht->loaded_nodes_list);
    free(dht);
}
DHT* new_DHT (Networking_Core * net)
Definition at line 2196 of file DHT.c.
References CRYPTO_PACKET_HARDENING, CRYPTO_PACKET_NAT_PING, cryptopacket_handle(), cryptopacket_registerhandler(), DHT_addfriend(), DHT_FAKE_FRIEND_NUMBER, DHT::dht_harden_ping_array, DHT::dht_ping_array, DHT_PING_ARRAY_SIZE, handle_getnodes(), handle_hardening(), handle_NATping(), handle_sendnodes_ipv6(), i, kill_DHT(), DHT::net, NET_PACKET_CRYPTO, NET_PACKET_GET_NODES, NET_PACKET_SEND_NODES_IPV6, networking_registerhandler(), new_Assoc_default(), new_ping(), new_symmetric_key(), DHT::ping, ping_array_init(), PING_TIMEOUT, DHT::secret_symmetric_key, DHT::self_public_key, DHT::self_secret_key, and unix_time_update().
Referenced by main(), new_messenger(), new_onions(), START_TEST(), and test_addto_lists().
{
    /* init time */
    unix_time_update();
    if (net == NULL)
        return NULL;
    DHT *dht = calloc(1, sizeof(DHT));
    if (dht == NULL)
        return NULL;
    dht->net = net;
    dht->ping = new_ping(dht);
    if (dht->ping == NULL) {
        kill_DHT(dht);
        return NULL;
    }
    networking_registerhandler(dht->net,
      NET_PACKET_GET_NODES, &handle_getnodes, dht);
    networking_registerhandler(dht->net,
      NET_PACKET_SEND_NODES_IPV6, &handle_sendnodes_ipv6, dht);
    networking_registerhandler(dht->net,
      NET_PACKET_CRYPTO, &cryptopacket_handle, dht);
    cryptopacket_registerhandler(dht,
      CRYPTO_PACKET_NAT_PING, &handle_NATping, dht);
    cryptopacket_registerhandler(dht,
      CRYPTO_PACKET_HARDENING, &handle_hardening, dht);
    new_symmetric_key(dht->secret_symmetric_key);
    crypto_box_keypair(dht->self_public_key, dht->self_secret_key);
    ping_array_init(&dht->dht_ping_array,
      DHT_PING_ARRAY_SIZE, PING_TIMEOUT);
    ping_array_init(&dht->dht_harden_ping_array,
      DHT_PING_ARRAY_SIZE, PING_TIMEOUT);
#ifdef ENABLE_ASSOC_DHT
    dht->assoc = new_Assoc_default(dht->self_public_key);
#endif
    uint32_t i;
    for (i = 0; i < DHT_FAKE_FRIEND_NUMBER; ++i) {
        uint8_t random_key_bytes[crypto_box_PUBLICKEYBYTES];
        randombytes(random_key_bytes, sizeof(random_key_bytes));
        DHT_addfriend(dht, random_key_bytes, 0, 0, 0, 0);
    }
    return dht;
}
int pack_nodes (uint8_t * data, uint16_t length, const Node_format * nodes, uint16_t number)
Definition at line 207 of file DHT.c.
References i, PACKED_NODE_SIZE_IP4, PACKED_NODE_SIZE_IP6, make-funny-savefile::public_key, SIZE_IP4, SIZE_IP6, TCP_INET, TCP_INET6, TOX_AF_INET, TOX_AF_INET6, TOX_TCP_INET, and TOX_TCP_INET6.
Referenced by DHT_save(), handle_announce_request(), messenger_save(), send_dhtpk_announce(), send_relays(), and sendnodes_ipv6().
{
    uint32_t i, packed_length = 0;
    for (i = 0; i < number; ++i) {
        int ipv6 = -1;
        uint8_t net_family;
        if (nodes[i].ip_port.ip.family == AF_INET) {
            ipv6 = 0;
            net_family = TOX_AF_INET;
        } else if (nodes[i].ip_port.ip.family == TCP_INET) {
            ipv6 = 0;
            net_family = TOX_TCP_INET;
        } else if (nodes[i].ip_port.ip.family == AF_INET6) {
            ipv6 = 1;
            net_family = TOX_AF_INET6;
        } else if (nodes[i].ip_port.ip.family == TCP_INET6) {
            ipv6 = 1;
            net_family = TOX_TCP_INET6;
        } else {
            return -1;
        }
        if (ipv6 == 0) {
            uint32_t size = PACKED_NODE_SIZE_IP4;
            if (packed_length + size > length)
                return -1;
            data[packed_length] = net_family;
            memcpy(data + packed_length + 1, &nodes[i].ip_port.ip.ip4,
      SIZE_IP4);
            memcpy(data + packed_length + 1 + SIZE_IP4, &nodes[i].ip_port.port, sizeof(uint16_t
      ));
            memcpy(data + packed_length + 1 + SIZE_IP4 + sizeof(uint16_t), nodes[i].
      public_key, crypto_box_PUBLICKEYBYTES);
            packed_length += size;
        } else if (ipv6 == 1) {
            uint32_t size = PACKED_NODE_SIZE_IP6;
            if (packed_length + size > length)
                return -1;
            data[packed_length] = net_family;
            memcpy(data + packed_length + 1, &nodes[i].ip_port.ip.ip6,
      SIZE_IP6);
            memcpy(data + packed_length + 1 + SIZE_IP6, &nodes[i].ip_port.port, sizeof(uint16_t
      ));
            memcpy(data + packed_length + 1 + SIZE_IP6 + sizeof(uint16_t), nodes[i].
      public_key, crypto_box_PUBLICKEYBYTES);
            packed_length += size;
        } else {
            return -1;
        }
    }
    return packed_length;
}
int packed_node_size (uint8_t ip_family)
Definition at line 186 of file DHT.c.
References PACKED_NODE_SIZE_IP4, PACKED_NODE_SIZE_IP6, TCP_INET, and TCP_INET6.
Referenced by DHT_size(), messenger_save(), and messenger_size().
{
    if (ip_family == AF_INET) {
        return PACKED_NODE_SIZE_IP4;
    } else if (ip_family == TCP_INET) {
        return PACKED_NODE_SIZE_IP4;
    } else if (ip_family == AF_INET6) {
        return PACKED_NODE_SIZE_IP6;
    } else if (ip_family == TCP_INET6) {
        return PACKED_NODE_SIZE_IP6;
    } else {
        return -1;
    }
}
int route_packet (const DHT * dht, const uint8_t * public_key, const uint8_t * packet, uint16_t length)
Definition at line 1467 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, DHT::close_clientlist, i, id_equal(), IP_Port::ip, ip_isset(), IPPTsPng::ip_port, LCLIENT_LIST, DHT::net, Client_data::public_key, and sendpacket().
Referenced by cryptopacket_handle().
{
    uint32_t i;
    for (i = 0; i < LCLIENT_LIST; ++i) {
        if (id_equal(public_key, dht->close_clientlist[i].
      public_key)) {
            const Client_data *client = &dht->close_clientlist[
      i];
            if (ip_isset(&client->assoc6.ip_port.ip))
                return sendpacket(dht->net, client->assoc6.
      ip_port, packet, length);
            else if (ip_isset(&client->assoc4.ip_port.ip))
                return sendpacket(dht->net, client->assoc4.
      ip_port, packet, length);
            else
                break;
        }
    }
    return -1;
}
int route_tofriend (const DHT * dht, const uint8_t * friend_id, const uint8_t * packet, uint16_t length)
Definition at line 1562 of file DHT.c.
References Client_data::assoc4, Client_data::assoc6, BAD_NODE_TIMEOUT, friend_iplist(), friend_number(), DHT::friends_list, i, IP_Port::ip, ip_isset(), IPPTsPng::ip_port, is_timeout(), MAX_FRIEND_CLIENTS, DHT::net, num, IPPTsPng::ret_ip_port, IPPTsPng::ret_timestamp, and sendpacket().
Referenced by send_dht_dhtpk(), and send_NATping().
{
    int num = friend_number(dht, friend_id);
    if (num == -1)
        return 0;
    uint32_t i, sent = 0;
    uint8_t friend_sent[MAX_FRIEND_CLIENTS] = {0};
    IP_Port ip_list[MAX_FRIEND_CLIENTS];
    int ip_num = friend_iplist(dht, ip_list, num);
    if (ip_num < (MAX_FRIEND_CLIENTS / 4))
        return 0; /* Reason for that? */
    DHT_Friend *friend = &dht->friends_list[num];
    Client_data *client;
    /* extra legwork, because having the outside allocating the space for us
     * is *usually* good(tm) (bites us in the behind in this case though) */
    uint32_t a;
    for (a = 0; a < 2; a++)
        for (i = 0; i < MAX_FRIEND_CLIENTS; ++i) {
            if (friend_sent[i])/* Send one packet per client.*/
                continue;
            client = &friend->client_list[i];
            IPPTsPng *assoc = NULL;
            if (!a)
                assoc = &client->assoc4;
            else
                assoc = &client->assoc6;
            /* If ip is not zero and node is good. */
            if (ip_isset(&assoc->ret_ip_port.ip) &&
                    !is_timeout(assoc->ret_timestamp,
      BAD_NODE_TIMEOUT)) {
                int retval = sendpacket(dht->net, assoc->ip_port, packet, length);
                if ((unsigned int)retval == length) {
                    ++sent;
                    friend_sent[i] = 1;
                }
            }
        }
    return sent;
}
int to_host_family (IP * ip)
Definition at line 167 of file DHT.c.
References IP::family, TOX_AF_INET, and TOX_AF_INET6.
Referenced by ip_unpack().
{
    if (ip->family == TOX_AF_INET) {
        ip->family = AF_INET;
        return 0;
    } else if (ip->family == TOX_AF_INET6) {
        ip->family = AF_INET6;
        return 0;
    } else {
        return -1;
    }
}
void to_net_family (IP * ip)
Definition at line 159 of file DHT.c.
References IP::family, TOX_AF_INET, and TOX_AF_INET6.
Referenced by ip_pack().
{
    if (ip->family == AF_INET)
        ip->family = TOX_AF_INET;
    else if (ip->family == AF_INET6)
        ip->family = TOX_AF_INET6;
}
int unpack_nodes (Node_format * nodes, uint16_t max_num_nodes, uint16_t * processed_data_len, const uint8_t * data, uint16_t length, uint8_t tcp_enabled)
Definition at line 268 of file DHT.c.
References IP::family, IP_Port::ip, Node_format::ip_port, num, PACKED_NODE_SIZE_IP4, PACKED_NODE_SIZE_IP6, make-funny-savefile::public_key, SIZE_IP4, SIZE_IP6, TCP_INET, TCP_INET6, TOX_AF_INET, TOX_AF_INET6, TOX_TCP_INET, and TOX_TCP_INET6.
Referenced by dht_load_state_callback(), handle_announce_response(), handle_dhtpk_announce(), handle_hardening(), handle_packet(), handle_sendnodes_core(), and messenger_load_state_callback().
{
    uint32_t num = 0, len_processed = 0;
    while (num < max_num_nodes && len_processed < length) {
        int ipv6 = -1;
        uint8_t host_family;
        if (data[len_processed] == TOX_AF_INET) {
            ipv6 = 0;
            host_family = AF_INET;
        } else if (data[len_processed] == TOX_TCP_INET) {
            if (!tcp_enabled)
                return -1;
            ipv6 = 0;
            host_family = TCP_INET;
        } else if (data[len_processed] == TOX_AF_INET6) {
            ipv6 = 1;
            host_family = AF_INET6;
        } else if (data[len_processed] == TOX_TCP_INET6) {
            if (!tcp_enabled)
                return -1;
            ipv6 = 1;
            host_family = TCP_INET6;
        } else {
            return -1;
        }
        if (ipv6 == 0) {
            uint32_t size = PACKED_NODE_SIZE_IP4;
            if (len_processed + size > length)
                return -1;
            nodes[num].ip_port.ip.family = host_family;
            memcpy(&nodes[num].ip_port.ip.ip4, data + len_processed + 1,
      SIZE_IP4);
            memcpy(&nodes[num].ip_port.port, data + len_processed + 1 +
      SIZE_IP4, sizeof(uint16_t));
            memcpy(nodes[num].public_key, data + len_processed + 1 +
      SIZE_IP4 + sizeof(uint16_t), crypto_box_PUBLICKEYBYTES);
            len_processed += size;
            ++num;
        } else if (ipv6 == 1) {
            uint32_t size = PACKED_NODE_SIZE_IP6;
            if (len_processed + size > length)
                return -1;
            nodes[num].ip_port.ip.family = host_family;
            memcpy(&nodes[num].ip_port.ip.ip6, data + len_processed + 1,
      SIZE_IP6);
            memcpy(&nodes[num].ip_port.port, data + len_processed + 1 +
      SIZE_IP6, sizeof(uint16_t));
            memcpy(nodes[num].public_key, data + len_processed + 1 +
      SIZE_IP6 + sizeof(uint16_t), crypto_box_PUBLICKEYBYTES);
            len_processed += size;
            ++num;
        } else {
            return -1;
        }
    }
    if (processed_data_len)
        *processed_data_len = len_processed;
    return num;
}