toxcore/onion_announce.c File Reference
#include `onion_announce.h`
*
#include `LAN_discovery.h`
*
#include `util.h`
*
Macros
#define PING_ID_TIMEOUT 20
#define ANNOUNCE_REQUEST_SIZE_RECV (ONION_ANNOUNCE_REQUEST_SIZE + ONION_RETURN_3)
#define DATA_REQUEST_MIN_SIZE ONION_DATA_REQUEST_MIN_SIZE
#define DATA_REQUEST_MIN_SIZE_RECV (DATA_REQUEST_MIN_SIZE + ONION_RETURN_3)
Functions
int create_announce_request (uint8_t *packet, uint16_t max_packet_length, const uint8_t *dest_client_id, const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *ping_id, const uint8_t *client_id, const uint8_t *data_public_key, uint64_t sendback_data)
int create_data_request (uint8_t *packet, uint16_t max_packet_length, const uint8_t *public_key, const uint8_t *encrypt_public_key, const uint8_t *nonce, const uint8_t *data, uint16_t length)
int send_announce_request (Networking_Core *net, const Onion_Path *path, Node_format dest, const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *ping_id, const uint8_t *client_id, const uint8_t *data_public_key, uint64_t sendback_data)
int send_data_request (Networking_Core *net, const Onion_Path *path, IP_Port dest, const uint8_t *public_key, const uint8_t *encrypt_public_key, const uint8_t *nonce, const uint8_t *data, uint16_t length)
static void generate_ping_id (const Onion_Announce *onion_a, uint64_t time, const uint8_t *public_key, IP_Port ret_ip_port, uint8_t *ping_id)
static int in_entries (const Onion_Announce *onion_a, const uint8_t *public_key)
static int cmp_entry (const void *a, const void *b)
static int add_to_entries (Onion_Announce *onion_a, IP_Port ret_ip_port, const uint8_t *public_key, const uint8_t *data_public_key, const uint8_t *ret)
static int handle_announce_request (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_data_request (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
Onion_Announce * new_onion_announce (DHT *dht)
void kill_onion_announce (Onion_Announce *onion_a)
Variables
static uint8_t cmp_public_key [crypto_box_PUBLICKEYBYTES]
Macro Definition Documentation
#define ANNOUNCE_REQUEST_SIZE_RECV (ONION_ANNOUNCE_REQUEST_SIZE + ONION_RETURN_3)
Definition at line 32 of file onion_announce.c.
Referenced by handle_announce_request().
#define DATA_REQUEST_MIN_SIZE ONION_DATA_REQUEST_MIN_SIZE
Definition at line 34 of file onion_announce.c.
Referenced by create_data_request().
#define DATA_REQUEST_MIN_SIZE_RECV (DATA_REQUEST_MIN_SIZE + ONION_RETURN_3)
Definition at line 35 of file onion_announce.c.
Referenced by handle_data_request().
#define PING_ID_TIMEOUT 20
Definition at line 30 of file onion_announce.c.
Referenced by generate_ping_id(), and handle_announce_request().
Function Documentation
static int add_to_entries (Onion_Announce * onion_a, IP_Port ret_ip_port, const uint8_t * public_key, const uint8_t * data_public_key, const uint8_t * ret) [static]
Definition at line 255 of file onion_announce.c.
References cmp_entry(), cmp_public_key, Onion_Announce_Entry::data_public_key, Onion_Announce::dht, Onion_Announce::entries, i, id_closest(), in_entries(), is_timeout(), ONION_ANNOUNCE_MAX_ENTRIES, ONION_ANNOUNCE_TIMEOUT, ONION_RETURN_3, Onion_Announce_Entry::public_key, Onion_Announce_Entry::ret, Onion_Announce_Entry::ret_ip_port, DHT::self_public_key, Onion_Announce_Entry::time, and unix_time().
Referenced by handle_announce_request().
{
    int pos = in_entries(onion_a, public_key);
    unsigned int i;
    if (pos == -1) {
        for (i = 0; i < ONION_ANNOUNCE_MAX_ENTRIES; ++
      i) {
            if (is_timeout(onion_a->entries[i].time,
      ONION_ANNOUNCE_TIMEOUT))
                pos = i;
        }
    }
    if (pos == -1) {
        if (id_closest(onion_a->dht->self_public_key,
      public_key, onion_a->entries[0].public_key) == 1)
            pos = 0;
    }
    if (pos == -1)
        return -1;
    memcpy(onion_a->entries[pos].public_key, public_key,
      crypto_box_PUBLICKEYBYTES);
    onion_a->entries[pos].ret_ip_port = ret_ip_port;
    memcpy(onion_a->entries[pos].ret, ret, ONION_RETURN_3);
    memcpy(onion_a->entries[pos].data_public_key, data_public_key,
      crypto_box_PUBLICKEYBYTES);
    onion_a->entries[pos].time = unix_time();
    memcpy(cmp_public_key, onion_a->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    qsort(onion_a->entries, ONION_ANNOUNCE_MAX_ENTRIES, sizeof(
      Onion_Announce_Entry), cmp_entry);
    return in_entries(onion_a, public_key);
}
static int cmp_entry (const void * a, const void * b) [static]
Definition at line 222 of file onion_announce.c.
References cmp_public_key, id_closest(), is_timeout(), ONION_ANNOUNCE_TIMEOUT, Onion_Announce_Entry::public_key, and Onion_Announce_Entry::time.
Referenced by add_to_entries().
{
    Onion_Announce_Entry entry1, entry2;
    memcpy(&entry1, a, sizeof(Onion_Announce_Entry));
    memcpy(&entry2, b, sizeof(Onion_Announce_Entry));
    int t1 = is_timeout(entry1.time, ONION_ANNOUNCE_TIMEOUT);
    int t2 = is_timeout(entry2.time, ONION_ANNOUNCE_TIMEOUT);
    if (t1 && t2)
        return 0;
    if (t1)
        return -1;
    if (t2)
        return 1;
    int close = id_closest(cmp_public_key, entry1.
      public_key, entry2.public_key);
    if (close == 1)
        return 1;
    if (close == 2)
        return -1;
    return 0;
}
int create_announce_request (uint8_t * packet, uint16_t max_packet_length, const uint8_t * dest_client_id, const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * ping_id, const uint8_t * client_id, const uint8_t * data_public_key, uint64_t sendback_data)
Definition at line 50 of file onion_announce.c.
References encrypt_data(), NET_PACKET_ANNOUNCE_REQUEST, ONION_ANNOUNCE_REQUEST_SIZE, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, ONION_PING_ID_SIZE, and random_nonce().
Referenced by client_send_announce_request(), and send_announce_request().
{
    if (max_packet_length < ONION_ANNOUNCE_REQUEST_SIZE)
        return -1;
    uint8_t plain[ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES +
                  ONION_ANNOUNCE_SENDBACK_DATA_LENGTH];
    memcpy(plain, ping_id, ONION_PING_ID_SIZE);
    memcpy(plain + ONION_PING_ID_SIZE, client_id, crypto_box_PUBLICKEYBYTES);
    memcpy(plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES, data_public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES, &sendback_data,
           sizeof(sendback_data));
    packet[0] = NET_PACKET_ANNOUNCE_REQUEST;
    random_nonce(packet + 1);
    int len = encrypt_data(dest_client_id, secret_key, packet + 1, plain, sizeof(plain),
                           packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES);
    if ((uint32_t)len + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES !=
      ONION_ANNOUNCE_REQUEST_SIZE)
        return -1;
    memcpy(packet + 1 + crypto_box_NONCEBYTES, public_key, crypto_box_PUBLICKEYBYTES);
    return ONION_ANNOUNCE_REQUEST_SIZE;
}
int create_data_request (uint8_t * packet, uint16_t max_packet_length, const uint8_t * public_key, const uint8_t * encrypt_public_key, const uint8_t * nonce, const uint8_t * data, uint16_t length)
Definition at line 89 of file onion_announce.c.
References DATA_REQUEST_MIN_SIZE, encrypt_data(), NET_PACKET_ONION_DATA_REQUEST, and ONION_MAX_DATA_SIZE.
Referenced by send_data_request(), and send_onion_data().
{
    if (DATA_REQUEST_MIN_SIZE + length > max_packet_length)
        return -1;
    if ((unsigned int)DATA_REQUEST_MIN_SIZE + length >
      ONION_MAX_DATA_SIZE)
        return -1;
    packet[0] = NET_PACKET_ONION_DATA_REQUEST;
    memcpy(packet + 1, public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, nonce, crypto_box_NONCEBYTES);
    uint8_t random_public_key[crypto_box_PUBLICKEYBYTES];
    uint8_t random_secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(random_public_key, random_secret_key);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES, random_public_key,
      crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data(encrypt_public_key, random_secret_key, packet + 1 +
      crypto_box_PUBLICKEYBYTES, data, length,
                           packet + 1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES +
      crypto_box_PUBLICKEYBYTES);
    if (1 + crypto_box_PUBLICKEYBYTES + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + len !=
      DATA_REQUEST_MIN_SIZE +
            length)
        return -1;
    return DATA_REQUEST_MIN_SIZE + length;
}
static void generate_ping_id (const Onion_Announce * onion_a, uint64_t time, const uint8_t * public_key, IP_Port ret_ip_port, uint8_t * ping_id) [static]
Definition at line 191 of file onion_announce.c.
References crypto_box_KEYBYTES, make-funny-savefile::data, PING_ID_TIMEOUT, and Onion_Announce::secret_bytes.
Referenced by handle_announce_request().
{
    time /= PING_ID_TIMEOUT;
    uint8_t data[crypto_box_KEYBYTES + sizeof(time) + crypto_box_PUBLICKEYBYTES +
      sizeof(ret_ip_port)];
    memcpy(data, onion_a->secret_bytes, crypto_box_KEYBYTES);
    memcpy(data + crypto_box_KEYBYTES, &time, sizeof(time));
    memcpy(data + crypto_box_KEYBYTES + sizeof(time),
      public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(data + crypto_box_KEYBYTES + sizeof(time) + crypto_box_PUBLICKEYBYTES, &
      ret_ip_port, sizeof(ret_ip_port));
    crypto_hash_sha256(ping_id, data, sizeof(data));
}
static int handle_announce_request (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 289 of file onion_announce.c.
References add_to_entries(), ANNOUNCE_REQUEST_SIZE_RECV, make-funny-savefile::data, Onion_Announce_Entry::data_public_key, decrypt_data_symmetric(), Onion_Announce::dht, encrypt_data_symmetric(), Onion_Announce::entries, generate_ping_id(), get_close_nodes(), get_shared_key(), in_entries(), IP_Port::ip, LAN_ip(), MAX_SENT_NODES, Onion_Announce::net, NET_PACKET_ANNOUNCE_RESPONSE, nonce, ONION_ANNOUNCE_RESPONSE_MAX_SIZE, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, ONION_PING_ID_SIZE, ONION_RETURN_3, pack_nodes(), PING_ID_TIMEOUT, Onion_Announce_Entry::public_key, random_nonce(), DHT::self_secret_key, send_onion_response(), Onion_Announce::shared_keys_recv, and unix_time().
Referenced by new_onion_announce().
{
    Onion_Announce *onion_a = object;
    if (length != ANNOUNCE_REQUEST_SIZE_RECV)
        return 1;
    const uint8_t *packet_public_key = packet + 1 + crypto_box_NONCEBYTES;
    uint8_t shared_key[crypto_box_BEFORENMBYTES];
    get_shared_key(&onion_a->shared_keys_recv, shared_key, onion_a->
      dht->self_secret_key, packet_public_key);
    uint8_t plain[ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES +
                  ONION_ANNOUNCE_SENDBACK_DATA_LENGTH];
    int len = decrypt_data_symmetric(shared_key, packet + 1, packet + 1 +
      crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES,
                                     ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH +
                                     crypto_box_MACBYTES, plain);
    if ((uint32_t)len != sizeof(plain))
        return 1;
    uint8_t ping_id1[ONION_PING_ID_SIZE];
    generate_ping_id(onion_a, unix_time(), packet_public_key, source, ping_id1);
    uint8_t ping_id2[ONION_PING_ID_SIZE];
    generate_ping_id(onion_a, unix_time() +
      PING_ID_TIMEOUT, packet_public_key, source, ping_id2);
    int index = -1;
    uint8_t *data_public_key = plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES;
    if (memcmp(ping_id1, plain, ONION_PING_ID_SIZE) == 0 || memcmp(ping_id2, plain,
      ONION_PING_ID_SIZE) == 0) {
        index = add_to_entries(onion_a, source, packet_public_key, data_public_key,
                               packet + (ANNOUNCE_REQUEST_SIZE_RECV -
      ONION_RETURN_3));
    } else {
        index = in_entries(onion_a, plain + ONION_PING_ID_SIZE);
    }
    /*Respond with a announce response packet*/
    Node_format nodes_list[MAX_SENT_NODES];
    unsigned int num_nodes = get_close_nodes(onion_a->dht, plain +
      ONION_PING_ID_SIZE, nodes_list, 0,
                             LAN_ip(source.ip) == 0, 1);
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t pl[1 + ONION_PING_ID_SIZE + sizeof(nodes_list)];
    if (index == -1) {
        pl[0] = 0;
        memcpy(pl + 1, ping_id2, ONION_PING_ID_SIZE);
    } else {
        if (memcmp(onion_a->entries[index].public_key, packet_public_key,
      crypto_box_PUBLICKEYBYTES) == 0) {
            if (memcmp(onion_a->entries[index].data_public_key, data_public_key,
      crypto_box_PUBLICKEYBYTES) != 0) {
                pl[0] = 0;
                memcpy(pl + 1, ping_id2, ONION_PING_ID_SIZE);
            } else {
                pl[0] = 2;
                memcpy(pl + 1, ping_id2, ONION_PING_ID_SIZE);
            }
        } else {
            pl[0] = 1;
            memcpy(pl + 1, onion_a->entries[index].data_public_key,
      crypto_box_PUBLICKEYBYTES);
        }
    }
    int nodes_length = 0;
    if (num_nodes != 0) {
        nodes_length = pack_nodes(pl + 1 + ONION_PING_ID_SIZE, sizeof(
      nodes_list), nodes_list, num_nodes);
        if (nodes_length <= 0)
            return 1;
    }
    uint8_t data[ONION_ANNOUNCE_RESPONSE_MAX_SIZE];
    len = encrypt_data_symmetric(shared_key, nonce, pl, 1 +
      ONION_PING_ID_SIZE + nodes_length,
                                 data + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES);
    if (len != 1 + ONION_PING_ID_SIZE + nodes_length + crypto_box_MACBYTES)
        return 1;
    data[0] = NET_PACKET_ANNOUNCE_RESPONSE;
    memcpy(data + 1, plain + ONION_PING_ID_SIZE + crypto_box_PUBLICKEYBYTES +
      crypto_box_PUBLICKEYBYTES,
           ONION_ANNOUNCE_SENDBACK_DATA_LENGTH);
    memcpy(data + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, nonce,
      crypto_box_NONCEBYTES);
    if (send_onion_response(onion_a->net, source, data,
                            1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH +
      crypto_box_NONCEBYTES + len,
                            packet + (ANNOUNCE_REQUEST_SIZE_RECV -
      ONION_RETURN_3)) == -1)
        return 1;
    return 0;
}
static int handle_data_request (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 382 of file onion_announce.c.
References make-funny-savefile::data, DATA_REQUEST_MIN_SIZE_RECV, Onion_Announce::entries, in_entries(), Onion_Announce::net, NET_PACKET_ONION_DATA_RESPONSE, ONION_MAX_PACKET_SIZE, ONION_RETURN_3, Onion_Announce_Entry::ret, Onion_Announce_Entry::ret_ip_port, and send_onion_response().
Referenced by new_onion_announce().
{
    Onion_Announce *onion_a = object;
    if (length <= DATA_REQUEST_MIN_SIZE_RECV)
        return 1;
    if (length > ONION_MAX_PACKET_SIZE)
        return 1;
    int index = in_entries(onion_a, packet + 1);
    if (index == -1)
        return 1;
    uint8_t data[length - (crypto_box_PUBLICKEYBYTES + ONION_RETURN_3)];
    data[0] = NET_PACKET_ONION_DATA_RESPONSE;
    memcpy(data + 1, packet + 1 + crypto_box_PUBLICKEYBYTES, length - (1 + crypto_box_PUBLICKEYBYTES +
      ONION_RETURN_3));
    if (send_onion_response(onion_a->net, onion_a->entries[index].
      ret_ip_port, data, sizeof(data),
                            onion_a->entries[index].ret) == -1)
        return 1;
    return 0;
}
static int in_entries (const Onion_Announce * onion_a, const uint8_t * public_key) [static]
Definition at line 208 of file onion_announce.c.
References Onion_Announce::entries, i, is_timeout(), ONION_ANNOUNCE_MAX_ENTRIES, ONION_ANNOUNCE_TIMEOUT, Onion_Announce_Entry::public_key, and Onion_Announce_Entry::time.
Referenced by add_to_entries(), handle_announce_request(), and handle_data_request().
{
    unsigned int i;
    for (i = 0; i < ONION_ANNOUNCE_MAX_ENTRIES; ++i) {
        if (!is_timeout(onion_a->entries[i].time,
      ONION_ANNOUNCE_TIMEOUT)
                && memcmp(onion_a->entries[i].public_key,
      public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return i;
    }
    return -1;
}
void kill_onion_announce (Onion_Announce * onion_a)
Definition at line 428 of file onion_announce.c.
References Onion_Announce::net, NET_PACKET_ANNOUNCE_REQUEST, NET_PACKET_ONION_DATA_REQUEST, and networking_registerhandler().
Referenced by kill_messenger(), kill_onions(), new_messenger(), and START_TEST().
{
    if (onion_a == NULL)
        return;
    networking_registerhandler(onion_a->net,
      NET_PACKET_ANNOUNCE_REQUEST, NULL, NULL);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ONION_DATA_REQUEST, NULL, NULL);
    free(onion_a);
}
Onion_Announce* new_onion_announce (DHT * dht)
Definition at line 408 of file onion_announce.c.
References Onion_Announce::dht, handle_announce_request(), handle_data_request(), Onion_Announce::net, DHT::net, NET_PACKET_ANNOUNCE_REQUEST, NET_PACKET_ONION_DATA_REQUEST, networking_registerhandler(), new_symmetric_key(), and Onion_Announce::secret_bytes.
Referenced by main(), new_messenger(), new_onions(), and START_TEST().
{
    if (dht == NULL)
        return NULL;
    Onion_Announce *onion_a = calloc(1, sizeof(Onion_Announce));
    if (onion_a == NULL)
        return NULL;
    onion_a->dht = dht;
    onion_a->net = dht->net;
    new_symmetric_key(onion_a->secret_bytes);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ANNOUNCE_REQUEST, &handle_announce_request,
      onion_a);
    networking_registerhandler(onion_a->net,
      NET_PACKET_ONION_DATA_REQUEST, &handle_data_request,
      onion_a);
    return onion_a;
}
int send_announce_request (Networking_Core * net, const Onion_Path * path, Node_format dest, const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * ping_id, const uint8_t * client_id, const uint8_t * data_public_key, uint64_t sendback_data)
Definition at line 132 of file onion_announce.c.
References create_announce_request(), create_onion_packet(), Node_format::ip_port, Onion_Path::ip_port1, ONION_ANNOUNCE_REQUEST_SIZE, ONION_MAX_PACKET_SIZE, Node_format::public_key, and sendpacket().
Referenced by START_TEST().
{
    uint8_t request[ONION_ANNOUNCE_REQUEST_SIZE];
    int len = create_announce_request(request, sizeof(request), dest.
      public_key, public_key, secret_key, ping_id, client_id,
                                      data_public_key, sendback_data);
    if (len != sizeof(request))
        return -1;
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    len = create_onion_packet(packet, sizeof(packet), path, dest.
      ip_port, request, sizeof(request));
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}
int send_data_request (Networking_Core * net, const Onion_Path * path, IP_Port dest, const uint8_t * public_key, const uint8_t * encrypt_public_key, const uint8_t * nonce, const uint8_t * data, uint16_t length)
Definition at line 169 of file onion_announce.c.
References create_data_request(), create_onion_packet(), Onion_Path::ip_port1, ONION_MAX_DATA_SIZE, ONION_MAX_PACKET_SIZE, and sendpacket().
Referenced by START_TEST().
{
    uint8_t request[ONION_MAX_DATA_SIZE];
    int len = create_data_request(request, sizeof(request),
      public_key, encrypt_public_key, nonce, data, length);
    if (len == -1)
        return -1;
    uint8_t packet[ONION_MAX_PACKET_SIZE];
    len = create_onion_packet(packet, sizeof(packet), path, dest, request, len);
    if (len == -1)
        return -1;
    if (sendpacket(net, path->ip_port1, packet, len) != len)
        return -1;
    return 0;
}
Variable Documentation
uint8_t cmp_public_key[crypto_box_PUBLICKEYBYTES] [static]
Definition at line 221 of file onion_announce.c.
Referenced by add_to_entries(), and cmp_entry().