toxcore/list.h File Reference
#include <stdlib.h>
*
#include <stdint.h>
*
#include <string.h>
*
Data Structures
struct BS_LIST
Functions
int bs_list_init (BS_LIST *list, uint32_t element_size, uint32_t initial_capacity)
void bs_list_free (BS_LIST *list)
int bs_list_find (const BS_LIST *list, const uint8_t *data)
int bs_list_add (BS_LIST *list, const uint8_t *data, int id)
int bs_list_remove (BS_LIST *list, const uint8_t *data, int id)
int bs_list_trim (BS_LIST *list)
Function Documentation
int bs_list_add (BS_LIST * list, const uint8_t * data, int id)
Definition at line 177 of file list.c.
References BS_LIST::capacity, BS_LIST::data, BS_LIST::element_size, find(), i, BS_LIST::ids, BS_LIST::n, and resize().
Referenced by add_accepted(), crypto_connection_add_source(), and set_direct_ip_port().
{
    //find where the new element should be inserted
    //see: return value of find()
    int i = find(list, data);
    if (i >= 0) {
        //already in list
        return 0;
    }
    i = ~i;
    //increase the size of the arrays if needed
    if (list->n == list->capacity) {
        // 1.5 * n + 1
        const uint32_t new_capacity = list->n + list->n / 2 + 1;
        if (!resize(list, new_capacity)) {
            return 0;
        }
        list->capacity = new_capacity;
    }
    //insert data to element array
    memmove(list->data + (i + 1) * list->element_size, list->
      data + i * list->element_size,
            (list->n - i) * list->element_size);
    memcpy(list->data + i * list->element_size, data, list->
      element_size);
    //insert id to id array
    memmove(&list->ids[i + 1], &list->ids[i], (list->n - i) * sizeof(int));
    list->ids[i] = id;
    //increase n
    list->n++;
    return 1;
}
int bs_list_find (const BS_LIST * list, const uint8_t * data)
Definition at line 165 of file list.c.
References find(), and BS_LIST::ids.
Referenced by crypto_id_ip_port(), and get_TCP_connection_index().
{
    int r = find(list, data);
    //return only -1 and positive values
    if (r < 0) {
        return -1;
    }
    return list->ids[r];
}
void bs_list_free (BS_LIST * list)
Definition at line 158 of file list.c.
References BS_LIST::data, and BS_LIST::ids.
Referenced by kill_net_crypto(), and kill_TCP_server().
{
    //free both arrays
    free(list->data);
    free(list->ids);
}
int bs_list_init (BS_LIST * list, uint32_t element_size, uint32_t initial_capacity)
Definition at line 138 of file list.c.
References BS_LIST::capacity, BS_LIST::data, BS_LIST::element_size, BS_LIST::ids, BS_LIST::n, and resize().
Referenced by new_net_crypto(), and new_TCP_server().
{
    //set initial values
    list->n = 0;
    list->element_size = element_size;
    list->capacity = 0;
    list->data = NULL;
    list->ids = NULL;
    if (initial_capacity != 0) {
        if (!resize(list, initial_capacity)) {
            return 0;
        }
    }
    list->capacity = initial_capacity;
    return 1;
}
int bs_list_remove (BS_LIST * list, const uint8_t * data, int id)
Definition at line 217 of file list.c.
References BS_LIST::capacity, BS_LIST::data, BS_LIST::element_size, find(), i, BS_LIST::ids, BS_LIST::n, and resize().
Referenced by crypto_connection_add_source(), crypto_kill(), del_accepted(), and set_direct_ip_port().
{
    int i = find(list, data);
    if (i < 0) {
        return 0;
    }
    if (list->ids[i] != id) {
        //this should never happen
        return 0;
    }
    //decrease the size of the arrays if needed
    if (list->n < list->capacity / 2) {
        const uint32_t new_capacity = list->capacity / 2;
        if (resize(list, new_capacity)) {
            list->capacity = new_capacity;
        }
    }
    list->n--;
    memmove(list->data + i * list->element_size, list->data + (i + 1) * list->
      element_size,
            (list->n - i) * list->element_size);
    memmove(&list->ids[i], &list->ids[i + 1], (list->n - i) * sizeof(int));
    return 1;
}
int bs_list_trim (BS_LIST * list)
Definition at line 248 of file list.c.
References BS_LIST::capacity, BS_LIST::n, and resize().
{
    if (!resize(list, list->n)) {
        return 0;
    }
    list->capacity = list->n;
    return 1;
}