toxcore/LAN_discovery.c File Reference
#include `LAN_discovery.h`
*
#include `util.h`
*
Macros
#define MAX_INTERFACES 16
Functions
static void fetch_broadcast_info (uint16_t port)
static uint32_t send_broadcasts (Networking_Core *net, uint16_t port, const uint8_t *data, uint16_t length)
static IP broadcast_ip (sa_family_t family_socket, sa_family_t family_broadcast)
_Bool Local_ip (IP ip)
int LAN_ip (IP ip)
static int handle_LANdiscovery (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
int send_LANdiscovery (uint16_t port, DHT *dht)
void LANdiscovery_init (DHT *dht)
void LANdiscovery_kill (DHT *dht)
Variables
static int broadcast_count = -1
static IP_Port broadcast_ip_port [MAX_INTERFACES]
Macro Definition Documentation
#define MAX_INTERFACES 16
Definition at line 38 of file LAN_discovery.c.
Function Documentation
static IP broadcast_ip (sa_family_t family_socket, sa_family_t family_broadcast) [static]
Definition at line 199 of file LAN_discovery.c.
References IP::family, ip, IP::ip4, IP::ip6, ip_reset(), IP4::uint32, IP6::uint32, and IP6::uint8.
Referenced by send_LANdiscovery().
{
    IP ip;
    ip_reset(&ip);
    if (family_socket == AF_INET6) {
        if (family_broadcast == AF_INET6) {
            ip.family = AF_INET6;
            /* FF02::1 is - according to RFC 4291 - multicast all-nodes link-local */
            /* FE80::*: MUST be exact, for that we would need to look over all
             * interfaces and check in which status they are */
            ip.ip6.uint8[ 0] = 0xFF;
            ip.ip6.uint8[ 1] = 0x02;
            ip.ip6.uint8[15] = 0x01;
        } else if (family_broadcast == AF_INET) {
            ip.family = AF_INET6;
            ip.ip6.uint32[0] = 0;
            ip.ip6.uint32[1] = 0;
            ip.ip6.uint32[2] = htonl(0xFFFF);
            ip.ip6.uint32[3] = INADDR_BROADCAST;
        }
    } else if (family_socket == AF_INET) {
        if (family_broadcast == AF_INET) {
            ip.family = AF_INET;
            ip.ip4.uint32 = INADDR_BROADCAST;
        }
    }
    return ip;
}
static void fetch_broadcast_info (uint16_t port) [static]
Definition at line 169 of file LAN_discovery.c.
References broadcast_count.
Referenced by send_broadcasts().
{
    broadcast_count = 0;
}
static int handle_LANdiscovery (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 309 of file LAN_discovery.c.
References DHT_bootstrap(), IP_Port::ip, and LAN_ip().
Referenced by LANdiscovery_init().
{
    DHT *dht = object;
    if (LAN_ip(source.ip) == -1)
        return 1;
    if (length != crypto_box_PUBLICKEYBYTES + 1)
        return 1;
    DHT_bootstrap(dht, source, packet + 1);
    return 0;
}
int LAN_ip (IP ip)
Definition at line 259 of file LAN_discovery.c.
References IP::family, IP::ip4, IP::ip6, IPV6_IPV4_IN_V6, LAN_ip(), Local_ip(), IP4::uint32, IP6::uint32, IP4::uint8, and IP6::uint8.
Referenced by Assoc_get_close_entries(), client_or_ip_port_in_list(), client_ping_nodes(), DHT_non_lan_connected(), entry_heard_store(), get_close_nodes_inner(), handle_announce_request(), handle_LANdiscovery(), handle_sendnodes_ipv6(), LAN_ip(), sendnodes_ipv6(), and set_direct_ip_port().
{
    if (Local_ip(ip))
        return 0;
    if (ip.family == AF_INET) {
        IP4 ip4 = ip.ip4;
        /* 10.0.0.0 to 10.255.255.255 range. */
        if (ip4.uint8[0] == 10)
            return 0;
        /* 172.16.0.0 to 172.31.255.255 range. */
        if (ip4.uint8[0] == 172 && ip4.uint8[1] >= 16 && ip4.uint8[1] <= 31)
            return 0;
        /* 192.168.0.0 to 192.168.255.255 range. */
        if (ip4.uint8[0] == 192 && ip4.uint8[1] == 168)
            return 0;
        /* 169.254.1.0 to 169.254.254.255 range. */
        if (ip4.uint8[0] == 169 && ip4.uint8[1] == 254 && ip4.uint8[2] != 0
                && ip4.uint8[2] != 255)
            return 0;
        /* RFC 6598: 100.64.0.0 to 100.127.255.255 (100.64.0.0/10)
         * (shared address space to stack another layer of NAT) */
        if ((ip4.uint8[0] == 100) && ((ip4.uint8[1] & 0xC0) == 0x40))
            return 0;
    } else if (ip.family == AF_INET6) {
        /* autogenerated for each interface: FE80::* (up to FEBF::*)
           FF02::1 is - according to RFC 4291 - multicast all-nodes link-local */
        if (((ip.ip6.uint8[0] == 0xFF) && (ip.ip6.uint8[1] < 3) && (ip.
      ip6.uint8[15] == 1)) ||
                ((ip.ip6.uint8[0] == 0xFE) && ((ip.ip6.uint8[1] & 0xC0) == 0x80)))
            return 0;
        /* embedded IPv4-in-IPv6 */
        if (IPV6_IPV4_IN_V6(ip.ip6)) {
            IP ip4;
            ip4.family = AF_INET;
            ip4.ip4.uint32 = ip.ip6.uint32[3];
            return LAN_ip(ip4);
        }
    }
    return -1;
}
void LANdiscovery_init (DHT * dht)
Definition at line 356 of file LAN_discovery.c.
References handle_LANdiscovery(), DHT::net, NET_PACKET_LAN_DISCOVERY, and networking_registerhandler().
Referenced by main(), and new_friend_connections().
{
    networking_registerhandler(dht->net,
      NET_PACKET_LAN_DISCOVERY, &handle_LANdiscovery, dht);
}
void LANdiscovery_kill (DHT * dht)
Definition at line 361 of file LAN_discovery.c.
References DHT::net, NET_PACKET_LAN_DISCOVERY, and networking_registerhandler().
Referenced by kill_friend_connections().
{
    networking_registerhandler(dht->net,
      NET_PACKET_LAN_DISCOVERY, NULL, NULL);
}
_Bool Local_ip (IP ip)
Definition at line 231 of file LAN_discovery.c.
References IP::family, IP::ip4, IP::ip6, IPV6_IPV4_IN_V6, Local_ip(), IP4::uint32, IP6::uint32, IP6::uint64, and IP4::uint8.
Referenced by friend_add_tcp_relay(), LAN_ip(), and Local_ip().
{
    if (ip.family == AF_INET) {
        IP4 ip4 = ip.ip4;
        /* Loopback. */
        if (ip4.uint8[0] == 127)
            return 1;
    } else {
        /* embedded IPv4-in-IPv6 */
        if (IPV6_IPV4_IN_V6(ip.ip6)) {
            IP ip4;
            ip4.family = AF_INET;
            ip4.ip4.uint32 = ip.ip6.uint32[3];
            return Local_ip(ip4);
        }
        /* localhost in IPv6 (::1) */
        if (ip.ip6.uint64[0] == 0 && ip.ip6.uint32[2] == 0 && ip.
      ip6.uint32[3] == htonl(1))
            return 1;
    }
    return 0;
}
static uint32_t send_broadcasts (Networking_Core * net, uint16_t port, const uint8_t * data, uint16_t length) [static]
Definition at line 180 of file LAN_discovery.c.
References broadcast_count, fetch_broadcast_info(), i, and sendpacket().
Referenced by send_LANdiscovery().
{
    /* fetch only once? on every packet? every X seconds?
     * old: every packet, new: once */
    if (broadcast_count < 0)
        fetch_broadcast_info(port);
    if (!broadcast_count)
        return 0;
    int i;
    for (i = 0; i < broadcast_count; i++)
        sendpacket(net, broadcast_ip_port[i], data, length);
    return 1;
}
int send_LANdiscovery (uint16_t port, DHT * dht)
Definition at line 324 of file LAN_discovery.c.
References broadcast_ip(), make-funny-savefile::data, Networking_Core::family, id_copy(), IP_Port::ip, ip_isset(), DHT::net, NET_PACKET_LAN_DISCOVERY, port, IP_Port::port, DHT::self_public_key, send_broadcasts(), and sendpacket().
Referenced by LANdiscovery(), and main().
{
    uint8_t data[crypto_box_PUBLICKEYBYTES + 1];
    data[0] = NET_PACKET_LAN_DISCOVERY;
    id_copy(data + 1, dht->self_public_key);
    send_broadcasts(dht->net, port, data, 1 + crypto_box_PUBLICKEYBYTES);
    int res = -1;
    IP_Port ip_port;
    ip_port.port = port;
    /* IPv6 multicast */
    if (dht->net->family == AF_INET6) {
        ip_port.ip = broadcast_ip(AF_INET6, AF_INET6);
        if (ip_isset(&ip_port.ip))
            if (sendpacket(dht->net, ip_port, data, 1 + crypto_box_PUBLICKEYBYTES) > 0)
                res = 1;
    }
    /* IPv4 broadcast (has to be IPv4-in-IPv6 mapping if socket is AF_INET6 */
    ip_port.ip = broadcast_ip(dht->net->family, AF_INET);
    if (ip_isset(&ip_port.ip))
        if (sendpacket(dht->net, ip_port, data, 1 + crypto_box_PUBLICKEYBYTES))
            res = 1;
    return res;
}
Variable Documentation
int broadcast_count = -1 [static]
Definition at line 41 of file LAN_discovery.c.
Referenced by fetch_broadcast_info(), and send_broadcasts().
IP_Port broadcast_ip_port[MAX_INTERFACES] [static]
Definition at line 42 of file LAN_discovery.c.