toxav/toxav.c File Reference
#include `codec.h`
*
#include `msi.h`
*
#include `group.h`
*
#include `../toxcore/logger.h`
*
#include `../toxcore/util.h`
*
#include <assert.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Data Structures
struct _ToxAvCall
struct _ToxAv
Macros
#define TOX_DEFINED
#define _GNU_SOURCE /* implicit declaration warning */
#define MAX_ENCODE_TIME_US ((1000 / 24) * 1000)
#define CALL_INVALID_INDEX(idx, max) (idx < 0 || idx >= max)
Typedefs
typedef struct Messenger Tox
typedef struct _ToxAvCall ToxAvCall
Functions
static const MSICSettings * msicsettings_cast (const ToxAvCSettings *from)
static const ToxAvCSettings * toxavcsettings_cast (const MSICSettings *from)
ToxAv * toxav_new (Tox *messenger, int32_t max_calls)
void toxav_kill (ToxAv *av)
uint32_t toxav_do_interval (ToxAv *av)
void toxav_do (ToxAv *av)
void toxav_register_callstate_callback (ToxAv *av, ToxAVCallback cb, ToxAvCallbackID id, void *userdata)
void toxav_register_audio_callback (ToxAv *av, ToxAvAudioCallback cb, void *userdata)
void toxav_register_video_callback (ToxAv *av, ToxAvVideoCallback cb, void *userdata)
int toxav_call (ToxAv *av, int32_t *call_index, int user, const ToxAvCSettings *csettings, int ringing_seconds)
int toxav_hangup (ToxAv *av, int32_t call_index)
int toxav_answer (ToxAv *av, int32_t call_index, const ToxAvCSettings *csettings)
int toxav_reject (ToxAv *av, int32_t call_index, const char *reason)
int toxav_cancel (ToxAv *av, int32_t call_index, int peer_id, const char *reason)
int toxav_change_settings (ToxAv *av, int32_t call_index, const ToxAvCSettings *csettings)
int toxav_stop_call (ToxAv *av, int32_t call_index)
int toxav_prepare_transmission (ToxAv *av, int32_t call_index, int support_video)
int toxav_kill_transmission (ToxAv *av, int32_t call_index)
static int toxav_send_rtp_payload (ToxAv *av, ToxAvCall *call, ToxAvCallType type, const uint8_t *payload, unsigned int length)
int toxav_prepare_video_frame (ToxAv *av, int32_t call_index, uint8_t *dest, int dest_max, vpx_image_t *input)
int toxav_send_video (ToxAv *av, int32_t call_index, const uint8_t *frame, unsigned int frame_size)
int toxav_prepare_audio_frame (ToxAv *av, int32_t call_index, uint8_t *dest, int dest_max, const int16_t *frame, int frame_size)
int toxav_send_audio (ToxAv *av, int32_t call_index, const uint8_t *data, unsigned int size)
int toxav_get_peer_csettings (ToxAv *av, int32_t call_index, int peer, ToxAvCSettings *dest)
int toxav_get_peer_id (ToxAv *av, int32_t call_index, int peer)
ToxAvCallState toxav_get_call_state (ToxAv *av, int32_t call_index)
int toxav_capability_supported (ToxAv *av, int32_t call_index, ToxAvCapabilities capability)
Tox * toxav_get_tox (ToxAv *av)
int toxav_get_active_count (ToxAv *av)
int toxav_add_av_groupchat (Tox *tox, void(*audio_callback)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *), void *userdata)
int toxav_join_av_groupchat (Tox *tox, int32_t friendnumber, const uint8_t *data, uint16_t length, void(*audio_callback)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *), void *userdata)
int toxav_group_send_audio (Tox *tox, int groupnumber, const int16_t *pcm, unsigned int samples, uint8_t channels, unsigned int sample_rate)
Variables
const ToxAvCSettings av_DefaultSettings
static const uint32_t jbuf_capacity = 6
static const uint8_t audio_index = 0
static const uint8_t video_index = 1
Macro Definition Documentation
#define _GNU_SOURCE /* implicit declaration warning */
Definition at line 29 of file toxav.c.
#define CALL_INVALID_INDEX(idx, max) (idx < 0 || idx >= max)
Definition at line 46 of file toxav.c.
Referenced by toxav_get_call_state(), toxav_get_peer_csettings(), toxav_get_peer_id(), toxav_kill_transmission(), toxav_prepare_audio_frame(), toxav_prepare_transmission(), toxav_prepare_video_frame(), toxav_send_audio(), and toxav_send_video().
#define MAX_ENCODE_TIME_US ((1000 / 24) * 1000)
Definition at line 43 of file toxav.c.
Referenced by toxav_prepare_video_frame().
#define TOX_DEFINED
toxav.c
Copyright (C) 2013 Tox project All Rights Reserved.
This file is part of Tox.
Tox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Tox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Tox. If not, see http://www.gnu.org/licenses/.
Definition at line 26 of file toxav.c.
Typedef Documentation
typedef struct Messenger Tox
Definition at line 27 of file toxav.c.
typedef struct _ToxAvCall ToxAvCall
Function Documentation
static const MSICSettings* msicsettings_cast (const ToxAvCSettings * from) [static]
Definition at line 89 of file toxav.c.
Referenced by toxav_answer(), toxav_call(), and toxav_change_settings().
{
    assert(sizeof(MSICSettings) == sizeof(ToxAvCSettings));
    return (const MSICSettings *) from;
}
int toxav_add_av_groupchat (Tox * tox, void(*)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *) audio_callback, void * userdata)
Definition at line 653 of file toxav.c.
References add_av_groupchat(), Messenger::group_chat_object, and m.
{
    Messenger *m = tox;
    return add_av_groupchat(m->group_chat_object, audio_callback, userdata
      );
}
int toxav_answer (ToxAv * av, int32_t call_index, const ToxAvCSettings * csettings)
Answer incoming call. Pass the csettings that you will use.
Definition at line 240 of file toxav.c.
References msi_answer(), _ToxAv::msi_session, and msicsettings_cast().
Referenced by in_thread_call().
{
    return msi_answer(av->msi_session, call_index,
      msicsettings_cast(csettings));
}
int toxav_call (ToxAv * av, int32_t * call_index, int friend_id, const ToxAvCSettings * csettings, int ringing_seconds)
Call user. Use its friend_id.
Definition at line 226 of file toxav.c.
References msi_invite(), _ToxAv::msi_session, and msicsettings_cast().
Referenced by in_thread_call(), and START_TEST().
{
    return msi_invite(av->msi_session, call_index,
      msicsettings_cast(csettings), ringing_seconds * 1000, user);
}
int toxav_cancel (ToxAv * av, int32_t call_index, int peer_id, const char * reason)
Cancel outgoing request.
Definition at line 250 of file toxav.c.
References msi_cancel(), and _ToxAv::msi_session.
Referenced by START_TEST().
{
    return msi_cancel(av->msi_session, call_index, peer_id, reason);
}
int toxav_capability_supported (ToxAv * av, int32_t call_index, ToxAvCapabilities capability)
Is certain capability supported. Used to determine if encoding/decoding is ready.
Definition at line 615 of file toxav.c.
References _ToxAv::calls, _CSSession::capabilities, and _ToxAvCall::cs.
{
    return av->calls[call_index].cs ? av->calls[call_index].cs->
      capabilities & (CSCapabilities) capability : 0;
    /* 0 is error here */
}
int toxav_change_settings (ToxAv * av, int32_t call_index, const ToxAvCSettings * csettings)
Notify peer that we are changing codec settings.
Definition at line 255 of file toxav.c.
References msi_change_csettings(), _ToxAv::msi_session, and msicsettings_cast().
Referenced by START_TEST().
{
    return msi_change_csettings(av->msi_session, call_index,
      msicsettings_cast(csettings));
}
void toxav_do (ToxAv * av)
Main loop for the session. Best called right after tox_do();
Definition at line 176 of file toxav.c.
References _ToxAvCall::active, _ToxAv::calls, _ToxAvCall::cs, cs_do(), current_time_monotonic(), end, i, _ToxAv::max_calls, msi_do(), _ToxAv::msi_session, _ToxAvCall::mutex, _ToxAvCall::mutex_do, and start.
Referenced by START_TEST().
{
    msi_do(av->msi_session);
    uint64_t start = current_time_monotonic();
    uint32_t i = 0;
    for (; i < av->max_calls; i ++) {
        pthread_mutex_lock(av->calls[i].mutex);
        if (av->calls[i].active) {
            pthread_mutex_lock(av->calls[i].mutex_do);
            pthread_mutex_unlock(av->calls[i].mutex);
            cs_do(av->calls[i].cs);
            pthread_mutex_unlock(av->calls[i].mutex_do);
        } else {
            pthread_mutex_unlock(av->calls[i].mutex);
        }
    }
    uint64_t end = current_time_monotonic();
    /* TODO maybe use variable for sizes */
    av->dectmsstotal += end - start;
    if (++av->dectmsscount == 3) {
        av->avgdectms = av->dectmsstotal / 3 + 2 /* NOTE Magic Offset */;
        av->dectmsscount = 0;
        av->dectmsstotal = 0;
    }
}
uint32_t toxav_do_interval (ToxAv * av)
Returns the interval in milliseconds when the next toxav_do() should be called. If no call is active at the moment returns 200.
Definition at line 157 of file toxav.c.
References _ToxAvCall::active, _CSSession::audio_decoder_frame_duration, _ToxAv::calls, _ToxAvCall::cs, i, _ToxAv::max_calls, MIN, and _ToxAvCall::mutex.
{
    int i = 0;
    uint32_t rc = 200 + av->avgdectms; /* Return 200 if no call is active */
    for (; i < av->max_calls; i ++) {
        pthread_mutex_lock(av->calls[i].mutex);
        if (av->calls[i].active) {
            /* This should work. Video payload will always come in greater intervals */
            rc = MIN(av->calls[i].cs->audio_decoder_frame_duration,
      rc);
        }
        pthread_mutex_unlock(av->calls[i].mutex);
    }
    return rc < av->avgdectms ? 0 : rc - av->avgdectms;
}
int toxav_get_active_count (ToxAv * av)
Returns number of active calls or -1 on error.
Definition at line 626 of file toxav.c.
References _ToxAvCall::active, _ToxAv::calls, i, _ToxAv::max_calls, and _ToxAvCall::mutex.
{
    if (!av) return -1;
    int rc = 0, i = 0;
    for (; i < av->max_calls; i++) {
        pthread_mutex_lock(av->calls[i].mutex);
        if (av->calls[i].active) rc++;
        pthread_mutex_unlock(av->calls[i].mutex);
    }
    return rc;
}
ToxAvCallState toxav_get_call_state (ToxAv * av, int32_t call_index)
Get current call state.
Definition at line 606 of file toxav.c.
References av_CallNonExistent, CALL_INVALID_INDEX, _MSISession::calls, _MSISession::max_calls, _ToxAv::msi_session, and _MSICall::state.
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls) || !av->msi_session->calls[call_index])
        return av_CallNonExistent;
    return av->msi_session->calls[call_index]->state;
}
int toxav_get_peer_csettings (ToxAv * av, int32_t call_index, int peer, ToxAvCSettings * dest)
Get codec settings from the peer. These were exchanged during call initialization or when peer send us new csettings.
Definition at line 587 of file toxav.c.
References av_ErrorNoCall, av_ErrorNone, CALL_INVALID_INDEX, _MSISession::calls, _MSICall::csettings_peer, _MSISession::max_calls, _ToxAv::msi_session, _MSICall::peer_count, and toxavcsettings_cast().
Referenced by callback_peer_cs_change(), and callback_self_cs_change().
{
    if (peer < 0 || CALL_INVALID_INDEX(call_index, av->
      msi_session->max_calls) ||
            !av->msi_session->calls[call_index] || av->
      msi_session->calls[call_index]->peer_count <= peer)
        return av_ErrorNoCall;
    *dest = *toxavcsettings_cast(&av->msi_session->
      calls[call_index]->csettings_peer[peer]);
    return av_ErrorNone;
}
int toxav_get_peer_id (ToxAv * av, int32_t call_index, int peer)
Get friend id of peer participating in conversation.
Definition at line 597 of file toxav.c.
References av_ErrorNoCall, CALL_INVALID_INDEX, _MSISession::calls, _MSISession::max_calls, _ToxAv::msi_session, _MSICall::peer_count, and _MSICall::peers.
{
    if (peer < 0 || CALL_INVALID_INDEX(call_index, av->
      msi_session->max_calls) || !av->msi_session->
      calls[call_index]
            || av->msi_session->calls[call_index]->peer_count <= peer)
        return av_ErrorNoCall;
    return av->msi_session->calls[call_index]->peers[peer];
}
Tox* toxav_get_tox (ToxAv * av)
Returns tox reference.
Definition at line 621 of file toxav.c.
References _ToxAv::messenger.
{
    return (Tox *)av->messenger;
}
int toxav_group_send_audio (Tox * tox, int groupnumber, const int16_t * pcm, unsigned int samples, uint8_t channels, unsigned int sample_rate)
Definition at line 691 of file toxav.c.
References Messenger::group_chat_object, group_send_audio(), and m.
{
    Messenger *m = tox;
    return group_send_audio(m->group_chat_object, groupnumber, pcm,
      samples, channels, sample_rate);
}
int toxav_hangup (ToxAv * av, int32_t call_index)
Hangup active call.
Definition at line 235 of file toxav.c.
References msi_hangup(), and _ToxAv::msi_session.
Referenced by in_thread_call(), and START_TEST().
{
    return msi_hangup(av->msi_session, call_index);
}
int toxav_join_av_groupchat (Tox * tox, int32_t friendnumber, const uint8_t * data, uint16_t length, void(*)(Messenger *, int, int, const int16_t *, unsigned int, uint8_t, unsigned int, void *) audio_callback, void * userdata)
Definition at line 670 of file toxav.c.
References Messenger::group_chat_object, join_av_groupchat(), and m.
{
    Messenger *m = tox;
    return join_av_groupchat(m->group_chat_object, friendnumber,
      data, length, audio_callback, userdata);
}
void toxav_kill (ToxAv * av)
Remove A/V session.
Definition at line 133 of file toxav.c.
References audio_index, _ToxAv::calls, _ToxAvCall::crtps, _ToxAvCall::cs, cs_kill(), i, _ToxAv::max_calls, _MSISession::messenger_handle, msi_kill(), _ToxAv::msi_session, _ToxAvCall::mutex, rtp_kill(), and video_index.
{
    uint32_t i;
    for (i = 0; i < av->max_calls; i ++) {
        if (av->calls[i].crtps[audio_index])
            rtp_kill(av->calls[i].crtps[audio_index], av->
      msi_session->messenger_handle);
        if (av->calls[i].crtps[video_index])
            rtp_kill(av->calls[i].crtps[video_index], av->
      msi_session->messenger_handle);
        if (av->calls[i].cs)
            cs_kill(av->calls[i].cs);
        pthread_mutex_destroy(av->calls[i].mutex);
    }
    msi_kill(av->msi_session);
    free(av->calls);
    free(av);
}
int toxav_kill_transmission (ToxAv * av, int32_t call_index)
Clears transmission data. Call this at the end of the transmission.
Definition at line 370 of file toxav.c.
References _ToxAvCall::active, audio_index, av_ErrorInvalidState, av_ErrorNoCall, av_ErrorNone, CALL_INVALID_INDEX, _ToxAv::calls, _ToxAvCall::crtps, _ToxAvCall::cs, cs_kill(), LOGGER_WARNING, _MSISession::max_calls, _ToxAv::messenger, _ToxAv::msi_session, _ToxAvCall::mutex, _ToxAvCall::mutex_do, _ToxAvCall::mutex_encoding_audio, _ToxAvCall::mutex_encoding_video, rtp_kill(), and video_index.
Referenced by in_thread_call(), and START_TEST().
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls)) {
        LOGGER_WARNING("Invalid call index: %d", call_index);
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (!call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Action on inactive call: %d", call_index);
        return av_ErrorInvalidState;
    }
    call->active = 0;
    pthread_mutex_lock(call->mutex_encoding_audio);
    pthread_mutex_unlock(call->mutex_encoding_audio);
    pthread_mutex_lock(call->mutex_encoding_video);
    pthread_mutex_unlock(call->mutex_encoding_video);
    pthread_mutex_lock(call->mutex_do);
    pthread_mutex_unlock(call->mutex_do);
    rtp_kill(call->crtps[audio_index], av->messenger);
    call->crtps[audio_index] = NULL;
    rtp_kill(call->crtps[video_index], av->messenger);
    call->crtps[video_index] = NULL;
    cs_kill(call->cs);
    call->cs = NULL;
    pthread_mutex_destroy(call->mutex_encoding_audio);
    pthread_mutex_destroy(call->mutex_encoding_video);
    pthread_mutex_destroy(call->mutex_do);
    pthread_mutex_unlock(call->mutex);
    return av_ErrorNone;
}
ToxAv* toxav_new (Tox * messenger, int32_t max_calls)
Start new A/V session. There can only be one session at the time.
Definition at line 102 of file toxav.c.
References _MSISession::agent_handler, _ToxAv::calls, create_recursive_mutex(), i, LOGGER_WARNING, _ToxAv::max_calls, _ToxAv::messenger, msi_kill(), msi_new(), _ToxAv::msi_session, and _ToxAvCall::mutex.
Referenced by START_TEST().
{
    ToxAv *av = calloc (sizeof(ToxAv), 1);
    if (av == NULL) {
        LOGGER_WARNING("Allocation failed!");
        return NULL;
    }
    av->messenger = (Messenger *)messenger;
    av->msi_session = msi_new(av->messenger, max_calls);
    av->msi_session->agent_handler = av;
    av->calls = calloc(sizeof(ToxAvCall), max_calls);
    av->max_calls = max_calls;
    unsigned int i;
    for (i = 0; i < max_calls; ++i) {
        if (create_recursive_mutex(av->calls[i].mutex) != 0) {
            LOGGER_WARNING("Failed to init call(%u) mutex!", i);
            msi_kill(av->msi_session);
            free(av->calls);
            free(av);
            return NULL;
        }
    }
    return av;
}
int toxav_prepare_audio_frame (ToxAv * av, int32_t call_index, uint8_t * dest, int dest_max, const int16_t * frame, int frame_size)
Encode audio frame.
Definition at line 531 of file toxav.c.
References _ToxAvCall::active, _CSSession::audio_encoder, av_ErrorEncodingAudio, av_ErrorInvalidState, av_ErrorNoCall, CALL_INVALID_INDEX, _ToxAv::calls, _ToxAvCall::cs, LOGGER_ERROR, LOGGER_WARNING, _MSISession::max_calls, _ToxAv::msi_session, _ToxAvCall::mutex, and _ToxAvCall::mutex_encoding_audio.
Referenced by in_thread_call(), and START_TEST().
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls)) {
        LOGGER_WARNING("Action on nonexisting call: %d", call_index);
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (!call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Action on inactive call: %d", call_index);
        return av_ErrorInvalidState;
    }
    pthread_mutex_lock(call->mutex_encoding_audio);
    pthread_mutex_unlock(call->mutex);
    int32_t rc = opus_encode(call->cs->audio_encoder, frame, frame_size, dest, dest_max);
    pthread_mutex_unlock(call->mutex_encoding_audio);
    if (rc < 0) {
        LOGGER_ERROR("Failed to encode payload: %s\n", opus_strerror(rc));
        return av_ErrorEncodingAudio;
    }
    return rc;
}
int toxav_prepare_transmission (ToxAv * av, int32_t call_index, int support_video)
Allocates transmission data. Must be call before calling toxav_prepare_* and toxav_send_*. Also, it must be called when call is started
Definition at line 265 of file toxav.c.
References _ToxAvCall::active, _CSSession::agent, _ToxAvCSettings::audio_bitrate, _ToxAvCSettings::audio_channels, _ToxAvCSettings::audio_frame_duration, audio_index, _ToxAvCSettings::audio_sample_rate, av_ErrorAlreadyInCallWithPeer, av_ErrorCreatingRtpSessions, av_ErrorInitializingCodecs, av_ErrorNoCall, av_ErrorNone, av_ErrorUnknown, _CSSession::call_idx, CALL_INVALID_INDEX, _ToxAvCSettings::call_type, _ToxAv::calls, _MSISession::calls, _ToxAvCall::crtps, _ToxAvCall::cs, _RTPSession::cs, cs_kill(), cs_new(), _MSICall::csettings_local, _MSICall::csettings_peer, error, jbuf_capacity, LOGGER_DEBUG, LOGGER_ERROR, _MSISession::max_calls, _ToxAvCSettings::max_video_height, _ToxAvCSettings::max_video_width, _ToxAv::messenger, _ToxAv::msi_session, msi_TypeAudio, msi_TypeVideo, _ToxAvCall::mutex, _ToxAvCall::mutex_do, _ToxAvCall::mutex_encoding_audio, _ToxAvCall::mutex_encoding_video, _MSICall::peers, rtp_kill(), rtp_new(), toxavcsettings_cast(), _ToxAvCSettings::video_bitrate, and video_index.
Referenced by callback_call_started(), and in_thread_call().
{
    if (!av->msi_session || CALL_INVALID_INDEX(call_index, av->
      msi_session->max_calls) ||
            !av->msi_session->calls[call_index] || !av->
      msi_session->calls[call_index]->csettings_peer) {
        LOGGER_ERROR("Error while starting RTP session: invalid call!\n");
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_ERROR("Error while starting RTP session: call already active!\n");
        return av_ErrorAlreadyInCallWithPeer;
    }
    if (pthread_mutex_init(call->mutex_encoding_audio, NULL) != 0
            || pthread_mutex_init(call->mutex_encoding_video, NULL) != 0 ||
      pthread_mutex_init(call->mutex_do, NULL) != 0) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_ERROR("Error while starting RTP session: mutex initializing failed!\n");
        return av_ErrorUnknown;
    }
    const ToxAvCSettings *c_peer = toxavcsettings_cast
                                   (&av->msi_session->calls[call_index]->
      csettings_peer[0]);
    const ToxAvCSettings *c_self = toxavcsettings_cast
                                   (&av->msi_session->calls[call_index]->
      csettings_local);
    LOGGER_DEBUG(
        "Type: %u(s) %u(p)\n"
        "Video bitrate: %u(s) %u(p)\n"
        "Video height: %u(s) %u(p)\n"
        "Video width: %u(s) %u(p)\n"
        "Audio bitrate: %u(s) %u(p)\n"
        "Audio framedur: %u(s) %u(p)\n"
        "Audio sample rate: %u(s) %u(p)\n"
        "Audio channels: %u(s) %u(p)\n",
        c_self->call_type, c_peer->call_type,
        c_self->video_bitrate, c_peer->video_bitrate,
        c_self->max_video_height, c_peer->max_video_height,
        c_self->max_video_width, c_peer->max_video_width,
        c_self->audio_bitrate, c_peer->audio_bitrate,
        c_self->audio_frame_duration, c_peer->
      audio_frame_duration,
        c_self->audio_sample_rate, c_peer->
      audio_sample_rate,
        c_self->audio_channels, c_peer->audio_channels);
    if (!(call->cs = cs_new(c_self, c_peer, jbuf_capacity, support_video))) {
        LOGGER_ERROR("Error while starting Codec State!\n");
        pthread_mutex_unlock(call->mutex);
        return av_ErrorInitializingCodecs;
    }
    call->cs->agent = av;
    call->cs->call_idx = call_index;
    call->cs->acb.first = av->acb.first;
    call->cs->acb.second = av->acb.second;
    call->cs->vcb.first = av->vcb.first;
    call->cs->vcb.second = av->vcb.second;
    call->crtps[audio_index] =
        rtp_new(msi_TypeAudio, av->messenger, av->
      msi_session->calls[call_index]->peers[0]);
    if (!call->crtps[audio_index]) {
        LOGGER_ERROR("Error while starting audio RTP session!\n");
        goto error;
    }
    call->crtps[audio_index]->cs = call->cs;
    if (support_video) {
        call->crtps[video_index] =
            rtp_new(msi_TypeVideo, av->messenger, av->
      msi_session->calls[call_index]->peers[0]);
        if (!call->crtps[video_index]) {
            LOGGER_ERROR("Error while starting video RTP session!\n");
            goto error;
        }
        call->crtps[video_index]->cs = call->cs;
    }
    call->active = 1;
    pthread_mutex_unlock(call->mutex);
    return av_ErrorNone;
error:
    rtp_kill(call->crtps[audio_index], av->messenger);
    call->crtps[audio_index] = NULL;
    rtp_kill(call->crtps[video_index], av->messenger);
    call->crtps[video_index] = NULL;
    cs_kill(call->cs);
    call->cs = NULL;
    call->active = 0;
    pthread_mutex_destroy(call->mutex_encoding_audio);
    pthread_mutex_destroy(call->mutex_encoding_video);
    pthread_mutex_destroy(call->mutex_do);
    pthread_mutex_unlock(call->mutex);
    return av_ErrorCreatingRtpSessions;
}
int toxav_prepare_video_frame (ToxAv * av, int32_t call_index, uint8_t * dest, int dest_max, vpx_image_t * input)
Encode video frame.
Definition at line 446 of file toxav.c.
References _ToxAvCall::active, av_ErrorEncodingVideo, av_ErrorInvalidState, av_ErrorNoCall, av_ErrorPacketTooLarge, av_ErrorSettingVideoResolution, CALL_INVALID_INDEX, _ToxAv::calls, _CSSession::capabilities, _ToxAvCall::cs, cs_set_video_encoder_resolution(), cs_VideoEncoding, _CSSession::frame_counter, LOGGER_ERROR, LOGGER_WARNING, _MSISession::max_calls, MAX_ENCODE_TIME_US, _ToxAv::msi_session, _ToxAvCall::mutex, _ToxAvCall::mutex_encoding_video, and _CSSession::v_encoder.
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls)) {
        LOGGER_WARNING("Invalid call index: %d", call_index);
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (!call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Action on inactive call: %d", call_index);
        return av_ErrorInvalidState;
    }
    if (!(call->cs->capabilities & cs_VideoEncoding)) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Call doesn't support encoding video: %d", call_index);
        return av_ErrorInvalidState;
    }
    if (cs_set_video_encoder_resolution(call->cs, input->w, input->h) < 0)
       {
        pthread_mutex_unlock(call->mutex);
        return av_ErrorSettingVideoResolution;
    }
    pthread_mutex_lock(call->mutex_encoding_video);
    pthread_mutex_unlock(call->mutex);
    int rc = vpx_codec_encode(&call->cs->v_encoder, input, call->cs->
      frame_counter, 1, 0, MAX_ENCODE_TIME_US);
    if (rc != VPX_CODEC_OK) {
        LOGGER_ERROR("Could not encode video frame: %s\n", vpx_codec_err_to_string(rc));
        pthread_mutex_unlock(call->mutex_encoding_video);
        return av_ErrorEncodingVideo;
    }
    ++call->cs->frame_counter;
    vpx_codec_iter_t iter = NULL;
    const vpx_codec_cx_pkt_t *pkt;
    int copied = 0;
    while ((pkt = vpx_codec_get_cx_data(&call->cs->v_encoder, &iter))) {
        if (pkt->kind == VPX_CODEC_CX_FRAME_PKT) {
            if (copied + pkt->data.frame.sz > dest_max) {
                pthread_mutex_unlock(call->mutex_encoding_video);
                return av_ErrorPacketTooLarge;
            }
            memcpy(dest + copied, pkt->data.frame.buf, pkt->data.frame.sz);
            copied += pkt->data.frame.sz;
        }
    }
    pthread_mutex_unlock(call->mutex_encoding_video);
    return copied;
}
void toxav_register_audio_callback (ToxAv * av, ToxAvAudioCallback cb, void * userdata)
Register callback for audio data.
Definition at line 214 of file toxav.c.
Referenced by register_callbacks().
{
    av->acb.first = cb;
    av->acb.second = userdata;
}
void toxav_register_callstate_callback (ToxAv * av, ToxAVCallback cb, ToxAvCallbackID id, void * userdata)
Register callback for call state.
Definition at line 209 of file toxav.c.
References msi_register_callback(), and _ToxAv::msi_session.
Referenced by register_callbacks().
{
    msi_register_callback(av->msi_session, (
      MSICallbackType)cb, (MSICallbackID) id, userdata);
}
void toxav_register_video_callback (ToxAv * av, ToxAvVideoCallback cb, void * userdata)
Register callback for video data.
Definition at line 220 of file toxav.c.
Referenced by register_callbacks().
{
    av->vcb.first = cb;
    av->vcb.second = userdata;
}
int toxav_reject (ToxAv * av, int32_t call_index, const char * reason)
Reject incoming call.
Definition at line 245 of file toxav.c.
References msi_reject(), and _ToxAv::msi_session.
Referenced by START_TEST().
{
    return msi_reject(av->msi_session, call_index, reason);
}
int toxav_send_audio (ToxAv * av, int32_t call_index, const uint8_t * frame, unsigned int size)
Send encoded audio frame.
Definition at line 565 of file toxav.c.
References _ToxAvCall::active, av_ErrorInvalidState, av_ErrorNoCall, av_TypeAudio, CALL_INVALID_INDEX, _ToxAv::calls, LOGGER_WARNING, _MSISession::max_calls, _ToxAv::msi_session, _ToxAvCall::mutex, and toxav_send_rtp_payload().
Referenced by in_thread_call(), and START_TEST().
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls)) {
        LOGGER_WARNING("Action on nonexisting call: %d", call_index);
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (!call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Action on inactive call: %d", call_index);
        return av_ErrorInvalidState;
    }
    int rc = toxav_send_rtp_payload(av, call, av_TypeAudio,
      data, size);
    pthread_mutex_unlock(call->mutex);
    return rc;
}
static int toxav_send_rtp_payload (ToxAv * av, ToxAvCall * call, ToxAvCallType type, const uint8_t * payload, unsigned int length) [static]
Definition at line 412 of file toxav.c.
References audio_index, av_ErrorNone, av_ErrorNoRtpSession, av_ErrorSendingPayload, av_TypeAudio, _ToxAvCall::crtps, _ToxAvCall::cs, cs_get_split_video_frame(), cs_split_video_payload(), i, _ToxAv::messenger, rtp_send_msg(), and video_index.
Referenced by toxav_send_audio(), and toxav_send_video().
{
    if (call->crtps[type - av_TypeAudio]) {
        /* Audio */
        if (type == av_TypeAudio)
            return rtp_send_msg(call->crtps[audio_index], av->
      messenger, payload, length);
        /* Video */
        int parts = cs_split_video_payload(call->cs, payload, length);
        if (parts < 0) return parts;
        uint16_t part_size;
        const uint8_t *iter;
        int i;
        for (i = 0; i < parts; i++) {
            iter = cs_get_split_video_frame(call->cs, &part_size);
            if (rtp_send_msg(call->crtps[video_index], av->
      messenger, iter, part_size) < 0)
                return av_ErrorSendingPayload;
        }
        return av_ErrorNone;
    } else return av_ErrorNoRtpSession;
}
int toxav_send_video (ToxAv * av, int32_t call_index, const uint8_t * frame, unsigned int frame_size)
Definition at line 507 of file toxav.c.
References _ToxAvCall::active, av_ErrorInvalidState, av_ErrorNoCall, av_TypeVideo, CALL_INVALID_INDEX, _ToxAv::calls, LOGGER_WARNING, _MSISession::max_calls, _ToxAv::msi_session, _ToxAvCall::mutex, and toxav_send_rtp_payload().
{
    if (CALL_INVALID_INDEX(call_index, av->msi_session->
      max_calls)) {
        LOGGER_WARNING("Invalid call index: %d", call_index);
        return av_ErrorNoCall;
    }
    ToxAvCall *call = &av->calls[call_index];
    pthread_mutex_lock(call->mutex);
    if (!call->active) {
        pthread_mutex_unlock(call->mutex);
        LOGGER_WARNING("Action on inactive call: %d", call_index);
        return av_ErrorInvalidState;
    }
    int rc = toxav_send_rtp_payload(av, call, av_TypeVideo, frame,
      frame_size);
    pthread_mutex_unlock(call->mutex);
    return rc;
}
int toxav_stop_call (ToxAv * av, int32_t call_index)
Terminate transmission. Note that transmission will be terminated without informing remote peer. Usually called when we can't inform peer.
Definition at line 260 of file toxav.c.
References _ToxAv::msi_session, and msi_stopcall().
{
    return msi_stopcall(av->msi_session, call_index);
}
static const ToxAvCSettings* toxavcsettings_cast (const MSICSettings * from) [static]
Definition at line 95 of file toxav.c.
Referenced by toxav_get_peer_csettings(), and toxav_prepare_transmission().
{
    assert(sizeof(MSICSettings) == sizeof(ToxAvCSettings));
    return (const ToxAvCSettings *) from;
}
Variable Documentation
const uint8_t audio_index = 0 [static]
Definition at line 62 of file toxav.c.
Referenced by toxav_kill(), toxav_kill_transmission(), toxav_prepare_transmission(), and toxav_send_rtp_payload().
const ToxAvCSettings av_DefaultSettings
Initial value:
= {
    av_TypeAudio,
    500,
    1280,
    720,
    32000,
    20,
    48000,
    1
}
Definition at line 48 of file toxav.c.
Referenced by in_thread_call(), and START_TEST().
const uint32_t jbuf_capacity = 6 [static]
Definition at line 61 of file toxav.c.
Referenced by toxav_prepare_transmission().
const uint8_t video_index = 1 [static]
Definition at line 62 of file toxav.c.
Referenced by toxav_kill(), toxav_kill_transmission(), toxav_prepare_transmission(), and toxav_send_rtp_payload().