toxdns/toxdns.c File Reference
#include `../toxcore/Messenger.h`
*
#include `../toxcore/logger.h`
*
#include `toxdns.h`
*
Data Structures
struct DNS_Object
Macros
#define _encode(a, b, c)
#define DOT_INTERVAL (6 * 5)
Functions
static void dns_new_temp_keys (DNS_Object *d)
void * tox_dns3_new (uint8_t *server_public_key)
void tox_dns3_kill (void *dns3_object)
int tox_generate_dns3_string (void *dns3_object, uint8_t *string, uint16_t string_max_len, uint32_t *request_id, uint8_t *name, uint8_t name_len)
static int decode (uint8_t *dest, uint8_t *src)
int tox_decrypt_dns3_TXT (void *dns3_object, uint8_t *tox_id, uint8_t *id_record, uint32_t id_record_len, uint32_t request_id)
Variables
static const char base32 [32] = {`abcdefghijklmnopqrstuvwxyz012345`}
Macro Definition Documentation
#define _encode(a, b, c)
Value:
{ \
uint8_t i = 0; \
    while(i != c) { \
        *a++ = base32[((b[0] >> bits) | (b[1] << (8 - bits))) & 0x1F]; \
        bits += 5; \
        if(bits >= 8) { \
            bits -= 8; \
            b++; \
            i++; \
        } \
    } \
} \
Definition at line 34 of file toxdns.c.
Referenced by tox_generate_dns3_string().
#define DOT_INTERVAL (6 * 5)
Referenced by tox_generate_dns3_string().
Function Documentation
static int decode (uint8_t * dest, uint8_t * src) [static]
Definition at line 155 of file toxdns.c.
Referenced by tox_decrypt_dns3_TXT().
{
    uint8_t *p = src, *op = dest, bits = 0;
    *op = 0;
    while (*p) {
        uint8_t ch = *p++;
        if ('A' <= ch && ch <= 'Z') {
            ch = ch - 'A';
        } else if ('a' <= ch && ch <= 'z') {
            ch = ch - 'a';
        } else if ('0' <= ch && ch <= '5') {
            ch = ch - '0' + 26;
        } else {
            return - 1;
        }
        *op |= (ch << bits);
        bits += 5;
        if (bits >= 8) {
            bits -= 8;
            ++op;
            *op = (ch >> (5 - bits));
        }
    }
    return op - dest;
}
static void dns_new_temp_keys (DNS_Object * d) [static]
Definition at line 57 of file toxdns.c.
References encrypt_precompute(), DNS_Object::nonce, DNS_Object::nonce_start, random_int(), DNS_Object::server_public_key, DNS_Object::shared_key, DNS_Object::temp_pk, and DNS_Object::temp_sk.
Referenced by tox_dns3_new(), and tox_generate_dns3_string().
{
    d->nonce = d->nonce_start = random_int();
    crypto_box_keypair(d->temp_pk, d->temp_sk);
    encrypt_precompute(d->server_public_key, d->
      temp_sk, d->shared_key);
}
int tox_decrypt_dns3_TXT (void * dns3_object, uint8_t * tox_id, uint8_t * id_record, uint32_t id_record_len, uint32_t request_id)
Definition at line 198 of file toxdns.c.
References make-funny-savefile::data, decode(), decrypt_data_symmetric(), FRIEND_ADDRESS_SIZE, nonce, and DNS_Object::shared_key.
Referenced by main().
{
    DNS_Object *d = dns3_object;
    if (id_record_len != 87)
        return -1;
    /*if (id_record_len > 255 || id_record_len <= (sizeof(uint32_t) + crypto_box_MACBYTES))
        return -1;*/
    uint8_t id_record_null[id_record_len + 1];
    memcpy(id_record_null, id_record, id_record_len);
    id_record_null[id_record_len] = 0;
    uint8_t data[id_record_len];
    int length = decode(data, id_record_null);
    if (length == -1)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES] = {0};
    memcpy(nonce, &request_id, sizeof(uint32_t));
    nonce[sizeof(uint32_t)] = 1;
    int len = decrypt_data_symmetric(d->shared_key, nonce, data, length,
      tox_id);
    if (len != FRIEND_ADDRESS_SIZE)
        return -1;
    return 0;
}
void tox_dns3_kill (void * dns3_object)
Definition at line 83 of file toxdns.c.
{
    memset(dns3_object, 0, sizeof(DNS_Object));
    free(dns3_object);
}
void* tox_dns3_new (uint8_t * server_public_key)
Definition at line 69 of file toxdns.c.
References dns_new_temp_keys(), and DNS_Object::server_public_key.
Referenced by main().
{
    DNS_Object *d = malloc(sizeof(DNS_Object));
    if (d == NULL)
        return NULL;
    memcpy(d->server_public_key, server_public_key, crypto_box_PUBLICKEYBYTES);
    dns_new_temp_keys(d);
    return d;
}
int tox_generate_dns3_string (void * dns3_object, uint8_t * string, uint16_t string_max_len, uint32_t * request_id, uint8_t * name, uint8_t name_len)
Definition at line 101 of file toxdns.c.
References _encode, dns_new_temp_keys(), DOT_INTERVAL, encrypt_data_symmetric(), i, LOGGER_ERROR, nonce, DNS_Object::nonce, DNS_Object::nonce_start, DNS_Object::shared_key, and DNS_Object::temp_pk.
Referenced by main().
{
#define DOT_INTERVAL (6 * 5)
    int base = (sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + name_len + crypto_box_MACBYTES);
    int end_len = ((base * 8) / 5) + (base / DOT_INTERVAL) + !!(base % 5);
    end_len -= !(base % DOT_INTERVAL);
    if (end_len > string_max_len)
        return -1;
    DNS_Object *d = dns3_object;
    uint8_t buffer[1024];
    uint8_t nonce[crypto_box_NONCEBYTES] = {0};
    memcpy(nonce, &d->nonce, sizeof(uint32_t));
    memcpy(buffer, &d->nonce, sizeof(uint32_t));
    memcpy(buffer + sizeof(uint32_t), d->temp_pk, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data_symmetric(d->shared_key, nonce, name, name_len,
                                     buffer + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES);
    if (len == -1)
        return -1;
    int total_len = len + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES;
    uint8_t *buff = buffer, *old_str = string;
    buffer[total_len] = 0;
    uint8_t bits = 0;
    int i;
    for (i = !(total_len % DOT_INTERVAL); i < (total_len /
      DOT_INTERVAL); ++i) {
        _encode(string, buff, DOT_INTERVAL);
        *string = '.';
        ++string;
    }
    int left = total_len - (buff - buffer);
    _encode(string, buff, left);
#undef DOT_INTERVAL
    *request_id = d->nonce;
    ++d->nonce;
    if (d->nonce == d->nonce_start) {
        dns_new_temp_keys(d);
    }
    if (end_len != string - old_str) {
        LOGGER_ERROR("tox_generate_dns3_string Fail, %u != %lu\n", end_len, string - old_str);
        return -1;
    }
    return string - old_str;
}
Variable Documentation
const char base32[32] = {`abcdefghijklmnopqrstuvwxyz012345`} [static]
Definition at line 32 of file toxdns.c.