toxcore/crypto_core.h File Reference
#include `network.h`
*
#include <sodium.h>
*
Macros
#define crypto_box_KEYBYTES (crypto_box_BEFORENMBYTES)
#define MAX_CRYPTO_REQUEST_SIZE 1024
#define CRYPTO_PACKET_FRIEND_REQ 32 /* Friend request crypto packet ID. */
#define CRYPTO_PACKET_HARDENING 48 /* Hardening crypto packet ID. */
#define CRYPTO_PACKET_DHTPK 156
#define CRYPTO_PACKET_NAT_PING 254 /* NAT ping crypto packet ID. */
Functions
int public_key_cmp (const uint8_t *pk1, const uint8_t *pk2)
uint32_t random_int (void)
uint64_t random_64b (void)
int public_key_valid (const uint8_t *public_key)
int encrypt_data (const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *nonce, const uint8_t *plain, uint32_t length, uint8_t *encrypted)
int decrypt_data (const uint8_t *public_key, const uint8_t *secret_key, const uint8_t *nonce, const uint8_t *encrypted, uint32_t length, uint8_t *plain)
void encrypt_precompute (const uint8_t *public_key, const uint8_t *secret_key, uint8_t *enc_key)
int encrypt_data_symmetric (const uint8_t *secret_key, const uint8_t *nonce, const uint8_t *plain, uint32_t length, uint8_t *encrypted)
int decrypt_data_symmetric (const uint8_t *secret_key, const uint8_t *nonce, const uint8_t *encrypted, uint32_t length, uint8_t *plain)
void increment_nonce (uint8_t *nonce)
void increment_nonce_number (uint8_t *nonce, uint32_t num)
void random_nonce (uint8_t *nonce)
void new_symmetric_key (uint8_t *key)
void new_nonce (uint8_t *nonce)
int create_request (const uint8_t *send_public_key, const uint8_t *send_secret_key, uint8_t *packet, const uint8_t *recv_public_key, const uint8_t *data, uint32_t length, uint8_t request_id)
int handle_request (const uint8_t *self_public_key, const uint8_t *self_secret_key, uint8_t *public_key, uint8_t *data, uint8_t *request_id, const uint8_t *packet, uint16_t length)
Macro Definition Documentation
#define crypto_box_KEYBYTES (crypto_box_BEFORENMBYTES)
Definition at line 42 of file crypto_core.h.
Referenced by generate_ping_id(), new_symmetric_key(), START_TEST(), and tox_derive_key_with_salt().
#define CRYPTO_PACKET_DHTPK 156
Definition at line 126 of file crypto_core.h.
Referenced by kill_onion_client(), new_onion_client(), and send_dht_dhtpk().
#define CRYPTO_PACKET_FRIEND_REQ 32 /* Friend request crypto packet ID. */
Definition at line 124 of file crypto_core.h.
Referenced by send_friend_request_packet(), and set_friend_request_callback().
#define CRYPTO_PACKET_HARDENING 48 /* Hardening crypto packet ID. */
Definition at line 125 of file crypto_core.h.
Referenced by kill_DHT(), new_DHT(), send_hardening_getnode_res(), and send_hardening_req().
#define CRYPTO_PACKET_NAT_PING 254 /* NAT ping crypto packet ID. */
Definition at line 127 of file crypto_core.h.
Referenced by kill_DHT(), new_DHT(), and send_NATping().
#define MAX_CRYPTO_REQUEST_SIZE 1024
Definition at line 122 of file crypto_core.h.
Referenced by create_request(), cryptopacket_handle(), handle_request(), send_dht_dhtpk(), send_hardening_getnode_res(), send_hardening_req(), and send_NATping().
Function Documentation
int create_request (const uint8_t * send_public_key, const uint8_t * send_secret_key, uint8_t * packet, const uint8_t * recv_public_key, const uint8_t * data, uint32_t length, uint8_t request_id)
Definition at line 203 of file crypto_core.c.
References encrypt_data(), MAX_CRYPTO_REQUEST_SIZE, NET_PACKET_CRYPTO, new_nonce(), and nonce.
Referenced by send_dht_dhtpk(), send_hardening_getnode_res(), send_hardening_req(), and send_NATping().
{
    if (MAX_CRYPTO_REQUEST_SIZE < length + 1 + crypto_box_PUBLICKEYBYTES * 2 +
      crypto_box_NONCEBYTES + 1 +
            crypto_box_MACBYTES)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES];
    uint8_t temp[MAX_CRYPTO_REQUEST_SIZE];
    memcpy(temp + 1, data, length);
    temp[0] = request_id;
    new_nonce(nonce);
    int len = encrypt_data(recv_public_key, send_secret_key, nonce, temp, length + 1,
                           1 + crypto_box_PUBLICKEYBYTES * 2 + crypto_box_NONCEBYTES + packet);
    if (len == -1)
        return -1;
    packet[0] = NET_PACKET_CRYPTO;
    memcpy(packet + 1, recv_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES, send_public_key, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + 1 + crypto_box_PUBLICKEYBYTES * 2, nonce, crypto_box_NONCEBYTES);
    return len + 1 + crypto_box_PUBLICKEYBYTES * 2 + crypto_box_NONCEBYTES;
}
int decrypt_data (const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * nonce, const uint8_t * encrypted, uint32_t length, uint8_t * plain)
Definition at line 131 of file crypto_core.c.
References decrypt_data_symmetric(), and encrypt_precompute().
Referenced by handle_announce_response(), handle_crypto_handshake(), handle_data_response(), handle_dht_dhtpk(), handle_request(), handle_test_3(), handle_test_4(), new_TCP_con(), and START_TEST().
{
    uint8_t k[crypto_box_BEFORENMBYTES];
    encrypt_precompute(public_key, secret_key, k);
    return decrypt_data_symmetric(k, nonce, encrypted, length, plain);
}
int decrypt_data_symmetric (const uint8_t * secret_key, const uint8_t * nonce, const uint8_t * encrypted, uint32_t length, uint8_t * plain)
Definition at line 104 of file crypto_core.c.
Referenced by decrypt_data(), handle_announce_request(), handle_cookie_request(), handle_cookie_response(), handle_data_packet(), handle_getnodes(), handle_handshake(), handle_ping_request(), handle_ping_response(), handle_recv_1(), handle_recv_2(), handle_recv_3(), handle_send_1(), handle_send_2(), handle_send_initial(), handle_sendnodes_core(), handle_TCP_handshake(), open_cookie(), read_packet_sec_TCP(), read_packet_TCP_secure_connection(), START_TEST(), tox_decrypt_dns3_TXT(), and tox_pass_key_decrypt().
{
    if (length <= crypto_box_BOXZEROBYTES)
        return -1;
    uint8_t temp_plain[length + crypto_box_ZEROBYTES];
    uint8_t temp_encrypted[length + crypto_box_BOXZEROBYTES];
    memset(temp_encrypted, 0, crypto_box_BOXZEROBYTES);
    memcpy(temp_encrypted + crypto_box_BOXZEROBYTES, encrypted, length); // Pad the message with 16 0
       bytes.
    if (crypto_box_open_afternm(temp_plain, temp_encrypted, length + crypto_box_BOXZEROBYTES,
      nonce, secret_key) != 0)
        return -1;
    memcpy(plain, temp_plain + crypto_box_ZEROBYTES, length - crypto_box_MACBYTES);
    return length - crypto_box_MACBYTES;
}
int encrypt_data (const uint8_t * public_key, const uint8_t * secret_key, const uint8_t * nonce, const uint8_t * plain, uint32_t length, uint8_t * encrypted)
Definition at line 123 of file crypto_core.c.
References encrypt_data_symmetric(), and encrypt_precompute().
Referenced by create_announce_request(), create_crypto_handshake(), create_data_request(), create_request(), new_TCP_con(), send_dht_dhtpk(), send_onion_data(), and START_TEST().
{
    uint8_t k[crypto_box_BEFORENMBYTES];
    encrypt_precompute(public_key, secret_key, k);
    return encrypt_data_symmetric(k, nonce, plain, length, encrypted);
}
int encrypt_data_symmetric (const uint8_t * secret_key, const uint8_t * nonce, const uint8_t * plain, uint32_t length, uint8_t * encrypted)
Definition at line 84 of file crypto_core.c.
Referenced by create_cookie(), create_cookie_request(), create_cookie_response(), create_onion_packet(), create_onion_packet_tcp(), encrypt_data(), generate_handshake(), getnodes(), handle_announce_request(), handle_send_1(), handle_send_2(), handle_TCP_handshake(), onion_send_1(), send_data_packet(), send_ping_request(), send_ping_response(), sendnodes_ipv6(), START_TEST(), tox_generate_dns3_string(), tox_pass_key_encrypt(), and write_packet_TCP_secure_connection().
{
    if (length == 0)
        return -1;
    uint8_t temp_plain[length + crypto_box_ZEROBYTES];
    uint8_t temp_encrypted[length + crypto_box_MACBYTES + crypto_box_BOXZEROBYTES];
    memset(temp_plain, 0, crypto_box_ZEROBYTES);
    memcpy(temp_plain + crypto_box_ZEROBYTES, plain, length); // Pad the message with 32 0 bytes.
    if (crypto_box_afternm(temp_encrypted, temp_plain, length + crypto_box_ZEROBYTES,
      nonce, secret_key) != 0)
        return -1;
    /* Unpad the encrypted message. */
    memcpy(encrypted, temp_encrypted + crypto_box_BOXZEROBYTES, length + crypto_box_MACBYTES);
    return length + crypto_box_MACBYTES;
}
void encrypt_precompute (const uint8_t * public_key, const uint8_t * secret_key, uint8_t * enc_key)
Definition at line 79 of file crypto_core.c.
Referenced by accept_crypto_connection(), create_onion_path(), decrypt_data(), dns_new_temp_keys(), encrypt_data(), get_shared_key(), handle_handshake(), handle_new_connection_handshake(), handle_packet_connection(), handle_TCP_handshake(), new_TCP_con(), new_TCP_connection(), and START_TEST().
{
    crypto_box_beforenm(enc_key, public_key, secret_key);
}
int handle_request (const uint8_t * self_public_key, const uint8_t * self_secret_key, uint8_t * public_key, uint8_t * data, uint8_t * request_id, const uint8_t * packet, uint16_t length)
Definition at line 235 of file crypto_core.c.
References decrypt_data(), MAX_CRYPTO_REQUEST_SIZE, and nonce.
Referenced by cryptopacket_handle().
{
    if (length <= crypto_box_PUBLICKEYBYTES * 2 + crypto_box_NONCEBYTES + 1 + crypto_box_MACBYTES ||
            length > MAX_CRYPTO_REQUEST_SIZE)
        return -1;
    if (memcmp(packet + 1, self_public_key, crypto_box_PUBLICKEYBYTES) != 0)
        return -1;
    memcpy(public_key, packet + 1 + crypto_box_PUBLICKEYBYTES, crypto_box_PUBLICKEYBYTES);
    uint8_t nonce[crypto_box_NONCEBYTES];
    uint8_t temp[MAX_CRYPTO_REQUEST_SIZE];
    memcpy(nonce, packet + 1 + crypto_box_PUBLICKEYBYTES * 2, crypto_box_NONCEBYTES);
    int len1 = decrypt_data(public_key, self_secret_key, nonce,
                            packet + 1 + crypto_box_PUBLICKEYBYTES * 2 + crypto_box_NONCEBYTES,
                            length - (crypto_box_PUBLICKEYBYTES * 2 + crypto_box_NONCEBYTES + 1), temp);
    if (len1 == -1 || len1 == 0)
        return -1;
    request_id[0] = temp[0];
    --len1;
    memcpy(data, temp + 1, len1);
    return len1;
}
void increment_nonce (uint8_t * nonce)
Definition at line 141 of file crypto_core.c.
References i.
Referenced by read_packet_sec_TCP(), read_packet_TCP_secure_connection(), send_data_packet(), START_TEST(), and write_packet_TCP_secure_connection().
{
    uint32_t i;
    for (i = crypto_box_NONCEBYTES; i != 0; --i) {
        ++nonce[i - 1];
        if (nonce[i - 1] != 0)
            break;
    }
}
void increment_nonce_number (uint8_t * nonce, uint32_t num)
Definition at line 153 of file crypto_core.c.
References i.
Referenced by handle_data_packet().
{
    uint32_t num1, num2;
    memcpy(&num1, nonce + (crypto_box_NONCEBYTES - sizeof(num1)), sizeof(num1));
    num1 = ntohl(num1);
    num2 = num + num1;
    if (num2 < num1) {
        uint32_t i;
        for (i = crypto_box_NONCEBYTES - sizeof(num1); i != 0; --i) {
            ++nonce[i - 1];
            if (nonce[i - 1] != 0)
                break;
        }
    }
    num2 = htonl(num2);
    memcpy(nonce + (crypto_box_NONCEBYTES - sizeof(num2)), &num2, sizeof(num2));
}
void new_nonce (uint8_t * nonce)
Definition at line 188 of file crypto_core.c.
References random_nonce().
Referenced by create_cookie(), create_cookie_request(), create_cookie_response(), create_crypto_handshake(), create_request(), generate_handshake(), getnodes(), handle_send_1(), handle_send_2(), handle_TCP_handshake(), new_TCP_con(), onion_send_1(), send_dht_dhtpk(), send_ping_request(), send_ping_response(), sendnodes_ipv6(), and START_TEST().
{
    random_nonce(nonce);
}
void new_symmetric_key (uint8_t * key)
Definition at line 182 of file crypto_core.c.
References crypto_box_KEYBYTES.
Referenced by add_groupchat(), change_symmetric_key(), new_DHT(), new_net_crypto(), new_onion(), new_onion_announce(), new_onion_client(), START_TEST(), and tox_file_send().
{
    randombytes(key, crypto_box_KEYBYTES);
}
int public_key_cmp (const uint8_t * pk1, const uint8_t * pk2)
Definition at line 39 of file crypto_core.c.
Referenced by handle_crypto_handshake(), handle_new_connection_handshake(), and handle_packet_connection().
{
    return crypto_verify_32(pk1, pk2);
}
int public_key_valid (const uint8_t * public_key)
Definition at line 66 of file crypto_core.c.
Referenced by m_addfriend(), and m_addfriend_norequest().
{
    if (public_key[31] >= 128) /* Last bit of key is always zero. */
        return 0;
    return 1;
}
uint64_t random_64b (void)
Definition at line 53 of file crypto_core.c.
Referenced by DHT_addfriend(), do_confirmed_TCP(), do_TCP_confirmed(), handle_NATping(), new_crypto_connection(), and ping_array_add().
{
    uint64_t randnum;
    randombytes((uint8_t *)&randnum, sizeof(randnum));
    return randnum;
}
uint32_t random_int (void)
Definition at line 46 of file crypto_core.c.
Referenced by dns_new_temp_keys(), logger_new(), new_messenger(), rtp_new(), and t_randomstr().
{
    uint32_t randnum;
    randombytes((uint8_t *)&randnum , sizeof(randnum));
    return randnum;
}
void random_nonce (uint8_t * nonce)
Definition at line 176 of file crypto_core.c.
Referenced by accept_crypto_connection(), create_announce_request(), create_onion_packet(), create_onion_packet_tcp(), generate_handshake(), handle_announce_request(), handle_TCP_handshake(), new_crypto_connection(), new_nonce(), new_TCP_con(), send_onion_data(), START_TEST(), and tox_pass_key_encrypt().
{
    randombytes(nonce, crypto_box_NONCEBYTES);
}