toxcore/group.c File Reference
#include `group.h`
*
#include `util.h`
*
Macros
#define INVITE_PACKET_SIZE (1 + sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
#define INVITE_ID 0
#define INVITE_RESPONSE_PACKET_SIZE (1 + sizeof(uint16_t) * 2 + GROUP_IDENTIFIER_LENGTH)
#define INVITE_RESPONSE_ID 1
#define GROUP_MESSAGE_PING_ID 0
#define GROUP_MESSAGE_NEW_PEER_ID 16
#define GROUP_MESSAGE_NEW_PEER_LENGTH (sizeof(uint16_t) + crypto_box_PUBLICKEYBYTES * 2)
#define GROUP_MESSAGE_KILL_PEER_ID 17
#define GROUP_MESSAGE_KILL_PEER_LENGTH (sizeof(uint16_t))
#define GROUP_MESSAGE_NAME_ID 48
#define GROUP_MESSAGE_TITLE_ID 49
#define ONLINE_PACKET_DATA_SIZE (sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
#define PEER_KILL_ID 1
#define PEER_QUERY_ID 8
#define PEER_RESPONSE_ID 9
#define PEER_TITLE_ID 10
#define MIN_MESSAGE_PACKET_LEN (sizeof(uint16_t) * 2 + sizeof(uint32_t) + 1)
#define MAX_GROUP_MESSAGE_DATA_LEN (MAX_CRYPTO_DATA_SIZE - (1 + MIN_MESSAGE_PACKET_LEN))
#define GROUP_PING_INTERVAL 20
Enumerations
enum { GROUPCHAT_CLOSEST_NONE,
GROUPCHAT_CLOSEST_ADDED,
GROUPCHAT_CLOSEST_REMOVED
 }
Functions
static uint8_t groupnumber_not_valid (const Group_Chats *g_c, int groupnumber)
static int realloc_groupchats (Group_Chats *g_c, uint32_t num)
static int create_group_chat (Group_Chats *g_c)
static int wipe_group_chat (Group_Chats *g_c, int groupnumber)
static Group_c * get_group_c (const Group_Chats *g_c, int groupnumber)
static int peer_in_chat (const Group_c *chat, const uint8_t *real_pk)
static int get_group_num (const Group_Chats *g_c, const uint8_t *identifier)
static int get_peer_index (Group_c *g, uint16_t peer_number)
static uint64_t calculate_comp_value (const uint8_t *pk1, const uint8_t *pk2)
static int friend_in_close (Group_c *g, int friendcon_id)
static int add_conn_to_groupchat (Group_Chats *g_c, int friendcon_id, int groupnumber, uint8_t closest, uint8_t lock)
static int add_to_closest (Group_Chats *g_c, int groupnumber, const uint8_t *real_pk, const uint8_t *temp_pk)
static unsigned int pk_in_closest_peers (Group_c *g, uint8_t *real_pk)
static int send_packet_online (Friend_Connections *fr_c, int friendcon_id, uint16_t group_num, uint8_t *identifier)
static int connect_to_closest (Group_Chats *g_c, int groupnumber)
static int addpeer (Group_Chats *g_c, int groupnumber, const uint8_t *real_pk, const uint8_t *temp_pk, uint16_t peer_number)
static int remove_close_conn (Group_Chats *g_c, int groupnumber, int friendcon_id)
static int delpeer (Group_Chats *g_c, int groupnumber, int peer_index)
static int setnick (Group_Chats *g_c, int groupnumber, int peer_index, const uint8_t *nick, uint16_t nick_len)
static int settitle (Group_Chats *g_c, int groupnumber, int peer_index, const uint8_t *title, uint8_t title_len)
static void set_conns_type_close (Group_Chats *g_c, int groupnumber, int friendcon_id, uint8_t type)
static void set_conns_status_groups (Group_Chats *g_c, int friendcon_id, uint8_t type)
static int handle_status (void *object, int friendcon_id, uint8_t status)
static int handle_packet (void *object, int friendcon_id, uint8_t *data, uint16_t length)
static int handle_lossy (void *object, int friendcon_id, const uint8_t *data, uint16_t length)
int add_groupchat (Group_Chats *g_c, uint8_t type)
static int group_kill_peer_send (const Group_Chats *g_c, int groupnumber, uint16_t peer_num)
int del_groupchat (Group_Chats *g_c, int groupnumber)
int group_peer_pubkey (const Group_Chats *g_c, int groupnumber, int peernumber, uint8_t *pk)
int group_peername (const Group_Chats *g_c, int groupnumber, int peernumber, uint8_t *name)
int group_names (const Group_Chats *g_c, int groupnumber, uint8_t names[][MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
int group_number_peers (const Group_Chats *g_c, int groupnumber)
unsigned int group_peernumber_is_ours (const Group_Chats *g_c, int groupnumber, int peernumber)
int group_get_type (const Group_Chats *g_c, int groupnumber)
static unsigned int send_packet_group_peer (Friend_Connections *fr_c, int friendcon_id, uint8_t packet_id, uint16_t group_num, const uint8_t *data, uint16_t length)
static unsigned int send_lossy_group_peer (Friend_Connections *fr_c, int friendcon_id, uint8_t packet_id, uint16_t group_num, const uint8_t *data, uint16_t length)
int invite_friend (Group_Chats *g_c, int32_t friendnumber, int groupnumber)
static unsigned int send_peer_query (Group_Chats *g_c, int friendcon_id, uint16_t group_num)
int join_groupchat (Group_Chats *g_c, int32_t friendnumber, uint8_t expected_type, const uint8_t *data, uint16_t length)
void g_callback_group_invite (Group_Chats *g_c, void(*function)(Messenger *m, int32_t, uint8_t, const uint8_t *, uint16_t, void *), void *userdata)
void g_callback_group_message (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void g_callback_group_action (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint16_t, void *), void *userdata)
void group_lossy_packet_registerhandler (Group_Chats *g_c, uint8_t byte, int(*function)(void *, int, int, void *, const uint8_t *, uint16_t))
void g_callback_group_namelistchange (Group_Chats *g_c, void(*function)(Messenger *m, int, int, uint8_t, void *), void *userdata)
void g_callback_group_title (Group_Chats *g_c, void(*function)(Messenger *m, int, int, const uint8_t *, uint8_t, void *), void *userdata)
int callback_groupchat_peer_new (const Group_Chats *g_c, int groupnumber, void(*function)(void *, int, int))
int callback_groupchat_peer_delete (Group_Chats *g_c, int groupnumber, void(*function)(void *, int, int, void *))
int callback_groupchat_delete (Group_Chats *g_c, int groupnumber, void(*function)(void *, int))
static unsigned int send_message_group (const Group_Chats *g_c, int groupnumber, uint8_t message_id, const uint8_t *data, uint16_t len)
int group_ping_send (const Group_Chats *g_c, int groupnumber)
int group_new_peer_send (const Group_Chats *g_c, int groupnumber, uint16_t peer_num, const uint8_t *real_pk, uint8_t *temp_pk)
static int group_name_send (const Group_Chats *g_c, int groupnumber, const uint8_t *nick, uint16_t nick_len)
int group_title_send (const Group_Chats *g_c, int groupnumber, const uint8_t *title, uint8_t title_len)
int group_title_get (const Group_Chats *g_c, int groupnumber, uint8_t *title, uint32_t max_length)
static void handle_friend_invite_packet (Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t length)
static unsigned int count_close_connected (Group_c *g)
static unsigned int send_peer_kill (Group_Chats *g_c, int friendcon_id, uint16_t group_num)
static int handle_packet_online (Group_Chats *g_c, int friendcon_id, uint8_t *data, uint16_t length)
static unsigned int send_peers (Group_Chats *g_c, int groupnumber, int friendcon_id, uint16_t group_num)
static int handle_send_peers (Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length)
static void handle_direct_packet (Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length, int close_index)
static unsigned int send_message_all_close (const Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length, int receiver)
static unsigned int send_lossy_all_close (const Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length, int receiver)
int group_message_send (const Group_Chats *g_c, int groupnumber, const uint8_t *message, uint16_t length)
int group_action_send (const Group_Chats *g_c, int groupnumber, const uint8_t *action, uint16_t length)
int send_group_lossy_packet (const Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length)
static void handle_message_packet_group (Group_Chats *g_c, int groupnumber, const uint8_t *data, uint16_t length, int close_index)
static unsigned int lossy_packet_not_received (Group_c *g, int peer_index, uint16_t message_number)
int group_set_object (const Group_Chats *g_c, int groupnumber, void *object)
int group_peer_set_object (const Group_Chats *g_c, int groupnumber, int peernumber, void *object)
void * group_get_object (const Group_Chats *g_c, int groupnumber)
void * group_peer_get_object (const Group_Chats *g_c, int groupnumber, int peernumber)
static int ping_groupchat (Group_Chats *g_c, int groupnumber)
static int groupchat_clear_timedout (Group_Chats *g_c, int groupnumber)
void send_name_all_groups (Group_Chats *g_c)
Group_Chats * new_groupchats (Messenger *m)
void do_groupchats (Group_Chats *g_c)
void kill_groupchats (Group_Chats *g_c)
uint32_t count_chatlist (Group_Chats *g_c)
uint32_t copy_chatlist (Group_Chats *g_c, int32_t *out_list, uint32_t list_size)
Macro Definition Documentation
#define GROUP_MESSAGE_KILL_PEER_ID 17
Definition at line 1145 of file group.c.
Referenced by group_kill_peer_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_KILL_PEER_LENGTH (sizeof(uint16_t))
Definition at line 1146 of file group.c.
Referenced by group_kill_peer_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_NAME_ID 48
Definition at line 1166 of file group.c.
Referenced by group_name_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_NEW_PEER_ID 16
Definition at line 1122 of file group.c.
Referenced by group_new_peer_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_NEW_PEER_LENGTH (sizeof(uint16_t) + crypto_box_PUBLICKEYBYTES * 2)
Definition at line 1123 of file group.c.
Referenced by group_new_peer_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_PING_ID 0
Definition at line 1112 of file group.c.
Referenced by group_ping_send(), and handle_message_packet_group().
#define GROUP_MESSAGE_TITLE_ID 49
Definition at line 1184 of file group.c.
Referenced by group_title_send(), and handle_message_packet_group().
#define GROUP_PING_INTERVAL 20
Definition at line 2165 of file group.c.
Referenced by groupchat_clear_timedout(), and ping_groupchat().
#define INVITE_ID 0
Definition at line 891 of file group.c.
Referenced by handle_friend_invite_packet(), and invite_friend().
#define INVITE_PACKET_SIZE (1 + sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
Definition at line 890 of file group.c.
Referenced by handle_friend_invite_packet(), and invite_friend().
#define INVITE_RESPONSE_ID 1
Definition at line 894 of file group.c.
Referenced by handle_friend_invite_packet(), and join_groupchat().
#define INVITE_RESPONSE_PACKET_SIZE (1 + sizeof(uint16_t) * 2 + GROUP_IDENTIFIER_LENGTH)
Definition at line 893 of file group.c.
Referenced by handle_friend_invite_packet(), and join_groupchat().
#define MAX_GROUP_MESSAGE_DATA_LEN (MAX_CRYPTO_DATA_SIZE - (1 + MIN_MESSAGE_PACKET_LEN))
Definition at line 1710 of file group.c.
Referenced by send_message_group().
#define MIN_MESSAGE_PACKET_LEN (sizeof(uint16_t) * 2 + sizeof(uint32_t) + 1)
Definition at line 1594 of file group.c.
#define ONLINE_PACKET_DATA_SIZE (sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
Definition at line 1357 of file group.c.
Referenced by handle_packet_online(), and send_packet_online().
#define PEER_KILL_ID 1
Definition at line 1421 of file group.c.
Referenced by handle_direct_packet(), and send_peer_kill().
#define PEER_QUERY_ID 8
Definition at line 1422 of file group.c.
Referenced by handle_direct_packet(), and send_peer_query().
#define PEER_RESPONSE_ID 9
Definition at line 1423 of file group.c.
Referenced by handle_direct_packet(), and send_peers().
#define PEER_TITLE_ID 10
Definition at line 1424 of file group.c.
Referenced by handle_direct_packet(), and send_peers().
Enumeration Type Documentation
anonymous enum
Enumerator
GROUPCHAT_CLOSEST_NONE
GROUPCHAT_CLOSEST_ADDED
GROUPCHAT_CLOSEST_REMOVED
Definition at line 205 of file group.c.
     {
    GROUPCHAT_CLOSEST_NONE,
    GROUPCHAT_CLOSEST_ADDED,
    GROUPCHAT_CLOSEST_REMOVED
};
Function Documentation
static int add_conn_to_groupchat (Group_Chats * g_c, int friendcon_id, int groupnumber, uint8_t closest, uint8_t lock) [static]
Definition at line 623 of file group.c.
References Group_c::close, Group_c::closest, Group_Chats::fr_c, Messenger::fr_c, friend_connection_callbacks(), friend_connection_lock(), get_group_c(), GROUPCHAT_CALLBACK_INDEX, GROUPCHAT_CLOSE_CONNECTION, GROUPCHAT_CLOSE_NONE, handle_lossy(), handle_packet(), handle_status(), i, Group_Chats::m, MAX_GROUP_CONNECTIONS, Group_c::number, and Group_c::type.
Referenced by connect_to_closest(), handle_friend_invite_packet(), and join_groupchat().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint16_t i, ind = MAX_GROUP_CONNECTIONS;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE) {
            ind = i;
            continue;
        }
        if (g->close[i].number == (uint32_t)friendcon_id) {
            g->close[i].closest = closest;
            return i; /* Already in list. */
        }
    }
    if (ind == MAX_GROUP_CONNECTIONS)
        return -1;
    if (lock)
        friend_connection_lock(g_c->fr_c, friendcon_id);
    g->close[ind].type = GROUPCHAT_CLOSE_CONNECTION;
    g->close[ind].number = friendcon_id;
    g->close[ind].closest = closest;
    //TODO
    friend_connection_callbacks(g_c->m->fr_c, friendcon_id,
      GROUPCHAT_CALLBACK_INDEX, &handle_status, &
      handle_packet,
                                &handle_lossy, g_c, friendcon_id);
    return ind;
}
int add_groupchat (Group_Chats * g_c, uint8_t type)
Definition at line 667 of file group.c.
References addpeer(), Group_Chats::chats, create_group_chat(), Messenger::dht, GROUPCHAT_STATUS_CONNECTED, Group_c::identifier, Group_Chats::m, Messenger::name, Messenger::name_length, Messenger::net_crypto, new_symmetric_key(), Group_c::number_joined, Group_c::peer_number, Group_c::real_pk, Net_Crypto::self_public_key, DHT::self_public_key, setnick(), and Group_c::status.
Referenced by add_av_groupchat(), and tox_add_groupchat().
{
    int groupnumber = create_group_chat(g_c);
    if (groupnumber == -1)
        return -1;
    Group_c *g = &g_c->chats[groupnumber];
    g->status = GROUPCHAT_STATUS_CONNECTED;
    g->number_joined = -1;
    new_symmetric_key(g->identifier + 1);
    g->identifier[0] = type;
    g->peer_number = 0; /* Founder is peer 0. */
    memcpy(g->real_pk, g_c->m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    int peer_index = addpeer(g_c, groupnumber, g->real_pk, g_c->m->
      dht->self_public_key, 0);
    if (peer_index == -1) {
        return -1;
    }
    setnick(g_c, groupnumber, peer_index, g_c->m->name, g_c->m->
      name_length);
    return groupnumber;
}
static int add_to_closest (Group_Chats * g_c, int groupnumber, const uint8_t * real_pk, const uint8_t * temp_pk) [static]
Definition at line 214 of file group.c.
References calculate_comp_value(), Group_c::changed, Group_c::closest_peers, DESIRED_CLOSE_CONNECTIONS, Group_c::entry, get_group_c(), GROUPCHAT_CLOSEST_ADDED, i, Group_c::real_pk, and Group_c::temp_pk.
Referenced by addpeer(), and connect_to_closest().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if (memcmp(g->real_pk, real_pk, crypto_box_PUBLICKEYBYTES) == 0)
        return -1;
    unsigned int i;
    unsigned int index = DESIRED_CLOSE_CONNECTIONS;
    for (i = 0; i < DESIRED_CLOSE_CONNECTIONS; ++i) {
        if (g->closest_peers[i].entry && memcmp(real_pk, g->
      closest_peers[i].real_pk, crypto_box_PUBLICKEYBYTES) == 0) {
            return 0;
        }
    }
    for (i = 0; i < DESIRED_CLOSE_CONNECTIONS; ++i) {
        if (g->closest_peers[i].entry == 0) {
            index = i;
            break;
        }
    }
    if (index == DESIRED_CLOSE_CONNECTIONS) {
        uint64_t comp_val = calculate_comp_value(g->real_pk, real_pk);
        uint64_t comp_d = 0;
        for (i = 0; i < (DESIRED_CLOSE_CONNECTIONS / 2); ++i) {
            uint64_t comp;
            comp = calculate_comp_value(g->real_pk, g->
      closest_peers[i].real_pk);
            if (comp > comp_val && comp > comp_d) {
                index = i;
                comp_d = comp;
            }
        }
        comp_val = calculate_comp_value(real_pk, g->real_pk);
        for (i = (DESIRED_CLOSE_CONNECTIONS / 2); i < DESIRED_CLOSE_CONNECTIONS; +
      +i) {
            uint64_t comp = calculate_comp_value(g->
      closest_peers[i].real_pk, g->real_pk);
            if (comp > comp_val && comp > comp_d) {
                index = i;
                comp_d = comp;
            }
        }
    }
    if (index == DESIRED_CLOSE_CONNECTIONS) {
        return -1;
    }
    uint8_t old_real_pk[crypto_box_PUBLICKEYBYTES];
    uint8_t old_temp_pk[crypto_box_PUBLICKEYBYTES];
    uint8_t old = 0;
    if (g->closest_peers[index].entry) {
        memcpy(old_real_pk, g->closest_peers[index].real_pk, crypto_box_PUBLICKEYBYTES)
      ;
        memcpy(old_temp_pk, g->closest_peers[index].temp_pk, crypto_box_PUBLICKEYBYTES)
      ;
        old = 1;
    }
    g->closest_peers[index].entry = 1;
    memcpy(g->closest_peers[index].real_pk, real_pk, crypto_box_PUBLICKEYBYTES);
    memcpy(g->closest_peers[index].temp_pk, temp_pk, crypto_box_PUBLICKEYBYTES);
    if (old) {
        add_to_closest(g_c, groupnumber, old_real_pk, old_temp_pk);
    }
    if (!g->changed)
        g->changed = GROUPCHAT_CLOSEST_ADDED;
    return 0;
}
static int addpeer (Group_Chats * g_c, int groupnumber, const uint8_t * real_pk, const uint8_t * temp_pk, uint16_t peer_number) [static]
Definition at line 384 of file group.c.
References add_to_closest(), CHAT_CHANGE_PEER_ADD, get_group_c(), get_peer_index(), Group_c::group, Group_Chats::group_namelistchange_userdata, id_copy(), Group_Peer::last_recv, Group_Chats::m, Group_c::numpeers, Group_c::object, peer_in_chat(), Group_Chats::peer_namelistchange, Group_Peer::peer_number, Group_c::peer_on_join, Group_Peer::real_pk, Group_Peer::temp_pk, and unix_time().
Referenced by add_groupchat(), handle_friend_invite_packet(), handle_message_packet_group(), and handle_send_peers().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    //TODO
    int peer_index = peer_in_chat(g, real_pk);
    if (peer_index != -1) {
        id_copy(g->group[peer_index].temp_pk, temp_pk);
        if (g->group[peer_index].peer_number != peer_number)
            return -1;
        return peer_index;
    }
    peer_index = get_peer_index(g, peer_number);
    if (peer_index != -1)
        return -1;
    Group_Peer *temp;
    temp = realloc(g->group, sizeof(Group_Peer) * (g->numpeers + 1));
    if (temp == NULL)
        return -1;
    memset(&(temp[g->numpeers]), 0, sizeof(Group_Peer));
    g->group = temp;
    id_copy(g->group[g->numpeers].real_pk, real_pk);
    id_copy(g->group[g->numpeers].temp_pk, temp_pk);
    g->group[g->numpeers].peer_number = peer_number;
    g->group[g->numpeers].last_recv = unix_time();
    ++g->numpeers;
    add_to_closest(g_c, groupnumber, real_pk, temp_pk);
    if (g_c->peer_namelistchange)
        g_c->peer_namelistchange(g_c->m, groupnumber, g->
      numpeers - 1, CHAT_CHANGE_PEER_ADD,
                                 g_c->group_namelistchange_userdata);
    if (g->peer_on_join)
        g->peer_on_join(g->object, groupnumber, g->numpeers - 1);
    return (g->numpeers - 1);
}
static uint64_t calculate_comp_value (const uint8_t * pk1, const uint8_t * pk2) [static]
Definition at line 191 of file group.c.
References i.
Referenced by add_to_closest(), and send_lossy_all_close().
{
    uint64_t cmp1 = 0, cmp2 = 0;
    unsigned int i;
    for (i = 0; i < sizeof(uint64_t); ++i) {
        cmp1 = (cmp1 << 8) + (uint64_t)pk1[i];
        cmp2 = (cmp2 << 8) + (uint64_t)pk2[i];
    }
    return (cmp1 - cmp2);
}
int callback_groupchat_delete (Group_Chats * g_c, int groupnumber, void(*)(void *, int) function)
Definition at line 1098 of file group.c.
References get_group_c(), and Group_c::group_on_delete.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->group_on_delete = function;
    return 0;
}
int callback_groupchat_peer_delete (Group_Chats * g_c, int groupnumber, void(*)(void *, int, int, void *) function)
Definition at line 1080 of file group.c.
References get_group_c(), and Group_c::peer_on_leave.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->peer_on_leave = function;
    return 0;
}
int callback_groupchat_peer_new (const Group_Chats * g_c, int groupnumber, void(*)(void *, int, int) function)
Definition at line 1062 of file group.c.
References get_group_c(), and Group_c::peer_on_join.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->peer_on_join = function;
    return 0;
}
static int connect_to_closest (Group_Chats * g_c, int groupnumber) [static]
Definition at line 312 of file group.c.
References add_conn_to_groupchat(), add_to_closest(), Group_c::changed, Group_c::close, Group_c::closest, Group_c::closest_peers, DESIRED_CLOSE_CONNECTIONS, Group_c::entry, Group_Chats::fr_c, friend_con_connected(), FRIENDCONN_STATUS_CONNECTED, get_friendcon_public_keys(), get_group_c(), getfriend_conn_id_pk(), Group_c::group, GROUPCHAT_CLOSE_NONE, GROUPCHAT_CLOSEST_NONE, GROUPCHAT_CLOSEST_REMOVED, i, Group_c::identifier, kill_friend_connection(), MAX_GROUP_CONNECTIONS, new_friend_connection(), Group_c::number, Group_c::numpeers, pk_in_closest_peers(), Group_Peer::real_pk, Group_c::real_pk, send_packet_online(), set_dht_temp_pk(), Group_Peer::temp_pk, Group_c::temp_pk, and Group_c::type.
Referenced by do_groupchats().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if (!g->changed)
        return 0;
    unsigned int i;
    if (g->changed == GROUPCHAT_CLOSEST_REMOVED) {
        for (i = 0; i < g->numpeers; ++i) {
            add_to_closest(g_c, groupnumber, g->group[i].
      real_pk, g->group[i].temp_pk);
        }
    }
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        if (!g->close[i].closest)
            continue;
        uint8_t real_pk[crypto_box_PUBLICKEYBYTES];
        uint8_t dht_temp_pk[crypto_box_PUBLICKEYBYTES];
        get_friendcon_public_keys(real_pk, dht_temp_pk, g_c->
      fr_c, g->close[i].number);
        if (!pk_in_closest_peers(g, real_pk)) {
            g->close[i].type = GROUPCHAT_CLOSE_NONE;
            kill_friend_connection(g_c->fr_c, g->close[i].
      number);
        }
    }
    for (i = 0; i < DESIRED_CLOSE_CONNECTIONS; ++i) {
        if (!g->closest_peers[i].entry)
            continue;
        int friendcon_id = getfriend_conn_id_pk(g_c->fr_c, g->
      closest_peers[i].real_pk);
        uint8_t lock = 1;
        if (friendcon_id == -1) {
            friendcon_id = new_friend_connection(g_c->fr_c, g->
      closest_peers[i].real_pk);
            lock = 0;
            if (friendcon_id == -1) {
                continue;
            }
            set_dht_temp_pk(g_c->fr_c, friendcon_id, g->
      closest_peers[i].temp_pk);
        }
        add_conn_to_groupchat(g_c, friendcon_id, groupnumber, 1, lock);
        if (friend_con_connected(g_c->fr_c, friendcon_id) ==
      FRIENDCONN_STATUS_CONNECTED) {
            send_packet_online(g_c->fr_c, friendcon_id, groupnumber, g->
      identifier);
        }
    }
    g->changed = GROUPCHAT_CLOSEST_NONE;
    return 0;
}
uint32_t copy_chatlist (Group_Chats * g_c, int32_t * out_list, uint32_t list_size)
Definition at line 2298 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, i, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_get_chatlist().
{
    if (!out_list) {
        return 0;
    }
    if (g_c->num_chats == 0) {
        return 0;
    }
    uint32_t i, ret = 0;
    for (i = 0; i < g_c->num_chats; ++i) {
        if (ret >= list_size) {
            break; /* Abandon ship */
        }
        if (g_c->chats[i].status > GROUPCHAT_STATUS_NONE) {
            out_list[ret] = i;
            ret++;
        }
    }
    return ret;
}
uint32_t count_chatlist (Group_Chats * g_c)
Definition at line 2279 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, i, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_count_chatlist().
{
    uint32_t ret = 0;
    uint32_t i;
    for (i = 0; i < g_c->num_chats; i++) {
        if (g_c->chats[i].status != GROUPCHAT_STATUS_NONE) {
            ret++;
        }
    }
    return ret;
}
static unsigned int count_close_connected (Group_c * g) [static]
Definition at line 1344 of file group.c.
References Group_c::close, GROUPCHAT_CLOSE_ONLINE, i, MAX_GROUP_CONNECTIONS, and Group_c::type.
Referenced by handle_packet_online().
{
    unsigned int i, count = 0;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_ONLINE) {
            ++count;
        }
    }
    return count;
}
static int create_group_chat (Group_Chats * g_c) [static]
Definition at line 77 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, i, Group_Chats::num_chats, realloc_groupchats(), and Group_c::status.
Referenced by add_groupchat(), and join_groupchat().
{
    uint32_t i;
    for (i = 0; i < g_c->num_chats; ++i) {
        if (g_c->chats[i].status == GROUPCHAT_STATUS_NONE)
            return i;
    }
    int id = -1;
    if (realloc_groupchats(g_c, g_c->num_chats + 1) == 0) {
        id = g_c->num_chats;
        ++g_c->num_chats;
        memset(&(g_c->chats[id]), 0, sizeof(Group_c));
    }
    return id;
}
int del_groupchat (Group_Chats * g_c, int groupnumber)
Definition at line 699 of file group.c.
References Group_c::close, Group_Chats::fr_c, get_group_c(), Group_c::group, group_kill_peer_send(), Group_c::group_on_delete, GROUPCHAT_CLOSE_NONE, i, kill_friend_connection(), MAX_GROUP_CONNECTIONS, Group_c::number, Group_c::numpeers, Group_Peer::object, Group_c::object, Group_c::peer_number, Group_c::peer_on_leave, Group_c::type, and wipe_group_chat().
Referenced by add_av_groupchat(), join_av_groupchat(), kill_groupchats(), and tox_del_groupchat().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    group_kill_peer_send(g_c, groupnumber, g->peer_number);
    unsigned int i;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        g->close[i].type = GROUPCHAT_CLOSE_NONE;
        kill_friend_connection(g_c->fr_c, g->close[i].
      number);
    }
    for (i = 0; i < g->numpeers; ++i) {
        if (g->peer_on_leave)
            g->peer_on_leave(g->object, groupnumber, i, g->
      group[i].object);
    }
    free(g->group);
    if (g->group_on_delete)
        g->group_on_delete(g->object, groupnumber);
    return wipe_group_chat(g_c, groupnumber);
}
static int delpeer (Group_Chats * g_c, int groupnumber, int peer_index) [static]
Definition at line 467 of file group.c.
References Group_c::changed, CHAT_CHANGE_PEER_DEL, Group_c::closest_peers, DESIRED_CLOSE_CONNECTIONS, Group_c::entry, Group_Chats::fr_c, get_group_c(), getfriend_conn_id_pk(), Group_c::group, Group_Chats::group_namelistchange_userdata, GROUPCHAT_CLOSEST_REMOVED, i, id_equal(), Group_Chats::m, Group_c::numpeers, Group_Peer::object, Group_c::object, Group_Chats::peer_namelistchange, Group_c::peer_on_leave, Group_Peer::real_pk, Group_c::real_pk, and remove_close_conn().
Referenced by groupchat_clear_timedout(), and handle_message_packet_group().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint32_t i;
    for (i = 0; i < DESIRED_CLOSE_CONNECTIONS; ++i) { /* If peer is in
       closest_peers list, remove it. */
        if (g->closest_peers[i].entry && id_equal(g->
      closest_peers[i].real_pk, g->group[peer_index].real_pk)) {
            g->closest_peers[i].entry = 0;
            g->changed = GROUPCHAT_CLOSEST_REMOVED;
            break;
        }
    }
    int friendcon_id = getfriend_conn_id_pk(g_c->fr_c, g->
      group[peer_index].real_pk);
    if (friendcon_id != -1) {
        remove_close_conn(g_c, groupnumber, friendcon_id);
    }
    Group_Peer *temp;
    --g->numpeers;
    void *peer_object = g->group[peer_index].object;
    if (g->numpeers == 0) {
        free(g->group);
        g->group = NULL;
    } else {
        if (g->numpeers != (uint32_t)peer_index)
            memcpy(&g->group[peer_index], &g->group[g->numpeers], sizeof(
      Group_Peer));
        temp = realloc(g->group, sizeof(Group_Peer) * (g->
      numpeers));
        if (temp == NULL)
            return -1;
        g->group = temp;
    }
    if (g_c->peer_namelistchange)
        g_c->peer_namelistchange(g_c->m, groupnumber, peer_index,
      CHAT_CHANGE_PEER_DEL, g_c->group_namelistchange_userdata);
    if (g->peer_on_leave)
        g->peer_on_leave(g->object, groupnumber, peer_index, peer_object);
    return 0;
}
void do_groupchats (Group_Chats * g_c)
Definition at line 2241 of file group.c.
References connect_to_closest(), get_group_c(), groupchat_clear_timedout(), GROUPCHAT_STATUS_CONNECTED, i, Group_Chats::num_chats, ping_groupchat(), and Group_c::status.
Referenced by tox_iterate().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        Group_c *g = get_group_c(g_c, i);
        if (!g)
            continue;
        if (g->status == GROUPCHAT_STATUS_CONNECTED) {
            connect_to_closest(g_c, i);
            ping_groupchat(g_c, i);
            groupchat_clear_timedout(g_c, i);
        }
    }
    //TODO
}
static int friend_in_close (Group_c * g, int friendcon_id) [static]
Definition at line 1325 of file group.c.
References Group_c::close, GROUPCHAT_CLOSE_NONE, i, MAX_GROUP_CONNECTIONS, Group_c::number, and Group_c::type.
Referenced by handle_lossy(), handle_packet(), and handle_packet_online().
{
    unsigned int i;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        if (g->close[i].number != (uint32_t)friendcon_id)
            continue;
        return i;
    }
    return -1;
}
void g_callback_group_action (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1012 of file group.c.
References Group_Chats::action_callback, and Group_Chats::action_callback_userdata.
Referenced by tox_callback_group_action().
{
    g_c->action_callback = function;
    g_c->action_callback_userdata = userdata;
}
void g_callback_group_invite (Group_Chats * g_c, void(*)(Messenger *m, int32_t, uint8_t, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 990 of file group.c.
References Group_Chats::invite_callback, and Group_Chats::invite_callback_userdata.
Referenced by tox_callback_group_invite().
{
    g_c->invite_callback = function;
    g_c->invite_callback_userdata = userdata;
}
void g_callback_group_message (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1001 of file group.c.
References Group_Chats::message_callback, and Group_Chats::message_callback_userdata.
Referenced by tox_callback_group_message().
{
    g_c->message_callback = function;
    g_c->message_callback_userdata = userdata;
}
void g_callback_group_namelistchange (Group_Chats * g_c, void(*)(Messenger *m, int, int, uint8_t, void *) function, void * userdata)
Definition at line 1036 of file group.c.
References Group_Chats::group_namelistchange_userdata, and Group_Chats::peer_namelistchange.
Referenced by tox_callback_group_namelist_change().
{
    g_c->peer_namelistchange = function;
    g_c->group_namelistchange_userdata = userdata;
}
void g_callback_group_title (Group_Chats * g_c, void(*)(Messenger *m, int, int, const uint8_t *, uint8_t, void *) function, void * userdata)
Definition at line 1048 of file group.c.
References Group_Chats::title_callback, and Group_Chats::title_callback_userdata.
Referenced by tox_callback_group_title().
{
    g_c->title_callback = function;
    g_c->title_callback_userdata = userdata;
}
static Group_c* get_group_c (const Group_Chats * g_c, int groupnumber) [static]
Definition at line 124 of file group.c.
References Group_Chats::chats, and groupnumber_not_valid().
Referenced by add_conn_to_groupchat(), add_to_closest(), addpeer(), callback_groupchat_delete(), callback_groupchat_peer_delete(), callback_groupchat_peer_new(), connect_to_closest(), del_groupchat(), delpeer(), do_groupchats(), group_get_object(), group_get_type(), group_names(), group_number_peers(), group_peer_get_object(), group_peer_pubkey(), group_peer_set_object(), group_peername(), group_peernumber_is_ours(), group_set_object(), group_title_get(), group_title_send(), groupchat_clear_timedout(), handle_direct_packet(), handle_friend_invite_packet(), handle_lossy(), handle_message_packet_group(), handle_packet(), handle_packet_online(), handle_send_peers(), invite_friend(), ping_groupchat(), remove_close_conn(), send_group_lossy_packet(), send_lossy_all_close(), send_message_all_close(), send_message_group(), send_name_all_groups(), send_peers(), set_conns_type_close(), setnick(), and settitle().
{
    if (groupnumber_not_valid(g_c, groupnumber))
        return 0;
    return &g_c->chats[groupnumber];
}
static int get_group_num (const Group_Chats * g_c, const uint8_t * identifier) [static]
Definition at line 160 of file group.c.
References Group_Chats::chats, GROUP_IDENTIFIER_LENGTH, i, Group_c::identifier, and Group_Chats::num_chats.
Referenced by handle_friend_invite_packet(), handle_packet_online(), and join_groupchat().
{
    uint32_t i;
    for (i = 0; i < g_c->num_chats; ++i)
        if (memcmp(g_c->chats[i].identifier, identifier,
      GROUP_IDENTIFIER_LENGTH) == 0)
            return i;
    return -1;
}
static int get_peer_index (Group_c * g, uint16_t peer_number) [static]
Definition at line 179 of file group.c.
References Group_c::group, i, Group_c::numpeers, and Group_Peer::peer_number.
Referenced by addpeer(), handle_friend_invite_packet(), handle_lossy(), and handle_message_packet_group().
{
    uint32_t i;
    for (i = 0; i < g->numpeers; ++i)
        if (g->group[i].peer_number == peer_number)
            return i;
    return -1;
}
int group_action_send (const Group_Chats * g_c, int groupnumber, const uint8_t * action, uint16_t length)
Definition at line 1768 of file group.c.
References PACKET_ID_ACTION, and send_message_group().
Referenced by tox_group_action_send().
{
    if (send_message_group(g_c, groupnumber, PACKET_ID_ACTION, action,
      length)) {
        return 0;
    } else {
        return -1;
    }
}
void* group_get_object (const Group_Chats * g_c, int groupnumber)
Definition at line 2136 of file group.c.
References get_group_c(), and Group_c::object.
Referenced by group_send_audio(), and send_audio_packet().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return NULL;
    return g->object;
}
int group_get_type (const Group_Chats * g_c, int groupnumber)
Definition at line 840 of file group.c.
References get_group_c(), and Group_c::identifier.
Referenced by tox_group_get_type().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    return g->identifier[0];
}
static int group_kill_peer_send (const Group_Chats * g_c, int groupnumber, uint16_t peer_num) [static]
Definition at line 1152 of file group.c.
References GROUP_MESSAGE_KILL_PEER_ID, GROUP_MESSAGE_KILL_PEER_LENGTH, and send_message_group().
Referenced by del_groupchat().
{
    uint8_t packet[GROUP_MESSAGE_KILL_PEER_LENGTH];
    peer_num = htons(peer_num);
    memcpy(packet, &peer_num, sizeof(uint16_t));
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_KILL_PEER_ID, packet, sizeof(packet))) {
        return 0;
    } else {
        return -1;
    }
}
void group_lossy_packet_registerhandler (Group_Chats * g_c, uint8_t byte, int(*)(void *, int, int, void *, const uint8_t *, uint16_t) function)
Definition at line 1025 of file group.c.
References Group_Chats::function, and Group_Chats::lossy_packethandlers.
Referenced by groupchat_enable_av().
{
    g_c->lossy_packethandlers[byte].function = function;
}
int group_message_send (const Group_Chats * g_c, int groupnumber, const uint8_t * message, uint16_t length)
Definition at line 1755 of file group.c.
References PACKET_ID_MESSAGE, and send_message_group().
Referenced by tox_group_message_send().
{
    if (send_message_group(g_c, groupnumber, PACKET_ID_MESSAGE, message,
       length)) {
        return 0;
    } else {
        return -1;
    }
}
static int group_name_send (const Group_Chats * g_c, int groupnumber, const uint8_t * nick, uint16_t nick_len) [static]
Definition at line 1172 of file group.c.
References GROUP_MESSAGE_NAME_ID, MAX_NAME_LENGTH, and send_message_group().
Referenced by handle_send_peers(), and send_name_all_groups().
{
    if (nick_len > MAX_NAME_LENGTH)
        return -1;
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_NAME_ID, nick, nick_len)) {
        return 0;
    } else {
        return -1;
    }
}
int group_names (const Group_Chats * g_c, int groupnumber, uint8_t names[][MAX_NAME_LENGTH], uint16_t lengths[], uint16_t length)
Definition at line 786 of file group.c.
References get_group_c(), group_peername(), i, and Group_c::numpeers.
Referenced by tox_group_get_names().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    unsigned int i;
    for (i = 0; i < g->numpeers && i < length; ++i) {
        lengths[i] = group_peername(g_c, groupnumber, i, names[i]);
    }
    return i;
}
int group_new_peer_send (const Group_Chats * g_c, int groupnumber, uint16_t peer_num, const uint8_t * real_pk, uint8_t * temp_pk)
Definition at line 1128 of file group.c.
References GROUP_MESSAGE_NEW_PEER_ID, GROUP_MESSAGE_NEW_PEER_LENGTH, and send_message_group().
Referenced by handle_friend_invite_packet().
{
    uint8_t packet[GROUP_MESSAGE_NEW_PEER_LENGTH];
    peer_num = htons(peer_num);
    memcpy(packet, &peer_num, sizeof(uint16_t));
    memcpy(packet + sizeof(uint16_t), real_pk, crypto_box_PUBLICKEYBYTES);
    memcpy(packet + sizeof(uint16_t) + crypto_box_PUBLICKEYBYTES, temp_pk, crypto_box_PUBLICKEYBYTES);
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_NEW_PEER_ID, packet, sizeof(packet))) {
        return 0;
    } else {
        return -1;
    }
}
int group_number_peers (const Group_Chats * g_c, int groupnumber)
Definition at line 806 of file group.c.
References get_group_c(), and Group_c::numpeers.
Referenced by tox_group_number_peers().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    return g->numpeers;
}
void* group_peer_get_object (const Group_Chats * g_c, int groupnumber, int peernumber)
Definition at line 2151 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::object.
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return NULL;
    if ((uint32_t)peernumber >= g->numpeers)
        return NULL;
    return g->group[peernumber].object;
}
int group_peer_pubkey (const Group_Chats * g_c, int groupnumber, int peernumber, uint8_t * pk)
Definition at line 737 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::real_pk.
Referenced by tox_group_peer_pubkey().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    memcpy(pk, g->group[peernumber].real_pk, crypto_box_PUBLICKEYBYTES);
    return 0;
}
int group_peer_set_object (const Group_Chats * g_c, int groupnumber, int peernumber, void * object)
Definition at line 2117 of file group.c.
References get_group_c(), Group_c::group, Group_c::numpeers, and Group_Peer::object.
Referenced by group_av_peer_new().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    g->group[peernumber].object = object;
    return 0;
}
int group_peername (const Group_Chats * g_c, int groupnumber, int peernumber, uint8_t * name)
Definition at line 757 of file group.c.
References get_group_c(), Group_c::group, Group_Peer::nick, Group_Peer::nick_len, and Group_c::numpeers.
Referenced by group_names(), and tox_group_peername().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if ((uint32_t)peernumber >= g->numpeers)
        return -1;
    if (g->group[peernumber].nick_len == 0) {
        memcpy(name, "Tox User", 8);
        return 8;
    }
    memcpy(name, g->group[peernumber].nick, g->group[peernumber].
      nick_len);
    return g->group[peernumber].nick_len;
}
unsigned int group_peernumber_is_ours (const Group_Chats * g_c, int groupnumber, int peernumber)
Definition at line 819 of file group.c.
References get_group_c(), Group_c::group, GROUPCHAT_STATUS_CONNECTED, Group_c::numpeers, Group_Peer::peer_number, Group_c::peer_number, and Group_c::status.
Referenced by tox_group_peernumber_is_ours().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return 0;
    if (g->status != GROUPCHAT_STATUS_CONNECTED)
        return 0;
    if ((uint32_t)peernumber >= g->numpeers)
        return 0;
    return g->peer_number == g->group[peernumber].peer_number;
}
int group_ping_send (const Group_Chats * g_c, int groupnumber)
Definition at line 1113 of file group.c.
References GROUP_MESSAGE_PING_ID, and send_message_group().
Referenced by ping_groupchat().
{
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_PING_ID, 0, 0)) {
        return 0;
    } else {
        return -1;
    }
}
int group_set_object (const Group_Chats * g_c, int groupnumber, void * object)
Definition at line 2101 of file group.c.
References get_group_c(), and Group_c::object.
Referenced by groupchat_enable_av().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    g->object = object;
    return 0;
}
int group_title_get (const Group_Chats * g_c, int groupnumber, uint8_t * title, uint32_t max_length)
Definition at line 1222 of file group.c.
References get_group_c(), MAX_NAME_LENGTH, Group_c::title, and Group_c::title_len.
Referenced by tox_group_get_title().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if (g->title_len == 0 || g->title_len > MAX_NAME_LENGTH)
        return -1;
    if (max_length > g->title_len)
        max_length = g->title_len;
    memcpy(title, g->title, max_length);
    return max_length;
}
int group_title_send (const Group_Chats * g_c, int groupnumber, const uint8_t * title, uint8_t title_len)
Definition at line 1190 of file group.c.
References get_group_c(), GROUP_MESSAGE_TITLE_ID, MAX_NAME_LENGTH, Group_c::numpeers, send_message_group(), Group_c::title, and Group_c::title_len.
Referenced by tox_group_set_title().
{
    if (title_len > MAX_NAME_LENGTH || title_len == 0)
        return -1;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    /* same as already set? */
    if (g->title_len == title_len && !memcmp(g->title, title, title_len))
        return 0;
    memcpy(g->title, title, title_len);
    g->title_len = title_len;
    if (g->numpeers == 1)
        return 0;
    if (send_message_group(g_c, groupnumber,
      GROUP_MESSAGE_TITLE_ID, title, title_len))
        return 0;
    else
        return -1;
}
static int groupchat_clear_timedout (Group_Chats * g_c, int groupnumber) [static]
Definition at line 2182 of file group.c.
References delpeer(), get_group_c(), Group_c::group, GROUP_PING_INTERVAL, i, is_timeout(), Group_Peer::last_recv, Group_c::numpeers, Group_Peer::peer_number, and Group_c::peer_number.
Referenced by do_groupchats().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint32_t i;
    for (i = 0; i < g->numpeers; ++i) {
        if (g->peer_number != g->group[i].peer_number &&
      is_timeout(g->group[i].last_recv, GROUP_PING_INTERVAL * 3)) {
            delpeer(g_c, groupnumber, i);
        }
        if (g->group == NULL || i >= g->numpeers)
            break;
    }
    return 0;
}
static uint8_t groupnumber_not_valid (const Group_Chats * g_c, int groupnumber) [static]
Definition at line 34 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, Group_Chats::num_chats, and Group_c::status.
Referenced by get_group_c(), and wipe_group_chat().
{
    if ((unsigned int)groupnumber >= g_c->num_chats)
        return 1;
    if (g_c->chats == NULL)
        return 1;
    if (g_c->chats[groupnumber].status == GROUPCHAT_STATUS_NONE)
        return 1;
    return 0;
}
static void handle_direct_packet (Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length, int close_index) [static]
Definition at line 1548 of file group.c.
References Group_c::close, Group_c::closest, Group_Chats::fr_c, get_group_c(), Group_c::group_number, GROUPCHAT_CLOSE_NONE, handle_send_peers(), kill_friend_connection(), Group_c::number, PEER_KILL_ID, PEER_QUERY_ID, PEER_RESPONSE_ID, PEER_TITLE_ID, send_peers(), settitle(), and Group_c::type.
Referenced by handle_packet().
{
    if (length == 0)
        return;
    switch (data[0]) {
        case PEER_KILL_ID: {
            Group_c *g = get_group_c(g_c, groupnumber);
            if (!g)
                return;
            if (!g->close[close_index].closest) {
                g->close[close_index].type = GROUPCHAT_CLOSE_NONE;
                kill_friend_connection(g_c->fr_c, g->
      close[close_index].number);
            }
        }
        break;
        case PEER_QUERY_ID: {
            Group_c *g = get_group_c(g_c, groupnumber);
            if (!g)
                return;
            send_peers(g_c, groupnumber, g->close[close_index].
      number, g->close[close_index].group_number);
        }
        break;
        case PEER_RESPONSE_ID: {
            handle_send_peers(g_c, groupnumber, data + 1, length - 1);
        }
        break;
        case PEER_TITLE_ID: {
            settitle(g_c, groupnumber, -1, data + 1, length - 1);
        }
        break;
    }
}
static void handle_friend_invite_packet (Messenger * m, uint32_t friendnumber, const uint8_t * data, uint16_t length) [static]
Definition at line 1239 of file group.c.
References add_conn_to_groupchat(), addpeer(), Group_c::close, Group_Chats::fr_c, get_friendcon_public_keys(), get_group_c(), get_group_num(), get_peer_index(), getfriendcon_id(), Messenger::group_chat_object, GROUP_IDENTIFIER_LENGTH, group_new_peer_send(), Group_c::group_number, GROUPCHAT_CLOSE_ONLINE, Group_c::identifier, Group_Chats::invite_callback, Group_Chats::invite_callback_userdata, INVITE_ID, INVITE_PACKET_SIZE, INVITE_RESPONSE_ID, INVITE_RESPONSE_PACKET_SIZE, and Group_c::type.
Referenced by new_groupchats().
{
    Group_Chats *g_c = m->group_chat_object;
    if (length <= 1)
        return;
    const uint8_t *invite_data = data + 1;
    uint16_t invite_length = length - 1;
    switch (data[0]) {
        case INVITE_ID: {
            if (length != INVITE_PACKET_SIZE)
                return;
            int groupnumber = get_group_num(g_c, data + 1 + sizeof(uint16_t));
            if (groupnumber == -1) {
                if (g_c->invite_callback)
                    g_c->invite_callback(m, friendnumber, *(invite_data + sizeof(uint16_t)),
       invite_data, invite_length,
                                         g_c->invite_callback_userdata);
                return;
            }
            break;
        }
        case INVITE_RESPONSE_ID: {
            if (length != INVITE_RESPONSE_PACKET_SIZE)
                return;
            uint16_t other_groupnum, groupnum;
            memcpy(&groupnum, data + 1 + sizeof(uint16_t), sizeof(uint16_t));
            groupnum = ntohs(groupnum);
            Group_c *g = get_group_c(g_c, groupnum);
            if (!g)
                return;
            if (memcmp(data + 1 + sizeof(uint16_t) * 2, g->identifier,
      GROUP_IDENTIFIER_LENGTH) != 0)
                return;
            uint16_t peer_number = rand(); /* TODO: what if two people enter the group at the same time and
  are given the same peer_number by different nodes? */
            unsigned int tries = 0;
            while (get_peer_index(g, peer_number) != -1) {
                peer_number = rand();
                ++tries;
                if (tries > 32)
                    return;
            }
            memcpy(&other_groupnum, data + 1, sizeof(uint16_t));
            other_groupnum = ntohs(other_groupnum);
            int friendcon_id = getfriendcon_id(m, friendnumber);
            uint8_t real_pk[crypto_box_PUBLICKEYBYTES], temp_pk[crypto_box_PUBLICKEYBYTES];
            get_friendcon_public_keys(real_pk, temp_pk, g_c->
      fr_c, friendcon_id);
            addpeer(g_c, groupnum, real_pk, temp_pk, peer_number);
            int close_index = add_conn_to_groupchat(g_c, friendcon_id, groupnum, 0, 1)
      ;
            if (close_index != -1) {
                g->close[close_index].group_number = other_groupnum;
                g->close[close_index].type = GROUPCHAT_CLOSE_ONLINE;
            }
            group_new_peer_send(g_c, groupnum, peer_number, real_pk, temp_pk);
            break;
        }
        default:
            return;
    }
}
static int handle_lossy (void * object, int friendcon_id, const uint8_t * data, uint16_t length) [static]
Definition at line 2038 of file group.c.
References friend_in_close(), Group_Chats::function, get_group_c(), get_peer_index(), Group_c::group, lossy_packet_not_received(), Group_Chats::lossy_packethandlers, Group_Peer::object, Group_c::object, PACKET_ID_LOSSY_GROUPCHAT, Group_c::peer_number, and send_lossy_all_close().
Referenced by add_conn_to_groupchat().
{
    Group_Chats *g_c = object;
    if (length < 1 + sizeof(uint16_t) * 3 + 1)
        return -1;
    if (data[0] != PACKET_ID_LOSSY_GROUPCHAT)
        return -1;
    uint16_t groupnumber, peer_number, message_number;
    memcpy(&groupnumber, data + 1, sizeof(uint16_t));
    memcpy(&peer_number, data + 1 + sizeof(uint16_t), sizeof(uint16_t));
    memcpy(&message_number, data + 1 + sizeof(uint16_t) * 2, sizeof(uint16_t));
    groupnumber = ntohs(groupnumber);
    peer_number = ntohs(peer_number);
    message_number = ntohs(message_number);
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    int index = friend_in_close(g, friendcon_id);
    if (index == -1)
        return -1;
    if (peer_number == g->peer_number)
        return -1;
    int peer_index = get_peer_index(g, peer_number);
    if (peer_index == -1)
        return -1;
    if (lossy_packet_not_received(g, peer_index, message_number))
        return -1;
    const uint8_t *lossy_data = data + 1 + sizeof(uint16_t) * 3;
    uint16_t lossy_length = length - (1 + sizeof(uint16_t) * 3);
    uint8_t message_id = lossy_data[0];
    ++lossy_data;
    --lossy_length;
    if (g_c->lossy_packethandlers[message_id].function) {
        if (g_c->lossy_packethandlers[message_id].function(g->
      object, groupnumber, peer_index, g->group[peer_index].object,
                lossy_data, lossy_length) == -1) {
            return -1;
        }
    } else {
        return -1;
    }
    send_lossy_all_close(g_c, groupnumber, data + 1 + sizeof(uint16_t), length - (1
       + sizeof(uint16_t)), index);
    return 0;
}
static void handle_message_packet_group (Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length, int close_index) [static]
Definition at line 1805 of file group.c.
References Group_Chats::action_callback, Group_Chats::action_callback_userdata, addpeer(), Group_c::close, delpeer(), get_group_c(), get_peer_index(), Group_c::group, GROUP_MESSAGE_KILL_PEER_ID, GROUP_MESSAGE_KILL_PEER_LENGTH, GROUP_MESSAGE_NAME_ID, GROUP_MESSAGE_NEW_PEER_ID, GROUP_MESSAGE_NEW_PEER_LENGTH, GROUP_MESSAGE_PING_ID, GROUP_MESSAGE_TITLE_ID, Group_c::group_number, Group_Peer::last_message_number, Group_Peer::last_recv, Group_Chats::m, Group_Chats::message_callback, Group_Chats::message_callback_userdata, Group_c::number, PACKET_ID_ACTION, PACKET_ID_MESSAGE, send_message_all_close(), send_peer_query(), setnick(), settitle(), and unix_time().
Referenced by handle_packet().
{
    if (length < sizeof(uint16_t) + sizeof(uint32_t) + 1)
        return;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return;
    uint16_t peer_number;
    memcpy(&peer_number, data, sizeof(uint16_t));
    peer_number = ntohs(peer_number);
    int index = get_peer_index(g, peer_number);
    if (index == -1) {
        /* We don't know the peer this packet came from so we query the list of peers from that peer.
          (They would not have relayed it if they didn't know the peer.) */
        send_peer_query(g_c, g->close[close_index].number, g->
      close[close_index].group_number);
        return;
    }
    uint32_t message_number;
    memcpy(&message_number, data + sizeof(uint16_t), sizeof(message_number));
    message_number = ntohl(message_number);
    if (g->group[index].last_message_number == 0) {
        g->group[index].last_message_number = message_number;
    } else if (message_number - g->group[index].last_message_number > 64 ||
               message_number == g->group[index].last_message_number) {
        return;
    }
    g->group[index].last_message_number = message_number;
    uint8_t message_id = data[sizeof(uint16_t) + sizeof(message_number)];
    const uint8_t *msg_data = data + sizeof(uint16_t) + sizeof(message_number) + 1;
    uint16_t msg_data_len = length - (sizeof(uint16_t) + sizeof(message_number) + 1);
    switch (message_id) {
        case GROUP_MESSAGE_PING_ID: {
            if (msg_data_len != 0)
                return;
            g->group[index].last_recv = unix_time();
        }
        break;
        case GROUP_MESSAGE_NEW_PEER_ID: {
            if (msg_data_len != GROUP_MESSAGE_NEW_PEER_LENGTH)
                return;
            uint16_t new_peer_number;
            memcpy(&new_peer_number, msg_data, sizeof(uint16_t));
            new_peer_number = ntohs(new_peer_number);
            addpeer(g_c, groupnumber, msg_data + sizeof(uint16_t), msg_data + sizeof(uint16_t) +
      crypto_box_PUBLICKEYBYTES,
                    new_peer_number);
        }
        break;
        case GROUP_MESSAGE_KILL_PEER_ID: {
            if (msg_data_len != GROUP_MESSAGE_KILL_PEER_LENGTH)
                return;
            uint16_t kill_peer_number;
            memcpy(&kill_peer_number, msg_data, sizeof(uint16_t));
            kill_peer_number = ntohs(kill_peer_number);
            if (peer_number == kill_peer_number) {
                delpeer(g_c, groupnumber, index);
            } else {
                return;
                //TODO
            }
        }
        break;
        case GROUP_MESSAGE_NAME_ID: {
            if (setnick(g_c, groupnumber, index, msg_data, msg_data_len) == -1)
                return;
        }
        break;
        case GROUP_MESSAGE_TITLE_ID: {
            if (settitle(g_c, groupnumber, index, msg_data, msg_data_len) == -1)
                return;
        }
        break;
        case PACKET_ID_MESSAGE: {
            if (msg_data_len == 0)
                return;
            uint8_t newmsg[msg_data_len + 1];
            memcpy(newmsg, msg_data, msg_data_len);
            newmsg[msg_data_len] = 0;
            //TODO
            if (g_c->message_callback)
                g_c->message_callback(g_c->m, groupnumber, index, newmsg, msg_data_len,
      g_c->message_callback_userdata);
            break;
        }
        case PACKET_ID_ACTION: {
            if (msg_data_len == 0)
                return;
            uint8_t newmsg[msg_data_len + 1];
            memcpy(newmsg, msg_data, msg_data_len);
            newmsg[msg_data_len] = 0;
            //TODO
            if (g_c->action_callback)
                g_c->action_callback(g_c->m, groupnumber, index, newmsg, msg_data_len, g_c
      ->action_callback_userdata);
            break;
        }
        default:
            return;
    }
    send_message_all_close(g_c, groupnumber, data, length, -1/*TODO close_index*/
      );
}
static int handle_packet (void * object, int friendcon_id, uint8_t * data, uint16_t length) [static]
Definition at line 1933 of file group.c.
References friend_in_close(), get_group_c(), handle_direct_packet(), handle_message_packet_group(), handle_packet_online(), PACKET_ID_DIRECT_GROUPCHAT, PACKET_ID_MESSAGE_GROUPCHAT, and PACKET_ID_ONLINE_PACKET.
Referenced by add_conn_to_groupchat().
{
    Group_Chats *g_c = object;
    if (length < 1 + sizeof(uint16_t) + 1)
        return -1;
    if (data[0] == PACKET_ID_ONLINE_PACKET) {
        return handle_packet_online(g_c, friendcon_id, data + 1, length - 1);
    }
    if (data[0] != PACKET_ID_DIRECT_GROUPCHAT &&
      data[0] != PACKET_ID_MESSAGE_GROUPCHAT)
        return -1;
    uint16_t groupnumber;
    memcpy(&groupnumber, data + 1, sizeof(uint16_t));
    groupnumber = ntohs(groupnumber);
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    int index = friend_in_close(g, friendcon_id);
    if (index == -1)
        return -1;
    switch (data[0]) {
        case PACKET_ID_DIRECT_GROUPCHAT: {
            handle_direct_packet(g_c, groupnumber, data + 1 + sizeof(uint16_t),
      length - (1 + sizeof(uint16_t)), index);
            break;
        }
        case PACKET_ID_MESSAGE_GROUPCHAT: {
            handle_message_packet_group(g_c, groupnumber,
      data + 1 + sizeof(uint16_t), length - (1 + sizeof(uint16_t)), index);
            break;
        }
        default: {
            return 0;
        }
    }
    return 0;
}
static int handle_packet_online (Group_Chats * g_c, int friendcon_id, uint8_t * data, uint16_t length) [static]
Definition at line 1372 of file group.c.
References Group_c::close, Group_c::closest, count_close_connected(), DESIRED_CLOSE_CONNECTIONS, Group_Chats::fr_c, friend_in_close(), get_group_c(), get_group_num(), Group_c::group_number, GROUPCHAT_CLOSE_NONE, GROUPCHAT_CLOSE_ONLINE, Group_c::identifier, kill_friend_connection(), Group_c::number, Group_c::number_joined, ONLINE_PACKET_DATA_SIZE, send_packet_online(), send_peer_kill(), send_peer_query(), and Group_c::type.
Referenced by handle_packet().
{
    if (length != ONLINE_PACKET_DATA_SIZE)
        return -1;
    int groupnumber = get_group_num(g_c, data + sizeof(uint16_t));
    uint16_t other_groupnum;
    memcpy(&other_groupnum, data, sizeof(uint16_t));
    other_groupnum = ntohs(other_groupnum);
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    int index = friend_in_close(g, friendcon_id);
    if (index == -1)
        return -1;
    if (g->close[index].type == GROUPCHAT_CLOSE_ONLINE) {
        return -1;
    }
    if (count_close_connected(g) == 0) {
        send_peer_query(g_c, friendcon_id, other_groupnum);
    }
    g->close[index].group_number = other_groupnum;
    g->close[index].type = GROUPCHAT_CLOSE_ONLINE;
    send_packet_online(g_c->fr_c, friendcon_id, groupnumber, g->
      identifier);
    if (g->number_joined != -1 && count_close_connected(g) >=
      DESIRED_CLOSE_CONNECTIONS) {
        int fr_close_index = friend_in_close(g, g->number_joined);
        if (fr_close_index == -1)
            return -1;
        if (!g->close[fr_close_index].closest) {
            g->close[fr_close_index].type = GROUPCHAT_CLOSE_NONE;
            send_peer_kill(g_c, g->close[fr_close_index].
      number, g->close[fr_close_index].group_number);
            kill_friend_connection(g_c->fr_c, g->close[fr_close_index].
      number);
            g->number_joined = -1;
        }
    }
    return 0;
}
static int handle_send_peers (Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length) [static]
Definition at line 1505 of file group.c.
References addpeer(), make-funny-savefile::data, get_group_c(), group_name_send(), GROUPCHAT_STATUS_CONNECTED, GROUPCHAT_STATUS_VALID, Group_Chats::m, MAX_NAME_LENGTH, Messenger::name, Messenger::name_length, Messenger::net_crypto, Group_c::peer_number, Net_Crypto::self_public_key, setnick(), and Group_c::status.
Referenced by handle_direct_packet().
{
    if (length == 0)
        return -1;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    const uint8_t *d = data;
    while ((unsigned int)(length - (d - data)) >= sizeof(uint16_t) + crypto_box_PUBLICKEYBYTES * 2 + 1)
       {
        uint16_t peer_num;
        memcpy(&peer_num, d, sizeof(peer_num));
        peer_num = ntohs(peer_num);
        d += sizeof(uint16_t);
        int peer_index = addpeer(g_c, groupnumber, d, d + crypto_box_PUBLICKEYBYTES, peer_num);
        if (peer_index == -1)
            return -1;
        if (g->status == GROUPCHAT_STATUS_VALID
                && memcmp(d, g_c->m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES) == 0) {
            g->peer_number = peer_num;
            g->status = GROUPCHAT_STATUS_CONNECTED;
            group_name_send(g_c, groupnumber, g_c->m->name, g_c->
      m->name_length);
        }
        d += crypto_box_PUBLICKEYBYTES * 2;
        uint8_t name_length = *d;
        d += 1;
        if (name_length > (length - (d - data)) || name_length >
      MAX_NAME_LENGTH)
            return -1;
        setnick(g_c, groupnumber, peer_index, d, name_length);
        d += name_length;
    }
    return 0;
}
static int handle_status (void * object, int friendcon_id, uint8_t status) [static]
Definition at line 601 of file group.c.
References GROUPCHAT_CLOSE_CONNECTION, GROUPCHAT_CLOSE_ONLINE, and set_conns_status_groups().
Referenced by add_conn_to_groupchat().
{
    Group_Chats *g_c = object;
    if (status) { /* Went online */
        set_conns_status_groups(g_c, friendcon_id,
      GROUPCHAT_CLOSE_ONLINE);
    } else { /* Went offline */
        set_conns_status_groups(g_c, friendcon_id,
      GROUPCHAT_CLOSE_CONNECTION);
        //TODO remove timedout connections?
    }
    return 0;
}
int invite_friend (Group_Chats * g_c, int32_t friendnumber, int groupnumber)
Definition at line 900 of file group.c.
References get_group_c(), GROUP_IDENTIFIER_LENGTH, Group_c::identifier, invite, INVITE_ID, INVITE_PACKET_SIZE, Group_Chats::m, send_group_invite_packet(), and wipe_group_chat().
Referenced by tox_invite_friend().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint8_t invite[INVITE_PACKET_SIZE];
    invite[0] = INVITE_ID;
    uint16_t groupchat_num = htons((uint16_t)groupnumber);
    memcpy(invite + 1, &groupchat_num, sizeof(groupchat_num));
    memcpy(invite + 1 + sizeof(groupchat_num), g->identifier,
      GROUP_IDENTIFIER_LENGTH);
    if (send_group_invite_packet(g_c->m, friendnumber, invite, sizeof(invite))) {
        return 0;
    } else {
        wipe_group_chat(g_c, groupnumber);
        return -1;
    }
}
int join_groupchat (Group_Chats * g_c, int32_t friendnumber, uint8_t expected_type, const uint8_t * data, uint16_t length)
Definition at line 930 of file group.c.
References add_conn_to_groupchat(), Group_Chats::chats, Group_c::close, create_group_chat(), get_group_num(), getfriendcon_id(), GROUP_IDENTIFIER_LENGTH, Group_c::group_number, GROUPCHAT_CLOSE_ONLINE, GROUPCHAT_STATUS_NONE, GROUPCHAT_STATUS_VALID, Group_c::identifier, INVITE_RESPONSE_ID, INVITE_RESPONSE_PACKET_SIZE, Group_Chats::m, Messenger::net_crypto, Group_c::number_joined, Group_c::real_pk, Net_Crypto::self_public_key, send_group_invite_packet(), send_peer_query(), Group_c::status, and Group_c::type.
Referenced by join_av_groupchat(), and tox_join_groupchat().
{
    if (length != sizeof(uint16_t) + GROUP_IDENTIFIER_LENGTH)
        return -1;
    if (data[sizeof(uint16_t)] != expected_type)
        return -1;
    int friendcon_id = getfriendcon_id(g_c->m, friendnumber);
    if (friendcon_id == -1)
        return -1;
    if (get_group_num(g_c, data + sizeof(uint16_t)) != -1)
        return -1;
    int groupnumber = create_group_chat(g_c);
    if (groupnumber == -1)
        return -1;
    Group_c *g = &g_c->chats[groupnumber];
    uint16_t group_num = htons(groupnumber);
    g->status = GROUPCHAT_STATUS_VALID;
    g->number_joined = -1;
    memcpy(g->real_pk, g_c->m->net_crypto->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    uint8_t response[INVITE_RESPONSE_PACKET_SIZE];
    response[0] = INVITE_RESPONSE_ID;
    memcpy(response + 1, &group_num, sizeof(uint16_t));
    memcpy(response + 1 + sizeof(uint16_t), data, sizeof(uint16_t) +
      GROUP_IDENTIFIER_LENGTH);
    if (send_group_invite_packet(g_c->m, friendnumber, response, sizeof(response))
      ) {
        uint16_t other_groupnum;
        memcpy(&other_groupnum, data, sizeof(other_groupnum));
        other_groupnum = ntohs(other_groupnum);
        memcpy(g->identifier, data + sizeof(uint16_t),
      GROUP_IDENTIFIER_LENGTH);
        int close_index = add_conn_to_groupchat(g_c, friendcon_id, groupnumber, 0, 1);
        if (close_index != -1) {
            g->close[close_index].group_number = other_groupnum;
            g->close[close_index].type = GROUPCHAT_CLOSE_ONLINE;
            g->number_joined = friendcon_id;
        }
        send_peer_query(g_c, friendcon_id, other_groupnum);
        return groupnumber;
    } else {
        g->status = GROUPCHAT_STATUS_NONE;
        return -1;
    }
}
void kill_groupchats (Group_Chats * g_c)
Definition at line 2262 of file group.c.
References del_groupchat(), Messenger::group_chat_object, i, Group_Chats::m, m_callback_group_invite(), and Group_Chats::num_chats.
Referenced by tox_kill().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        del_groupchat(g_c, i);
    }
    m_callback_group_invite(g_c->m, NULL);
    g_c->m->group_chat_object = 0;
    free(g_c);
}
static unsigned int lossy_packet_not_received (Group_c * g, int peer_index, uint16_t message_number) [static]
Definition at line 1987 of file group.c.
References Group_Peer::bottom_lossy_number, Group_c::group, i, MAX_LOSSY_COUNT, Group_Peer::recv_lossy, and Group_Peer::top_lossy_number.
Referenced by handle_lossy().
{
    if (peer_index == -1)
        return -1;
    if (g->group[peer_index].bottom_lossy_number == g->
      group[peer_index].top_lossy_number) {
        g->group[peer_index].top_lossy_number = message_number;
        g->group[peer_index].bottom_lossy_number = (message_number -
      MAX_LOSSY_COUNT) + 1;
        g->group[peer_index].recv_lossy[message_number %
      MAX_LOSSY_COUNT] = 1;
        return 0;
    }
    if ((uint16_t)(message_number - g->group[peer_index].
      bottom_lossy_number) < MAX_LOSSY_COUNT) {
        if (g->group[peer_index].recv_lossy[message_number %
      MAX_LOSSY_COUNT]) {
            return 1;
        }
        g->group[peer_index].recv_lossy[message_number %
      MAX_LOSSY_COUNT] = 1;
        return 0;
    }
    if ((uint16_t)(message_number - g->group[peer_index].
      bottom_lossy_number) > (1 << 15))
        return -1;
    uint16_t top_distance = message_number - g->group[peer_index].
      top_lossy_number;
    if (top_distance >= MAX_LOSSY_COUNT) {
        memset(g->group[peer_index].recv_lossy, 0, sizeof(g->
      group[peer_index].recv_lossy));
        g->group[peer_index].top_lossy_number = message_number;
        g->group[peer_index].bottom_lossy_number = (message_number -
      MAX_LOSSY_COUNT) + 1;
        g->group[peer_index].recv_lossy[message_number %
      MAX_LOSSY_COUNT] = 1;
        return 0;
    }
    if (top_distance < MAX_LOSSY_COUNT) {
        unsigned int i;
        for (i = g->group[peer_index].bottom_lossy_number; i != (g->
      group[peer_index].bottom_lossy_number + top_distance);
                ++i) {
            g->group[peer_index].recv_lossy[i % MAX_LOSSY_COUNT] = 0;
        }
        g->group[peer_index].top_lossy_number = message_number;
        g->group[peer_index].bottom_lossy_number = (message_number -
      MAX_LOSSY_COUNT) + 1;
        g->group[peer_index].recv_lossy[message_number %
      MAX_LOSSY_COUNT] = 1;
        return 0;
    }
    return -1;
}
Group_Chats* new_groupchats (Messenger * m)
Definition at line 2222 of file group.c.
References Group_Chats::fr_c, Messenger::fr_c, Messenger::group_chat_object, handle_friend_invite_packet(), m, Group_Chats::m, and m_callback_group_invite().
Referenced by tox_new().
{
    if (!m)
        return NULL;
    Group_Chats *temp = calloc(1, sizeof(Group_Chats));
    if (temp == NULL)
        return NULL;
    temp->m = m;
    temp->fr_c = m->fr_c;
    m->group_chat_object = temp;
    m_callback_group_invite(m, &
      handle_friend_invite_packet);
    return temp;
}
static int peer_in_chat (const Group_c * chat, const uint8_t * real_pk) [static]
Definition at line 141 of file group.c.
References Group_c::group, i, id_equal(), Group_c::numpeers, and Group_Peer::real_pk.
Referenced by addpeer().
{
    uint32_t i;
    for (i = 0; i < chat->numpeers; ++i)
        if (id_equal(chat->group[i].real_pk, real_pk))
            return i;
    return -1;
}
static int ping_groupchat (Group_Chats * g_c, int groupnumber) [static]
Definition at line 2167 of file group.c.
References get_group_c(), GROUP_PING_INTERVAL, group_ping_send(), is_timeout(), Group_c::last_sent_ping, and unix_time().
Referenced by do_groupchats().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    if (is_timeout(g->last_sent_ping,
      GROUP_PING_INTERVAL)) {
        if (group_ping_send(g_c, groupnumber) != -1) /* Ping */
            g->last_sent_ping = unix_time();
    }
    return 0;
}
static unsigned int pk_in_closest_peers (Group_c * g, uint8_t * real_pk) [static]
Definition at line 294 of file group.c.
References Group_c::closest_peers, DESIRED_CLOSE_CONNECTIONS, Group_c::entry, i, and Group_c::real_pk.
Referenced by connect_to_closest().
{
    unsigned int i;
    for (i = 0; i < DESIRED_CLOSE_CONNECTIONS; ++i) {
        if (!g->closest_peers[i].entry)
            continue;
        if (memcmp(g->closest_peers[i].real_pk, real_pk, crypto_box_PUBLICKEYBYTES) ==
      0)
            return 1;
    }
    return 0;
}
static int realloc_groupchats (Group_Chats * g_c, uint32_t num) [static]
Definition at line 54 of file group.c.
References Group_Chats::chats.
Referenced by create_group_chat(), and wipe_group_chat().
{
    if (num == 0) {
        free(g_c->chats);
        g_c->chats = NULL;
        return 0;
    }
    Group_c *newgroup_chats = realloc(g_c->chats, num * sizeof(
      Group_c));
    if (newgroup_chats == NULL)
        return -1;
    g_c->chats = newgroup_chats;
    return 0;
}
static int remove_close_conn (Group_Chats * g_c, int groupnumber, int friendcon_id) [static]
Definition at line 437 of file group.c.
References Group_c::close, Group_Chats::fr_c, get_group_c(), GROUPCHAT_CLOSE_NONE, i, kill_friend_connection(), MAX_GROUP_CONNECTIONS, Group_c::number, and Group_c::type.
Referenced by delpeer().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint32_t i;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        if (g->close[i].number == (unsigned int)friendcon_id) {
            g->close[i].type = GROUPCHAT_CLOSE_NONE;
            kill_friend_connection(g_c->fr_c, friendcon_id);
            return 0;
        }
    }
    return -1;
}
int send_group_lossy_packet (const Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length)
Definition at line 1782 of file group.c.
References get_group_c(), Group_c::lossy_message_number, Group_c::peer_number, and send_lossy_all_close().
Referenced by send_audio_packet().
{
    //TODO: length check here?
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint8_t packet[sizeof(uint16_t) * 2 + length];
    uint16_t peer_number = htons(g->peer_number);
    memcpy(packet, &peer_number, sizeof(uint16_t));
    uint16_t message_num = htons(g->lossy_message_number);
    memcpy(packet + sizeof(uint16_t), &message_num, sizeof(uint16_t));
    memcpy(packet + sizeof(uint16_t) * 2, data, length);
    if (send_lossy_all_close(g_c, groupnumber, packet, sizeof(packet), -1) == 0) {
        return -1;
    }
    ++g->lossy_message_number;
    return 0;
}
static unsigned int send_lossy_all_close (const Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length, int receiver) [static]
Definition at line 1631 of file group.c.
References calculate_comp_value(), Group_c::close, Group_c::closest, DESIRED_CLOSE_CONNECTIONS, Group_Chats::fr_c, get_friendcon_public_keys(), get_group_c(), Group_c::group_number, GROUPCHAT_CLOSE_ONLINE, i, MAX_GROUP_CONNECTIONS, Group_c::number, PACKET_ID_LOSSY_GROUPCHAT, Group_c::real_pk, send_lossy_group_peer(), and Group_c::type.
Referenced by handle_lossy(), and send_group_lossy_packet().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return 0;
    unsigned int i, sent = 0, num_connected_closest = 0, connected_closest[
      DESIRED_CLOSE_CONNECTIONS];
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type != GROUPCHAT_CLOSE_ONLINE)
            continue;
        if ((int)i == receiver)
            continue;
        if (g->close[i].closest) {
            connected_closest[num_connected_closest] = i;
            ++num_connected_closest;
            continue;
        }
        if (send_lossy_group_peer(g_c->fr_c, g->close[i].
      number, PACKET_ID_LOSSY_GROUPCHAT, g->close[i].
      group_number, data,
                                  length))
            ++sent;
    }
    if (!num_connected_closest) {
        return sent;
    }
    unsigned int to_send = 0;
    uint64_t comp_val_old = ~0;
    for (i = 0; i < num_connected_closest; ++i) {
        uint8_t real_pk[crypto_box_PUBLICKEYBYTES];
        uint8_t dht_temp_pk[crypto_box_PUBLICKEYBYTES];
        get_friendcon_public_keys(real_pk, dht_temp_pk, g_c->
      fr_c, g->close[connected_closest[i]].number);
        uint64_t comp_val = calculate_comp_value(g->real_pk, real_pk);
        if (comp_val < comp_val_old) {
            to_send = connected_closest[i];
            comp_val_old = comp_val;
        }
    }
    if (send_lossy_group_peer(g_c->fr_c, g->close[to_send].
      number, PACKET_ID_LOSSY_GROUPCHAT,
                              g->close[to_send].group_number,
      data, length)) {
        ++sent;
    }
    unsigned int to_send_other = 0;
    comp_val_old = ~0;
    for (i = 0; i < num_connected_closest; ++i) {
        uint8_t real_pk[crypto_box_PUBLICKEYBYTES];
        uint8_t dht_temp_pk[crypto_box_PUBLICKEYBYTES];
        get_friendcon_public_keys(real_pk, dht_temp_pk, g_c->
      fr_c, g->close[connected_closest[i]].number);
        uint64_t comp_val = calculate_comp_value(real_pk, g->
      real_pk);
        if (comp_val < comp_val_old) {
            to_send_other = connected_closest[i];
            comp_val_old = comp_val;
        }
    }
    if (to_send_other == to_send) {
        return sent;
    }
    if (send_lossy_group_peer(g_c->fr_c, g->close[to_send_other].
      number, PACKET_ID_LOSSY_GROUPCHAT,
                              g->close[to_send_other].group_number,
      data, length)) {
        ++sent;
    }
    return sent;
}
static unsigned int send_lossy_group_peer (Friend_Connections * fr_c, int friendcon_id, uint8_t packet_id, uint16_t group_num, const uint8_t * data, uint16_t length) [static]
Definition at line 875 of file group.c.
References friend_connection_crypt_connection_id(), MAX_CRYPTO_DATA_SIZE, Friend_Connections::net_crypto, and send_lossy_cryptpacket().
Referenced by send_lossy_all_close().
{
    if (1 + sizeof(uint16_t) + length > MAX_CRYPTO_DATA_SIZE)
        return 0;
    group_num = htons(group_num);
    uint8_t packet[1 + sizeof(uint16_t) + length];
    packet[0] = packet_id;
    memcpy(packet + 1, &group_num, sizeof(uint16_t));
    memcpy(packet + 1 + sizeof(uint16_t), data, length);
    return send_lossy_cryptpacket(fr_c->net_crypto,
      friend_connection_crypt_connection_id(fr_c, friendcon_id), packet,
                                  sizeof(packet)) != -1;
}
static unsigned int send_message_all_close (const Group_Chats * g_c, int groupnumber, const uint8_t * data, uint16_t length, int receiver) [static]
Definition at line 1601 of file group.c.
References Group_c::close, Group_Chats::fr_c, get_group_c(), Group_c::group_number, GROUPCHAT_CLOSE_ONLINE, i, MAX_GROUP_CONNECTIONS, Group_c::number, PACKET_ID_MESSAGE_GROUPCHAT, send_packet_group_peer(), and Group_c::type.
Referenced by handle_message_packet_group(), and send_message_group().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return 0;
    uint16_t i, sent = 0;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type != GROUPCHAT_CLOSE_ONLINE)
            continue;
        if ((int)i == receiver)
            continue;
        if (send_packet_group_peer(g_c->fr_c, g->close[i].
      number, PACKET_ID_MESSAGE_GROUPCHAT, g->close[i].
      group_number, data,
                                   length))
            ++sent;
    }
    return sent;
}
static unsigned int send_message_group (const Group_Chats * g_c, int groupnumber, uint8_t message_id, const uint8_t * data, uint16_t len) [static]
Definition at line 1717 of file group.c.
References get_group_c(), GROUPCHAT_STATUS_CONNECTED, MAX_GROUP_MESSAGE_DATA_LEN, Group_c::message_number, Group_c::peer_number, send_message_all_close(), and Group_c::status.
Referenced by group_action_send(), group_kill_peer_send(), group_message_send(), group_name_send(), group_new_peer_send(), group_ping_send(), and group_title_send().
{
    if (len > MAX_GROUP_MESSAGE_DATA_LEN)
        return 0;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return 0;
    if (g->status != GROUPCHAT_STATUS_CONNECTED)
        return 0;
    uint8_t packet[sizeof(uint16_t) + sizeof(uint32_t) + 1 + len];
    uint16_t peer_num = htons(g->peer_number);
    memcpy(packet, &peer_num, sizeof(peer_num));
    ++g->message_number;
    if (!g->message_number)
        ++g->message_number;
    uint32_t message_num = htonl(g->message_number);
    memcpy(packet + sizeof(uint16_t), &message_num, sizeof(message_num));
    packet[sizeof(uint16_t) + sizeof(uint32_t)] = message_id;
    if (len)
        memcpy(packet + sizeof(uint16_t) + sizeof(uint32_t) + 1, data, len);
    return send_message_all_close(g_c, groupnumber, packet, sizeof(packet), -1);
}
void send_name_all_groups (Group_Chats * g_c)
Definition at line 2205 of file group.c.
References get_group_c(), group_name_send(), GROUPCHAT_STATUS_CONNECTED, i, Group_Chats::m, Messenger::name, Messenger::name_length, Group_Chats::num_chats, and Group_c::status.
Referenced by tox_self_set_name().
{
    unsigned int i;
    for (i = 0; i < g_c->num_chats; ++i) {
        Group_c *g = get_group_c(g_c, i);
        if (!g)
            continue;
        if (g->status == GROUPCHAT_STATUS_CONNECTED) {
            group_name_send(g_c, i, g_c->m->name, g_c->m->
      name_length);
        }
    }
}
static unsigned int send_packet_group_peer (Friend_Connections * fr_c, int friendcon_id, uint8_t packet_id, uint16_t group_num, const uint8_t * data, uint16_t length) [static]
Definition at line 855 of file group.c.
References friend_connection_crypt_connection_id(), MAX_CRYPTO_DATA_SIZE, Friend_Connections::net_crypto, and write_cryptpacket().
Referenced by send_message_all_close(), send_peer_kill(), send_peer_query(), and send_peers().
{
    if (1 + sizeof(uint16_t) + length > MAX_CRYPTO_DATA_SIZE)
        return 0;
    group_num = htons(group_num);
    uint8_t packet[1 + sizeof(uint16_t) + length];
    packet[0] = packet_id;
    memcpy(packet + 1, &group_num, sizeof(uint16_t));
    memcpy(packet + 1 + sizeof(uint16_t), data, length);
    return write_cryptpacket(fr_c->net_crypto,
      friend_connection_crypt_connection_id(fr_c, friendcon_id), packet,
                             sizeof(packet), 0) != -1;
}
static int send_packet_online (Friend_Connections * fr_c, int friendcon_id, uint16_t group_num, uint8_t * identifier) [static]
Definition at line 1359 of file group.c.
References friend_connection_crypt_connection_id(), GROUP_IDENTIFIER_LENGTH, Friend_Connections::net_crypto, ONLINE_PACKET_DATA_SIZE, PACKET_ID_ONLINE_PACKET, and write_cryptpacket().
Referenced by connect_to_closest(), handle_packet_online(), and set_conns_type_close().
{
    uint8_t packet[1 + ONLINE_PACKET_DATA_SIZE];
    group_num = htons(group_num);
    packet[0] = PACKET_ID_ONLINE_PACKET;
    memcpy(packet + 1, &group_num, sizeof(uint16_t));
    memcpy(packet + 1 + sizeof(uint16_t), identifier, GROUP_IDENTIFIER_LENGTH);
    return write_cryptpacket(fr_c->net_crypto,
      friend_connection_crypt_connection_id(fr_c, friendcon_id), packet,
                             sizeof(packet), 0) != -1;
}
static unsigned int send_peer_kill (Group_Chats * g_c, int friendcon_id, uint16_t group_num) [static]
Definition at line 1430 of file group.c.
References Group_Chats::fr_c, PACKET_ID_DIRECT_GROUPCHAT, PEER_KILL_ID, and send_packet_group_peer().
Referenced by handle_packet_online().
{
    uint8_t packet[1];
    packet[0] = PEER_KILL_ID;
    return send_packet_group_peer(g_c->fr_c, friendcon_id,
      PACKET_ID_DIRECT_GROUPCHAT, group_num, packet, sizeof(packet));
}
static unsigned int send_peer_query (Group_Chats * g_c, int friendcon_id, uint16_t group_num) [static]
Definition at line 1441 of file group.c.
References Group_Chats::fr_c, PACKET_ID_DIRECT_GROUPCHAT, PEER_QUERY_ID, and send_packet_group_peer().
Referenced by handle_message_packet_group(), handle_packet_online(), and join_groupchat().
{
    uint8_t packet[1];
    packet[0] = PEER_QUERY_ID;
    return send_packet_group_peer(g_c->fr_c, friendcon_id,
      PACKET_ID_DIRECT_GROUPCHAT, group_num, packet, sizeof(packet));
}
static unsigned int send_peers (Group_Chats * g_c, int groupnumber, int friendcon_id, uint16_t group_num) [static]
Definition at line 1451 of file group.c.
References Group_Chats::fr_c, get_group_c(), Group_c::group, i, MAX_CRYPTO_DATA_SIZE, Group_Peer::nick, Group_Peer::nick_len, Group_c::numpeers, PACKET_ID_DIRECT_GROUPCHAT, Group_Peer::peer_number, PEER_RESPONSE_ID, PEER_TITLE_ID, Group_Peer::real_pk, send_packet_group_peer(), Group_Peer::temp_pk, Group_c::title, and Group_c::title_len.
Referenced by handle_direct_packet().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    uint8_t packet[MAX_CRYPTO_DATA_SIZE - (1 + sizeof(uint16_t))];
    packet[0] = PEER_RESPONSE_ID;
    uint8_t *p = packet + 1;
    uint16_t sent = 0;
    unsigned int i;
    for (i = 0; i < g->numpeers; ++i) {
        if ((p - packet) + sizeof(uint16_t) + crypto_box_PUBLICKEYBYTES * 2 + 1 + g->
      group[i].nick_len > sizeof(packet)) {
            if (send_packet_group_peer(g_c->fr_c, friendcon_id,
      PACKET_ID_DIRECT_GROUPCHAT, group_num, packet, (p - packet))) {
                sent = i;
            } else {
                return sent;
            }
            p = packet + 1;
        }
        uint16_t peer_num = htons(g->group[i].peer_number);
        memcpy(p, &peer_num, sizeof(peer_num));
        p += sizeof(peer_num);
        memcpy(p, g->group[i].real_pk, crypto_box_PUBLICKEYBYTES);
        p += crypto_box_PUBLICKEYBYTES;
        memcpy(p, g->group[i].temp_pk, crypto_box_PUBLICKEYBYTES);
        p += crypto_box_PUBLICKEYBYTES;
        *p = g->group[i].nick_len;
        p += 1;
        memcpy(p, g->group[i].nick, g->group[i].nick_len);
        p += g->group[i].nick_len;
    }
    if (sent != i) {
        if (send_packet_group_peer(g_c->fr_c, friendcon_id,
      PACKET_ID_DIRECT_GROUPCHAT, group_num, packet, (p - packet))) {
            sent = i;
        }
    }
    if (g->title_len) {
        uint8_t Packet[1 + g->title_len];
        Packet[0] = PEER_TITLE_ID;
        memcpy(Packet + 1, g->title, g->title_len);
        send_packet_group_peer(g_c->fr_c, friendcon_id,
      PACKET_ID_DIRECT_GROUPCHAT, group_num, Packet, sizeof(Packet));
    }
    return sent;
}
static void set_conns_status_groups (Group_Chats * g_c, int friendcon_id, uint8_t type) [static]
Definition at line 592 of file group.c.
References i, Group_Chats::num_chats, and set_conns_type_close().
Referenced by handle_status().
{
    uint32_t i;
    for (i = 0; i < g_c->num_chats; ++i) {
        set_conns_type_close(g_c, i, friendcon_id, type);
    }
}
static void set_conns_type_close (Group_Chats * g_c, int groupnumber, int friendcon_id, uint8_t type) [static]
Definition at line 568 of file group.c.
References Group_c::close, Group_Chats::fr_c, get_group_c(), GROUPCHAT_CLOSE_NONE, GROUPCHAT_CLOSE_ONLINE, i, Group_c::identifier, MAX_GROUP_CONNECTIONS, Group_c::number, send_packet_online(), and Group_c::type.
Referenced by set_conns_status_groups().
{
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return;
    uint32_t i;
    for (i = 0; i < MAX_GROUP_CONNECTIONS; ++i) {
        if (g->close[i].type == GROUPCHAT_CLOSE_NONE)
            continue;
        if (g->close[i].number != (unsigned int)friendcon_id)
            continue;
        if (type == GROUPCHAT_CLOSE_ONLINE) {
            send_packet_online(g_c->fr_c, friendcon_id, groupnumber, g->
      identifier);
        } else {
            g->close[i].type = type;
        }
    }
}
static int setnick (Group_Chats * g_c, int groupnumber, int peer_index, const uint8_t * nick, uint16_t nick_len) [static]
Definition at line 519 of file group.c.
References CHAT_CHANGE_PEER_NAME, get_group_c(), Group_c::group, Group_Chats::group_namelistchange_userdata, Group_Chats::m, MAX_NAME_LENGTH, Group_Peer::nick, Group_Peer::nick_len, and Group_Chats::peer_namelistchange.
Referenced by add_groupchat(), handle_message_packet_group(), and handle_send_peers().
{
    if (nick_len > MAX_NAME_LENGTH)
        return -1;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    /* same name as already stored? */
    if (g->group[peer_index].nick_len == nick_len)
        if (nick_len == 0 || !memcmp(g->group[peer_index].nick, nick, nick_len))
            return 0;
    if (nick_len)
        memcpy(g->group[peer_index].nick, nick, nick_len);
    g->group[peer_index].nick_len = nick_len;
    if (g_c->peer_namelistchange)
        g_c->peer_namelistchange(g_c->m, groupnumber, peer_index,
      CHAT_CHANGE_PEER_NAME, g_c->group_namelistchange_userdata
      );
    return 0;
}
static int settitle (Group_Chats * g_c, int groupnumber, int peer_index, const uint8_t * title, uint8_t title_len) [static]
Definition at line 545 of file group.c.
References get_group_c(), Group_Chats::m, MAX_NAME_LENGTH, Group_c::title, Group_Chats::title_callback, Group_Chats::title_callback_userdata, and Group_c::title_len.
Referenced by handle_direct_packet(), and handle_message_packet_group().
{
    if (title_len > MAX_NAME_LENGTH || title_len == 0)
        return -1;
    Group_c *g = get_group_c(g_c, groupnumber);
    if (!g)
        return -1;
    /* same as already set? */
    if (g->title_len == title_len && !memcmp(g->title, title, title_len))
        return 0;
    memcpy(g->title, title, title_len);
    g->title_len = title_len;
    if (g_c->title_callback)
        g_c->title_callback(g_c->m, groupnumber, peer_index, title, title_len, g_c->
      title_callback_userdata);
    return 0;
}
static int wipe_group_chat (Group_Chats * g_c, int groupnumber) [static]
Definition at line 103 of file group.c.
References Group_Chats::chats, GROUPCHAT_STATUS_NONE, groupnumber_not_valid(), i, Group_Chats::num_chats, realloc_groupchats(), and Group_c::status.
Referenced by del_groupchat(), and invite_friend().
{
    if (groupnumber_not_valid(g_c, groupnumber))
        return -1;
    uint32_t i;
    memset(&(g_c->chats[groupnumber]), 0 , sizeof(Group_c));
    for (i = g_c->num_chats; i != 0; --i) {
        if (g_c->chats[i - 1].status != GROUPCHAT_STATUS_NONE)
            break;
    }
    if (g_c->num_chats != i) {
        g_c->num_chats = i;
        realloc_groupchats(g_c, g_c->num_chats);
    }
    return 0;
}