toxcore/onion_client.h File Reference
#include `onion_announce.h`
*
#include `net_crypto.h`
*
#include `ping_array.h`
*
Data Structures
struct Onion_Node
struct Onion_Client_Paths
struct Last_Pinged
struct Onion_Friend
struct Onion_Client
Macros
#define MAX_ONION_CLIENTS 8
#define ONION_NODE_PING_INTERVAL 20
#define ONION_NODE_TIMEOUT (ONION_NODE_PING_INTERVAL * 3)
#define ONION_DHTPK_SEND_INTERVAL 30
#define DHT_DHTPK_SEND_INTERVAL 20
#define NUMBER_ONION_PATHS 6
#define ONION_PATH_FIRST_TIMEOUT 4
#define ONION_PATH_TIMEOUT 10
#define ONION_PATH_MAX_LIFETIME 1200
#define ONION_PATH_MAX_NO_RESPONSE_USES 4
#define MAX_STORED_PINGED_NODES 9
#define MIN_NODE_PING_TIME 10
#define MAX_PATH_NODES 32
#define ONION_OFFLINE_TIMEOUT (ONION_NODE_PING_INTERVAL * 1.25)
#define ONION_DATA_FRIEND_REQ CRYPTO_PACKET_FRIEND_REQ
#define ONION_DATA_DHTPK CRYPTO_PACKET_DHTPK
#define ONION_DATA_IN_RESPONSE_MIN_SIZE (crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
#define ONION_CLIENT_MAX_DATA_SIZE (MAX_DATA_REQUEST_SIZE - ONION_DATA_IN_RESPONSE_MIN_SIZE)
Typedefs
typedef int(* oniondata_handler_callback)(void *object, const uint8_t *source_pubkey, const uint8_t *data, uint16_t len)
Functions
int onion_add_bs_path_node (Onion_Client *onion_c, IP_Port ip_port, const uint8_t *public_key)
uint16_t onion_backup_nodes (const Onion_Client *onion_c, Node_format *nodes, uint16_t max_num)
int onion_friend_num (const Onion_Client *onion_c, const uint8_t *public_key)
int onion_addfriend (Onion_Client *onion_c, const uint8_t *public_key)
int onion_delfriend (Onion_Client *onion_c, int friend_num)
int onion_set_friend_online (Onion_Client *onion_c, int friend_num, uint8_t is_online)
int onion_getfriendip (const Onion_Client *onion_c, int friend_num, IP_Port *ip_port)
int recv_tcp_relay_handler (Onion_Client *onion_c, int friend_num, int(*tcp_relay_node_callback)(void *object, uint32_t number, IP_Port ip_port, const uint8_t *public_key), void *object, uint32_t number)
int onion_dht_pk_callback (Onion_Client *onion_c, int friend_num, void(*function)(void *data, int32_t number, const uint8_t *dht_public_key), void *object, uint32_t number)
int onion_set_friend_DHT_pubkey (Onion_Client *onion_c, int friend_num, const uint8_t *dht_key)
unsigned int onion_getfriend_DHT_pubkey (const Onion_Client *onion_c, int friend_num, uint8_t *dht_key)
int send_onion_data (Onion_Client *onion_c, int friend_num, const uint8_t *data, uint16_t length)
void oniondata_registerhandler (Onion_Client *onion_c, uint8_t byte, oniondata_handler_callback cb, void *object)
void do_onion_client (Onion_Client *onion_c)
Onion_Client * new_onion_client (Net_Crypto *c)
void kill_onion_client (Onion_Client *onion_c)
unsigned int onion_connection_status (const Onion_Client *onion_c)
Macro Definition Documentation
#define DHT_DHTPK_SEND_INTERVAL 20
Definition at line 37 of file onion_client.h.
Referenced by do_friend().
#define MAX_ONION_CLIENTS 8
Definition at line 31 of file onion_client.h.
Referenced by client_add_to_list(), client_ping_nodes(), do_announce(), do_friend(), onion_isconnected(), and send_onion_data().
#define MAX_PATH_NODES 32
Definition at line 51 of file onion_client.h.
Referenced by do_announce(), do_friend(), onion_add_bs_path_node(), onion_add_path_node(), onion_backup_nodes(), and random_nodes_path_onion().
#define MAX_STORED_PINGED_NODES 9
Definition at line 48 of file onion_client.h.
Referenced by good_to_ping().
#define MIN_NODE_PING_TIME 10
Definition at line 49 of file onion_client.h.
Referenced by good_to_ping().
#define NUMBER_ONION_PATHS 6
Definition at line 39 of file onion_client.h.
Referenced by is_path_used(), path_exists(), path_timed_out(), random_path(), and set_path_timeouts().
#define ONION_CLIENT_MAX_DATA_SIZE (MAX_DATA_REQUEST_SIZE - ONION_DATA_IN_RESPONSE_MIN_SIZE)
Definition at line 260 of file onion_client.h.
Referenced by friendreq_handlepacket(), and send_friend_request_packet().
#define ONION_DATA_DHTPK CRYPTO_PACKET_DHTPK
Definition at line 60 of file onion_client.h.
Referenced by kill_onion_client(), new_onion_client(), and send_dhtpk_announce().
#define ONION_DATA_FRIEND_REQ CRYPTO_PACKET_FRIEND_REQ
Definition at line 59 of file onion_client.h.
#define ONION_DATA_IN_RESPONSE_MIN_SIZE (crypto_box_PUBLICKEYBYTES + crypto_box_MACBYTES)
Definition at line 259 of file onion_client.h.
#define ONION_DHTPK_SEND_INTERVAL 30
Definition at line 36 of file onion_client.h.
Referenced by do_friend().
#define ONION_NODE_PING_INTERVAL 20
Definition at line 32 of file onion_client.h.
#define ONION_NODE_TIMEOUT (ONION_NODE_PING_INTERVAL * 3)
Definition at line 33 of file onion_client.h.
Referenced by client_add_to_list(), client_ping_nodes(), cmp_entry(), do_announce(), onion_isconnected(), and send_onion_data().
#define ONION_OFFLINE_TIMEOUT (ONION_NODE_PING_INTERVAL * 1.25)
Definition at line 56 of file onion_client.h.
Referenced by onion_isconnected().
#define ONION_PATH_FIRST_TIMEOUT 4
Definition at line 43 of file onion_client.h.
Referenced by random_path().
#define ONION_PATH_MAX_LIFETIME 1200
Definition at line 45 of file onion_client.h.
Referenced by is_path_used(), and path_timed_out().
#define ONION_PATH_MAX_NO_RESPONSE_USES 4
Definition at line 46 of file onion_client.h.
Referenced by path_timed_out(), and random_path().
#define ONION_PATH_TIMEOUT 10
Definition at line 44 of file onion_client.h.
Referenced by is_path_used(), and random_path().
Typedef Documentation
typedef int(* oniondata_handler_callback)(void *object, const uint8_t *source_pubkey, const uint8_t *data, uint16_t len)
Definition at line 123 of file onion_client.h.
Function Documentation
void do_onion_client (Onion_Client * onion_c)
Definition at line 1431 of file onion_client.c.
References Onion_Client::c, Onion_Client::dht, DHT_non_lan_connected(), do_announce(), do_friend(), Onion_Client::first_run, get_random_tcp_onion_conn_number(), i, is_timeout(), Onion_Client::last_run, Onion_Client::num_friends, Onion_Client::onion_connected, ONION_CONNECTION_SECONDS, onion_connection_status(), onion_isconnected(), populate_path_nodes(), populate_path_nodes_tcp(), set_tcp_onion_status(), Net_Crypto::tcp_c, Onion_Client::UDP_connected, and unix_time().
Referenced by do_messenger(), and do_onions().
{
    unsigned int i;
    if (onion_c->last_run == unix_time())
        return;
    populate_path_nodes(onion_c);
    do_announce(onion_c);
    if (onion_isconnected(onion_c)) {
        if (onion_c->onion_connected < ONION_CONNECTION_SECONDS * 2)
       {
            ++onion_c->onion_connected;
        }
    } else {
        populate_path_nodes_tcp(onion_c);
        if (onion_c->onion_connected != 0) {
            --onion_c->onion_connected;
        }
    }
    _Bool UDP_connected = DHT_non_lan_connected(onion_c->
      dht);
    if (is_timeout(onion_c->first_run,
      ONION_CONNECTION_SECONDS)) {
        set_tcp_onion_status(onion_c->c->tcp_c, !UDP_connected);
    }
    onion_c->UDP_connected = UDP_connected
                             || get_random_tcp_onion_conn_number(onion_c->
      c->tcp_c) == -1; /* Check if connected to any TCP relays. */
    if (onion_connection_status(onion_c)) {
        for (i = 0; i < onion_c->num_friends; ++i) {
            do_friend(onion_c, i);
        }
    }
    if (onion_c->last_run == 0) {
        onion_c->first_run = unix_time();
    }
    onion_c->last_run = unix_time();
}
void kill_onion_client (Onion_Client * onion_c)
Definition at line 1506 of file onion_client.c.
References Onion_Client::announce_ping_array, Onion_Client::c, CRYPTO_PACKET_DHTPK, cryptopacket_registerhandler(), Onion_Client::dht, Onion_Client::net, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, networking_registerhandler(), ONION_DATA_DHTPK, oniondata_registerhandler(), ping_array_free_all(), realloc_onion_friends(), set_onion_packet_tcp_connection_callback(), and Net_Crypto::tcp_c.
Referenced by kill_messenger(), kill_onions(), and new_messenger().
{
    if (onion_c == NULL)
        return;
    ping_array_free_all(&onion_c->announce_ping_array);
    realloc_onion_friends(onion_c, 0);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ANNOUNCE_RESPONSE, NULL, NULL);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ONION_DATA_RESPONSE, NULL, NULL);
    oniondata_registerhandler(onion_c, ONION_DATA_DHTPK, NULL,
      NULL);
    cryptopacket_registerhandler(onion_c->dht,
      CRYPTO_PACKET_DHTPK, NULL, NULL);
    set_onion_packet_tcp_connection_callback(onion_c->
      c->tcp_c, NULL, NULL);
    memset(onion_c, 0, sizeof(Onion_Client));
    free(onion_c);
}
Onion_Client* new_onion_client (Net_Crypto * c)
Definition at line 1477 of file onion_client.c.
References ANNOUNCE_ARRAY_SIZE, Onion_Client::announce_ping_array, ANNOUNCE_TIMEOUT, Onion_Client::c, CRYPTO_PACKET_DHTPK, cryptopacket_registerhandler(), Onion_Client::dht, Net_Crypto::dht, handle_announce_response(), handle_data_response(), handle_dht_dhtpk(), handle_dhtpk_announce(), handle_tcp_onion(), Onion_Client::net, DHT::net, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, networking_registerhandler(), new_symmetric_key(), ONION_DATA_DHTPK, oniondata_registerhandler(), ping_array_init(), Onion_Client::secret_symmetric_key, set_onion_packet_tcp_connection_callback(), Net_Crypto::tcp_c, Onion_Client::temp_public_key, and Onion_Client::temp_secret_key.
Referenced by new_messenger(), and new_onions().
{
    if (c == NULL)
        return NULL;
    Onion_Client *onion_c = calloc(1, sizeof(Onion_Client));
    if (onion_c == NULL)
        return NULL;
    if (ping_array_init(&onion_c->announce_ping_array,
      ANNOUNCE_ARRAY_SIZE, ANNOUNCE_TIMEOUT) != 0) {
        free(onion_c);
        return NULL;
    }
    onion_c->dht = c->dht;
    onion_c->net = c->dht->net;
    onion_c->c = c;
    new_symmetric_key(onion_c->secret_symmetric_key);
    crypto_box_keypair(onion_c->temp_public_key, onion_c->
      temp_secret_key);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ANNOUNCE_RESPONSE, &
      handle_announce_response, onion_c);
    networking_registerhandler(onion_c->net,
      NET_PACKET_ONION_DATA_RESPONSE, &
      handle_data_response, onion_c);
    oniondata_registerhandler(onion_c, ONION_DATA_DHTPK, &
      handle_dhtpk_announce, onion_c);
    cryptopacket_registerhandler(onion_c->dht,
      CRYPTO_PACKET_DHTPK, &handle_dht_dhtpk, onion_c);
    set_onion_packet_tcp_connection_callback(onion_c->
      c->tcp_c, &handle_tcp_onion, onion_c);
    return onion_c;
}
int onion_add_bs_path_node (Onion_Client * onion_c, IP_Port ip_port, const uint8_t * public_key)
Definition at line 41 of file onion_client.c.
References IP::family, i, IP_Port::ip, Node_format::ip_port, last, MAX_PATH_NODES, Onion_Client::path_nodes_bs, Onion_Client::path_nodes_index_bs, and Node_format::public_key.
Referenced by messenger_load_state_callback(), populate_path_nodes_tcp(), and tox_bootstrap().
{
    if (ip_port.ip.family != AF_INET && ip_port.ip.family != AF_INET6)
        return -1;
    unsigned int i;
    for (i = 0; i < MAX_PATH_NODES; ++i) {
        if (memcmp(public_key, onion_c->path_nodes_bs[i].
      public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return -1;
    }
    onion_c->path_nodes_bs[onion_c->path_nodes_index_bs %
      MAX_PATH_NODES].ip_port = ip_port;
    memcpy(onion_c->path_nodes_bs[onion_c->path_nodes_index_bs %
      MAX_PATH_NODES].public_key, public_key,
           crypto_box_PUBLICKEYBYTES);
    uint16_t last = onion_c->path_nodes_index_bs;
    ++onion_c->path_nodes_index_bs;
    if (onion_c->path_nodes_index_bs < last)
        onion_c->path_nodes_index_bs = MAX_PATH_NODES + 1;
    return 0;
}
int onion_addfriend (Onion_Client * onion_c, const uint8_t * public_key)
Definition at line 1010 of file onion_client.c.
References Onion_Client::friends_list, i, num, Onion_Client::num_friends, onion_friend_num(), Onion_Friend::real_public_key, realloc_onion_friends(), Onion_Friend::status, Onion_Friend::temp_public_key, and Onion_Friend::temp_secret_key.
Referenced by new_friend_connection(), and START_TEST().
{
    int num = onion_friend_num(onion_c, public_key);
    if (num != -1)
        return num;
    unsigned int i, index = ~0;
    for (i = 0; i < onion_c->num_friends; ++i) {
        if (onion_c->friends_list[i].status == 0) {
            index = i;
            break;
        }
    }
    if (index == (uint32_t)~0) {
        if (realloc_onion_friends(onion_c, onion_c->
      num_friends + 1) == -1)
            return -1;
        index = onion_c->num_friends;
        memset(&(onion_c->friends_list[onion_c->num_friends]), 0, sizeof(
      Onion_Friend));
        ++onion_c->num_friends;
    }
    onion_c->friends_list[index].status = 1;
    memcpy(onion_c->friends_list[index].real_public_key,
      public_key, crypto_box_PUBLICKEYBYTES);
    crypto_box_keypair(onion_c->friends_list[index].temp_public_key, onion_c->
      friends_list[index].temp_secret_key);
    return index;
}
uint16_t onion_backup_nodes (const Onion_Client * onion_c, Node_format * nodes, uint16_t max_num)
Definition at line 100 of file onion_client.c.
References i, MAX_PATH_NODES, Onion_Client::path_nodes, and Onion_Client::path_nodes_index.
Referenced by messenger_save().
{
    unsigned int i;
    if (!max_num)
        return 0;
    unsigned int num_nodes = (onion_c->path_nodes_index <
      MAX_PATH_NODES) ? onion_c->path_nodes_index :
      MAX_PATH_NODES;
    if (num_nodes == 0)
        return 0;
    if (num_nodes < max_num)
        max_num = num_nodes;
    for (i = 0; i < max_num; ++i) {
        nodes[i] = onion_c->path_nodes[(onion_c->path_nodes_index - (1 +
      i)) % num_nodes];
    }
    return max_num;
}
unsigned int onion_connection_status (const Onion_Client * onion_c)
Definition at line 1418 of file onion_client.c.
References Onion_Client::onion_connected, ONION_CONNECTION_SECONDS, and Onion_Client::UDP_connected.
Referenced by connection_status_cb(), do_onion_client(), and tox_self_get_connection_status().
{
    if (onion_c->onion_connected >= ONION_CONNECTION_SECONDS) {
        if (onion_c->UDP_connected) {
            return 2;
        } else {
            return 1;
        }
    }
    return 0;
}
int onion_delfriend (Onion_Client * onion_c, int friend_num)
Definition at line 1046 of file onion_client.c.
References Onion_Client::friends_list, i, Onion_Client::num_friends, realloc_onion_friends(), and Onion_Friend::status.
Referenced by kill_friend_connection().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    //if (onion_c->friends_list[friend_num].know_dht_public_key)
    // DHT_delfriend(onion_c->dht, onion_c->friends_list[friend_num].dht_public_key, 0);
    memset(&(onion_c->friends_list[friend_num]), 0, sizeof(
      Onion_Friend));
    unsigned int i;
    for (i = onion_c->num_friends; i != 0; --i) {
        if (onion_c->friends_list[i - 1].status != 0)
            break;
    }
    if (onion_c->num_friends != i) {
        onion_c->num_friends = i;
        realloc_onion_friends(onion_c, onion_c->num_friends);
    }
    return friend_num;
}
int onion_dht_pk_callback (Onion_Client * onion_c, int friend_num, void(*)(void *data, int32_t number, const uint8_t *dht_public_key) function, void * object, uint32_t number)
Definition at line 1098 of file onion_client.c.
References Onion_Friend::dht_pk_callback, Onion_Friend::dht_pk_callback_number, Onion_Friend::dht_pk_callback_object, Onion_Client::friends_list, and Onion_Client::num_friends.
Referenced by new_friend_connection(), and START_TEST().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    onion_c->friends_list[friend_num].dht_pk_callback = function;
    onion_c->friends_list[friend_num].dht_pk_callback_object = object;
    onion_c->friends_list[friend_num].dht_pk_callback_number = number;
    return 0;
}
int onion_friend_num (const Onion_Client * onion_c, const uint8_t * public_key)
Definition at line 968 of file onion_client.c.
References Onion_Client::friends_list, i, Onion_Client::num_friends, Onion_Friend::real_public_key, and Onion_Friend::status.
Referenced by handle_dhtpk_announce(), and onion_addfriend().
{
    unsigned int i;
    for (i = 0; i < onion_c->num_friends; ++i) {
        if (onion_c->friends_list[i].status == 0)
            continue;
        if (memcmp(public_key, onion_c->friends_list[i].
      real_public_key, crypto_box_PUBLICKEYBYTES) == 0)
            return i;
    }
    return -1;
}
unsigned int onion_getfriend_DHT_pubkey (const Onion_Client * onion_c, int friend_num, uint8_t * dht_key)
Definition at line 1143 of file onion_client.c.
References Onion_Friend::dht_public_key, Onion_Client::friends_list, Onion_Friend::know_dht_public_key, Onion_Client::num_friends, and Onion_Friend::status.
Referenced by onion_getfriendip().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return 0;
    if (onion_c->friends_list[friend_num].status == 0)
        return 0;
    if (!onion_c->friends_list[friend_num].know_dht_public_key)
        return 0;
    memcpy(dht_key, onion_c->friends_list[friend_num].dht_public_key,
      crypto_box_PUBLICKEYBYTES);
    return 1;
}
int onion_getfriendip (const Onion_Client * onion_c, int friend_num, IP_Port * ip_port)
Definition at line 1165 of file onion_client.c.
References Onion_Client::dht, DHT_getfriendip(), and onion_getfriend_DHT_pubkey().
Referenced by START_TEST().
{
    uint8_t dht_public_key[crypto_box_PUBLICKEYBYTES];
    if (onion_getfriend_DHT_pubkey(onion_c, friend_num, dht_public_key) == 0)
        return -1;
    return DHT_getfriendip(onion_c->dht, dht_public_key, ip_port);
}
int onion_set_friend_DHT_pubkey (Onion_Client * onion_c, int friend_num, const uint8_t * dht_key)
Definition at line 1115 of file onion_client.c.
References Onion_Friend::dht_public_key, Onion_Client::friends_list, Onion_Friend::know_dht_public_key, Onion_Friend::last_seen, Onion_Client::num_friends, Onion_Friend::status, and unix_time().
Referenced by dht_pk_callback(), and handle_dhtpk_announce().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (onion_c->friends_list[friend_num].status == 0)
        return -1;
    if (onion_c->friends_list[friend_num].know_dht_public_key) {
        if (memcmp(dht_key, onion_c->friends_list[friend_num].
      dht_public_key, crypto_box_PUBLICKEYBYTES) == 0) {
            return -1;
        }
        onion_c->friends_list[friend_num].know_dht_public_key = 0;
    }
    onion_c->friends_list[friend_num].last_seen = unix_time();
    onion_c->friends_list[friend_num].know_dht_public_key = 1;
    memcpy(onion_c->friends_list[friend_num].dht_public_key, dht_key,
      crypto_box_PUBLICKEYBYTES);
    return 0;
}
int onion_set_friend_online (Onion_Client * onion_c, int friend_num, uint8_t is_online)
Definition at line 1185 of file onion_client.c.
References Onion_Client::friends_list, Onion_Friend::is_online, Onion_Friend::last_noreplay, Onion_Friend::last_seen, Onion_Client::num_friends, Onion_Friend::run_count, and unix_time().
Referenced by handle_status().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (is_online == 0 && onion_c->friends_list[friend_num].
      is_online == 1)
        onion_c->friends_list[friend_num].last_seen =
      unix_time();
    onion_c->friends_list[friend_num].is_online = is_online;
    /* This should prevent some clock related issues */
    if (!is_online) {
        onion_c->friends_list[friend_num].last_noreplay = 0;
        onion_c->friends_list[friend_num].run_count = 0;
    }
    return 0;
}
void oniondata_registerhandler (Onion_Client * onion_c, uint8_t byte, oniondata_handler_callback cb, void * object)
Definition at line 1310 of file onion_client.c.
References Onion_Client::function, Onion_Client::object, and Onion_Client::Onion_Data_Handlers.
Referenced by kill_onion_client(), new_onion_client(), and set_friend_request_callback().
{
    onion_c->Onion_Data_Handlers[byte].function = cb;
    onion_c->Onion_Data_Handlers[byte].object = object;
}
int recv_tcp_relay_handler (Onion_Client * onion_c, int friend_num, int(*)(void *object, uint32_t number, IP_Port ip_port, const uint8_t *public_key) tcp_relay_node_callback, void * object, uint32_t number)
Definition at line 1078 of file onion_client.c.
References Onion_Client::friends_list, Onion_Client::num_friends, Onion_Friend::tcp_relay_node_callback, tcp_relay_node_callback(), Onion_Friend::tcp_relay_node_callback_number, and Onion_Friend::tcp_relay_node_callback_object.
Referenced by new_friend_connection().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    onion_c->friends_list[friend_num].tcp_relay_node_callback =
      tcp_relay_node_callback;
    onion_c->friends_list[friend_num].tcp_relay_node_callback_object
       = object;
    onion_c->friends_list[friend_num].tcp_relay_node_callback_number
       = number;
    return 0;
}
int send_onion_data (Onion_Client * onion_c, int friend_num, const uint8_t * data, uint16_t length)
Definition at line 789 of file onion_client.c.
References Onion_Client::c, Onion_Friend::clients_list, create_data_request(), DATA_IN_RESPONSE_MIN_SIZE, Onion_Node::data_public_key, encrypt_data(), Onion_Client::friends_list, i, is_timeout(), MAX_DATA_REQUEST_SIZE, MAX_ONION_CLIENTS, nonce, Onion_Client::num_friends, ONION_MAX_PACKET_SIZE, ONION_NODE_TIMEOUT, Onion_Client::onion_paths_friends, path, random_nonce(), random_path(), Onion_Friend::real_public_key, Net_Crypto::self_public_key, Net_Crypto::self_secret_key, and send_onion_packet_tcp_udp().
Referenced by send_dhtpk_announce(), and send_friend_request_packet().
{
    if ((uint32_t)friend_num >= onion_c->num_friends)
        return -1;
    if (length + DATA_IN_RESPONSE_MIN_SIZE >
      MAX_DATA_REQUEST_SIZE)
        return -1;
    if (length == 0)
        return -1;
    unsigned int i, good_nodes[MAX_ONION_CLIENTS], num_good = 0, num_nodes = 0;
    Onion_Node *list_nodes = onion_c->friends_list[friend_num].
      clients_list;
    for (i = 0; i < MAX_ONION_CLIENTS; ++i) {
        if (is_timeout(list_nodes[i].timestamp, ONION_NODE_TIMEOUT))
            continue;
        ++num_nodes;
        if (list_nodes[i].is_stored) {
            good_nodes[num_good] = i;
            ++num_good;
        }
    }
    if (num_good < (num_nodes / 4) + 1)
        return -1;
    uint8_t nonce[crypto_box_NONCEBYTES];
    random_nonce(nonce);
    uint8_t packet[DATA_IN_RESPONSE_MIN_SIZE + length];
    memcpy(packet, onion_c->c->self_public_key, crypto_box_PUBLICKEYBYTES);
    int len = encrypt_data(onion_c->friends_list[friend_num].
      real_public_key, onion_c->c->self_secret_key, nonce,
      data,
                           length, packet + crypto_box_PUBLICKEYBYTES);
    if ((uint32_t)len + crypto_box_PUBLICKEYBYTES != sizeof(packet))
        return -1;
    unsigned int good = 0;
    for (i = 0; i < num_good; ++i) {
        Onion_Path path;
        if (random_path(onion_c, &onion_c->onion_paths_friends, ~0, &path) ==
       -1)
            continue;
        uint8_t o_packet[ONION_MAX_PACKET_SIZE];
        len = create_data_request(o_packet, sizeof(o_packet), onion_c->
      friends_list[friend_num].real_public_key,
                                  list_nodes[good_nodes[i]].data_public_key, nonce, packet,
      sizeof(packet));
        if (len == -1)
            continue;
        if (send_onion_packet_tcp_udp(onion_c, &path, list_nodes[good_nodes[i]].
      ip_port, o_packet, len) == 0)
            ++good;
    }
    return good;
}