toxcore/friend_requests.c File Reference
#include `friend_requests.h`
*
#include `util.h`
*
Functions
void set_nospam (Friend_Requests *fr, uint32_t num)
uint32_t get_nospam (const Friend_Requests *fr)
void callback_friendrequest (Friend_Requests *fr, void(*function)(void *, const uint8_t *, const uint8_t *, size_t, void *), void *object, void *userdata)
void set_filter_function (Friend_Requests *fr, int(*function)(const uint8_t *, void *), void *userdata)
static void addto_receivedlist (Friend_Requests *fr, const uint8_t *real_pk)
static int request_received (Friend_Requests *fr, const uint8_t *real_pk)
int remove_request_received (Friend_Requests *fr, const uint8_t *real_pk)
static int friendreq_handlepacket (void *object, const uint8_t *source_pubkey, const uint8_t *packet, uint16_t length)
void friendreq_init (Friend_Requests *fr, Friend_Connections *fr_c)
Function Documentation
static void addto_receivedlist (Friend_Requests * fr, const uint8_t * real_pk) [static]
Definition at line 61 of file friend_requests.c.
References id_copy(), MAX_RECEIVED_STORED, Friend_Requests::received_requests, and Friend_Requests::received_requests_index.
Referenced by friendreq_handlepacket().
{
    if (fr->received_requests_index >=
      MAX_RECEIVED_STORED)
        fr->received_requests_index = 0;
    id_copy(fr->received_requests[fr->
      received_requests_index], real_pk);
    ++fr->received_requests_index;
}
void callback_friendrequest (Friend_Requests * fr, void(*)(void *, const uint8_t *, const uint8_t *, size_t, void *) function, void * object, void * userdata)
Definition at line 45 of file friend_requests.c.
References Friend_Requests::handle_friendrequest, Friend_Requests::handle_friendrequest_isset, Friend_Requests::handle_friendrequest_object, and Friend_Requests::handle_friendrequest_userdata.
Referenced by m_callback_friendrequest().
{
    fr->handle_friendrequest = function;
    fr->handle_friendrequest_isset = 1;
    fr->handle_friendrequest_object = object;
    fr->handle_friendrequest_userdata = userdata;
}
static int friendreq_handlepacket (void * object, const uint8_t * source_pubkey, const uint8_t * packet, uint16_t length) [static]
Definition at line 106 of file friend_requests.c.
References addto_receivedlist(), Friend_Requests::filter_function, Friend_Requests::filter_function_userdata, Friend_Requests::handle_friendrequest, Friend_Requests::handle_friendrequest_isset, Friend_Requests::handle_friendrequest_object, Friend_Requests::handle_friendrequest_userdata, Friend_Requests::nospam, ONION_CLIENT_MAX_DATA_SIZE, and request_received().
Referenced by friendreq_init().
{
    Friend_Requests *fr = object;
    if (length <= 1 + sizeof(fr->nospam) || length >
      ONION_CLIENT_MAX_DATA_SIZE)
        return 1;
    ++packet;
    --length;
    if (fr->handle_friendrequest_isset == 0)
        return 1;
    if (request_received(fr, source_pubkey))
        return 1;
    if (memcmp(packet, &fr->nospam, sizeof(fr->nospam)) != 0)
        return 1;
    if (fr->filter_function)
        if ((*fr->filter_function)(source_pubkey, fr->
      filter_function_userdata) != 0)
            return 1;
    addto_receivedlist(fr, source_pubkey);
    uint32_t message_len = length - sizeof(fr->nospam);
    uint8_t message[message_len + 1];
    memcpy(message, packet + sizeof(fr->nospam), message_len);
    message[sizeof(message) - 1] = 0; /* Be sure the message is null terminated. */
    (*fr->handle_friendrequest)(fr->
      handle_friendrequest_object, source_pubkey, message, message_len,
                                fr->handle_friendrequest_userdata);
    return 0;
}
void friendreq_init (Friend_Requests * fr, Friend_Connections * fr_c)
Definition at line 141 of file friend_requests.c.
References friendreq_handlepacket(), and set_friend_request_callback().
Referenced by new_messenger().
{
    set_friend_request_callback(fr_c, &
      friendreq_handlepacket, fr);
}
uint32_t get_nospam (const Friend_Requests * fr)
Definition at line 38 of file friend_requests.c.
References Friend_Requests::nospam.
Referenced by getaddress(), messenger_save(), and tox_self_get_nospam().
{
    return fr->nospam;
}
int remove_request_received (Friend_Requests * fr, const uint8_t * real_pk)
Definition at line 91 of file friend_requests.c.
References i, id_equal(), MAX_RECEIVED_STORED, and Friend_Requests::received_requests.
Referenced by m_delfriend().
{
    uint32_t i;
    for (i = 0; i < MAX_RECEIVED_STORED; ++i) {
        if (id_equal(fr->received_requests[i], real_pk)) {
            memset(fr->received_requests[i], 0, crypto_box_PUBLICKEYBYTES);
            return 0;
        }
    }
    return -1;
}
static int request_received (Friend_Requests * fr, const uint8_t * real_pk) [static]
Definition at line 75 of file friend_requests.c.
References i, id_equal(), MAX_RECEIVED_STORED, and Friend_Requests::received_requests.
Referenced by friendreq_handlepacket().
{
    uint32_t i;
    for (i = 0; i < MAX_RECEIVED_STORED; ++i)
        if (id_equal(fr->received_requests[i], real_pk))
            return 1;
    return 0;
}
void set_filter_function (Friend_Requests * fr, int(*)(const uint8_t *, void *) function, void * userdata)
Definition at line 54 of file friend_requests.c.
References Friend_Requests::filter_function, and Friend_Requests::filter_function_userdata.
Referenced by new_messenger().
{
    fr->filter_function = function;
    fr->filter_function_userdata = userdata;
}
void set_nospam (Friend_Requests * fr, uint32_t num)
Definition at line 33 of file friend_requests.c.
References Friend_Requests::nospam, and num.
Referenced by messenger_load_state_callback(), new_messenger(), and tox_self_set_nospam().
{
    fr->nospam = num;
}