toxcore/Messenger.c File Reference
#include `logger.h`
*
#include `Messenger.h`
*
#include `assoc.h`
*
#include `network.h`
*
#include `util.h`
*
Data Structures
struct SAVED_FRIEND
Macros
#define MAX_FILENAME_LENGTH 255
#define MAX_FILE_DATA_SIZE (MAX_CRYPTO_DATA_SIZE - 2)
#define MIN_SLOTS_FREE (CRYPTO_MIN_QUEUE_LENGTH / 4)
#define MIN_RUN_INTERVAL 50
#define MESSENGER_STATE_COOKIE_GLOBAL 0x15ed1b1f
#define MESSENGER_STATE_COOKIE_TYPE 0x01ce
#define MESSENGER_STATE_TYPE_NOSPAMKEYS 1
#define MESSENGER_STATE_TYPE_DHT 2
#define MESSENGER_STATE_TYPE_FRIENDS 3
#define MESSENGER_STATE_TYPE_NAME 4
#define MESSENGER_STATE_TYPE_STATUSMESSAGE 5
#define MESSENGER_STATE_TYPE_STATUS 6
#define MESSENGER_STATE_TYPE_TCP_RELAY 10
#define MESSENGER_STATE_TYPE_PATH_NODE 11
#define MESSENGER_STATE_TYPE_END 255
#define SAVED_FRIEND_REQUEST_SIZE 1024
#define NUM_SAVED_PATH_NODES 8
Functions
static void set_friend_status (Messenger *m, int32_t friendnumber, uint8_t status)
static int write_cryptpacket_id (const Messenger *m, int32_t friendnumber, uint8_t packet_id, const uint8_t *data, uint32_t length, uint8_t congestion_control)
static uint8_t friend_not_valid (const Messenger *m, int32_t friendnumber)
int realloc_friendlist (Messenger *m, uint32_t num)
int32_t getfriend_id (const Messenger *m, const uint8_t *real_pk)
int get_real_pk (const Messenger *m, int32_t friendnumber, uint8_t *real_pk)
int getfriendcon_id (const Messenger *m, int32_t friendnumber)
static uint16_t address_checksum (const uint8_t *address, uint32_t len)
void getaddress (const Messenger *m, uint8_t *address)
static int send_online_packet (Messenger *m, int32_t friendnumber)
static int send_offline_packet (Messenger *m, int friendcon_id)
static int handle_status (void *object, int i, uint8_t status)
static int handle_packet (void *object, int i, uint8_t *temp, uint16_t len)
static int handle_custom_lossy_packet (void *object, int friend_num, const uint8_t *packet, uint16_t length)
static int32_t init_new_friend (Messenger *m, const uint8_t *real_pk, uint8_t status)
int32_t m_addfriend (Messenger *m, const uint8_t *address, const uint8_t *data, uint16_t length)
int32_t m_addfriend_norequest (Messenger *m, const uint8_t *real_pk)
static int clear_receipts (Messenger *m, int32_t friendnumber)
static int add_receipt (Messenger *m, int32_t friendnumber, uint32_t packet_num, uint32_t msg_id)
static int friend_received_packet (const Messenger *m, int32_t friendnumber, uint32_t number)
static int do_receipts (Messenger *m, int32_t friendnumber)
int m_delfriend (Messenger *m, int32_t friendnumber)
int m_get_friend_connectionstatus (const Messenger *m, int32_t friendnumber)
int m_friend_exists (const Messenger *m, int32_t friendnumber)
int m_send_message_generic (Messenger *m, int32_t friendnumber, uint8_t type, const uint8_t *message, uint32_t length, uint32_t *message_id)
static int m_sendname (const Messenger *m, int32_t friendnumber, const uint8_t *name, uint16_t length)
int setfriendname (Messenger *m, int32_t friendnumber, const uint8_t *name, uint16_t length)
int setname (Messenger *m, const uint8_t *name, uint16_t length)
uint16_t getself_name (const Messenger *m, uint8_t *name)
int getname (const Messenger *m, int32_t friendnumber, uint8_t *name)
int m_get_name_size (const Messenger *m, int32_t friendnumber)
int m_get_self_name_size (const Messenger *m)
int m_set_statusmessage (Messenger *m, const uint8_t *status, uint16_t length)
int m_set_userstatus (Messenger *m, uint8_t status)
int m_get_statusmessage_size (const Messenger *m, int32_t friendnumber)
int m_copy_statusmessage (const Messenger *m, int32_t friendnumber, uint8_t *buf, uint32_t maxlen)
int m_get_self_statusmessage_size (const Messenger *m)
int m_copy_self_statusmessage (const Messenger *m, uint8_t *buf)
uint8_t m_get_userstatus (const Messenger *m, int32_t friendnumber)
uint8_t m_get_self_userstatus (const Messenger *m)
uint64_t m_get_last_online (const Messenger *m, int32_t friendnumber)
int m_set_usertyping (Messenger *m, int32_t friendnumber, uint8_t is_typing)
int m_get_istyping (const Messenger *m, int32_t friendnumber)
static int send_statusmessage (const Messenger *m, int32_t friendnumber, const uint8_t *status, uint16_t length)
static int send_userstatus (const Messenger *m, int32_t friendnumber, uint8_t status)
static int send_user_istyping (const Messenger *m, int32_t friendnumber, uint8_t is_typing)
static int set_friend_statusmessage (const Messenger *m, int32_t friendnumber, const uint8_t *status, uint16_t length)
static void set_friend_userstatus (const Messenger *m, int32_t friendnumber, uint8_t status)
static void set_friend_typing (const Messenger *m, int32_t friendnumber, uint8_t is_typing)
void m_callback_friendrequest (Messenger *m, void(*function)(Messenger *m, const uint8_t *, const uint8_t *, size_t, void *), void *userdata)
void m_callback_friendmessage (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, const uint8_t *, size_t, void *), void *userdata)
void m_callback_namechange (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, size_t, void *), void *userdata)
void m_callback_statusmessage (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, size_t, void *), void *userdata)
void m_callback_userstatus (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, void *), void *userdata)
void m_callback_typingchange (Messenger *m, void(*function)(Messenger *m, uint32_t, _Bool, void *), void *userdata)
void m_callback_read_receipt (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, void *), void *userdata)
void m_callback_connectionstatus (Messenger *m, void(*function)(Messenger *m, uint32_t, unsigned int, void *), void *userdata)
void m_callback_core_connection (Messenger *m, void(*function)(Messenger *m, unsigned int, void *), void *userdata)
void m_callback_connectionstatus_internal_av (Messenger *m, void(*function)(Messenger *m, uint32_t, uint8_t, void *), void *userdata)
static void check_friend_tcp_udp (Messenger *m, int32_t friendnumber)
static void break_files (const Messenger *m, int32_t friendnumber)
static void check_friend_connectionstatus (Messenger *m, int32_t friendnumber, uint8_t status)
void m_callback_group_invite (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, uint16_t))
int send_group_invite_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint16_t length)
void callback_file_sendrequest (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *), void *userdata)
void callback_file_control (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, unsigned int, void *), void *userdata)
void callback_file_data (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *), void *userdata)
void callback_file_reqchunk (Messenger *m, void(*function)(Messenger *m, uint32_t, uint32_t, uint64_t, size_t, void *), void *userdata)
int file_get_id (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint8_t *file_id)
static int file_sendrequest (const Messenger *m, int32_t friendnumber, uint8_t filenumber, uint32_t file_type, uint64_t filesize, const uint8_t *file_id, const uint8_t *filename, uint16_t filename_length)
long int new_filesender (const Messenger *m, int32_t friendnumber, uint32_t file_type, uint64_t filesize, const uint8_t *file_id, const uint8_t *filename, uint16_t filename_length)
int send_file_control_packet (const Messenger *m, int32_t friendnumber, uint8_t send_receive, uint8_t filenumber, uint8_t control_type, uint8_t *data, uint16_t data_length)
int file_control (const Messenger *m, int32_t friendnumber, uint32_t filenumber, unsigned int control)
int file_seek (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint64_t position)
static int64_t send_file_data_packet (const Messenger *m, int32_t friendnumber, uint8_t filenumber, const uint8_t *data, uint16_t length)
int file_data (const Messenger *m, int32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t *data, uint16_t length)
uint64_t file_dataremaining (const Messenger *m, int32_t friendnumber, uint8_t filenumber, uint8_t send_receive)
static void do_reqchunk_filecb (Messenger *m, int32_t friendnumber)
static int handle_filecontrol (Messenger *m, int32_t friendnumber, uint8_t receive_send, uint8_t filenumber, uint8_t control_type, uint8_t *data, uint16_t length)
void m_callback_msi_packet (Messenger *m, void(*function)(Messenger *m, uint32_t, const uint8_t *, uint16_t, void *), void *userdata)
int m_msi_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint16_t length)
void custom_lossy_packet_registerhandler (Messenger *m, void(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object), void *object)
int m_callback_rtp_packet (Messenger *m, int32_t friendnumber, uint8_t byte, int(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t len, void *object), void *object)
int send_custom_lossy_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint32_t length)
static int handle_custom_lossless_packet (void *object, int friend_num, const uint8_t *packet, uint16_t length)
void custom_lossless_packet_registerhandler (Messenger *m, void(*packet_handler_callback)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object), void *object)
int send_custom_lossless_packet (const Messenger *m, int32_t friendnumber, const uint8_t *data, uint32_t length)
static int friend_already_added (const uint8_t *real_pk, void *data)
Messenger * new_messenger (Messenger_Options *options, unsigned int *error)
void kill_messenger (Messenger *m)
static void check_friend_request_timed_out (Messenger *m, uint32_t i, uint64_t t)
void do_friends (Messenger *m)
static void connection_status_cb (Messenger *m)
uint32_t messenger_run_interval (const Messenger *m)
void do_messenger (Messenger *m)
static uint32_t saved_friendslist_size (const Messenger *m)
static uint32_t friends_list_save (const Messenger *m, uint8_t *data)
static int friends_list_load (Messenger *m, const uint8_t *data, uint32_t length)
uint32_t messenger_size (const Messenger *m)
static uint8_t * z_state_save_subheader (uint8_t *data, uint32_t len, uint16_t type)
void messenger_save (const Messenger *m, uint8_t *data)
static int messenger_load_state_callback (void *outer, const uint8_t *data, uint32_t length, uint16_t type)
int messenger_load (Messenger *m, const uint8_t *data, uint32_t length)
uint32_t count_friendlist (const Messenger *m)
uint32_t copy_friendlist (Messenger const *m, uint32_t *out_list, uint32_t list_size)
Macro Definition Documentation
#define MAX_FILE_DATA_SIZE (MAX_CRYPTO_DATA_SIZE - 2)
Definition at line 1305 of file Messenger.c.
Referenced by do_reqchunk_filecb(), file_data(), and handle_packet().
#define MAX_FILENAME_LENGTH 255
Definition at line 985 of file Messenger.c.
Referenced by file_sendrequest(), handle_packet(), and new_filesender().
#define MESSENGER_STATE_COOKIE_GLOBAL 0x15ed1b1f
Definition at line 2423 of file Messenger.c.
Referenced by messenger_load(), and messenger_save().
#define MESSENGER_STATE_COOKIE_TYPE 0x01ce
Definition at line 2425 of file Messenger.c.
Referenced by messenger_load(), and z_state_save_subheader().
#define MESSENGER_STATE_TYPE_DHT 2
Definition at line 2427 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_END 255
Definition at line 2434 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_FRIENDS 3
Definition at line 2428 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_NAME 4
Definition at line 2429 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_NOSPAMKEYS 1
Definition at line 2426 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_PATH_NODE 11
Definition at line 2433 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_STATUS 6
Definition at line 2431 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_STATUSMESSAGE 5
Definition at line 2430 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MESSENGER_STATE_TYPE_TCP_RELAY 10
Definition at line 2432 of file Messenger.c.
Referenced by messenger_load_state_callback(), and messenger_save().
#define MIN_RUN_INTERVAL 50
Definition at line 2261 of file Messenger.c.
Referenced by messenger_run_interval().
#define MIN_SLOTS_FREE (CRYPTO_MIN_QUEUE_LENGTH / 4)
Definition at line 1306 of file Messenger.c.
Referenced by do_reqchunk_filecb(), and file_data().
#define NUM_SAVED_PATH_NODES 8
Definition at line 2437 of file Messenger.c.
Referenced by messenger_load_state_callback(), messenger_save(), and messenger_size().
#define SAVED_FRIEND_REQUEST_SIZE 1024
Definition at line 2436 of file Messenger.c.
Referenced by friends_list_save().
Function Documentation
static int add_receipt (Messenger * m, int32_t friendnumber, uint32_t packet_num, uint32_t msg_id) [static]
Definition at line 311 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Receipts::msg_id, Receipts::next, Receipts::packet_num, Friend::receipts_end, and Friend::receipts_start.
Referenced by m_send_message_generic().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    struct Receipts *new = calloc(1, sizeof(struct Receipts));
    if (!new)
        return -1;
    new->packet_num = packet_num;
    new->msg_id = msg_id;
    if (!m->friendlist[friendnumber].receipts_start) {
        m->friendlist[friendnumber].receipts_start = new;
    } else {
        m->friendlist[friendnumber].receipts_end->next = new;
    }
    m->friendlist[friendnumber].receipts_end = new;
    new->next = NULL;
    return 0;
}
static uint16_t address_checksum (const uint8_t * address, uint32_t len) [static]
Definition at line 121 of file Messenger.c.
References i.
Referenced by friends_list_load(), getaddress(), and m_addfriend().
{
    uint8_t checksum[2] = {0};
    uint16_t check;
    uint32_t i;
    for (i = 0; i < len; ++i)
        checksum[i % 2] ^= address[i];
    memcpy(&check, checksum, sizeof(check));
    return check;
}
static void break_files (const Messenger * m, int32_t friendnumber) [static]
Definition at line 1490 of file Messenger.c.
References Friend::file_receiving, Friend::file_sending, FILESTATUS_NONE, Messenger::friendlist, i, MAX_CONCURRENT_FILE_PIPES, and File_Transfers::status.
Referenced by check_friend_connectionstatus().
{
    uint32_t i;
    //TODO: Inform the client which file transfers get killed with a callback?
    for (i = 0; i < MAX_CONCURRENT_FILE_PIPES; ++i) {
        if (m->friendlist[friendnumber].file_sending[i].
      status != FILESTATUS_NONE)
            m->friendlist[friendnumber].file_sending[i].
      status = FILESTATUS_NONE;
        if (m->friendlist[friendnumber].file_receiving[i].
      status != FILESTATUS_NONE)
            m->friendlist[friendnumber].file_receiving[i].
      status = FILESTATUS_NONE;
    }
}
void callback_file_control (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 954 of file Messenger.c.
References Messenger::file_filecontrol, and Messenger::file_filecontrol_userdata.
Referenced by tox_callback_file_recv_control().
{
    m->file_filecontrol = function;
    m->file_filecontrol_userdata = userdata;
}
void callback_file_data (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 966 of file Messenger.c.
References Messenger::file_filedata, and Messenger::file_filedata_userdata.
Referenced by tox_callback_file_recv_chunk().
{
    m->file_filedata = function;
    m->file_filedata_userdata = userdata;
}
void callback_file_reqchunk (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint64_t, size_t, void *) function, void * userdata)
Definition at line 978 of file Messenger.c.
References Messenger::file_reqchunk, and Messenger::file_reqchunk_userdata.
Referenced by tox_callback_file_chunk_request().
{
    m->file_reqchunk = function;
    m->file_reqchunk_userdata = userdata;
}
void callback_file_sendrequest (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, uint32_t, uint64_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 942 of file Messenger.c.
References Messenger::file_sendrequest, and Messenger::file_sendrequest_userdata.
Referenced by tox_callback_file_recv().
{
    m->file_sendrequest = function;
    m->file_sendrequest_userdata = userdata;
}
static void check_friend_connectionstatus (Messenger * m, int32_t friendnumber, uint8_t status) [static]
Definition at line 858 of file Messenger.c.
References break_files(), check_friend_tcp_udp(), clear_receipts(), Messenger::friend_connectionstatuschange_internal, Messenger::friend_connectionstatuschange_internal_userdata, FRIEND_ONLINE, Messenger::friendlist, Friend::name_sent, NOFRIEND, Friend::status, Friend::statusmessage_sent, Friend::user_istyping_sent, and Friend::userstatus_sent.
Referenced by set_friend_status().
{
    if (status == NOFRIEND)
        return;
    const uint8_t was_online = m->friendlist[friendnumber].status ==
      FRIEND_ONLINE;
    const uint8_t is_online = status == FRIEND_ONLINE;
    if (is_online != was_online) {
        if (was_online) {
            break_files(m, friendnumber);
            clear_receipts(m, friendnumber);
        } else {
            m->friendlist[friendnumber].name_sent = 0;
            m->friendlist[friendnumber].userstatus_sent = 0;
            m->friendlist[friendnumber].statusmessage_sent = 0;
            m->friendlist[friendnumber].user_istyping_sent = 0;
        }
        m->friendlist[friendnumber].status = status;
        check_friend_tcp_udp(m, friendnumber);
        if (m->friend_connectionstatuschange_internal)
            m->friend_connectionstatuschange_internal(m, friendnumber
      , is_online,
                    m->friend_connectionstatuschange_internal_userdata
      );
    }
}
static void check_friend_request_timed_out (Messenger * m, uint32_t i, uint64_t t) [static]
Definition at line 1880 of file Messenger.c.
References FRIEND_ADDED, Messenger::friendlist, Friend::friendrequest_lastsent, Friend::friendrequest_timeout, i, and set_friend_status().
Referenced by do_friends().
{
    Friend *f = &m->friendlist[i];
    if (f->friendrequest_lastsent + f->
      friendrequest_timeout < t) {
        set_friend_status(m, i, FRIEND_ADDED);
        /* Double the default timeout every time if friendrequest is assumed
         * to have been sent unsuccessfully.
         */
        f->friendrequest_timeout *= 2;
    }
}
static void check_friend_tcp_udp (Messenger * m, int32_t friendnumber) [static]
Definition at line 832 of file Messenger.c.
References CONNECTION_TCP, CONNECTION_UDP, CONNECTION_UNKNOWN, Messenger::friend_connectionstatuschange, Messenger::friend_connectionstatuschange_userdata, Messenger::friendlist, Friend::last_connection_udp_tcp, and m_get_friend_connectionstatus().
Referenced by check_friend_connectionstatus(), and do_friends().
{
    int last_connection_udp_tcp = m->friendlist[friendnumber].
      last_connection_udp_tcp;
    int ret = m_get_friend_connectionstatus(m, friendnumber);
    if (ret == -1)
        return;
    if (ret == CONNECTION_UNKNOWN) {
        if (last_connection_udp_tcp == CONNECTION_UDP) {
            return;
        } else {
            ret = CONNECTION_TCP;
        }
    }
    if (last_connection_udp_tcp != ret) {
        if (m->friend_connectionstatuschange)
            m->friend_connectionstatuschange(m, friendnumber, ret, m->
      friend_connectionstatuschange_userdata);
    }
    m->friendlist[friendnumber].last_connection_udp_tcp = ret;
}
static int clear_receipts (Messenger * m, int32_t friendnumber) [static]
Definition at line 293 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Receipts::next, Friend::receipts_end, and Friend::receipts_start.
Referenced by check_friend_connectionstatus(), kill_messenger(), and m_delfriend().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    struct Receipts *receipts = m->friendlist[friendnumber].
      receipts_start;
    while (receipts) {
        struct Receipts *temp_r = receipts->next;
        free(receipts);
        receipts = temp_r;
    }
    m->friendlist[friendnumber].receipts_start = NULL;
    m->friendlist[friendnumber].receipts_end = NULL;
    return 0;
}
static void connection_status_cb (Messenger * m) [static]
Definition at line 2230 of file Messenger.c.
References Messenger::core_connection_change, Messenger::core_connection_change_userdata, Messenger::last_connection_status, Messenger::onion_c, and onion_connection_status().
Referenced by do_messenger().
{
    unsigned int conn_status = onion_connection_status(m->
      onion_c);
    if (conn_status != m->last_connection_status) {
        if (m->core_connection_change)
            (*m->core_connection_change)(m, conn_status, m->
      core_connection_change_userdata);
        m->last_connection_status = conn_status;
    }
}
uint32_t copy_friendlist (Messenger const * m, uint32_t * out_list, uint32_t list_size)
Definition at line 2784 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, and Friend::status.
Referenced by tox_self_get_friend_list().
{
    if (!out_list)
        return 0;
    if (m->numfriends == 0) {
        return 0;
    }
    uint32_t i;
    uint32_t ret = 0;
    for (i = 0; i < m->numfriends; i++) {
        if (ret >= list_size) {
            break; /* Abandon ship */
        }
        if (m->friendlist[i].status > 0) {
            out_list[ret] = i;
            ret++;
        }
    }
    return ret;
}
uint32_t count_friendlist (const Messenger * m)
Definition at line 2765 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, and Friend::status.
Referenced by saved_friendslist_size(), and tox_self_get_friend_list_size().
{
    uint32_t ret = 0;
    uint32_t i;
    for (i = 0; i < m->numfriends; i++) {
        if (m->friendlist[i].status > 0) {
            ret++;
        }
    }
    return ret;
}
void custom_lossless_packet_registerhandler (Messenger * m, void(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object) packet_handler_callback, void * object)
Definition at line 1707 of file Messenger.c.
References Messenger::lossless_packethandler, and Messenger::lossless_packethandler_userdata.
Referenced by tox_callback_friend_lossless_packet().
{
    m->lossless_packethandler = packet_handler_callback;
    m->lossless_packethandler_userdata = object;
}
void custom_lossy_packet_registerhandler (Messenger * m, void(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, size_t len, void *object) packet_handler_callback, void * object)
Definition at line 1637 of file Messenger.c.
References Messenger::lossy_packethandler, and Messenger::lossy_packethandler_userdata.
Referenced by tox_callback_friend_lossy_packet().
{
    m->lossy_packethandler = packet_handler_callback;
    m->lossy_packethandler_userdata = object;
}
void do_friends (Messenger * m)
Definition at line 2173 of file Messenger.c.
References check_friend_request_timed_out(), check_friend_tcp_udp(), do_receipts(), do_reqchunk_filecb(), Messenger::fr_c, FRIEND_ADDED, FRIEND_CONFIRMED, FRIEND_ONLINE, FRIEND_REQUESTED, Friend::friendcon_id, Messenger::friendlist, Friend::friendrequest_lastsent, Friend::friendrequest_nospam, i, Friend::info, Friend::info_size, Friend::last_seen_time, m_sendname(), Messenger::name, Messenger::name_length, Friend::name_sent, Messenger::numfriends, send_friend_request_packet(), send_statusmessage(), send_user_istyping(), send_userstatus(), set_friend_status(), Friend::status, Messenger::statusmessage, Messenger::statusmessage_length, Friend::statusmessage_sent, unix_time(), Friend::user_istyping, Friend::user_istyping_sent, Messenger::userstatus, and Friend::userstatus_sent.
Referenced by do_messenger().
{
    uint32_t i;
    uint64_t temp_time = unix_time();
    for (i = 0; i < m->numfriends; ++i) {
        if (m->friendlist[i].status == FRIEND_ADDED) {
            int fr = send_friend_request_packet(m->
      fr_c, m->friendlist[i].friendcon_id, m->friendlist[i].
      friendrequest_nospam,
                                                m->friendlist[i].info,
                                                m->friendlist[i].
      info_size);
            if (fr >= 0) {
                set_friend_status(m, i, FRIEND_REQUESTED);
                m->friendlist[i].friendrequest_lastsent = temp_time;
            }
        }
        if (m->friendlist[i].status == FRIEND_REQUESTED
                || m->friendlist[i].status == FRIEND_CONFIRMED) { /* friend
       is not online. */
            if (m->friendlist[i].status == FRIEND_REQUESTED) {
                /* If we didn't connect to friend after successfully sending him a friend request the
       request is deemed
                 * unsuccessful so we set the status back to FRIEND_ADDED and try again.
                 */
                check_friend_request_timed_out(m, i, temp_time);
            }
        }
        if (m->friendlist[i].status == FRIEND_ONLINE) { /* friend is online.
      */
            if (m->friendlist[i].name_sent == 0) {
                if (m_sendname(m, i, m->name, m->name_length))
                    m->friendlist[i].name_sent = 1;
            }
            if (m->friendlist[i].statusmessage_sent == 0) {
                if (send_statusmessage(m, i, m->statusmessage, m->
      statusmessage_length))
                    m->friendlist[i].statusmessage_sent = 1;
            }
            if (m->friendlist[i].userstatus_sent == 0) {
                if (send_userstatus(m, i, m->userstatus))
                    m->friendlist[i].userstatus_sent = 1;
            }
            if (m->friendlist[i].user_istyping_sent == 0) {
                if (send_user_istyping(m, i, m->friendlist[i].
      user_istyping))
                    m->friendlist[i].user_istyping_sent = 1;
            }
            check_friend_tcp_udp(m, i);
            do_receipts(m, i);
            do_reqchunk_filecb(m, i);
            m->friendlist[i].last_seen_time = (uint64_t) time(NULL);
        }
    }
}
void do_messenger (Messenger * m)
Definition at line 2280 of file Messenger.c.
References add_tcp_relay(), Client_data::assoc4, DHT_Friend::client_list, DHT::close_clientlist, connection_status_cb(), Messenger::dht, do_DHT(), do_friend_connections(), do_friends(), do_net_crypto(), do_onion_client(), do_TCP_server(), IP::family, Messenger::fr_c, Messenger::friendlist, DHT::friends_list, Messenger::has_added_relays, i, id_equal(), IP_Port::ip, IP::ip4, ip_isset(), ip_ntoa(), IPPTsPng::ip_port, Node_format::ip_port, IPPTsPng::last_pinged, LCLIENT_LIST, Messenger::loaded_relays, LOGGER_TRACE, MAX_FRIEND_CLIENTS, Friend::name, Messenger::net, Messenger::net_crypto, networking_poll(), DHT::num_friends, NUM_SAVED_TCP_RELAYS, Messenger::numfriends, Messenger::onion_c, Messenger::options, IP_Port::port, Client_data::public_key, DHT_Friend::public_key, TCP_Server::public_key, Node_format::public_key, Friend::real_pk, Messenger::tcp_server, Messenger_Options::tcp_server_port, Messenger_Options::udp_disabled, IP4::uint32, unix_time(), and unix_time_update().
Referenced by main(), and tox_iterate().
{
    // Add the TCP relays, but only if this is the first time calling do_messenger
    if (m->has_added_relays == 0) {
        m->has_added_relays = 1;
        int i;
        for (i = 0; i < NUM_SAVED_TCP_RELAYS; ++i) {
            add_tcp_relay(m->net_crypto, m->loaded_relays[i].
      ip_port, m->loaded_relays[i].public_key);
        }
        if (m->tcp_server) {
            /* Add self tcp server. */
            IP_Port local_ip_port;
            local_ip_port.port = m->options.tcp_server_port;
            local_ip_port.ip.family = AF_INET;
            local_ip_port.ip.ip4.uint32 = INADDR_LOOPBACK;
            add_tcp_relay(m->net_crypto, local_ip_port, m->
      tcp_server->public_key);
        }
    }
    unix_time_update();
    if (!m->options.udp_disabled) {
        networking_poll(m->net);
        do_DHT(m->dht);
    }
    if (m->tcp_server) {
        do_TCP_server(m->tcp_server);
    }
    do_net_crypto(m->net_crypto);
    do_onion_client(m->onion_c);
    do_friend_connections(m->fr_c);
    do_friends(m);
    connection_status_cb(m);
#ifdef LOGGING
    if (unix_time() > lastdump + DUMPING_CLIENTS_FRIENDS_EVERY_N_SECONDS) {
#ifdef ENABLE_ASSOC_DHT
        Assoc_status(m->dht->assoc);
#endif
        lastdump = unix_time();
        uint32_t client, last_pinged;
        for (client = 0; client < LCLIENT_LIST; client++) {
            Client_data *cptr = &m->dht->close_clientlist[client];
            IPPTsPng *assoc = NULL;
            uint32_t a;
            for (a = 0, assoc = &cptr->assoc4; a < 2; a++, assoc = &cptr->assoc6)
                if (ip_isset(&assoc->ip_port.ip)) {
                    last_pinged = lastdump - assoc->last_pinged;
                    if (last_pinged > 999)
                        last_pinged = 999;
                    LOGGER_TRACE("C[%2u] %s:%u [%3u] %s",
                                 client, ip_ntoa(&assoc->ip_port.
      ip), ntohs(assoc->ip_port.port),
                                 last_pinged, ID2String(cptr->public_key));
                }
        }
        uint32_t friend, dhtfriend;
        /* dht contains additional "friends" (requests) */
        uint32_t num_dhtfriends = m->dht->num_friends;
        int32_t m2dht[num_dhtfriends];
        int32_t dht2m[num_dhtfriends];
        for (friend = 0; friend < num_dhtfriends; friend++) {
            m2dht[friend] = -1;
            dht2m[friend] = -1;
            if (friend >= m->numfriends)
                continue;
            for (dhtfriend = 0; dhtfriend < m->dht->num_friends; dhtfriend++)
                if (id_equal(m->friendlist[friend].real_pk, m->
      dht->friends_list[dhtfriend].public_key)) {
                    m2dht[friend] = dhtfriend;
                    break;
                }
        }
        for (friend = 0; friend < num_dhtfriends; friend++)
            if (m2dht[friend] >= 0)
                dht2m[m2dht[friend]] = friend;
        if (m->numfriends != m->dht->num_friends) {
            LOGGER_TRACE("Friend num in DHT %u != friend num in msger %u\n", m->
      dht->num_friends, m->numfriends);
        }
        Friend *msgfptr;
        DHT_Friend *dhtfptr;
        for (friend = 0; friend < num_dhtfriends; friend++) {
            if (dht2m[friend] >= 0)
                msgfptr = &m->friendlist[dht2m[friend]];
            else
                msgfptr = NULL;
            dhtfptr = &m->dht->friends_list[friend];
            if (msgfptr) {
                LOGGER_TRACE("F[%2u:%2u] <%s> %s",
                             dht2m[friend], friend, msgfptr->name,
                             ID2String(msgfptr->real_pk));
            } else {
                LOGGER_TRACE("F[--:%2u] %s", friend, ID2String(dhtfptr->
      public_key));
            }
            for (client = 0; client < MAX_FRIEND_CLIENTS; client++) {
                Client_data *cptr = &dhtfptr->client_list[client];
                IPPTsPng *assoc = NULL;
                uint32_t a;
                for (a = 0, assoc = &cptr->assoc4; a < 2; a++, assoc = &cptr->assoc6)
                    if (ip_isset(&assoc->ip_port.ip)) {
                        last_pinged = lastdump - assoc->last_pinged;
                        if (last_pinged > 999)
                            last_pinged = 999;
                        LOGGER_TRACE("F[%2u] => C[%2u] %s:%u [%3u] %s",
                                     friend, client, ip_ntoa(&assoc->
      ip_port.ip),
                                     ntohs(assoc->ip_port.port), last_pinged,
                                     ID2String(cptr->public_key));
                    }
            }
        }
    }
#endif /* LOGGING */
}
static int do_receipts (Messenger * m, int32_t friendnumber) [static]
Definition at line 347 of file Messenger.c.
References friend_not_valid(), friend_received_packet(), Messenger::friendlist, Receipts::msg_id, Receipts::next, Receipts::packet_num, Messenger::read_receipt, Messenger::read_receipt_userdata, Friend::receipts_end, and Friend::receipts_start.
Referenced by do_friends().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    struct Receipts *receipts = m->friendlist[friendnumber].
      receipts_start;
    while (receipts) {
        struct Receipts *temp_r = receipts->next;
        if (friend_received_packet(m, friendnumber, receipts->
      packet_num) == -1)
            break;
        if (m->read_receipt)
            (*m->read_receipt)(m, friendnumber, receipts->msg_id, m->
      read_receipt_userdata);
        free(receipts);
        m->friendlist[friendnumber].receipts_start = temp_r;
        receipts = temp_r;
    }
    if (!m->friendlist[friendnumber].receipts_start)
        m->friendlist[friendnumber].receipts_end = NULL;
    return 0;
}
static void do_reqchunk_filecb (Messenger * m, int32_t friendnumber) [static]
Definition at line 1404 of file Messenger.c.
References crypto_num_free_sendqueue_slots(), file_data(), FILE_PAUSE_NOT, Messenger::file_reqchunk, Messenger::file_reqchunk_userdata, Friend::file_sending, FILESTATUS_FINISHED, FILESTATUS_NONE, FILESTATUS_TRANSFERRING, Messenger::fr_c, friend_connection_crypt_connection_id(), friend_received_packet(), Friend::friendcon_id, Messenger::friendlist, i, File_Transfers::last_packet_number, MAX_CONCURRENT_FILE_PIPES, MAX_FILE_DATA_SIZE, max_speed_reached(), MIN_SLOTS_FREE, Messenger::net_crypto, num, Friend::num_sending_files, File_Transfers::paused, File_Transfers::requested, File_Transfers::size, File_Transfers::slots_allocated, File_Transfers::status, and File_Transfers::transferred.
Referenced by do_friends().
{
    if (!m->friendlist[friendnumber].num_sending_files)
        return;
    int free_slots = crypto_num_free_sendqueue_slots(m->
      net_crypto, friend_connection_crypt_connection_id(m->
      fr_c,
                     m->friendlist[friendnumber].friendcon_id));
    if (free_slots < MIN_SLOTS_FREE) {
        free_slots = 0;
    } else {
        free_slots -= MIN_SLOTS_FREE;
    }
    unsigned int i, num = m->friendlist[friendnumber].
      num_sending_files;
    for (i = 0; i < MAX_CONCURRENT_FILE_PIPES; ++i) {
        struct File_Transfers *ft = &m->friendlist[friendnumber].
      file_sending[i];
        if (ft->status != FILESTATUS_NONE) {
            --num;
            if (ft->status == FILESTATUS_FINISHED) {
                /* Check if file was entirely sent. */
                if (friend_received_packet(m, friendnumber, ft->
      last_packet_number) == 0) {
                    if (m->file_reqchunk)
                        (*m->file_reqchunk)(m, friendnumber, i, ft->
      transferred, 0, m->file_reqchunk_userdata);
                    ft->status = FILESTATUS_NONE;
                    --m->friendlist[friendnumber].num_sending_files;
                }
            }
            /* TODO: if file is too slow, switch to the next. */
            if (ft->slots_allocated > (unsigned int)free_slots) {
                free_slots = 0;
            } else {
                free_slots -= ft->slots_allocated;
            }
        }
        while (ft->status == FILESTATUS_TRANSFERRING && (ft->
      paused == FILE_PAUSE_NOT)) {
            if (max_speed_reached(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                  m->friendlist[friendnumber].
      friendcon_id))) {
                free_slots = 0;
            }
            if (free_slots == 0)
                break;
            uint16_t length = MAX_FILE_DATA_SIZE;
            if (ft->size == 0) {
                /* Send 0 data to friend if file is 0 length. */
                file_data(m, friendnumber, i, 0, 0, 0);
                break;
            }
            if (ft->size == ft->requested) {
                break;
            }
            if (ft->size - ft->requested < length) {
                length = ft->size - ft->requested;
            }
            ++ft->slots_allocated;
            uint64_t position = ft->requested;
            ft->requested += length;
            if (m->file_reqchunk)
                (*m->file_reqchunk)(m, friendnumber, i, position, length, m->
      file_reqchunk_userdata);
            --free_slots;
        }
        if (num == 0)
            break;
    }
}
int file_control (const Messenger * m, int32_t friendnumber, uint32_t filenumber, unsigned int control)
Definition at line 1137 of file Messenger.c.
References FILE_PAUSE_OTHER, FILE_PAUSE_US, Friend::file_receiving, Friend::file_sending, FILECONTROL_ACCEPT, FILECONTROL_KILL, FILECONTROL_PAUSE, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, FILESTATUS_TRANSFERRING, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, MAX_CONCURRENT_FILE_PIPES, Friend::num_sending_files, File_Transfers::paused, send_file_control_packet(), File_Transfers::status, and Friend::status.
Referenced by tox_file_control().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        send_receive = 0;
        temp_filenum = filenumber;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -3;
    if (control > FILECONTROL_KILL)
        return -4;
    if (control == FILECONTROL_PAUSE && ((ft->paused &
      FILE_PAUSE_US) || ft->status != FILESTATUS_TRANSFERRING))
        return -5;
    if (control == FILECONTROL_ACCEPT) {
        if (ft->status == FILESTATUS_TRANSFERRING) {
            if (!(ft->paused & FILE_PAUSE_US)) {
                if (ft->paused & FILE_PAUSE_OTHER) {
                    return -6;
                } else {
                    return -7;
                }
            }
        } else {
            if (ft->status != FILESTATUS_NOT_ACCEPTED)
                return -7;
            if (!send_receive)
                return -6;
        }
    }
    if (send_file_control_packet(m, friendnumber, send_receive, file_number,
      control, 0, 0)) {
        if (control == FILECONTROL_KILL) {
            ft->status = FILESTATUS_NONE;
            if (send_receive == 0) {
                --m->friendlist[friendnumber].num_sending_files;
            }
        } else if (control == FILECONTROL_PAUSE) {
            ft->paused |= FILE_PAUSE_US;
        } else if (control == FILECONTROL_ACCEPT) {
            ft->status = FILESTATUS_TRANSFERRING;
            if (ft->paused & FILE_PAUSE_US) {
                ft->paused ^= FILE_PAUSE_US;
            }
        }
    } else {
        return -8;
    }
    return 0;
}
int file_data (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint64_t position, const uint8_t * data, uint16_t length)
Definition at line 1318 of file Messenger.c.
References crypto_num_free_sendqueue_slots(), Friend::file_sending, FILESTATUS_FINISHED, FILESTATUS_TRANSFERRING, Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, File_Transfers::last_packet_number, MAX_CONCURRENT_FILE_PIPES, MAX_FILE_DATA_SIZE, MIN_SLOTS_FREE, Messenger::net_crypto, File_Transfers::requested, send_file_data_packet(), File_Transfers::size, File_Transfers::slots_allocated, File_Transfers::status, Friend::status, and File_Transfers::transferred.
Referenced by do_reqchunk_filecb(), handle_packet(), and tox_file_send_chunk().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    if (filenumber >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    struct File_Transfers *ft = &m->friendlist[friendnumber].
      file_sending[filenumber];
    if (ft->status != FILESTATUS_TRANSFERRING)
        return -4;
    if (length > MAX_FILE_DATA_SIZE)
        return -5;
    if (ft->size - ft->transferred < length) {
        return -5;
    }
    if (ft->size != UINT64_MAX && length != MAX_FILE_DATA_SIZE && (ft->
      transferred + length) != ft->size) {
        return -5;
    }
    if (position != ft->transferred || (ft->requested <= position && ft->
      size != 0)) {
        return -7;
    }
    /* Prevent file sending from filling up the entire buffer preventing messages from being sent. TODO:
       remove */
    if (crypto_num_free_sendqueue_slots(m->
      net_crypto, friend_connection_crypt_connection_id(m->
      fr_c,
                                        m->friendlist[friendnumber].
      friendcon_id)) < MIN_SLOTS_FREE)
        return -6;
    int64_t ret = send_file_data_packet(m, friendnumber, filenumber,
      data, length);
    if (ret != -1) {
        //TODO record packet ids to check if other received complete file.
        ft->transferred += length;
        if (ft->slots_allocated) {
            --ft->slots_allocated;
        }
        if (length != MAX_FILE_DATA_SIZE || ft->size == ft->
      transferred) {
            ft->status = FILESTATUS_FINISHED;
            ft->last_packet_number = ret;
        }
        return 0;
    }
    return -6;
}
uint64_t file_dataremaining (const Messenger * m, int32_t friendnumber, uint8_t filenumber, uint8_t send_receive)
Definition at line 1384 of file Messenger.c.
References Friend::file_receiving, Friend::file_sending, FILESTATUS_NONE, friend_not_valid(), Messenger::friendlist, File_Transfers::size, File_Transfers::status, and File_Transfers::transferred.
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    if (send_receive == 0) {
        if (m->friendlist[friendnumber].file_sending[filenumber].
      status == FILESTATUS_NONE)
            return 0;
        return m->friendlist[friendnumber].file_sending[filenumber].
      size -
               m->friendlist[friendnumber].file_sending[filenumber].
      transferred;
    } else {
        if (m->friendlist[friendnumber].file_receiving[filenumber].
      status == FILESTATUS_NONE)
            return 0;
        return m->friendlist[friendnumber].file_receiving[filenumber].
      size -
               m->friendlist[friendnumber].file_receiving[filenumber].
      transferred;
    }
}
int file_get_id (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint8_t * file_id)
Definition at line 993 of file Messenger.c.
References FILE_ID_LENGTH, Friend::file_receiving, Friend::file_sending, FILESTATUS_NONE, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, File_Transfers::id, MAX_CONCURRENT_FILE_PIPES, File_Transfers::status, and Friend::status.
Referenced by tox_file_get_file_id().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        send_receive = 0;
        temp_filenum = filenumber;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -2;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -2;
    memcpy(file_id, ft->id, FILE_ID_LENGTH);
    return 0;
}
int file_seek (const Messenger * m, int32_t friendnumber, uint32_t filenumber, uint64_t position)
Definition at line 1230 of file Messenger.c.
References Friend::file_receiving, Friend::file_sending, FILECONTROL_SEEK, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, friend_not_valid(), FRIEND_ONLINE, Messenger::friendlist, host_to_net(), MAX_CONCURRENT_FILE_PIPES, send_file_control_packet(), sending_pos, File_Transfers::size, File_Transfers::status, Friend::status, and File_Transfers::transferred.
Referenced by tox_file_seek().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -2;
    uint32_t temp_filenum;
    uint8_t send_receive, file_number;
    if (filenumber >= (1 << 16)) {
        send_receive = 1;
        temp_filenum = (filenumber >> 16) - 1;
    } else {
        return -4;
    }
    if (temp_filenum >= MAX_CONCURRENT_FILE_PIPES)
        return -3;
    file_number = temp_filenum;
    struct File_Transfers *ft;
    if (send_receive) {
        ft = &m->friendlist[friendnumber].file_receiving[file_number];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[file_number];
    }
    if (ft->status == FILESTATUS_NONE)
        return -3;
    if (ft->status != FILESTATUS_NOT_ACCEPTED)
        return -5;
    if (position > ft->size) {
        return -6;
    }
    uint64_t sending_pos = position;
    host_to_net((uint8_t *)&sending_pos, sizeof(sending_pos));
    if (send_file_control_packet(m, friendnumber, send_receive, file_number,
      FILECONTROL_SEEK, (uint8_t *)&sending_pos,
                                 sizeof(sending_pos))) {
        ft->transferred = position;
    } else {
        return -8;
    }
    return 0;
}
static int file_sendrequest (const Messenger * m, int32_t friendnumber, uint8_t filenumber, uint32_t file_type, uint64_t filesize, const uint8_t * file_id, const uint8_t * filename, uint16_t filename_length) [static]
Definition at line 1037 of file Messenger.c.
References FILE_ID_LENGTH, friend_not_valid(), host_to_net(), MAX_FILENAME_LENGTH, PACKET_ID_FILE_SENDREQUEST, and write_cryptpacket_id().
Referenced by new_filesender().
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    if (filename_length > MAX_FILENAME_LENGTH)
        return 0;
    uint8_t packet[1 + sizeof(file_type) + sizeof(filesize) + FILE_ID_LENGTH +
      filename_length];
    packet[0] = filenumber;
    file_type = htonl(file_type);
    memcpy(packet + 1, &file_type, sizeof(file_type));
    host_to_net((uint8_t *)&filesize, sizeof(filesize));
    memcpy(packet + 1 + sizeof(file_type), &filesize, sizeof(filesize));
    memcpy(packet + 1 + sizeof(file_type) + sizeof(filesize), file_id,
      FILE_ID_LENGTH);
    if (filename_length) {
        memcpy(packet + 1 + sizeof(file_type) + sizeof(filesize) +
      FILE_ID_LENGTH, filename, filename_length);
    }
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_FILE_SENDREQUEST, packet, sizeof(packet), 0);
}
static int friend_already_added (const uint8_t * real_pk, void * data) [static]
Definition at line 1740 of file Messenger.c.
References make-funny-savefile::data, and getfriend_id().
Referenced by new_messenger().
{
    const Messenger *m = data;
    if (getfriend_id(m, real_pk) == -1)
        return 0;
    return -1;
}
static uint8_t friend_not_valid (const Messenger * m, int32_t friendnumber) [static]
Definition at line 44 of file Messenger.c.
References Messenger::friendlist, and Friend::status.
Referenced by add_receipt(), clear_receipts(), do_receipts(), file_control(), file_data(), file_dataremaining(), file_get_id(), file_seek(), file_sendrequest(), friend_received_packet(), get_real_pk(), getfriendcon_id(), getname(), handle_custom_lossless_packet(), handle_custom_lossy_packet(), m_callback_rtp_packet(), m_copy_statusmessage(), m_delfriend(), m_friend_exists(), m_get_friend_connectionstatus(), m_get_istyping(), m_get_last_online(), m_get_name_size(), m_get_statusmessage_size(), m_get_userstatus(), m_send_message_generic(), m_set_usertyping(), new_filesender(), send_custom_lossless_packet(), send_custom_lossy_packet(), send_file_data_packet(), send_online_packet(), set_friend_statusmessage(), setfriendname(), and write_cryptpacket_id().
{
    if ((unsigned int)friendnumber < m->numfriends) {
        if (m->friendlist[friendnumber].status != 0) {
            return 0;
        }
    }
    return 1;
}
static int friend_received_packet (const Messenger * m, int32_t friendnumber, uint32_t number) [static]
Definition at line 338 of file Messenger.c.
References cryptpacket_received(), Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), Friend::friendcon_id, Messenger::friendlist, and Messenger::net_crypto.
Referenced by do_receipts(), and do_reqchunk_filecb().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return cryptpacket_received(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                m->friendlist[friendnumber].
      friendcon_id), number);
}
static int friends_list_load (Messenger * m, const uint8_t * data, uint32_t length) [static]
Definition at line 2499 of file Messenger.c.
References address_checksum(), FRIEND_ADDRESS_SIZE, Messenger::friendlist, SAVED_FRIEND::friendrequest_nospam, i, id_copy(), SAVED_FRIEND::info, SAVED_FRIEND::info_size, Friend::last_seen_time, SAVED_FRIEND::last_seen_time, m_addfriend(), m_addfriend_norequest(), SAVED_FRIEND::name, SAVED_FRIEND::name_length, net_to_host, num, SAVED_FRIEND::real_pk, set_friend_statusmessage(), set_friend_userstatus(), setfriendname(), SAVED_FRIEND::status, SAVED_FRIEND::statusmessage, SAVED_FRIEND::statusmessage_length, and SAVED_FRIEND::userstatus.
Referenced by messenger_load_state_callback().
{
    if (length % sizeof(struct SAVED_FRIEND) != 0) {
        return -1;
    }
    uint32_t num = length / sizeof(struct SAVED_FRIEND);
    uint32_t i;
    for (i = 0; i < num; ++i) {
        struct SAVED_FRIEND temp;
        memcpy(&temp, data + i * sizeof(struct SAVED_FRIEND), sizeof(struct
      SAVED_FRIEND));
        if (temp.status >= 3) {
            int fnum = m_addfriend_norequest(m, temp.real_pk);
            if (fnum < 0)
                continue;
            setfriendname(m, fnum, temp.name, ntohs(temp.name_length));
            set_friend_statusmessage(m, fnum, temp.
      statusmessage, ntohs(temp.statusmessage_length));
            set_friend_userstatus(m, fnum, temp.userstatus);
            uint8_t last_seen_time[sizeof(uint64_t)];
            memcpy(last_seen_time, &temp.last_seen_time, sizeof(uint64_t));
            net_to_host(last_seen_time, sizeof(uint64_t));
            memcpy(&m->friendlist[fnum].last_seen_time,
      last_seen_time, sizeof(uint64_t));
        } else if (temp.status != 0) {
            /* TODO: This is not a good way to do this. */
            uint8_t address[FRIEND_ADDRESS_SIZE];
            id_copy(address, temp.real_pk);
            memcpy(address + crypto_box_PUBLICKEYBYTES, &(temp.friendrequest_nospam), sizeof(uint32_t));
            uint16_t checksum = address_checksum(address,
      FRIEND_ADDRESS_SIZE - sizeof(checksum));
            memcpy(address + crypto_box_PUBLICKEYBYTES + sizeof(uint32_t), &checksum, sizeof(checksum));
            m_addfriend(m, address, temp.info, ntohs(temp.info_size));
        }
    }
    return num;
}
static uint32_t friends_list_save (const Messenger * m, uint8_t * data) [static]
Definition at line 2457 of file Messenger.c.
References Messenger::friendlist, Friend::friendrequest_nospam, SAVED_FRIEND::friendrequest_nospam, host_to_net(), i, Friend::info, SAVED_FRIEND::info, Friend::info_size, SAVED_FRIEND::info_size, Friend::last_seen_time, SAVED_FRIEND::last_seen_time, Friend::name, SAVED_FRIEND::name, Friend::name_length, SAVED_FRIEND::name_length, num, Messenger::numfriends, Friend::real_pk, SAVED_FRIEND::real_pk, SAVED_FRIEND_REQUEST_SIZE, Friend::status, SAVED_FRIEND::status, Friend::statusmessage, SAVED_FRIEND::statusmessage, Friend::statusmessage_length, SAVED_FRIEND::statusmessage_length, Friend::userstatus, and SAVED_FRIEND::userstatus.
Referenced by messenger_save().
{
    uint32_t i;
    uint32_t num = 0;
    for (i = 0; i < m->numfriends; i++) {
        if (m->friendlist[i].status > 0) {
            struct SAVED_FRIEND temp;
            memset(&temp, 0, sizeof(struct SAVED_FRIEND));
            temp.status = m->friendlist[i].status;
            memcpy(temp.real_pk, m->friendlist[i].real_pk, crypto_box_PUBLICKEYBYTES);
            if (temp.status < 3) {
                if (m->friendlist[i].info_size >
      SAVED_FRIEND_REQUEST_SIZE) {
                    memcpy(temp.info, m->friendlist[i].info,
      SAVED_FRIEND_REQUEST_SIZE);
                } else {
                    memcpy(temp.info, m->friendlist[i].info, m->
      friendlist[i].info_size);
                }
                temp.info_size = htons(m->friendlist[i].info_size);
                temp.friendrequest_nospam = m->friendlist[i].
      friendrequest_nospam;
            } else {
                memcpy(temp.name, m->friendlist[i].name, m->
      friendlist[i].name_length);
                temp.name_length = htons(m->friendlist[i].name_length);
                memcpy(temp.statusmessage, m->friendlist[i].
      statusmessage, m->friendlist[i].statusmessage_length);
                temp.statusmessage_length = htons(m->friendlist[i].
      statusmessage_length);
                temp.userstatus = m->friendlist[i].userstatus;
                uint8_t last_seen_time[sizeof(uint64_t)];
                memcpy(last_seen_time, &m->friendlist[i].
      last_seen_time, sizeof(uint64_t));
                host_to_net(last_seen_time, sizeof(uint64_t));
                memcpy(&temp.last_seen_time, last_seen_time, sizeof(uint64_t));
            }
            memcpy(data + num * sizeof(struct SAVED_FRIEND), &temp, sizeof(struct
      SAVED_FRIEND));
            num++;
        }
    }
    return num * sizeof(struct SAVED_FRIEND);
}
int get_real_pk (const Messenger * m, int32_t friendnumber, uint8_t * real_pk)
Definition at line 98 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::real_pk.
Referenced by tox_friend_get_public_key().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    memcpy(real_pk, m->friendlist[friendnumber].real_pk, crypto_box_PUBLICKEYBYTES)
      ;
    return 0;
}
void getaddress (const Messenger * m, uint8_t * address)
Definition at line 138 of file Messenger.c.
References address_checksum(), Messenger::fr, FRIEND_ADDRESS_SIZE, get_nospam(), id_copy(), Messenger::net_crypto, make-funny-savefile::nospam, and Net_Crypto::self_public_key.
Referenced by main(), and tox_self_get_address().
{
    id_copy(address, m->net_crypto->self_public_key);
    uint32_t nospam = get_nospam(&(m->fr));
    memcpy(address + crypto_box_PUBLICKEYBYTES, &nospam, sizeof(nospam));
    uint16_t checksum = address_checksum(address,
      FRIEND_ADDRESS_SIZE - sizeof(checksum));
    memcpy(address + crypto_box_PUBLICKEYBYTES + sizeof(nospam), &checksum, sizeof(checksum));
}
int32_t getfriend_id (const Messenger * m, const uint8_t * real_pk)
Definition at line 79 of file Messenger.c.
References Messenger::friendlist, i, id_equal(), Messenger::numfriends, Friend::real_pk, and Friend::status.
Referenced by friend_already_added(), m_addfriend(), m_addfriend_norequest(), main(), and tox_friend_by_public_key().
{
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i) {
        if (m->friendlist[i].status > 0)
            if (id_equal(real_pk, m->friendlist[i].
      real_pk))
                return i;
    }
    return -1;
}
int getfriendcon_id (const Messenger * m, int32_t friendnumber)
Definition at line 110 of file Messenger.c.
References friend_not_valid(), Friend::friendcon_id, and Messenger::friendlist.
Referenced by handle_friend_invite_packet(), and join_groupchat().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].friendcon_id;
}
int getname (const Messenger * m, int32_t friendnumber, uint8_t * name)
Definition at line 570 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::name, and Friend::name_length.
Referenced by main(), messenger_suite(), START_TEST(), and tox_friend_get_name().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    memcpy(name, m->friendlist[friendnumber].name, m->
      friendlist[friendnumber].name_length);
    return m->friendlist[friendnumber].name_length;
}
uint16_t getself_name (const Messenger * m, uint8_t * name)
Definition at line 553 of file Messenger.c.
References Messenger::name, and Messenger::name_length.
Referenced by messenger_suite(), START_TEST(), and tox_self_get_name().
{
    if (name == NULL) {
        return 0;
    }
    memcpy(name, m->name, m->name_length);
    return m->name_length;
}
static int handle_custom_lossless_packet (void * object, int friend_num, const uint8_t * packet, uint16_t length) [static]
Definition at line 1688 of file Messenger.c.
References friend_not_valid(), Messenger::lossless_packethandler, Messenger::lossless_packethandler_userdata, PACKET_ID_LOSSLESS_RANGE_SIZE, and PACKET_ID_LOSSLESS_RANGE_START.
Referenced by handle_packet().
{
    Messenger *m = object;
    if (friend_not_valid(m, friend_num))
        return -1;
    if (packet[0] < PACKET_ID_LOSSLESS_RANGE_START)
        return -1;
    if (packet[0] >= (PACKET_ID_LOSSLESS_RANGE_START +
      PACKET_ID_LOSSLESS_RANGE_SIZE))
        return -1;
    if (m->lossless_packethandler)
        m->lossless_packethandler(m, friend_num, packet, length, m->
      lossless_packethandler_userdata);
    return 1;
}
static int handle_custom_lossy_packet (void * object, int friend_num, const uint8_t * packet, uint16_t length) [static]
Definition at line 1615 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::function, Messenger::lossy_packethandler, Messenger::lossy_packethandler_userdata, Friend::lossy_rtp_packethandlers, Friend::object, PACKET_ID_LOSSY_RANGE_START, and PACKET_LOSSY_AV_RESERVED.
Referenced by init_new_friend().
{
    Messenger *m = object;
    if (friend_not_valid(m, friend_num))
        return 1;
    if (packet[0] < (PACKET_ID_LOSSY_RANGE_START +
      PACKET_LOSSY_AV_RESERVED)) {
        if (m->friendlist[friend_num].lossy_rtp_packethandlers[packet[0]
      % PACKET_LOSSY_AV_RESERVED].function)
            return m->friendlist[friend_num].lossy_rtp_packethandlers[
      packet[0] % PACKET_LOSSY_AV_RESERVED].function(
                       m, friend_num, packet, length, m->friendlist[friend_num].
      lossy_rtp_packethandlers[packet[0] %
                               PACKET_LOSSY_AV_RESERVED].object);
        return 1;
    }
    if (m->lossy_packethandler)
        m->lossy_packethandler(m, friend_num, packet, length, m->
      lossy_packethandler_userdata);
    return 1;
}
static int handle_filecontrol (Messenger * m, int32_t friendnumber, uint8_t receive_send, uint8_t filenumber, uint8_t control_type, uint8_t * data, uint16_t length) [static]
Definition at line 1506 of file Messenger.c.
References Messenger::file_filecontrol, Messenger::file_filecontrol_userdata, FILE_PAUSE_OTHER, Friend::file_receiving, Friend::file_sending, FILECONTROL_ACCEPT, FILECONTROL_KILL, FILECONTROL_PAUSE, FILECONTROL_SEEK, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, FILESTATUS_TRANSFERRING, Messenger::friendlist, net_to_host, Friend::num_sending_files, File_Transfers::paused, File_Transfers::requested, send_file_control_packet(), File_Transfers::size, File_Transfers::status, and File_Transfers::transferred.
Referenced by handle_packet().
{
    if (receive_send > 1)
        return -1;
    if (control_type > FILECONTROL_SEEK)
        return -1;
    uint32_t real_filenumber = filenumber;
    struct File_Transfers *ft;
    if (receive_send == 0) {
        real_filenumber += 1;
        real_filenumber <<= 16;
        ft = &m->friendlist[friendnumber].file_receiving[filenumber];
    } else {
        ft = &m->friendlist[friendnumber].file_sending[filenumber];
    }
    if (ft->status == FILESTATUS_NONE) {
        /* File transfer doesn't exist, tell the other to kill it. */
        send_file_control_packet(m, friendnumber, !receive_send, filenumber,
      FILECONTROL_KILL, 0, 0);
        return -1;
    }
    if (control_type == FILECONTROL_ACCEPT) {
        if (receive_send && ft->status == FILESTATUS_NOT_ACCEPTED) {
            ft->status = FILESTATUS_TRANSFERRING;
        } else {
            if (ft->paused & FILE_PAUSE_OTHER) {
                ft->paused ^= FILE_PAUSE_OTHER;
            } else {
                return -1;
            }
        }
        if (m->file_filecontrol)
            (*m->file_filecontrol)(m, friendnumber, real_filenumber, control_type, m->
      file_filecontrol_userdata);
    } else if (control_type == FILECONTROL_PAUSE) {
        if ((ft->paused & FILE_PAUSE_OTHER) || ft->status !=
      FILESTATUS_TRANSFERRING) {
            return -1;
        }
        ft->paused |= FILE_PAUSE_OTHER;
        if (m->file_filecontrol)
            (*m->file_filecontrol)(m, friendnumber, real_filenumber, control_type, m->
      file_filecontrol_userdata);
    } else if (control_type == FILECONTROL_KILL) {
        if (m->file_filecontrol)
            (*m->file_filecontrol)(m, friendnumber, real_filenumber, control_type, m->
      file_filecontrol_userdata);
        ft->status = FILESTATUS_NONE;
        if (receive_send) {
            --m->friendlist[friendnumber].num_sending_files;
        }
    } else if (control_type == FILECONTROL_SEEK) {
        uint64_t position;
        if (length != sizeof(position)) {
            return -1;
        }
        /* seek can only be sent by the receiver to seek before resuming broken tranfers. */
        if (ft->status != FILESTATUS_NOT_ACCEPTED || !receive_send) {
            return -1;
        }
        memcpy(&position, data, sizeof(position));
        net_to_host((uint8_t *) &position, sizeof(position));
        if (position > ft->size) {
            return -1;
        }
        ft->transferred = ft->requested = position;
    } else {
        return -1;
    }
    return 0;
}
static int handle_packet (void * object, int i, uint8_t * temp, uint16_t len) [static]
Definition at line 1908 of file Messenger.c.
References make-funny-savefile::data, file_data(), Messenger::file_filedata, Messenger::file_filedata_userdata, FILE_ID_LENGTH, FILE_PAUSE_NOT, Friend::file_receiving, Messenger::file_sendrequest, Messenger::file_sendrequest_userdata, FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, FILESTATUS_TRANSFERRING, FRIEND_CONFIRMED, Messenger::friend_message, Messenger::friend_message_userdata, Messenger::friend_namechange, Messenger::friend_namechange_userdata, FRIEND_ONLINE, Messenger::friend_statusmessagechange, Messenger::friend_statusmessagechange_userdata, Messenger::friend_typingchange, Messenger::friend_typingchange_userdata, Messenger::friend_userstatuschange, Messenger::friend_userstatuschange_userdata, Messenger::friendlist, Messenger::group_invite, handle_custom_lossless_packet(), handle_filecontrol(), i, File_Transfers::id, MAX_CONCURRENT_FILE_PIPES, MAX_FILE_DATA_SIZE, MAX_FILENAME_LENGTH, MAX_NAME_LENGTH, MAX_STATUSMESSAGE_LENGTH, Messenger::msi_packet, Messenger::msi_packet_userdata, Friend::name, Friend::name_length, net_to_host, PACKET_ID_ACTION, PACKET_ID_FILE_CONTROL, PACKET_ID_FILE_DATA, PACKET_ID_FILE_SENDREQUEST, PACKET_ID_INVITE_GROUPCHAT, PACKET_ID_MESSAGE, PACKET_ID_MSI, PACKET_ID_NICKNAME, PACKET_ID_OFFLINE, PACKET_ID_ONLINE, PACKET_ID_STATUSMESSAGE, PACKET_ID_TYPING, PACKET_ID_USERSTATUS, File_Transfers::paused, send_online_packet(), set_friend_status(), set_friend_statusmessage(), set_friend_typing(), set_friend_userstatus(), File_Transfers::size, File_Transfers::status, Friend::status, File_Transfers::transferred, and USERSTATUS_INVALID.
Referenced by init_new_friend().
{
    if (len == 0)
        return -1;
    Messenger *m = object;
    uint8_t packet_id = temp[0];
    uint8_t *data = temp + 1;
    uint32_t data_length = len - 1;
    if (m->friendlist[i].status != FRIEND_ONLINE) {
        if (packet_id == PACKET_ID_ONLINE && len == 1) {
            set_friend_status(m, i, FRIEND_ONLINE);
            send_online_packet(m, i);
        } else {
            return -1;
        }
    }
    switch (packet_id) {
        case PACKET_ID_OFFLINE: {
            if (data_length != 0)
                break;
            set_friend_status(m, i, FRIEND_CONFIRMED);
            break;
        }
        case PACKET_ID_NICKNAME: {
            if (data_length > MAX_NAME_LENGTH)
                break;
            /* Make sure the NULL terminator is present. */
            uint8_t data_terminated[data_length + 1];
            memcpy(data_terminated, data, data_length);
            data_terminated[data_length] = 0;
            /* inform of namechange before we overwrite the old name */
            if (m->friend_namechange)
                m->friend_namechange(m, i, data_terminated, data_length, m->
      friend_namechange_userdata);
            memcpy(m->friendlist[i].name, data_terminated, data_length);
            m->friendlist[i].name_length = data_length;
            break;
        }
        case PACKET_ID_STATUSMESSAGE: {
            if (data_length > MAX_STATUSMESSAGE_LENGTH)
                break;
            /* Make sure the NULL terminator is present. */
            uint8_t data_terminated[data_length + 1];
            memcpy(data_terminated, data, data_length);
            data_terminated[data_length] = 0;
            if (m->friend_statusmessagechange)
                m->friend_statusmessagechange(m, i, data_terminated, data_length
      ,
                                              m->
      friend_statusmessagechange_userdata);
            set_friend_statusmessage(m, i, data_terminated, data_length);
            break;
        }
        case PACKET_ID_USERSTATUS: {
            if (data_length != 1)
                break;
            USERSTATUS status = data[0];
            if (status >= USERSTATUS_INVALID)
                break;
            if (m->friend_userstatuschange)
                m->friend_userstatuschange(m, i, status, m->
      friend_userstatuschange_userdata);
            set_friend_userstatus(m, i, status);
            break;
        }
        case PACKET_ID_TYPING: {
            if (data_length != 1)
                break;
            _Bool typing = !!data[0];
            set_friend_typing(m, i, typing);
            if (m->friend_typingchange)
                m->friend_typingchange(m, i, typing, m->
      friend_typingchange_userdata);
            break;
        }
        case PACKET_ID_MESSAGE:
        case PACKET_ID_ACTION: {
            if (data_length == 0)
                break;
            const uint8_t *message = data;
            uint16_t message_length = data_length;
            /* Make sure the NULL terminator is present. */
            uint8_t message_terminated[message_length + 1];
            memcpy(message_terminated, message, message_length);
            message_terminated[message_length] = 0;
            uint8_t type = packet_id - PACKET_ID_MESSAGE;
            if (m->friend_message)
                (*m->friend_message)(m, i, type, message_terminated, message_length, m->
      friend_message_userdata);
            break;
        }
        case PACKET_ID_INVITE_GROUPCHAT: {
            if (data_length == 0)
                break;
            if (m->group_invite)
                (*m->group_invite)(m, i, data, data_length);
            break;
        }
        case PACKET_ID_FILE_SENDREQUEST: {
            const unsigned int head_length = 1 + sizeof(uint32_t) + sizeof(uint64_t) +
      FILE_ID_LENGTH;
            if (data_length < head_length)
                break;
            uint8_t filenumber = data[0];
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES)
                break;
            uint64_t filesize;
            uint32_t file_type;
            uint16_t filename_length = data_length - head_length;
            if (filename_length > MAX_FILENAME_LENGTH)
                break;
            memcpy(&file_type, data + 1, sizeof(file_type));
            file_type = ntohl(file_type);
            memcpy(&filesize, data + 1 + sizeof(uint32_t), sizeof(filesize));
            net_to_host((uint8_t *) &filesize, sizeof(filesize));
            struct File_Transfers *ft = &m->friendlist[i].
      file_receiving[filenumber];
            if (ft->status != FILESTATUS_NONE)
                break;
            ft->status = FILESTATUS_NOT_ACCEPTED;
            ft->size = filesize;
            ft->transferred = 0;
            ft->paused = FILE_PAUSE_NOT;
            memcpy(ft->id, data + 1 + sizeof(uint32_t) + sizeof(uint64_t),
      FILE_ID_LENGTH);
            uint8_t filename_terminated[filename_length + 1];
            uint8_t *filename = NULL;
            if (filename_length) {
                /* Force NULL terminate file name. */
                memcpy(filename_terminated, data + head_length, filename_length);
                filename_terminated[filename_length] = 0;
                filename = filename_terminated;
            }
            uint32_t real_filenumber = filenumber;
            real_filenumber += 1;
            real_filenumber <<= 16;
            if (m->file_sendrequest)
                (*m->file_sendrequest)(m, i, real_filenumber, file_type, filesize,
      filename, filename_length,
                                       m->file_sendrequest_userdata);
            break;
        }
        case PACKET_ID_FILE_CONTROL: {
            if (data_length < 3)
                break;
            uint8_t send_receive = data[0];
            uint8_t filenumber = data[1];
            uint8_t control_type = data[2];
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES)
                break;
            if (handle_filecontrol(m, i, send_receive, filenumber, control_type, data +
      3, data_length - 3) == -1)
                break;
            break;
        }
        case PACKET_ID_FILE_DATA: {
            if (data_length < 1)
                break;
            uint8_t filenumber = data[0];
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES)
                break;
            struct File_Transfers *ft = &m->friendlist[i].
      file_receiving[filenumber];
            if (ft->status != FILESTATUS_TRANSFERRING)
                break;
            uint64_t position = ft->transferred;
            uint32_t real_filenumber = filenumber;
            real_filenumber += 1;
            real_filenumber <<= 16;
            uint16_t file_data_length = (data_length - 1);
            uint8_t *file_data;
            if (file_data_length == 0) {
                file_data = NULL;
            } else {
                file_data = data + 1;
            }
            if (m->file_filedata)
                (*m->file_filedata)(m, i, real_filenumber, position, file_data,
      file_data_length, m->file_filedata_userdata);
            ft->transferred += file_data_length;
            if (file_data_length && (ft->transferred >= ft->size || file_data_length !=
      MAX_FILE_DATA_SIZE)) {
                file_data_length = 0;
                file_data = NULL;
                position = ft->transferred;
                /* Full file received. */
                if (m->file_filedata)
                    (*m->file_filedata)(m, i, real_filenumber, position, file_data,
      file_data_length, m->file_filedata_userdata);
            }
            /* Data is zero, filetransfer is over. */
            if (file_data_length == 0) {
                ft->status = FILESTATUS_NONE;
            }
            break;
        }
        case PACKET_ID_MSI: {
            if (data_length == 0)
                break;
            if (m->msi_packet)
                (*m->msi_packet)(m, i, data, data_length, m->
      msi_packet_userdata);
            break;
        }
        default: {
            handle_custom_lossless_packet(object, i, temp, len);
            break;
        }
    }
    return 0;
}
static int handle_status (void * object, int i, uint8_t status) [static]
Definition at line 1893 of file Messenger.c.
References FRIEND_CONFIRMED, FRIEND_ONLINE, Messenger::friendlist, send_online_packet(), set_friend_status(), and Friend::status.
Referenced by init_new_friend().
{
    Messenger *m = object;
    if (status) { /* Went online. */
        send_online_packet(m, i);
    } else { /* Went offline. */
        if (m->friendlist[i].status == FRIEND_ONLINE) {
            set_friend_status(m, i, FRIEND_CONFIRMED);
        }
    }
    return 0;
}
static int32_t init_new_friend (Messenger * m, const uint8_t * real_pk, uint8_t status) [static]
Definition at line 168 of file Messenger.c.
References FAERR_NOMEM, Messenger::fr_c, friend_con_connected(), friend_connection_callbacks(), Friend::friendcon_id, FRIENDCONN_STATUS_CONNECTED, Messenger::friendlist, Friend::friendrequest_lastsent, handle_custom_lossy_packet(), handle_packet(), handle_status(), i, id_copy(), Friend::is_typing, Friend::message_id, MESSENGER_CALLBACK_INDEX, new_friend_connection(), NOFRIEND, Messenger::numfriends, Friend::real_pk, realloc_friendlist(), send_online_packet(), Friend::status, Friend::statusmessage_length, Friend::userstatus, and USERSTATUS_NONE.
Referenced by m_addfriend(), and m_addfriend_norequest().
{
    /* Resize the friend list if necessary. */
    if (realloc_friendlist(m, m->numfriends + 1) != 0)
        return FAERR_NOMEM;
    memset(&(m->friendlist[m->numfriends]), 0, sizeof(Friend));
    int friendcon_id = new_friend_connection(m->fr_c, real_pk);
    if (friendcon_id == -1)
        return FAERR_NOMEM;
    uint32_t i;
    for (i = 0; i <= m->numfriends; ++i) {
        if (m->friendlist[i].status == NOFRIEND) {
            m->friendlist[i].status = status;
            m->friendlist[i].friendcon_id = friendcon_id;
            m->friendlist[i].friendrequest_lastsent = 0;
            id_copy(m->friendlist[i].real_pk, real_pk);
            m->friendlist[i].statusmessage_length = 0;
            m->friendlist[i].userstatus = USERSTATUS_NONE;
            m->friendlist[i].is_typing = 0;
            m->friendlist[i].message_id = 0;
            friend_connection_callbacks(m->fr_c, friendcon_id,
      MESSENGER_CALLBACK_INDEX, &handle_status, &
      handle_packet,
                                        &handle_custom_lossy_packet, m, i);
            if (m->numfriends == i)
                ++m->numfriends;
            if (friend_con_connected(m->fr_c, friendcon_id) ==
      FRIENDCONN_STATUS_CONNECTED) {
                send_online_packet(m, i);
            }
            return i;
        }
    }
    return FAERR_NOMEM;
}
void kill_messenger (Messenger * m)
Definition at line 1848 of file Messenger.c.
References clear_receipts(), Messenger::dht, Messenger::fr_c, Messenger::friendlist, i, kill_DHT(), kill_friend_connections(), kill_net_crypto(), kill_networking(), kill_onion(), kill_onion_announce(), kill_onion_client(), kill_TCP_server(), Messenger::net, Messenger::net_crypto, Messenger::numfriends, Messenger::onion, Messenger::onion_a, Messenger::onion_c, and Messenger::tcp_server.
Referenced by main(), tox_kill(), and tox_new().
{
    if (!m)
        return;
    uint32_t i;
    if (m->tcp_server) {
        kill_TCP_server(m->tcp_server);
    }
    kill_friend_connections(m->fr_c);
    kill_onion(m->onion);
    kill_onion_announce(m->onion_a);
    kill_onion_client(m->onion_c);
    kill_net_crypto(m->net_crypto);
    kill_DHT(m->dht);
    kill_networking(m->net);
    for (i = 0; i < m->numfriends; ++i) {
        clear_receipts(m, i);
    }
    free(m->friendlist);
    free(m);
}
int32_t m_addfriend (Messenger * m, const uint8_t * address, const uint8_t * data, uint16_t length)
Definition at line 226 of file Messenger.c.
References address_checksum(), FAERR_ALREADYSENT, FAERR_BADCHECKSUM, FAERR_NOMESSAGE, FAERR_OWNKEY, FAERR_SETNEWNOSPAM, FAERR_TOOLONG, FRIEND_ADDED, FRIEND_ADDRESS_SIZE, FRIEND_CONFIRMED, friend_id, Messenger::friendlist, Friend::friendrequest_nospam, FRIENDREQUEST_TIMEOUT, Friend::friendrequest_timeout, getfriend_id(), id_copy(), id_equal(), Friend::info, Friend::info_size, init_new_friend(), MAX_FRIEND_REQUEST_DATA_SIZE, Messenger::net_crypto, make-funny-savefile::nospam, public_key_valid(), Net_Crypto::self_public_key, and Friend::status.
Referenced by friends_list_load(), main(), parent_friend_request(), and tox_friend_add().
{
    if (length > MAX_FRIEND_REQUEST_DATA_SIZE)
        return FAERR_TOOLONG;
    uint8_t real_pk[crypto_box_PUBLICKEYBYTES];
    id_copy(real_pk, address);
    if (!public_key_valid(real_pk))
        return FAERR_BADCHECKSUM;
    uint16_t check, checksum = address_checksum(address,
      FRIEND_ADDRESS_SIZE - sizeof(checksum));
    memcpy(&check, address + crypto_box_PUBLICKEYBYTES + sizeof(uint32_t), sizeof(check));
    if (check != checksum)
        return FAERR_BADCHECKSUM;
    if (length < 1)
        return FAERR_NOMESSAGE;
    if (id_equal(real_pk, m->net_crypto->self_public_key))
        return FAERR_OWNKEY;
    int32_t friend_id = getfriend_id(m, real_pk);
    if (friend_id != -1) {
        if (m->friendlist[friend_id].status >= FRIEND_CONFIRMED)
            return FAERR_ALREADYSENT;
        uint32_t nospam;
        memcpy(&nospam, address + crypto_box_PUBLICKEYBYTES, sizeof(nospam));
        if (m->friendlist[friend_id].friendrequest_nospam == nospam)
            return FAERR_ALREADYSENT;
        m->friendlist[friend_id].friendrequest_nospam =
      nospam;
        return FAERR_SETNEWNOSPAM;
    }
    int32_t ret = init_new_friend(m, real_pk, FRIEND_ADDED);
    if (ret < 0) {
        return ret;
    }
    m->friendlist[ret].friendrequest_timeout =
      FRIENDREQUEST_TIMEOUT;
    memcpy(m->friendlist[ret].info, data, length);
    m->friendlist[ret].info_size = length;
    memcpy(&(m->friendlist[ret].friendrequest_nospam), address +
      crypto_box_PUBLICKEYBYTES, sizeof(uint32_t));
    return ret;
}
int32_t m_addfriend_norequest (Messenger * m, const uint8_t * real_pk)
Definition at line 279 of file Messenger.c.
References FAERR_ALREADYSENT, FAERR_BADCHECKSUM, FAERR_OWNKEY, FRIEND_CONFIRMED, getfriend_id(), id_equal(), init_new_friend(), Messenger::net_crypto, public_key_valid(), and Net_Crypto::self_public_key.
Referenced by child_got_request(), friends_list_load(), main(), print_request(), and tox_friend_add_norequest().
{
    if (getfriend_id(m, real_pk) != -1)
        return FAERR_ALREADYSENT;
    if (!public_key_valid(real_pk))
        return FAERR_BADCHECKSUM;
    if (id_equal(real_pk, m->net_crypto->self_public_key))
        return FAERR_OWNKEY;
    return init_new_friend(m, real_pk, FRIEND_CONFIRMED);
}
void m_callback_connectionstatus (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 812 of file Messenger.c.
References Messenger::friend_connectionstatuschange, and Messenger::friend_connectionstatuschange_userdata.
Referenced by tox_callback_friend_connection_status().
{
    m->friend_connectionstatuschange = function;
    m->friend_connectionstatuschange_userdata = userdata;
}
void m_callback_connectionstatus_internal_av (Messenger * m, void(*)(Messenger *m, uint32_t, uint8_t, void *) function, void * userdata)
Definition at line 825 of file Messenger.c.
References Messenger::friend_connectionstatuschange_internal, and Messenger::friend_connectionstatuschange_internal_userdata.
Referenced by msi_new().
{
    m->friend_connectionstatuschange_internal = function;
    m->friend_connectionstatuschange_internal_userdata =
      userdata;
}
void m_callback_core_connection (Messenger * m, void(*)(Messenger *m, unsigned int, void *) function, void * userdata)
Definition at line 819 of file Messenger.c.
References Messenger::core_connection_change, and Messenger::core_connection_change_userdata.
Referenced by tox_callback_self_connection_status().
{
    m->core_connection_change = function;
    m->core_connection_change_userdata = userdata;
}
void m_callback_friendmessage (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 773 of file Messenger.c.
References Messenger::friend_message, and Messenger::friend_message_userdata.
Referenced by main(), and tox_callback_friend_message().
{
    m->friend_message = function;
    m->friend_message_userdata = userdata;
}
void m_callback_friendrequest (Messenger * m, void(*)(Messenger *m, const uint8_t *, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 765 of file Messenger.c.
References callback_friendrequest(), and Messenger::fr.
Referenced by main(), and tox_callback_friend_request().
{
    void (*handle_friendrequest)(void *, const uint8_t *, const uint8_t *, size_t, void *) = (void *)
      function;
    callback_friendrequest(&(m->fr), handle_friendrequest, m, userdata);
}
void m_callback_group_invite (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, uint16_t) function)
Definition at line 919 of file Messenger.c.
References Messenger::group_invite.
Referenced by kill_groupchats(), and new_groupchats().
{
    m->group_invite = function;
}
void m_callback_msi_packet (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, uint16_t, void *) function, void * userdata)
Definition at line 1598 of file Messenger.c.
References Messenger::msi_packet, and Messenger::msi_packet_userdata.
Referenced by msi_kill(), and msi_new().
{
    m->msi_packet = function;
    m->msi_packet_userdata = userdata;
}
void m_callback_namechange (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 780 of file Messenger.c.
References Messenger::friend_namechange, and Messenger::friend_namechange_userdata.
Referenced by tox_callback_friend_name().
{
    m->friend_namechange = function;
    m->friend_namechange_userdata = userdata;
}
void m_callback_read_receipt (Messenger * m, void(*)(Messenger *m, uint32_t, uint32_t, void *) function, void * userdata)
Definition at line 806 of file Messenger.c.
References Messenger::read_receipt, and Messenger::read_receipt_userdata.
Referenced by tox_callback_friend_read_receipt().
{
    m->read_receipt = function;
    m->read_receipt_userdata = userdata;
}
int m_callback_rtp_packet (Messenger * m, int32_t friendnumber, uint8_t byte, int(*)(Messenger *m, uint32_t friendnumber, const uint8_t *data, uint16_t len, void *object) packet_handler_callback, void * object)
Definition at line 1644 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::function, Friend::lossy_rtp_packethandlers, Friend::object, PACKET_ID_LOSSY_RANGE_START, and PACKET_LOSSY_AV_RESERVED.
Referenced by rtp_kill(), and rtp_new().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (byte < PACKET_ID_LOSSY_RANGE_START)
        return -1;
    if (byte >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_LOSSY_AV_RESERVED))
        return -1;
    m->friendlist[friendnumber].lossy_rtp_packethandlers[byte %
      PACKET_LOSSY_AV_RESERVED].function =
        packet_handler_callback;
    m->friendlist[friendnumber].lossy_rtp_packethandlers[byte %
      PACKET_LOSSY_AV_RESERVED].object = object;
    return 0;
}
void m_callback_statusmessage (Messenger * m, void(*)(Messenger *m, uint32_t, const uint8_t *, size_t, void *) function, void * userdata)
Definition at line 787 of file Messenger.c.
References Messenger::friend_statusmessagechange, and Messenger::friend_statusmessagechange_userdata.
Referenced by main(), and tox_callback_friend_status_message().
{
    m->friend_statusmessagechange = function;
    m->friend_statusmessagechange_userdata = userdata;
}
void m_callback_typingchange (Messenger * m, void(*)(Messenger *m, uint32_t, _Bool, void *) function, void * userdata)
Definition at line 800 of file Messenger.c.
References Messenger::friend_typingchange, and Messenger::friend_typingchange_userdata.
Referenced by tox_callback_friend_typing().
{
    m->friend_typingchange = function;
    m->friend_typingchange_userdata = userdata;
}
void m_callback_userstatus (Messenger * m, void(*)(Messenger *m, uint32_t, unsigned int, void *) function, void * userdata)
Definition at line 794 of file Messenger.c.
References Messenger::friend_userstatuschange, and Messenger::friend_userstatuschange_userdata.
Referenced by tox_callback_friend_status().
{
    m->friend_userstatuschange = function;
    m->friend_userstatuschange_userdata = userdata;
}
int m_copy_self_statusmessage (const Messenger * m, uint8_t * buf)
Definition at line 664 of file Messenger.c.
References Messenger::statusmessage, and Messenger::statusmessage_length.
Referenced by tox_self_get_status_message().
{
    memcpy(buf, m->statusmessage, m->statusmessage_length);
    return m->statusmessage_length;
}
int m_copy_statusmessage (const Messenger * m, int32_t friendnumber, uint8_t * buf, uint32_t maxlen)
Definition at line 644 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, MIN, Friend::statusmessage, and Friend::statusmessage_length.
Referenced by tox_friend_get_status_message().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    int msglen = MIN(maxlen, m->friendlist[friendnumber].
      statusmessage_length);
    memcpy(buf, m->friendlist[friendnumber].statusmessage, msglen);
    memset(buf + msglen, 0, maxlen - msglen);
    return msglen;
}
int m_delfriend (Messenger * m, int32_t friendnumber)
Definition at line 379 of file Messenger.c.
References clear_receipts(), FAERR_NOMEM, Messenger::fr, Messenger::fr_c, friend_con_connected(), friend_connection_callbacks(), Messenger::friend_connectionstatuschange_internal, Messenger::friend_connectionstatuschange_internal_userdata, friend_not_valid(), Friend::friendcon_id, FRIENDCONN_STATUS_CONNECTED, Messenger::friendlist, i, kill_friend_connection(), MESSENGER_CALLBACK_INDEX, NOFRIEND, Messenger::numfriends, Friend::real_pk, realloc_friendlist(), remove_request_received(), send_offline_packet(), and Friend::status.
Referenced by messenger_suite(), START_TEST(), and tox_friend_delete().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friend_connectionstatuschange_internal)
        m->friend_connectionstatuschange_internal(m, friendnumber, 0,
       m->friend_connectionstatuschange_internal_userdata);
    clear_receipts(m, friendnumber);
    remove_request_received(&(m->fr), m->friendlist[friendnumber].
      real_pk);
    friend_connection_callbacks(m->fr_c, m->
      friendlist[friendnumber].friendcon_id,
      MESSENGER_CALLBACK_INDEX, 0, 0, 0, 0, 0);
    if (friend_con_connected(m->fr_c, m->friendlist[friendnumber].
      friendcon_id) == FRIENDCONN_STATUS_CONNECTED) {
        send_offline_packet(m, m->friendlist[friendnumber].
      friendcon_id);
    }
    kill_friend_connection(m->fr_c, m->friendlist[friendnumber].
      friendcon_id);
    memset(&(m->friendlist[friendnumber]), 0, sizeof(Friend));
    uint32_t i;
    for (i = m->numfriends; i != 0; --i) {
        if (m->friendlist[i - 1].status != NOFRIEND)
            break;
    }
    m->numfriends = i;
    if (realloc_friendlist(m, m->numfriends) != 0)
        return FAERR_NOMEM;
    return 0;
}
int m_friend_exists (const Messenger * m, int32_t friendnumber)
Definition at line 437 of file Messenger.c.
References friend_not_valid().
Referenced by messenger_suite(), START_TEST(), and tox_friend_exists().
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    return 1;
}
int m_get_friend_connectionstatus (const Messenger * m, int32_t friendnumber)
Definition at line 412 of file Messenger.c.
References CONNECTION_NONE, CONNECTION_TCP, CONNECTION_UDP, CONNECTION_UNKNOWN, crypto_connection_status(), Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, Messenger::net_crypto, and Friend::status.
Referenced by check_friend_tcp_udp(), messenger_suite(), START_TEST(), and tox_friend_get_connection_status().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].status == FRIEND_ONLINE) {
        _Bool direct_connected = 0;
        unsigned int num_online_relays = 0;
        crypto_connection_status(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                 m->friendlist[friendnumber].
      friendcon_id), &direct_connected, &num_online_relays);
        if (direct_connected) {
            return CONNECTION_UDP;
        } else {
            if (num_online_relays) {
                return CONNECTION_TCP;
            } else {
                return CONNECTION_UNKNOWN;
            }
        }
    } else {
        return CONNECTION_NONE;
    }
}
int m_get_istyping (const Messenger * m, int32_t friendnumber)
Definition at line 715 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::is_typing.
Referenced by tox_friend_get_typing().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].is_typing;
}
uint64_t m_get_last_online (const Messenger * m, int32_t friendnumber)
Definition at line 689 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::last_seen_time.
Referenced by tox_friend_get_last_online().
{
    if (friend_not_valid(m, friendnumber))
        return UINT64_MAX;
    return m->friendlist[friendnumber].last_seen_time;
}
int m_get_name_size (const Messenger * m, int32_t friendnumber)
Definition at line 579 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::name_length.
Referenced by tox_friend_get_name_size().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].name_length;
}
int m_get_self_name_size (const Messenger * m)
Definition at line 587 of file Messenger.c.
References Messenger::name_length.
Referenced by tox_self_get_name_size().
{
    return m->name_length;
}
int m_get_self_statusmessage_size (const Messenger * m)
Definition at line 659 of file Messenger.c.
References Messenger::statusmessage_length.
Referenced by tox_self_get_status_message_size().
{
    return m->statusmessage_length;
}
uint8_t m_get_self_userstatus (const Messenger * m)
Definition at line 684 of file Messenger.c.
References Messenger::userstatus.
Referenced by tox_self_get_status().
{
    return m->userstatus;
}
int m_get_statusmessage_size (const Messenger * m, int32_t friendnumber)
Definition at line 633 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, and Friend::statusmessage_length.
Referenced by START_TEST(), tox_friend_get_status_message(), and tox_friend_get_status_message_size().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    return m->friendlist[friendnumber].statusmessage_length;
}
uint8_t m_get_userstatus (const Messenger * m, int32_t friendnumber)
Definition at line 670 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::userstatus, USERSTATUS_INVALID, and USERSTATUS_NONE.
Referenced by tox_friend_get_status().
{
    if (friend_not_valid(m, friendnumber))
        return USERSTATUS_INVALID;
    uint8_t status = m->friendlist[friendnumber].userstatus;
    if (status >= USERSTATUS_INVALID) {
        status = USERSTATUS_NONE;
    }
    return status;
}
int m_msi_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint16_t length)
Definition at line 1610 of file Messenger.c.
References PACKET_ID_MSI, and write_cryptpacket_id().
Referenced by send_message().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_MSI, data, length, 0);
}
int m_send_message_generic (Messenger * m, int32_t friendnumber, uint8_t type, const uint8_t * message, uint32_t length, uint32_t * message_id)
Definition at line 454 of file Messenger.c.
References add_receipt(), Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, MESSAGE_ACTION, Friend::message_id, Receipts::msg_id, Messenger::net_crypto, PACKET_ID_MESSAGE, Receipts::packet_num, Friend::status, and write_cryptpacket().
Referenced by main(), print_message(), START_TEST(), and tox_friend_send_message().
{
    if (type > MESSAGE_ACTION)
        return -5;
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length >= MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -3;
    uint8_t packet[length + 1];
    packet[0] = type + PACKET_ID_MESSAGE;
    if (length != 0)
        memcpy(packet + 1, message, length);
    int64_t packet_num = write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                                           m->friendlist[friendnumber].
      friendcon_id), packet, length + 1, 0);
    if (packet_num == -1)
        return -4;
    uint32_t msg_id = ++m->friendlist[friendnumber].message_id;
    add_receipt(m, friendnumber, packet_num, msg_id);
    if (message_id)
        *message_id = msg_id;
    return 0;
}
static int m_sendname (const Messenger * m, int32_t friendnumber, const uint8_t * name, uint16_t length) [static]
Definition at line 494 of file Messenger.c.
References MAX_NAME_LENGTH, PACKET_ID_NICKNAME, and write_cryptpacket_id().
Referenced by do_friends().
{
    if (length > MAX_NAME_LENGTH)
        return 0;
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_NICKNAME, name, length, 0);
}
int m_set_statusmessage (Messenger * m, const uint8_t * status, uint16_t length)
Definition at line 592 of file Messenger.c.
References Messenger::friendlist, i, MAX_STATUSMESSAGE_LENGTH, Messenger::numfriends, Messenger::statusmessage, Messenger::statusmessage_length, and Friend::statusmessage_sent.
Referenced by messenger_load_state_callback(), START_TEST(), and tox_self_set_status_message().
{
    if (length > MAX_STATUSMESSAGE_LENGTH)
        return -1;
    if (m->statusmessage_length == length && (length == 0 || memcmp(m->
      statusmessage, status, length) == 0))
        return 0;
    if (length)
        memcpy(m->statusmessage, status, length);
    m->statusmessage_length = length;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].statusmessage_sent = 0;
    return 0;
}
int m_set_userstatus (Messenger * m, uint8_t status)
Definition at line 613 of file Messenger.c.
References Messenger::friendlist, i, Messenger::numfriends, Messenger::userstatus, USERSTATUS_INVALID, and Friend::userstatus_sent.
Referenced by messenger_load_state_callback(), messenger_suite(), and tox_self_set_status().
{
    if (status >= USERSTATUS_INVALID)
        return -1;
    if (m->userstatus == status)
        return 0;
    m->userstatus = status;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].userstatus_sent = 0;
    return 0;
}
int m_set_usertyping (Messenger * m, int32_t friendnumber, uint8_t is_typing)
Definition at line 697 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, Friend::user_istyping, and Friend::user_istyping_sent.
Referenced by tox_self_set_typing().
{
    if (is_typing != 0 && is_typing != 1)
        return -1;
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (m->friendlist[friendnumber].user_istyping == is_typing)
        return 0;
    m->friendlist[friendnumber].user_istyping = is_typing;
    m->friendlist[friendnumber].user_istyping_sent = 0;
    return 0;
}
int messenger_load (Messenger * m, const uint8_t * data, uint32_t length)
Definition at line 2744 of file Messenger.c.
References lendian_to_host32(), load_state(), messenger_load_state_callback(), MESSENGER_STATE_COOKIE_GLOBAL, and MESSENGER_STATE_COOKIE_TYPE.
Referenced by main(), START_TEST(), and tox_new().
{
    uint32_t data32[2];
    uint32_t cookie_len = sizeof(data32);
    if (length < cookie_len)
        return -1;
    memcpy(data32, data, sizeof(uint32_t));
    lendian_to_host32(data32 + 1, data + sizeof(uint32_t));
    if (!data32[0] && (data32[1] == MESSENGER_STATE_COOKIE_GLOBAL))
        return load_state(messenger_load_state_callback, m,
      data + cookie_len,
                          length - cookie_len, MESSENGER_STATE_COOKIE_TYPE);
    else
        return -1;
}
static int messenger_load_state_callback (void * outer, const uint8_t * data, uint32_t length, uint16_t type) [static]
Definition at line 2648 of file Messenger.c.
References Messenger::dht, DHT_load(), Messenger::fr, friends_list_load(), Messenger::has_added_relays, i, Node_format::ip_port, load_secret_key(), Messenger::loaded_relays, m_set_statusmessage(), m_set_userstatus(), MAX_NAME_LENGTH, MAX_STATUSMESSAGE_LENGTH, MESSENGER_STATE_TYPE_DHT, MESSENGER_STATE_TYPE_END, MESSENGER_STATE_TYPE_FRIENDS, MESSENGER_STATE_TYPE_NAME, MESSENGER_STATE_TYPE_NOSPAMKEYS, MESSENGER_STATE_TYPE_PATH_NODE, MESSENGER_STATE_TYPE_STATUS, MESSENGER_STATE_TYPE_STATUSMESSAGE, MESSENGER_STATE_TYPE_TCP_RELAY, Messenger::net_crypto, num, NUM_SAVED_PATH_NODES, NUM_SAVED_TCP_RELAYS, onion_add_bs_path_node(), Messenger::onion_c, Node_format::public_key, Net_Crypto::self_public_key, set_nospam(), setname(), and unpack_nodes().
Referenced by messenger_load().
{
    Messenger *m = outer;
    switch (type) {
        case MESSENGER_STATE_TYPE_NOSPAMKEYS:
            if (length == crypto_box_PUBLICKEYBYTES + crypto_box_SECRETKEYBYTES + sizeof(uint32_t)) {
                set_nospam(&(m->fr), *(uint32_t *)data);
                load_secret_key(m->net_crypto, (&data[sizeof(uint32_t)]) +
      crypto_box_PUBLICKEYBYTES);
                if (memcmp((&data[sizeof(uint32_t)]), m->net_crypto->
      self_public_key, crypto_box_PUBLICKEYBYTES) != 0) {
                    return -1;
                }
            } else
                return -1; /* critical */
            break;
        case MESSENGER_STATE_TYPE_DHT:
            DHT_load(m->dht, data, length);
            break;
        case MESSENGER_STATE_TYPE_FRIENDS:
            friends_list_load(m, data, length);
            break;
        case MESSENGER_STATE_TYPE_NAME:
            if ((length > 0) && (length <= MAX_NAME_LENGTH)) {
                setname(m, data, length);
            }
            break;
        case MESSENGER_STATE_TYPE_STATUSMESSAGE:
            if ((length > 0) && (length < MAX_STATUSMESSAGE_LENGTH)) {
                m_set_statusmessage(m, data, length);
            }
            break;
        case MESSENGER_STATE_TYPE_STATUS:
            if (length == 1) {
                m_set_userstatus(m, *data);
            }
            break;
        case MESSENGER_STATE_TYPE_TCP_RELAY: {
            if (length == 0) {
                break;
            }
            unpack_nodes(m->loaded_relays,
      NUM_SAVED_TCP_RELAYS, 0, data, length, 1);
            m->has_added_relays = 0;
            break;
        }
        case MESSENGER_STATE_TYPE_PATH_NODE: {
            Node_format nodes[NUM_SAVED_PATH_NODES];
            if (length == 0) {
                break;
            }
            int i, num = unpack_nodes(nodes,
      NUM_SAVED_PATH_NODES, 0, data, length, 0);
            for (i = 0; i < num; ++i) {
                onion_add_bs_path_node(m->onion_c, nodes[i].
      ip_port, nodes[i].public_key);
            }
            break;
        }
        case MESSENGER_STATE_TYPE_END: {
            if (length != 0) {
                return -1;
            }
            return -2;
            break;
        }
#ifdef DEBUG
        default:
            fprintf(stderr, "Load state: contains unrecognized part (len %u, type %u)\n",
                    length, type);
            break;
#endif
    }
    return 0;
}
uint32_t messenger_run_interval (const Messenger * m)
Definition at line 2268 of file Messenger.c.
References crypto_run_interval(), MIN_RUN_INTERVAL, and Messenger::net_crypto.
Referenced by tox_iteration_interval().
{
    uint32_t crypto_interval = crypto_run_interval(m->
      net_crypto);
    if (crypto_interval > MIN_RUN_INTERVAL) {
        return MIN_RUN_INTERVAL;
    } else {
        return crypto_interval;
    }
}
void messenger_save (const Messenger * m, uint8_t * data)
Definition at line 2565 of file Messenger.c.
References copy_connected_tcp_relays(), make-funny-savefile::data, Messenger::dht, DHT_save(), DHT_size(), Messenger::fr, friends_list_save(), get_nospam(), host_to_lendian32(), messenger_size(), MESSENGER_STATE_COOKIE_GLOBAL, MESSENGER_STATE_TYPE_DHT, MESSENGER_STATE_TYPE_END, MESSENGER_STATE_TYPE_FRIENDS, MESSENGER_STATE_TYPE_NAME, MESSENGER_STATE_TYPE_NOSPAMKEYS, MESSENGER_STATE_TYPE_PATH_NODE, MESSENGER_STATE_TYPE_STATUS, MESSENGER_STATE_TYPE_STATUSMESSAGE, MESSENGER_STATE_TYPE_TCP_RELAY, Messenger::name, Messenger::name_length, Messenger::net_crypto, num, NUM_SAVED_PATH_NODES, NUM_SAVED_TCP_RELAYS, onion_backup_nodes(), Messenger::onion_c, pack_nodes(), packed_node_size(), save_keys(), saved_friendslist_size(), Messenger::statusmessage, Messenger::statusmessage_length, TCP_INET6, Messenger::userstatus, and z_state_save_subheader().
Referenced by main(), START_TEST(), and tox_get_savedata().
{
    memset(data, 0, messenger_size(m));
    uint32_t len;
    uint16_t type;
    uint32_t size32 = sizeof(uint32_t);
    memset(data, 0, size32);
    data += size32;
    host_to_lendian32(data, MESSENGER_STATE_COOKIE_GLOBAL
      );
    data += size32;
#ifdef DEBUG
    assert(sizeof(get_nospam(&(m->fr))) == sizeof(uint32_t));
#endif
    len = size32 + crypto_box_PUBLICKEYBYTES + crypto_box_SECRETKEYBYTES;
    type = MESSENGER_STATE_TYPE_NOSPAMKEYS;
    data = z_state_save_subheader(data, len, type);
    *(uint32_t *)data = get_nospam(&(m->fr));
    save_keys(m->net_crypto, data + size32);
    data += len;
    len = saved_friendslist_size(m);
    type = MESSENGER_STATE_TYPE_FRIENDS;
    data = z_state_save_subheader(data, len, type);
    friends_list_save(m, data);
    data += len;
    len = m->name_length;
    type = MESSENGER_STATE_TYPE_NAME;
    data = z_state_save_subheader(data, len, type);
    memcpy(data, m->name, len);
    data += len;
    len = m->statusmessage_length;
    type = MESSENGER_STATE_TYPE_STATUSMESSAGE;
    data = z_state_save_subheader(data, len, type);
    memcpy(data, m->statusmessage, len);
    data += len;
    len = 1;
    type = MESSENGER_STATE_TYPE_STATUS;
    data = z_state_save_subheader(data, len, type);
    *data = m->userstatus;
    data += len;
    len = DHT_size(m->dht);
    type = MESSENGER_STATE_TYPE_DHT;
    data = z_state_save_subheader(data, len, type);
    DHT_save(m->dht, data);
    data += len;
    Node_format relays[NUM_SAVED_TCP_RELAYS];
    type = MESSENGER_STATE_TYPE_TCP_RELAY;
    uint8_t *temp_data = data;
    data = z_state_save_subheader(temp_data, 0, type);
    unsigned int num = copy_connected_tcp_relays(m->
      net_crypto, relays, NUM_SAVED_TCP_RELAYS);
    int l = pack_nodes(data, NUM_SAVED_TCP_RELAYS *
      packed_node_size(TCP_INET6), relays, num);
    if (l > 0) {
        len = l;
        data = z_state_save_subheader(temp_data, len, type);
        data += len;
    }
    Node_format nodes[NUM_SAVED_PATH_NODES];
    type = MESSENGER_STATE_TYPE_PATH_NODE;
    temp_data = data;
    data = z_state_save_subheader(data, 0, type);
    memset(nodes, 0, sizeof(nodes));
    num = onion_backup_nodes(m->onion_c, nodes,
      NUM_SAVED_PATH_NODES);
    l = pack_nodes(data, NUM_SAVED_PATH_NODES *
      packed_node_size(TCP_INET6), nodes, num);
    if (l > 0) {
        len = l;
        data = z_state_save_subheader(temp_data, len, type);
        data += len;
    }
    z_state_save_subheader(data, 0,
      MESSENGER_STATE_TYPE_END);
}
uint32_t messenger_size (const Messenger * m)
Definition at line 2540 of file Messenger.c.
References Messenger::dht, DHT_size(), Messenger::name_length, NUM_SAVED_PATH_NODES, NUM_SAVED_TCP_RELAYS, packed_node_size(), saved_friendslist_size(), Messenger::statusmessage_length, and TCP_INET6.
Referenced by main(), messenger_save(), START_TEST(), and tox_get_savedata_size().
{
    uint32_t size32 = sizeof(uint32_t), sizesubhead = size32 * 2;
    return size32 * 2 // global cookie
             + sizesubhead + sizeof(uint32_t) + crypto_box_PUBLICKEYBYTES + crypto_box_SECRETKEYBYTES
             + sizesubhead + DHT_size(m->dht) // DHT
             + sizesubhead + saved_friendslist_size(m) // Friendlist itself.
             + sizesubhead + m->name_length // Own nickname.
             + sizesubhead + m->statusmessage_length // status message
             + sizesubhead + 1 // status
             + sizesubhead + NUM_SAVED_TCP_RELAYS *
      packed_node_size(TCP_INET6) //TCP relays
             + sizesubhead + NUM_SAVED_PATH_NODES *
      packed_node_size(TCP_INET6) //saved path nodes
             + sizesubhead;
}
long int new_filesender (const Messenger * m, int32_t friendnumber, uint32_t file_type, uint64_t filesize, const uint8_t * file_id, const uint8_t * filename, uint16_t filename_length)
Definition at line 1070 of file Messenger.c.
References FILE_ID_LENGTH, FILE_PAUSE_NOT, Friend::file_sending, file_sendrequest(), FILESTATUS_NONE, FILESTATUS_NOT_ACCEPTED, friend_not_valid(), Messenger::friendlist, i, File_Transfers::id, MAX_CONCURRENT_FILE_PIPES, MAX_FILENAME_LENGTH, Friend::num_sending_files, File_Transfers::paused, File_Transfers::requested, File_Transfers::size, File_Transfers::slots_allocated, File_Transfers::status, and File_Transfers::transferred.
Referenced by tox_file_send().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (filename_length > MAX_FILENAME_LENGTH)
        return -2;
    uint32_t i;
    for (i = 0; i < MAX_CONCURRENT_FILE_PIPES; ++i) {
        if (m->friendlist[friendnumber].file_sending[i].
      status == FILESTATUS_NONE)
            break;
    }
    if (i == MAX_CONCURRENT_FILE_PIPES)
        return -3;
    if (file_sendrequest(m, friendnumber, i, file_type, filesize, file_id, filename,
      filename_length) == 0)
        return -4;
    struct File_Transfers *ft = &m->friendlist[friendnumber].
      file_sending[i];
    ft->status = FILESTATUS_NOT_ACCEPTED;
    ft->size = filesize;
    ft->transferred = 0;
    ft->requested = 0;
    ft->slots_allocated = 0;
    ft->paused = FILE_PAUSE_NOT;
    memcpy(ft->id, file_id, FILE_ID_LENGTH);
    ++m->friendlist[friendnumber].num_sending_files;
    return i;
}
Messenger* new_messenger (Messenger_Options * options, unsigned int * error)
Definition at line 1751 of file Messenger.c.
References Messenger::dht, Messenger::fr, Messenger::fr_c, friend_already_added(), friendreq_init(), ip, ip_init(), Messenger_Options::ipv6enabled, kill_DHT(), kill_friend_connections(), kill_net_crypto(), kill_networking(), kill_onion(), kill_onion_announce(), kill_onion_client(), m, MESSENGER_ERROR_NONE, MESSENGER_ERROR_OTHER, MESSENGER_ERROR_PORT, MESSENGER_ERROR_TCP_SERVER, Messenger::net, Messenger::net_crypto, new_DHT(), new_friend_connections(), new_net_crypto(), new_networking_ex(), new_onion(), new_onion_announce(), new_onion_client(), new_TCP_server(), Messenger::onion, Messenger::onion_a, Messenger::onion_c, Messenger::options, Messenger_Options::port_range, Messenger_Options::proxy_info, random_int(), DHT::self_secret_key, set_filter_function(), set_nospam(), Messenger::tcp_server, Messenger_Options::tcp_server_port, and Messenger_Options::udp_disabled.
Referenced by main(), and tox_new().
{
    Messenger *m = calloc(1, sizeof(Messenger));
    if (error)
        *error = MESSENGER_ERROR_OTHER;
    if (! m)
        return NULL;
    unsigned int net_err = 0;
    if (options->udp_disabled) {
        /* this is the easiest way to completely disable UDP without changing too much code. */
        m->net = calloc(1, sizeof(Networking_Core));
    } else {
        IP ip;
        ip_init(&ip, options->ipv6enabled);
        m->net = new_networking_ex(ip, options->port_range[0], options->
      port_range[1], &net_err);
    }
    if (m->net == NULL) {
        free(m);
        if (error && net_err == 1) {
            *error = MESSENGER_ERROR_PORT;
        }
        return NULL;
    }
    m->dht = new_DHT(m->net);
    if (m->dht == NULL) {
        kill_networking(m->net);
        free(m);
        return NULL;
    }
    m->net_crypto = new_net_crypto(m->dht, &options->
      proxy_info);
    if (m->net_crypto == NULL) {
        kill_networking(m->net);
        kill_DHT(m->dht);
        free(m);
        return NULL;
    }
    m->onion = new_onion(m->dht);
    m->onion_a = new_onion_announce(m->dht);
    m->onion_c = new_onion_client(m->net_crypto);
    m->fr_c = new_friend_connections(m->onion_c);
    if (!(m->onion && m->onion_a && m->onion_c)) {
        kill_friend_connections(m->fr_c);
        kill_onion(m->onion);
        kill_onion_announce(m->onion_a);
        kill_onion_client(m->onion_c);
        kill_net_crypto(m->net_crypto);
        kill_DHT(m->dht);
        kill_networking(m->net);
        free(m);
        return NULL;
    }
    if (options->tcp_server_port) {
        m->tcp_server = new_TCP_server(options->
      ipv6enabled, 1, &options->tcp_server_port, m->dht->
      self_secret_key, m->onion);
        if (m->tcp_server == NULL) {
            kill_friend_connections(m->fr_c);
            kill_onion(m->onion);
            kill_onion_announce(m->onion_a);
            kill_onion_client(m->onion_c);
            kill_net_crypto(m->net_crypto);
            kill_DHT(m->dht);
            kill_networking(m->net);
            free(m);
            if (error)
                *error = MESSENGER_ERROR_TCP_SERVER;
            return NULL;
        }
    }
    m->options = *options;
    friendreq_init(&(m->fr), m->fr_c);
    set_nospam(&(m->fr), random_int());
    set_filter_function(&(m->fr), &friend_already_added, m);
    if (error)
        *error = MESSENGER_ERROR_NONE;
    return m;
}
int realloc_friendlist (Messenger * m, uint32_t num)
Definition at line 59 of file Messenger.c.
References Messenger::friendlist.
Referenced by init_new_friend(), and m_delfriend().
{
    if (num == 0) {
        free(m->friendlist);
        m->friendlist = NULL;
        return 0;
    }
    Friend *newfriendlist = realloc(m->friendlist, num * sizeof(
      Friend));
    if (newfriendlist == NULL)
        return -1;
    m->friendlist = newfriendlist;
    return 0;
}
static uint32_t saved_friendslist_size (const Messenger * m) [static]
Definition at line 2452 of file Messenger.c.
References count_friendlist().
Referenced by messenger_save(), and messenger_size().
{
    return count_friendlist(m) * sizeof(struct SAVED_FRIEND);
}
int send_custom_lossless_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint32_t length)
Definition at line 1714 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, Messenger::net_crypto, PACKET_ID_LOSSLESS_RANGE_SIZE, PACKET_ID_LOSSLESS_RANGE_START, Friend::status, and write_cryptpacket().
Referenced by tox_friend_send_lossless_packet().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (data[0] < PACKET_ID_LOSSLESS_RANGE_START)
        return -3;
    if (data[0] >= (PACKET_ID_LOSSLESS_RANGE_START +
      PACKET_ID_LOSSLESS_RANGE_SIZE))
        return -3;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -4;
    if (write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                          m->friendlist[friendnumber].friendcon_id),
      data, length, 1) == -1) {
        return -5;
    } else {
        return 0;
    }
}
int send_custom_lossy_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint32_t length)
Definition at line 1663 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, Messenger::net_crypto, PACKET_ID_LOSSY_RANGE_SIZE, PACKET_ID_LOSSY_RANGE_START, send_lossy_cryptpacket(), and Friend::status.
Referenced by rtp_send_msg(), and tox_friend_send_lossy_packet().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length == 0 || length > MAX_CRYPTO_DATA_SIZE)
        return -2;
    if (data[0] < PACKET_ID_LOSSY_RANGE_START)
        return -3;
    if (data[0] >= (PACKET_ID_LOSSY_RANGE_START +
      PACKET_ID_LOSSY_RANGE_SIZE))
        return -3;
    if (m->friendlist[friendnumber].status != FRIEND_ONLINE)
        return -4;
    if (send_lossy_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                               m->friendlist[friendnumber].
      friendcon_id), data, length) == -1) {
        return -5;
    } else {
        return 0;
    }
}
int send_file_control_packet (const Messenger * m, int32_t friendnumber, uint8_t send_receive, uint8_t filenumber, uint8_t control_type, uint8_t * data, uint16_t data_length)
Definition at line 1106 of file Messenger.c.
References MAX_CRYPTO_DATA_SIZE, PACKET_ID_FILE_CONTROL, and write_cryptpacket_id().
Referenced by file_control(), file_seek(), and handle_filecontrol().
{
    if ((unsigned int)(1 + 3 + data_length) > MAX_CRYPTO_DATA_SIZE)
        return -1;
    uint8_t packet[3 + data_length];
    packet[0] = send_receive;
    packet[1] = filenumber;
    packet[2] = control_type;
    if (data_length) {
        memcpy(packet + 3, data, data_length);
    }
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_FILE_CONTROL, packet, sizeof(packet), 0);
}
static int64_t send_file_data_packet (const Messenger * m, int32_t friendnumber, uint8_t filenumber, const uint8_t * data, uint16_t length) [static]
Definition at line 1287 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), Friend::friendcon_id, Messenger::friendlist, Messenger::net_crypto, PACKET_ID_FILE_DATA, and write_cryptpacket().
Referenced by file_data().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    uint8_t packet[2 + length];
    packet[0] = PACKET_ID_FILE_DATA;
    packet[1] = filenumber;
    if (length) {
        memcpy(packet + 2, data, length);
    }
    return write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                             m->friendlist[friendnumber].friendcon_id), packet,
      sizeof(packet), 1);
}
int send_group_invite_packet (const Messenger * m, int32_t friendnumber, const uint8_t * data, uint16_t length)
Definition at line 930 of file Messenger.c.
References PACKET_ID_INVITE_GROUPCHAT, and write_cryptpacket_id().
Referenced by invite_friend(), and join_groupchat().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_INVITE_GROUPCHAT, data, length, 0);
}
static int send_offline_packet (Messenger * m, int friendcon_id) [static]
Definition at line 157 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), Messenger::net_crypto, PACKET_ID_OFFLINE, and write_cryptpacket().
Referenced by m_delfriend().
{
    uint8_t packet = PACKET_ID_OFFLINE;
    return write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c, friendcon_id), &packet,
                             sizeof(packet), 0) != -1;
}
static int send_online_packet (Messenger * m, int32_t friendnumber) [static]
Definition at line 147 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), Friend::friendcon_id, Messenger::friendlist, Messenger::net_crypto, PACKET_ID_ONLINE, and write_cryptpacket().
Referenced by handle_packet(), handle_status(), and init_new_friend().
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    uint8_t packet = PACKET_ID_ONLINE;
    return write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                             m->friendlist[friendnumber].friendcon_id), &packet,
      sizeof(packet), 0) != -1;
}
static int send_statusmessage (const Messenger * m, int32_t friendnumber, const uint8_t * status, uint16_t length) [static]
Definition at line 723 of file Messenger.c.
References PACKET_ID_STATUSMESSAGE, and write_cryptpacket_id().
Referenced by do_friends().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_STATUSMESSAGE, status, length, 0);
}
static int send_user_istyping (const Messenger * m, int32_t friendnumber, uint8_t is_typing) [static]
Definition at line 733 of file Messenger.c.
References PACKET_ID_TYPING, and write_cryptpacket_id().
Referenced by do_friends().
{
    uint8_t typing = is_typing;
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_TYPING, &typing, sizeof(typing), 0);
}
static int send_userstatus (const Messenger * m, int32_t friendnumber, uint8_t status) [static]
Definition at line 728 of file Messenger.c.
References PACKET_ID_USERSTATUS, and write_cryptpacket_id().
Referenced by do_friends().
{
    return write_cryptpacket_id(m, friendnumber,
      PACKET_ID_USERSTATUS, &status, sizeof(status), 0);
}
void set_friend_status (Messenger * m, int32_t friendnumber, uint8_t status) [static]
Definition at line 887 of file Messenger.c.
References check_friend_connectionstatus(), Messenger::friendlist, and Friend::status.
Referenced by check_friend_request_timed_out(), do_friends(), handle_packet(), and handle_status().
{
    check_friend_connectionstatus(m, friendnumber,
      status);
    m->friendlist[friendnumber].status = status;
}
static int set_friend_statusmessage (const Messenger * m, int32_t friendnumber, const uint8_t * status, uint16_t length) [static]
Definition at line 739 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, MAX_STATUSMESSAGE_LENGTH, Friend::statusmessage, and Friend::statusmessage_length.
Referenced by friends_list_load(), and handle_packet().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length > MAX_STATUSMESSAGE_LENGTH)
        return -1;
    if (length)
        memcpy(m->friendlist[friendnumber].statusmessage,
      status, length);
    m->friendlist[friendnumber].statusmessage_length = length;
    return 0;
}
static void set_friend_typing (const Messenger * m, int32_t friendnumber, uint8_t is_typing) [static]
Definition at line 759 of file Messenger.c.
References Messenger::friendlist, and Friend::is_typing.
Referenced by handle_packet().
{
    m->friendlist[friendnumber].is_typing = is_typing;
}
static void set_friend_userstatus (const Messenger * m, int32_t friendnumber, uint8_t status) [static]
Definition at line 754 of file Messenger.c.
References Messenger::friendlist, and Friend::userstatus.
Referenced by friends_list_load(), and handle_packet().
{
    m->friendlist[friendnumber].userstatus = status;
}
int setfriendname (Messenger * m, int32_t friendnumber, const uint8_t * name, uint16_t length)
Definition at line 507 of file Messenger.c.
References friend_not_valid(), Messenger::friendlist, MAX_NAME_LENGTH, Friend::name, and Friend::name_length.
Referenced by friends_list_load().
{
    if (friend_not_valid(m, friendnumber))
        return -1;
    if (length > MAX_NAME_LENGTH || length == 0)
        return -1;
    m->friendlist[friendnumber].name_length = length;
    memcpy(m->friendlist[friendnumber].name, name, length);
    return 0;
}
int setname (Messenger * m, const uint8_t * name, uint16_t length)
Definition at line 528 of file Messenger.c.
References Messenger::friendlist, i, MAX_NAME_LENGTH, Messenger::name, Messenger::name_length, Friend::name_sent, and Messenger::numfriends.
Referenced by main(), messenger_load_state_callback(), messenger_suite(), START_TEST(), and tox_self_set_name().
{
    if (length > MAX_NAME_LENGTH)
        return -1;
    if (m->name_length == length && (length == 0 || memcmp(name, m->
      name, length) == 0))
        return 0;
    if (length)
        memcpy(m->name, name, length);
    m->name_length = length;
    uint32_t i;
    for (i = 0; i < m->numfriends; ++i)
        m->friendlist[i].name_sent = 0;
    return 0;
}
static int write_cryptpacket_id (const Messenger * m, int32_t friendnumber, uint8_t packet_id, const uint8_t * data, uint32_t length, uint8_t congestion_control) [static]
Definition at line 893 of file Messenger.c.
References Messenger::fr_c, friend_connection_crypt_connection_id(), friend_not_valid(), FRIEND_ONLINE, Friend::friendcon_id, Messenger::friendlist, MAX_CRYPTO_DATA_SIZE, Messenger::net_crypto, Friend::status, and write_cryptpacket().
Referenced by file_sendrequest(), m_msi_packet(), m_sendname(), send_file_control_packet(), send_group_invite_packet(), send_statusmessage(), send_user_istyping(), and send_userstatus().
{
    if (friend_not_valid(m, friendnumber))
        return 0;
    if (length >= MAX_CRYPTO_DATA_SIZE || m->friendlist[friendnumber].
      status != FRIEND_ONLINE)
        return 0;
    uint8_t packet[length + 1];
    packet[0] = packet_id;
    if (length != 0)
        memcpy(packet + 1, data, length);
    return write_cryptpacket(m->net_crypto,
      friend_connection_crypt_connection_id(m->
      fr_c,
                             m->friendlist[friendnumber].friendcon_id), packet,
      length + 1, congestion_control) != -1;
}
static uint8_t* z_state_save_subheader (uint8_t * data, uint32_t len, uint16_t type) [static]
Definition at line 2555 of file Messenger.c.
References make-funny-savefile::data, host_to_lendian32(), host_tolendian16, and MESSENGER_STATE_COOKIE_TYPE.
Referenced by messenger_save().
{
    host_to_lendian32(data, len);
    data += sizeof(uint32_t);
    host_to_lendian32(data, (host_tolendian16(
      MESSENGER_STATE_COOKIE_TYPE) << 16) |
      host_tolendian16(type));
    data += sizeof(uint32_t);
    return data;
}