auto_tests/onion_test.c File Reference
#include <sys/types.h>
*
#include <stdint.h>
*
#include <string.h>
*
#include <check.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include `../toxcore/onion.h`
*
#include `../toxcore/onion_announce.h`
*
#include `../toxcore/onion_client.h`
*
#include `../toxcore/util.h`
*
#include `helpers.h`
*
#include <unistd.h>
*
Data Structures
struct Onions
Macros
#define c_sleep(x) usleep(1000*x)
#define NUM_ONIONS 50
#define NUM_FIRST 7
#define NUM_LAST 37
Functions
void do_onion (Onion *onion)
static int handle_test_1 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_test_2 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_test_3 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
static int handle_test_4 (void *object, IP_Port source, const uint8_t *packet, uint16_t length)
START_TEST (test_basic)
Onions * new_onions (uint16_t port)
void do_onions (Onions *on)
void kill_onions (Onions *on)
void dht_ip_callback (void *object, int32_t number, IP_Port ip_port)
static void dht_pk_callback (void *object, int32_t number, const uint8_t *dht_public_key)
START_TEST (test_announce)
END_TEST Suite * onion_suite (void)
int main (int argc, char *argv[])
Variables
static int handled_test_1
static int handled_test_2
uint8_t sb_data [ONION_ANNOUNCE_SENDBACK_DATA_LENGTH]
static int handled_test_3
uint8_t test_3_pub_key [crypto_box_PUBLICKEYBYTES]
uint8_t test_3_ping_id [crypto_hash_sha256_BYTES]
uint8_t nonce [crypto_box_NONCEBYTES]
static int handled_test_4
_Bool first_ip
_Bool last_ip
_Bool first
_Bool last
uint8_t first_dht_pk [crypto_box_PUBLICKEYBYTES]
uint8_t last_dht_pk [crypto_box_PUBLICKEYBYTES]
Macro Definition Documentation
#define c_sleep(x) usleep(1000*x)
Definition at line 23 of file onion_test.c.
Referenced by START_TEST().
#define NUM_FIRST 7
Definition at line 309 of file onion_test.c.
Referenced by dht_ip_callback(), dht_pk_callback(), and START_TEST().
#define NUM_LAST 37
Definition at line 310 of file onion_test.c.
Referenced by dht_ip_callback(), dht_pk_callback(), and START_TEST().
#define NUM_ONIONS 50
Definition at line 308 of file onion_test.c.
Referenced by START_TEST().
Function Documentation
void dht_ip_callback (void * object, int32_t number, IP_Port ip_port)
Definition at line 313 of file onion_test.c.
References first_ip, last_ip, NUM_FIRST, and NUM_LAST.
Referenced by dht_pk_callback().
{
    if (NUM_FIRST == number) {
        first_ip = 1;
        return;
    }
    if (NUM_LAST == number) {
        last_ip = 1;
        return;
    }
    ck_abort_msg("Error.");
}
static void dht_pk_callback (void * object, int32_t number, const uint8_t * dht_public_key) [static]
Definition at line 332 of file onion_test.c.
References ck_assert_msg(), Onion::dht, DHT_addfriend(), dht_ip_callback(), first, first_dht_pk, last, last_dht_pk, NUM_FIRST, NUM_LAST, and Onions::onion.
Referenced by START_TEST().
{
    Onions *on = object;
    uint16_t count = 0;
    int ret = DHT_addfriend(on->onion->dht, dht_public_key, &
      dht_ip_callback, object, number, &count);
    ck_assert_msg(count == 1, "Count not 1");
    ck_assert_msg(ret == 0, "DHT_addfriend() did not return 0");
    if (NUM_FIRST == number && !first) {
        first = 1;
        if (memcmp(dht_public_key, last_dht_pk, crypto_box_PUBLICKEYBYTES) != 0) {
            ck_abort_msg("Error wrong dht key.");
        }
        return;
    }
    if (NUM_LAST == number && !last) {
        last = 1;
        if (memcmp(dht_public_key, first_dht_pk, crypto_box_PUBLICKEYBYTES) != 0) {
            ck_abort_msg("Error wrong dht key.");
        }
        return;
    }
    ck_abort_msg("Error.");
}
void do_onion (Onion * onion)
Definition at line 26 of file onion_test.c.
References Onion::dht, do_DHT(), Onion::net, and networking_poll().
Referenced by START_TEST().
{
    networking_poll(onion->net);
    do_DHT(onion->dht);
}
void do_onions (Onions * on)
Definition at line 287 of file onion_test.c.
References Onion::dht, do_DHT(), do_onion_client(), Onion::net, networking_poll(), Onions::onion, and Onions::onion_c.
Referenced by START_TEST().
{
    networking_poll(on->onion->net);
    do_DHT(on->onion->dht);
    do_onion_client(on->onion_c);
}
static int handle_test_1 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 33 of file onion_test.c.
References handled_test_1, Onion::net, and send_onion_response().
Referenced by START_TEST().
{
    Onion *onion = object;
    if (memcmp(packet, "Install Gentoo", sizeof("Install Gentoo")) != 0)
        return 1;
    if (send_onion_response(onion->net, source, (uint8_t *)"install gentoo", sizeof("
      install gentoo"),
                            packet + sizeof("Install Gentoo")) == -1)
        return 1;
    handled_test_1 = 1;
    return 0;
}
static int handle_test_2 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 49 of file onion_test.c.
References handled_test_2.
Referenced by START_TEST().
{
    if (length != sizeof("install Gentoo"))
        return 1;
    if (memcmp(packet, (uint8_t *)"install gentoo", sizeof("install gentoo")) != 0)
        return 1;
    handled_test_2 = 1;
    return 0;
}
static int handle_test_3 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 75 of file onion_test.c.
References decrypt_data(), Onion::dht, handled_test_3, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH, sb_data, DHT::self_secret_key, test_3_ping_id, and test_3_pub_key.
Referenced by START_TEST().
{
    Onion *onion = object;
    if (length != (1 + crypto_box_NONCEBYTES +
      ONION_ANNOUNCE_SENDBACK_DATA_LENGTH + 1 + crypto_hash_sha256_BYTES +
                   crypto_box_MACBYTES))
        return 1;
    uint8_t plain[1 + crypto_hash_sha256_BYTES];
    //print_client_id(packet, length);
    int len = decrypt_data(test_3_pub_key, onion->dht->
      self_secret_key, packet + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
      ,
                           packet + 1 + ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
       + crypto_box_NONCEBYTES,
                           1 + crypto_hash_sha256_BYTES + crypto_box_MACBYTES, plain);
    if (len == -1)
        return 1;
    if (memcmp(packet + 1, sb_data, ONION_ANNOUNCE_SENDBACK_DATA_LENGTH
      ) != 0)
        return 1;
    memcpy(test_3_ping_id, plain + 1, crypto_hash_sha256_BYTES);
    //print_client_id(test_3_ping_id, sizeof(test_3_ping_id));
    handled_test_3 = 1;
    return 0;
}
static int handle_test_4 (void * object, IP_Port source, const uint8_t * packet, uint16_t length) [static]
Definition at line 104 of file onion_test.c.
References decrypt_data(), Onion::dht, handled_test_4, nonce, and DHT::self_secret_key.
Referenced by START_TEST().
{
    Onion *onion = object;
    if (length != (1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES + sizeof("Install gentoo") +
      crypto_box_MACBYTES))
        return 1;
    uint8_t plain[sizeof("Install gentoo")] = {0};
    if (memcmp(nonce, packet + 1, crypto_box_NONCEBYTES) != 0)
        return 1;
    int len = decrypt_data(packet + 1 + crypto_box_NONCEBYTES, onion->
      dht->self_secret_key, packet + 1,
                           packet + 1 + crypto_box_NONCEBYTES + crypto_box_PUBLICKEYBYTES, sizeof("Install
       gentoo") + crypto_box_MACBYTES, plain);
    if (len == -1)
        return 1;
    if (memcmp(plain, "Install gentoo", sizeof("Install gentoo")) != 0)
        return 1;
    handled_test_4 = 1;
    return 0;
}
void kill_onions (Onions * on)
Definition at line 294 of file onion_test.c.
References Onion_Client::c, Onion::dht, kill_DHT(), kill_net_crypto(), kill_networking(), kill_onion(), kill_onion_announce(), kill_onion_client(), DHT::net, Onions::onion, Onions::onion_a, and Onions::onion_c.
Referenced by START_TEST().
{
    Networking_Core *net = on->onion->dht->net;
    DHT *dht = on->onion->dht;
    Net_Crypto *c = on->onion_c->c;
    kill_onion_client(on->onion_c);
    kill_onion_announce(on->onion_a);
    kill_onion(on->onion);
    kill_net_crypto(c);
    kill_DHT(dht);
    kill_networking(net);
    free(on);
}
int main (int argc, char * argv[])
Definition at line 459 of file onion_test.c.
References onion_suite().
{
    srand((unsigned int) time(NULL));
    Suite *onion = onion_suite();
    SRunner *test_runner = srunner_create(onion);
    int number_failed = 0;
    srunner_run_all(test_runner, CK_NORMAL);
    number_failed = srunner_ntests_failed(test_runner);
    srunner_free(test_runner);
    return number_failed;
}
Onions* new_onions (uint16_t port)
Definition at line 269 of file onion_test.c.
References ip, IP::ip6, ip_init(), new_DHT(), new_net_crypto(), new_networking(), new_onion(), new_onion_announce(), new_onion_client(), Onions::onion, Onions::onion_a, Onions::onion_c, and IP6::uint8.
Referenced by START_TEST().
{
    IP ip;
    ip_init(&ip, 1);
    ip.ip6.uint8[15] = 1;
    Onions *on = malloc(sizeof(Onions));
    DHT *dht = new_DHT(new_networking(ip, port));
    on->onion = new_onion(dht);
    on->onion_a = new_onion_announce(dht);
    TCP_Proxy_Info inf = {0};
    on->onion_c = new_onion_client(new_net_crypto(dht, &inf));
    if (on->onion && on->onion_a && on->onion_c)
        return on;
    return NULL;
}
END_TEST Suite* onion_suite (void)
Definition at line 450 of file onion_test.c.
References DEFTESTCASE_SLOW.
Referenced by main().
{
    Suite *s = suite_create("Onion");
    DEFTESTCASE_SLOW(basic, 5);
    DEFTESTCASE_SLOW(announce, 70);
    return s;
}
START_TEST (test_basic)
Definition at line 129 of file onion_test.c.
References c_sleep, ck_assert_msg(), create_onion_path(), Onion::dht, do_onion(), Onion_Announce::entries, handle_test_1(), handle_test_2(), handle_test_3(), handle_test_4(), handled_test_1, handled_test_2, handled_test_3, handled_test_4, ip, IP::ip6, ip_init(), Node_format::ip_port, kill_DHT(), kill_networking(), kill_onion(), kill_onion_announce(), Onion::net, DHT::net, NET_PACKET_ANNOUNCE_RESPONSE, NET_PACKET_ONION_DATA_RESPONSE, networking_registerhandler(), new_DHT(), new_networking(), new_nonce(), new_onion(), new_onion_announce(), nonce, ONION_ANNOUNCE_MAX_ENTRIES, path, Networking_Core::port, Onion_Announce_Entry::public_key, make-funny-savefile::public_key, Node_format::public_key, sb_data, DHT::self_public_key, DHT::self_secret_key, send_announce_request(), send_data_request(), send_onion_packet(), test_3_ping_id, test_3_pub_key, Onion_Announce_Entry::time, IP6::uint8, and unix_time().
{
    IP ip;
    ip_init(&ip, 1);
    ip.ip6.uint8[15] = 1;
    Onion *onion1 = new_onion(new_DHT(new_networking(ip, 34567)));
    Onion *onion2 = new_onion(new_DHT(new_networking(ip, 34568)));
    ck_assert_msg((onion1 != NULL) && (onion2 != NULL), "Onion failed initializing.");
    networking_registerhandler(onion2->net, 'I', &
      handle_test_1, onion2);
    IP_Port on1 = {ip, onion1->net->port};
    Node_format n1;
    memcpy(n1.public_key, onion1->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    n1.ip_port = on1;
    IP_Port on2 = {ip, onion2->net->port};
    Node_format n2;
    memcpy(n2.public_key, onion2->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    n2.ip_port = on2;
    Node_format nodes[4];
    nodes[0] = n1;
    nodes[1] = n2;
    nodes[2] = n1;
    nodes[3] = n2;
    Onion_Path path;
    create_onion_path(onion1->dht, &path, nodes);
    int ret = send_onion_packet(onion1->net, &path, nodes[3].
      ip_port, (uint8_t *)"Install Gentoo",
                                sizeof("Install Gentoo"));
    ck_assert_msg(ret == 0, "Failed to create/send onion packet.");
    handled_test_1 = 0;
    while (handled_test_1 == 0) {
        do_onion(onion1);
        do_onion(onion2);
    }
    networking_registerhandler(onion1->net, 'i', &
      handle_test_2, onion1);
    handled_test_2 = 0;
    while (handled_test_2 == 0) {
        do_onion(onion1);
        do_onion(onion2);
    }
    Onion_Announce *onion1_a = new_onion_announce(onion1->
      dht);
    Onion_Announce *onion2_a = new_onion_announce(onion2->
      dht);
    networking_registerhandler(onion1->net,
      NET_PACKET_ANNOUNCE_RESPONSE, &handle_test_3, onion1);
    ck_assert_msg((onion1_a != NULL) && (onion2_a != NULL), "Onion_Announce failed
       initializing.");
    uint8_t zeroes[64] = {0};
    randombytes(sb_data, sizeof(sb_data));
    uint64_t s;
    memcpy(&s, sb_data, sizeof(uint64_t));
    memcpy(test_3_pub_key, nodes[3].public_key, crypto_box_PUBLICKEYBYTES);
    ret = send_announce_request(onion1->net, &path, nodes[3], onion1->
      dht->self_public_key,
                                onion1->dht->self_secret_key,
                                zeroes, onion1->dht->self_public_key, onion1->
      dht->self_public_key, s);
    ck_assert_msg(ret == 0, "Failed to create/send onion announce_request packet.");
    handled_test_3 = 0;
    while (handled_test_3 == 0) {
        do_onion(onion1);
        do_onion(onion2);
        c_sleep(50);
    }
    randombytes(sb_data, sizeof(sb_data));
    memcpy(&s, sb_data, sizeof(uint64_t));
    memcpy(onion2_a->entries[1].public_key, onion2->dht->
      self_public_key, crypto_box_PUBLICKEYBYTES);
    onion2_a->entries[1].time = unix_time();
    networking_registerhandler(onion1->net,
      NET_PACKET_ONION_DATA_RESPONSE, &handle_test_4, onion1);
    send_announce_request(onion1->net, &path, nodes[3], onion1->
      dht->self_public_key, onion1->dht->self_secret_key,
                          test_3_ping_id, onion1->dht->
      self_public_key, onion1->dht->self_public_key, s);
    while (memcmp(onion2_a->entries[ONION_ANNOUNCE_MAX_ENTRIES - 2].
      public_key, onion1->dht->self_public_key,
                  crypto_box_PUBLICKEYBYTES) != 0) {
        do_onion(onion1);
        do_onion(onion2);
        c_sleep(50);
    }
    c_sleep(1000);
    Onion *onion3 = new_onion(new_DHT(new_networking(ip, 34569)));
    ck_assert_msg((onion3 != NULL), "Onion failed initializing.");
    new_nonce(nonce);
    ret = send_data_request(onion3->net, &path, nodes[3].
      ip_port, onion1->dht->self_public_key,
                            onion1->dht->self_public_key,
                            nonce, (uint8_t *)"Install gentoo", sizeof("Install gentoo"));
    ck_assert_msg(ret == 0, "Failed to create/send onion data_request packet.");
    handled_test_4 = 0;
    while (handled_test_4 == 0) {
        do_onion(onion1);
        do_onion(onion2);
        c_sleep(50);
    }
    kill_onion_announce(onion1_a);
    kill_onion_announce(onion2_a);
    {
        Onion *onion = onion1;
        Networking_Core *net = onion->dht->net;
        DHT *dht = onion->dht;
        kill_onion(onion);
        kill_DHT(dht);
        kill_networking(net);
    }
    {
        Onion *onion = onion2;
        Networking_Core *net = onion->dht->net;
        DHT *dht = onion->dht;
        kill_onion(onion);
        kill_DHT(dht);
        kill_networking(net);
    }
    {
        Onion *onion = onion3;
        Networking_Core *net = onion->dht->net;
        DHT *dht = onion->dht;
        kill_onion(onion);
        kill_DHT(dht);
        kill_networking(net);
    }
}
START_TEST (test_announce)
Definition at line 363 of file onion_test.c.
References c_sleep, ck_assert_msg(), Onion::dht, DHT_bootstrap(), DHT_isconnected(), dht_pk_callback(), do_onions(), first, first_dht_pk, first_ip, i, ip, IP::ip6, ip_init(), kill_onions(), last, last_dht_pk, last_ip, Onion::net, new_onions(), NUM_FIRST, NUM_LAST, NUM_ONIONS, Onions::onion, onion_addfriend(), onion_dht_pk_callback(), onion_getfriendip(), IP_Port::port, Networking_Core::port, printf(), DHT::self_public_key, and IP6::uint8.
{
    uint32_t i, j;
    Onions *onions[NUM_ONIONS];
    for (i = 0; i < NUM_ONIONS; ++i) {
        onions[i] = new_onions(i + 34655);
        ck_assert_msg(onions[i] != 0, "Failed to create onions. %u");
    }
    IP ip;
    ip_init(&ip, 1);
    ip.ip6.uint8[15] = 1;
    for (i = 3; i < NUM_ONIONS; ++i) {
        IP_Port ip_port = {ip, onions[i - 1]->onion->net->port};
        DHT_bootstrap(onions[i]->onion->dht, ip_port, onions[i - 1]->
      onion->dht->self_public_key);
        IP_Port ip_port1 = {ip, onions[i - 2]->onion->net->port};
        DHT_bootstrap(onions[i]->onion->dht, ip_port1, onions[i - 2]->
      onion->dht->self_public_key);
        IP_Port ip_port2 = {ip, onions[i - 3]->onion->net->port};
        DHT_bootstrap(onions[i]->onion->dht, ip_port2, onions[i - 3]->
      onion->dht->self_public_key);
    }
    uint32_t connected = 0;
    while (connected != NUM_ONIONS) {
        connected = 0;
        for (i = 0; i < NUM_ONIONS; ++i) {
            do_onions(onions[i]);
            connected += DHT_isconnected(onions[i]->onion->dht);
        }
        c_sleep(50);
    }
    printf("connected\n");
    for (i = 0; i < 25 * 2; ++i) {
        for (j = 0; j < NUM_ONIONS; ++j) {
            do_onions(onions[j]);
        }
        c_sleep(50);
    }
    memcpy(first_dht_pk, onions[NUM_FIRST]->onion->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    memcpy(last_dht_pk, onions[NUM_LAST]->onion->dht->self_public_key,
      crypto_box_PUBLICKEYBYTES);
    printf("adding friend\n");
    int frnum_f = onion_addfriend(onions[NUM_FIRST]->onion_c, onions[
      NUM_LAST]->onion_c->c->self_public_key);
    int frnum = onion_addfriend(onions[NUM_LAST]->onion_c, onions[
      NUM_FIRST]->onion_c->c->self_public_key);
    onion_dht_pk_callback(onions[NUM_FIRST]->onion_c, frnum_f, &
      dht_pk_callback, onions[NUM_FIRST], NUM_FIRST);
    onion_dht_pk_callback(onions[NUM_LAST]->onion_c, frnum, &
      dht_pk_callback, onions[NUM_LAST], NUM_LAST);
    int ok = -1;
    IP_Port ip_port;
    while (!first || !last) {
        for (i = 0; i < NUM_ONIONS; ++i) {
            do_onions(onions[i]);
        }
        c_sleep(50);
    }
    printf("Waiting for ips\n");
    while (!first_ip || !last_ip) {
        for (i = 0; i < NUM_ONIONS; ++i) {
            do_onions(onions[i]);
        }
        c_sleep(50);
    }
    onion_getfriendip(onions[NUM_LAST]->onion_c, frnum, &ip_port);
    ck_assert_msg(ip_port.port == onions[NUM_FIRST]->
      onion->net->port, "Port in returned ip not correct.");
    for (i = 0; i < NUM_ONIONS; ++i) {
        kill_onions(onions[i]);
    }
}
Variable Documentation
_Bool first
Definition at line 328 of file onion_test.c.
Referenced by dht_pk_callback(), and START_TEST().
uint8_t first_dht_pk[crypto_box_PUBLICKEYBYTES]
Definition at line 329 of file onion_test.c.
Referenced by dht_pk_callback(), and START_TEST().
_Bool first_ip
Definition at line 312 of file onion_test.c.
Referenced by dht_ip_callback(), and START_TEST().
int handled_test_1 [static]
Definition at line 32 of file onion_test.c.
Referenced by handle_test_1(), and START_TEST().
int handled_test_2 [static]
Definition at line 48 of file onion_test.c.
Referenced by handle_test_2(), and START_TEST().
int handled_test_3 [static]
Definition at line 72 of file onion_test.c.
Referenced by handle_test_3(), and START_TEST().
int handled_test_4 [static]
Definition at line 103 of file onion_test.c.
Referenced by handle_test_4(), and START_TEST().
_Bool last
Definition at line 328 of file onion_test.c.
Referenced by dht_pk_callback(), dist_index_bubble(), onion_add_bs_path_node(), onion_add_path_node(), and START_TEST().
uint8_t last_dht_pk[crypto_box_PUBLICKEYBYTES]
Definition at line 330 of file onion_test.c.
Referenced by dht_pk_callback(), and START_TEST().
_Bool last_ip
Definition at line 312 of file onion_test.c.
Referenced by dht_ip_callback(), and START_TEST().
uint8_t nonce[crypto_box_NONCEBYTES]
Definition at line 102 of file onion_test.c.
Referenced by handle_test_4(), and START_TEST().
uint8_t sb_data[ONION_ANNOUNCE_SENDBACK_DATA_LENGTH]
Definition at line 71 of file onion_test.c.
Referenced by handle_test_3(), and START_TEST().
uint8_t test_3_ping_id[crypto_hash_sha256_BYTES]
Definition at line 74 of file onion_test.c.
Referenced by handle_test_3(), and START_TEST().
uint8_t test_3_pub_key[crypto_box_PUBLICKEYBYTES]
Definition at line 73 of file onion_test.c.
Referenced by handle_test_3(), and START_TEST().